initramfs/src/init/pkg/process/kubeadm.go
rootfs/.conform.yaml

fix(init): typo in service subnet field; pin version of Kubernetes

---

initramfs/src/init/Gopkg.lock
initramfs/src/init/main.go
initramfs/src/init/pkg/constants/constants.go
initramfs/src/init/pkg/kernel/kernel.go
initramfs/src/init/pkg/mount/mount.go
initramfs/src/init/pkg/userdata/userdata.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/.travis.yml
initramfs/src/init/vendor/gopkg.in/yaml.v2/LICENSE
initramfs/src/init/vendor/gopkg.in/yaml.v2/LICENSE.libyaml
initramfs/src/init/vendor/gopkg.in/yaml.v2/NOTICE
initramfs/src/init/vendor/gopkg.in/yaml.v2/README.md
initramfs/src/init/vendor/gopkg.in/yaml.v2/apic.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/decode.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/emitterc.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/encode.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/go.mod
initramfs/src/init/vendor/gopkg.in/yaml.v2/parserc.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/readerc.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/resolve.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/scannerc.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/sorter.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/writerc.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/yaml.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/yamlh.go
initramfs/src/init/vendor/gopkg.in/yaml.v2/yamlprivateh.go

This PR implements the basic logic to discover and download a user data YAML file.

feat(init): user data

---

rootfs/.conform.yaml

fix(rootfs): install conntrack

---

initramfs/src/init/pkg/process/crio.go

fix(init): don't create CRI-O CNI configurations

---

initramfs/src/init/pkg/process/kubeadm.go
kernel/src/linux/config

feat(*): enable IPVS

---

initramfs/src/init/main.go
initramfs/src/init/pkg/mount/cgroups/cgroups.go
initramfs/src/init/pkg/mount/mount.go
initramfs/src/init/pkg/switchroot/switchroot.go

fix(init): switch_root implementation

---

initramfs/src/init/main.go
initramfs/src/init/pkg/etc/etc.go
initramfs/src/init/pkg/rootfs/rootfs.go
initramfs/src/init/pkg/userdata/userdata.go
rootfs/.conform.yaml
rootfs/src/files/hosts
rootfs/src/files/resolv.conf

fix(*): generate /etc/hosts and /etc/resolv.conf

---

initramfs/src/init/pkg/mount/cgroups/cgroups.go

fix(init): enable hierarchical accounting and reclaim

---

.conform.yaml
generate/src/entrypoint.sh
packer.json

chore(*): build AMI

---

rootfs/.conform.yaml

feat(rootfs): install cut

---

src/initramfs/cmd/init/pkg/system/services/kubeadm.go

The only time we need admin.conf is when the joining node creates a control plane.

fix(init): node join

---

src/initramfs/.conform.yaml

Building xfsprogs before adding the soruce code will speed up builds.

chore: build xfsprogs before binaries

---

.conform.yaml
src/docs/.conform.yaml

The newest version of Conform now deletes the destination.

chore: update artifact destination

---

src/initramfs/cmd/init/main.go
src/initramfs/cmd/init/pkg/security/cis/cis.go
src/initramfs/cmd/init/pkg/system/services/blockd.go
src/initramfs/cmd/init/pkg/system/services/crt.go
src/initramfs/cmd/init/pkg/system/services/kubeadm.go
src/initramfs/cmd/init/pkg/system/services/kubelet.go
src/initramfs/cmd/init/pkg/system/services/osd.go
src/initramfs/cmd/osd/pkg/reg/reg.go
src/initramfs/pkg/userdata/userdata.go

feat: embed the kubeadm config

---

src/initramfs/pkg/blockdevice/blockdevice.go
src/initramfs/pkg/blockdevice/bockdevice_options.go
src/initramfs/pkg/blockdevice/table/gpt/gpt.go
src/initramfs/pkg/blockdevice/table/table.go

feat(initramfs): API for creating new partition tables

---

.conform.yaml
src/initramfs/cmd/init/pkg/mount/blkid/blkid.go
src/initramfs/cmd/init/pkg/mount/mount.go
src/initramfs/cmd/init/pkg/platform/baremetal/baremetal.go

Fixes an issue where the block devices were not detected properly.

fix(init): use the correct blkid lookup values

---

src/initramfs/cmd/init/pkg/rootfs/etc/etc.go

- DRY symlink creation for /etc/hosts and /etc/resolv.conf
- Fix bug with incorrect filename in error message

refactor(init): DRY symlink creation

---

.dockerignore
Dockerfile
Makefile
hack/scripts/cleanup.sh
hack/scripts/fhs.sh

feat: use musl libc

---

README.md

docs: improve the README

---

internal/pkg/grpc/tls/tls.go

feat: disable session tickets

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

chore: add CONTRIBUTING.md

---

CHANGELOG.md

chore: prepare v0.1.0-alpha.17 release

---

Makefile

Follow up on previous PR #338
- suppress output from docker commands to test for buildkit container
- add sleep to ensure buildkit has enough time to startup
- change target for all to ci instead of individual buildkit steps

fix: Minor adjustments to makefile

---

.conform.yaml

chore: remove GPG requirement

---

README.md

docs: add kubeadm mention in README

---

CHANGELOG.md

chore: prepare v0.1.0-alpha.18 release

---

internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/cloud/aws/aws.go
internal/app/init/internal/platform/cloud/vmware/vmware.go
internal/app/init/internal/platform/platform.go
internal/app/init/internal/rootfs/rootfs.go
internal/app/init/main.go
internal/pkg/userdata/userdata.go

refactor: Make userdata.Open userdata.Download consistent return types

---

internal/pkg/userdata/userdata.go

fix: Adding initialization for userdata download

---

Dockerfile

fix: add iptables to rootfs

---

.travis.yml

chore: fix Travis double builds

---

internal/app/init/main.go

fix: ensure DNS works in early boot

---

README.md

docs: add comparison to similar distributions

---

README.md

docs: add contact info to README

---

Makefile

chore: fix installer image name

---

Dockerfile
go.mod
go.sum

feat: upgrade containerd to v1.2.4

---

Makefile

feat: upgrade musl to 1.1.21

---

Makefile

feat: upgrade linux to v4.19.23

---

README.md

docs: add Twitter badge to README

---

internal/app/osctl/cmd/config.go
internal/app/osctl/cmd/dmesg.go
internal/app/osctl/cmd/kubeconfig.go
internal/app/osctl/cmd/logs.go
internal/app/osctl/cmd/ps.go
internal/app/osctl/cmd/reboot.go
internal/app/osctl/cmd/reset.go
internal/app/osctl/cmd/restart.go
internal/app/osctl/cmd/root.go
internal/app/osctl/cmd/routes.go
internal/app/osctl/cmd/stats.go
internal/app/osctl/cmd/version.go
internal/app/osctl/internal/client/client.go
internal/app/osctl/internal/client/config/config.go

feat: add config flag to osctl

---

internal/app/osctl/cmd/config.go
internal/app/osctl/internal/client/config/config.go

fix: write config changes to specified config file

---

CONTRIBUTING.md

Signed-off-by: Tim Jones <timniverse@gmail.com>
fixes #393

docs: improve contibuting documentation

---

internal/app/osctl/cmd/root.go
internal/pkg/constants/constants.go

feat: add TALOSCONFIG env var

---

internal/app/proxyd/internal/frontend/frontend.go
internal/pkg/net/net.go
internal/pkg/userdata/userdata.go

feat: create certificates with all non-loopback addresses

---

internal/app/init/internal/rootfs/rootfs.go
internal/pkg/grpc/gen/gen.go
internal/pkg/userdata/userdata.go

feat: allow user specified IP addresses in SANs

---

internal/app/init/pkg/system/services/kubeadm.go
internal/pkg/grpc/gen/gen.go

fix: distribute PKI from initial master to joining masters

---

go.mod
go.sum
hack/installer/entrypoint.sh
internal/app/init/internal/rootfs/etc/etc.go
internal/app/init/main.go
internal/app/init/pkg/network/network.go

This PR is mostly the changes from #417, with a few logging and interface interaction changes, as well as using our forked dhcp library. We should close #417 and keep this one.

feat: add DHCP client

---

CONTRIBUTING.md

chore: fix git commit hook

---

internal/app/init/pkg/network/network.go

Signed-off-by: Tim Jones <timniverse@gmail.com>

fix: fallback on IP address when DHCP reply has no hostname

---

internal/app/osctl/cmd/config.go

fix: assign to existing target variable

---

internal/pkg/install/install.go

When the previous changes went in for the Install() func, we download to the appropriate destination and return the sourceFile as the downloaded file. Since the sourceFile is the actual file and not an archive, it triggers the second match in the switch statement.
Because we dont have a destFile defined, we get a fun seg fault.

fix(initramfs): Fix case where we download a non archive file

---

internal/app/init/pkg/system/services/blockd.go
internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go

fix: add missing mounts and remove memory limits

---

Dockerfile
hack/installer/entrypoint.sh

chore: create images that consider the size of /var

---

.conform.yaml
LICENSE_HEADER
Makefile
README.md

chore: upgrade conform

---

Dockerfile
internal/pkg/blockdevice/filesystem/vfat/options.go
internal/pkg/blockdevice/filesystem/vfat/vfat.go

feat: add dosfstools to initramfs and rootfs

---

internal/app/init/internal/rootfs/mount/mount.go

fix: mount /dev/shm as tmpfs

---

internal/app/init/main.go

feat: log to stdout when in container mode

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.19

---

internal/app/init/main.go
internal/app/init/pkg/network/network.go

feat(initramfs): Add support for refreshing dhcp lease

---

Dockerfile

Prep for installing bootloader

feat: Adding gpt.mbr to initramfs

---

internal/app/init/internal/security/cis/cis.go

feat: remove DenyEscalatingExec admission plugin

---

Dockerfile
internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/rootfs/mount/mount.go
internal/app/osinstall/cmd/install.go
internal/pkg/blockdevice/bootloader/bootloader.go
internal/pkg/blockdevice/bootloader/syslinux/syslinux.go
internal/pkg/blockdevice/filesystem/vfat/superblock.go
internal/pkg/blockdevice/filesystem/vfat/vfat.go
internal/pkg/blockdevice/table/gpt/gpt.go
internal/pkg/blockdevice/table/gpt/partition/options.go
internal/pkg/install/install.go
internal/pkg/install/prepare.go
internal/pkg/kernel/kernel.go

feat: install bootloader to block device

---

Dockerfile
Makefile
go.mod
go.sum
internal/app/init/main.go
internal/app/init/pkg/network/network.go
internal/app/init/pkg/system/services/ntpd.go
internal/app/ntpd/main.go
internal/pkg/userdata/userdata.go

Closes https://github.com/autonomy/talos/issues/279

feat: Adding basic ntp implementation

---

internal/app/init/pkg/system/services/kubelet.go

refactor(initramfs): Verify shared mounts with kubelet

---

Dockerfile
go.mod
go.sum

feat: upgrade containerd to v1.2.5

---

Makefile

feat: upgrade Linux to v4.19.31

---

Dockerfile

feat: upgrade runc to v1.0.0-rc.7

---

Dockerfile

fix: revert runc to v1.0.0-rc.6

---

internal/app/init/internal/platform/cloud/packet/packet.go
internal/app/init/internal/platform/platform.go

feat: add packet support

---

internal/pkg/blockdevice/blockdevice.go
internal/pkg/blockdevice/filesystem/xfs/xfs.go
internal/pkg/blockdevice/table/gpt/gpt.go
internal/pkg/install/install.go
internal/pkg/install/mount.go
internal/pkg/install/prepare.go
internal/pkg/userdata/userdata.go
internal/pkg/userdata/userdata_test.go

refactor: improve installer code

---

internal/pkg/userdata/userdata.go
internal/pkg/userdata/userdata_test.go

Eliminate two extra copies of `Kubeadm` struct by using type aliases and
"shadow" fields which are not marshalled to YAML. Having three copies of
the same structure is going to lead to mistakes when they get out of
sync.

chore: DRY userdata Kubeadm struct marshal/unmarshal

---

internal/app/osctl/cmd/config.go
internal/app/osctl/cmd/dmesg.go
internal/app/osctl/cmd/inject.go
internal/app/osctl/cmd/kubeconfig.go
internal/app/osctl/cmd/logs.go
internal/app/osctl/cmd/ps.go
internal/app/osctl/cmd/reboot.go
internal/app/osctl/cmd/reset.go
internal/app/osctl/cmd/root.go
internal/app/osctl/cmd/routes.go
internal/app/osctl/cmd/stats.go
internal/app/osctl/cmd/version.go

This is continuation of work from PR #467

chore: report errors in osctl cli in a consistent way

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.20

---

cmd/osctl/cmd/config.go

fix(osctl): add missing flags

---

go.mod
go.sum

chore: upgrade DHCP package

---

hack/installer/entrypoint.sh
internal/app/init/internal/rootfs/etc/etc.go
internal/pkg/blockdevice/bootloader/syslinux/syslinux.go

chore: remove 'Autonomy' from os-release

---

.gitignore
Makefile

chore: remove static images directory

---

README.md

chore: fix Twitter badge

---

hack/dev/Makefile
hack/dev/docker-compose.yaml

chore: switch back docker image org name to 'autonomy'

---

internal/app/init/pkg/system/services/kubeadm.go

That's what kubeadm expects to see as `--certificate-key`:
https://github.com/kubernetes/kubernetes/blob/50bf223a0545a121dc202de8fad673402b8ebde6/cmd/kubeadm/app/constants/constants.go#L198-L199

chore: sha256() provided certificateKey to make it 32 bytes

---

internal/app/init/internal/rootfs/rootfs.go
internal/pkg/constants/constants.go

fix: remove static resolv.conf

---

Dockerfile
Makefile
hack/dev/Makefile
hack/installer/entrypoint.sh

chore: add release target to Makefile

---

internal/app/init/pkg/system/runner/process/process.go

Signficant change is going from `cmd.Process.Wait()` to `cmd.Wait()`,
the reason is that looks like `cmd.Wait()` does some stuff besides
waiting for the process to exit:
```
Wait waits for the command to exit and waits for any copying to
stdin or copying from stdout or stderr to complete.
...
The returned error is nil if the command runs, has no problems copying
stdin, stdout, and stderr, and exits with a zero exit status.
...
Wait releases any resources associated with the Cmd.
```
This replaces potentially infinite recursison with explicit loop.
I want to add unit-test for this code, but that requires adding 'Stop()'
method which requires even more refactoring, so I didn't want to go that
route so that diff is manageable. I will get unit-test done as the next
step.
Signed-off-by: Andrey …

chore: refactor and dry up process runner

---

internal/app/init/main.go
internal/app/init/pkg/network/network.go
pkg/userdata/userdata.go

feat: Expand network configuration support

---

internal/app/init/pkg/network/network.go

fix: check link state before bringing it up

---

Makefile

chore: run lint and test first

---

Makefile

fix: create GCE disk as disk.raw

---

Makefile
hack/installer/packer.json

refactor: improve artifact names

---

Makefile

See https://github.com/talos-systems/kernel/pull/10

chore: export vmlinux kernel

---

internal/app/init/pkg/system/runner/process/log/log.go

1. No need to allocate sync.Mutex, simple variable is just fine.
2. Protect every access to the map with mutex, as otherwise it would be
a data race.
3. Remove log from instance variable when log is closed. I haven't seen
logs being closed, but if we have method implemented, it's better if
it's correct.

chore: fixups for ProcessLog

---

hack/dev/Makefile
hack/dev/docker-compose.yaml
hack/dev/enter.sh

chore: add container for development

---

hack/dev/docker-compose.yaml

chore: add /var/log as a volume to docker platform

---

.travis.yml
hack/dev/Makefile
hack/dev/integration.sh

chore: add basic integration test

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.21

---

internal/app/init/pkg/network/static.go
pkg/userdata/userdata.go

This allows us to define the private network for packet

feat(initramfs): Add support for specifying static routes

---

Dockerfile
cmd/osctl/pkg/client/client.go
hack/golang/golangci-lint.yaml
internal/app/init/pkg/system/services/kubeadm.go
internal/app/ntpd/main.go
internal/app/udevd/internal/drivers/scsi/scsi.go
internal/pkg/blockdevice/table/gpt/partition/options.go
internal/pkg/grpc/tls/tls.go
internal/pkg/mount/mount.go
pkg/userdata/userdata.go

chore: upgrade golangci-lint to v1.16.0

---

README.md

chore: add goreportcard badge

---

internal/app/init/shutdown.go

:wave: Hello! I was browsing through some code that makes use of my packages, and I came across this file. I've applied a couple of fixes here:
- remove use of redundant generic netlink connection; the existing connection should work fine
- netlink.IsNotExist should be used because the netlink package produces `*netlink.OpError` types, see https://godoc.org/github.com/mdlayher/genetlink#Conn.GetFamily
I hope this is useful, and thanks for your time.

fix: remove redundant netlink connection, use netlink.IsNotExist in init

---

README.md

docs: refer to talos as an operating system

---

internal/app/init/pkg/system/runner/containerd/import.go

Inner function in goroutine was using `err` (return variable) of the
outer function.

chore: clean up outer variable used in inner func

---

.drone.yml
.travis.yml
Dockerfile
Makefile
hack/dev/kubectl.sh
hack/dev/osctl.sh

chore: add drone build

---

.drone.yml
Makefile

chore: push images for master branch

---

.drone.yml

chore: fix push step

---

Dockerfile
Makefile

chore: create /lib/modules

---

hack/scripts/symlink.sh

chore: don't crate /lib/modules in  symlink.sh

---

internal/app/init/internal/rootfs/mount/mount.go
internal/app/init/main.go
internal/app/init/pkg/system/services/kubelet.go
internal/pkg/install/prepare.go
pkg/userdata/userdata.go

feat: add support for extra disk management

---

Makefile

feat: upgrade Linux to v4.19.34

---

Dockerfile
go.mod
go.sum

feat: upgrade containerd to v1.2.6

---

.drone.yml

chore: push images for all branches

---

internal/app/init/internal/rootfs/mount/mount.go

feat: log the xfs_growfs of the data partition

---

.drone.yml
.gitignore
Makefile

chore: add github-release plugin

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.22

---

.drone.yml

chore: add BUILDKIT_HOST env var to release step

---

.drone.yml

chore: fetch git tags

---

.drone.yml

chore: improve drone parallel steps

---

Makefile
hack/dev/Makefile

chore: use gitmeta for image tag

---

.drone.yml

chore: optimize the build for pull requests and tags

---

.drone.yml
Makefile

chore: remove raw device outputs from release

---

Makefile

chore: remove modules from build output

---

.drone.yml
.gitignore

chore: ignore checksum files create in release

---

README.md

docs: update README.md with drone build status

---

internal/app/init/pkg/system/runner/containerd/containerd_test.go

Just because we can easily do that, this also covers prior work
on converting panics to errors: #518

refactor: add unit-test for containerd image import

---

README.md

chore: add slack invite badge

---

internal/pkg/blockdevice/blockdevice.go
internal/pkg/blockdevice/probe/probe.go
internal/pkg/install/detect.go
internal/pkg/install/install.go
internal/pkg/install/prepare.go

feat: detect if an install has already occurred

---

Makefile

chore: Update kernel image

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.23

---

cmd/osctl/cmd/df.go
cmd/osctl/pkg/client/client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

feat(osctl): add df command

---

cmd/osctl/cmd/shutdown.go
cmd/osctl/pkg/client/client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

feat: add shutdown command

---

pkg/userdata/generate/admin.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/init.go
pkg/userdata/generate/userdata.go
pkg/userdata/generate/userdata_test.go
pkg/userdata/generate/worker.go

feat: add package for generating userdata

---

hack/dev/integration.sh

chore(ci): apply manifests and wait for health nodes

---

internal/app/init/main.go

feat(init): load only the images required by the node type

---

.codecov.yml

chore: add codecov configuration file

---

.codecov.yml

chore: disable codecov patch status

---

.drone.yml

chore: add slack notification to drone

---

.conform.yaml
internal/app/init/pkg/system/services/kubeadm.go
internal/app/trustd/main.go
internal/pkg/grpc/gen/gen.go
internal/pkg/grpc/middleware/auth/basic/basic.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/init.go
pkg/userdata/generate/join.go
pkg/userdata/userdata.go

feat(trustd): use a token instead of username and password

---

internal/app/init/internal/security/kspp/kspp.go
internal/app/init/main.go

feat(init): enforce KSPP kernel parameters

---

docs/proposals/YYYYMMDD-TEMPLATE.md

chore: add proposals template

---

.drone.yml
Makefile

chore(ci): Update buildkit v0.5

---

internal/app/init/main.go
internal/app/init/pkg/network/dhcp.go
internal/pkg/constants/constants.go

feat(init): Add support for hostname kernel parameter

---

Makefile
README.md
cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/cluster/pkg/node/node.go
go.mod
hack/test/integration.sh
pkg/userdata/generate/init.go

feat(osctl): expose osd and api server ports on master-1

---

go.mod
internal/pkg/chunker/file/file.go

fix(osd): read log files only on write events

---

cmd/osctl/cmd/cluster.go
go.mod

fix(osctl): fix issue with downloading image

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.24

---

cmd/osctl/cmd/cluster.go

fix(osctl): ensure image is present

---

README.md

chore: update example outputs in README

---

Dockerfile
Makefile
internal/app/init/main.go
internal/app/init/pkg/system/services/udevd.go

feat(init): run udevd as a container

---

Makefile

chore: add make target for building AMIs

---

hack/installer/packer.json

chore: fix install command in packer template

---

.codecov.yml

chore: update codecov project theshold to 17%

---

Makefile
hack/installer/entrypoint.sh
internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/iso/iso.go
internal/app/init/internal/platform/platform.go
internal/pkg/blockdevice/blockdevice.go
internal/pkg/blockdevice/probe/probe.go
internal/pkg/constants/constants.go
internal/pkg/install/install.go

feat: add support for ISO based installations

---

cmd/osctl/cmd/config.go

feat(osctl): add config generate command

---

pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/init.go
pkg/userdata/userdata_test.go

chore: Fix kubeadm warnings

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.25

---

hack/installer/entrypoint.sh
internal/app/init/internal/rootfs/mount/mount.go
internal/pkg/constants/constants.go
internal/pkg/install/mount.go
internal/pkg/install/prepare.go

feat: update partition layout to accomodate upgrades

---

cmd/osctl/cmd/cluster.go

feat(osctl): add flag for number of workers to create

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
cmd/osctl/pkg/client/config/config.go
pkg/userdata/userdata.go

fix(osctl): output talosconfig on generate

---

Makefile

feat: upgrade Linux to v4.19.40

---

internal/pkg/kubernetes/kubernetes.go

feat: add helper package for cordon and drain

---

internal/app/init/internal/platform/platform.go

feat: remove EC2 verification step

---

go.mod
internal/pkg/install/install.go
internal/pkg/install/prepare.go
internal/pkg/install/prepare_test.go

refactor(initramfs): Compose Install better

---

pkg/userdata/services.go
pkg/userdata/services_test.go
pkg/userdata/userdata.go

fix: allow no trustd endpoints to be specified

---

.drone.yml
Makefile
hack/installer/packer.json

chore: publish AMIs on tags

---

.drone.yml

chore: add env vars required for AMI publishing

---

.drone.yml

chore: set PACKER_LOG=1 in AMI build

---

cmd/osctl/cmd/top.go

- disable word wrap ( prevent uber long commands from screwing up output )
- move topOutput to be called directly by draw ( no reason for it to be externally called and I think this was the cause for random exits )
- fix up output/confusion around proc.Command/proc.Args/proc.Executable ( make output useful )

fix(osctl): Fix formatting of command/args to be useful

---

hack/installer/entrypoint.sh
internal/pkg/blockdevice/bootloader/bootloader.go
internal/pkg/blockdevice/bootloader/syslinux/syslinux.go
internal/pkg/install/install.go
internal/pkg/install/prepare.go
internal/pkg/install/prepare_test.go

feat: add ability to create multiple entries in extlinux.conf

---

hack/installer/entrypoint.sh

chore: fix creation of syslinux config file

---

internal/pkg/grpc/factory/factory.go

fix(init): unlink unix bind address

---

cmd/osctl/pkg/client/client.go

fix(osctl): Fix panic on osctl df if error is returned

---

internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/cloud/packet/packet.go
internal/app/init/internal/platform/cloud/vmware/vmware.go
internal/app/init/internal/platform/iso/iso.go
internal/app/init/internal/platform/platform.go
internal/app/init/internal/security/kspp/kspp.go
internal/app/init/main.go
internal/app/init/pkg/network/dhcp.go
internal/pkg/constants/constants.go
internal/pkg/kernel/kernel.go
internal/pkg/kernel/kernel_test.go

feat: improve package for /proc/cmdline parsing and management

---

Makefile
hack/installer/entrypoint.sh
internal/pkg/blockdevice/bootloader/syslinux/syslinux.go
internal/pkg/install/install.go

feat: add support for UEFI

---

internal/pkg/kernel/kernel_test.go

test: add another test case for setting kernel params

---

cmd/osctl/cmd/root.go
cmd/osctl/cmd/upgrade.go
cmd/osctl/cmd/upgrade_darwin.go
cmd/osctl/cmd/upgrade_linux.go
cmd/osctl/pkg/client/client.go
go.mod
go.sum
internal/app/init/internal/reg/reg.go
internal/app/init/proto/api.proto
internal/app/osd/internal/reg/init_client.go
internal/app/osd/proto/api.proto
internal/pkg/constants/constants.go
internal/pkg/upgrade/upgrade.go

feat(init): Add upgrade endpoint

---

.drone.yml

chore: remove AMI publish step

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.26

---

Dockerfile
Makefile
cmd/osctl/cmd/install_linux.go
hack/installer/entrypoint.sh
hack/installer/packer.json
internal/pkg/blockdevice/probe/probe.go
internal/pkg/blockdevice/util/util.go
internal/pkg/blockdevice/util/util_test.go
internal/pkg/install/install.go
internal/pkg/install/mount.go
internal/pkg/install/prepare.go
internal/pkg/kernel/kernel.go

feat: use osctl in installer

---

internal/app/init/internal/rootfs/mount/mount.go
internal/app/init/pkg/system/services/kubelet.go

fix(init): mount /sys into kubelet container

---

internal/app/osd/internal/reg/reg.go

fix(osd): Read talos service logs from file

---

pkg/userdata/generate/controlplane.go
pkg/userdata/generate/init.go
pkg/userdata/generate/join.go
pkg/userdata/kubeadm.go

fix(osctl): output config without localAPIEndpoint

---

cmd/osctl/cmd/service.go

feat: add plural alias of service command

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.27

---

cmd/osctl/cmd/gen.go
cmd/osctl/cmd/inject.go
hack/dev/Makefile
hack/dev/gen.sh
hack/dev/userdata/.master-1.tpl.yaml
hack/dev/userdata/.master-3.tpl.yaml
internal/app/init/internal/rootfs/rootfs.go
internal/app/init/main.go
internal/app/init/pkg/system/services/kubeadm.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/init.go
pkg/userdata/kubeadm.go
pkg/userdata/token/token.go
pkg/userdata/userdata.go
pkg/userdata/userdata_test.go

feat(init): Add bootstrapToken parameter to userdata

---

internal/app/osd/internal/reg/reg.go

fix(osd): Sanitize request.id for log streams

---

README.md

docs: add Zoom meeting schedule to README

---

README.md

docs: change meeting times to 24 hour format

---

cmd/osctl/cmd/cluster.go
hack/dev/gen.sh
hack/dev/userdata/.master-1.tpl.yaml
hack/dev/userdata/.master-2.tpl.yaml
hack/dev/userdata/.master-3.tpl.yaml
internal/app/init/internal/security/cis/cis.go
internal/app/init/pkg/system/mocks_test.go
internal/app/init/pkg/system/service.go
internal/app/init/pkg/system/service_runner.go
internal/app/init/pkg/system/services/containerd.go
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubeadm/kubeadm.go
internal/app/init/pkg/system/services/kubeadm/system_test.go
internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/ntpd.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go
internal/app/init/pkg/system/services/udevd.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/generate_test.go
pkg/userdata/generate/init.go

refactor(init): Allow kubeadm init on controlplane

---

hack/test/integration.sh

This PR ensures that we have 3 master nodes

chore: improve the basic integration test

---

cmd/osctl/cmd/config.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/init.go

fix(osctl): Generate correct config with master IPs

---

internal/app/init/main.go

feat(init): Prioritize usage of local userdata

---

internal/app/init/pkg/system/service_runner.go

This fixes a race condition when kubeadm doesn't start waiting for
networkd forever.
If one service enters 'Waiting' state after another service already
finishes running, we should consider 'Finished' service to be 'up' in
the sense it has finished successfully (vs. 'Failed' state which is not
'up').

fix(init): consider 'finished' services to be 'up'

---

Makefile
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go
internal/pkg/constants/constants.go

feat: upgrade Kubernetes to v1.15.0-beta.1

---

pkg/userdata/generate/controlplane.go
pkg/userdata/generate/init.go
pkg/userdata/generate/join.go
pkg/userdata/generate/talosconfig.go

Need to test this in gce/aws, but wanted to get it out there before I lose train of thought.

fix: ensure shebang at top of userdata

---

internal/app/init/pkg/system/service_runner.go

refactor(init): use 'switch' instead of long condition

---

cmd/osctl/cmd/cluster.go
hack/dev/Makefile
hack/dev/userdata/.master-1.tpl.yaml
hack/dev/userdata/.master-2.tpl.yaml
hack/dev/userdata/.master-3.tpl.yaml
hack/dev/userdata/.worker.tpl.yaml
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubeadm/kubeadm.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/init.go
pkg/userdata/generate/join.go
pkg/userdata/kubeadm.go

feat(init): Add support for control plane join config

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.28

---

internal/app/init/pkg/system/system.go
internal/app/init/pkg/system/system_test.go

feat(init): Add support for stopping individual services

---

Makefile

chore: download official gitmeta to BINDIR

---

internal/app/init/internal/reg/reg.go
internal/app/init/pkg/system/system.go
internal/app/init/pkg/system/system_test.go
internal/app/init/proto/api.proto

 feat(init): Add service stop api

---

.drone.yml
Makefile

fix: Add gitmeta as dependency for push

---

internal/app/init/internal/reg/reg.go
internal/app/init/pkg/system/system.go
internal/pkg/upgrade/upgrade.go

feat(init): Add support for kubeadm reset during upgrade 

---

cmd/osctl/cmd/ls.go
cmd/osctl/pkg/client/client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

Implement an API for remote directory listing

API for remote `ls`

---

.conform.yaml
internal/app/proxyd/internal/frontend/frontend.go

fix(proxyd): Fix backend deletion

---

README.md

chore: add google group to readme

---

internal/app/init/pkg/system/runner/containerd/containerd_test.go

This should be no-op but allows to depend less on timing for concurrent
operations.

chore: improve test stability for containerd tests

---

internal/pkg/containers/containers_test.go

fix: containers test by locking image to specific tag

---

.drone.yml
.gitignore
Makefile
hack/test/e2e.sh
hack/test/manifests/capi-secrets.yaml
hack/test/osctl-docker-create.sh

feat(ci): enable nightly e2e tests

---

pkg/userdata/generate/controlplane.go
pkg/userdata/generate/init.go

fix: we don't need no stinkin' localapiendpoint

---

Dockerfile
cmd/osctl/cmd/root.go

refactor(osctl): use UserHomeDir to detect user home directory

---

.drone.yml

chore: fix drone make command for basic and E2E integration tests

---

.drone.yml

chore: disable e2e

---

docs/content/components/_index.md
docs/content/components/init.md
docs/content/components/kernel.md
docs/content/components/trustd.md
docs/content/components/udevd.md
docs/content/configuration/masters.md
docs/content/configuration/osd.md
docs/content/configuration/userdata.md
docs/content/configuration/workers.md
docs/content/guides/bare_metal.md
docs/content/guides/gcloud.md
docs/content/guides/getting_started.md
docs/content/guides/kvm.md
docs/content/guides/xen.md
docs/content/talos.md

docs: bring in missing changes from docs repo

---

docs/content/guides/gcp.md

docs: rename Google Cloud to GCP

---

docs/content/guides/getting_started.md

docs: refresh getting started guide

---

README.md
docs/content/community/index.md
docs/content/components/_index.md
docs/content/configuration/_index.md
docs/content/guides/_index.md
docs/content/talos.md

docs: improve description and layout

---

docs/content/talos.md

docs: update menu

---

internal/app/proxyd/internal/frontend/frontend.go

Prevent proxyd from getting in a loop of proxying to itself

fix(proxyd): Use local apiserver endpoint

---

hack/dev/docker-compose.yaml

fix: update hack/dev for new userdata location

---

docs/content/community/index.md

docs: fix the everytimezone.com link

---

internal/app/proxyd/internal/frontend/frontend.go

fix(proxyd): remove self-hosted label in listwatch

---

internal/app/init/pkg/system/services/udevd.go

feat: enable debug in udevd service

---

docs/content/components/_index.md
docs/content/configuration/_index.md
docs/content/guides/_index.md

fix: top-level docs now appear properly with sidebar

---

docs/content/talos.md
docs/content/use_cases/_index.md
docs/content/use_cases/edge.md
docs/content/use_cases/multi-cloud.md
docs/content/use_cases/serverless.md

docs: add use cases section

---

docs/content/guides/getting_started.md

docs: update getting started guide

---

internal/app/proxyd/internal/frontend/frontend.go

 fix(proxyd): Add support for dropping broken backends

---

CHANGELOG.md

chore: prepare release v0.1.0-beta.0

---

.drone.yml
.github/main.workflow

chore: add GitHub action to enforce conform policies

---

.github/main.workflow

chore: fix GitHub action

---

.github/main.workflow

chore: use pull_request event for GitHub action

---

.github/main.workflow

chore: upgrade conform to v0.1.0-alpha.13

---

.drone.yml
Makefile

(cherry picked from commit c29e5aec938522987781008af6b0f7136d1364c4)

chore: publish gce images with releases (#809)

---

CHANGELOG.md

chore: prepare release v0.1.0-beta.1

---

CHANGELOG.md

(cherry picked from commit 4d9de739ac9d066b28a9df5dbaa290005d1feae9)

chore: fix CHANGELOG (#814)

---

cmd/osctl/cmd/install_linux.go
internal/pkg/blockdevice/probe/probe.go
internal/pkg/install/detect.go
internal/pkg/install/install.go
internal/pkg/install/mount.go
internal/pkg/install/prepare.go

fix: probe specified install device

---

cmd/osctl/cmd/install_linux.go
internal/pkg/blockdevice/probe/probe.go
internal/pkg/install/detect.go
internal/pkg/install/install.go
internal/pkg/install/mount.go
internal/pkg/install/prepare.go

(cherry picked from commit cca60ed1219b07d8c8d52f68053609412bd6b14a)

fix: probe specified install device (#818)

---

.github/main.workflow

chore: upgrade conform to v0.1.0-alpha.14

---

.drone.yml
.gitignore
Makefile
hack/golang/test.sh
hack/test/basic-integration.sh
hack/test/osctl-cluster-create.sh

chore: fix GCE image creation

---

.drone.yml
.gitignore
Makefile
hack/golang/test.sh
hack/test/basic-integration.sh
hack/test/osctl-cluster-create.sh

This reverts commit 11f8392e53986da6c124037ffab06064ec04aedd.

chore: revert #816

---

.drone.yml

(cherry picked from commit 105226f5a05e897a66a4f7087b9280688d3c4445)

chore: fix GCE image creation (#830)

---

CHANGELOG-0.1.md

(cherry picked from commit 3914e4052abace6a4ccc705e92b422b2bb3b639b)

chore: fix CHANGELOGs (#834)

---

Makefile

See PR https://github.com/talos-systems/gitmeta/pull/10,
talos-systems/gitmeta#12

chore: use 'fast' gitmeta

---

.github/main.workflow

This version of conform fixes a few message format errors that were confusing when a policy was violated.

chore: upgrade conform to v0.1.0-alpha.16

---

CHANGELOG-0.2.md

chore: prepare release v0.2.0-alpha.1

---

.drone.yml
Dockerfile
Makefile

feat: Use individual component steps for drone

---

Dockerfile
Makefile

This kernel update brings in:
- modules support
- BPF support
- Azure support

feat: update kernel

---

CHANGELOG-0.2.md

Details can be found in the CHANGELOG.

chore: prepare release v0.2.0-alpha.2

---

cmd/osctl/cmd/install_linux.go
hack/installer/entrypoint.sh
internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/cloud/packet/packet.go
internal/app/init/internal/platform/iso/iso.go
internal/pkg/kernel/kernel.go

fix: Fix integration of extra kernel args

---

Makefile
internal/app/init/internal/platform/cloud/azure/azure.go
internal/app/init/internal/platform/cloud/azure/azure_test.go
internal/app/init/internal/platform/cloud/azure/register.go
internal/app/init/internal/platform/platform.go

feat(init): Add azure as a supported platform

---

internal/pkg/rootfs/rootfs.go

In order to accomodate the various ways that SSL certs are managed by
the different Linux distros, kubeadm creates control plane compoents
with volume mounts of the type DirectoryOrCreate to all well known SSL
cert locations. This change creates symlinks to /etc/ss/certs at all the
well known paths to account for the fact that the rootfs is read-only.

fix: create symlinks to /etc/ssl/certs

---

CHANGELOG-0.1.md

This commit updates the CHANGELOG.

chore: prepare release v0.1.0-rc.0

---

internal/pkg/network/setup.go
internal/pkg/network/setup_single.go
pkg/userdata/networking.go

This PR is needed so we can specify an MTU of 1460 for GCE VMs

feat: allow mtu specification for network devices

---

CONTRIBUTING.md
README.md
docs/content/components/osctl.md
docs/content/configuration/masters.md
docs/content/configuration/userdata.md
docs/content/guides/getting_started.md
docs/content/talos.md

Minor spelling corrections.
Signed-off-by: Matt Welch <matt.welch@gmail.com>

docs: minor spelling corrections.

---

CHANGELOG-0.2.md

Please see the CHANGELOG for a list of changes.

chore: prepare v0.2.0-alpha.3 release

---

.drone.yml

This change makes the release step wait for the Azure artifact.

chore: fix release

---

internal/pkg/grpc/gen/gen.go

This PR will connect to each trustd endpoint specified, returning once successful. Closes #891.

feat: attempt to connect to all trustd endpoints when downloading PKI

---

internal/pkg/mount/cgroups/cgroups.go

This change mounts cgroups properly.

fix: mount cgroups properly

---

.drone.yml
Dockerfile
Makefile
cmd/osctl/cmd/install_linux.go
docs/content/configuration/userdata.md
go.mod
go.sum
hack/installer/entrypoint.sh
internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/cloud/packet/packet.go
internal/app/init/internal/platform/iso/iso.go
internal/app/machined/main.go
internal/app/machined/pkg/system/services/kubeadm.go
internal/app/machined/pkg/system/services/osd.go
internal/pkg/blockdevice/bootloader/syslinux/syslinux.go
internal/pkg/constants/constants.go
internal/pkg/install/install.go
internal/pkg/install/mount.go
internal/pkg/install/prepare.go
internal/pkg/install/prepare_test.go
internal/pkg/mount/mount.go
internal/pkg/rootfs/cni/cni.go
internal/pkg/rootfs/etc/etc.go
internal/pkg/rootfs/mount/mount.go
internal/pkg/rootfs/rootfs.go
internal/pkg/upgrade/upgrade.go
pkg/userdata/install.go

This change moves the rootfs to a squashfs image.

feat: run rootfs from squashfs

---

.drone.yml

This will build AMIs and publish them to our official account on a
release.

chore: add AMI build

---

internal/app/machined/internal/event/event_test.go

Small tests to make sure code works as expected.

chore: add tests for event.Bus

---

internal/app/machined/pkg/system/health/health_test.go

It was failing randomly due to Sleep being insufficient for the desired
condition being reached.

chore: stabilize health test

---

internal/app/machined/pkg/system/health/health_test.go

Same approach: attempt more retries to fight general slowness/resource
starvation.

chore: stabilize one more health test

---

.github/main.workflow

This PR will hopefully re-enable the github actions for conform to work
as expected. :crossed_fingers:

chore: re-add github actions

---

.drone.yml
.gitignore
Makefile
hack/test/capi-setup.sh
hack/test/e2e-integration.sh

chore(ci): Add e2e promotion pipeline

---

.drone.yml
hack/test/conformance.sh
hack/test/e2e-integration.sh
hack/test/e2e-runner.sh
hack/test/osctl-cluster-create.sh

chore: Wait a little after cluster comes up

---

.drone.yml
hack/drone.jsonnet

This is another attempt at fixing the clone logic to make it work when
building the master branch.

chore: fix clone logic

---

.drone.yml
hack/drone.jsonnet

We should wait until basic integration is done.

chore: fix push step dependencies

---

internal/pkg/installer/manifest/manifest.go

fix: store PartitionName when on NVMe disk

---

cmd/osctl/pkg/client/client.go
pkg/net/net.go

fix: enclose server address is bracks if IPv6

---

internal/app/machined/internal/phase/sysctls/sysctls.go

fix: enable IPv6 forwarding

---

internal/app/proxyd/internal/frontend/frontend.go

Handle IPv6 addresses in proxyd frontend.
Fixes #988

fix(proxyd): wrap Dial addresses

---

.drone.yml
hack/drone.jsonnet

This was removed during the refactor of our Drone file.

chore: reenable AMI publishing

---

internal/app/proxyd/internal/frontend/frontend.go

fix(proxyd): do not pre-bracket IPv6 backend addrs

---

.drone.yml
hack/drone.jsonnet

We need to exclude the promotion event in a number of places.

chore: exclude promotion event

---

docs/content/guides/bare_metal.md

Initial doc for kernel parameters.

chore: add kernel parameters doc for bare-metal

---

Dockerfile

Updates the kernel image to pull the kernel from.

feat: upgrade Linux to v5.2.8

---

Makefile

This image upgrades golang to v1.12.8 to address security
vulnerabilities.

chore: update tools image

---

Dockerfile
internal/app/ntpd/main.go
internal/app/ntpd/pkg/ntp/ntp.go
internal/app/ntpd/pkg/reg/reg.go
internal/app/ntpd/pkg/reg/reg_test.go
internal/app/ntpd/proto/api.proto
pkg/constants/constants.go

Also migrated ntp functionality to sub package for better organization. 

feat: Add gRPC server for ntp

---

cmd/osctl/cmd/install_linux.go
internal/app/machined/internal/platform/baremetal/baremetal.go
internal/app/machined/internal/platform/iso/iso.go
internal/app/machined/internal/platform/packet/packet.go
internal/pkg/installer/installer.go
internal/pkg/installer/installer_test.go
internal/pkg/installer/manifest/manifest.go
internal/pkg/installer/manifest/manifest_test.go
internal/pkg/installer/manifest/verify.go
internal/pkg/installer/manifest/verify_test.go

This fixes the possibility of panicing on a nil pointer by running the
verification steps earlier.

fix: verify installation definition

---

internal/app/proxyd/main.go

This cleans up the multiple listener implementation.

refactor(proxyd): Update multilisteners to use error chan.

---

docs/content/guides/azure.md

Add getting started guide for Azure.

docs: Add Azure docs

---

pkg/blockdevice/blockdevice.go

Should help make it more robust

chore: Retry reread partition table if EBUSY

---

Dockerfile
docs/content/components/init.md
docs/content/components/kubeadm.md
docs/content/components/networkd.md
docs/content/components/osctl.md
docs/content/configuration/osd.md
docs/content/configuration/userdata.md
docs/content/configuration/workers.md
docs/content/guides/azure.md
docs/content/guides/bare_metal.md
docs/content/talos.md
docs/content/use_cases/edge.md
docs/content/use_cases/multi-cloud.md
docs/content/use_cases/serverless.md
docs/proposals/YYYYMMDD-TEMPLATE.md

This is widely considered best practice, we should enforce it.

chore: enforce one sentence per line in Markdown files

---

pkg/blockdevice/blockdevice.go

Should prevent a flake with returning an error when
it actually succeeded.
Believe previously if we hit a case where we needed to retry and then succeeded we'd still throw an error from being previously set. 

chore: Fix reread error value on retry

---

pkg/userdata/generate/talosconfig.go

fix: enclose target in quotes

---

hack/dev/qemu-boot.sh

This script will help in low-level development.

chore: add QEMU script

---

internal/app/machined/internal/phase/rootfs/mount_overlays.go
internal/app/machined/internal/phase/rootfs/mount_shared.go
internal/app/machined/main.go
internal/pkg/mount/manager/overlay/overlay.go
internal/pkg/mount/manager/overlay/overlay_test.go
internal/pkg/mount/mount.go
internal/pkg/mount/options.go
pkg/constants/constants.go

This adds a well defined task for handling all overlay mount points that
are required by the system.

feat: add overlay task

---

internal/app/machined/internal/phase/phase.go
internal/app/machined/internal/phase/services/start_services.go
internal/app/machined/internal/phase/services/stop_services.go
internal/app/machined/internal/sequencer/sequencer.go
internal/app/machined/internal/sequencer/v1alpha1/types.go
internal/app/machined/main.go

This adds an interface that can be used to descibe boot, shutdown, and
upgrade events in a set of phases.

feat: add sequencer interface

---

hack/test/azure-setup.sh
hack/test/capi.sh
hack/test/e2e-integration.sh

Single quote causes variable to not be evaluated

chore: Fix azure image upload

---

Dockerfile
hack/containerd.toml
internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/system-containerd.go

Should take care of our issue with Zombies

fix(init): Reap child processes

---

internal/app/machined/pkg/system/health/health_test.go

Fixes #1018
Fixes #1020
Add more wait loops to address cases when unit-tests are running
extremely slow under high load on the build machine.

chore: make health tests more robust

---

.drone.yml
hack/drone.jsonnet

This is experiment to see how stable they are.

chore: enable unit-tests-race

---

internal/app/networkd/pkg/networkd/networkd.go

This uses a wait group to configure interfaces concurrently.

feat: configure interfaces concurrently

---

hack/test/basic-integration.sh

Think this was causing some of our flakeyness for this test. Also gives some flexibility to the script so it can be run locally. 

chore: Retry check for HA control plane

---

internal/app/machined/internal/phase/sysctls/sysctls.go

Minor improvement for busy systems

chore(machined): Increase pid_max to 262k

---

cmd/osctl/cmd/top.go

This should give it a closer feel to the rest of the UX.

chore: remove top output border

---

.drone.yml
hack/drone.jsonnet

chore: Rename maintainers channel

---

.drone.yml
Makefile
hack/drone.jsonnet
hack/test/aws-setup.sh
hack/test/azure-setup.sh
hack/test/capi.sh
hack/test/e2e-integration.sh
hack/test/gcp-setup.sh
hack/test/manifests/aws-cluster.yaml
hack/test/manifests/capi-secrets.yaml

test(ci): Add aws for e2e and conformance targets

---

pkg/blockdevice/probe/probe.go

Fixes flakey image creation.
fixes #1034 

fix: Add retry/delay to probing device file

---

internal/app/machined/pkg/system/health/check.go

There was a new ticker being created for each run of the healthcheck.

chore(machined): Clean up unnecessary ticker alloc

---

internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/pkg/containers/containerd/containerd_test.go

Looks like containerd creates shim file sockets in Linux abstract
namespace which are fixed (don't depend on containerd root directory)
and depend on container namespace and id. So if two containerd instances
on the same host run same namespace/id pair, that is going to create a
conflict on that shim filesocket.
Avoid that by randomizing namespace name. CRI tests should be fine as
namespace is fixed, but container ID is random.

chore: randomize containerd namespace in tests

---

internal/app/machined/internal/runtime/initializer/metal/metal.go

chore: remove dead code

---

hack/test/conformance.sh
hack/test/e2e-runner.sh

This version has a fix for a bug that is affecting us.

chore: upgrade Sonobuoy to v0.15.4

---

cmd/osctl/cmd/processes.go

In general it is better if we default to single requests, and then gate
streams behind a flag. This makes the processes subcommand work in this
way and puts the streamed data behind a `--watch` flag.

feat: default processes command to one shot

---

pkg/userdata/generate/generate.go
pkg/userdata/v1alpha1/generate/generate.go

This changes CA certificate generation from 24 hours to 1 year.

fix: generate CA certificates with 1 year expiration

---

pkg/userdata/generate/generate.go
pkg/userdata/v1alpha1/generate/generate.go

fix: generate CA certificates with 10 year expiration

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
cmd/osctl/cmd/install_linux.go
go.mod
go.sum
internal/app/machined/pkg/system/services/kubeadm.go
internal/app/machined/pkg/system/services/kubeadm/kubeadm.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/constants/constants.go
pkg/userdata/download/download_test.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/generate_test.go
pkg/userdata/generate/init.go
pkg/userdata/generate/join.go
pkg/userdata/services.go
pkg/userdata/translate/translate_test.go
pkg/userdata/translate/translate_v1alpha1.go
pkg/userdata/userdata.go
pkg/userdata/v1alpha1/cluster_config.go
pkg/userdata/v1alpha1/generate/controlplane.go
pkg/userdata/v1alpha1/generate/generate.go
pkg/userdata/v1alpha1/generate/generate_test.go
pkg/userdata/v1alpha1/generate/init.go
pkg/userdata/v1alpha1/generate/join.go

This allows for users to specifify which version of Kubernetes to use.

feat: allow Kubernetes version to be configured

---

hack/dev/qemu-boot.sh

feat: Allow env override of hack/qemu image location

---

pkg/userdata/services.go

This adds a struct for configuring etcd.

feat: add etcd service to config

---

Makefile

This PR will upgrade the tools container used for building talos.

chore: upgrade tools for go v1.13.1

---

go.mod
internal/app/machined/internal/phase/services/start_services.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubeadm.go
internal/app/machined/pkg/system/services/kubeadm/kubeadm.go
pkg/constants/constants.go
pkg/crypto/x509/x509.go
pkg/kubernetes/kubernetes.go
pkg/userdata/generate/generate.go
pkg/userdata/translate/translate_v1alpha1.go
pkg/userdata/v1alpha1/cluster_config.go
pkg/userdata/v1alpha1/generate/controlplane.go
pkg/userdata/v1alpha1/generate/generate.go
pkg/userdata/v1alpha1/generate/init.go

This allows users to create an etcd service using the host init system.

feat: allow for host level etcd

---

internal/app/machined/pkg/system/services/kubelet.go

This removes the hardcoded IP and replaces it with the calculated IP.

fix: set --cluster-dns kubelet flag properly

---

pkg/config/types/v1alpha1/config.go

This implements the String() method.

fix: marshal v1alpha1 config in String() method

---

internal/pkg/platform/azure/azure.go

This PR will add the ability to query metadata servers in azure to fetch
external IPs. Needed to ensure certs get generated with proper cert SANs

feat: add external IP discovery for azure

---

docs/content/faqs/index.md
docs/content/talos.md

docs: some improvements based on community feedback (try 2)

---

internal/app/machined/pkg/system/services/osd.go

The endpoint discovery performed by OSD depends on a generated
kubeconfig that references a client certificate which is not on disk by
the time the OSD service runner is created. This adds a wait for the
kubelet to be healthy and retry logic to tolerate any race conditions.

fix: retry endpoint discovery

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.1 release.

chore: prepare release v0.3.0-alpha.1

---

pkg/config/types/v1alpha1/generate/generate.go
pkg/crypto/x509/x509.go

It is common for us to create a certificate and key using a root CA.
This adds a helper function to make this process easier and
standardized. For now, the function is only used when generating
configs, but there are a number of places we should update in follow
ups.

refactor: add helper func to create cert and key

---

cmd/osctl/cmd/validate.go

This is a minor refactor of the validate flags.

refactor: improve validate flag names

---

Dockerfile
Makefile

Ref:
* https://github.com/talos-systems/pkgs/pull/68
* https://github.com/talos-systems/tools/pull/80

chore: bump tools & pkgs for Go 1.13.2

---

docs/website/assets/css/main.css
docs/website/layouts/default.vue
docs/website/pages/index.vue

The background should only be shown on the landing page.

docs: show background only on landing page

---

docs/website/components/Dropdown.vue

The adds shadow and border radius to dropdown menu.

docs: improve dropdown menu

---

docs/website/assets/css/navigation.css
docs/website/components/CommunityDropdown.vue
docs/website/components/DocumentationDropdown.vue
docs/website/components/Header.vue

This adds a dropdown menu to the header that makes it easy to find our
community links.

docs: add community dropdown

---

docs/website/assets/css/navigation.css
docs/website/components/DocumentationDropdown.vue
docs/website/components/Header.vue
docs/website/pages/docs/_.vue

This moves the documentation version dropdown menu into the
documentation page.

docs: move docs version dropdown to docs page

---

docs/website/assets/css/main.css
docs/website/components/Sidebar.vue
docs/website/pages/docs/_.vue

This bumps the content of a doc page up and drops the sidebar down.

docs: change doc content margins and padding

---

docs/website/assets/css/main.css
docs/website/components/Content.vue
docs/website/components/Sidebar.vue
docs/website/pages/docs/_.vue

Instead of floating the sidebar, we want it to be stick so that the
footer doesn't cover the bottom of the sidebar.

docs: make the sidebar sticky

---

docs/website/assets/css/main.css
docs/website/components/CommunityDropdown.vue
docs/website/components/Header.vue
docs/website/pages/index.vue

This adds a little more space between the landing page items to make the
page a little more readable.

docs: improve landing page

---

docs/website/components/Terminal.vue

This removes the button hover color and sets the asciinema-player speed
to 1.0.

docs: improve landing page terminal

---

.drone.yml
hack/drone.jsonnet

This is critical to get correct `gitmeta image tag`.

chore: run 'git fetch --tags' as first step

---

docs/website/assets/css/navigation.css
docs/website/components/Footer.vue
docs/website/components/Header.vue

This makes the header a fixed height without animation.

docs: remove header animation

---

.drone.yml
hack/drone.jsonnet

chore: make Slack notifications more fancy

---

internal/app/machined/pkg/system/service_runner_test.go

This replaces `time.Sleep()` wait with  calls to `retry.Constant` to
wait for specific condition to be reached.

chore: make service_runner_test less flaky

---

internal/pkg/containers/containerd/containerd_test.go

The problem was that if container fails to start, it never reaches
'StateRunning' and test hangs waiting for that state. Assertion doesn't
abort whole test (it only aborts goroutine it was called from), so this
doesn't help.
Fix that by signalling back if some containers fail to start.
This is not a fix, but it should expose the actual failure happening in
this test.

chore: fix containerd test hanging

---

pkg/proc/reaper/hunter.go

This is not 100% fix as I can't reproduce tests hanging in local
environment, but the idea is the following:
1. `reaper.Start()` started reaper loop in a goroutine which starts with
subscribing to `SIGCHLD`.
2. `reaper.Start()` just spawned goroutine never waiting for it.
3. if after `reaper.Start()` reaper goroutine never runs, but process is
created in the test and it terminates, `SIGCHLD` will be ignored and
reaper will never wake up to reap the child.
4. process test hangs as it waits for reaper to reap the child and
return its exit status.
Sample failures:
```
=== RUN   TestProcessSuite/runReaper=true/TestRunLogs
2019/10/15 14:17:41 state Running: Process Process(["/bin/sh" "-c" "echo -n \"Test 1\nTest 2\n\""]) started with PID 11802
coverage: 60.0% of statements
panic: test timed …
```

chore: attempt to fix test hanging with reaper enabled

---

internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/pkg/containers/containerd/containerd_test.go

I can't say how exactly those conflicts happen in the tests, but I tried
to randomize more container IDs and namespace names (which both feed
into final abstract unix socket path).

chore: attempt to avoid containerd shim socket conflicts in tests

---

internal/app/machined/internal/phase/config/config.go

This PR will add the ability for talos to detect if the machine config
that it downloads from the platform is a gzipped file. If so, it will
unzip it and overwrite the byte slice that gets written to disk.

feat: detect gzipped machine configs

---

docs/website/assets/css/main.css
docs/website/content/v0.3/en/guides/cloud/aws.md
hack/test/aws-setup.sh

This adds documentation for v0.3 AWS users.

docs: add v0.3 AWS guide

---

docs/website/README.md
docs/website/pages/index.vue
docs/website/tailwind.config.js

- Most of the landing page is responsive on small/medium screens now. There are still
some bugs around the ascii cinema.
- Some wording tweaks, mostly I removed words to make things more concise. Feel free
to edit my edits.
- Simplified a couple of HTML constructs.
- Expanded the "features" section into two rows with a placeholder image for the 6th item.
Happy for feedback.

docs: responsiveness fixes and wording changes

---

internal/app/osd/internal/reg/reg.go

Closes #1230 
I'm not sure I understood correctly when to do retry, but i retry in osapi to 5 minutes every 5 second

feat: Add retry on get kubeconfig

---

Makefile
docs/website/content/v0.3.en.json
docs/website/content/v0.3/en/guides/cloud/digitalocean.md
internal/pkg/runtime/platform/digitalocean/digitalocean.go
internal/pkg/runtime/platform/digitalocean/digitalocean_test.go
internal/pkg/runtime/platform/platform.go

This adds a Digital Ocean platform implementation.
Closes #1206.

feat: add support for Digital Ocean

---

docs/website/content/v0.3/en/guides/cloud/digitalocean.md

Fixes small typos, and errors in the tutorial.

docs: fix Digital Ocean docs

---

.drone.yml
hack/drone.jsonnet

This will add a step to build the Digital Ocean image.

chore: add Digital Ocean image to release

---

docs/website/content/v0.3.en.json
docs/website/content/v0.3/en/guides/cloud/aws.md
docs/website/content/v0.3/en/guides/cloud/digitalocean.md
docs/website/content/v0.3/en/guides/cloud/vmware.md

This adds the VMware docs to the sidebar menu and also touches up the
wording a bit.

docs: add VMware docs to menu

---

Dockerfile
Makefile
docs/website/assets/css/main.css
docs/website/content/v0.3.en.json
docs/website/content/v0.3/en/customization/index.md
docs/website/content/v0.3/en/customization/kernel.md

This adds a section on customizing Talos.

docs: add customization guide

---

Makefile

We need to remove this so that it is not published in a release.

chore: remove RAW disk

---

CHANGELOG-0.3.md
hack/release.sh

This is the official v0.3.0-alpha.5 release.

chore: prepare release v0.3.0-alpha.5

---

internal/app/machined/pkg/system/services/bootkube.go

This adds a default PSP that is applied upon bootstrapping the cluster.
Closes #1005.

feat: create cluster with default PSP

---

internal/app/machined/internal/phase/upgrade/leave_etcd.go
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/etcd/etcd.go

This DRYs things up by using the etcd package for client creation.

refactor: use etcd package

---

internal/app/machined/internal/phase/kubernetes/tasks.go

This addresses an issue caused by containers that refuse to exit with
SIGTERM. After sending SIGTERM, we send SIGKILL after a timeout of one minute.

fix: send SIGKILL to hanging containers

---

Makefile

This adds the force option to gzip.

chore: force overwrite of output file

---

pkg/blockdevice/blkpg/blkpg.go

There are cases where we can see EBUSY when attempting to use the BLKPG
ioctl. The recommendation seems to be to retry when this happens.

fix: retry BLKPG operations

---

internal/app/machined/pkg/system/services/etcd.go

We should add an etcd member only if it has not already been added. When
a control plane node is rebooted, or down for whatever reason, when it
comes back up it will attempt to add itself again. When it does so, the
cluster is unhelathy due to the fact that the node was down. A feature
of etcd called "strict-reconfig-check" prevents any member adds when the
cluster is unhealthy since doing so would cause the cluster to lose
quorum.

fix: add etcd member conditionally

---

internal/app/ntpd/pkg/ntp/ntp.go

We need to sleep between successful queries so we don't hit the NTP
server too often.

fix: sleep in NTP query loop

---

internal/app/machined/pkg/system/services/apid.go

Since APId/gRPC connections should never go through a proxy, we will explicitly exclude
these environment variables from apid.

fix: Disable support for proxy variables for apid.

---

docs/website/content/v0.3/en/configuration/v1alpha1/reference.md

Adds information about supported environment variables.

docs: Add machine.env section

---

internal/app/machined/pkg/system/services/bootkube.go

Just a small nit, as all the services share same package, global
variable with generic name might lead to fun collisions.

fix: remove global variable in bootkube

---

internal/app/machined/pkg/system/runner/containerd/containerd.go

This allows the config.Debug setting to control container output to allow better troubleshooting.
We should probably expose a `Debug` setting per app/service, but that can be done later. 

feat: Add support for setting container output to stdout

---

Dockerfile
cmd/osctl/cmd/kubeconfig.go
cmd/osctl/pkg/client/client.go
internal/integration/base/k8s.go
internal/integration/integration_test.go
internal/integration/k8s/k8s.go
internal/integration/k8s/version.go

Once again, mostly groundwork and one simple test for node versions.

test: add k8s integration tests

---

internal/app/machined/internal/phase/services/start_system_containerd.go

Just remove duplicate line (to satisfy commit message linter).

fix: remove duplicate line

---

docs/website/components/Header.vue
docs/website/pages/roadmap/index.vue
docs/website/tailwind.config.js

This adds the first pass out our public roadmap. It is intended to be a
living document.

docs: add public roadmap

---

docs/website/pages/index.vue

This updates our note on our commitment to staying in lockstep with
Kubernetes and Linux.

docs: update landing page

---

docs/website/assets/css/main.css
docs/website/components/Header.vue
docs/website/pages/docs/_.vue
docs/website/pages/roadmap/index.vue

This adds margins to the roadmap to make it centered like the docs.

docs: fix roadmap layout

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
pkg/config/types/v1alpha1/v1alpha1_types.go

chore: format docs to one sentence per line

---

docs/website/content/v0.3/en/customization/proxy.md

Small fixes to the Dockerfile example for proxy setups.

docs: fix proxy Dockerfile example

---

cmd/osctl/cmd/root.go
cmd/osctl/pkg/client/client.go
internal/integration/base/api.go

Closes #1171 Added context switch for specific osctl command

feat: Add context key to osctl

---

docs/website/content/v0.3/en/guides/cloud/azure.md

This PR updates the azure doc to match the newer processes of deploying
talos.

docs: Update azure doc

---

docs/website/content/v0.3/en/guides/cloud/gcp.md

This PR will uplift the GCP documentation to match our current way to
deploy talos via CLI.

docs: update gcp docs

---

internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/argsbuilder/argsbuilder_args.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This allows users to supply extra arguments for the kubelet.

fix: honor the extraArgs option for the kubelet

---

pkg/kubernetes/kubernetes.go

When implementing the controller-manager I found a race condition between it
and the cordon operation. The controller-manager annotates the node to
indicate that an upgrade is on progress, and Talos tries to mark the
node as unschedulable at nearly the same time. This leads to a race
condition. The fix is to simply retry the cordon.

fix: retry cordon and uncordon

---

docs/website/content/v0.3/en/guides/metal/matchbox.md

This adds a basic guide on using Talos with Matchbox.

docs: add matchbox getting started guide

---

Dockerfile
pkg/constants/constants.go

This brings in the following changes:
- Linux 5.3.13
- Containerd 1.3.1

feat: upgrade packages

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
internal/app/machined/internal/phase/config/sysctls.go
internal/app/machined/internal/sequencer/v1alpha1/types.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This adds the ability to write sysctls on boot by specifying them in the
machine config.

feat: allow sysctl writes

---

cmd/osctl/cmd/validate.go

fix: require mode flag when validating

---

internal/app/machined/pkg/system/services/etcd.go

This adds a check for the existence of data in the etcd data directory,
that we then use to conditionally set the initial cluster args to handle
the case of a reboot of all etcd members at once. Without this, etcd
fails to come back up, and effectively kills the cluster.

fix: ensure etcd comes back up on reboot of all members

---

docs/website/nuxt.config.js
docs/website/package-lock.json
docs/website/package.json

- add the Google Analytics tracking package and tracking ID.

feat: add Google Analytics tracking to the project website

---

hack/test/conformance.sh
hack/test/e2e-runner.sh

This upgrades sonouoy and additionally adds the `--e2e-parallel` flag to
hopefully speed things up.

chore: upgrade sonobuoy

---

docs/proposals/20190704-AutomatedUpgrades.md

This is a proposal for the new way of running Talos and performing upgrades in v0.2

docs: add automated upgrades proposal

---

cmd/osctl/cmd/kubeconfig.go

This PR allows you to specify the kubeconfig command like `osctl
kubeconfig . --force` or `osctl kubeconfig . -f` to delete the
kubeconfig file before we write it out.

feat: support force flag for osctl kubeconfig

---

cmd/osctl/cmd/config.go

chore: validate url input for osctl config generate

---

cmd/osctl/cmd/config.go

This PR adds a `--output-dir/-o` flag to osctl config generate and will
attempt to create the directory path and write the generated files to
that location. Will close #1509.

feat: support output directory for osctl config generate

---

hack/drone.jsonnet

This PR adds the ability to override the image in our default build step
function in jsonnet. Needed so we can override the image easily for
basic integration tests.

chore: support image specification in drone step function

---

Dockerfile
pkg/constants/constants.go

This brings in the latest version of Containerd.

feat: upgrade containerd to v1.3.2

---

Dockerfile

This is required when doing anything with KVM.

feat: add universal TUN/TAP device driver support

---

Dockerfile

This brings in the latest 5.3 version of Linux.

feat: upgrade Linux to v5.3.15

---

pkg/constants/constants.go

This is required to pass integration tests.

fix: update kernel version constant

---

internal/app/apid/main.go
internal/app/apid/pkg/provider/provider_test.go
internal/app/apid/pkg/provider/tls.go

No functional changes, just moving code around.

refactor: extract TLS bits from apid main.go

---

.drone.yml
Makefile
hack/drone.jsonnet
internal/test-framework/cmd/basic-integration.go
internal/test-framework/cmd/root.go
internal/test-framework/internal/pkg/runner/runner.go
internal/test-framework/main.go

This PR will be the start of several. It rewrites the basic integration
in go. We'll do these one at a time.

chore: rewrite basic integration in go instead of bash

---

hack/test/e2e-runner.sh

This brings in the latest sonobuoy.

chore upgrade sonobuoy to v0.16.5

---

pkg/retry/retry.go

We need deterministic ordering for retry errorss

fix: make retry errors ordered

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
pkg/config/types/v1alpha1/v1alpha1_types.go

docs: update with new cni abilities

---

go.mod

fix: run go mod tidy

---

internal/app/machined/internal/phase/sysctls/sysctls.go

Docker for Mac doesn't seem to have br_netfilter, so we set this
conditionally.

fix: don't set br_netfilter sysctls in container mode

---

pkg/net/net.go

Strip line feed from domainname after read

---

internal/app/networkd/pkg/networkd/misc.go

If we have a domainname, add it to resolv.conf.
Fixes #1626

feat: add domain line to resolv.conf

---

docs/website/package-lock.json
docs/website/package.json

Update node dependencies for project website.

fix: update node dependencies for project website

---

docs/website/content/v0.3/en/customization/proxy.md

It is possible to append to file since 84354c59414, hence no need to create custom Docker image

docs: simplify corporate proxy

---

docs/website/package.json

This change should slightly improve the search engine placement of our docs/project site by being a bit more descriptive.

fix: improve the project site meta description

---

cmd/osctl/cmd/cluster.go

This PR adds a `--cidr` flag to the custer create command that allows
for specification of the cidr block users want to use for their docker
network.

feat: support specifying CIDR for docker network

---

cmd/osctl/cmd/copy.go
cmd/osctl/cmd/kubeconfig.go
cmd/osctl/cmd/read.go
cmd/osctl/cmd/root.go
internal/integration/cli/copy.go
internal/integration/cli/kubeconfig.go
internal/integration/cli/list.go
internal/integration/cli/read.go

Fixes #1663
(I believe it's 0.3 backport strong candidate).

fix: fail on muliple nodes for commands which don't support it

---

hack/test/integration/dnsmasq/talos0.conf

This adds hostname and domain name options to the DHCP response.

chore: fix KVM test

---

cmd/osctl/cmd/list.go

For long format, node is reported always as first column.
For regular format, if `--nodes` wasn't specified, output goes as
before without node name, but if `--nodes` is used, output switches to
column format with node being first column.
Example:
```
$ osctl list /etc
.
ca-certificates
cni
cri
hostname
hosts
kubernetes
mtab
os-release
pki
resolv.conf
ssl
```
```
$ osctl list --nodes 10.5.0.2,10.5.0.3 /etc
NODE       NAME
10.5.0.2   .
10.5.0.2   ca-certificates
10.5.0.2   cni
10.5.0.3   .
10.5.0.3   ca-certificates
10.5.0.2   cri
10.5.0.2   hostname
10.5.0.2   hosts
10.5.0.2   kubernetes
10.5.0.2   mtab
10.5.0.2   os-release
10.5.0.2   pki
10.5.0.2   resolv.conf
10.5.0.2   ssl
10.5.0.3   cni
10.5.0.3   cri
10.5.0.3   hostname
10.5.0.3   hosts
10.5.0.3   kubernetes
10.5.0.3   mtab
10.5.0.3 …
```

fix: update `osctl list` to report node name

---

Dockerfile
pkg/constants/constants.go

This brings in the latest stable version of Linux.

feat: upgrade Linux to v5.4.5

---

internal/app/networkd/pkg/nic/nic.go

This should allow us to correctly differentiate between IFF_UP ( admin up ) and
IFF_RUNNING ( link ready ). This means that we should now wait for the link to
be up and running before proceeding with addressing which should allow for more
reliable results in the dhcp configuration and avoid any race issues in static
configuration.

fix(networkd): Check for IFF_RUNNING on link up

---

cmd/osctl/cmd/upgrade.go
internal/app/machined/pkg/system/runner/restart/restart.go
internal/app/networkd/pkg/networkd/networkd.go

This fixes random log issues.
Fixes #1659.

fix: fix output formats

---

.drone.yml
Makefile
hack/drone.jsonnet

This replaces buildkit and buildctl with the docker buildx plugin.

chore: use docker buildx

---

.drone.yml
Dockerfile
Makefile
hack/drone.jsonnet

This PR aims to make the Makefile more DRY.

chore: refactor Makefile to be more DRY

---

.dockerignore
.drone.yml
.gitignore
Dockerfile
Makefile
cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
cmd/osctl/cmd/root.go
docs/osctl/osctl_cluster_create.md
docs/osctl/osctl_config_generate.md
docs/osctl/osctl_gen_keypair.md
hack/drone.jsonnet
hack/installer/entrypoint.sh
internal/test-framework/cmd/basic-integration.go
pkg/constants/constants.go

This adds a help  menu to the Makefile. It documents all build
dependencies, and how to get started.

chore: add help menu to the Makefile

---

.drone.yml
hack/drone.jsonnet

We no longer depend on gitmeta.

chore: remove gitmeta references

---

.drone.yml
hack/drone.jsonnet

The drone linter complained about duplicate steps. This removes them.

chore: fix conformance

---

internal/pkg/provision/check/default.go
internal/pkg/provision/check/options.go
internal/pkg/provision/check/service.go

This adds a cluster check that requires etcd to be healthy.

test: ensure etcd is healthy on all control plane nodes

---

cmd/installer/pkg/ova/ova.go

This adds a variable to the mf template to render the mf file name
properly.

fix: use the correct mf file name

---

.drone.yml
Makefile
hack/drone.jsonnet

This ensures that the latest tag is updated on git tag events.

chore: push latest tag on tag events

---

.drone.yml
CHANGELOG-0.3.md
Makefile
cmd/installer/cmd/image.go
cmd/installer/cmd/root.go
cmd/installer/pkg/ova/ova.go
hack/drone.jsonnet
internal/pkg/runtime/platform/vmware/vmware.go

This is the official v0.3.0-beta.3 release.

chore: prepare release v0.3.0-beta.3

---

internal/pkg/provision/providers/docker/network.go

This PR will allow users to use an existing docker network for their
talos cluster. Hoping this will be useful for those wanting further
control and configuration of their local docker clusters, as well as
possibly useful for us during CI. The docker networks can be pre-created
with something like: `docker network create my-cluster --subnet
192.168.0.0/24 --label talos.owned=true --label
talos.cluster.name=my-cluster`. Note that the labels are pre-reqs for our discovery and re-use of these networks.

chore: allow re-use of docker network for local clusters

---

.drone.yml
Dockerfile
Makefile
hack/drone.jsonnet
hack/test/basic-integration.sh

We should build the most common things by default.

chore: update all target in Makefile

---

Dockerfile
pkg/constants/constants.go

This brings in the latest 5.4 kernel.

feat: upgrade linux to v5.4.8

---

docs/website/content/v0.3.en.json

This PR alphabetizes the components and adds in the missing ntpd link.
Will close #1751 

docs: reorganize components sidebar and add ntpd

---

Dockerfile
pkg/constants/constants.go

This brings in the latest stable Linux.

feat: upgrade Linux to v5.4.10

---

Dockerfile

This brings in the latest stable linux.

feat: upgrade Linux to v5.4.11

---

Dockerfile
Makefile

Ref: https://github.com/talos-systems/tools/pull/85,
https://github.com/talos-systems/pkgs/pull/87

chore: bump tools/pkgs for Go 1.13.6

---

pkg/grpc/gen/remote.go

Consumers of RemoteGenerator need a way to close the grpc.ClientConn.

fix: add Close func in remote generator

---

internal/app/machined/internal/api/reg/reg.go

This PR will add a very basic check to make sure that the installer
image specified during something like `osctl upgrade` indeed seems to be
a talos installer. We do this by simply calling the help flag of a known
binary (`/bin/installer --help`). If this doesn't exist, we exit with
the assumption that the user has made a mistake.

chore: validate installer image before upgrade

---

.drone.yml
hack/drone.jsonnet
hack/test/basic-integration.sh
hack/test/capi.sh
hack/test/conformance.sh
hack/test/e2e-integration.sh
hack/test/e2e-runner.sh

This adds sonobuoy's quick mode test to basic integration.

chore: run sonobuoy in quick mode

---

docs/osctl/osctl_cluster_create.md
docs/osctl/osctl_config_generate.md
docs/website/content/v0.3/en/configuration/v1alpha1.md
hack/test/e2e-runner.sh
hack/test/integration/libvirt.sh
hack/test/manifests/aws-cluster.yaml
hack/test/manifests/gcp-cluster.yaml
pkg/config/types/v1alpha1/doc.go
pkg/constants/constants.go

This PR will bring in the latest point release of k8s 1.17

feat: upgrade kubernetes version to 1.17.1

---

CHANGELOG-0.3.md
internal/app/machined/internal/phase/phase.go
internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/main.go
internal/pkg/runtime/errors.go
internal/pkg/runtime/initializer/metal/metal.go

This is the official v0.3.1 release.

chore: prepare release v0.3.1

---

docs/website/content/v0.3/en/guides/metal/index.md

This simpifies the metal section overview.

docs: update metal section

---

.drone.yml
hack/drone.jsonnet

We need `DOCKER_NET` to be set.

chore: fix CI

---

.conform.yaml
docs/website/content/v0.3.en.json
docs/website/content/v0.3/en/components/apid.md

Describes apid and introduces some workflows to illustrate what apid does.

docs(apid): Add apid docs

---

internal/app/networkd/pkg/reg/reg.go

Call ticker.Stop() to prevent leak (ref #1807).

fix(networkd): fix ticker leak

---

docs/website/assets/images/external-link.svg
docs/website/components/EnterpriseLink.vue
docs/website/components/Header.vue
docs/website/pages/index.vue

- add a separate link to get to the corporate site
- unify some styles between corp and OSS sites
- minor responsiveness fixes

docs: add a link to the Talos Systems company site to the OSS site

---

internal/app/networkd/pkg/networkd/networkd.go

This DRYs up the interface configuration and adds in an error channel to capture
any issues that come up from interface configuration. These errors are still
treated as non-fatal, but should provide some additional insight.

chore(networkd): Report on errors during interface configuration

---

Dockerfile

This brings in a number of kernel improvements.

chore: update pkgs

---

internal/integration/api/reboot.go

This complements "rolling restart" RebootNodeByNode test by providing
more of a disaster scenario, when all the nodes are restarted at once.

test: implement RebootAllNodes test

---

internal/integration/api/reboot.go

As calls to the nodes are proxied through `apid` on init node, we can't
reboot all nodes concurrently, as init node might be already down by the
moment any other node is going to be rebooted.
Rewrite the test to reboot all the nodes in a single multi-node
request.

test: fix `RebootAllNodes` test to reboot all nodes in one call

---

internal/app/machined/pkg/system/services/kubelet.go

Handle multiple service CIDRs (such as for dual-stack configurations)
cleanly, calculating the DNS service IP for each.
Fixes #1888

fix: allow kublet to handle multiple service CIDRs

---

cmd/osctl/cmd/reset.go
docs/osctl/osctl_reset.md

We should default to shutting down when resetting.

fix: default reboot flag to false

---

internal/pkg/loadbalancer/loadbalancer.go

Nothing to say here, but validator requires commit body.

chore: fix small misprint

---

Dockerfile
Makefile
pkg/config/machine/machine.go
pkg/constants/constants.go

See also:
* https://github.com/talos-systems/tools/pull/89
* https://github.com/talos-systems/pkgs/pull/103

chore: update pkgs & tools for Go 1.14

---

internal/pkg/mount/manager/owned/owned.go

We need the ability to manage the boot partition and ephemeral partition
independently. This adds the required functions to allow for that.

feat: add function for mounting a specific system disk partition

---

internal/app/networkd/pkg/networkd/networkd_test.go

This adds a test for a case when a DHCP response contains a domain name,
but not a hostname.

test: add test for empty hostname option

---

internal/app/init/main.go

This PR reworks the ordering of our recovery function. It will make sure
we actually show the user the recovery message prior to looking into
whether to auto-reboot.

fix: ensure printing of panic message

---

Dockerfile
Makefile

Fixes #1934
See talos-systems/pkgs#106, talos-systems/tools#90

feat: upgrade Go to version 1.14.1

---

docs/website/package-lock.json
docs/website/package.json
docs/website/pages/docs/_.vue
docs/website/pages/roadmap/index.vue

- Update the website generator's package list to quiet github.
- Apply a couple of auto-lint fixes.

docs: update the website generator's npm packages

---

.drone.yml
Dockerfile
hack/drone.jsonnet

This adds an ARM64 build of `talosctl`.

feat: build talosctl for ARM64

---

docs/website/package-lock.json

This is addresses a security vulnerability.

chore: run npm audit fix

---

.drone.yml
Dockerfile
hack/drone.jsonnet

This adds an ARM v7 build of `talosctl`.

feat: build talosctl for ARM v7

---

docs/osctl/osctl_cluster_create.md

docs: run make docs

---

docs/website/content/v0.4/en/components/networkd.md

docs: Add example of a VLAN configured device.

---

internal/app/networkd/pkg/reg/reg.go

We saw strange behavior in this health check, and think that it is due
to ARP table cache. In practice, the health check caused nodes to hang.
We decided to not use the ARP table to determine the health of networkd.
The fact that networkd can respond to the health API should be
sufficient enough since network will fail to start upon any error in the
initial setup of the network.

fix: don't use ARP table for networkd health check

---

internal/pkg/mount/mount.go

This fixes reboot errors like:
```
[    8.963544] [talos] [phase]: unmount system disk submounts error running task: unmount: 1 error(s) occurred:
[    8.964428] 	invalid argument
[    8.964711] [talos] [phase]: unmount system disk submounts done, 1.836089ms
[    8.965354] [talos] error running phase "unmount system disk submounts": 1 error occurred:
[    8.966077] 	* unmount: 1 error(s) occurred:
[    8.966469] 	invalid argument
[    8.966765]
[    8.966919]
[    8.967102] [talos] recovered from: shutdown failed: error running phase "unmount system disk submounts": 1 error occurred:
[    8.968119] 	* unmount: 1 error(s) occurred:
[    8.968530] 	invalid argument
[    8.968815]
[    8.968966]
[    8.969177] [talos] rebooting in 10 seconds
```
Fixing this on the safe side: unmount is …

fix: ignore EINVAL on unmounting when mount point isn't mounted

---

internal/app/machined/internal/phase/rootfs/validate_config.go

This fixes a race condition between config validation and USB storage
availablity. If a user attempts to install to a USB disk, we should wait
for the amount of seconds specified in
`/sys/module/usb_storage/parameters/delay_use` before we attempt to
validate the config. If we don't, then there is the chance that the USB
device is not mounted in time, and we fail to install because we cannot
verify the disk is available.
Fixes #1985.

fix: wait for USB storage

---

Dockerfile

This brings in a kernel with BNX drivers enabled.

feat: add BNX drivers

---

internal/app/machined/internal/phase/services/start_system_containerd.go

On slow systems, next task to run container via `system-containerd`
might fail as `system-containerd` is not healthy yet.
New log output verifies that:
```
172.20.0.1: user: warning: [2020-04-06T20:13:17.618186962Z]: [talos] [phase]: start system-containerd
172.20.0.1: user: warning: [2020-04-06T20:13:17.618970962Z]: [talos] service[system-containerd](Preparing): Running pre state
172.20.0.1: user: warning: [2020-04-06T20:13:17.619918962Z]: [talos] service[system-containerd](Preparing): Creating service runner
172.20.0.1: user: warning: [2020-04-06T20:13:18.841389962Z]: [talos] service[system-containerd](Running): Process Process(["/bin/containerd" "--address" "/run/system/containerd/containerd.sock" "--state" "/run/system/containerd" "--root" "/run/system/lib/containerd"]) started with …
```

fix: wait for `system-containerd` to become healthy before proceeding

---

Dockerfile

This adds the firmware for the bnx2 and bnx2x drivers.

fix: add bnx2 and bnx2x firmware

---

Dockerfile
pkg/constants/constants.go

This brings in the latest 5.5 version of Linux.

feat: upgrade Linux to v5.5.15

---

.drone.yml
Makefile
hack/drone.jsonnet

`make docs` removes and then regenerates contents of some docs, so it
might cause random `-dirty` issue when running concurrently with build
steps.

test: serialize `docs` step execution

---

Makefile
internal/integration/provision/upgrade.go

We should stick to the latest version in each release series.

test: update versions used for upgrade tests

---

Dockerfile
Makefile

See also:
* https://github.com/talos-systems/tools/pull/91
* https://github.com/talos-systems/pkgs/pull/114

feat: upgrade Go to 1.14.2

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

This adds an issue template for bug reports.

chore: add bug report issue template

---

.conform.yaml
CHANGELOG.md
hack/release.sh

This is the official v0.5.0-alpha.1 release.

release(v0.5.0-alpha.1): prepare release

---

CHANGELOG-0.4.md

This is the official v0.4.1 release.

chore: prepare release v0.4.1

---

internal/app/networkd/pkg/nic/nic.go

Fix IPv6 default gateway creation when the gateway is only reachable via Link-Local-Unicast address.
It was broken. Discussed on Slack with @andrewrynhard 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2075)

fix IPv6 static default gateway not set if gateway is a LL unicast address

---

internal/integration/api/reboot.go

This makes troubleshooting easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2085)

test: add node name to error messages in RebootAllNodes

---

docs/website/components/Footer.vue

- Update the page footer copyright date to 2020
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2098)

docs: update copyright date

---

Dockerfile

This brings in an updated kernel that enables rpfilter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2092)

feat: enable rpfilter

---

cmd/installer/cmd/root.go
cmd/installer/pkg/install/install.go
pkg/download/download.go

This adds support for reading the config from a local file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2103)

feat: add support for file scheme

---

CHANGELOG.md

This is the official v0.5.0-beta.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2104)

release(v0.5.0-beta.0): prepare release

---

.conform.yaml
CHANGELOG.md

This is the official v0.6.0-alpha.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2114)

release(v0.6.0-alpha.0): prepare release

---

docs/website/content/v0.5/en/components/overview.md

Added a table containing all(?) Talos components, to the components/overview page.
This should fix issue #1933
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2116)

docs: overview of talos components

---

docs/website/components/Content.vue
docs/website/content/v0.4/en/components/machined.md
docs/website/content/v0.5/en/components/machined.md
docs/website/content/v0.5/en/components/overview.md
docs/website/nuxt.config.js
docs/website/package-lock.json
docs/website/package.json

- Intra-site docs links need to be relative
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2123)

docs: fix broken links in components pages (fixes #2117)

---

Dockerfile
pkg/constants/constants.go

This brings in the latest version of Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2125)

feat: upgrade Linux to v5.6.13

---

Makefile
internal/integration/provision/upgrade.go

Our policy it to support two last releases (0.4, 0.5 at the moment).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2126)

test: update Talos versions for upgrade tests

---

internal/integration/base/api.go

After node reboot test code tries endlessly to read the uptime
until it goes down after reboot, but during actual reboot API won't be
responsive and it might happen that this call will time out only with
parent context cancelling, and by that time retry timeout is already
exhausted, so no more attempts will be made (while node successfuly
booted after a reboot).
```
uptime didn't go down: before 219.730000, after 267.020000
uptime didn't go down: before 219.730000, after 268.030000
EOF
rpc error: code = DeadlineExceeded desc = context deadline exceeded
timeout
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2 …

test: improve reboot/reset test resiliency against request timeouts

---

CHANGELOG.md

This is the official v0.5.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2147)

release(v0.5.0): prepare release

---

docs/website/pages/index.vue

- center the "Certified Kubernetes" logo
- adjust margin on an unordered list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2154)

docs: fix a few minor styling issues on the home page

---

docs/website/content/v0.5.en.json
docs/website/content/v0.5/en/guides/getting-started/talosctl.md

Initial version of the talosctl docs.
Signed-off-by: Patatman <git@jeursen.nl>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2149)

docs: add talosctl docs document

---

internal/app/apid/pkg/backend/apid.go

This validates IPs by simple parsing and ensures `host:part` is correct
by using `net.FormatAddress`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2161)

fix: correctly handle IPv6 address in apid

---

internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
internal/app/machined/pkg/system/services/trustd.go

This adds a dependency on timed to services that depend on time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2157)

fix: make services depend on timed

---

CHANGELOG.md

This is the official v0.6.0-alpha.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2177)

release(v0.6.0-alpha.2): prepare release

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go

This allows for the recovery sequence to be ran at any time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2180)

feat: allow recovery at all times

---

Dockerfile
pkg/constants/constants.go

This PR bundles three commits from the pkgs repo:
- https://github.com/talos-systems/pkgs/commit/c09825e05a6489e544f44835f746bf28e2d9c454
- https://github.com/talos-systems/pkgs/commit/393291ddf21d7b72f8b9b9be63a00fa546b577ab
- https://github.com/talos-systems/pkgs/commit/908b75b81f0a8103935e2c8f427f99f935b9e60a
Will close #2176 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2184)

feat: update linux kernel (with 32 bit support) and talos pkgs for v0.6

---

docs/website/content/v0.4/en/configuration/v1alpha1.md
docs/website/content/v0.5/en/configuration/v1alpha1.md
docs/website/content/v0.6/en/configuration/v1alpha1.md
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/argsbuilder/argsbuilder_args.go
pkg/config/types/v1alpha1/v1alpha1_types.go

Replace blacklist with denylist, it was only used internally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2201)

chore: use neutral terminology

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/syslinux/syslinux.go

This changes fixes a bug that caused the revert API to fail. It
fails because the `Revert` function uses the syslinux ADV to
determine which boot label to revert to. This adds a function
for reverting the default boot to an explicit value. The revert
API does a lookup of what should be the next boot, and uses
this new function to perform the rollback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2211)

fix: revert default boot properly

---

cmd/talosctl/cmd/talos/rollback.go
docs/talosctl/talosctl.md
docs/talosctl/talosctl_rollback.md
pkg/client/client.go

This adds the `rollback` command to `talosctl`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2197)

feat: add rollback command

---

.drone.yml
hack/drone.jsonnet

This change makes the provision tests run in parallel to the
e2e tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2216)

chore: run provision tests in parallel

---

CHANGELOG.md

This is the official v0.6.0-alpha.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2217)

release(v0.6.0-alpha.3): prepare release

---

.drone.yml

This was missed in a previous PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2221)

chore: sign the drone file

---

internal/app/bootkube/main.go

This moves to using a boolean value to determine if we need to
cleanup the manifests directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2225)

fix: detect failed bootkube run properly

---

CONTRIBUTING.md

To make it easier for new comer, and added some tips for OSX plus Visual Studio Code.
Signed-off-by: Patatman <git@jeursen.nl>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2207)

docs: extend contribution doc

---

docs/website/content/v0.6/en/guides/getting-started/intro.md

specs added to the quickstart, to fix #2200
Signed-off-by: Patatman <git@jeursen.nl>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2205)

docs: specs added

---

internal/integration/api/reboot.go
internal/integration/api/reset.go
internal/integration/base/api.go

These tests rely on node uptime checks. These checks are quite flaky.
Following fixes were applied:
* code was refactored as common method shared between reset/reboot tests
(reboot all nodes does checks in a different way, so it wasn't updated)
* each request to read uptime times out in 5 seconds, so that checks
don't wait forever when node is down (or connection is aborted)
* to account for node availability vs. lower uptime in the beginning of
test, add extra elapsed time to the check condition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2245)

test: fix and improve reboot/reset tests

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2246)

release(v0.6.0-alpha.4): prepare release

---

docs/website/content/v0.6.en.json
docs/website/content/v0.6/en/guides/metal/digitalrebar.md
hack/test/digitalrebar/bootenv.yaml
hack/test/digitalrebar/params.yaml
hack/test/digitalrebar/stages.yaml
hack/test/digitalrebar/talos-controlplane-profile.yaml
hack/test/digitalrebar/talos-init-profile.yaml
hack/test/digitalrebar/talos-worker-profile.yaml
hack/test/digitalrebar/workflow.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2222)

docs: digital rebar docs

---

Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2252)

feat: upgrade containerd to v1.3.6

---

Dockerfile
pkg/constants/constants.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2257)

fix: report the correct containerd version

---

Dockerfile
pkg/constants/constants.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2258)

feat: upgrade Linux to v5.7.7

---

cmd/talosctl/cmd/mgmt/cluster/create.go
docs/talosctl/talosctl_cluster_create.md

Fixes #2263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2264)

fix: provide default DNS domain to talosctl cluster create
