- docs/website/content/v0.4/en/guides/getting-started/firecracker.md
docs: add installation chapter to firecracker getting started
docs: add troubleshooting chapter to firecracker getting started
Add installation/troubleshooting chapters to firecracker getting started guide.
Missing steps in the getting started guide as discussed in https://github.com/talos-systems/talos/issues/2062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2064)
> docs: add install and troubleshooting section in firecracker getting started

- docs/website/content/v0.4/en/configuration/v1alpha1.md
- go.mod
- go.sum
- internal/app/bootkube/assets.go
- internal/app/machined/pkg/runtime/configurator.go
- pkg/config/types/v1alpha1/generate/init.go
- pkg/config/types/v1alpha1/v1alpha1_configurator.go
- pkg/config/types/v1alpha1/v1alpha1_types.go
Handle dual-stack configurations with the bootkube wrapper.  This uses
the new PodCIDRs and ServiceCIDRs `asset.Config` parameters in bootkube.
Fixes #2055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2056)
> feat: allow dual-stack support with bootkube wrapper

- cmd/installer/pkg/install/install.go
There is no need to really warn about this. We handle this sceanrio just
fine now. The warning just adds confusion.
Fixes #2071.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2072)
> refactor: remove warning about missing boot partition

- Dockerfile
We were never copying the protobuf files in, so prototool was never
really linting anything. This ensures that the `api` directory is copied
in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2069)
> chore: fix prototool lint

- docs/website/components/Content.vue
- docs/website/components/DocumentationDropdown.vue
- docs/website/components/Sidebar.vue
- docs/website/pages/docs/_.vue
- docs/website/store/sidebar.js
- simplify the docs page handling logic and get more nuxt-like
- the handleClick function was vestigial and didn't do anything anymore, remove it
- simplify the Vuex state quite a bit, remove activeDocPath
- clean up github link generation code and fix #2076
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2077)
> docs: clean up docs page scripts in preparation for 0.5 docs

- docs/website/nuxt.config.js
There are some funny interactions between Netlify and Nuxt/Vue-based SPA apps. Docs urls to individual pages aren't "real" files on disk from Netlify's perspective, so for deep links, we need to set up fallback routes on the Nuxt/Vue side.
More here: https://nuxtjs.org/faq/netlify-deployment#for-site-generated-in-spa-mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2081)
> docs: fix netlify deep linking for 0.5 docs with fallback routes

- docs/website/content/v0.3/en/guides/index.md
- docs/website/content/v0.4/en/guides/index.md
- Replaced the basic intro text for 0.3 and 0.4 on the docs home page with more useful information and links to next steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2082)
> docs: backport intro text to 0.3 and 0.4 docs

- .drone.yml
- hack/drone.jsonnet
- internal/integration/api/reset.go
Bump timeouts for reset API test as K8s control plane teardown might
take 3 minutes on its own.
Bump Go Firecracker SDK timeout when talking to firecracker process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2083)
> test: stabilize tests by bumping timeouts

- Dockerfile
A new version of markdownlint-cli was released that breaks the
lint-markdown target. This pins all the libraries we use for
linting markdown files to specific versions that are known to
work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2084)
> chore: pin markdown linting libraries

- internal/app/machined/main.go
This ensures that the machined RPC logs are written to disk so that users
can retrieve them via the log API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2088)
> fix: write machined RPC logs to file

- Dockerfile
This updates packages to include a kernel built with
CONFIG_NETFILTER_XT_MATCH_SOCKET=y since it is recommended
by cilium.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2086)
> fix: update kernel package

- cmd/talosctl/cmd/talos/root.go
- internal/integration/base/api.go
- internal/pkg/cluster/config.go
- pkg/client/client.go
- pkg/client/options.go
- pkg/client/resolver.go
Create a new `client.NewFromConfigContext` to make external API systems
easier to construct.
This also makes a first pass at supporting multiple endpoints properly
by creating a custom grpc resolver.  (Proper load balancing support is
still a TODO.)
Fixes #2093
Refactor client construction API for easier use with external tooling.
Several steps in constructing a client were embedded within the talosctl command, resulting in repeated and non-obvious code when constructing custom clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2094)
> fix: refactor client creation API

- .drone.yml
- hack/drone.jsonnet
This PR will ensure that the firecracker provision tests will only run
after a successful e2e_firecracker run. This is being added in hopes of
freeing up some resources during CI testing and making things more
stable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2087)
> chore: serialize firecracker e2e tests

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
1. `sync.Mutex` zero value is fine as initial value, and it's part of
the `Events` structured which is passed by pointer, it's fine to embed
it. (simplify)
2. Add safety net around potentially blocked event subscribers so that
it doesn't block event propagation. This is not a perfect solution, but
my feeling that it's better than blocking.
3. Fix delete sequence - first remove the channel, then close it, as
otherwise send might panic to closed channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2107)
> chore: fix nits in the events code

- cmd/talosctl/cmd/mgmt/cluster/create.go
- docs/talosctl/talosctl_cluster_create.md
- internal/pkg/provision/providers/docker/docker.go
This PR will fix some unexpected user behavior where nameservers were
always getting written to 8.8.8.8,1.1.1.1 for the docker-based talos
clusters. This occurred even when updating the docker daemon's config.
This PR will make the docker provisioner respect the --nameserver flag
and allow that to be used to override the defaults.
Should close #2109.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2112)
> fix: respect nameservers when using docker cluster

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/main.go
- internal/app/machined/pkg/system/runner/goroutine/goroutine.go
- internal/app/machined/pkg/system/runner/goroutine/goroutine_test.go
- internal/app/machined/pkg/system/services/machined.go
In recent refactoring the machined API service was changed to run outside
of the service framework. This brings it back as a service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2106)
> fix: run machined API as a service

- internal/app/machined/pkg/system/services/etcd.go
- internal/pkg/etcd/etcd.go
- pkg/net/net.go
Make certain that all etcd address URLs are properly wrapped to handle
IPv6 addresses.
Fixes #2120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2122)
> fix: wrap etcd address URLs with formatting

- go.mod
- go.sum
This updates the bootkube plugin that brings in a fix that allows
any seccomp profile name to be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2127)
> fix: allow all seccomp profile names

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
This adds a bit more time to the max wait time for services to start.
This fixes a few issues. First it makes the cluster health wait fail
often since there isn't enough time and the boot sequence fails, even
though things are progressing just fine. Second, this gives a bit more
time for users to collect data when debugging and more time for
invoking the bootstrap API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2132)
> fix: bump service wait to ten minutes

- go.mod
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/main.go
- internal/app/machined/pkg/runtime/events.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
The idea here is to use single slice of events for all the consumers.
Each consumer keeps its own position within the stream, and stream is
structured as circular buffer to avoid using too much memory.
This implementation allows for one more future: looking "back" into the
event history and returning past event starting with some offset (e.g.
timestamp, event ID, etc.). This feature is not implemented yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2113)
> chore: replace underlying event implementation with single slice

- .drone.yml
- Dockerfile
- Makefile
- hack/drone.jsonnet
- hack/golang/test.sh
With Go 1.14.3 we can run race-enabled code on muslc, so this opens path
to run unit-tests-race under Talos environment with rootfs, enabling all
the tests to run under race detector.
Also fixed the tests run by specifying platform in the test environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2137)
> chore: upgrade Go to 1.14.3 and use toolchain for race detector

- cmd/talosctl/cmd/talos/containers.go
- cmd/talosctl/cmd/talos/dmesg.go
- cmd/talosctl/cmd/talos/events.go
- cmd/talosctl/cmd/talos/interfaces.go
- cmd/talosctl/cmd/talos/list.go
- cmd/talosctl/cmd/talos/logs.go
- cmd/talosctl/cmd/talos/memory.go
- cmd/talosctl/cmd/talos/mounts.go
- cmd/talosctl/cmd/talos/processes.go
- cmd/talosctl/cmd/talos/routes.go
- cmd/talosctl/cmd/talos/service.go
- cmd/talosctl/cmd/talos/stats.go
- cmd/talosctl/cmd/talos/time.go
- cmd/talosctl/cmd/talos/upgrade.go
- cmd/talosctl/cmd/talos/version.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- pkg/client/client.go
- pkg/client/peer.go
This provides interface to consume (watch) events in the same way (with
the same API) as server code does. So some processing might be moved
back and forth between client and server without much code change.
Also moved peer methods out of helpers to the main client package, they
might be useful for any client, not only talosctl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2134)
> feat: implement simplified client method to consume events

- README.md
The one sentence per line linter thinks that the ! is part of a sentence. This
uses HTML to get around this limitation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2143)
> chore: fix markdown lint

- pkg/client/client.go
Fixes #2138
`FilterMessages` might return `nil` resp if it extracts errors into
`err` from `resp`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2144)
> fix: prevent panic on nil pointer in ServiceInfo method

- Dockerfile
This adds LVM2 to the rootfs. This is required by rook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2142)
> feat: add LVM2

- docs/website/components/DocumentationDropdown.vue
- docs/website/components/Header.vue
- docs/website/pages/index.vue
This updates links and dropdown menus to point to the v0.5
documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2150)
> docs: make v0.5 docs the default

- Makefile
- internal/integration/provision/upgrade.go
This adds latest 0.6 alpha and 0.5 stable to the upgrade tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2153)
> chore: update provision test versions

- go.mod
- go.sum
- internal/app/machined/pkg/system/services/networkd.go
- internal/app/machined/pkg/system/services/networkd_test.go
- internal/app/machined/pkg/system/services/osd.go
- internal/app/machined/pkg/system/services/routerd.go
- internal/app/machined/pkg/system/services/timed.go
- internal/app/timed/main.go
- internal/app/timed/pkg/ntp/ntp.go
- internal/app/timed/pkg/ntp/options.go
- internal/app/timed/pkg/reg/reg.go
- internal/app/timed/pkg/timex/timex.go
This should be proper way to adjust time incrementally without causing
jumps one in +/- direction. Time-sensitive services might be confused by
huge jumps.
Next steps: insert/delete leap seconds, provide timed health status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2145)
> feat: adjust time properly in timed via adjtime()

- internal/app/apid/pkg/backend/apid.go
- pkg/net/net.go
- pkg/net/net_test.go
This allows node names for APID, but checks for empty or port-appended
addresses in a best-effort manner.
Fixes #2163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2164)
> fix: allow node names

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
It is common to want to reset a node when it is stuck in the boot
sequence due to misconfiguration. This allows the reset sequence
at all times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2167)
> feat: allow reset API at all times

- docs/website/content/v0.4/en/guides/getting-started/firecracker.md
- docs/website/content/v0.5/en/guides/local/firecracker.md
This adds a note on a few more requirements on the host kernel for
running Talos with firecracker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2168)
> docs: add kernel options to firecracker reqs

- internal/app/machined/pkg/system/runner/containerd/containerd_test.go
- internal/pkg/containers/containerd/containerd_test.go
- internal/pkg/containers/cri/cri_test.go
- internal/pkg/cri/cri_test.go
Looks like goroutine launched from suite setup might have a race while
trying to access methods which in the end try to load `testing.T` value,
as it changes while each individual test is running.
This leaves us with less diagnostics, but eliminates the race.
Sample:
```
WARNING: DATA RACE
Write at 0x00c00035e418 by goroutine 56:
github.com/stretchr/testify/suite.(*Suite).SetT()
/go/pkg/mod/github.com/stretchr/testify@v1.5.1/suite/suite.go:37
+0x12d
github.com/talos-systems/talos/internal/pkg/containers/containerd_test.(*ContainerdSuite).SetT()
<autogenerated>:1 +0x4d
github.com/stretchr/testify/suite.Run.func2()
/go/pkg/mod/github.com/stretchr/testify@v1.5.1/suite/suite.go:119
+0x10f
testing.tRunner()
/toolchain/go/src/testing/testing.go:991 +0x1eb
Previous read at 0x00c00035e418 by …
```
> test: fix race in some tests caused by `SetT`

- Dockerfile
This brings in an updated build of LVM2 that addresses a
segfault error. We were also missing libaio.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2188)
> fix: update LVM2

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
We need to activate logical volumes on boot so that storage providers,
like Rook, can work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2189)
> fix: activate logical volumes

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/app/machined/pkg/system/services/trustd.go
This skips running udevd, udevd-trigger, and timed when running in
container mode. Since the containers run as privileged containers
these services will contend with the host's equivalent services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2194)
> fix: skip services when in container mode

- Dockerfile
A number of storage providers depend on having open-iscsi installed
on the host. This adds open-iscsi along with any dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2196)
> feat: add open-iscsi

- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/manifest.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/mount/mount.go
- pkg/blockdevice/blockdevice.go
- pkg/blockdevice/blockdevice_darwin.go
- pkg/blockdevice/blockdevice_linux.go
- pkg/blockdevice/probe/probe.go
This adds a sentinel error for a missing partition table. This error
is used to detect if a partition table already exists when setting
up user defined disks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2215)
> fix: detect if partition table is missing

- internal/app/bootkube/main.go
Bootkube expects a clean manifests directory. This ensures that we
clean it up on a failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2223)
> fix: delete manifests dir on bootkube failure

- Dockerfile
This PR pulls in a newer kernel with CONFIG_CRYPTO_USER_API_HASH
support. This is needed for cilium 1.7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2224)
> chore: update kernel to support CONFIG_CRYPTO_USER_API_HASH

- docs/website/content/v0.6/en/configuration/v1alpha1.md
- internal/app/machined/pkg/runtime/configurator.go
- internal/app/networkd/pkg/networkd/netconf.go
- internal/app/networkd/pkg/nic/nic.go
- internal/app/networkd/pkg/nic/options.go
- pkg/config/types/v1alpha1/v1alpha1_types.go
This PR will introduce a new field to v1alpha1 configs that allows users
to set `dummy: true` when specifying interfaces. If present, we will
create a dummy interface with the CIDR information given. This is useful
for users that don't want to use loopback for things like ECMP (or want
more than one dummy interface).
The created dummy interface looked like this with `ip a`:
```
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
link/ether 66:4a:e3:5f:38:10 brd ff:ff:ff:ff:ff:ff
inet 10.254.0.5/32 brd 10.254.0.5 scope global dummy0
valid_lft forever preferred_lft forever
```
Will close #2186 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems …
> feat: allow ability to create dummy nics

- pkg/config/types/v1alpha1/v1alpha1_validation.go
This fixes a panic when `machine.network` is defined, but `nil`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2227)
> fix: check if machine networking is nil

- internal/app/machined/pkg/system/services/kubelet.go
For better security, kubelet shouldn't have access to contents of `/run`
directory which contains Talos services sockets and other system
information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2185)
> fix: isolate kubelet /run directory

- internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware.go
This PR aims to give users some extra info about where the machine
config is getting pulled from. The goal is to allow users to catch
things like typos in the config URL, and to validate that the platform
is set properly.
Will close #2131.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2206)
> chore: output where we are pulling configs for each platform

- docs/website/content/v0.6/en/guides/local/firecracker.md
Plugin `static` is used for IPAM on interfaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2232)
> docs: update firecracker with one more CNI plugin

- docs/website/content/v0.6.en.json
- docs/website/content/v0.6/en/guides/local/registry-cache.md
This can be expanded one day to air-gapped solution, but gives good
starting point for those who run clusters locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2237)
> docs: add local registry cache documentation

- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
This PR fixes a bug caused by azure disabling their metadata endpoint
for some headscratching reason. The config data is mounted only at first
boot (from what I recall) as a cdrom device essentially. This adds
support for trying to hit the metadata endpoint and, if it doesn't work,
falling back to the cdrom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2231)
> fix: attempt to pull machine config from mounted disk in azure

- .golangci.yml
- Dockerfile
This version is built with newer Go which fixes
`fatal error: mlock failed` on Ubuntu kernels which are actually
patched, but their minor version doesn't match Go expectations.
New linters were disabled to minimize the changes, and plan is to fix
the linting errors in subsequent PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2236)
> chore: upgrade golangci-lint to 1.27

- Makefile
- cmd/installer/pkg/install/manifest.go
This hopefully should fix errors like:
```
2020/06/25 18:23:22 attaching loopback device
2020/06/25 18:23:22 partitioning /dev/loop2 - ESP
2020/06/25 18:23:22 partitioning /dev/loop2 - EPHEMERAL
2020/06/25 18:23:22 formatting partition "/dev/loop2p1" as "fat" with label "ESP"
2020/06/25 18:23:22 detaching loopback device
2020/06/25 18:23:22 failed to format device: exit status 1: mkfs.vfat: can't open '/dev/loop2p1': No such file or directory
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2238)
> fix: make installer re-read partition table before formatting

- .drone.yml
- hack/drone.jsonnet
e2e tests are running in `/tmp/e2e` directory, so all the firecracker VM
virtual disk are going to `/tmp` directory. As `/tmp` was mounted as
`tmpfs`, this was putting high pressure on build host memory. Memory is
also used for docker containers, firecracker VMs, etc. Build host has
fast NVMe disks, so no good reason to keep `/tmp` in memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2242)
> chore: stop mounting /tmp for the build pipeline

- internal/app/init/main.go
- internal/app/machined/pkg/runtime/logging/cicrular.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/integration/api/logs.go
- internal/integration/cli/logs.go
- internal/integration/integration_test.go
- internal/pkg/circular/circular.go
- internal/pkg/circular/circular_test.go
- internal/pkg/circular/errors.go
- internal/pkg/circular/options.go
- internal/pkg/circular/reader.go
- internal/pkg/circular/streaming.go
- internal/pkg/kmsg/kmsg.go
This replaces logging to files with inotify following to pure in-memory
circular buffer which grows on demand capped at specified maximum
capacity.
The concern with previous approach was that logs on tmpfs were growing
without any bound potentially consuming all the node memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2230)
> feat: implement circular buffer for system logs

- docs/website/content/v0.5/en/configuration/v1alpha1.md
- docs/website/content/v0.6/en/configuration/v1alpha1.md
- internal/integration/provision/upgrade.go
- pkg/config/types/v1alpha1/doc.go
- pkg/config/types/v1alpha1/generate/generate.go
- pkg/config/types/v1alpha1/generate/init.go
- pkg/config/types/v1alpha1/generate/join.go
Update all k8s image references to point to the version specified by the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2241)
> fix: use kubernetes version in config generator

- .drone.yml
- hack/drone.jsonnet
CAPI-based steps are using docker Talos cluster built at `e2e-docker`
stage as a bootstrap cluster. Share the config via volume which is
attached to specific steps. Volume is temporary, but no longer resides
on `tmpfs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2244)
> chore: bring back tmp volume shared from e2e-docker to CAPI steps

- .golangci.yml
- cmd/installer/cmd/image.go
- cmd/talosctl/cmd/mgmt/config.go
- cmd/talosctl/cmd/talos/processes.go
- internal/app/init/main.go
- internal/app/machined/pkg/runtime/controller_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/runner/containerd/containerd_test.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/app/machined/pkg/system/services/machined.go
- internal/app/machined/pkg/system/services/networkd.go
- internal/app/machined/pkg/system/services/osd.go
- internal/app/machined/pkg/system/services/routerd.go
- internal/app/machined/pkg/system/services/timed.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/pkg/containers/containerd/containerd_test.go
- internal/pkg/containers/cri/cri_test.go
- internal/pkg/containers/image/resolver_test.go
- internal/pkg/cri/cri_test.go
- internal/pkg/provision/providers/firecracker/node.go
- pkg/retry/constant_test.go
- pkg/retry/exponential_test.go
- pkg/retry/linear_test.go
It makes sure our `//nolint:` directives are not redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2247)
> chore: enable nolintlint linter

- Dockerfile
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/containerd.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/pkg/mount/mount.go
- internal/pkg/mount/overlay.go
- internal/pkg/mount/pseudo.go
- internal/pkg/provision/providers/docker/node.go
- pkg/constants/constants.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2253)
> feat: add /system directory

- .codecov.yml
- .drone.yml
- hack/drone.jsonnet
As many pipelines inherit steps from `default_steps`, take out
`e2e-firecracker-short` from `default_steps`.
`e2e` pipeline only relies on `e2e-docker`.
`integration` pipeline does full firecracker run with `e2e-firecracker`.
`release` pipeline manually pulls in `e2e-firecracker-short` to be on
the safe side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2255)
> test: run `e2e-firecracker-short` for default pipeline only

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
- internal/pkg/circular/circular_test.go
Fixes #2243
These tests rely on some kind of sync between readers and writers, as if
circular buffer is overrun, test no longer runs as expected.
We use time-sensitive rate limiter to limit write speed to make sure
readers can always catch up. Lowering the rate should slow down writers
and make tests more likely to succeed.
For #2243, the failure was from buffer overrun: when overrun is
detected, `Watch` function closes the channel (and test "receives" zero
element).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2256)
> test: stabilize race unit-tests (circular, events)

- .drone.yml
- hack/drone.jsonnet
Just a copy of `integration` pipeline with the same trigger as `nightly`
pipeline, so we can have two separate pipelines and two notifications
for better visibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2259)
> test: run integration pipeline nightly

- internal/pkg/containers/containerd/containerd_test.go
I had to copy over some oci stuff from newer package version, but as we
for a long time use newer oic, we don't need a copy anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2262)
> test: resolve old TODO item

- hack/test/e2e.sh
This PR will make sure that, if we're going to retry sonobuoy, we run
the delete command first to clean up any dangling resources.
Closes #2266.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2271)
> chore: cleanup sonobuoy after failed attempts

- hack/test/e2e.sh
This PR fixes the fix where we try to cleanup sonobuoy. We did that
successfully, but still got errors b/c we were immediately trying to
create service accounts in a namespace that was being deleted. This
should fix that. The sonobuoy default wait period is 1hr, should be
plenty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2279)
> chore: wait for resource deletion in sonobuoy

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Arguments to `defer` are evaluate at the time `defer` statement is
executed, not during the `defer` callback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2282)
> fix: print correct sequence/task duration

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/system.go
- internal/app/machined/pkg/system/system_test.go
The problem was that flow to re-run the service with different
parameters was not consistent: it depends on whether services was loaded
before or not, but that is not reliable, as e.g. with bootstrap API
`bootkube` is loaded for the bootstrap and stays until reboot, and never
loaded for any other boot.
`Unload()` stops and removes the service completely so that new instance
of the service could be loaded and started.
This fixes the edge case with recovery API not running bootkube properly
before reboot after bootstrap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2284)
> fix: implement Unload() for services to make sure bootkube runs always

- cmd/talosctl/cmd/mgmt/cluster/create.go
- internal/integration/api/events.go
- internal/integration/api/logs.go
- internal/integration/provision/upgrade.go
- internal/pkg/cluster/check/default.go
- internal/pkg/cluster/check/reporter.go
- internal/pkg/cluster/check/service.go
- pkg/client/events.go
- pkg/client/resolver.go
Handling of multiple endpoints has already been implemented in #2094.
This PR enables round-robin policy so that grpc picks up new endpoint
for each call (and not send each request to the first control plane
node).
Endpoint list is randomized to handle cases when only one request is
going to be sent, so that it doesn't go always to the first node in the
list.
gprc handles dead/unresponsive nodes automatically for us.
`talosctl cluster create` and provision tests switched to use
client-side load balancer for Talos API.
On the additional improvements we got:
* `talosctl` now reports correct node IP when using commands without
`-n`, not the loadbalancer IP (if using multiple endpoints of course)
* loadbalancer can't provide reliable handling of errors when upstream
server is unresponsive or …
> feat: add round-robin LB policy to Talos client by default

- internal/app/osd/internal/reg/reg.go
- internal/integration/cli/logs.go
- internal/integration/cli/restart.go
There were three problems:
* cli tests did commands in sequence assuming they all hit the same
node, but with load-balancing it's no longer true
* restart test was affected, as it hit different node for check after
restart, and it succeeded immediately, while on original node process
was still starting which resulted in failure in the next tests; replace
the check to make sure service is up and healthy, so that test leaves
cluster in a good state
* restart API response had wrong format (no message returned) which
resulted in failures with apid proxy (when used with `-n`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/ …
> test: fix cli tests after load-balancing got enabled

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/talos/health.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/integration/base/api.go
- internal/pkg/cluster/check/default.go
- internal/pkg/cluster/check/kubernetes.go
- pkg/kubernetes/kubernetes.go
Talos will mark node as schedulable if it was previously cordoned by
Talos (for upgrade, reset, etc.)
If user marked node as not schedulable, Talos won't change it on boot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2291)
> feat: uncordon nodes automatically on boot

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/kubernetes/kubernetes.go
1. Increase retry timeout.
2. Use timeout per attempt.
3. Check for node readiness as a gate to succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2296)
> fix: improve node uncordon tasks

- cmd/talosctl/cmd/mgmt/cluster/create.go
- docs/talosctl/talosctl_cluster_create.md
- hack/test/e2e-docker.sh
- hack/test/e2e-firecracker.sh
When cluster fails to be bootstrapped or it fails the health check, it's
hard to find the root cause without the logs.
This change adds optional crashdump (it dumps firecracker logs or docker
logs) after provisioning failure. It's not enabled by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2300)
> feat: print crash dump in `talosctl cluster create` on failure 

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
Some of the event tests rely on publishing more events than buffer
capacity, so consumers should be able to keep up with the producer to
avoid hitting buffer overrun.
Producer was rate-limited already, now adding rate limiting for consumer
with higher burst, it should allow consumers to reach blocked state, but
syncronizes them a bit with each other.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2301)
> test: update events test with more flow control

- cmd/talosctl/cmd/talos/events.go
- internal/app/machined/pkg/runtime/controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_test.go
For each task, name follow function name for now (but it could be
customized if needed).
Phases are after main theme of the tasks inside the phase.
Task and phase events are now displayed in `talosctl events`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2289)
> feat: add names to tasks and phases

- internal/app/machined/pkg/system/runner/containerd/containerd_test.go
I'm not sure if this is going to stop it, but feels like we're hitting
some race condition in containerd itself, so attempt to sleep a bit in
between the container launches to avoid the errors.
```
=== RUN   TestContainerdSuite/TestRunTwice
2020/07/10 18:57:24 state Running: Started task 036de7a9-f667-48e8-905f-216233980f94 (PID 4964) for container 036de7a9-f667-48e8-905f-216233980f94
TestContainerdSuite/TestRunTwice: containerd_test.go:179:
Error Trace:	containerd_test.go:179
Error:      	Received unexpected error:
failed to create task: "036de7a9-f667-48e8-905f-216233980f94": dial unix \00/containerd-shim/f88fff9fe9795db4229846b09b2da816f6bd981b8112345486ff3b5653892920.sock: connect: connection refused: unknown
Test:       	TestContainerdSuite/TestRunTwice
--- FAIL: TestContainerdSuite …
```
> test: workaround famous flaky Containerd.RunTwice test

- docs/website/content/v0.4/en/guides/cloud/azure.md
- docs/website/content/v0.5/en/guides/cloud/azure.md
- docs/website/content/v0.6/en/guides/cloud/azure.md
This PR updates the worker flags for azure. Fixes an issue where, if you
have multiple subnets and the talos one isn't default, the workers and
control plane nodes came up on different subnets. Requires updating the
firewalls if they don't come up in the same subnet, so this is better
UX.
Also added a note that azure support is broken in v0.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2310)
> docs: update worker creation flags for azure docs

- Dockerfile
- Makefile
go1.14.5 (released 2020/07/14) includes security fixes to the
crypto/x509 and net/http packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2314)
> chore: upgrade Go to 1.14.5

- internal/pkg/provision/providers/docker/crashdump.go
Small bug resulted in container names being cut in the wrong way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2319)
> fix: update container name in docker crashdump

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
We often see in the logs errors like:
```
machined Unknown [/machine.MachineService/Upgrade] 6.984959636s unary Unauthorized (:authority=unix:/run/system/machined/machine.sock;content-type=application/grpc;proxyfrom=172.21.0.2,172.21.0.3,172.21.0.4;user-agent=grpc-go/1.26.0)
```
```
* 172.21.0.4: rpc error: code = Unknown desc = Unauthorized
```
These errors are not related to the API handling, but most probably
coming from one of the actions performed by the handler. Wrap the errors
to get better debugging output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2320)
> fix: wrap errors in upgrade API handler

- internal/pkg/provision/providers/firecracker/firecracker.go
- pkg/config/types/v1alpha1/generate/generate.go
- pkg/config/types/v1alpha1/generate/init.go
- pkg/config/types/v1alpha1/generate/join.go
- pkg/config/types/v1alpha1/generate/options.go
Firecracker never executes the bootloader, so kernel args passed to the
installer aren't used, but if the same disk image is used to boot Talos
e.g. in `qemu`, it fails to set up console properly for example.
This PR simply provides those kernel args to the installer so that
they're persisted in the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2321)
> test: provider correct installer kernel args for firecracker

- cmd/talosctl/cmd/talos/processes.go
- go.mod
- go.sum
This removes dependency on `bytefmt` package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2325)
> refactor: use `humanize.Bytes` everywhere

- internal/pkg/provision/providers/firecracker/create.go
- internal/pkg/provision/providers/firecracker/destroy.go
- internal/pkg/provision/providers/firecracker/node.go
- internal/pkg/provision/providers/vm/crashdump.go
- internal/pkg/provision/providers/vm/loadbalancer.go
- internal/pkg/provision/providers/vm/network.go
- internal/pkg/provision/providers/vm/process.go
Second part of refactoring to split common logic for VM provisioners
from Firecracker provisioner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2328)
> chore: extract loadbalancer, network, crashdup and process from firecracker

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Previously log said `done` for the failed items which seemed not obvious
when combined with the error message later on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2333)
> fix: log messages properly when sequence/phase/task fails

- internal/pkg/kmsg/reader_test.go
Due to the race between `Read()` and context cancellation, error might
be returned which we can safely ignore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2352)
> test: fix racy test ReaderNoFollow

- cmd/talosctl/cmd/mgmt/cluster/create.go
- docs/talosctl/talosctl_cluster_create.md
- internal/pkg/provision/options.go
- internal/pkg/provision/providers/docker/node.go
This allows to override default `0.0.0.0` (`*`) to a specific IP to
avoid conflicts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2353)
> test: add an option to bind docker to specific host IP

- Dockerfile
- Makefile
This also brings in multi-arch pkgs and tools, but we're not consuming
arm64 images yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2343)
> chore: upgrade pkgs and tools for Go 1.14.6

- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_other.go
This fixes the build on arm64.
The fix itself is part of PR #2156.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2355)
> fix: skip vmware platform for !amd64

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
For single-node upgrades if we drop the CRI state, API server won't
start after reboot and this breaks the control plane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2340)
> fix: skip removing CRI state when doing upgrade with preserve

- .drone.jsonnet
This should provide caching for the builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2357)
> chore: use outer docker as buildkit instance

- internal/pkg/kubeconfig/admin.go
This ensures that the generated kubeconfig has a namespace. This fixes
an edge case when a user attempts to use the kubeconfig from within a
pod of a different kubernetes cluster. If the kubeconfig does not have a
namespace, kubectl will use the "in cluster namespace" which is
unexpected, especially if the "in cluster namespace" does not exist in
the target cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2361)
> fix: generate admin kubeconfig with default namespace

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
This bumps some timeouts that can cause nodes to reboot too quickly when
things go wrong, making it difficult to debug. Give users a little bit
more time before we reboot automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2362)
> fix: bump timeouts

- internal/app/timed/pkg/ntp/ntp.go
- internal/pkg/cluster/check/default.go
Talos depends on accurate time for many actions, so many services depend
on timed successful health check. If timed fails to do initial sync, it
enters pretty long wait loop for the next attempt which might not come
in time for the boot timeout. Instead, fail timed service on initial
sync and rely on service restart for another attempt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2366)
> fix: fail ntpd service if initial time sync fails

- Dockerfile
This PR pulls in the latest pkgs build, which contains a kernel with
FUSE support enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2365)
> feat: pull in kernel with fuse support 

- .drone.jsonnet
- Makefile
- cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
- hack/test/provision-tests.sh
- internal/pkg/provision/providers/vm/loadbalancer.go
- internal/pkg/provision/request.go
We're not using load balancer for `apid` (always using client-side load
balancing), so we can remove this safely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2354)
> test: remove apid load balancer for firecracker

- hack/test/e2e.sh
- internal/integration/base/base.go
- internal/integration/base/cli.go
- internal/integration/base/cluster.go
- internal/integration/base/discovery_k8s.go
- internal/integration/integration_test.go
Fixes #2330
CLI tests require node discovery as `--nodes` flag is enforced for most
of the `talosctl commands`.
For clusters created via `talosctl cluster create`, cluster provisioner
state provides all the necessary information, but clusters created via
CAPI don't have the state attached.
API tests rely on Talos and Kubernetes APIs to fetch kubeconfig and
access Nodes K8s API.
CLI tests should rely only on CLI tools, so we use `kubectl get nodes` +
`talosctl kubeconfig` to fetch list of master and worker nodes.
This discovery method relies on "bootstrap" node being set in
`talosconfig` (to fetch `kubeconfig`).
--- …
> test: provide node discovery for cli tests via kubectl

- internal/app/timed/pkg/ntp/ntp.go
- internal/app/timed/pkg/timex/timex.go
Status big `STA_UNSYNC` should be cleared otherwise kernel assumes that
time is not sync. `STA_PLL` is set to notify kernel that we apply offset
adjustments periodically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2374)
> fix: update status when adjusting the time

- go.mod
- go.sum
- internal/integration/base/cli.go
- internal/pkg/cluster/check/kubernetes.go
- pkg/kubernetes/kubernetes.go
Fixes #2350
This also brings in a fix for `coredns` tolerations from
https://github.com/talos-systems/bootkube-plugin/pull/19.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2375)
> feat: taint master nodes with `NoSchedule` taint

- .drone.jsonnet
This seems to be the way to do it for kube-runner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2379)
> chore: really mount /tmp in CI as tmpfs

- internal/app/machined/pkg/system/system.go
Logs:
```
[   27.739699] [talos] bootstrap request received
[   27.740500] [talos] bootstrap sequence: 3 phase(s)
[   27.741297] [talos] phase etcd (1/3): 1 tasks(s)
[   27.741991] [talos] task bootstrapEtcd (1/1): starting
[   27.742855] [talos] service[etcd](Failed): Failed to run pre stage: context canceled
[   27.744355] [talos] service[etcd](Finished): Bootstrap requested
```
`etcd` was stopped, `Finished` state was injected, but new service never
started. This is most likely a race in `Start`: it removes service from
`running` after it stops, but event that service got stopped is sent
before that, so task might see service as stopped, unload it, load it
back, but `Start()` will be no-op as service is considered to be
running. …
> fix: workaround edge case for etcd re-injection on bootstrap

- Makefile
- cmd/talosctl/cmd/mgmt/cluster/create.go
- docs/talosctl/talosctl_cluster_create.md
- hack/test/e2e-firecracker.sh
- hack/test/e2e-qemu.sh
- hack/test/e2e.sh
- internal/integration/provision/upgrade.go
- internal/pkg/provision/options.go
- internal/pkg/provision/providers/firecracker/create.go
- internal/pkg/provision/providers/firecracker/kernel.go
- internal/pkg/provision/providers/firecracker/node.go
- internal/pkg/provision/providers/qemu/create.go
- internal/pkg/provision/providers/qemu/launch.go
- internal/pkg/provision/providers/qemu/node.go
- internal/pkg/provision/providers/qemu/qemu.go
- internal/pkg/provision/request.go
Fixes #2363 #2364 #2370 #2371
Several changes packed together:
* use compressed `vmlinuz` everywhere, firecracker provisioner
uncompresses it before first use, drop `vmlinux`
* handle reboots in qemu launcher to support reset API case, update
empty disk check to handle reset behavior (erasing partition table)
* make bootloader support default in provisioners, and flag to disable
that
* early support for target architecture for qemu provisioner
This should allow us to use `qemu` in CI/CD (not included into this PR):
integration test passes with qemu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2373)
> test: update qemu/firecracker provisioners

- .drone.jsonnet
- internal/integration/provision/upgrade.go
qemu opens up a bunch of possibilities, including the bootloader
testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2381)
> chore: use qemu instead of firecracker in CI

- internal/integration/provision/upgrade.go
'cordonAndDrainNode' task sometimes takes 5 minutes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2384)
> test: bump timeout for upgrade tests

- cmd/talosctl/cmd/talos/memory.go
- cmd/talosctl/cmd/talos/mounts.go
- cmd/talosctl/cmd/talos/processes.go
- cmd/talosctl/cmd/talos/routes.go
- cmd/talosctl/cmd/talos/stats.go
- docs/talosctl/talosctl.md
- docs/talosctl/talosctl_stats.md
Aliases are close to regular UNIX commands.
Fixes #2195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2383)
> chore: add aliases to some `talosctl` commands

- hack/test/e2e-firecracker.sh
- hack/test/e2e-qemu.sh
As the build runs inside containers which are part of a single pod, we
need to clean up networking bits (bridge interface, etc.), so that it
doesn't cause problems for other steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2386)
> test: destroy clusters in e2e tests (qemu/firecracker)

- hack/test/e2e-docker.sh
- hack/test/e2e-firecracker.sh
- hack/test/e2e-qemu.sh
- hack/test/e2e.sh
This relies on registry caching mirrors running in the CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2349)
> test: use registry mirrors in CI

- internal/pkg/provision/providers/qemu/arch.go
- internal/pkg/provision/providers/qemu/create.go
- internal/pkg/provision/providers/qemu/launch.go
- internal/pkg/provision/providers/qemu/node.go
- internal/pkg/provision/providers/qemu/pflash.go
- internal/pkg/provision/providers/qemu/qemu.go
- internal/pkg/provision/providers/vm/state.go
This includes better machine args, support for UEFI parallel flash
images required as low-level bootloader, and miscallenous cleanups.
Qemu support was enabled for mapping host random source to the guest as
entropy source to prevent stalls on the boot waiting for the entropy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2397)
> fix: update qemu launcher on arm64 to boot Talos properly

- cmd/talosctl/cmd/mgmt/config.go
- docs/talosctl/talosctl_gen_config.md
This PR adds a flag to tweak the persistence value for talosctl gen
config.
Will close #2401.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2402)
> feat: add persist flag to gen config

- docs/website/content/v0.6/en/configuration/v1alpha1.md
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/networkd/pkg/address/static.go
- internal/app/networkd/pkg/networkd/netconf.go
- internal/app/networkd/pkg/networkd/netconf_test.go
- internal/app/networkd/pkg/networkd/networkd_test.go
- internal/pkg/containers/cri/containerd/config.go
- internal/pkg/containers/cri/containerd/config_test.go
- internal/pkg/containers/cri/containerd/containerd.go
- internal/pkg/containers/image/resolver.go
- internal/pkg/containers/image/resolver_test.go
- internal/pkg/provision/providers/firecracker/firecracker.go
- pkg/config/provider.go
- pkg/config/types/v1alpha1/generate/generate.go
- pkg/config/types/v1alpha1/generate/options.go
- pkg/config/types/v1alpha1/v1alpha1_provider.go
- pkg/config/types/v1alpha1/v1alpha1_types.go
- pkg/config/types/v1alpha1/v1alpha1_validation.go
This make the config provider a pure interface definition by removing
all concrete internal types, and making them an interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2392)
> refactor: remove structs from config provider

- pkg/kubernetes/kubernetes.go
While waiting for node ready condition, API server endpoint might return
networking errors (e.g. if endpoint is a RR DNS record).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2410)
> fix: retry non-HTTP errors from API server

- hack/test/capi/cluster-aws.yaml
- hack/test/capi/cluster-gcp.yaml
- hack/test/e2e-capi.sh
- hack/test/e2e.sh
This PR will update the CI testing to make use of our control plane
provider, as well as the other CAPI components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2313)
> chore: update capi CI manifests to use control planes

- hack/test/e2e.sh
This PR replaces python with python3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2415)
> fix: update e2e scripts to work with python3

- go.mod
- go.sum
- internal/app/machined/pkg/system/services/etcd.go
- internal/pkg/etcd/etcd.go
- pkg/constants/constants.go
This upgrades etcd to latest v3.4.x version as smooth upgrade from
version 3.3.22 in 0.6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2419)
> feat: upgrade etcd to 3.4.10

- pkg/provision/providers/docker/docker.go
This avoids pause on container startup when `networkd` tries to do DHCP
over `eth0` (which fails for obvious reasons). Interfaces are
pre-configured in Docker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2420)
> fix: ignore eth0 interface in docker provisioner

- go.mod
The version we had was pre-push to master and it's invalid version:
```
go get github.com/talos-systems/talos@master
go: github.com/talos-systems/talos master => v0.7.0-alpha.0.0.20200818212414-6a7cc0264819
go get: github.com/talos-systems/talos@v0.7.0-alpha.0.0.20200818212414-6a7cc0264819 requires
github.com/talos-systems/talos/pkg/machinery@v0.0.0-00010101000000-000000000000:
invalid version: unknown revision 000000000000
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2438)
> chore: update machinery version in go.mod

- cmd/talosctl/cmd/mgmt/cluster/create.go
- docs/talosctl/talosctl_cluster_create.md
As we're going to make API bootstrapping a preferred method of
bootstrapping Talos clusters, our defaults should reflect that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2440)
> feat: make boostrap via API default choice in talosctl cluster create

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/cluster/bootstrap.go
- pkg/cluster/cluster.go
- pkg/provision/access/adapter.go
It should be useful in any project provisioning Talos clusters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2439)
> refactor: extract cluster bootstrapper via API as common component

- internal/app/apid/main.go
- internal/app/bootkube/main.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/system/runner/containerd/containerd.go
- internal/app/machined/pkg/system/runner/containerd/containerd_test.go
- internal/app/machined/pkg/system/runner/runner.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/bootkube.go
- internal/app/machined/pkg/system/services/networkd.go
- internal/app/machined/pkg/system/services/timed.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/app/networkd/main.go
- internal/app/timed/main.go
- internal/app/trustd/main.go
- internal/pkg/etcd/etcd.go
- pkg/machinery/config/configloader/configloader.go
In order to perform upgrades the way we would like, it is important that
we avoid any bind mounts into containers. This change ensures that all
system services get their config via stdin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2443)
> fix: pass config via stdin

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/machinery/client/config/config.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
This should simplify the code when new clusters are created and Talos
client config is injected.
Also refactored client config to have `ReadFrom` as common denominator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2449)
> chore: add a method to merge Talos client config

- docs/website/content/v0.4.en.json
- docs/website/content/v0.4/en/troubleshooting/machine-reset.md
- docs/website/content/v0.5.en.json
- docs/website/content/v0.5/en/troubleshooting/machine-reset.md
- docs/website/content/v0.6.en.json
- docs/website/content/v0.6/en/troubleshooting/machine-reset.md
This PR adds a simple doc on how to do a talos machine reset. This
command was introduced all the way back on v0.4 so the docs are added
everywhere.
Will close #2095 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2463)
> docs: add reset doc

- .drone.jsonnet
- Dockerfile
- Makefile
- pkg/machinery/constants/constants.go
`vmlinux` (uncompressed kernel) shouldn't be much useful to the people
as it can't be booted directly with most of the boot tools (it's too
huge). We had it enabled for firecracker, but now firecracker has
support for decompressing `vmlinuz` on the fly.
So, to reduce confusion, make assets smaller, remove `vmlinux`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2464)
> chore: drop vmlinux from assets

- Dockerfile
We need syslinux to create an ISO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2475)
> fix: add syslinux to create ISO

- docs/website/components/DocumentationDropdown.vue
- docs/website/components/Header.vue
This promotes the v0.6 docs from pre-release status to stable, and make v0.6
the default docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2477)
> docs: graduate v0.6 docs

- docs/website/content/v0.5/en/guides/getting-started/talosctl.md
- docs/website/content/v0.6/en/guides/getting-started/talosctl.md
- internal/app/machined/pkg/system/services/apid.go
This is what happens when massive find-replace goes wrong...
Change should be cosmetic though, it doesn't affect operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2478)
> fix: change apid container image name to expected value

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/udevd.go
- internal/app/machined/pkg/system/services/udevd_test.go
- pkg/cmd/cmd.go
Experimental PR to move those actions to udevd healthchecks for
automatic retries and better error reporting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2480)
> refactor: move udevadm trigger/settle to udevd healthcheck

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
This adds special handling for files that are static pods. This is a
workaround for v0.6.
(cherry picked from commit 7930f7480aef11e53a649aff8e4d28a1642ed36a)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2482)
> fix: allow static pod files

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
There were two issues:
* directories leading up to the path were created with effectively
`000` perms, as `os.ModeDirectory` is a directory flag bit, not perms
* permssions of files created via `open(2)` syscall are affected by
`umask(2)`, which in turn is `0022` by default. As `umask` gets
inherited via `fork/exec`, it's better not to change it in `machined`,
so we use explicit `chmod(2)` call which is not affected by `umask(2)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2484)
> fix: update permissions for directories and files created via extraFiles

- Dockerfile
This stage is already derived from `rootfs-base`, so this copy statement
should be doing nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2483)
> chore: remove extra COPY from rootfs

- internal/app/machined/pkg/system/services/udevd.go
We found that the debug option is so noisy, that if machine debug is enabled, udevdadm
settle becomes extremely slow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2488)
> fix: remove udevd debug flag

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/provision/providers/docker/docker.go
- pkg/provision/providers/firecracker/firecracker.go
- pkg/provision/providers/qemu/qemu.go
Docker for OS X doesn't leave any other option, as node IPs are not
routeable from the host, and current default was to use all the control
plane node IPs in round-robin LB.
Fixes #2495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2496)
> fix: default endpoint to 127.0.0.1 for Docker/OS X

- Dockerfile
This brings in a version of packages that have been built with gcc 10.2.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2497)
> feat: use latest packages

- Dockerfile
- Makefile
There's no way to use variable substitution in `COPY --from=`, but we
can use that in `FROM`.
Also bump TOOLS version to finish bump from #2497.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2500)
> refactor: deduplicate packages version in Dockerfile

- internal/app/machined/main.go
If bootloader meta failed to be found/to be reverted, don't abort the
whole sequence of actions leading to reboot, otherwise control returns
back and machined tries to run next sequence in failed state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2501)
> fix: don't abort reboot sequence on bootloader meta failure

- cmd/installer/pkg/ova/ova.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
Multiple fixes from local testing:
* `.ova` file shouldn't contain `./` entries
* fix error message (`err` is `nil` at that point)
* drop `efi` boot key (BIOS mode works fine)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2502)
> fix: update vmware image and platform

- cmd/talosctl/cmd/talos/upgrade-k8s.go
- docs/talosctl/talosctl.md
- docs/talosctl/talosctl_upgrade-k8s.md
- pkg/cluster/kubernetes/kubernetes.go
- pkg/cluster/kubernetes/upgrade.go
- pkg/machinery/constants/constants.go
This command handles upgrading Kubernetes control plane from 1.18.x and
1.19.x to 1.19.x.
There's automatic handling of pod-checkpointer to speed up
kube-apiserver upgrades.
Separate PR will add K8s upgrade to integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2505)
> feat: implement command `talosctl upgrade-k8s`

- .drone.jsonnet
- internal/integration/provision/upgrade.go
Add Kubernetes upgrade as part of the provisioning (upgrade tests):
first K8s control plane is upgraded, then Talos is upgraded (with
kubelet), and e2e test is run last.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2508)
> test: verify kubernetes control plane upgrade in provision tests

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
This PR fixes some small bugs we were seeing where grub was booting in
blind mode. Let's keep grub from trying to get too fancy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2513)
> fix: tell grub to use console output

- go.mod
- go.sum
- internal/app/bootkube/assets.go
This updates bootkube-plugin with PR
https://github.com/talos-systems/bootkube-plugin/pull/21.
Flannel image is chosen based on host architecture.
Fixes #2510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2519)
> feat: update Flannel to 0.12, support for arm64

- cmd/talosctl/cmd/mgmt/cluster/create.go
This way config doesn't contain k8s version, so Talos will pick the
default one for the version being run. This allows to do experiments
more easily, and also allows to boot older Talos (e.g. 0.5.1) with
`talosctl cluster create`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2523)
> fix: don't enforce k8s version in `talosctl cluster create` by default

- pkg/provision/internal/inmemhttp/inmemhttp.go
- pkg/provision/providers/firecracker/launch.go
- pkg/provision/providers/qemu/controller.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/vm/controller.go
- pkg/provision/providers/vm/launch.go
- pkg/provision/result.go
Fixes #2515
This implements simple HTTP API which should cover same methods as IPMI
methods in Sidero.
Examples:
```
$ curl http://172.20.0.1:34791/status
{"PoweredOn":false}
```
```
$ curl -X POST http://172.20.0.1:34791/poweroff
```
API listens on bridge address, each VM has unique port which can be
found in cluster state as `apiport: NNNN`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2516)
> test: implement API for QEMU VM provisioner

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- cmd/talosctl/cmd/talos/upgrade-k8s.go
- docs/talosctl/talosctl_gen_config.md
- docs/talosctl/talosctl_upgrade-k8s.md
- internal/integration/provision/upgrade.go
- pkg/cluster/kubernetes/upgrade.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
This is one step towards running Talos on non-amd64 architectures (e.g. arm64).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2525)
> feat: use architecture-specific image for core k8s components

- internal/app/machined/pkg/system/services/etcd.go
Required to start etcd on arm64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2528)
> fix: set environment variable for etcd on arm64

- cmd/talosctl/cmd/talos/time.go
This PR changes the headers for issuing `talosctl time` to make it a bit
clearer which time is being reported in each column.
Will close #2341 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2530)
> chore: update ntp time headers

- internal/app/networkd/pkg/networkd/networkd.go
An invalid interface set as a bond's subinterface should produce an
error, but it should not panic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2532)
> fix: gracefully handle invalid interfaces in bond

- internal/app/networkd/pkg/address/static.go
- internal/app/networkd/pkg/networkd/netconf.go
- internal/app/networkd/pkg/nic/nic.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
This PR allows for the ability to specify neither CIDR nor DHCP in the
talos machine config. The result here should allow for things like SLAAC
addressing with ipv6.
Will close #2486 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2518)
> feat: allow for link local networking

- Makefile
- pkg/machinery/constants/constants.go
This addresses CVE-2020-14386.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2537)
> feat: ugrade Linux kernel to 5.8.10

- Dockerfile
- pkg/constants/constants.go
This addresses CVE-2020-14386.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2538)
> feat: upgrade Linux kernel to 5.8.10

- cmd/talosctl/cmd/talos/images.go
- docs/talosctl/talosctl.md
- docs/talosctl/talosctl_images.md
- internal/app/bootkube/assets.go
- internal/app/bootkube/images/images.go
- internal/integration/cli/images.go
- pkg/machinery/constants/constants.go
This adds a command that lists all of the images used by Talos. This is
useful in the case of airgap installs, so that users will know which images
to pull.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2543)
> feat: add images command

- go.mod
- go.sum
- internal/app/machined/internal/install/install.go
- internal/pkg/containers/image/image.go
This uses go-retry feature
(https://github.com/talos-systems/go-retry/pull/3) to print errors being
retried.
If image is not found in the index, abort retries immediately.
Don't pull installer image twice (if already pulled by the validation
code before).
Fixes #2527 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2548)
> fix: retry image pulling, stop on 404, no duplicate pulls

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
This makes EFI install path "standard" which should (hopefully) help
with some UEFI implementations.
Fixes #2556
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2564)
> fix: enable --removable options for GRUB

- Dockerfile
- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- cmd/talosctl/cmd/talos/images.go
- pkg/images/images.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/constants/constants.go
Machinery is supposed to be consumed without special build instructions,
so move images to "main" talos tree.
As config implementation is in the machinery, I had to drop the default
installer image there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2565)
> fix: move installer image variables out of machinery

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
This PR adds a small note to the config docs to detail how to do link
local networking like SLAAC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2567)
> docs: add note around link-local addressing

- .drone.jsonnet
These targets don't inherit from the common step definition, so they
were missing correct platform list which was in turn making them fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2574)
> chore: fix 'push' targets

- internal/app/machined/pkg/system/runner/containerd/containerd_test.go
- internal/app/machined/pkg/system/runner/containerd/import.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/bootkube.go
- internal/app/machined/pkg/system/services/networkd.go
- internal/app/machined/pkg/system/services/routerd.go
- internal/app/machined/pkg/system/services/timed.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/pkg/containers/image/image.go
This bug is sometimes reproducible with QEMU/arm64, as it runs really
slow. Looks like multiple concurrent image unpacks sharing some layers
might fail unexpectedly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2575)
> fix: retry container image import

- docs/website/content/v0.6/en/guides/local/docker.md
- docs/website/content/v0.7/en/guides/local/docker.md
This PR fixes a docs bug where we were still referencing `talos_default`
as the cluster name. It should be `talos-default` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2579)
> docs: fix cluster name in docker docs

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
This adds a check that ensures the cluster DNS name is valid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2554)
> feat: validate cluster DNS name

- Dockerfile
- internal/app/bootkube/images/images.go
- pkg/version/version.go
Flannel CNI image default was hardcoded in the bootkube-plugin, so it
might become outdated as `$PKGS` get rebuilt. Fix that by embedding
`$PKGS` variable with the Talos build.
Note: we might want to print `$PKGS` variable with `talosctl version`
for easier troubleshooting (or version tag is enough?).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2581)
> fix: make Flannel CNI image follow `$PKGS` version

- internal/pkg/kubeconfig/admin.go
This allows for more clean merge of multiple kubeconfigs from different
Talos clusters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2584)
> fix: provide unique username in generated kubeconfig

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/app/machined/pkg/system/services/trustd.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Adds the capability to diasable NTP when it cannot be provided in the deployed network
When a cluster is deployed in environment where NTP cannot be provided Talos can be enabled to run without NTP server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2583)
> feat: add support for disabling time

- cmd/talosctl/cmd/talos/kubeconfig.go
- docs/talosctl/talosctl_kubeconfig.md
- internal/integration/cli/kubeconfig.go
This also refactors much of the CLI code for the `talosctl kubeconfig`:
1. Do all the checks before fetching kubeconfig from the server: as
kubeconfig generation takes a few seconds, it doesn't make sense to
generate it if it's not going to be used.
2. Unify most of merge & write directly features.
3. Don't use ExtractTarGz method to be more flexible.
4. Allow custom paths for kubeconfig, whether it is a directory or full
path to the file to be created.
Fixes #2151
> feat: support custom filename for talosctl kubeconfig

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/cluster/show.go
This shows cluster state along with the IPs, resources, node roles, etc.
Example (with Docker):
```
$ talosctl cluster create
validating CIDR and reserving IPs
generating PKI and tokens
creating network talos-default
creating master nodes
creating worker nodes
waiting for API
bootstrapping cluster
waiting for etcd to be healthy: ...
waiting for etcd to be healthy: 1 error occurred:
* 10.5.0.2: service "etcd" not in expected state "Running": current state [Preparing] Running pre state
waiting for etcd to be healthy: 1 error occurred:
* 10.5.0.2: service is not healthy: etcd
waiting for etcd to be healthy: OK
waiting for bootkube to finish: ...
waiting for bootkube to finish: 1 error occurred:
* 10.5.0.2: service "bootkube" not in expected state ["Finished" "Skipped"]: current state …
```
> feat: show cluster state when `talosctl cluster create` finishes

- pkg/cli/context.go
Bug was that it required three ^C to exit immediately instead of two.
> fix: make CLI context exit immediately on second ^C

- cmd/talosctl/cmd/talos/kubeconfig.go
- docs/talosctl/talosctl_kubeconfig.md
- go.mod
- go.sum
- internal/integration/cli/kubeconfig.go
- internal/pkg/kubeconfig/kubeconfig.go
- internal/pkg/kubeconfig/merge.go
- internal/pkg/kubeconfig/merge_test.go
Kubeconfig merge was completely rewritten to be "smarter":
* automatically apply renames done at previous stages to avoid asking
over and over again (in general should ask just once)
* skip checks if parts of the config match exactly
* allow overwrite as an option
* flexible way to control the output
* activating context in the end
* custom merged context name
Fixes #2578
Fixes #2587
Fixes #2577
> feat: use kubeconfig merge in `talosctl kubeconfig` by default

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/talos/kubeconfig.go
- docs/talosctl/talosctl_cluster.md
- docs/talosctl/talosctl_cluster_create.md
- internal/pkg/kubeconfig/kubeconfig.go
Kubeconfig is merged into `~/.kube/config` with rename option
(existing configuration is never overwritten).
If endpoint was used, it is automatically put into the `kubeconfig`.
This should make OS X experience literally `talosctl cluster create`
followed by any `kubectl get ...`.
Fixes #2603 
> feat: pull kubeconfig from the cluster on successful `cluster create`

- CHANGELOG.md
This is the official v0.7.0-alpha.4 release.
> release(v0.7.0-alpha.4): prepare release

- cmd/talosctl/cmd/talos/dashboard/components/tables.go
The problem was that process stats diff is only available on the second
poll from the Talos API, while list of processes might be availalbe
immediately. So on the first poll we can't sort the processes, but still
talosctl shouldn't crash.
> fix: nil pointer panic in talosctl dashboard

- Makefile
- hack/release.sh
This uses `talosctl images`. This way it's easy to find installer image
or talos image for any release.
> chore: publish list of images to release notes

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
Prior fix was incorrect as the platform is empty when installing to real
hardware. Looks like `--removable` does nothing when platform is not
UEFI, so we can have it always enabled.
> fix: apply --removable option always to get standard UEFI filename

- Makefile
This brings in new kernel configs which includes the following PRs:
* https://github.com/talos-systems/pkgs/pull/174
* https://github.com/talos-systems/pkgs/pull/171
> chore: bump pkgs version

- internal/app/machined/pkg/runtime/platform.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/register.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_other.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/networkd/pkg/networkd/networkd.go
- pkg/download/download.go
Context is passed there for proper cancellation and timeouts.
https://github.com/talos-systems/talos/issues/2318
> chore: add Context as param to some methods of `Platform` interface

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/machinery/constants/constants.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/qemu/qemu.go
This allows to change `Shutdown()` API behavior to halt the system
instead of powering it off.
This is useful for QEMU provisioner, as it doesn't distinguiush between
power off and reboot.
> feat: implement talos.shutdown=[halt|poweroff] kernel argument

- cmd/talosctl/cmd/talos/health.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
- internal/integration/base/cluster.go
The problem was that some of the health checks sort the list of the
nodes in place (via `sort.Strings()`). If cluster info provider returns
original slice, it might be mutated in such a way that it gets
corrupted.
We never noticed it before CAPI clusters, as in our tests IPs are
assigned sequentially, and sort operation is a no-op.
Specifically, the problem was with the `Nodes()` function, it returns
`append(controlPlaneNodes, workerNodes...)` slice, which by definition
might share memory with `controlPlaneNodes` slice. For example,
if control plane nodes were `4, 5, 6` and worker nodes were `3`, the
returned slice will be `4, 5, 6, 3`, and it shares memory with
`controlPlaneNodes` slice (firs three items). If we apply `sort` to the
returned slice, it re-orders it as `3, 4, 5, 6`, but as …
> fix: random failures in cluster health checks

- Dockerfile
- Makefile
- cmd/talosctl/cmd/talos/images.go
- internal/app/bootkube/images/images.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/constants/constants.go
- pkg/version/version.go
This introduces newly built multi-arch images from
`talos-systems/extras`.
Also fixed default installer image if config is missing.
Fixes #2509 
> feat: bring in install-cni & pod-checkpointer from extras packages

- CHANGELOG.md
This is the official v0.7.0-alpha.5 release.
> release(v0.7.0-alpha.5): prepare release

- pkg/provision/internal/inmemhttp/inmemhttp.go
- pkg/provision/providers/qemu/launch.go
Missing timeout in shutdown is the only reason I could find for Sfyra
tests being stuck on teardown.
> test: potential fix for talosctl cluster destroy being stuck

- README.md
- docs/website/components/DocumentationDropdown.vue
- docs/website/components/Header.vue
- docs/website/nuxt.config.js
We need a way for users to get to the latest stable docs easily.
> docs: add link to latest docs

- docs/website/components/DocumentationDropdown.vue
Latest release was tagged as "pre-release". It should be "latest".
> docs: fix latest tag

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/mode.go
- pkg/machinery/client/client.go
Return proper message back to the client in case if called method is not
supported by mode any particular node runs in.
Fixes: https://github.com/talos-systems/talos/issues/2629
> feat: handle unsupported commands being called for docker

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- internal/app/networkd/pkg/address/dhcp.go
- internal/app/networkd/pkg/networkd/netconf.go
- internal/app/networkd/pkg/nic/nic.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
This PR adds a "DHCPOptions" field to the config. This field contains a
single subfield currently, "RouteMetric". Setting this well ensure that
any routes provided from the DHCP server are given this metric upon
injection into the routing table.
> feat: support metric values for DHCP

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- internal/app/networkd/pkg/address/dhcp.go
- internal/app/networkd/pkg/networkd/netconf.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
This PR updates the behavior of our machine configs with respect to
DHCP-enabled interfaces. Now, if MTU is specified by the user, that
value will take precedence over any setting provided by the DHCP server.
Additionally, any routes specified will be appended to routes specified
by the DHCP server.
Will close #2533
> feat: support MTU and route changes for DHCP

- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
If the config does not have the kubelet field, we should return a default struct.
> fix: address nil pointer panic

- .golangci.yml
- internal/integration/api/apply-config.go
- internal/integration/api/diskusage.go
- internal/integration/api/dmesg.go
- internal/integration/api/etcd.go
- internal/integration/api/logs.go
- internal/integration/api/reboot.go
- internal/integration/api/recover.go
- internal/integration/api/reset.go
- internal/integration/api/version.go
- internal/integration/base/api.go
- internal/integration/base/base.go
- internal/integration/base/cli.go
- internal/integration/base/cluster.go
- internal/integration/base/discovery_k8s.go
- internal/integration/base/run.go
- internal/integration/cli/crashdump.go
- internal/integration/cli/diskusage.go
- internal/integration/cli/gen.go
- internal/integration/cli/health.go
- internal/integration/cli/restart.go
- internal/integration/cli/validate.go
- internal/integration/cli/version.go
- internal/integration/integration_test.go
- internal/integration/k8s/version.go
- internal/integration/provision/upgrade.go
This enables golangci-lint via build tags for integration tests (this
should have been done long ago!), and fixes the linting errors.
Two tests were updated to reduce flakiness:
* apply config: wait for nodes to issue "boot done" sequence event
before proceeding
* recover: kill pods even if they appear after the initial set gets
killed (potential race condition with previous test).
> test: clean up integration test code, fix flakes

- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/install/manifest_test.go
- docs/website/content/v0.7/en/configuration/v1alpha1.md
- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/mount/iter.go
- internal/pkg/mount/mount.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
This unifies more code paths under the control of `install.Manifest` vs.
being split across the installer and manifest code.
There should be no functional changes now.
> refactor: bring more control to install.Manifest execution

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/app/machined/pkg/system/services/trustd.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
This PR changes the bool for disabling ntp to `disable` instead of the
previous `enable`. We need to do this because customers were seeing
failure in cases where they were defining time servers only, which
results in `enabled: false` when configs get unmarshalled. Users wishing
to disable ntp altogether should now use `disabled: true`.
> fix: update handling of ntp disable

- CHANGELOG.md
This is the official v0.7.0-alpha.7 release.
> release(v0.7.0-alpha.7): prepare release

- Makefile
`git describe` ignores untracked files in `-dirty`
> chore: fix the check-dirty command to abort on untracked files

- go.mod
- go.sum
- internal/app/networkd/pkg/nic/nic.go
This PR makes use of a new merge into the upstream rtnetlink library
that introduces functional args for adding routes.
> chore: move to newer release of rtnetlink with fn args

- cmd/installer/cmd/root.go
- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/install/manifest_test.go
- cmd/talosctl/cmd/talos/rollback.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/integration/base/api.go
- internal/pkg/mount/system.go
- pkg/archiver/archiver.go
- pkg/archiver/untar.go
This fixes A/B upgrades and rollback API.
Installer manifest supports now an option to preserve partition contents
while disk is being re-partitioned and partitions are re-formatted.
Mount `/boot` partition as needed (to find current label before starting
the installation and in the rollback API).
Fix upgrade API for non-master nodes.
Contents of `/boot`, `/system/state` and META partitions are preserved
in memory while the disk is re-partitioned.
Remove `--save` flag from the installer as it's not being used.
Fixes #2521
> fix: implement preserving contents of partition on install

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/pkg/etcd/etcd.go
- pkg/machinery/constants/constants.go
When an etcd node is upgraded, we now perform additional quorum checks.
This is necessary because when etcd nodes are upgraded, they are removed
from membership.  If, for instance, two etcd nodes were to upgrade
simultaneously, quorum may be lost.  This, of course, does not apply to
single-node etcd clusters.
Fixes #1422
> feat: extend etcd health check on upgrade

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/system.go
The problem was that etcd stop was only happening in `LeaveEtcd`, thus
upgrade with preserve was never stopping etcd leaving ephemeral
partition still busy.
Refactored code which was stopping service, shutting down all the
services to provide the interface we need:
* stop a service without considering reverse dependencies (force);
* stop a service (services) waiting for reverse dependencies;
* shutdown all the services waiting for reverse dependencies.
> fix: stop etcd on any path on upgrade

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/cri/pods.go
Talos always stops and removes CRI pods before stopping CRI containerd
when upgrading with wipe (force), but on "preserve" code paths pods were
never stopped (we can't remove them to keep preserve guarantees). This
PR makes sure pods are stopped on upgrade in any case.
> fix: stop CRI pods on upgrade with preserve

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/system.go
- internal/pkg/cri/pods.go
fix: stop etcd on any path on upgrade
The problem was that etcd stop was only happening in `LeaveEtcd`, thus
upgrade with preserve was never stopping etcd leaving ephemeral
partition still busy.
Refactored code which was stopping service, shutting down all the
services to provide the interface we need:
* stop a service without considering reverse dependencies (force);
* stop a service (services) waiting for reverse dependencies;
* shutdown all the services waiting for reverse dependencies.
(cherry picked from commit e7f6344d97f79067fd3172e88f76795944b78b4c)
fix: stop CRI pods on upgrade with preserve
Talos always stops and removes CRI pods before stopping CRI containerd
when upgrading with wipe (force), but on "preserve" code paths …
> fix: single-node upgrade: stopping etcd and CRI pods

- pkg/machinery/config/encoder/markdown.go
- website/content/docs/v0.7/Reference/configuration.md
Looks like gridsome can't handle markdown inside \<code\> tags.
Completely replaced this thing with html syntax.
> docs: fix config reference types links

- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/constants/constants.go
This is the recommended version for K8s 1.19.x:
https://github.com/coredns/deployment/blob/master/kubernetes/CoreDNS-k8s_version.md
> feat: bump CoreDNS to 1.7.0

- Makefile
- pkg/machinery/constants/constants.go
See https://github.com/talos-systems/pkgs/pull/181
> feat: bump Linux to 5.8.16, enable mpt3sas driver

- cmd/talosctl/cmd/talos/time.go
- website/content/docs/v0.7/Reference/cli.md
This was causing the ntp query to always use pool.ntp.org.
> fix: remove default time server in time command

- cmd/installer/cmd/install.go
- cmd/installer/pkg/install/manifest.go
This will make it more obvious when installer got started, and when it
starts to wipe a disk (which might take some time).
> chore: output more logs from the installer

- website/content/docs/v0.7/Introduction/quickstart.md
- website/src/components/LayoutHeader.vue
- website/src/components/Search.vue
- website/src/components/Sidebar.vue
- website/src/components/SidebarDropdown.vue
- website/src/layouts/Default.vue
- website/src/templates/MarkdownPage.vue
The search bar was taking too much space in the header. This moves it
to the sidebar. The search query now filters based on the current version
of docs.
> docs: improve search bar

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
This is :facepalm:, I somehow missed that installer Manifest is used
here and missed the fact I need to update it.
> fix: properly initialize manifest in user disks creation

- cmd/installer/pkg/install/manifest.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.7/Reference/configuration.md
Otherwise we're bound with 4GiB partititions.
Discovered by @Unix4ever.
> fix: bump type for `DiskSize` to be 64-bit

- .drone.jsonnet
- Makefile
- internal/integration/provision/upgrade.go
Use 0.6.3 as upgrade source version, use latest Cilium release.
> test: bump Talos version for upgrade tests, bump Cilium version

- CHANGELOG.md
This is the official v0.7.0-alpha.8 release.
> release(v0.7.0-alpha.8): prepare release

- pkg/machinery/config/encoder/markdown.go
- website/content/docs/v0.7/Reference/configuration.md
- website/src/assets/css/main.css
- website/src/components/OnThisPage.vue
- website/src/templates/MarkdownPage.vue
Adds a dashed line between struct field sections in generate configuration
markdown. Also improves the padding of the headers in the right sidebar.
> docs: fix small CSS issues

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/cluster/show.go
- hack/test/e2e-qemu.sh
- internal/integration/cli/mounts.go
- internal/integration/integration_test.go
- internal/integration/provision/provision.go
- internal/integration/provision/upgrade.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/join.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- pkg/provision/providers/docker/docker.go
- pkg/provision/providers/firecracker/node.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/vm/disk.go
- pkg/provision/provision.go
- pkg/provision/request.go
- pkg/provision/result.go
- website/content/docs/v0.7/Reference/cli.md
User-disks are supported by QEMU and Firecracker providers.
Can be defined by using the following parameters:
```
--user-disk /mount/path:1GB
```
Can get more than 1 user disk.
Same set of user disks will be created for all master and worker nodes.
> feat: allow specifying user-disks in talosctl cluster create

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- website/content/docs/v0.7/Reference/configuration.md
Use octal representation to dump FileMode to yaml.
Use 100MB/1GB/1.5TB representations for partitions size, but only if
that doesn't lead to losing precision. Decoding of them should work as
well.
> fix: read/write human readable representations for bytes and octals

- go.mod
- go.sum
- internal/pkg/mount/mount.go
This skips writing partition table if partition doesn't have to be
resized (already resized or max size from the beginning).
> feat: skip resizing ephemeral partition if not required

- .drone.jsonnet
- Dockerfile
- Makefile
- cmd/talosctl/cmd/mgmt/cluster/cluster.go
- cmd/talosctl/cmd/mgmt/cluster/create.go
- go.mod
- go.sum
- hack/test/e2e-qemu.sh
- pkg/provision/providers/qemu/arch.go
- pkg/provision/providers/qemu/create.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/qemu/preflight.go
- pkg/provision/request.go
- website/content/docs/v0.7/Local Platforms/firecracker.md
- website/content/docs/v0.7/Local Platforms/qemu.md
- website/content/docs/v0.7/Reference/cli.md
This builds a bundle with CNI plugins for talosctl which is
automatically downloaded by `talosctl` if CNI plugins are missing.
CNI directories are moved by default to the `~/.talos/cni` path.
Also add a bunch of pre-flight checks to the QEMU provisioner to make it
easier to bootstrap the Talos QEMU cluster.
> feat: build talosctl-cni-bundle, use it in talosctl for QEMU

- internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/errors/errors.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/webconfig/webconfig.go
If no configuration source is provided (on baremetal only for now), Talos will set of a simple web service to receive its configuration via an HTTP POST request, on port 80 or 443.
It also serves a simple web form for interactive submission from the browser.
Fixes #2593
> feat: add webconfig service

- Dockerfile
- hack/cleanup.sh
Removes socat (no dependency in containerd since 1.4), and static binaries.
> chore: remove unused binaries

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
Adds options to the grub.cfg that prevents booting in blind mode.
> fix: prevent blind mode boot

- .golangci.yml
- Dockerfile
- cmd/installer/cmd/iso.go
- internal/app/bootkube/main.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
- internal/app/machined/pkg/system/runner/restart/restart.go
- internal/app/networkd/pkg/nic/nic.go
- internal/app/timed/pkg/ntp/options.go
- internal/pkg/containers/cri/cri_test.go
- pkg/machinery/config/decoder/decoder.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/constants/constants.go
- pkg/sysctl/sysctl.go
Brings in the latest version of golangci-lint and addresses errors.
> chore: update golangci-lint

- Makefile
- pkg/machinery/constants/constants.go
This PR brings in an upgraded pkgs version that contains https://github.com/talos-systems/pkgs/commit/fe414af3b4779196a18b5bc401003deba081e456
> feat: upgrade kernel to v5.9.3

- internal/app/maintenance/main.go
Errors should be returned, otherwise we will get a kernel panic.
> fix: remove log.Fatal from maintenance service

- CHANGELOG.md
This is the official v0.7.0-beta.0 release.
> release(v0.7.0-beta.0): prepare release

- Dockerfile
> chore: fix markdownlint command

- Dockerfile
- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- cmd/talosctl/cmd/talos/apply-config.go
- internal/app/maintenance/main.go
- internal/integration/provision/upgrade.go
- pkg/grpc/middleware/auth/basic/token.go
- pkg/machinery/client/client.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
- pkg/provision/providers/docker/node.go
- pkg/provision/providers/firecracker/node.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
- website/content/docs/v0.7/Reference/cli.md
This fixes the reverse Go dependency from `pkg/machinery` to `talos`
package.
Add a check to `Dockerfile` to prevent `pkg/machinery/go.mod` getting
out of sync, this should prevent problems in the future.
Fix potential security issue in `token` authorizer to deny requests
without grpc metadata.
In provisioner, add support for launching nodes without the config
(config is not delivered to the provisioned nodes).
Breaking change in `pkg/provision`: now `NodeRequest.Type` should be set
to the node type (as config can be missing now).
In `talosctl cluster create` add a flag to skip providing config to the
nodes so that they enter maintenance mode, while the generated configs
are written down to disk (so they can be tweaked and applied easily).
Signed-off-by: Andrey Smirnov …
> fix: remove 'token creds' from maintenance service

- go.mod
- go.sum
Fixes #2746
This should cover the `x/net/http2` fixes which were backported in Go
1.15.4.
> chore: bump version of `x/net` module

- Dockerfile
- Makefile
- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- cmd/talosctl/cmd/talos/apply-config.go
- go.mod
- go.sum
- internal/app/maintenance/main.go
- internal/integration/provision/upgrade.go
- pkg/grpc/middleware/auth/basic/token.go
- pkg/machinery/client/client.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
- pkg/provision/providers/docker/node.go
- pkg/provision/providers/firecracker/node.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
- website/content/docs/v0.7/Reference/cli.md
This backports PRs #2733 #2738 #2745 #2747
Fixes #2736 
fix: update packages
Brings in the R8169 driver.
(cherry picked from commit 4d9555a3ac11760410f925e15f979c7804a3e4ec)
chore: bump Go to 1.15.4
See:
* https://github.com/talos-systems/pkgs/pull/185
* https://github.com/talos-systems/tools/pull/111
* https://github.com/talos-systems/extras/pull/3
(cherry picked from commit 5fca20e137fa10cff18c2bcc367f728b10b181e2)
fix: remove 'token creds' from maintenance service
This fixes the reverse Go dependency from `pkg/machinery` to `talos`
package.
Add a check to `Dockerfile` to prevent `pkg/machinery/go.mod` getting
out of sync, this should prevent problems in the future.
Fix potential …
> fix: r8169 driver, Go 1.15.4, maintenance service API

- pkg/download/download.go
Depending on the nature of the error, each attempt might take much
longer than 1 second, so bump the overall timeout, but print the error
encountered so that longer timeout doesn't mean less feedback for the
user.
> fix: bump timeout for config downloading on bare metal

- pkg/machinery/constants/constants.go
- website/content/docs/v0.7/Guides/upgrading-kubernetes.md
- website/content/docs/v0.7/Reference/configuration.md
> fix: use ghcr.io/talos-systems/kubelet

- cmd/talosctl/cmd/talos/apply-config.go
- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/maintenance/main.go
- website/content/docs/v0.7/Reference/cli.md
Server in maintenance mode now prints certficate fingerprint and
provides sample talosctl command to upload config to the node.
`talosctl` can optionally enforce server certificate fingerprint.
See also https://github.com/talos-systems/crypto/pull/4
Fixes #2753
> feat: add example command in maintenance, enforce cert fingerprint

- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
This PR fixes a bug where the nics in packet was only receiving the
public mgmt IP, instead of all addresses supplied in the network
metadata.
It also moves to using the bond instead of eth0 directly. This is more
in line with other packet OS images. We will need to explore why eth1
seems to always show as not having a carrier, as well as tolerate that
condition when setting up bonding in a follow-up PR.
> fix: ensure packet nics get all IPs

- hack/docgen/main.go
- pkg/machinery/config/encoder/encoder.go
- pkg/machinery/config/encoder/encoder_test.go
- pkg/machinery/config/encoder/markdown.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.7/Reference/configuration.md
`docgen` now correctly extracts documentation for the structure itself,
and supports mix of Go-style and yaml-style docblocks, so that we can
keep linter happy while embedding examples.
Fixes for encoder to keep things marshalled same way even with the
presence of the struct docs.
Add real examples replacing fake ones.
Add top-level hacked examples for `Config`, `MachineConfig` and
`ClusterConfig` to show the overall structure without pulling in all the
deep structure of those types.
Fixes #2768 
> docs: improve configuration reference documentation

- .drone.jsonnet
- Makefile
- cmd/installer/cmd/image.go
- cmd/installer/cmd/iso.go
- cmd/installer/pkg/ova/ova.go
- hack/test/capi/cluster-aws.yaml
- hack/test/capi/cluster-gcp.yaml
- hack/test/e2e-aws.sh
- hack/test/e2e-azure.sh
- hack/test/e2e-gcp.sh
- website/content/docs/v0.6/Cloud Platforms/digitalocean.md
- website/content/docs/v0.7/Cloud Platforms/aws.md
- website/content/docs/v0.7/Cloud Platforms/azure.md
- website/content/docs/v0.7/Cloud Platforms/digitalocean.md
- website/content/docs/v0.7/Cloud Platforms/gcp.md
This changes installer image/iso output to be tar via stdout
(optionally), so that we can copy back artifacts back from remote docker
daemon.
Fixes #2776
> chore: build arm64 images in CI

- .drone.jsonnet
- Makefile
- cmd/installer/cmd/image.go
- cmd/installer/cmd/iso.go
- cmd/installer/pkg/ova/ova.go
- hack/test/capi/cluster-aws.yaml
- hack/test/capi/cluster-gcp.yaml
- hack/test/e2e-aws.sh
- hack/test/e2e-azure.sh
- hack/test/e2e-gcp.sh
- website/content/docs/v0.6/Cloud Platforms/digitalocean.md
- website/content/docs/v0.7/Cloud Platforms/aws.md
- website/content/docs/v0.7/Cloud Platforms/azure.md
- website/content/docs/v0.7/Cloud Platforms/digitalocean.md
- website/content/docs/v0.7/Cloud Platforms/gcp.md
Backports PRs #2778, #2782
Fixes #2790 #2791
feat: update Go to 1.15.5
Release contains important security fixes:
https://groups.google.com/g/golang-announce/c/NpBGTTmKzpM/m/fLguyiM2CAAJ
Fixes #2775
(cherry picked from commit 32d231debd965f8ec0bf3b2a64815762ee311c4d)
chore: build arm64 images in CI
This changes installer image/iso output to be tar via stdout
(optionally), so that we can copy back artifacts back from remote docker
daemon.
Fixes #2776
(cherry picked from commit 61facf700a1cb949f32a1f8c912186ad17f25767)
> feat: Go 1.15.5, arm64 images in the CI

- hack/test/capi/cluster-aws.yaml
- hack/test/capi/cluster-gcp.yaml
- hack/test/e2e-capi.sh
This should fix the problem with the kubelet image.
> chore: bump K8s to 1.19.4 in e2e scripts with CABPT version

- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
- pkg/machinery/constants/constants.go
This provides compatibility with VMWare CAPI provider which stores the
bootstrap secret in `guestinfo.userdata`.
Fixes #2795
> feat: read config from extra guestinfo key (vmware)

- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
- pkg/download/download.go
- website/content/docs/v0.7/Cloud Platforms/digitalocean.md
On first boot of Talos, if userdata is missing, Talos is going to drop
into maintenance mode which allows to upload config to the server via
`talosctl apply-config` command.
See also: https://github.com/talos-systems/go-retry/pull/4
Fixes #2780
> feat: drop to maintenance mode in cloud platforms if userdata is missing

- pkg/machinery/client/config/config.go
- pkg/machinery/client/config/config_test.go
Implement merging of Talos client config without overwrites - numeric
value is appended to context name to avoid ever overwriting config.
Fixes #2799
> feat: correctly merge talosconfig (don't ever overwrite)

- website/gridsome.config.js
- website/src/pages/Index.vue
- website/static/_redirects
The v0.7 docs are now the default and marked as stable.
> docs: graduate v0.7 docs

- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
This PR fixes a bug where kubelets weren't getting registered with the
actual hostname of the server in packet.
> fix: return hostname from packet platform

- internal/app/networkd/pkg/address/address.go
- internal/app/networkd/pkg/address/dhcp.go
- internal/app/networkd/pkg/address/static.go
- internal/app/networkd/pkg/nic/nic.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.7/Reference/configuration.md
While IPv6 were mostly supported already, there was a single segment in
the interface setup which forced everything into an IPv4 route.
This limitation has been removed.
In so doing, route metrics have been cleaned up a small amount.
This change allows the specification of the route metric from the
config.
Fixes #2772
> feat: support ipv6 routes

- Makefile
- internal/integration/provision/upgrade.go
Bump to 0.7.0 as we have a new release.
Clean up the tests we do: 0.6.3 is a previous release, 0.7.0 is a stable
release, current version (0.8.x) is the "next" release.
We test the following:
* 0.6.3 -> 0.7.0
* 0.7.0 -> 0.8-current
* 0.7.0 -> 0.8-current (single node)
This tests upgrades always between two releases.
> test: update integration test versions, clean up names

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
- cmd/talosctl/cmd/talos/apply-config.go
- go.mod
- go.sum
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/maintenance/server/server.go
- internal/integration/provision/upgrade.go
- internal/pkg/configuration/configuration.go
- internal/pkg/tui/components/formlabel.go
- internal/pkg/tui/components/group.go
- internal/pkg/tui/components/menubutton.go
- internal/pkg/tui/components/spinner.go
- internal/pkg/tui/installer/installer.go
- internal/pkg/tui/installer/state.go
- pkg/cluster/kubernetes.go
- pkg/machinery/client/client.go
- pkg/machinery/client/config/config.go
- pkg/machinery/config/encoder/documentation.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/bundle/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.7/Reference/cli.md
Fixes: https://github.com/talos-systems/talos/issues/2742
This is initial commit of the installer.
What's done:
- verifying node availability before starting any operations.
- gathering information about disks on the machine.
- allows setting: install disk, hostname, machine type, installer image,
kubernetes version, dns domain, cluster name.
- can dump/merge talosconfig to a file after applying configuration.
> feat: add TUI based talos interactive installer

- website/content/docs/v0.6/Cloud Platforms/gcp.md
- website/content/docs/v0.7/Cloud Platforms/gcp.md
This PR fixes some missing info in the GCP docs to make sure that we
allow for talosctl in the firewall, as well as set the node in talosctl
so the kubeconfig command works.
Will close #2610
> docs: ensure gcp docs have firewall and node info

- website/content/docs/v0.6/Bare Metal Platforms/digital-rebar.md
- website/content/docs/v0.6/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.6/Bare Metal Platforms/matchbox.md
- website/content/docs/v0.6/Cloud Platforms/aws.md
- website/content/docs/v0.6/Cloud Platforms/azure.md
- website/content/docs/v0.6/Cloud Platforms/digitalocean.md
- website/content/docs/v0.6/Virtualized Platforms/vmware.md
- website/content/docs/v0.7/Bare Metal Platforms/digital-rebar.md
- website/content/docs/v0.7/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.7/Bare Metal Platforms/matchbox.md
- website/content/docs/v0.7/Cloud Platforms/aws.md
- website/content/docs/v0.7/Cloud Platforms/azure.md
- website/content/docs/v0.7/Cloud Platforms/digitalocean.md
- website/content/docs/v0.7/Virtualized Platforms/vmware.md
This PR makes sure we go through the step of running `talosctl
config nodes` for each of our environment guides.
Will close #2609
> docs: ensure we configure nodes in guides

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/timed.go
Under normal boot, Talos run `timed` before starting almost anything
else, but in the installer phase timed doesn't run. If the RTC is
missing or totally off, it might lead to image pull failure for the
installer.
This is special task to run timed without blocking on time sync, as it
might not be available in some environments.
> feat: sync time before installer runs

- go.mod
- go.sum
See https://github.com/talos-systems/go-blockdevice/pull/17
> fix: bump blockdevice library for `mmcblk` part name fix

- internal/integration/api/generate-config.go
- internal/pkg/configuration/configuration.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/generate_test.go
Fixes: https://github.com/talos-systems/talos/issues/2819
Only if requested config type is not `TypeInit`.
This functionality will help implementing TUI installer cluster
extension workflow.
> feat: make GenerateConfiguration API reuse current node auth

- cmd/talosctl/cmd/talos/apply-config.go
- internal/pkg/tui/installer/connection.go
- internal/pkg/tui/installer/installer.go
- internal/pkg/tui/installer/state.go
Fixes: https://github.com/talos-systems/talos/issues/2816
Now with:
```
talosctl apply-config -i --interactive -n 10.5.0.2
talosctl apply-config -i --interactive -n 10.5.0.3 -e 10.5.0.2
```
It is possible to add more nodes to already existing cluster.
Installer will call `GenerateConfiguration` on the bootstrap node
instead of using target node.
As we have to create separate clients to connect to two different nodes (one can be insecure and another one should be secure), I've decided to create that 2 clients wrapper `Connection` entity.
I didn't want to drag node context and node client through all the places, this looks cleaner, but if you don't like my approach I'm open for suggestions.
> feat: support cluster expansion in the interactive installer

- internal/pkg/tui/components/form.go
- internal/pkg/tui/components/formlabel.go
- internal/pkg/tui/components/table.go
- internal/pkg/tui/installer/installer.go
- internal/pkg/tui/installer/state.go
Implemented a new component based on `tview.Table` that shows all
available block devices as a table.
Had to stop using standard form control, because it doesn't really
handle multiline elements.
> feat: change UI component for disks selector

- .drone.jsonnet
- Makefile
- cmd/installer/cmd/image.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
This PR adds the ability for us to deploy Talos in openstack. Tested in
local devstack with a supplied userdata file. It also adds support to
the Makefile for building the openstack image so it'll be published with
next release.
> feat: support openstack platform

- Makefile
- pkg/machinery/constants/constants.go
This brings in Containerd v1.4.2 and Linux v5.9.11
> feat: update Containerd and Linux

- Makefile
The variable $(TAG) was used both during linking phase to set the
version of Talos built into binaries and as an image reference for
pushing. This leads to to `:latest` image being built with version
`latest`.
Separate image push reference and Talos version by introducing
`$(IMAGE_TAG)` which defaults to `$(TAG)`, but can be overridden.
> chore: use IMAGE_TAG instead of TAG for :latest pushes

- cmd/installer/pkg/ova/ova.go
Use constant instead of hardcoded value.
Fixes #2845
> fix: update generated .ova manifest for raw disk size

- cmd/installer/cmd/image.go
We shouldn't include "none" in the default metal image.
> chore: fix metal image name

- cmd/talosctl/cmd/mgmt/config.go
- go.mod
- go.sum
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.8/Reference/cli.md
- website/content/docs/v0.8/Reference/configuration.md
Default image versions are kept as commented out examples.
This allows better experience for generating config on amd64 for arm64
servers. (e.g. for RPi).
Without embedded values in the config, Talos is going to use the
defaults which work better.
> feat: stop including K8s version by default in `talosctl gen config`

- .conform.yaml
- Makefile
- pkg/machinery/constants/constants.go
This brings in the the latest Containerd to address a CVE.
> fix(security): update Containerd to v1.4.3

- Dockerfile
- Makefile
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
This adds sun50i-h5-libretech-all-h3-cc.dtb to the EFI partition.
> fix: use the dtb from kernel pkg for libretech_all_h3_cc_h5

- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
This documents how to generate the libretech_all_h3_cc_h5 board image with the correct
console args.
> docs: add console kernel arg to libretech_all_h3_cc_h5 image generation

- website/content/docs/v0.8/Single Board Computers/rpi_4.md
This documents how to generate the rpi_4 board image with the correct console args.
> docs: add console kernel arg to rpi_4 image generation

- internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/app/networkd/pkg/address/dhcp.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
This adds the Banana Pi M64 to the list of supported boards.
> feat: add support for the Banana Pi M64

- cmd/installer/pkg/install/install.go
- internal/app/machined/pkg/runtime/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
This allows boards to provide kernel args at install time. We need this so that
we can set the console.
> feat: allow boards to set kernel args

- internal/app/networkd/pkg/address/dhcp.go
- internal/app/networkd/pkg/nic/netlink.go
- internal/app/networkd/pkg/nic/nic.go
- pkg/provision/providers/vm/dhcpd.go
There were two problems:
* `configureInterfaces` was always failing if interface is already set
up, as the routes already exist
* `renew` was halving the renew interval each time `configureInterface`
fails, which starts at (LeaseTime/2) and goes effectively to zero
This was leading to high networkd CPU usage, storm of DHCP requests on
the network.
> fix: prevent endless loop with DHCP requests in networkd

- pkg/kubernetes/kubernetes.go
This seems to be more preferred way and fixes compatibility with
deployments which don't do `operator: Exists` in tolerations.
> fix: remove value (change to empty) for `NoSchedule` taint

- website/content/docs/v0.7/Local Platforms/virtualbox.md
- website/content/docs/v0.7/Virtualized Platforms/proxmox.md
- website/content/docs/v0.8/Local Platforms/virtualbox.md
- website/content/docs/v0.8/Virtualized Platforms/proxmox.md
This PR adds the default port to these docs so it's clear that port is
required.
> docs: ensure port for vbox and proxmox docs

- cmd/talosctl/cmd/mgmt/config.go
- internal/integration/cli/gen.go
Ex.:
```
$ talosctl gen config foo 192.168.0.1
no scheme and port specified for the cluster endpoint URL
try: "https://192.168.0.1:6443"
```
> feat: suggest fixed control plane endpoints in talosctl gen config

- pkg/machinery/client/client.go
Now config context is resolved only when it is about to be used, so that
client can operate in config-less mode if config is not required (e.g.
when doing `apply-config --insecure`).
> fix: defer resolving config context in client code

- pkg/kubernetes/kubernetes.go
As code was looking for existing taint with `value == true`, it failed
to find existing taint and tried to add another one which never
succeeds.
> fix: node taint doesn't contain value anymore

- .drone.jsonnet
This PR makes sure that we run integration more often. I did this in
UTC, with Eastern time zones in mind. In Eastern, it'll do 6AM, noon,
and 6PM. That should give us pretty good coverage across all of our
timezones so we can all have a chance to tackle new issues.
The cron that I added to drone (in UTC) is:
```
drone cron add "talos-systems/talos" "thrice-daily" "0 0 11,17,22 * * *"
```
> chore: run integration test thrice daily

- internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rock64/rock64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
This adds `tty0` for all the boards in case HDMI output actually works.
For RPi4, disable BT to enable PL011 instead of mini-UART for serial
console, as PL011 is much more stable (fixes garbage on serial output).
> fix: stabilize serial console on RPi4, add video console

- pkg/machinery/config/types/v1alpha1/generate/options.go
This should fix interactive installer on arm64.
> fix: make default generate image arch dynamic based on arch

- .drone.jsonnet
- Makefile
This publishes the Pine64 Rock64 image.
> chore: publish Rock64 image

- CHANGELOG.md
- Makefile
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.0-alpha.2 release.
> release(v0.8.0-alpha.2): prepare release

- .conform.yaml
Updates the allowed scope for releases.
> chore: fix conform for releases

- website/content/docs/v0.8/Guides/configuring-network-connectivity.md
Add documentation on network ports required to operate Talos.
Closes #2870 
I tried to run `make docs` on my mac before pushing this commit but it failed with the following:
```sh
> [tools  5/10] RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b /toolchain/bin v1.32.2:
#12 0.506 golangci/golangci-lint info checking GitHub for tag 'v1.32.2'
#12 0.533 golangci/golangci-lint crit unable to find 'v1.32.2' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
```
The actual release seems to exist, so I'm not sure what the problem is.
> docs: Add docs for network connectivity

- hack/golang/test.sh
As we run unit-tests concurrently, it makes sense to limit each run
concurrency.
> chore: limit unit-test run concurrency

- Makefile
- internal/integration/provision/upgrade.go
We should always use latest releases.
> test: bump Talos release version for upgrade test to 0.7.1

- website/content/docs/v0.8/Guides/storage.md
Adds a basic guide on storage.
> docs: add storage doc

- website/content/docs/v0.8/Learn More/architecture.md
This adds documentation on how the root file system is laid out.
> docs: add architectural doc on the root file system layout

- cmd/talosctl/cmd/talos/config.go
- internal/integration/cli/config.go
- website/content/docs/v0.8/Reference/cli.md
Bonus to `talosctl config merge`.
Got that idea after using talosctl for a weekend.
I feel that can be a good addition to have a command that can list existing
contexts in a table view, which is similar to what `kubectl config get-contexts`
does. To avoid going through the file which has all the certs and such.
Called it just `contexts` to align with whatever we have now (to switch
context you need to use `talosctl config context`).
> feat: add talosctl config contexts

- cmd/talosctl/cmd/talos/config.go
- internal/integration/cli/config.go
- website/content/docs/v0.8/Reference/cli.md
Fixes: https://github.com/talos-systems/talos/issues/2875
Allows merging two Talos configs into one. Merges the config in whatever
is set by `TALOSCONFIG` or into `~/.talos/config`.
> feat: add talosctl merge config command

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
- website/content/docs/v0.8/Reference/cli.md
If disk is empty and ISO path is given, QEMU provisioner mounts ISO on
the first boot.
To drop into maintenance mode:
```
talosctl cluster create --provisioner=qemu --iso-path=./_out/talos-amd64.iso --skip-injecting-config --wait=false
```
Then inject the config, bootstrap the node, wait for it to come up (via
`talosctl cluster health`).
See #2881
> test: add support for mounting ISO in talosctl cluster create

- .drone.jsonnet
- hack/test/e2e-iso.sh
- internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
Adds a simple test for the ISO. Boots the ISO, and then uses the `apply-config` command
in `talosctl` to create a cluster.
> test: add ISO test

- Makefile
- internal/integration/api/events.go
- internal/integration/api/reboot.go
- internal/integration/api/reset.go
- internal/integration/base/errors.go
- internal/integration/provision/upgrade.go
- pkg/cluster/crashdump.go
For single node clusters, control plane is unstable after reboot, run
health check several times to let it settle down to avoid failures in
subsequent checks.
> test: stabilize upgrade test by running health check several times

- internal/app/machined/pkg/system/services/etcd.go
- internal/pkg/containers/image/image.go
Instead of running `PreFunc` in goroutine which might leak behind the
lifetime of the service `PreFunc`, add more clauses to correctly abort
sequence on context canceled.
> refactor: remove setup goroutine in etcd service

- .drone.jsonnet
Self-hosted control plane upgrade with Cilium looks to be really flaky,
and it often fails the test run. We still have e2e-test with Cilium for
the test coverage.
> test: remove provision tests with Cilium CNI

- website/package-lock.json
https://github.com/advisories/GHSA-qqgx-2p2h-9c37
> chore: bump npm `ini` package for security vulnerability

- pkg/cluster/check/default.go
- pkg/cluster/check/events.go
This makes sure node boot sequence is done before we consider cluster to
be healthy.
> test: add an extra 'node boot done' health check

- Makefile
- pkg/machinery/constants/constants.go
This pulls in following PRs:
* https://github.com/talos-systems/pkgs/pull/219
* https://github.com/talos-systems/pkgs/pull/220
> feat: bump Linux kernel to 5.10.1, add CONFIG_USB_ACM

- .drone.jsonnet
- Makefile
- hack/cloud-image-uploader.sh
At the moment only AMIs for AWS, and upload results should be pushed
back to the docs as separate PR.
> chore: add drone pipeline to upload cloud images

- .drone.jsonnet
This should cut overall build time.
> chore: build ISOs earlier to launch e2e-iso as soon as possible

- cmd/talosctl/cmd/talos/time.go
- website/content/docs/v0.8/Reference/cli.md
Previously it was defaulting to `c`.
Signed-off-by: Artem Chernyshev <artem.0xd2@gmail.com>
> fix: properly define shorthand in `talosctl time` command

- go.mod
- go.sum
See https://github.com/talos-systems/go-blockdevice/pull/23
> fix: bump blockdevice library for 2nd partitione entries copy fix

- Makefile
This pulls in:
* https://github.com/talos-systems/pkgs/pull/222
* https://github.com/talos-systems/pkgs/pull/226
> feat: bump pkgs for kernel with HZ=250 on amd64

- go.mod
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/timed.go
- internal/app/timed/pkg/ntp/ntp.go
- internal/app/timed/pkg/ntp/ntp_test.go
- internal/app/timed/pkg/reg/reg.go
1. When time is set by timed, also sync RTC with system time, otherwise
time might be off after a reboot.
2. Before fetching Packet (Equinix Metal) metadata over `https://`, do
one-time time sync in the background, as if the clock skew is big
enough, TLS certificate will be considered invalid and boot fails.
> fix: sync RTC in timed, sync time before fetching packet metadata

- internal/app/bootkube/main.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/kubernetes/kubernetes.go
- pkg/machinery/constants/constants.go
When bootkube service fails, it can clean up manifests after itself, but
it only happens if we give it a chance to shut down cleanly. If boot
sequence times out, `machined` does emergency reboot and it doesn't let
`bootkube` do the cleanup.
So this fix has two paths:
* synchronize boot/bootstrap sequence timeouts with bootkube asset
timeout;
* cleanup bootkube-generated manfiests and bootkube service startup.
Also logs errors on initial phases like `labelNodeAsMaster` to provide
some feedback on why boot is stuck.
> fix: synchronize bootkube timeouts and various boot timeouts

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
It was run both as part of `Boot` and `Bootstrap` sequences, remove it
from the `Bootstrap` sequence.
> fix: don't run LabelNodeAsMaster in two sequences

- internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
This updates the `console` arg for the `bananapi_m64` board to the correct value.
> fix: use the correct console on Banana Pi M64

- .drone.jsonnet
- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/test/e2e-iso.sh
- hack/test/e2e-qemu.sh
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- pkg/cluster/apply-config.go
- pkg/provision/access/adapter.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
- website/content/docs/v0.8/Reference/cli.md
Fixes: https://github.com/talos-systems/talos/issues/2973
Can now supply disk image using `--disk-image-path` flag.
May need to enable `--with-apply-config` if it's necessary to bootstrap
nodes properly.
> feat: support disk image in talosctl cluster create

- internal/pkg/cri/pods.go
Talos stops CRI pods and containers before upgrade to make sure
ephemeral partition is not mounted anymore. At the same time with
different CNIs it's frequent that removing stop sandbox might fail
because of CNI teardown issue (dependency on API server being up, for
example). As upgrade only depends on volume mounts and doesn't require
CNI to be stopped, we can ignore such errors.
Plus installer anyway does mount check across all mount namespaces, so
it will abort if ephemeral partition is still mounted.
Fixes #2974
> fix: ignore errors on stopping/removing pod sandboxes

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/sequencer.go
- internal/app/machined/pkg/runtime/sequencer_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Upgrade itself is going to happen after the reboot, but we need to leave
etcd if the disks are to be wiped (!preserve) upgrade.
We're not doing integration test right now, as we need source version
for the upgrade to contain a fix. We can add a test once we release new
version with this fix (dropped a note to look into that later).
> fix: leave etcd for staged upgrades

- hack/test/e2e-qemu.sh
Forgot to add it in the original PR.
> fix: pass disk image flags to e2e-qemu cluster create command

- internal/app/machined/pkg/system/services/bootkube.go
- internal/app/machined/pkg/system/services/cri.go
CRI now waits for etcd to be up on control plane nodes, this makes sure
that if CRI is going to start kube-apiserver, API server will be able to
connect to local etcd.
Bootkube waits for kubelet to be healthy, as bootkube relies on kubelet
to start its operations.
> fix: add more dependencies for bootstrap services

- cmd/installer/pkg/install/install.go
- go.mod
- go.sum
SBC should always overwrite default kernel params.
Otherwise we will always get duplicate values for some of them.
> fix: use SetAll instead of AppendAll when building kernel args

- cmd/installer/pkg/install/install.go
- go.mod
- go.sum
- pkg/machinery/kernel/kernel.go
- pkg/provision/providers/firecracker/node.go
- pkg/provision/providers/qemu/node.go
That change should make Talos updates more straightforward in any
projects that depend on Talos.
> refactor: define default kernel flags in machinery instead of procfs

- Makefile
This pulls in:
https://github.com/talos-systems/pkgs/pull/227
> feat: bump pkgs for kernel with CONFIG_IPV6_MULTIPLE_TABLES

- go.mod
- go.sum
- hack/test/e2e-docker.sh
- internal/integration/api/recover.go
Default manifests created by bootkube so far were only enabling
pod-checkpointer for kube-apiserver. This seems to have issues with
single-node control plane scenario, when without scheduler and
controller-manager node might fall into `NodeAffinity` state.
See https://github.com/talos-systems/bootkube-plugin/pull/23
> fix: checkpoint controller-manager and scheduler

- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
- internal/app/networkd/pkg/networkd/networkd.go
This probably fixes bonding in general if 2nd link in the bond is down.
For packet, set additional options for the bonded interface. In
networkd, add interfaces filtered out by link status as ignored to make
them available as bond subinterfaces.
Fixes #3007 
> fix: bring up bonded interfaces correctly on packet

- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.6/Reference/configuration.md
- website/content/docs/v0.7/Reference/configuration.md
- website/content/docs/v0.8/Reference/configuration.md
Documents the effect of omitting the size of a DiskPartition.
Closes talos-systems/talos#3014
This was previously undocumented.
> docs: document omitting DiskPartition size

- cmd/talosctl/cmd/mgmt/validate.go
- website/content/docs/v0.8/Reference/cli.md
Adds valid modes in the help menu for `validate`.
> docs: add modes to validate command

- internal/integration/api/etcd.go
We can't test much of the flow on single-node clusters.
Fixes #3013
> test: skip etcd tests on non-HA clusters

- cmd/installer/pkg/install/install.go
- go.mod
- go.sum
Fixes #3011
See also https://github.com/talos-systems/go-procfs/pull/8
We don't want to allow all the kernel args to be overridden, as this
might compromise KSPP, but we would rather allow some args to be
overridden explicitly.
> fix: allow 'console' argument in kernel args to be always overridden

- internal/app/networkd/pkg/networkd/networkd.go
- internal/app/networkd/pkg/networkd/networkd_test.go
Looks like the code before change in #1578 returned the first hostname
found while interating over interfaces and addressing methods, but #1578
supposedly inadvertently flipped that to iterate over all interfaces (so
last interface wins).
Problem is that both `DHCP` and `Static` addressing methods provide
hostnames, while DHCP hostname comes from DHCP server, while `Static`
defines hostname as `talos-10-5-0-2` (by IP).
If we were to fix it for real, we should build a list of hostname with
priorities coming from different sources and pick a hostname with the
highest priority, so this fix is more of a bandaid rather than a real
fix.
> fix: pick first interface valid hostname (vs. last one)

- cmd/installer/pkg/install/install.go
- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
- internal/app/networkd/pkg/networkd/networkd.go
- internal/app/networkd/pkg/networkd/networkd_test.go
- pkg/machinery/kernel/kernel.go
- pkg/provision/providers/firecracker/node.go
- pkg/provision/providers/qemu/node.go
fix: bring up bonded interfaces correctly on packet
This probably fixes bonding in general if 2nd link in the bond is down.
For packet, set additional options for the bonded interface. In
networkd, add interfaces filtered out by link status as ignored to make
them available as bond subinterfaces.
(cherry picked from commit 5325a66e3e3bc4ae648e38ff60bfbf9a261caeea)
fix: allow 'console' argument in kernel args to be always overridden
Fixes #3011
See also https://github.com/talos-systems/go-procfs/pull/8
We don't want to allow all the kernel args to be overridden, as this
might compromise KSPP, but we would rather allow some args to be
overridden explicitly.
(cherry picked from …
> fix: networkd updates for Packet, hostname detection, console kernel arg

- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
Ballooning is not automatic, but it can be verified via QEMU monitor by
inflating/deflating the balloon inside the VM.
Monitor can be used like that:
```
$ sudo socat - unix-connect:/home/smira/.talos/clusters/talos-default/talos-default-master-1.monitor
QEMU 5.0.0 monitor - type 'help' for more information
(qemu) info status
info status
VM status: running
```
> chore: enable virtio-balloon and monitor in QEMU provisioner

- Makefile
- pkg/machinery/constants/constants.go
Musl update fixes CVE-2020-28928.
> feat: update Linux to 5.10.7, musl-libc to 1.2.2

- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/verify.go
- cmd/talosctl/cmd/mgmt/cluster/create.go
- go.mod
- go.sum
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/disk/disk.go
- internal/app/machined/pkg/runtime/disk/options.go
- internal/app/machined/pkg/runtime/state.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/meta.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
- internal/pkg/mount/system.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- pkg/provision/providers/docker/node.go
- pkg/provision/providers/firecracker/node.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
This refactoring is required to simplify the work to be done to support
disk encryption.
Tried to minimize amount of queries done by `blockdevice` `probe`
methods.
Instead, where we have `runtime.Runtime` we get all required blockdevices
there from blockdevice cache stored in `State().Machine().Disk()`.
This opens a way to store encryption settings in the `Partition`
objects.
> refactor: update go-blockdevice and restructure disk interaction code

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- cmd/talosctl/cmd/talos/upgrade-k8s.go
- internal/integration/provision/upgrade.go
- pkg/cluster/kubernetes/upgrade.go
- pkg/images/list.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- website/content/docs/v0.9/Reference/cli.md
- website/content/docs/v0.9/Reference/configuration.md
Flannel got updated to 0.13 version which has multi-arch image.
Kubernetes images are multi-arch.
Fixes #3049
> feat: use multi-arch images for k8s and Flannel CNI

- cmd/installer/pkg/install/manifest.go
- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/mount/mount.go
This fixes spurious race conditions when user disks are partitioned
and formatted in `mountUserDisks` task. While this task runs, `udevd` is
running to allow various `/dev/` symlinks to be used for user disks.
At the same time `udevd` might trigger syscall `BLKRRPART` at any time
concurrently with Talos which leads to a race on kernel side when Talos
tries to update kernel partition table while kernel does it on its own
as a result of `udevd` call.
As part of the fix, `RereadPartitionTable()` calls were removed (they
trigger `BLKRRPART` and they're not needed as Talos updates partition
table on its own).
Some cleanups to make sure blockdevice is open/closed just in matching
pairs (no lingering open blockdevice instances). This is import for
`WithExclusiveLock()` calls, as it would lead to …
> fix: open blockdevices with exclusive flock for partitioning

- internal/app/machined/pkg/system/services/apid.go
On worker join, apid waits for kubelet client certficiate to be pulled
by the kubelet. But if control plane and worker nodes are bootstrapped
around same time, apid might give up waiting:
On master:
```
2021-01-29 02:37:33.174609 I | [talos] phase startEverything (8/9): done, 46.064546765s
2021-01-29 02:37:33.174622 I | [talos] phase labelMaster (9/9): 1 tasks(s)
2021-01-29 02:37:33.174656 I | [talos] task labelNodeAsMaster (1/1): starting
2021-01-29 02:37:35.739865 I | [talos] retrying error: Get "https://10.5.0.2:6443/api/v1/nodes/e2e-docker-master-1?timeout=30s": dial tcp 10.5.0.2:6443: connect: connection refused
2021-01-29 02:37:50.250264 I | [talos] retrying error: nodes "e2e-docker-master-1" not found
2021-01-29 02:38:35.296363 I | [talos] task labelNodeAsMaster (1/1): done, …
```
> fix: bump timeout for worker apid waiting for kubelet client config

- internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
- pkg/machinery/constants/constants.go
Using prefix `talos-` so that controller can clean up static pod
manifests which should no longer be there. This allows potential smooth
upgrades if we decide not to run some of the static pods, or future
transition from control plane to worker node.
Fixes #3061
> fix: prefix rendered Talos-owned static pod manifests

- go.mod
- pkg/follow/follow.go
chore: fix import path for fsnotify
That matches the new Go module import path.
See also https://github.com/go-fsnotify/fsnotify.
Without that change, some Go tooling does not work,
including Dependabot.
> chore: fix import path for fsnotify

- internal/app/apid/main.go
- internal/app/init/main.go
- internal/app/machined/main.go
- internal/app/networkd/main.go
- internal/app/routerd/main.go
- internal/app/timed/main.go
- internal/app/trustd/main.go
As of now, we're not using Go profiling, so it's safe to disable it to
save some memory and CPU costs. Once we start using it, we can re-enable
it conditionally.
Each process allocates around 1.4MiB on amd64 for memory profiling
buckets.
> fix: lower memory usage a bit by disabling memory profiling

- Dockerfile
Fixes: https://github.com/talos-systems/talos/issues/3080
`cryptsetup` is necessary to enable disk encryption.
> feat: copy cryptsetup executable from pkgs

- internal/integration/api/apply-config.go
- internal/integration/api/reset.go
- internal/integration/base/api.go
After node reboot (and gRPC API unavailability), gRPC stack might cache
connection refused errors for up to backoff timeout. Explicitly clear
such errors in reset tests before trying to read data from the node to
verify reset success.
> test: clear connection refused errors after reset

- internal/app/machined/pkg/runtime/runtime.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/kubelet.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.9/Reference/configuration.md
This PR fixes a problem we had with AWS clusters. We now allow the
kubelet to register using the full fqdn instead of just hostname. This is done by passing the `registerWithFQDN` boolean in the kubelet section of our config.
It also introduces the idea of a "Node Name" in the runtime. This is specific to times where we are talking directly to kubernetes, so that we're not just running `os.Hostname()` everywhere.
> feat: allow fqdn to be used when registering k8s node

- internal/pkg/mount/pseudo.go
This adds a hugetlbfs. Some applications may depend on it.
> feat: mount hugetlbfs

- internal/app/apid/pkg/provider/tls.go
- pkg/grpc/gen/remote.go
- pkg/grpc/middleware/auth/basic/basic.go
- pkg/machinery/client/resolver.go
- pkg/machinery/client/resolver/resolver.go
- pkg/machinery/client/resolver/roundrobin.go
Instead of doing our homegrown "try all the endpoints" method,
use gRPC load-balancing across configured endpoints.
Generalize load-balancer via gRPC resolver we had in Talos API client,
use it in remote certificate generator code. Generalized resolver is
still under `machinery/`, as `pkg/grpc` is not in `machinery/`, and we
can't depend on Talos code from `machinery/`.
Related to: #3068
Full fix for #3068 requires dynamic updates to control plane endpoints
while apid is running, this is coming in the next PR.
> fix: use grpc load-balancing when connecting to trustd

- internal/pkg/mount/pseudo.go
Specifies the mount source as `hugetlbfs`.
> fix: use hugetlbfs instead of none

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
- internal/app/machined/pkg/controllers/secrets/kubernetes.go
- internal/integration/provision/upgrade.go
- internal/pkg/configuration/configuration.go
- internal/pkg/etcd/certs.go
- internal/pkg/kubeconfig/admin.go
- internal/pkg/kubeconfig/admin_test.go
- pkg/kubernetes/kubernetes.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/bundle/options.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/generate_test.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
ECDSA keys are smaller which decreases Talos config size, they are more
efficient in terms of key generation, signing, etc., so it makes boot
performance better (and config generation as well).
> feat: move to ECDSA keys for all Kubernetes/etcd certs and keys 

- internal/app/apid/main.go
- internal/app/apid/pkg/provider/endpoints.go
- internal/app/apid/pkg/provider/tls.go
- internal/app/machined/pkg/system/services/apid.go
- pkg/grpc/gen/remote.go
This moves endpoint refresh from the context of the service `apid` in
`machined` into `apid` service itself for the workers. `apid` does
initial poll for the endpoints when it boots, but also periodically
polls for new endpoints to make sure it has accurate list of `trustd`
endpoints to talk to, this handles cases when control plane endpoints
change (e.g. rolling replace of control plane nodes with new IPs).
Related to #3069
Fixes #3068
> fix: refresh control plane endpoints on worker apids on schedule

- internal/app/networkd/pkg/address/dhcp4.go
- internal/app/networkd/pkg/address/dhcp6.go
- internal/app/networkd/pkg/networkd/netconf.go
- internal/app/networkd/pkg/networkd/networkd_test.go
- internal/app/networkd/pkg/nic/nic.go
- internal/app/networkd/pkg/nic/vlan_options.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.9/Reference/configuration.md
This renames existing 'DHCP' implementation to `DHCP4`, new client is
`DHCP6`.
For now, `DHCP6` is disabled by default and should be explicitly enabled
with the config.
QEMU testbed for IPv6 is going to be pushed as separate PR.
> feat: implement IPv6 DHCP client in networkd

- internal/app/machined/pkg/system/services/networkd.go
- internal/app/networkd/pkg/networkd/networkd.go
Always prefer explicitly configured nameservers,
networkd was missing capability to bind address for DHCP6.
> fix: prefer configured nameservers, fix DHCP6 in container

- pkg/machinery/client/config/config.go
- pkg/machinery/client/config/config_test.go
fix: allow loading of empty config files
Fixes #3113.
> fix: allow loading of empty config files

- pkg/machinery/constants/constants.go
- website/content/docs/v0.9/Reference/configuration.md
> feat: upgrade CoreDNS to 1.8.0

- internal/app/machined/pkg/system/services/apid.go
- pkg/copy/copy.go
- pkg/machinery/constants/constants.go
Launch goroutine that copies kubelet pki folder contents into
`/system/secrets/kubelet` every minute before starting apid container
when running on the worker node.
Mounting kubelet secrets directly from `/var/lib/kubelet/pki` breaks
upgrade flow, because we are not able to unmount ephemeral partition,
which is being used by apid, which is not stopped during the upgrade.
> fix: mount kubelet secrets from system instead of ephemeral

- internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
- internal/app/machined/pkg/system/services/networkd.go
Before this change, every node had `os.Hostname()` of `talos-127-0-1-1`
which breaks resolving node hostname into the IP address (used in new
controller-runtime to fetch kubelet pod status).
> fix: set proper hostname on docker nodes

- internal/app/machined/pkg/controllers/secrets/kubernetes.go
- internal/app/machined/pkg/controllers/v1alpha1/boostrap_status.go
- internal/app/machined/pkg/controllers/v1alpha1/time_sync.go
- internal/app/machined/pkg/resources/v1alpha1/time_sync.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
Certificate generation depends on current time, and this bug is visible
on RPi which doesn't have RTC clock - controllers can generate certs
before `timed` does its initial sync creating certs which are not
usable.
Fix generates new intermediate resource `TimeSync` which tracks time
sync status (aggregates `timed` service status and `timed`
enabled/disabled in the config).
Fixes #3119
> fix: wait for time sync before generating Kubernetes certificates

- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- website/content/docs/v0.8/Guides/advanced-networking.md
- website/content/docs/v0.8/Reference/configuration.md
- website/content/docs/v0.9/Guides/advanced-networking.md
- website/content/docs/v0.9/Reference/configuration.md
Fixes a few typos in our docs.
> docs: fix typos

- Makefile
- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/cluster/show.go
- cmd/talosctl/cmd/mgmt/dhcpd_launch_linux.go
- go.mod
- go.sum
- internal/integration/api/reset.go
- internal/integration/cli/crashdump.go
- internal/integration/cli/health.go
- internal/integration/provision/upgrade.go
- pkg/cluster/apply-config.go
- pkg/provision/access/adapter.go
- pkg/provision/providers/docker/create.go
- pkg/provision/providers/docker/network.go
- pkg/provision/providers/docker/node.go
- pkg/provision/providers/docker/reflect.go
- pkg/provision/providers/firecracker/create.go
- pkg/provision/providers/firecracker/firecracker.go
- pkg/provision/providers/firecracker/node.go
- pkg/provision/providers/qemu/create.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/qemu/qemu.go
- pkg/provision/providers/vm/dhcpd.go
- pkg/provision/providers/vm/ipam.go
- pkg/provision/providers/vm/loadbalancer.go
- pkg/provision/providers/vm/network.go
- pkg/provision/request.go
- pkg/provision/result.go
- website/content/docs/v0.9/Reference/cli.md
Modify provision library to support multiple IPs, CIDRs, gateways, which
can be IPv4/IPv6. Based on IP types, enable services in the cluster to
run DHCPv4/DHCPv6 in the test environment.
There's outstanding bug left with routes not being properly set up in
the cluster so, IPs are not properly routable, but DHCPv6 works and IPs
are allocated (validates DHCPv6 client).
> test: add support for IPv6 in talosctl cluster create

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- internal/integration/provision/upgrade.go
- internal/pkg/configuration/configuration.go
- pkg/machinery/config/contract.go
- pkg/machinery/config/contract_test.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/bundle/options.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/generate_test.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- website/content/docs/v0.9/Reference/cli.md
This allows to generating current version Talos configs (by default) or
backwards compatible configuration (e.g. for Talos 0.8).
`talosctl gen config` defaults to current version, but explicit version
can be passed to the command via flags.
`talosctl cluster create` defaults to install/container image version,
but that can be overridden. This makes `talosctl cluster create` now
compatible with 0.8.1 images out of the box.
Upgrade tests use contract based on source version in the test.
When used as a library, `VersionContract` can be omitted (defaults to
current version) or passed explicitly. `VersionContract` can be
convienietly parsed from Talos version string or specified as one of the
constants.
Fixes #3130
> feat: support version contract for Talos config generation

- internal/app/machined/pkg/system/services/apid.go
On reboots, when `apid` is stopped, `PostFunc()` is called, but
`o.cancel` is only initialized for worker nodes, so it leads to `init`
panic on master nodes.
> fix: prevent crash in machined on apid service stop

- pkg/machinery/client/client.go
In our client API, as the request goes through `apid` proxying, actual
error might be wrapped into the response (to support multi-node
requests), so it should always be correctly unwrapped.
This has UX issue: `talosctl apply-config` silently doesn't work (server
API fails, but no errror is shown in `talosctl`).
> fix: correctly extract wrapped error messages

- internal/app/networkd/pkg/nic/nic.go
This PR fixes a bug where we removed adding attributes during the
RouteAdd call for rtnetlink. The way that code is implemented means that
if *any* attributes are passed, the defaults are ignored. But we were
expecting defaults to be there. No longer!
> fix: pass attributes when adding routes

- internal/app/machined/pkg/controllers/k8s/extra_manifest.go
Manifest URL might be anything, including any GET parameters which might
get into filename which might lead to 'filename too long' error. As each
URL is downloaded to a separate temporary directory, there's no reason
to use filename based on the URL.
> fix: don't use filename from URL when downloading manifest

- internal/app/networkd/pkg/nic/nic.go
This PR fixes a bug where we removed adding attributes during the
RouteAdd call for rtnetlink. The way that code is implemented means that
if *any* attributes are passed, the defaults are ignored. But we were
expecting defaults to be there. No longer!
(cherry picked from commit 1111edfc7681f2634d43c061a0f9f5bcfe56db4e)
> backport (fix): pass attributes when adding routes

- cmd/installer/cmd/iso.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
This allows to drop into GRUB menu and edit boot configuration.
> fix: add 3 seconds grub boot timeout

- internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
- pkg/kubernetes/kubernetes.go
Health checks verify node list in Kubernetes to match expectations, but
initial set of nodes for server-side health checks was driven by
`MasterIPs` functions which returns list of master endpoints which is
not exactly same as master nodes: endpoints also include some
healthchecks.
> fix: find master node IPs correctly in health checks

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
This should address flakiness issues related to partition unmount.
Also changed the order of partitions unmount in the sequencer.
> feat: stop all pods before unmounting the ephemeral partition

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- pkg/kubernetes/kubernetes.go
- pkg/machinery/constants/constants.go
Labels shouldn't be used, as this is not supposed to be used for
filtering pods. Use proper annotation prefix private for Talos.
Add config-version annotation to track how static pod propagates up to
API server (it will be used in control plane upgrade).
> fix: move versions to annotations in control plane static pods

- internal/app/machined/pkg/system/services/cri.go
This allows cri to start before etcd, allowing kubelet to be started
early on so that static pods can be started which might do some network
setup required for etcd to be up.
This fix was first added to 0.8 to help with single-node control plane
clusters.
> fix: drop cri dependency on etcd

- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/install/manifest_test.go
- cmd/installer/pkg/install/target.go
- go.mod
- go.sum
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/integration/provision/provision.go
- internal/integration/provision/upgrade.go
- internal/pkg/mount/mount.go
- internal/pkg/mount/options.go
- internal/pkg/mount/overlay.go
- internal/pkg/mount/squashfs.go
- internal/pkg/mount/system.go
- internal/pkg/partition/constants.go
- internal/pkg/partition/format.go
- internal/pkg/partition/partition.go
- pkg/cluster/check/default.go
Filesystem creation step is moved on the later stage: when Talos mounts
the partition for the first time.
Now it checks if the partition doesn't have any filesystem and formats
it right before mounting.
Additionally refactored mount options a bit:
- replaced separate options with a set of binary flags.
- implemented pre-mount and post-unmount hooks.
And fixed typos in couple of places and increased timeout for `apid ready`.
> feat: skip filesystem for state and ephemeral partitions in the installer

- .drone.jsonnet
That removes actually e2e-* from the `thrice-daily`.
> chore(ci): fix schedules in Drone pipelines

- .drone.jsonnet
- cmd/talosctl/cmd/talos/etcd.go
- internal/integration/cli/etcd.go
- pkg/machinery/client/client.go
This uses wrappers which helps to unwrap errors from proxied apid
responses.
> fix: correctly unwrap responses for etcd commands

- .drone.jsonnet
- Dockerfile
- cmd/installer/pkg/install/manifest.go
- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/test/e2e-qemu.sh
- internal/integration/api/apply-config.go
- internal/pkg/encryption/encryption.go
- internal/pkg/encryption/encryption_test.go
- internal/pkg/encryption/keys/keys.go
- internal/pkg/encryption/keys/nodeid.go
- internal/pkg/encryption/keys/options.go
- internal/pkg/encryption/keys/static.go
- internal/pkg/mount/options.go
- internal/pkg/mount/system.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/join.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- website/content/docs/v0.9/Reference/cli.md
- website/content/docs/v0.9/Reference/configuration.md
This PR introduces the first part of disk encryption support.
New config section `systemDiskEncryption` was added into MachineConfig.
For now it contains only Ephemeral partition encryption.
Encryption itself supports two kinds of keys for now:
- node id deterministic key.
- static key which is hardcoded in the config and mainly used for test
purposes.
Talosctl cluster create can now be told to encrypt ephemeral partition
by using `--encrypt-ephemeral` flag.
Additionally:
- updated pkgs library version.
- changed Dockefile to copy cryptsetup deps from pkgs.
> feat: implement ephemeral partition encryption

- .drone.jsonnet
This PR adds a trigger to aws and gcp e2e tasks to make sure they get
triggered during thrice-daily.
> test: trigger e2e on thrice daily

- .drone.jsonnet
- cmd/talosctl/cmd/mgmt/cluster/create.go
- go.sum
- hack/test/e2e-qemu.sh
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/adv.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/syslinux.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/talos/talos.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.9/Reference/cli.md
- website/content/docs/v0.9/Reference/configuration.md
Fixes: https://github.com/talos-systems/talos/issues/3109
State partition encryption support adds a new section to the machine config.
And a new step to the sequencer flow which saves encryption
configuration object as json serialized value in the META partition.
Everything else is the same as is for the ephemeral partition.
Additionally enabled state partition encryption in the disk encryption
integration tests.
> feat: add state encryption support

- cmd/talosctl/cmd/talos/etcd.go
- internal/integration/api/etcd.go
- pkg/machinery/client/client.go
This continues the fix from #3167.
> test: update integration tests to use wrapped client for etcd APIs

- .drone.jsonnet
This makes sure artifacts will allways be built as part of
the scheduled run, even if latest merge to master happened just before
the scheduled build.
> chore: run default pipeline as part of the `cron` pipeline

- internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
- internal/app/machined/pkg/controllers/k8s/manifest.go
- internal/app/machined/pkg/controllers/k8s/manifest_apply.go
- internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
- internal/app/machined/pkg/controllers/k8s/templates.go
- internal/app/machined/pkg/controllers/secrets/etcd.go
- internal/app/machined/pkg/controllers/secrets/kubernetes.go
- internal/app/machined/pkg/controllers/secrets/root.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- internal/pkg/kubeconfig/admin.go
- pkg/resources/secrets/etcd.go
- pkg/resources/secrets/kubernetes.go
- pkg/resources/secrets/root.go
Fixes #3062
There's no user-visible change in this PR.
It carefully separates generated secrets (e.g. certs) from source
secrets from the config (e.g. CAs), so that certs are generated on
config changes which actually affect cert input.
And same way separates etcd and Kubernetes PKI, so if etcd CA got
changed, only etcd certs will be regenerated.
This should have noticeable impact with RSA-based PKI as it reduces
number of times PKI gets generated.
> refactor: split kubernetes/etcd resource generation into subresources

- pkg/resources/k8s/manifest.go
- pkg/resources/k8s/manifest_test.go
If sub-doc contains a comment, it's not empty, but when
loaded into JSON it yields `nil` which should be skipped, as
`Unstructured` can't load from such object.
E.g.:
```
---
---
```
> fix: skip empty manifest YAML sub-documents

- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/app/machined/pkg/controllers/k8s/manifest.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/resources/config/k8s_control_plane.go
- website/content/docs/v0.9/Reference/configuration.md
This options drops kube-proxy manifest from the list of bootstrap
manifests. It might be used with CNIs which don't need `kube-proxy`.
> feat: add an option to disable kube-proxy manifest

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Encourage users to convert control plane to static pods after
upgrade to 0.9.
> feat: add a warning to boot log if running self-hosted control plane

- internal/app/machined/pkg/controllers/k8s/manifest.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- internal/app/machined/pkg/controllers/k8s/templates.go
- pkg/resources/k8s/manifest.go
JSON is a subset of YAML, so we can use JSON to escape whole YAML value
to handle any kind of symbols.
> fix: correctly escape extra args in kube-proxy manifest

- internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
- internal/app/machined/pkg/system/services/apid.go
- pkg/kubernetes/kubelet/kubelet.go
If kubelet is configured to issue certificates from the control plane,
`/var/lib/kubelet/pki/kubelet.crt` file is never created, and cluster CA
canv be used to verify the TLS connection.
Use k8s `RESTClient` instead of a custom client, this also results in
much more descriptive error messages if API call fails.
Fix a problem in apid on worker nodes with issued serving certificates:
`/var/lib/kubelet/pki` doesn't exist by the time `apid` starts.
First write static pods, then try to build kubelet client: for issued
serving kubelet certificates, control plane should be up first.
> fix: handle case when kubelet serving certificates are issued

- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/resources/config/k8s_control_plane.go
- pkg/resources/k8s/static_pod.go
- website/content/docs/v0.9/Reference/configuration.md
This allows to mount extra volumes into Talos-managed control plane
static pods. With additional options like extra files, any additional
content/configuration can be mounted.
> feat: add support for extra volume mounts for control plane pods

- internal/integration/provision/upgrade.go
- pkg/cluster/kubernetes/convert.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/cluster/kubernetes/upgrade.go
Upgrade is performed by updating node configuration (node by node, service
by service), watching internal resource state to get new configuration
version and verifying that pod with matching version successfully
propagated to the API server state and pod is ready.
Process is similar to the rolling update of the DaemonSet.
> feat: support control plane upgrades with Talos managed control plane

- internal/app/machined/pkg/controllers/k8s/manifest_apply.go
These warnings by default go to stderr, so to server console and flood
console with messages. Send warnings to the logger, so they stay
within controller-runtime logs.
> fix: redirect warnings in manifest apply k8s client

- Makefile
This brings in following PRs from pkgs:
* talos-systems/pkgs#243
* talos-systems/pkgs#244
* talos-systems/pkgs#245
> feat: u-boot 2021.01, ca-certificates update, Linux file ACLs

- internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Volume name should be DNS name, so make sure we don't have any leading
or trailing dashes in the generated volume name.
> fix: sanitize volume name better in static pod extra volumes

- .drone.jsonnet
- Makefile
- hack/test/e2e-qemu.sh
This adds new `IMAGE_REGISTRY` variable (similar to `IMAGE_TAG`) which
affects only the registry image gets pushed to, but it's not built into
the binaries and images as a default registry.
This fixes a problem when release builds reference our CI local
registry.
> chore: switch CI to stop embedding local registry into the builds

- internal/app/machined/internal/install/install.go
This fixes an issue when Talos on clean shutdown after install waits for
the process to terminate, that process is `containerd-shim` which is
still running because container wasn't cleaned up correctly.
> fix: stop and clean up installer container  correctly

- pkg/resources/v1alpha1/service.go
As 'healthy' was always set to true, some tasks started earlier than
expected, and specifically etcd cert was generated while the time sync
was happening leading to half-broken cert on RPi4.
> fix: correctly set service state in the resource

- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/kubernetes/kubernetes.go
Critical bug (I believe) was that drain code entered the loop to evict
the pod after wait for pod to be deleted returned success effectively
evicting pod once again once it got rescheduled to a different node.
Add a global timeout to prevent draining code from running forever.
Filter more pod types which shouldn't be ever drained.
Fixes #3124
> fix: improve the drain function

- internal/pkg/configuration/configuration.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/join.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_network_options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/go.mod
- pkg/provision/providers/docker/docker.go
- pkg/provision/providers/firecracker/firecracker.go
- pkg/provision/providers/qemu/qemu.go
Allow setting individual options for the network interface while
generating config instead of providing whole config. This solves the
problem of merging options from different sources to build the config.
There should be no changes with this PR.
This is prep work for control plane VIP.
> refactor: split WithNetworkConfig into sub-options

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/networkd/main.go
- internal/app/networkd/pkg/networkd/networkd.go
- internal/app/networkd/pkg/nic/nic.go
This changes introduces top-level cancellable on signal context to
networkd to abort operations when networkd is being stopped.
This allows for clean restarts of networkd container, and it is required
to support canceallable context for VIP etcd operations.
> refactor: add context to the networkd

- go.mod
- go.sum
- internal/app/apid/main.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/controllers/k8s/manifest_apply.go
- internal/app/machined/pkg/controllers/v1alpha1/boostrap_status.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/routerd/main.go
- internal/pkg/etcd/etcd.go
This version is finally using working `go.mod` files and tags, so no
more hacks with imports, and allows us to bump `grpc` library to the
latest version (I also did for this PR).
> feat: bump etcd client library to 3.5.0-alpha.0

- .drone.jsonnet
This showed up as missing Darwin talosctl in the release.
> chore: build both Darwin and Linux versions of talosctl

- cmd/talosctl/cmd/talos/containers.go
- cmd/talosctl/cmd/talos/logs.go
- cmd/talosctl/cmd/talos/restart.go
- cmd/talosctl/cmd/talos/root.go
- cmd/talosctl/cmd/talos/stats.go
- internal/integration/cli/containers.go
- internal/integration/cli/restart.go
- internal/integration/cli/stats.go
- internal/pkg/containers/cri/cri.go
- internal/pkg/containers/inspector.go
- website/content/docs/v0.9/Reference/cli.md
This fixes output of `talosctl containers` to show failed/exited
containers so that it's possible to see e.g. `kube-apiserver` container
when it fails to start. This also enables using ID from the container
list to see logs of failing containers, so it's easy to debug issues
when control plane pods don't start because of wrong configuration.
Also remove option to use either CRI or containerd inspector, default to
containerd for system namespace and to CRI for kubernetes namespace.
The only side effect is that we can't see `kubelet` container in the
output of `talosctl containers -k`, but `kubelet` itself is available in
`talosctl services` and `talosctl logs kubelet`.
> fix: show stopped/exited containers via CRI inspector

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
Accept both `1.19.2` and `v1.19.2` formats for kubernetes versions in
`talosctl gen`.
Fixes #3155
> feat: talosctl: allow v-prefixed k8s versions

- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
fix: set hdmi_safe=1 on Raspberry Pi for maximum HDMI compatibility
Setting hdmi_safe to 1 will lead to "safe mode" settings being used to try to boot with
maximum HDMI compatibility.
See https://www.raspberrypi.org/documentation/configuration/config-txt/video.md
My Raspberry Pi 4 8GB does boot without it.
> fix: set hdmi_safe=1 on Raspberry Pi for maximum HDMI compatibility

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
This should align all `apply-config` modes to use the same flows.
Also added unit-tests for `ApplyDynamicConfig`.
Fixes: https://github.com/talos-systems/talos/issues/3221
> fix: add ApplyDynamicConfig call in the apply-config --immediate mode

- internal/app/machined/pkg/controllers/secrets/kubernetes.go
- internal/integration/api/events.go
- pkg/resources/secrets/etcd.go
- pkg/resources/secrets/kubernetes.go
- pkg/resources/secrets/root.go
Talos generates in-cluster kubeconfig for the kube-scheduler and
kube-controller-manager to authenticate to kube-apiserver. Bug was that
validity of that kubeconfig was set to 24h by mistake. Fix that by
bumping validity to default for other Kubernetes certs (1 year).
Add a certificate refresh at 50% of the validity.
Fix bugs with copying secret resources which was leading to updates not
being propagated correctly.
> fix: update in-cluster kubeconfig validity to match other certs

- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rock64.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
Makes sense to update these guides to point to the v0.8.4 as it contains
many good fixes.
> docs: bump v0.8 release version in the SBCs guides

- Makefile
- internal/integration/provision/upgrade.go
- pkg/provision/providers/qemu/node.go
This drops support for 0.7.x in upgrade tests, and bumps tests to use
version 0.9.0-alpha.3 as the next stable (it will eventually graduate to
0.9.0).
> chore: update provision/upgrade tests to 0.9.0-alpha.3

- Makefile
- pkg/machinery/constants/constants.go
This PR pulls in a new version of pkgs which includes a linux kernel
bump.
> feat: update linux kernel to 5.10.19

- internal/pkg/mount/mount.go
This fixes a race condition between `udevd` issuing ioctl `BLKRRPART`
when block device is closed after partitioning/formatting and Talos
trying to mount a partition. When `BLKRRPART` is issued, kernel
temporarily wipes out all the in-memory partitions killing `/dev/sdX`
devices until partition scan is done.
> fix: ignore 'ENOENT' (no such file directory) on mount

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/main.go
- internal/app/machined/pkg/runtime/controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/kubernetes/kubernetes.go
This is required to correctly handle ACPI reboot or forceful reboots
during sequence that locks the controller.
Additionally fix `NoSchedule` untaint when the configuration is changed.
> chore: properly propagate context object in the controller

- cmd/talosctl/cmd/talos/output/json.go
- cmd/talosctl/cmd/talos/output/output.go
- cmd/talosctl/cmd/talos/output/yaml.go
- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
This adds support for `-o json` (easier to use `jq` to query additional
data), and prints event name in `--watch` mode.
> feat: support JSON output in `talosctl get`, event types

- cmd/talosctl/cmd/talos/edit.go
- cmd/talosctl/cmd/talos/patch.go
- website/content/docs/v0.9/Reference/cli.md
This allows to apply config even if sequencer is locked to recover from
confguration mistakes.
> feat: add `--on-reboot` flag to talosctl edit/patch machineConfig

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/main.go
- internal/app/machined/pkg/runtime/controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
Fixes: https://github.com/talos-systems/talos/issues/2997
Listen for restart events in parallel with the boot sequence and cancel
the context if got `RestartEvent`.
> feat: bypass lock if ACPI reboot/shutdown issued

- internal/app/machined/pkg/system/services/networkd.go
On upgrade with persistenct, etcd PKI path retains old mode 0600 which
breaks networkd bind mount for etcd certs.
> fix: chmod etcd PKI path to fix virtual IP for upgrades with persistence

- Makefile
- internal/integration/provision/upgrade.go
Resources/types were renamed after alpha.4, so we need Talos API to
match expectations of the upgrade test built against master.
> chore: fix upgrade tests by bumping 0.9 to alpha.5

- .drone.jsonnet
Otherwise we can quickly overflow our storage backend.
> chore: expire objects in CI S3 bucket

- pkg/cluster/kubernetes/convert.go
- pkg/cluster/kubernetes/kubernetes.go
- pkg/cluster/kubernetes/self_hosted.go
- pkg/cluster/kubernetes/talos_managed.go
Without loadbalancer, when api-server goes down, there will be
connection refused errors which should be retried.
> fix: ignore connection refused errors when updating/converting cp

- pkg/provision/providers/docker/docker.go
This was failed refactoring to the new config options.
> fix: properly propagate nameservers to provisioned docker clusters

- cmd/talosctl/cmd/mgmt/cluster/create.go
- internal/app/machined/pkg/system/services/kubelet.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/bundle/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
- website/content/docs/v0.9/Reference/cli.md
This makes sure source directory exists before performing mount
operation.
Also adds an ability to patch the config bundle configs with JSON patch,
which is exposed in `talosctl cluster create`, this allowed me to easily
test this fix:
```
talosctl cluster create ... --config-patch='[{"op": "add", "path": "/machine/kubelet/extraMounts", "value": [{"destination": "/var/log/containers", "type": "bind", "source": "/var/log/containers", "options": ["rshared", "rbind", "rw"]}]}]'
```
Fixes #3254
> fix: mkdir source of the extra mounts for the kubelet

- website/content/docs/v0.9/Bare Metal Platforms/digital-rebar.md
- website/content/docs/v0.9/Guides/air-gapped.md
- website/content/docs/v0.9/Guides/configuring-pull-through-cache.md
- website/content/docs/v0.9/Guides/configuring-the-cluster-endpoint.md
- website/content/docs/v0.9/Guides/configuring-wireguard-network.md
- website/content/docs/v0.9/Guides/editing-machine-configuration.md
- website/content/docs/v0.9/Introduction/what-is-new.md
- website/content/docs/v0.9/Learn More/components.md
Gridsome forces folders to be lower-case.
> docs: fix links in the documentation

- Makefile
This is major Go update to 1.16.x branch.
> chore: bump Go to 1.16.1

- internal/pkg/containers/cri/containerd/config_test.go
- internal/pkg/containers/cri/containerd/containerd.go
Talos user files task prohibits file creation under `/etc`.
> fix: move containerd CRI config files under `/var/`

- Makefile
Go 1.15.9 contains security fixes.
(this only updates 0.9 branch, as master is going to be updated to
1.16.1)
> chore: update Go to 1.15.9

- pkg/machinery/constants/constants.go
- website/content/docs/v0.9/Introduction/getting-started.md
- website/content/docs/v0.9/Reference/kernel.md
Update the Getting Started documentation to reflect the new ISO-based
installation method.
Fixes #3016
> docs: rewrite getting-started for ISO

- Makefile
- hack/test/provision-tests.sh
- internal/integration/integration_test.go
- internal/integration/provision/provision.go
- internal/integration/provision/upgrade.go
CNI was removed from build-container which works fine for
`talosctl cluster create` clusters as it installs its own CNI, but fails
for upgrade tests as they were never updated for the CNI bundle.
> chore: fix provision tests after changes to build-container

- Makefile
- cmd/talosctl/cmd/talos/convert-k8s.go
- hack/test/provision-tests.sh
- internal/integration/integration_test.go
- internal/integration/provision/provision.go
- internal/integration/provision/upgrade.go
- internal/pkg/containers/cri/containerd/config_test.go
- internal/pkg/containers/cri/containerd/containerd.go
- pkg/cluster/kubernetes/convert.go
This backports PRs #3283, #3287, #3293
> backport: conver-k8s output, CRI registry config fix, provision tests fix

- Makefile
- hack/test/provision-tests.sh
- internal/integration/integration_test.go
- internal/integration/provision/provision.go
- internal/integration/provision/upgrade.go
- internal/pkg/containers/cri/containerd/config_test.go
- internal/pkg/containers/cri/containerd/containerd.go
- internal/pkg/mount/mount.go
> backports: fix udevd mount race, CRI registry config, provision tests

- Makefile
- pkg/machinery/constants/constants.go
> chore: update Linux to 5.10.23

- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/install/manifest_test.go
- cmd/installer/pkg/install/target.go
- pkg/machinery/constants/constants.go
This fixes a case of upgrade from 0.9.0-alpha.4 to 0.9.0-beta.0. With
introduced proper partition alignment and physical block size != 512,
partitions before ephemeral will be moved around a bit (due to the
alignment), and `STATE` partition size might change a bit.
If encryption is enabled, contents are preserved as raw bytes, so
partition size should be exactly same during restore.
Drop code (mostly tests) which handled 0.6 to 0.7 upgrades.
On upgrade with preserve don't touch any partitions, at least for 0.8 ->
0.9 layout hasn't changed.
> fix: don't touch any partitions on upgrade with --preserve

- hack/test/e2e-aws.sh
This PR makes sure we set a cloud provider version, which will make our
AWS tests pass again.
> test: update aws cloud provider version

- pkg/cluster/check/default.go
- pkg/cluster/check/kubernetes.go
- pkg/cluster/check/reporter.go
- pkg/conditions/conditions.go
- pkg/conditions/poll.go
- pkg/conditions/poll_test.go
> fix: talosctl health should not check kube-proxy when it is disabled

- pkg/cluster/check/default.go
- pkg/cluster/check/kubernetes.go
- pkg/cluster/check/reporter.go
- pkg/conditions/conditions.go
- pkg/conditions/poll.go
- pkg/conditions/poll_test.go
Fixes #3299.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
(cherry picked from commit 7662d033bfc3d6e3878e2c2a2a1ec4d71dc2502e)
> backport: fix: talosctl health should not check kube-proxy when it is disabled

- hack/release.sh
- hack/release.toml
This replaces `git-chglog` with the `talos-systems/release-tool`.
We need to make sure we update `hack/release.toml` as we do PRs to make
sure we highlight any important feature or update as we go.
> chore: use new release tool for changelogs and release notes

- Makefile
`e2e-%` was missing due to bad regex.
> chore: fix `make help` output

- cmd/talosctl/cmd/completion.go
- website/content/docs/v0.9/Reference/cli.md
One place was missed.
Probably should be backported to 0.9?
> chore: remove old `osctl` reference

- internal/integration/provision/upgrade.go
- pkg/cluster/kubernetes/talos_managed.go
First, if the config for some component image (e.g. `apiServer`) is empty,
Talos pushes default image which is unknown to the script, so verify
that change is not no-op, as otherwise script will hang forvever waiting
for k8s control plane config update.
Second, with bootkube bootstrap it was fine to omit explicit kubernetes
version in upgrade test, but with Talos-managed that means that after
Talos upgrade Kubernetes gets upgraded as well (as Talos config doesn't
contain K8s version, and defaults are used). This is not what we want to
test actually.
> fix: upgrade-k8s bug with empty config values and provision script

- cmd/talosctl/cmd/completion.go
- website/content/docs/v0.9/Reference/cli.md
One place was missed.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
(cherry picked from commit f7d276b854c4c06f85155c517cc1de7109a53359)
> backport: chore: remove old `osctl` reference

- Makefile
Added rockpi_4 to the list of sbcs targets in the Makefile.
> fix: build rockpi4 metal image as part of CI build

- cmd/talosctl/cmd/completion.go
ZSH completion was broken in `talosctl`. Cobra does not hook the ZSH generated completion rules, as it appears. Tools with working ZSH cobra completion (such as `helm` and `kubectl`) do so by printing the hook (`compdef _<completion> <tool>`) themselves.
Fixes #3318
To get shell completion working for ZSH users (they are the best users!)
> fix: repair zsh completion

- internal/pkg/etcd/etcd.go
There are two APIs and `talosctl` commands:
* `etcd leave` removes the member from the cluster and removes etcd
data directory for the called node
* `etcd remove-member <node>` removes some other node from the etcd
cluster, but it doesn't affect called node state
This fixes confusing naming of the methods vs. what they're doing.
Fixes #3340
(cherry picked from commit ce795f1cea9d78c26edbcd4a40bb5d3637fde629)
> backport: fix: command `etcd remove-member` shouldn't remove etcd data directory

- website/gridsome.config.js
- website/static/_redirects
This makes the v0.9 release the default documentation.
> docs: make v0.9 the default docs

- Dockerfile
- hack/release.toml
- internal/app/apid/main.go
- internal/app/machined/main.go
- internal/app/machined/pkg/system/runner/containerd/containerd.go
- internal/app/machined/pkg/system/runner/containerd/containerd_test.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/routerd.go
- internal/app/machined/pkg/system/services/timed.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/app/routerd/main.go
- internal/app/timed/main.go
- internal/app/trustd/main.go
- internal/integration/cli/containers.go
- internal/pkg/containers/containerd/containerd.go
This removes container images for the aforementioned services, they are
now built into `machined` executable which launches one or another
service based on `argv[0]`.
Containers are started with rootfs directory which contains only a
single executable file for the service.
This creates rootfs on squashfs for each container in
`/opt/<container>`.
Service `networkd` is not touched as it's handled in #3350.
This removes all the image imports, snapshots and other things which
were associated with the existing way to run containers.
> refactor: move apid, routerd, timed and trustd to single executable

- website/content/docs/v0.10/Local Platforms/qemu.md
- website/content/docs/v0.7/Local Platforms/qemu.md
- website/content/docs/v0.8/Local Platforms/qemu.md
- website/content/docs/v0.9/Local Platforms/qemu.md
This PR fixes a docs bug where the name of the kernel and init to
download were incorrect for qemu.
> docs: update path for kernel downloads in qemu docs

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
This PR fixes a bug where, only when init nodes were used, we were
throwing an error during validation if there were no URLs in the list
for custom CNIs. We actually allow this empty list now so folks can
BYO-CNI.
Will fix #3300
> fix: allow empty list for CNI URLs

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Encryption config should be checked for state partition as well.
> fix: CNI config validation should apply to cp nodes, encryption config

- internal/app/networkd/pkg/address/dhcp4.go
Very easily reproduced when you start a node with a Dynamic IP.
Normally it should renew lease after TTL/2, but that doesn't happen, so
the node starts to get next IP one after another.
After looking at packets sent by other clients, found out that they
have `Client IP address` equal to the IP given by the DHCP server.
Additionally, changed DHCP client to send `Request` packets directly to the DHCP server after getting an offer.
It looks like DHCP spec states that you should use unicast request directly to DHCP server, not broadcast.
> fix: resolve the issue with DHCP lease not being renewed

- cmd/talosctl/cmd/talos/kubeconfig.go
This PR just fixes a teeny usability problem I saw yesterday with Steve,
where it's not immediately clear that you don't have to type the entire
word when you encounter an existing context when pulling kubeconfig.
> feat: show short options in talosctl kubeconfig

- go.mod
- go.sum
They were required long time ago, doesn't look like we need it now.
> chore: remove unused module replace directives

- website/content/docs/v0.10/Cloud Platforms/aws.md
- website/content/docs/v0.6/Cloud Platforms/aws.md
- website/content/docs/v0.7/Cloud Platforms/aws.md
- website/content/docs/v0.8/Cloud Platforms/aws.md
- website/content/docs/v0.9/Cloud Platforms/aws.md
This PR updates our AWS docs so that we specify a tag when creating
instances. This makes it easier to know which VMs were created as part
of this process, as well as quickly spot the init node.
> docs: update AWS docs to ensure instances are tagged

- cmd/talosctl/cmd/talos/convert-k8s.go
- pkg/cluster/kubernetes/convert.go
The command `--remove-initialized-key` is the last resort to convert
control plane when control plane is down for whatever reason, so it
should work when control plane is not available.
> fix: allow `convert-k8s --remove-initialized-keys` with K8s cp is down

- Dockerfile
Actually share golangci-lint cache.
> chore: fix typo

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
> fix: prevent panic in validate config if `machine.install` is missing

- internal/pkg/mount/system.go
- pkg/machinery/config/encoder/documentation.go
- pkg/machinery/config/encoder/encoder_test.go
- pkg/machinery/config/encoder/markdown.go
Fixes: https://github.com/talos-systems/talos/issues/3377  https://github.com/talos-systems/talos/issues/3380
Fixed data race in the encoder documentation examples by using `sync.Once`.
We only need to generate them once anyways and then it's not a big deal
that we are using the same pointers everywhere as they're pretty much
constant.
As of `system.go`, looks like we actually have concurrent operations for
partitions unmount. Just added a mutex there.
> fix: get rid of data race in encoder and fix concurrent map access

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- pkg/machinery/config/encoder/documentation.go
- pkg/machinery/config/encoder/encoder.go
- pkg/machinery/config/encoder/encoder_test.go
- pkg/machinery/config/encoder/markdown.go
- pkg/machinery/config/encoder/options.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- website/content/docs/v0.10/Cloud Platforms/aws.md
- website/content/docs/v0.10/Reference/cli.md
Fixes: https://github.com/talos-systems/talos/issues/3384
Instead of doing simple `--no-comments` flag, decided to use more
granular approach which allows to either disable examples, or docstring,
or both.
Thus the command looks like this:
```bash
talosctl gen config --with-docs=false --with-examples=false <...>
```
Both are enabled by default to provide better UX for users learning
Talos.
> feat: add ability to disable comments in talosctl gen config

- pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_network_options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
This avoids data race on config access: config object might be accessed
concurrently and it should be read-only on access.
> fix: don't write to config object on access

- internal/pkg/tui/components/form.go
- internal/pkg/tui/installer/state.go
- Table row selection was 1 element off, so disk selector wasn't quite
working.
- Reduce amount of interfaces on the last screen: show only ones that
have physical addresses (changing some settings for lo0 for example was
making TUI generate incorrect configs)
> fix: address several issues in TUI installer

- Dockerfile
- Makefile
This provides a variable to build core Talos components with race
detector enabled: `make initramfs WITH_RACE=yes`.
Our code still doesn't quite run in this mode, but this is a step
forward to check with race detector enabled.
> chore: build components with race detector enabled in dev mode

- Makefile
- pkg/machinery/constants/constants.go
This provides binary compatibility for really old binaries using 32-bit
time.
See also: talos-systems/pkgs#259
> feat: bring in Linux 5.10.27, support for 32-bit time syscalls

- website/content/docs/v0.10/Guides/upgrading-talos.md
- website/content/docs/v0.9/Guides/upgrading-talos.md
Found typo in the upgrading talos docs. It mentioned `--staged` flag, but it appears the flag is `--stage`.
> docs(upgrading-talos): fix typo for stage flag

- pkg/cluster/kubernetes/kubernetes.go
During the conversion process, API server goes down, so we can see lots
of network errors including EOF.
Fixes #3404
> fix: ignore EOF errors from Kubernetes API when converting control plane

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
The way processing works is that errors are not printed in the
sequencer, but something which called the sequencer prints the error,
but this means that for fatal failures say in 'upgrade' sequence error
message is printed by machined after the `apid` is stopped.
This means that error won't be visible via `talosctl dmesg`, but only in
serial console.
This changes the flow to print the task error as soon as task fails, and
removes 'done' messages in the sequencer if sequence/phase/task fails
(as otherwise it has both 'done' and 'failed' message which is
confusing).
> fix: print task failure error immediately

- pkg/cluster/kubernetes/convert.go
- pkg/cluster/kubernetes/kubernetes.go
- pkg/cluster/kubernetes/self_hosted.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/kubernetes/errors.go
- pkg/kubernetes/kubernetes.go
This extracts function which was used in upgrade/convert flows to retry
transient errors to the main `kubernetes` package, expands it to ignore
timeout errors, and it is now used to retry errors where applicable in
`pkg/kubernetes`.
Fixes #3403
> fix: retry Kubernetes API errors on cordon/uncordon/etc.

- Makefile
- internal/integration/provision/upgrade.go
Version 0.9.1 contains a fix for concurrent map write on unmount which
was frequently breaking our upgrade tests.
> test: update 0.9.x version in upgrade tests to 0.9.1

- Dockerfile
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/app/machined/pkg/system/services/utils.go
- pkg/machinery/constants/constants.go
Container rootfs should be writeable as containerd mounts standard
filesystems `/proc` et al.
When `/opt` was used as a root of container filesystem this results in a
problem: Talos overlay mounts `/opt` on `/var/system` which means that
as long as `apid` running `/var` can't be unmounted which breaks
upgrades.
So instead use `/system/libexec` as rootfs for the containers, `/system`
is `tmpfs`, and bind-mount actualy executable (`/sbin/init`, machined)
into rootfs.
This fixes upgrades for 0.10.
See also #3425
> fix: create rootfs for system services via /system tmpfs

- cmd/talosctl/cmd/mgmt/config.go
- internal/integration/cli/gen.go
- website/content/docs/v0.10/Bare Metal Platforms/digital-rebar.md
- website/content/docs/v0.10/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.10/Bare Metal Platforms/matchbox.md
- website/content/docs/v0.10/Cloud Platforms/aws.md
- website/content/docs/v0.10/Cloud Platforms/digitalocean.md
- website/content/docs/v0.10/Cloud Platforms/gcp.md
- website/content/docs/v0.10/Cloud Platforms/openstack.md
- website/content/docs/v0.10/Reference/cli.md
- website/content/docs/v0.10/Virtualized Platforms/vmware.md
Fixes: https://github.com/talos-systems/talos/issues/3410
Same as in `talosctl cluster create`. Will apply RFC6902 json patch
during the config generation if specified.
> feat: add --config-patch parameter to talosctl gen config

- .drone.jsonnet
Attempt #2. Forgot to add it to .drone.jsonnet also :facepalm:
> fix: publish rockpi4 image to release artifacts

- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/install/manifest_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Overlay mount in `mountinfo` don't show up as mounts for any particular
block device, so the existing check doesn't catch them.
This was discovered as our current master can't upgrade because of
overlay mount for `/opt` and `apid` image in `/opt/apid` (which will be
fixed in a separate PR).
Without the check, installer fails on resetting partition table for the
disk effectively wiping the node (`device or resourse busy` error).
> fix: add a check for overlay mounts in installer pre-flight checks

- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt
- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
Closes #3414.
Should be tested manually before merge.
> fix: make both HDMI ports work on RPi 4

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/etcd.go
This fix is not obvious on whether we need it actually or not, but what
I've seen in the tests seems to be around the fact that added member is
not visible in the member list fetched after the add command succeeds.
> fix: require leader on etcd member operations

- Dockerfile
- Makefile
- hack/cleanup.sh
- hack/test/e2e-aws.sh
- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/pkg/kubeconfig/admin_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_externalcloudproviderconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
- website/content/docs/v0.10/Reference/configuration.md
Closes #3312.
Requires changes/reorganization in cluster-api-templates. Draft: https://github.com/AlekSi/talos-cluster-api-templates/pull/1/files
> feat: allow external cloud provides configration

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See talos-systems/go-blockdevice#34 talos-systems/talos#3440
That change broke UEFI boot.
> fix: revert mark PMBR EFI partition as bootable

- cmd/talosctl/cmd/talos/config.go
When copy-pasting extra space might be added around an argument to the
`talosctl config endpoints/nodes`, which breaks the config as the
endpoint doesn't parse anymore as IP address.
> fix: trim endpoints/nodes from arguments in talosctl config

- hack/test/e2e-capi.sh
This PR pulls in an updated cluster api aws version, ensuring the CRDs
are closer to what's expected when we patch the CAPA image later in the
setup. We will eventually move to 0.6.5 as soon as it's cut.
> test: update CAPA to 0.6.4

- Makefile
- internal/integration/provision/upgrade.go
In preparation for going 0.10 beta, start testing upgrades to 0.10, drop
0.8 and self-hosted control plane handling in the tests.
> test: update upgrade tests to 0.10 release

- Makefile
- pkg/machinery/constants/constants.go
See talos-systems/pkgs#261 talos-systems/pkgs#262
> chore: update Linux to 5.10.28, u-boot to final 2021.04 release

- website/content/docs/v0.10/Guides/disk-encryption.md
- website/content/docs/v0.9/Guides/disk-encryption.md
Fixes a typo in a documented command for going from an unencrypted
EPHEMERAL partition to an encrypted one.
Because typos are bad, mkay? ;)
> docs: fixup typo in encryption guide command

- cmd/installer/cmd/install.go
- internal/app/machined/internal/install/install.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/runner/containerd/containerd.go
- internal/app/machined/pkg/system/runner/containerd/stdin.go
- pkg/machinery/config/configloader/configloader.go
Talos validates machine configuration at boot time, and refuses to boot
if machine configuration is invalid.
As machine configuration validation rules might change over time, we
need to prevent a scenario when after an upgrade machine configuration
becomes invalid, as there's no way to roll back properly.
Machine configuration is submitted over stdin to the installer
container, and installer container validates it using the new version of
Talos (which is going to be installed).
If the config is not sent over stdin, installer assumes old version of
Talos and proceeds.
This should be backported to 0.9 to allow config validation on upgrade
to 0.10.
Fixes #3419
> feat: validate the machine configuration in the installer container

- Dockerfile
- Makefile
- pkg/machinery/api/cluster/cluster_grpc.pb.go
- pkg/machinery/api/health/health_grpc.pb.go
- pkg/machinery/api/inspect/inspect_grpc.pb.go
- pkg/machinery/api/machine/machine_grpc.pb.go
- pkg/machinery/api/network/network_grpc.pb.go
- pkg/machinery/api/resource/resource_grpc.pb.go
- pkg/machinery/api/security/security_grpc.pb.go
- pkg/machinery/api/storage/storage_grpc.pb.go
- pkg/machinery/api/time/time_grpc.pb.go
Plus add stringer tool.
https://golang.org/doc/go1.16#go-command
> go install now accepts arguments with version suffixes (for example, go install example.com/cmd@v1.0.0). This causes go install to build and install packages in module-aware mode, ignoring the go.mod file in the current directory or any parent directory, if there is one. This is useful for installing executables without affecting the dependencies of the main module.
> chore: use Go 1.16 global install command

- pkg/machinery/config/contract_test.go
Test that `v0.8.` is not a typo.
> test: extend unit-tests for config contract parsing

- .codecov.yml
- Dockerfile
This allows us to see test coverage of packages that can't be unit-tested directly.
> chore: apply coverage analysis to all packages

- pkg/kubernetes/errors.go
Looks like tls errors implement the interface, but they are not derived
from the `*net.OpError`, so this check should catch more errors.
Fixes #3457
> fix: check retryable network errors by interface

- hack/release.toml
- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
- internal/app/machined/pkg/controllers/k8s/extra_manifest.go
- internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_inlinemanifest.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
- pkg/resources/config/k8s_control_plane.go
- website/content/docs/v0.10/Reference/configuration.md
Inline manifests work exactly same way as extra manifests, but the
manifest itself can be stored in the config body.
Example config patch:
```
--config-patch '[{"op": "replace", "path": "/cluster/inlineManifests", "value": [{"name": "foo", "contents": "apiVersion: v1\nkind: Namespace\nmetadata:\n  name: ci\n"}]}]'
```
Fixes #3416 
> feat: implement inline manifests in the machine configuration

- internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
Two PRs got merged, one which had old import paths and another one which
had import paths updated, and some paths didn't get updated properly.
> chore: fix import path mismerge

- Makefile
- pkg/machinery/constants/constants.go
Also brings tools/pkgs/extras re-tagged from a stable branch for Talos
0.10 release.
> feat: Linux 5.10.29 kernel

- cmd/installer/pkg/ova/ova.go
- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
- pkg/machinery/constants/constants.go
This PR makes Talos read VMWare's OVF Environment.  See #3452 3452
1. On vCloud Director, it seems the only way to supply customization info to the guest OS
2. Some sources claim that this is the "Right Way" to supply customization info to the guest OS, and that plain guestinfo is legacy/hacky (although it works)
> Read VMWare OVF Environment

- pkg/resources/k8s/manifest.go
This might lead to manifests being appended forever on changes.
Fixes #3476
> fix: zero out manifest contents before setting new value

- cmd/talosctl/cmd/talos/images.go
- pkg/machinery/config/encoder/documentation.go
- pkg/machinery/config/encoder/encoder.go
- pkg/machinery/config/encoder/encoder_test.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.10/Reference/configuration.md
For config patching, it's beneficial to have some fields to be present
in the config, even with the default (empty) value. At the same time not
all fields should be present in all versions of the config, e.g. some
config value don't apply to worker node configuration.
Empty value and nil value are treated equal by `yaml` library, but Talos
encoder can be made more smart to still output empty (non-nil) value to
the config, while skipping completely nil fields.
This PR implements that via new `talos:"omitonlyifnil"` tag and plus
moves docs for such fields into comments under the value.
GC'ed pod checkpointer config, so it doesn't get generated even as
comments (it was empty by default even for 0.8, so this just removes
comments about it).
Signed-off-by: Andrey Smirnov …
> feat: provide Talos machine config with field placeholders and docs

- .conform.yaml
- Makefile
In recent versions of conform, scope is regexp so `*` is not a valid
regexp.
> chore: fix conform with scopes

- internal/app/machined/pkg/system/services/etcd.go
- internal/pkg/etcd/etcd.go
Better error message to understand where the error is coming from, also
print errors to console when etcd is trying to join - this is invaluable
to understand why etcd doesn't join the cluster.
> fix: update etcd client errors, print etcd join failures

- Makefile
- hack/test/e2e.sh
- internal/integration/provision/upgrade.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.9/Reference/cli.md
- website/content/docs/v0.9/Reference/configuration.md
This PR brings in a newer version of 1.20.x to make sure we're not
shipping with https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#cve-2021-25735-validating-admission-webhook-does-not-observe-some-previous-fields
> feat: bump k8s version to 1.20.6

- .drone.jsonnet
- cmd/talosctl/cmd/talos/conformance.go
- hack/test/e2e-qemu.sh
- hack/test/e2e.sh
- pkg/cluster/sonobuoy/product.go
- pkg/cluster/sonobuoy/sonobuoy.go
- website/content/docs/v0.10/Reference/cli.md
Command implements two modes:
* `fast`: conformance suite is run at maximum speed
* `certified`: conformance suite is run in serial mode, results
are captured to produce artifacts ready for CNCF submission process
Fixes #3420
> test: implement `talosctl conformance` command to run e2e tests

- Makefile
This updates the pkgs version to pull in a fix for CPU scaling on
raspberry pi. It will be backported to release-0.10 upon merge.
> feat: update pkgs version

- hack/test/e2e.sh
REGISTRY_MIRROR_FLAGS can be already defined in the environment with .env or .envrc file.
Use it for easier and faster local e2e tests.
> chore: use REGISTRY_MIRROR_FLAGS if defined

- .drone.jsonnet
That's the best we can do now with https://about.codecov.io/security-update/
> chore: use codecov from the build container

- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
This introduces a check if the VMWare OVF environment is empty, so the code does not die if it is.
To get the OVA working without OVF env vars. See #3513
> fix: check if OVF env is empty

- .drone.jsonnet
- Dockerfile
- Makefile
- cmd/installer/cmd/image.go
- cmd/installer/cmd/iso.go
- cmd/installer/cmd/root.go
- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/ova/ova.go
- internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rock64/rock64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4/rockpi4.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- pkg/machinery/constants/constants.go
- pkg/provision/providers/qemu/preflight.go
This has two big visible changes:
* `installer` image now contains assets for both `amd64` and `arm64`, so
it can be used to generate any Talos image (including RPi on amd64 host)
* Talos is using cross-compilation instead of emulation to build
non-native architectures: on amd64, Go amd64 compiler produces binaries
for both arm64 and amd64
(before this change: Go arm64 compiler via QEMU produces arm64 binaries on amd64)
CI implications: we no longer require arm64 nodes.
Changes walkthrough:
* `installer` container now keeps assets under `/usr/install/<arch>`
* Dockerfile build starts forcing toolchain/base image to use the build
host native architecture, not target architecture
* lots of duplication for amd64/arm64 as we want to combine assets for
both arches in a single image (e.g. we …
> chore: refactor Dockerfile for cross-compilation

- cmd/installer/pkg/ova/ova.go
This changes the osType field in the ova to `other3xLinux64Guest` in order to have VMware accept it when deploying manually.
To be able to deploy the OVA directly into the vSphere HTML UI. See #3515.
> fix: update osType in OVA other3xLinux64Guest"

- pkg/machinery/config/types/v1alpha1/generate/options.go
As we discussed in Slack, I added new function for the registry CA cert.
Based on my tests, CA cert is created with proper content, however, I suspect just another containerd bug because CA seems to be not in use at all even if containerd.tmpl file also has proper content.
golang API to add custom CA certificate for registries.
We use docker registries with self-signed certificates. Already implemented "insecure_skip_verify" option is buggy in containerd.
Related containerd issue in github: https://github.com/containerd/containerd/issues/5079
> add WithRegistryCaCert

- website/src/data/cloud-images.json
Replaces AWS images with the latest 0.9.3, as 0.9.2/0.9.1 contain many
important fixes vs. 0.9.0 release we have today.
> docs: update cloud images for Talos v0.9.3

- pkg/kubernetes/kubelet/kubelet.go
Kubelet might be running either self-signed cert (by default) or API
server issued cert (signed by the CA). User might switch between the two
methods, so instead of guessing based on filesystem contents, accept
both Kubernetes CA and self-signed cert (if available).
Spotted by @aceat64
> fix: use both self-signed and Kubernetes CA to verify Kubelet cert

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- internal/integration/cli/gen.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/bundle/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
- website/content/docs/v0.11/Reference/cli.md
The problem is that some patches can't be applied to join config, as
some nodes don't even exist in the config, for example
`/cluster/apiServer` node, and applying such patches doesn't make any
sense.
> feat: add `--config-patch` flag by node type

- Makefile
Enable memory overcommit for VMware setup.
> feat: pull kernel with VMware balloon module enabled

- Makefile
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/pine64/pine64.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.11/Single Board Computers/pine64.md
This PR adds support for the Pine64 and Pine64+ SBC.
My Pine64 SBC really needs Talos. And Talos needs even more SBC support
> WIP: add Pine64 SBC support

- website/static/_redirects
Our latest version should be 0.10 now.
> docs: update redirects to Talos 0.10

- website/content/docs/v0.10/index.md
- website/content/docs/v0.11/index.md
- website/content/docs/v0.9/index.md
Add links to the Talos Matrix rooms (which are themselves linked to the
corresponding Slack channels).
> docs: add Matrix room links

- Makefile
This commit adds support for:
- PL2303
- CP210x
- CH341
- FTDI SIO
I'd like to use Talos to measure utilities (water, energy) in my home.
> feat: add USB serial drivers

- .drone.jsonnet
- Makefile
- internal/app/machined/pkg/runtime/v1alpha1/board/pine64/pine64.go
- pkg/machinery/constants/constants.go
Apparantly, I submitted non working Pine64 support earlier in #3559. I messed up my git checkout and pushed the wrong branch. Also, the board was not included in `sbcs` make target or Drone CI. This commit fixes all these things. 
Without this commit, there is non functioning pine64 support
> Repair pine64 support

- internal/pkg/cri/pods.go
Message:
```
WARNING: DATA RACE
Write at 0x00c000a9d4d0 by goroutine 154:
github.com/talos-systems/talos/internal/pkg/cri.stopAndRemove.func1()
/src/internal/pkg/cri/pods.go:188 +0x312
golang.org/x/sync/errgroup.(*Group).Go.func1()
/.cache/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94
Previous write at 0x00c000a9d4d0 by goroutine 276:
github.com/talos-systems/talos/internal/pkg/cri.stopAndRemove.func1()
/src/internal/pkg/cri/pods.go:188 +0x312
golang.org/x/sync/errgroup.(*Group).Go.func1()
/.cache/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94
```
This bug might lead to incorrect pod stop handling at worst.
> fix: avoid data race on CRI pod stop

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Otherwise it never detected mmc and nvme devices as such.
> fix: update go-blockdevice to fix disk type detection

- .drone.jsonnet
This fixes the dependency in the nightly run to make sure artifacts are
rebuilt fresh before triggering conformance run (every other step did
that, but not this one).
> chore: make conformance pipeline depend on cron-default

- website/src/components/AMIImages.vue
- website/src/data/cloud-images.json
This wraps AMI table into `<details>`, so by default it's not visible
and one can click to expand the table and find the AMI ID they need.
> docs: add AMIs for 0.10.1, collapse list of AMIs by default

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
The problem is with VIP and `reset` sequence: the order of operations
was that `etcd` was stopped first while `networkd` was still running,
and if the node owned the VIP at the time of the reset action, the lease
will be lost (as client connection is gone), so VIP will be unassigned
for a pretty long time.
This PR changes the order of operations: first, stop `networkd` and
other pods, and leave `etcd` last, so that VIP is released, and
`kube-apiserver` for example isn't left hanging on the node while `etcd`
is gone.
Fixes #3500
> fix: stop networkd before leaving etcd on 'reset' path

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Static pods changes 
- switch livenessProbe to ssl port
- add request resources
Cannot disable insecure ports, livenessProbe will fail
By security reason, we can close ports 10251, 10252 (--port=0 extraArgs param)
Add requests resources to static pods (#3562).
> feat: static pods improvements

- go.mod
- go.sum
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Also updated go-blockdevice library that makes disk type string case
insensitive.
> fix: properly pass disk type selector from config to matcher

- go.mod
- go.sum
This pulls in a newer version of smbios so that we can detect lower
smbios version and handle endianness if necessary.
> feat: update go-smbios library

- Makefile
- go.mod
- go.sum
- pkg/machinery/constants/constants.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/containerd/containerd/releases/tag/v1.4.5
See talos-systems/pkgs#277
> feat: update containerd to 1.4.5, runc to 1.0.0-rc94

- internal/pkg/configuration/configuration.go
Previosly it was set only if NetworkConfig is not nil.
> fix: properly populate AllowSchedulingOnMasters option in gen config RPC

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
The change is essentially same as #3590, but applied to the upgrade path
which is very similar to the reset path.
We have to stop networkd (and remove the VIP/lease on the VIP) before we
leave and stop etcd. Plus we stop the kube-apiserver before the etcd is
stopped, so that we don't have unhealthy kube-apiserver.
> fix: stop networkd and pods before leaving etcd on upgrade

- cmd/talosctl/cmd/talos/etcd.go
Header was printed more than once.
> fix: properly compose pattern and header in etcd members output

- Makefile
> chore: keep debug symbols in debug builds

- Makefile
- go.mod
- go.sum
- pkg/machinery/constants/constants.go
See https://github.com/containerd/containerd/releases/tag/v1.5.1
Also brings Talos kernel with Geneve encapsulation for Openvswitch (see
talos-systems/pkgs#278).
> feat: update containerd to 1.5.1

- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
There's no change to the default behavior. This change is going to be
used with Sidero/Sfyra.
> test: provide a way to force different boot order in provision library

- .dockerignore
- .textlintrc.json
- Dockerfile
- README.md
- website/content/docs/v0.10/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.10/Cloud Platforms/digitalocean.md
- website/content/docs/v0.10/Learn More/control-plane.md
- website/content/docs/v0.10/Learn More/controllers-resources.md
- website/content/docs/v0.10/Learn More/faqs.md
- website/content/docs/v0.11/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.11/Cloud Platforms/digitalocean.md
- website/content/docs/v0.11/Learn More/control-plane.md
- website/content/docs/v0.11/Learn More/controllers-resources.md
- website/content/docs/v0.11/Learn More/faqs.md
- website/content/docs/v0.6/Learn More/faqs.md
- website/content/docs/v0.7/Cloud Platforms/digitalocean.md
- website/content/docs/v0.7/Learn More/faqs.md
- website/content/docs/v0.8/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.8/Cloud Platforms/digitalocean.md
- website/content/docs/v0.8/Learn More/faqs.md
- website/content/docs/v0.9/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.9/Cloud Platforms/digitalocean.md
- website/content/docs/v0.9/Learn More/control-plane.md
- website/content/docs/v0.9/Learn More/controllers-resources.md
- website/content/docs/v0.9/Learn More/faqs.md
* without `-print0` / `-0`, paths with spaces were skipped sometimes;
* `--stdin-filename` flag incorrectly consumed the first file.
> chore: fix markdown linting

- Makefile
- go.mod
- go.sum
- pkg/machinery/constants/constants.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
This also updates libseccomp.
This addresses [CVE-2021-30465](https://github.com/opencontainers/runc/security/advisories/GHSA-c3xm-pvg7-gh7r).
> feat: update containerd to 1.4.6, runc to 1.0.0-rc95

- Makefile
- go.mod
- go.sum
- pkg/machinery/constants/constants.go
This also updates libseccomp and add support for `netxen` networkd card.
This addresses[CVE-2021-30465](https://github.com/opencontainers/runc/security/advisories/GHSA-c3xm-pvg7-gh7r).
> feat: update containerd to 1.5.2, runc to 1.0.0-rc95

- cmd/installer/pkg/ova/ova.go
This will add `talos.config` to the VMware vApp properties, this will allow the OVA to be deployed including the talos config.
see issue: #3669 
Currently the code reads the talos.config from the OVF, however since the property (talos.config) is not defined you cannot set it when deploying the OVA to vSphere.
> fix: Add talos.config to the vApp Properties in VMware OVA

- Dockerfile
The problem is that `pkg/machinery` is a submodule, so regular go walk
over the pattern `./...` doesn't include submodules, so we have to call
explicitly for the submodule.
This also enables go generate for all `./pkg`.
> chore: fix go generate for the machinery

- cmd/installer/cmd/install.go
- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/manifest.go
- go.mod
- go.sum
- hack/release.toml
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- website/content/docs/v0.11/Reference/configuration.md
Fixes: https://github.com/talos-systems/talos/issues/3532
Machine install section now has `markMBRBootable` option.
> feat: add ability to mark MBR partition bootable

- hack/release.toml
- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/app/machined/pkg/controllers/k8s/manifest.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/resources/config/k8s_control_plane.go
- website/content/docs/v0.11/Reference/configuration.md
Fixes: https://github.com/talos-systems/talos/issues/3556
Introduce `coredns.disabled` flag to the machine config that allows
turning off coredns deployment during cluster bootstrap.
> feat: add the ability to disable CoreDNS

- internal/app/machined/pkg/system/runner/containerd/containerd.go
I wasn't able to reproduce this case, but looks like containerd can get
into a state when the snapshot was left behind, but container record is
missing. This prevents the container from being started with the error:
```
failed to create container kubelet: snapshot kubelet: already exists
```
This PR should help to fix this issue by trying to remove the snapshot
by name even if the container record is not found.
> fix: clean up stale snapshots on container start

- Dockerfile
- Makefile
Go cross-compilation is not quite compatible with Go race detector, as C
toolchain is not cross-compliation ready.
Workaround is really simple: for race-enabled builds, don't build
multi-arch installer image (that is installer image which contains both
amd64 and arm64 Talos artifacts), but build installer artifacts only for
the target arch (skipping cross-compilation).
> chore: skip building multi-arch installer for race-enabled build

- internal/app/machined/pkg/controllers/network/node_address.go
- internal/app/machined/pkg/controllers/network/node_address_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- pkg/resources/network/address_status.go
- pkg/resources/network/link_status.go
- pkg/resources/network/network_test.go
- pkg/resources/network/node_address.go
This controller provides three important aggregated resources to be
consumed by different interested parties:
* "default" node IP
* "current" addresses (node can be reached on these at the moment)
* "accumulative" addresses (for certSANs)
Example:
```
$ talosctl get nodeaddresses -n 172.20.0.2
NODE         NAMESPACE   TYPE          ID             VERSION   ADDRESSES
172.20.0.2   network     NodeAddress   accumulative   4         ["10.244.0.0","10.244.0.1","172.20.0.2"]
172.20.0.2   network     NodeAddress   current        6         ["10.244.0.0","10.244.0.1","172.20.0.2"]
172.20.0.2   network     NodeAddress   default        1         ["172.20.0.2"]
```
> feat: implement NodeAddress controller

- internal/app/machined/pkg/controllers/network/cmdline.go
- internal/app/machined/pkg/controllers/network/cmdline_test.go
- pkg/machinery/constants/constants.go
This parses Talos cmdline args in addition to standard `ip=` cmdline
params.
GC'ed unused constant.
> feat: parse Talos-specific cmdline params

- internal/app/machined/pkg/controllers/perf/perf.go
- internal/app/machined/pkg/controllers/perf/perf_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- pkg/resources/perf/cpu.go
- pkg/resources/perf/mem.go
- pkg/resources/perf/perf.go
- pkg/resources/perf/perf_test.go
- pkg/resources/secrets/etcd.go
Now the latest value for CPU and Memory is also represented as COSI
resources.
Was going back and forth in the implementation but in the end decided to
use dedicated yaml structures for both CPU and Memory stats because:
- JSON tags are ignored by `go-yaml`, so the output is not really great.
- protobuf Talos definition contains fields which we don't really need
in the YAML output of `talosctl get`.
- current state of Talos resource service does not support protobuf
encoding for resources.
So the plan for Theila is to just use the structure as a dynamic object
without relying on protobufs. At least for now.
> feat: implement CPU and Memory stats controller

- cmd/talosctl/cmd/mgmt/config.go
- hack/release.toml
- internal/integration/cli/gen.go
- internal/integration/cli/validate.go
- website/content/docs/v0.11/Bare Metal Platforms/digital-rebar.md
- website/content/docs/v0.11/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.11/Bare Metal Platforms/matchbox.md
- website/content/docs/v0.11/Cloud Platforms/aws.md
- website/content/docs/v0.11/Cloud Platforms/azure.md
- website/content/docs/v0.11/Cloud Platforms/digitalocean.md
- website/content/docs/v0.11/Cloud Platforms/gcp.md
- website/content/docs/v0.11/Cloud Platforms/openstack.md
- website/content/docs/v0.11/Guides/configuring-the-cluster-endpoint.md
- website/content/docs/v0.11/Introduction/getting-started.md
- website/content/docs/v0.11/Local Platforms/virtualbox.md
- website/content/docs/v0.11/Virtualized Platforms/proxmox.md
- website/content/docs/v0.11/Virtualized Platforms/vmware.md
Changes `gen config` to output `controlplane` and `join` machine config
types only. Users can manually set the `type` to `init` if they need to.
> feat: default to bootstrap workflow

- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
Installer puts `none` if no URL was present in the cmdline on boot, e.g.
when installing from ISO.
> fix: drop into maintenance mode if config URL is `none` (metal)

- Makefile
- pkg/machinery/constants/constants.go
> chore: use Go 1.16.5

- internal/app/machined/pkg/controllers/files/etcfile.go
- internal/app/machined/pkg/controllers/files/etcfile_test.go
- internal/app/machined/pkg/controllers/files/files.go
- internal/app/machined/pkg/controllers/network/etcfile.go
- internal/app/machined/pkg/controllers/network/etcfile_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- pkg/resources/files/etcfile_spec.go
- pkg/resources/files/etcfile_status.go
- pkg/resources/files/files.go
- pkg/resources/files/files_test.go
This implements two controllers: one which generates templates for
`/etc/hosts` and `/etc/resolv.config`, and another generic controller
which renders files to `/etc` via shadow bind mounts.
> feat: implement EtcFileController to render files in `/etc`

- internal/app/machined/pkg/controllers/network/status.go
- internal/app/machined/pkg/controllers/network/status_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- pkg/resources/network/condition.go
- pkg/resources/network/condition_test.go
- pkg/resources/network/network_test.go
- pkg/resources/network/status.go
This resource holds aggregated network status which can be easily used
in various places to wait for the network to reach some desired state.
The state checks are simple right now, we might improve the logic to
make sure all the configured network subsystems reached defined state,
but this might come later as we refine the logic (e.g. to make sure that
all static configuration got applied, etc.)
> feat: implement network.Status resource and controller

- internal/app/machined/pkg/controllers/network/address_merge_test.go
- internal/app/machined/pkg/controllers/network/hostname_merge_test.go
- internal/app/machined/pkg/controllers/network/link_merge_test.go
- internal/app/machined/pkg/controllers/network/operator/dhcp4.go
- internal/app/machined/pkg/controllers/network/operator/operator.go
- internal/app/machined/pkg/controllers/network/resolver_merge_test.go
- internal/app/machined/pkg/controllers/network/route_merge_test.go
- internal/app/machined/pkg/controllers/network/timeserver_merge_test.go
- pkg/resources/network/configlayer.go
- pkg/resources/network/configlayer_string.go
There is nothing new in the DHCP4 operator, it's more or less adapted
code from networkd.
Other operators coming: DHCP6, VIP, WgLAN, etc.
> feat: implement operator framework with DHCP4 as the first example

- pkg/machinery/client/resources.go
Current interface does not provide a way to pass `tailEvents` param.
Theila is using this client and it needs to specify `tailEvents`.
> chore: expose WatchRequest in the resources client

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/network/address_spec.go
- internal/app/machined/pkg/controllers/network/operator/vip.go
- pkg/resources/network/address_spec.go
Code mostly copy-pasted from the networkd implementation, but adapted to
the resource model:
* watch for etcd state to start/stop activities
* watch for kube-api-server static pod state to give up VIP when
api-server goes down
Gratuitous ARP code re-implemented to drop dependency on kube-vip (once
the old networkd code is removed).
> feat: implement virtual IP (shared IP) network operator

- pkg/machinery/client/context.go
Many places rely on the "replace" semantics, and the change in #3738
broke that assumpion. This was showing up as upgrade test failure when
upgrade code saw a duplicate of config resource (as it saw responses
from two nodes).
> fix: overwrite nodes in the gRPC metadata

- internal/app/machined/pkg/controllers/network/operator_spec.go
- internal/app/machined/pkg/controllers/network/operator_spec_test.go
Controller operates on `OperatorSpec` resources generated by
`OperatorSpecController` from the machine configuration.
`OperatorSpecControllers` figures out whether operator should run based
on link status, restarts operators on configuration changes.
The controller also scrapes operators for the specs and syncs them as
resources.
> feat: implement controller which runs network operators

- internal/app/machined/pkg/controllers/network/platform_config.go
This concludes the last piece of the networkd replacement puzzle.
Platform hostname is fetched once and injected as a spec for the merge
process to pick it up.
> feat: implement platform config controller (hostnames)

- internal/app/machined/pkg/controllers/network/link_status.go
Looks like on some platforms (RPi4 at least) call fails until the link
is brought up via the flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3763)
> fix: don't treat ethtool errors as fatal

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/system/services/kubelet.go
- pkg/logging/zap.go
This PR enables debug logging of controller-runtime to the server
console if the machine configuration .debug field is set to true (log
verbosity can be also changed on the fly).
For control plane nodes, don't send kubelet logs to the console (as they
tend to flood the console with messages), this leaves reasonable amount
of logging for early boot troubleshooting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3767)
> feat: update controller-runtime logs to console level on config.debug

- internal/app/maintenance/main.go
- pkg/resources/network/hostname_status.go
This got "broken" as part of the change to the new networking
implementation, so that maintenance service is launched before the
network is ready.
Fetch DNS names and IPs for the certificate from the resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3768)
> fix: wait for the network to be ready in mainteancne mode

- go.mod
- go.sum
See https://github.com/talos-systems/go-retry/pull/9
This fixes dropping into maintenance mode on Equinix Metal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3770)
> fix: update retry package with a fix for errors.Is

- internal/app/machined/pkg/controllers/v1alpha1/service.go
- pkg/resources/v1alpha1/service.go
Otherwise if the service status is unknown it is shown as Unhealthy
which is actually different from what we have for:
`talosctl services` API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3762)
> fix: separate healthy and unknown flags in the service resource

- internal/app/machined/pkg/controllers/network/link_config.go
- internal/app/machined/pkg/controllers/network/link_config_test.go
- internal/app/machined/pkg/controllers/network/link_merge.go
- internal/app/machined/pkg/controllers/network/link_spec.go
- internal/app/machined/pkg/controllers/network/link_spec_test.go
- internal/app/machined/pkg/controllers/network/operator_config.go
- internal/app/machined/pkg/controllers/network/resolver_merge.go
- internal/app/machined/pkg/controllers/network/resolver_spec.go
- internal/app/machined/pkg/controllers/network/route_spec.go
- internal/app/machined/pkg/controllers/network/timeserver_merge.go
- pkg/machinery/nethelpers/routeflag_string_linux.go
- pkg/machinery/nethelpers/routeflags_linux.go
- pkg/resources/network/link_spec.go
This PR contains multiple fixes to the networking controllers and
logging improvements for easier debugging:
* `LinkConfigController` now correctly merges duplicate link definitions
in the machine configuration
* `LinkConfigController` correctly enslaves bond interfaces even if
they're not mentioned explicitly in the config
* bond slaves are no longer brought down forcefully, but they're brought
down before being enslaved (and brought up once they're enslaved)
* route sync code ignores flags which are not managed by Talos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3771)
> fix: update networking stack after Equinix Metal testing

- .drone.jsonnet
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/mount/mount.go
- internal/pkg/mount/options.go
- internal/pkg/mount/system.go
Initialize state should be only reading the config.
So now if it detects that the partition is not even formatted it will
skip it and will consider the state to be empty.
Fixes: https://github.com/talos-systems/talos/issues/3759
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3769)
> fix: do not format state partition in the initialize sequence

- pkg/machinery/config/contract.go
- pkg/machinery/config/contract_test.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/generate_test.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/join.go
This makes sure that if config is generated for older version of Talos,
RBAC feature is not enabled by default.
We do this to ensure that there's no surprise if Talos 0.10 is upgraded
to 0.11 and RBAC is enabled while the user is not ready for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3772)
> fix: don't enable RBAC feature in the config for Talos < 0.11

- internal/pkg/etcd/etcd.go
When etcd calls start failing, these log messages start spamming the
console a lot. Disable the client log until we figure out a better
destination for them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3774)
> fix: stop etcd client logs from going to the server console

- pkg/cluster/check/default.go
We're no longer testing against Talos <= 0.8, so no reason to
run this check (even if it's no-op).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3775)
> chore: remove bootkube check from cluster health check

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
- internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
- internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- internal/app/machined/pkg/controllers/k8s/nodename.go
- internal/app/machined/pkg/controllers/k8s/nodename_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- internal/app/machined/pkg/system/services/kubelet.go
- pkg/kubernetes/kubelet/kubelet.go
- pkg/resources/k8s/condition.go
- pkg/resources/k8s/condition_test.go
- pkg/resources/k8s/k8s_test.go
- pkg/resources/k8s/nodename.go
This changes the way Kubernetes nodename is computed: it is set by the
controller based on the hostname and machine configuration, and pulled
from the resource when needed.
Kubelet client now also uses nodename to fix the certifcate mismatch
issue on AWS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3776)
> feat: provide Kubernetes nodename as a COSI resource

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Fix of fixes #3765
disable kube-scheduler insecure port too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3785)
> feat: improve security of Kubernetes control plane components

- internal/app/machined/pkg/controllers/k8s/templates.go
This makes sure control plane components are evicted last in case of
resource shortage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3800)
> fix: mark kube-proxy as system critical priority

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
- website/content/docs/v0.11/Reference/configuration.md
This also pulls in HP ILO driver, dmesg restrict mode by default and
dm-crypt options.
See talos-systems/pkgs#289, talos-systems/pkgs#290,
talos-systems/pkgs#287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3801)
> feat: update Linux kernel to 5.10.45

- internal/app/machined/pkg/controllers/network/operator/dhcp4.go
This isn't strictly require, but it should be backwards compatible with
Talos 0.10 (networkd).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3808)
> fix: assign source address to the DHCP default gateway routes

- Makefile
Brings in the latest version of `pkgs` with a kernel that has MACVTAP
support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3815)
> feat: enable MACVTAP support

- internal/integration/base/cli.go
- internal/integration/base/run.go
- internal/integration/cli/config.go
- internal/integration/cli/copy.go
- internal/integration/cli/etcd.go
- internal/integration/cli/gen.go
- internal/integration/cli/kubeconfig.go
- internal/integration/cli/validate.go
Use testing.T.TempDir.
Add support for `talosctl --endpoints`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3810)
> chore: refactor CLI tests

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
- website/content/docs/v0.11/Reference/cli.md
This is useful for time sync testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3819)
> chore: add an option to launch cluster with bad RTC state

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
- internal/app/machined/pkg/controllers/secrets/etcd.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/pkg/etcd/certs.go
- internal/pkg/etcd/etcd.go
- pkg/machinery/constants/constants.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- pkg/resources/secrets/etcd.go
Fixes #3092
Fixes #3091
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3777)
> Separate etcd certificates

- .drone.jsonnet
- hack/cloud-image-uploader/main.go
This PR updates our CI so that when we release talos, a json file
containing our cloud images for AWS will be published as a release
asset.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3820)
> feat: add cloud images to releases

- Makefile
No actual changes, just tag updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3829)
> chore: use tagged versions of bldr dependencies for 0.11

- pkg/machinery/client/client.go
This change is for Theila which is going to use gRPC proxy to forward
requests from TS frontend right to the node's apid.
`gRPC` proxy operates on top of `grpc.ClientConn` objects, so getting
this connection from the clients which are already being created is the
easiest path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3834)
> feat: add a method to get gRPC connection from the client

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
> fix: ignore EINVAL on `unmount` operations

- go.mod
- go.sum
- internal/app/machined/pkg/system/services/apid.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
This makes sure that apid can't access any resources than the one it
actually needs. This improves the security in case of a container
breach.
> fix: limit apid access to COSI runtime resources

- hack/test/e2e-capi.sh
This PR makes sure we pin to a known CAPI version because with the new
v0.4.x released, we'll fail until we support the v1alpha4 APIs.
> chore: add CAPI version to CI setup

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/network/address_merge.go
- internal/app/machined/pkg/controllers/network/address_merge_test.go
- internal/app/machined/pkg/controllers/network/hostname_merge.go
- internal/app/machined/pkg/controllers/network/link_merge.go
- internal/app/machined/pkg/controllers/network/link_merge_test.go
- internal/app/machined/pkg/controllers/network/resolver_merge.go
- internal/app/machined/pkg/controllers/network/route_merge.go
- internal/app/machined/pkg/controllers/network/route_merge_test.go
- internal/app/machined/pkg/controllers/network/timeserver_merge.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
The sequence of events to reproduce the problem:
* some resource was merged as final representation with ID `x`
* underlying source resource gets destroyed
* merge controller marks final resource `x` for teardown and waits
for the finalizers to be empty
* another source resource appears which gets merged to same final `x`
* as `x` is in the teardown phase, spec controller will ignore it
* merge controller doesn't see the problem as well, as `x` spec is
correct, but the phase is wrong (which merge controller ignores)
This pulls in COSI fix to return an error if a resource in teardown
phase is modified. This way merge controller knows that the resource `x`
is in the teardown phase, so it should be first fully torn down, and
then new representation should be re-created as new resource with …
> fix: handle cases when merged resource re-appears before being destroyed

- internal/app/machined/pkg/controllers/network/link_spec_test.go
- pkg/resources/network/link.go
Basically all delay options are interlocked with `miimon`: if `miimon`
is zero, all delays are set to zero, and kernel complains even if zero
delay attribute is sent while miimon is zero.
> fix: don't set bond delay options if miimon is not enabled

- internal/app/machined/pkg/controllers/secrets/api.go
- pkg/grpc/gen/remote.go
This fixes endless block on RemoteGenerator.Close method rewriting the
RemoteGenerator using the retry package.
> fix: issue worker apid certs properly on renewal

- cmd/talosctl/cmd/talos/dashboard/components/topline.go
This is a small nit, Talos version already contains sha when it is
needed.
> fix: don't print git sha of the release twice in the dashboard

- hack/containerd.toml
- internal/pkg/containers/cri/containerd/config.go
- internal/pkg/containers/cri/containerd/config_test.go
Fixes #3816
* Rename key cri -> io.containerd.grpc.v1.cri
* Disable plugins aufs,zfs,devmapper,btrfs (less warning messages on
boot time)
> chore: Update containerd config version 2

- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go
It was broken, because `?uuid=` URL parses to `{"uuid": []string{""}}`.
> fix: fill uuid argument correctly in the config download URL

- internal/app/machined/pkg/controllers/secrets/kubernetes.go
- internal/pkg/kubeconfig/generate.go
* kube-apiserver keyusage serverAuth
* kube-scheduler keyusage clientAuth
* kube-controller-manager keyusage clientAuth
* kubeconfig keyusage clientAuth
> fix: controlplane keyusage

- internal/app/machined/pkg/controllers/secrets/kubernetes.go
- pkg/kubernetes/kubernetes.go
- pkg/machinery/constants/constants.go
This should fix an error like:
```
failed to create etcd client: error getting kubernetes endpoints: Unauthorized
```
The problem is that the generated cert was used immediately, so even
slight time sync issue across nodes might render the cert not (yet)
usable. Cert is generated on one node, but might be used on any other
node (as it goes via the LB).
> fix: workaround 'Unauthorized' errors when accessing Kubernetes API

- internal/pkg/etcd/etcd.go
When forfeiting etcd leadership, it might be that the node still reports
leadership status while not being a leader once the actual API call is
used. We should ignore such an error as the node is not a leader.
> fix: ignore 'not a leader' error on forfeit leadership

- internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
- internal/app/machined/pkg/controllers/k8s/endpoint.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/etcd/etcd.go
- pkg/cluster/cluster.go
- pkg/cluster/kubelet.go
- pkg/cluster/kubernetes.go
- pkg/kubernetes/kubernetes.go
The problem is that there's no official way to close Kuberentes client
underlying TCP/HTTP connections. So each time Talos initializes
connection to the control plane endpoint, new client is built, but this
client is never closed, so the connection stays active on the load
balancers, on the API server level, etc. It also eats some resources out
of Talos itself.
We add a way to close underlying connections by using helper from the
Kubernetes client libraries to force close all TCP connections which
should shut down all HTTP/2 connections as well.
Alternative approach might be to cache a client for some time, but many
of the clients are created with temporary PKI, so even cached client
still needs to be closed once it gets stale, and it's not clear how to
recreate a client in case existing …
> fix: close Kubernetes API client

- .drone.jsonnet
Drone shouldn't build releases for `pkg/machinery/vX.Y.Z` tags.
> chore: ignore future pkg/machinery/vX.Y.Z tags

- cmd/talosctl/cmd/talos/diskusage.go
- cmd/talosctl/cmd/talos/dmesg.go
- cmd/talosctl/cmd/talos/get.go
- cmd/talosctl/cmd/talos/health.go
- cmd/talosctl/cmd/talos/inspect.go
- cmd/talosctl/cmd/talos/list.go
- cmd/talosctl/cmd/talos/logs.go
- cmd/talosctl/pkg/talos/helpers/resources.go
- internal/integration/api/diskusage.go
- internal/integration/api/etcd.go
- pkg/cluster/bootstrap.go
- pkg/machinery/client/client.go
- pkg/machinery/client/events.go
- pkg/machinery/client/status.go
- pkg/machinery/client/status_test.go
The problem was that gRPC method `status.Code(err)` doesn't unwrap
errors, while Talos client returns errors wrapped with
`multierror.Error` and `fmt.Errrorf`, so `status.Code` doesn't return
error code correctly.
Fix that by introducing our own client method which correctly goes over
the chain of wrapped errors.
> fix: ignore DeadlineExceeded error correctly on bootstrap

- cmd/talosctl/cmd/talos/dashboard/source.go
- go.mod
- internal/app/machined/internal/server/v1alpha1/v1alpha1_inspect.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_monitoring.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_time.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_time_test.go
- internal/app/machined/pkg/runtime/events.go
- internal/app/networkd/pkg/server/server.go
- internal/app/networkd/pkg/server/server_test.go
- internal/app/storaged/server.go
- internal/integration/api/etcd.go
- pkg/machinery/client/client.go
- pkg/machinery/client/inspect.go
This simply uses new protobuf package instead of old one.
Old protobuf package is still in use by Talos dependencies.
> chore: update references to old protobuf package

- Makefile
This allows us to use tags for Go submodules `pkg/machinery/v0.11.0` and
still keeps Talos tag follow semantic version `v0.11.0`.
> chore: ignore tags which don't look like semantic version

- Makefile
This allows us to use tags for Go submodules `pkg/machinery/v0.11.0` and
still keeps Talos tag follow semantic version `v0.11.0`.
> backport: chore: ignore tags which don't look like semantic version

- internal/app/machined/pkg/system/services/etcd.go
We run etcd health check every 30s, and create/destroy client every 30s.
This puts a lot of pressure on etcd itself and machined.
There's protobuf overhead, TLS connection overhead, etc.
As we don't support changing etcd PKI (yet), client created once is good
enough for the lifetime of the node.
> fix: cache etcd client used for healthchecks

- internal/app/machined/pkg/controllers/network/address_config.go
- internal/app/machined/pkg/controllers/network/address_config_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Fixes #3847
Fixes #3919
1. Looks like `::1/128` is assigned to `lo` interface by the kernel
without our help, and kernel does it properly whether IPv6 is enabled
for not (including particular interface).
2. If IPv6 is disabled completely with command line, we should ignore
failures to write ipv6 sysctls (as these are not security-related,
skipping them isn't a risk).
> fix: workaround issues when IPv6 is fully or partially disabled

- internal/app/machined/pkg/controllers/network/route_spec_test.go
- pkg/resources/network/route_spec.go
Route scope doesn't depend on destination IP type being link-local, e.g.
in Azure route to link local address is create with gateway, and that
should be global (universe) scope route.
> fix: correctly pick route scope for link-local destination

- pkg/cluster/kubernetes/self_hosted.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/cluster/kubernetes/upgrade.go
This is going to be useful in the third party code which is using
upgrade modules, to collect output logs instead of printing them to the
stdout.
> chore: add ability to redirect talos upgrade module logs to io.Writer

- pkg/cluster/kubernetes/upgrade.go
No need to print them to stdout in that case.
> fix: write upgrade logs only to the LogOutput if it's defined

- cmd/talosctl/cmd/talos/upgrade-k8s.go
- pkg/cluster/kubernetes/detect.go
Scan all pods in `kube-system` and find `kube-proxy`, `kube-scheduler`,
`kube-controller-manager` and `kube-apiserver` ones, then check the
lowest version amogst them.
> feat: detect the lowest Kubernetes version in upgrade-k8s CLI command

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Set the /etc/os-release HOME_URL parameter.
It was using a non-functional url as described in https://github.com/talos-systems/talos/issues/3968
> fix: set the /etc/os-release HOME_URL parameter

- pkg/cluster/kubernetes/detect.go
We do not know the upgrade version when checking components' versions in
Theila.
> fix: do not require ToVersion to be set when detecting version

- Makefile
- pkg/machinery/constants/constants.go
This PR pulls in new pkgs to ensure we're patched against CVE-2021-33909
> fix: bump pkgs for new kernel 5.10.52

- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/trustd.go
Services apid, trusted and etcd run as root.
They do not need such capabilities.
> fix: drop linux capabilities

- internal/app/machined/pkg/system/runner/containerd/containerd.go
- internal/app/machined/pkg/system/runner/process/process.go
- internal/app/machined/pkg/system/runner/runner.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/containerd.go
- internal/app/machined/pkg/system/services/cri.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/trustd.go
#3846 #1849
This PR change oom-score:
* containerd to -999
* apid, trustd to -998
* cri to -100
* etcd to -998
Result:
```bash
4804	1334		1000	bash
4816	1333		1000	bash
4817	1333		1000	sort
4745	1332		1000	sleep
1814	666		0	udevd
2220	628		-100	containerd
2373	604		-99	containerd-shim
2442	604		-99	containerd-shim
2572	604		-99	containerd-shim
2601	604		-99	containerd-shim
2602	604		-99	containerd-shim
3102	604		-99	containerd-shim
3128	604		-99	containerd-shim
4213	604		-99	containerd-shim
4262	604		-99	containerd-shim
4530	604		-99	containerd-shim
4619	603		-99	containerd-shim
4621	603		-99	containerd-shim
2787	167		-997	kube-apiserver
3068	38		-997	kube-controller
2464	35		-999	kubelet
3419	33		-997	cilium-agent
3231	22		-997	cilium-operator
3030	19		-997	kube-scheduler
2287	18		-998 …
```
> feat: set oom score for main processes

- internal/app/machined/pkg/controllers/network/link_merge_test.go
- internal/app/machined/pkg/controllers/network/link_spec.go
- pkg/resources/network/link.go
- pkg/resources/network/link_spec.go
- pkg/resources/network/link_test.go
* correctly merge wireguard specs across multiple configuration layers
(partially stolen from #3577)
* fix erroneous wireguard reconfig when listen port in the config is
zero
* add tests for link merging (once again, partially stolen from #3577)
* fix ugly bug with LinkSpec Type merging (I believe it's a major source
of pain for you, Seán, in your PR).
> fix: resolve several issues with Wireguard link specs

- cmd/installer/pkg/install/manifest.go
- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Also print discovered blockdevice properties before partitioning the
device.
See https://github.com/talos-systems/go-blockdevice/pull/40
> fix: align partitions with minimal I/O size

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/talos-systems/go-blockdevice/pull/41
> fix: preserve PMBR bootable flag correctly

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
This allows to disable these plugins via `extraArgs` and shortens
argument list for the `kube-apiserver`.
There are no functional changes, as these plugins are enabled by default
anyways.
Based on #3971
> fix: remove admission plugins enabled by default from the list

- cmd/installer/pkg/install/manifest.go
- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Also print discovered blockdevice properties before partitioning the
device.
See https://github.com/talos-systems/go-blockdevice/pull/40
See https://github.com/talos-systems/go-blockdevice/pull/41
(cherry picked from commit 69ead37353b7e3aa7f089c70073037a6eba37767)
(cherry picked from commit dee63051702d49f495bfb28b4be74ed8b39143ad)
> fix: preserve PMBR bootable, align partitions with minimal I/O size

- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- internal/app/machined/pkg/controllers/k8s/manifest.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- internal/app/machined/pkg/controllers/k8s/templates.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_apiserverconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/resources/config/k8s_control_plane.go
- website/content/docs/v0.12/Reference/configuration.md
This feature comes as PSP is deprecated and going to be removed in 1.25.
In preparation for that, add an option to disable PSP which was always
enabled in Talos by default.
To keep backwards compatibility, PSP is still enabled by default.
See also #3971
Co-authored-by: Adam Szucs-Matyas <szucsitg@gmail.com>
> feat: add an option to disable PSP

- .drone.jsonnet
- hack/release.sh
GitHub recently introduced limit of 25000 byte for the release notes,
which breaks our release process, as our notes are over the limit.
PR https://github.com/talos-systems/talos/pull/4021 introduced support
for GFM release notes, which are at least 50% smaller.
This PR enables GFM, adds a check for release notes size and pushes
release-notes step to every build so that we known in advance if release
notes are over the limit (vs. the moment we push the release).
> chore: workaround GitHub new release notes limit

- cmd/installer/cmd/image.go
Preset `-0` for xz means fast compression but low compression level.
Changing this to `-6` (default) means that result is 10% smaller (tested
with RPi4 image).
Enable parallel compression with number of threads equal to number of
CPUs to make it compress even faster then with `-0`:
* `-0`: 15s
* `-6`: 60s
* `-6 -T 0`: 10s (on my machine, depends on number of cores)
> chore: use parallel xz with higher compression level

- go.mod
- go.sum
Brings in the latest version of go-blockdevice to fix and issues with
the PMBR.
> fix: update go-blockdevice

- Makefile
This pulls in a change to bump number of max CPUs in the kernel to 512
and update ca-certificates.
> chore: update PKGS version (512 cpus, new ca-certficates)

- Dockerfile
- cmd/installer/cmd/image.go
- cmd/installer/pkg/raw.go
Sparse file generation replaced with Go native calls.
Final artifact `.tar` reproducible with new tar flags and using GNU tar
instead of busybox one, but as the image itself is not reproducible,
this only helps a bit.
> chore: improve artifacts generation reproducibility

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
We are running etcd 3.4, so it's time to implement the TODO item.
> chore: use etcd client TryLock function on upgrade

- hack/docgen/main.go
- pkg/machinery/config/encoder/markdown.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.12/Reference/configuration.md
Also fix the const for `docgen:nodoc` for skipping the whole structure.
> fix: correctly handle nodoc for struct fields

- internal/app/machined/pkg/controllers/network/address_config.go
- internal/app/machined/pkg/controllers/network/address_merge.go
- internal/app/machined/pkg/controllers/network/operator_spec.go
- internal/app/machined/pkg/controllers/network/route_config.go
- internal/app/machined/pkg/controllers/network/route_config_test.go
- internal/app/machined/pkg/controllers/network/route_merge.go
- internal/app/machined/pkg/controllers/network/route_merge_test.go
- internal/app/machined/pkg/controllers/network/route_status.go
- internal/app/machined/pkg/controllers/network/route_status_test.go
- pkg/resources/network/network.go
New primary key is the following:
* table (if `main`, leave it empty)
* family
* gateway
* destination
* metric (priority)
There might be more ways we can improve this (probably gateway should be
removed?), but this should be much better model to represent routes in
the system.
This was discovered in KubeSpan development (@Ulexus).
> fix: make route resources ID match closer routing table primary key

- Dockerfile
- cmd/installer/cmd/image.go
- cmd/installer/pkg/raw.go
GCP does not consider generated .tar file to be valid.
This reverts commit b2507b41d250b989b9c13ad23e16202cd53a18d2.
Refs #4023.
> chore: revert "improve artifacts generation reproducibility"

- hack/release.toml
- internal/app/machined/pkg/controllers/runtime/common_test.go
- internal/app/machined/pkg/controllers/runtime/kernel_param_config.go
- internal/app/machined/pkg/controllers/runtime/kernel_param_config_test.go
- internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
- internal/app/machined/pkg/controllers/runtime/kernel_param_defaults_test.go
- internal/app/machined/pkg/controllers/runtime/kernel_param_spec.go
- internal/app/machined/pkg/controllers/runtime/kernel_param_spec_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- pkg/kernel/kernel.go
- pkg/kernel/kspp/kspp.go
- pkg/resources/runtime/condition.go
- pkg/resources/runtime/condition_test.go
- pkg/resources/runtime/kernel_params_spec.go
- pkg/resources/runtime/kernel_params_status.go
- pkg/resources/runtime/kernel_params_test.go
Fixed: https://github.com/talos-systems/talos/issues/3686
Replaced sequencer tasks for KSPP and Kubernetes required sysctl props
by the ones set by controllers.
Sysctl flow includes of 3 controllers and 2 resources:
- `KernelParamsConfigController` - handles user sysctls coming from v1alpha1
config.
- `KernelParamsDefaultsController` - handles our built-in KSPP and K8s
required sysctls.
- `KernelParamsSpecController` - consumes `KernelParamsSpec`s created by the
previous two controllers, applies them and updates the corresponding
`KernelParamsStatus`.
> feat: implement sysctl controllers
