- internal/pkg/cluster/check/kubernetes.go
Include kube-apiserver in the list of daemon sets to be checked, and
for each daemon set verify number of pods running and ready, as when
control plane is damaged daemon set properties are not updated properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2283)
> fix: update the control plane cluster health check

- hack/test/e2e.sh
It expects kubeconfig as required argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2290)
> test: fix sonobuoy delete

- docs/website/content/v0.6/en/guides/local/firecracker.md
See https://github.com/firecracker-microvm/firecracker-go-sdk/issues/174#issuecomment-655798205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2292)
> docs: update firecracker for new home of tc-redirect-tap plugin

- internal/integration/api/reset.go
Previously we assumed that node 0 is the init node, and it can't be
reset. With new bootstrap API approach, there's no init node, and all
the nodes can be reset. This corrects the check to skip only the init
node, and with bootstrap API there's no init node (so no nodes are
skipped).
Fixes #2277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2287)
> test: update init node check in reset API tests

- pkg/follow/follow_test.go
These tests rely a lot on `inotify` and interaction with the kernel. We
try to make them less dependent on wall time and performance by using
size hints and timeouts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2299)
> test: update tests for `pkg/follow` to be less time-dependent

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2304)
> chore: update meeting links

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2305)
> release(v0.6.0-alpha.5): prepare release

- cmd/installer/pkg/install/manifest.go
- docs/website/content/v0.6/en/configuration/v1alpha1.md
- pkg/blockdevice/table/gpt/gpt.go
- pkg/config/types/v1alpha1/v1alpha1_types.go
- pkg/config/types/v1alpha1/v1alpha1_validation.go
Fixes #2214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2331)
> feat: make partitions on additional disk without size occupy full disk

- pkg/config/types/v1alpha1/v1alpha1_validation.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2346)
> fix: log interface on validation error

- pkg/constants/constants.go
This reverts some temporary changes we made to get around some CI
issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2358)
> chore: set default CIDRs

- CHANGELOG.md
This is the official v0.6.0-alpha.6 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2359)
> release(v0.6.0-alpha.6): prepare release

- CHANGELOG.md
This is the official v0.5.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2338)
> release(v0.5.1): prepare release

- Makefile
- internal/integration/provision/upgrade.go
This bumps next version to the latest 0.6 alpha.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2339)
> test: upgrade versions the upgrade tests are operating on

- .drone.jsonnet
- Makefile
- hack/release.sh
This ensures that releases have notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2369)
> chore: add release notes

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/dhcpd_launch_linux.go
- cmd/talosctl/cmd/mgmt/qemu_launch_linux.go
- docs/talosctl/talosctl_cluster_create.md
- hack/test/e2e-qemu.sh
- internal/pkg/cniutils/cniutils.go
- internal/pkg/provision/providers/factory.go
- internal/pkg/provision/providers/firecracker/launch.go
- internal/pkg/provision/providers/firecracker/node.go
- internal/pkg/provision/providers/qemu/create.go
- internal/pkg/provision/providers/qemu/destroy.go
- internal/pkg/provision/providers/qemu/launch.go
- internal/pkg/provision/providers/qemu/node.go
- internal/pkg/provision/providers/qemu/qemu.go
- internal/pkg/provision/providers/qemu_linux.go
- internal/pkg/provision/providers/qemu_other.go
- internal/pkg/provision/providers/vm/dhcpd.go
- internal/pkg/provision/providers/vm/disk.go
- internal/pkg/provision/providers/vm/ipam.go
- internal/pkg/provision/providers/vm/launch.go
- internal/pkg/provision/providers/vm/loadbalancer.go
- internal/pkg/provision/providers/vm/node.go
- internal/pkg/provision/providers/vm/process.go
- internal/pkg/provision/request.go
Starts and stops qemu VMs, has some initial configuration subset.
Sets up networking through CNI tools, sets up DHCP server which gives IP
addresses to nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2334)
> feat: qemu provisioner

- .drone.jsonnet
This should help with I/O contention during the build as our disks are
not that performant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2377)
> chore: mount `/tmp` in CI to the build steps

- docs/website/content/v0.6/en/guides/cloud/aws.md
Update download example to reference latest release
Signed-off-by: Steve Francis <steverfancis@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2396)
> fix: update AMI link to latest

- Dockerfile
- Makefile
- pkg/constants/constants.go
This bring in:
- Go v1.14.7
- Linux v5.7.14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2407)
> chore: update packages

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
This adds special handling for files that are static pods. This is a
workaround for v0.6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2408)
> fix: allow static pod files

- docs/website/package-lock.json
- docs/website/package.json
See https://github.com/advisories/GHSA-wvhm-4hhf-97x9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2413)
> chore: update node dependencies

- CHANGELOG.md
This is the official v0.6.0-beta.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2412)
> release(v0.6.0-beta.1): prepare release

- internal/app/machined/pkg/system/services/etcd.go
This check is exactly same as as `etcdctl endpoint-health`.
Fixes #2399
During upgrade actions we should make sure `etcd` on other control plane
nodes are healthy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2421)
> fix: run health check for etcd service with Get API

- docs/website/content/v0.6/en/guides/getting-started/talosctl.md
Fixes a bad link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2426)
> docs: fix download link

- .conform.yaml
- CHANGELOG.md
This is the official v0.7.0-alpha.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2433)
> release(v0.7.0-alpha.0): prepare release

- Dockerfile
- pkg/machinery/constants/constants.go
This brings in the latest version of v5.7 Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2436)
> feat: upgrade Linux to v5.7.15

- docs/website/package-lock.json
This fixes all the deps which have the fix ready, but two deps don't
have updated version yet.
See https://www.npmjs.com/advisories/1548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2430)
> chore: update node.js dependencies

- CHANGELOG.md
This is the official v0.6.0-beta.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2447)
> release(v0.6.0-beta.2): prepare release

- Makefile
- internal/integration/provision/upgrade.go
This updates the "next" version in our integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2448)
> chore: bump next version to v0.6.0-beta.2

- docs/website/content/v0.6.en.json
- docs/website/content/v0.6/en/guides/local/qemu.md
Mostly copy-paste from Firecracker docs with small fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2450)
> docs: add QEMU provisioner documentation

- internal/integration/api/reboot.go
- internal/integration/base/api.go
Signed-off-by: Marco De Luca <marcodl404@gmail.com>
Changed the RebootSuite to use /proc/sys/kernel/random/boot_id rather than /proc/uptime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2451)
> test: determine reboots using boot id

- Dockerfile
- pkg/machinery/constants/constants.go
This PR pulls in the new stable linux version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2455)
> feat: update linux to 5.8.5

- CHANGELOG.md
This is the official v0.6.0-beta.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2457)
> release(v0.6.0-beta.3): prepare release

- .drone.jsonnet
- cmd/talosctl/cmd/mgmt/cluster/create.go
- docs/talosctl/talosctl_cluster_create.md
- hack/test/e2e-qemu.sh
- pkg/provision/options.go
- pkg/provision/providers/qemu/arch.go
- pkg/provision/providers/qemu/create.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/qemu/pflash.go
- pkg/provision/providers/vm/state.go
This also adds integration pipeline tests for UEFI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2454)
> feat: provide option to run Talos under UEFI in QEMU

- pkg/machinery/constants/constants.go
See https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2459)
> feat: upgrade etcd to 3.4.12

- Dockerfile
- Makefile
See also:
* https://github.com/talos-systems/pkgs/pull/158
* https://github.com/talos-systems/tools/pull/102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2466)
> chore: upgrade Go to 1.14.8

- CHANGELOG.md
This is the official v0.7.0-alpha.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2473)
> release(v0.7.0-alpha.1): prepare release

- docs/website/content/v0.6.en.json
- docs/website/content/v0.6/en/guides/upgrading/index.md
This adds docs on how to upgrade Kubernetes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2465)
> docs: add Kubernetes upgrade guide

- CHANGELOG.md
This is the official v0.6.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2474)
> release(v0.6.0): prepare release

- Dockerfile
- Makefile
See:
* https://github.com/talos-systems/pkgs/pull/161
* https://github.com/talos-systems/tools/pull/104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2487)
> chore: upgrade Go to 1.15.1

- Dockerfile
- go.mod
- go.sum
- pkg/machinery/constants/constants.go
This brings in the latest stable containerd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2490)
> feat: upgrade containerd to v1.4.0

- docs/website/content/v0.6/en/guides/getting-started/intro.md
- docs/website/content/v0.6/en/guides/upgrading/index.md
This PR fixes a few small links that were still pointing to 0.5
resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2494)
> docs: update 0.6 links

- .drone.jsonnet
I can't reproduce the failures with Cilium anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2511)
> test: re-enable Cilium e2e upgrade test

- cmd/installer/pkg/ova/ova.go
- cmd/talosctl/cmd/talos/upgrade-k8s.go
- docs/talosctl/talosctl.md
- docs/talosctl/talosctl_upgrade-k8s.md
- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/cluster/kubernetes/kubernetes.go
- pkg/cluster/kubernetes/upgrade.go
- pkg/constants/constants.go
Fixes #2485 
Fixes #2506 
Fixes #2512
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2514)
> Cherry picks

- CHANGELOG.md
This is the official v0.6.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2517)
> release(v0.6.1): prepare release

- pkg/machinery/constants/constants.go
We don't need them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2524)
> refactor: garbage collect unused constants

- docs/website/content/v0.6/en/guides/upgrading/index.md
- pkg/cluster/kubernetes/upgrade.go
This offers automated upgrades for Kubernetes control plane.
Fixes #2520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2526)
> docs: update upgrade guide with `talosctl upgrade-k8s`

- docs/website/content/v0.6/en/configuration/overview.md
Every infrastructure is different, and we can't enforce DNS endpoints
but we can recommend it.
Signed-off-by: Patatman <git@jeursen.nl>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2403)
> docs: add recommneded settings in overview

- pkg/machinery/client/client.go
Fixes #2096
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2534)
> fix: improve error message on empty config

- CHANGELOG.md
This is the official v0.6.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2540)
> release(v0.6.2): prepare release

- go.mod
- go.sum
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Validates cluster endpoint from v1alpha1 config.
Fixes #2101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2541)
> fix: validate cluster endpoint

- docs/website/package-lock.json
This updates packages to address security issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2542)
> fix: address node package update

- CHANGELOG.md
This is the official v0.7.0-alpha.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2539)
> release(v0.7.0-alpha.2): prepare release

- .drone.jsonnet
This PR makes sure we push an edge tag any time the nightly integration
tests pass. This also removes the dependency on cloud conformance to
pass in order for edge tags to be pushed.
Will close #2267 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2546)
> chore: push edge releases on successful nightly integration

- Dockerfile
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
We longer require an install image in the install config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2547)
> feat: add default install image

- Makefile
- chore: fix docker login
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2558)
>  chore: fix docker login

- .drone.jsonnet
- Makefile
Updates the drone config to setup the GHCR credentials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2559)
> chore: fix docker login

- .drone.jsonnet
Fix the docker login for edge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2560)
> chore: fix edge push

- docs/website/content/v0.7/en/guides/local/registry-cache.md
Fixed some small nits on the way, replaced firecracker with qemu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2563)
> docs: add ghcr.io to the registry cache docs

- internal/integration/provision/upgrade.go
This fixes an incorrect import path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2568)
> fix: use images package in integration tests

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Just one-liner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2569)
> fix: update the docs to fix the lint-markdown

- internal/integration/provision/upgrade.go
s/constants/images/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2570)
> fix: update one more places which had stale reference for constants

- CHANGELOG.md
This is the official v0.7.0-alpha.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2566)
> release(v0.7.0-alpha.3): prepare release

- README.md
We now only do a meeting once a week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2576)
> docs: remove second meeting from README

- docs/website/content/v0.6/en/guides/local/docker.md
This adds an extra step to the getting started guide that applies to
MacOS users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2580)
> docs: add note on settings endpoints on MacOS

- docs/website/content/v0.7.en.json
- docs/website/content/v0.7/en/guides/local/air-gapped.md
Fixes #2544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2585)
> docs: add guide on setting up air-gapped environment with `images`

- hack/test/qemu/qemu.sh
This can serve as an example of providing the config via an ISO, and
simplify local setups a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/2586)
> chore: update qemu hack script to use ISO

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- docs/website/content/v0.7/en/guides/local/air-gapped.md
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
> docs: small fixes for the config docs and air-gapped

- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
> fix: registry auth config building

- .drone.jsonnet
See https://github.com/docker/buildx/issues/327
> chore: attempt to fix image pushing for GitHub

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/validate.go
- docs/talosctl/talosctl_cluster_create.md
- docs/website/content/v0.7/en/configuration/v1alpha1.md
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/join.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_marshal.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_marshal_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Also fixes loading for CA certificate for the registry TLS auth.
> feat: support --registry-insecure-skip-verify for `cluster create`

- docs/website/content/v0.7/en/configuration/v1alpha1.md
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/kubernetes/kubernetes.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Add talosconfig parameter that allows to disable NoSchedule taint on
master nodes.
https://github.com/talos-systems/talos/issues/2573
> feat: allow disabling NoSchedule on master nodes

- CHANGELOG.md
This is the official v0.7.0-alpha.6 release.
> release(v0.7.0-alpha.6): prepare release

- internal/app/bootkube/assets.go
Just more logging and error context.
> fix: improve logging and errors for extra manifests by URL

- Makefile
> feat: bump packages version for the kernel with BBR TCP congestion algo

- Makefile
See https://github.com/talos-systems/tools/pull/110
> chore: bump Go to 1.15.3

- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/install/manifest_test.go
- internal/pkg/loopback/loopback.go
This test only works on local machine (see notes in the file).
> test: add unit-test for the installer manifest

- Makefile
- pkg/machinery/constants/constants.go
See:
* https://github.com/talos-systems/pkgs/pull/179
* https://github.com/talos-systems/pkgs/pull/178
> feat: bump packages for Linux 5.8.15 and containerd 1.4.1

- Dockerfile
This should fill out the description for the image.
> docs: link container images to our repository

- pkg/cluster/check/reporter.go
This was bugging me for quite some time, as (randomly) output was
scrolling endless repeated line when terminal width was small.
Root cause was that `\t` on output takes random amount of spaces
(columns). Fixed small issues counting correctly UTF-8 runes (important
for the spinner and if we ever do i18n), and make sure spinner itself is
included into the calculations.
> fix: correctly calculate output width in colored health reporter

- .drone.jsonnet
Hope is that will make Drone more stable.
> chore: reduce numer of steps/parallelism of Drone build

- cmd/installer/pkg/install/manifest.go
- go.mod
- go.sum
See https://github.com/talos-systems/talos/pull/2663 for details.
> feat: wipe disks faster in the installer

- hack/test/capi/cluster-aws.yaml
- hack/test/capi/cluster-gcp.yaml
- hack/test/e2e-azure.sh
- hack/test/e2e-capi.sh
- hack/test/e2e-gcp.sh
This is currently just a test.
> chore: update CI scripts

- internal/pkg/mount/mount.go
This fixes a bug introduced in #1982, the intention was to ignore
`EINVAL` on `unmount` when partition is no longer mounted, but the
change was wrong as it affected both `mount` and `unmount` code paths.
> fix: stop ignoring `EINVAL` on mount

- pkg/cluster/kubernetes/upgrade.go
This ignores temporary errors while `upgrade-k8s` is running,
as I observed that etcd leader change happened while waiting for
daemonset to be updated which aborted the upgrade process.
> fix: ignore transient errors in upgrade Kubernetes code

- website/gridsome.config.js
- website/static/robots.txt
Ensures that our site will be indexed.
> docs: add robots.txt and fix sitemap.xml

- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/constants/constants.go
This reverts commit 090039c4328c7d23982e879a69a7238ab2a1bd5b.
> fix: revert "feat: bump CoreDNS to 1.7.0"

- website/package-lock.json
- website/package.json
- website/src/components/LayoutHeader.vue
- website/src/components/NextPrevLinks.vue
- website/src/components/Sidebar.vue
- website/src/components/SidebarSection.vue
- website/src/layouts/Default.vue
- website/src/main.js
Fixes a handful of minor issues with the docs website.
> docs: address small nits

- pkg/cluster/bootstrap.go
This fixes a random failure at least in the tests. As the nodes are
booting, one node might boot earlier than others. As client is using all
control plane endpoints with load-balancing, check for apid might
succeed via one node, but next request might hit a different endpoint
which still has cached connection error, and we should retry that.
> fix: retry connection refused errors while bootstrapping a cluster

- CHANGELOG.md
This is the official v0.6.3 release.
> release(v0.6.3): prepare release

- website/static/_redirects
> docs: add redirect for /docs/latest

- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.7/Guides/configuring-pull-through-cache.md
- website/content/docs/v0.7/Reference/configuration.md
Mostly some nits, small examples, distributing docs better,
splitting examples, etc.
> docs: update config reference docs

- go.mod
- go.sum
- internal/pkg/webconfig/webconfig.go
Fixes TLS and invalide redirects.
> fix: address issues in webconfig

- .drone.jsonnet
- Dockerfile
- Makefile
- cmd/installer/cmd/iso.go
- cmd/installer/pkg/iso.go
- internal/app/machined/internal/install/install.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
This reverts commit 3515f4e0f8c11352539ed0d430e1f44f73c8229f.
> feat: add ISO support

- website/content/docs/v0.6/Cloud Platforms/aws.md
- website/content/docs/v0.7/Cloud Platforms/aws.md
Docs clarification for #2720 
Clarifies some docs for the AWS deploy guide.
To help users avoid banging their head against an obscure "feature" of AWS NLBs. 
> Clarification for the aws deployment guide for #2720

- website/content/docs/v0.7/Guides/upgrading-talos.md
- website/content/docs/v0.7/Learn More/architecture.md
- website/content/docs/v0.7/Learn More/components.md
- website/content/docs/v0.7/Learn More/faqs.md
- website/content/docs/v0.7/Learn More/philosophy.md
- website/content/docs/v0.7/Learn More/upgrades.md
Describe the Talos upgrade procedure and provide answers to common
questions about it.
Fixes issue #2626
> docs: describe talos upgrade

- website/content/docs/v0.7/Introduction/getting-started.md
Adds a description of the roles of endpoints and nodes in the talosctl
config.
Fixes #2731
> docs: add a description of endpoints and nodes

- Makefile
> fix: update packages

- Makefile
See:
* https://github.com/talos-systems/pkgs/pull/185
* https://github.com/talos-systems/tools/pull/111
* https://github.com/talos-systems/extras/pull/3
> chore: bump Go to 1.15.4

- .drone.jsonnet
- CHANGELOG.md
- cmd/talosctl/cmd/mgmt/cluster/create.go
- website/content/docs/v0.7/Reference/cli.md
This is the official v0.8.0-alpha.0 release.
> release(v0.8.0-alpha.0): prepare release

- website/content/docs/v0.6/Guides/configuring-pull-through-cache.md
- website/content/docs/v0.6/Guides/upgrading-kubernetes.md
- website/content/docs/v0.6/Guides/upgrading-talos.md
- website/content/docs/v0.7/Guides/configuring-pull-through-cache.md
- website/content/docs/v0.7/Guides/upgrading-kubernetes.md
- website/content/docs/v0.7/Guides/upgrading-talos.md
- website/content/docs/v0.7/Learn More/talosctl.md
This PR adds embedded youtube videos in places where we have done
walkthroughs of this functionality.
> docs: add live walkthroughs where applicable

- .drone.jsonnet
- CHANGELOG.md
- cmd/talosctl/cmd/mgmt/cluster/create.go
- website/content/docs/v0.7/Reference/cli.md
This is the official v0.7.0-beta.1 release.
> release(v0.7.0-beta.1): prepare release

- Makefile
Release contains important security fixes:
https://groups.google.com/g/golang-announce/c/NpBGTTmKzpM/m/fLguyiM2CAAJ
Fixes #2775
> feat: update Go to 1.15.5

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/maintenance/main.go
Plus fix the logging on docker/Talos to avoid logs in docker mode going
to the host kernel message buffer.
Fixes #2794
> fix: make fingerprint clearly optional in a boot hint

- CHANGELOG.md
- website/content/docs/v0.7/Reference/cli.md
This is the official v0.7.0 release.
> release(v0.7.0): prepare release

- internal/pkg/cri/pods.go
Fixes #2806
Also skips stopping pods which are already stopped from the previous run
with modes `POD`/`CONTAINER`.
> fix: ignore 'not found' errors when stopping/removing CRI pods

- internal/app/maintenance/main.go
Similar to what we have for config upload.
> feat: print hint about using interative installer in mainenance mode

- internal/app/networkd/pkg/address/dhcp.go
- internal/app/networkd/pkg/nic/nic.go
- pkg/provision/providers/qemu/launch.go
> feat: set interface MTU in DHCP mode even if DHCP is not successful

- .drone.jsonnet
- Dockerfile
- Makefile
- cmd/installer/cmd/image.go
- cmd/installer/cmd/root.go
- cmd/installer/pkg/install/install.go
- cmd/installer/pkg/install/manifest.go
- cmd/installer/pkg/install/manifest_test.go
- cmd/installer/pkg/raw.go
- go.mod
- go.sum
- internal/app/machined/internal/install/install.go
- internal/app/machined/pkg/runtime/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/mount/mount.go
- pkg/machinery/constants/constants.go
- pkg/provision/providers/firecracker/bootloader.go
- pkg/provision/providers/qemu/launch.go
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/gridsome.config.js
> feat: add support for installing to SBCs

- .drone.jsonnet
- Makefile
See https://github.com/talos-systems/pkgs/pull/199
Also serializes push/push-latest.
> feat: bump package for kernel with CIFS support

- internal/app/maintenance/server/server.go
- internal/app/networkd/pkg/networkd/devices.go
- internal/app/networkd/pkg/reg/reg.go
- internal/integration/api/network-interfaces.go
To be used in the interactive installer to configure networking.
> feat: implement network interfaces list API

- Makefile
This was preferred way to push images before multi-arch was introduced.
This way doesn't work with multi-platform images, so we had two paths.
Changes:
* `PUSH=true` works now always for `make installer`, `make talos`
* for `image-aws` and friends make sure to push the installer image
before doing that (either local registry or different username)
* `talosctl cluster create` for docker - make sure image is pushed and
`talosctl` knows about the image reference.
> chore: drop support for `docker load`

- Dockerfile
- Makefile
- cmd/installer/pkg/install/install.go
- internal/app/machined/pkg/runtime/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go
- pkg/copy/copy.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
This adds support for the Raspberry Pi 4 Model B.
> feat: add support for the Raspberry Pi 4 Model B

- cmd/talosctl/cmd/talos/config.go
Validate that context exists before using it.
Fixes #2851
> fix: prevent crash in `talosctl config` commands

- CHANGELOG.md
- website/content/docs/v0.7/Reference/cli.md
This is the official v0.7.1 release.
> release(v0.7.1): prepare release

- .drone.jsonnet
- Makefile
- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
This will build SBC images and output them to the artifacts directory. These images
will be published on releases.
> chore: build SBC images

- website/content/docs/v0.7/Cloud Platforms/gcp.md
- website/content/docs/v0.8/Cloud Platforms/gcp.md
- website/content/docs/v0.8/Cloud Platforms/openstack.md
This PR adds a guide on how to deploy on Openstack with our new image.
It also fixes a small typo I noticed in gcp docs.
Will close #2877 
> docs: add openstack docs

- website/content/docs/v0.8/Introduction/what-is-talos.md
> docs: fix typos

- go.mod
- go.sum
This bumps go-blockdevice library for the fix
https://github.com/talos-systems/go-blockdevice/pull/22
> fix: make reset work again

- .drone.jsonnet
This PR actually enables the integration pipeline for running thrice
daily.
> chore: enable thrice daily pipeline

- Makefile
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rock64/rock64.go
- internal/pkg/kubeconfig/admin.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.8/Single Board Computers/rock64.md
This adds support for the Rock64.
> feat: add support for the Pine64 Rock64

- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rock64.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
Improves the SBC documentation.
> docs: improve SBC documentation

- cmd/talosctl/cmd/talos/apply-config.go
Fixes: https://github.com/talos-systems/talos/issues/2910
> fix: make interactive installer work without endpoints provided

- Dockerfile
Hoping it might fix spurious buildkit failures.
> chore: bump dockerfile frontend version

- hack/test/provision-tests.sh
- internal/integration/provision/provision.go
> test: bump defaults for provision tests resources

- Makefile
See: talos-systems/tools#115,
talos-systems/pkgs#213, talos-systems/extras#7.
> chore: bump Go to 1.15.6

- cmd/installer/pkg/install/manifest.go
This makes sure Talos won't pick up any potential leftover data on fresh
install. On upgrade contents of META partitions are preserved anyways.
Fixes #2919
> fix: zero out partitions without filesystems on install

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
If Talos node is booted without `devkmsg_printk` set to `on` (which
disables ratelimiting), logs are severely ratelimited and close to
impossible to read.
If all the regular kernel args are missing (including KSPP ones), Talos
reboots but actual error message is not printed.
This fixes to at least disable ratelimiting on kmsg writes to make all
the logs visible anyways.
Fixes #2908
> fix: remove kmsg ratelimiting on startup

- website/content/docs/v0.8/Guides/configuring-certificate-authorities.md
This adds a guide on how to add a custom CA.
> docs: add guider for custom CAs

- website/content/docs/v0.8/Local Platforms/docker.md
Outlines limitations in the API in container mode.
> docs: add a note on caveats in container mode

- website/content/docs/v0.8/Bare Metal Platforms/equinix-metal.md
Adds a guide for Equinix Metal.
> docs: update Equinix Metal guide

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.0-alpha.3 release.
> release(v0.8.0-alpha.3): prepare release

- Makefile
> feat: bump pkgs for kernel with CONFIG_USB_XHCI_PLATFORM

- internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
This removes hardcoded `eth0` which might not be always part of the
bond, take the first one from packet metadata.
> fix: take the first interface from the bond (packet)

- .drone.jsonnet
- hack/test/e2e-docker.sh
- hack/test/e2e-firecracker.sh
- hack/test/e2e-iso.sh
- hack/test/e2e-qemu.sh
- hack/test/provision-tests.sh
This should help with the CNI encapsulation in the cluster.
> chore: lower MTU to 1450 for the tests in the CI

- cmd/talosctl/cmd/docs.go
- hack/protoc-gen-doc/markdown.tmpl
- website/content/docs/v0.8/Bare Metal Platforms/digital-rebar.md
- website/content/docs/v0.8/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.8/Bare Metal Platforms/matchbox.md
- website/content/docs/v0.8/Bare Metal Platforms/sidero.md
- website/content/docs/v0.8/Cloud Platforms/aws.md
- website/content/docs/v0.8/Cloud Platforms/azure.md
- website/content/docs/v0.8/Cloud Platforms/digitalocean.md
- website/content/docs/v0.8/Cloud Platforms/gcp.md
- website/content/docs/v0.8/Cloud Platforms/openstack.md
- website/content/docs/v0.8/Local Platforms/docker.md
- website/content/docs/v0.8/Local Platforms/firecracker.md
- website/content/docs/v0.8/Local Platforms/qemu.md
- website/content/docs/v0.8/Local Platforms/virtualbox.md
- website/content/docs/v0.8/Reference/api.md
- website/content/docs/v0.8/Reference/cli.md
- website/content/docs/v0.8/Reference/configuration.md
- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rock64.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
- website/content/docs/v0.8/Virtualized Platforms/proxmox.md
- website/content/docs/v0.8/Virtualized Platforms/vmware.md
- website/src/templates/MarkdownPage.vue
Also filled in some of the descriptions specific for particular pages.
Seeing that bug all the time was making me sad:
> docs: add fallback to default description if none is set on current page

- go.mod
- go.sum
See https://github.com/talos-systems/go-blockdevice/pull/24
> fix: don't overwrite PMBR

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.0-beta.0 release.
> release(v0.8.0-beta.0): prepare release

- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rock64.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
Also add `conv=fsync bs=4M` to `dd` commands.
> docs: update Talos release for SBCs

- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
> docs: fix SBC docs to point to beta.0 instead of beta.1

- website/src/data/cloud-images.json
Uploaded via `upload-images` pipeline.
https://ci.dev.talos-systems.io/talos-systems/talos/13922/1/22
> docs: provide AMIs for 0.8.0-beta.0

- pkg/cluster/check/kubernetes.go
Pods which are spun up as checkpoints shouldn't be counted towards the
normal pods spun up as part of the daemon set.
> fix: ignore pods spun up from checkpoints in health checks

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.0 release.
> release(v0.8.0): prepare release

- website/gridsome.config.js
- website/src/pages/Index.vue
> docs: set latest docs to v0.8

- website/static/_redirects
The `_redirects` file needs to be updated.
> docs: fix latest docs

- website/content/docs/v0.8/Guides/upgrading-talos.md
- website/content/docs/v0.8/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.8/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.8/Single Board Computers/rock64.md
- website/content/docs/v0.8/Single Board Computers/rpi_4.md
- website/src/data/cloud-images.json
Updating things for the final release.
> docs: update references to 0.8.0, add 0.8.0 AWS AMIs

- Makefile
- internal/integration/provision/upgrade.go
Now with official 0.8.0 release.
> chore: update upgrade test version used

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.1 release.
> release(v0.8.1): prepare release

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/integration/cli/list.go
> fix: list command unlimited recursion shouldn't be default behavior

- website/content/docs/v0.9/Learn More/components.md
- fix spelling
- increase readability
- fix grammar
- reduce verbiage
Reduce friction in knowledge transfer.
The document was hard to understand while reading.
> docs: update components.md

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
There's no system disk or meta in container mode, and `/sys/block` gets
_host_ block devices, so we better skip these probes altogether.
> fix: don't probe disks in container mode

- internal/app/networkd/pkg/address/dhcp.go
The problem was that our DHCP client was always doing
Discover-Offer-Request-Ack sequence as if it doesn't have any IP lease
which was breaking some DHCP servers leading to an error which in turn
makes Talos retry harder hitting the same error over and over again.
> fix: update DHCP client to use Request-Ack sequence after an Offer

- Dockerfile
- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
> chore: update dependencies via dependabot

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.2 release.
> release(v0.8.2): prepare release

- website/src/data/cloud-images.json
Images were uploaded via `upload-images` pipeline.
> docs: update AMI list for 0.8.2

- Makefile
- pkg/machinery/constants/constants.go
> feat: update Linux to 5.10.14

- go.mod
- go.sum
- hack/test/e2e-docker.sh
- internal/app/networkd/pkg/address/dhcp.go
- internal/integration/api/recover.go
- pkg/machinery/client/client.go
This backports PRs #2987, #3099, #3134
> backport: checkpoints for scheduler & controller manager, DHCP fixes, apply-config fixes

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.3 release.
> release(v0.8.3): prepare release

- Makefile
See talos-systems/tools#126, talos-systems/pkgs#241,
talos-systems/extras#10
> feat: bump Go to 1.15.8

- .drone.jsonnet
- Makefile
Collapse builds steps, split integration tests into multiple pipelines,
save and load build artifacts.
> chore: rework Drone pipelines

- .drone.jsonnet
This make sure release builds and branch builds after merge save
artifacts to different buckets (`$DRONE_TAG` is only set for tagged
builds).
> chore: update artifacts bucket name in Drone

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0-alpha.1 release.
> release(v0.9.0-alpha.1): prepare release

- .drone.jsonnet
> chore: add default cron pipeline to the list of pipelines

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.4 release.
> release(v0.8.4): prepare release

- internal/integration/api/apply-config.go
Verify that disk encryption sync operations work properly.
> test: enable disk encryption key rotation test

- README.md
- website/content/docs/v0.8/index.md
- website/content/docs/v0.9/index.md
We might benefit from more structured and searchable support forum.
> docs: add link to GitHub Discussions as a support forum

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0-alpha.2 release.
> release(v0.9.0-alpha.2): prepare release

- Dockerfile
- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
> chore: bump dependencies via dependabot

- .drone.jsonnet
- internal/integration/api/apply-config.go
- internal/integration/provision/upgrade.go
- pkg/cluster/check/default.go
Verify upgrade flow using the same version of the installer.
Run that with disk encryption enabled.
> test: upgrade master to master tests

- website/src/data/cloud-images.json
Keeping images in sync with Talos 0.8 releases.
> docs: update AMI images for 0.8.4

- .drone.jsonnet
- go.mod
- go.sum
- hack/test/e2e.sh
Canal CNI is known to be trying to reach out to k8s control plane on pod
teardown.
> test: add integration test with Canal CNI and reset API

- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Fixes: https://github.com/talos-systems/talos/issues/3221
Detect defined SANs and append only non-overlapping ones.
> fix: make ApplyDynamicConfig idempotent

- pkg/machinery/constants/constants.go
- website/content/docs/v0.9/Reference/configuration.md
See https://github.com/etcd-io/etcd/releases/tag/v3.4.15
> feat: update etcd to 3.4.15

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0-alpha.3 release.
> release(v0.9.0-alpha.3): prepare release

- website/content/docs/v0.9/Guides/disk-encryption.md
Fixes: https://github.com/talos-systems/talos/issues/3175
Describe usage tips, caveats, flow.
> docs: add disk encryption guide

- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/pkg/containers/image/image.go
This fixes a problem when Talos pulls `etcd` image one every reboot, as
`etcd` was running in the system containerd which is completely
ephemeral (backed by `tmpfs`).
Also skip pulling if image is already present and unpacked (same fix for
the `kubelet` image).
Fixes #3229
> fix: move etcd to `cri` containerd runner

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0-alpha.4 release.
> release(v0.9.0-alpha.4): prepare release

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0-alpha.5 release.
> release(v0.9.0-alpha.5): prepare release

- go.mod
- go.sum
See https://github.com/talos-systems/go-blockdevice/pull/31
> fix: align partition start to the physical sector size

- Makefile
No actual changes, just referencing tagged releases for 0.9.0.
> chore: update tools/pkgs/extras tags

- Makefile
- go.mod
- go.sum
- pkg/machinery/constants/constants.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/containerd/containerd/releases/tag/v1.4.4
Fixes #3254 
> feat: update containerd to version 1.4.4

- website/content/docs/v0.9/Guides/upgrading-kubernetes.md
CLI tool usage is same, but manual process is quite different.
> docs: update Kubernetes upgrade guide

- website/content/docs/v0.9/Guides/troubleshooting-control-plane.md
Describe common failures and debugging approach.
> docs: add troubleshooting control plane documentation

- website/content/docs/v0.9/Introduction/what-is-new.md
This describes high-level new features in Talos 0.9.
> docs: add highlights for 0.9 release

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0-beta.0 release.
> release(v0.9.0-beta.0): prepare release

- website/package-lock.json
This fixes some security vulnerabilities in the libraries.
> chore: update website npm dependencies

- website/content/docs/v0.9/Single Board Computers/rpi_4.md
This PR adds a quick how-to on installing talos on rpi.
> docs: add video for raspberry pi install

- website/content/docs/v0.9/Guides/vip.md
- website/content/docs/v0.9/Introduction/what-is-new.md
Add documentation for using VIP, or shared IP addresses, for the
controlplane.
Fixes #3289
> docs: add guide for VIP

- cmd/talosctl/cmd/talos/convert-k8s.go
- pkg/cluster/kubernetes/convert.go
- website/content/docs/v0.9/Guides/converting-control-plane.md
This includes Sean's comments from #3278 and introduces a new flag which
is referenced in manual conversion process document.
> fix: update output of `convert-k8s` command

- Makefile
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4/rockpi4.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.9/Single Board Computers/rockpi_4.md
That should be another nice addition to the list of supported SBCs.
Depends on: https://github.com/talos-systems/pkgs/pull/249
> feat: add Rock pi 4 support

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/networkd/main.go
- internal/app/networkd/pkg/address/address.go
- internal/app/networkd/pkg/address/dhcp4.go
- internal/app/networkd/pkg/address/dhcp6.go
- internal/app/networkd/pkg/address/static.go
- internal/app/networkd/pkg/networkd/misc.go
- internal/app/networkd/pkg/networkd/netconf.go
- internal/app/networkd/pkg/networkd/netconf_test.go
- internal/app/networkd/pkg/networkd/networkd.go
- internal/app/networkd/pkg/networkd/networkd_test.go
- internal/app/networkd/pkg/nic/nic.go
- internal/app/networkd/pkg/reg/reg.go
- internal/app/networkd/pkg/reg/reg_test.go
- internal/app/networkd/pkg/vip/vip.go
This changes will make easier running networkd as a goroutine in machined.
> refactor: provide explicit logger for networkd

- website/content/docs/v0.9/Introduction/getting-started.md
Fixes a few minor errors in the Getting Started doc.
> docs: minor fixes to getting started

- Makefile
- pkg/machinery/constants/constants.go
Update pkgs.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
> chore: update Linux to 5.10.23

- CHANGELOG.md
- website/content/docs/v0.8/Reference/cli.md
This is the official v0.8.5 release.
> release(v0.8.5): prepare release

- Dockerfile
- go.mod
- go.sum
- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
- pkg/machinery/go.mod
chore: use Go 1.16 language version
It affects some languages features and go subcommands.
https://golang.org/ref/mod#go-mod-file-go
> chore: use Go 1.16 language version

- CHANGELOG.md
- hack/release.sh
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.10.0-alpha.0 release.
> release(v0.10.0-alpha.0): prepare release

- website/content/docs/v0.9/Guides/converting-control-plane.md
- website/content/docs/v0.9/Guides/upgrading-kubernetes.md
- website/content/docs/v0.9/Guides/vip.md
- website/content/docs/v0.9/Learn More/control-plane.md
- website/content/docs/v0.9/Learn More/controllers-resources.md
- website/content/docs/v0.9/Learn More/faqs.md
Add FAQ on initial time sync.
Add 0.9 new videos.
> docs: add control plane in-depth guide

- CHANGELOG.md
- hack/release.sh
- hack/release.toml
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0-beta.1 release.
> release(v0.9.0-beta.1): prepare release

- Dockerfile
- Makefile
Creates a new container image and corresponding Makefile target.
Closes https://github.com/talos-systems/talos/issues/3324
> feat: publish talosctl container image

- hack/start-registry-proxies.sh
To avoid copying and pasting it from the documentation every time.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
> chore: add script for starting registry proxies

- internal/pkg/etcd/etcd.go
There are two APIs and `talosctl` commands:
* `etcd leave` removes the member from the cluster and removes etcd
data directory for the called node
* `etcd remove-member <node>` removes some other node from the etcd
cluster, but it doesn't affect called node state
This fixes confusing naming of the methods vs. what they're doing.
Fixes #3340
> fix: `etcd remove-member` removes etcd data directory

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.0 release.
> release(v0.9.0): prepare release

- website/src/data/cloud-images.json
Not all the regions were able to process the request, so list is a bit
shorter than usual.
> docs: add AMIs for Talos 0.9.0

- Dockerfile
- internal/app/machined/pkg/system/services/networkd.go
- internal/app/networkd/main.go
This removes machined as a separate container and image.
Reasons:
* `machined` becomes more and more bound into the core flow - now it
interacts with `etcd` for VIPs, so container has more and more
mounts/permissions
* it should be easier to COSIfy machined piece by piece if we have it
running in the same process
* initramfs size
> refactor: run networkd as a goroutine in machined

- internal/app/networkd/pkg/address/dhcp.go
Backport to 0.8.
Very easily reproduced when you start a node with a Dynamic IP.
Normally it should renew lease after TTL/2, but that doesn't happen, so
the node starts to get next IP one after another.
After looking at packets sent by other clients, found out that they
have `Client IP address` equal to the IP given by the DHCP server.
Additionally, changed DHCP client to send Request packets directly to the DHCP server after getting an offer.
It looks like DHCP spec states that you should use unicast request directly to DHCP server, not broadcast.
> fix: resolve the issue with DHCP lease not being renewed

- go.mod
- pkg/cluster/kubernetes/self_hosted.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/cluster/kubernetes/upgrade.go
- pkg/cluster/kubernetes/upgrade_test.go
Add missing cases, refactoring.
> fix: resolve the issue with Kubernetes upgrade

- .golangci.yml
- cmd/talosctl/cmd/talos/convert-k8s.go
- internal/app/networkd/pkg/server/server.go
- pkg/cluster/kubernetes/talos_managed.go
Copy from kres manually for now.
> chore: tweak nolintlint settings

- Dockerfile
- internal/integration/api/logs.go
Refs https://github.com/talos-systems/talos/issues/3378.
> chore: build integration tests with -race

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Follow-up for #3383
I added couple of first tests, we should add more as we go through this
code. Even with those tests, I found and fixed two more panics.
> test: add unit-test for machine config validation

- internal/app/machined/pkg/system/runner/containerd/containerd.go
Containerd API to pass stdin to the container is far from being perfect,
but it seems to contain a race condition we can't avoid: if `NewTask()`
fails, it starts the I/O loop in a goroutine, but never stops it. We
can't stop it as well, as `NewTask()` failed, so to workaround this
failure, copy the stdin into new reader on each access.
This copying shouldn't be a big deal for us, as it's just machine
configuration and it's tiny.
> fix: workaround race in containerd runner with stdin pipe

- internal/pkg/mount/system.go
- pkg/machinery/config/encoder/documentation.go
- pkg/machinery/config/encoder/encoder_test.go
- pkg/machinery/config/encoder/markdown.go
Cherry-pick https://github.com/talos-systems/talos/pull/3381 for 0.9.
> fix: get rid of data race in encoder and fix concurrent map access

- internal/integration/api/apply-config.go
Variable `chanErr` was read before waiting for the goroutine to finish.
> test: fix data race in apply config tests

- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.0-alpha.1 release.
> release(v0.10.0-alpha.1): prepare release

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.1 release.
> release(v0.9.1): prepare release

- Dockerfile
This moves things around a bit so that `go generate` is called after
modules are generated, as `go generate` downloads modules as well.
This fixes a race condition which might show up randomly.
Spotted by: @AlekSi
> refactor: download modules before `go generate`

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/talos-systems/go-blockdevice/pull/33
> chore: update blockdevice library for PMBR bootable fix

- Makefile
See talos-systems/tools#134 talos-systems/pkgs#260
talos-systems/extras#16
> chore: update Go to 1.16.3

- Makefile
- website/content/docs/v0.10/Cloud Platforms/digitalocean.md
- website/content/docs/v0.6/Cloud Platforms/digitalocean.md
- website/content/docs/v0.7/Cloud Platforms/digitalocean.md
- website/content/docs/v0.8/Cloud Platforms/digitalocean.md
- website/content/docs/v0.9/Cloud Platforms/digitalocean.md
> docs: fix "DigitalOcean" spelling

- website/content/docs/v0.10/Single Board Computers/rockpi_4.md
Describe that gross flow while I still remember it.
> docs: describe steps to install and boot Talos from the SSD on rockpi4

- hack/test/e2e-capi.sh
Cherry-pick https://github.com/talos-systems/talos/pull/3447 into 0.9
> test: update CAPA to 0.6.4

- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.0-alpha.2 release.
> release(v0.10.0-alpha.2): prepare release

- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt
- website/content/docs/v0.10/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.10/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.10/Single Board Computers/rock64.md
- website/content/docs/v0.10/Single Board Computers/rockpi_4.md
- website/content/docs/v0.10/Single Board Computers/rpi_4.md
> fix: document HDMI problem on RPi 4

- .gitignore
- cmd/talosctl/cmd/mgmt/cluster/create.go
- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/integration/api/generate-config.go
- internal/integration/provision/upgrade.go
- internal/pkg/tui/installer/state.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_cniconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.10/Reference/configuration.md
> feat: add support for "none" CNI type

- hack/test/e2e-aws.sh
> chore: use tagged version of cluster-api-templates

- .conform.yaml
- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.0-beta.0 release.
> release(v0.10.0-beta.0): prepare release

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.2 release.
> release(v0.9.2): prepare release

- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.0-beta.1 release.
> release(v0.10.0-beta.1): prepare release

- hack/cloud-image-uploader/aws.go
- hack/cloud-image-uploader/main.go
AWS now has opt-in regions which are not enabled by default, so we need
to ignore such regions to avoid failures.
> chore: list specifically for enabled regions

- website/content/docs/v0.10/Guides/disaster-recovery.md
Describe full procedure from backups to disaster recovery.
> docs: add etcd backup and restore guide

- website/content/docs/v0.10/Cloud Platforms/aws.md
- website/content/docs/v0.8/Cloud Platforms/aws.md
- website/content/docs/v0.9/Cloud Platforms/aws.md
This PR adds some docs changes where we had incorrect commands in the
AWS docs.
Will close #3495
> docs: update AWS instructions

- website/content/docs/v0.10/index.md
- website/content/docs/v0.9/index.md
Adds a survey link so that we can get feedback from users.
> docs: add survey

- hack/cloud-image-uploader/aws.go
- hack/cloud-image-uploader/main.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
> backports: AWS image uploads, VMWare OVF fix

- cmd/installer/pkg/ova/ova.go
- hack/cloud-image-uploader/aws.go
- hack/cloud-image-uploader/main.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
> backports: AWS images fix, OVF & VMWare fixes

- CHANGELOG.md
- website/content/docs/v0.9/Reference/cli.md
This is the official v0.9.3 release.
> release(v0.9.3): prepare release

- website/content/docs/v0.10/Introduction/what-is-new.md
Mostly based on the release notes.
> docs: add what's new for Talos 0.10

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.0 release.
> release(v0.10.0): prepare release

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/talos-systems/crypto/pull/11
> fix: bump crypto library for the CSR verification fix

- go.mod
- go.sum
> chore: remove temporary fork

- README.md
- website/content/docs/v0.10/index.md
- website/content/docs/v0.11/index.md
- website/content/docs/v0.6/index.md
- website/content/docs/v0.7/index.md
- website/content/docs/v0.8/index.md
- website/content/docs/v0.9/index.md
> docs: add survey to README

- Dockerfile
Use SOURCE_DATE_EPOCH, explicit timestamp setting, and the cpio
--reproducible flag in order to get hash-for-hash identical builds
across multiple systems.
Tested on Debian and Arch Linux systems
Signed-off-by: Lance R. Vick <lance@lrvick.net>
The generated build output of this repository is now deterministic across multiple systems.
This resolves the only hard blocker to pursue the improved supply chain integrity recommendations proposed here: https://github.com/talos-systems/rfcs/pull/2
Notably multiple independently controlled systems should be able to reproduce published binaries to prove they have not been tampered with, provided the cached toolchain is not tampered with (future work).
> feat: deterministic builds

- pkg/machinery/config/types/v1alpha1/v1alpha1_marshal_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
Fixes: https://github.com/talos-systems/talos/issues/3572
> fix: properly parse matcher expressions

- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.1 release.
> release(v0.10.1): prepare release

- internal/pkg/ntp/ntp.go
- internal/pkg/ntp/ntp_test.go
Fixes #3582
Time adjustment code was rewritten taking a peek at other time sync
implementations. Looks like `adjtimex` was used incorrectly before which
leads to huge time oscillations and `STA_UNSYNC` being set by the
kernel. Instead of setting time via `settimeofday`, use `adjtimex` as
well to set the time on big jump.
With this change, oscillation is pretty stable around zero, in
microsecond range (polling interval lowered for testing):
```
172.20.0.2: 2021/05/06 18:51:28  time.SyncController: adjusting time (slew) by -11.375µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:51:37  time.SyncController: adjusting time (slew) by 426.276µs via 192.36.143.130, state TIME_OK, status STA_PLL | STA_NANO
172.20.0.2: 2021/05/06 18:51:50 …
```
> fix: update the way NTP sync uses `adjtimex` syscall

- Makefile
- go.mod
- go.sum
- internal/app/apid/main.go
- internal/app/machined/main.go
- internal/app/trustd/main.go
> chore: allow building with debug handlers

- Makefile
- hack/parsebool.sh
Makes `make WITH_DEBUG=1` work.
Refs #3534.
Is there a better way?
> chore: parse "boolean" variables

- Makefile
- hack/test/e2e.sh
- internal/integration/provision/upgrade.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.11/Reference/cli.md
- website/content/docs/v0.11/Reference/configuration.md
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md
> feat: update Kubernetes to 1.21.1

- Makefile
- go.mod
- go.sum
- hack/test/e2e.sh
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/integration/provision/upgrade.go
- internal/pkg/cri/pods.go
- internal/pkg/ntp/ntp.go
- internal/pkg/ntp/ntp_test.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.10/Reference/cli.md
- website/content/docs/v0.10/Reference/configuration.md
PRs #3579 #3584 #3590 #3605 #3612
> backports: for 0.10.2 release

- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.2 release.
> release(v0.10.2): prepare release

- website/content/docs/v0.11/Guides/customizing-the-kernel.md
customizing kernel documentation update
> docs: custom kernel build steps update

- website/content/docs/v0.9/Introduction/what-is-new.md
> docs: fix spelling/grammar in What's New for Talos 0.9

- website/content/docs/v0.10/Guides/storage.md
- website/content/docs/v0.11/Guides/storage.md
This PR adds some documentation on how to use mayastor with talos and
links the video showing it in action.
> docs: add mayastor quickstart

- hack/test/e2e-docker.sh
- hack/test/e2e.sh
- hack/test/provision-tests.sh
- internal/integration/base/cli.go
- internal/integration/base/run.go
- internal/integration/cli/list.go
- pkg/archiver/walker_test.go
- pkg/provision/providers/qemu/launch.go
- website/content/docs/v0.11/Guides/configuring-pull-through-cache.md
Refs #3018.
Actual fixes will follow.
> test: better `talosctl ls` tests

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/pkg/configuration/configuration.go
> backports: fixes for Talos 0.10.3

- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.3 release.
> release(v0.10.3): prepare release

- website/content/docs/v0.10/Guides/configuring-wireguard-network.md
- website/content/docs/v0.11/Guides/configuring-wireguard-network.md
- website/content/docs/v0.9/Guides/configuring-wireguard-network.md
The wireguard guide has a small typo in the structure example of the config.
> docs: update wirguard guide

- cmd/talosctl/cmd/mgmt/config.go
Extract config generation into a seperate function. This reduces
cyclomatic complexity with the added benefit of being able to use
generation in another tool (e.g. Terraform provider to generate config).
Signed-off-by: Boran Car <boran.car@gmail.com>
Extract the config bundle generation into a separate function that can be invoked externally.
Primarily this is to enable creating a terraform provider so that talos generation can be easily rolled into typical terraform flows, without needing to stage it. The added benefit here is that it also reduces cyclomatic complexity of the original function. Still not enough though to remove the linting exception (cyclo is now at 15, whereas needs to be under 10).
> See `make help` for a description of the available …
> feat: extract config generation

- website/src/data/cloud-images.json
> docs: add AMIs for Talos 0.10.3

- cmd/talosctl/cmd/mgmt/gen.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/generate_test.go
- pkg/machinery/constants/constants.go
Minimal change for backporting into 0.10.
Refs #3421.
> feat: create certificates with os:admin role

- go.mod
- go.sum
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/pkg/mount/switchroot/switchroot.go
Fixes: https://github.com/talos-systems/talos/issues/3533
> feat: enable GORACE=halt_on_panic=1 in machined binary

- CHANGELOG.md
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0-alpha.0 release.
> release(v0.11.0-alpha.0): prepare release

- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
During boot sequence, if `talos.config`'s url has the uuid parameter, the uuid
value is retrieved via SMBIOS. However, at this part of the code it can happen
that the uuid is already set and valid. If this is the case, instead of
re-fetching the uuid, the one that is already set can be used.
The initial issue, why the call to SMBIOS fails has not been solved, however, it does not make sense to override a value that has already been set. This PR adds a check to only fetch uuid from SMBIOS when there is no value set.
closes #3676
> fix: only fetch machine uuid if it's not set

- internal/app/machined/pkg/system/services/etcd.go
- internal/integration/api/reset.go
This fixes a scenario when control plane node loses contents of `/var`
without leaving etcd first: on reboot etcd data directory is empty, but
member is already present in the etcd member list, so etcd won't be able
to join because of raft log being empty.
The fix is to remove a member with matching hostname if found in the
etcd member list followed by new member add.
The risk here is removing another member which has same hostname as the
joining node, but having duplicate hostnames for control plane node is a
problem anyways.
> fix: remove conflicting etcd member on rejoin with empty data directory

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- cmd/talosctl/cmd/mgmt/gen/csr.go
- go.mod
- go.sum
- internal/app/apid/main.go
- internal/app/apid/pkg/backend/apid.go
- internal/app/apid/pkg/backend/apid_test.go
- internal/app/apid/pkg/provider/tls.go
- internal/app/machined/pkg/controllers/k8s/templates.go
- internal/app/machined/pkg/system/services/machined.go
- internal/app/maintenance/main.go
- internal/app/trustd/main.go
- pkg/grpc/factory/factory.go
- pkg/grpc/middleware/auth/basic/token.go
- pkg/grpc/middleware/authz/authorizer.go
- pkg/grpc/middleware/authz/authorizer_test.go
- pkg/grpc/middleware/authz/context.go
- pkg/grpc/middleware/authz/injector.go
- pkg/grpc/middleware/authz/metadata.go
- pkg/grpc/proxy/backend/local.go
- pkg/grpc/proxy/backend/local_test.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/generate_test.go
- pkg/machinery/constants/constants.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- pkg/machinery/role/role.go
- pkg/machinery/role/role_test.go
- website/content/docs/v0.11/Reference/cli.md
It is not enforced yet.
Refs #3421.
> feat: implement basic RBAC interceptors

- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
- Prefer extraConfig (`guestinfo.*`) over OVF env
- Skip empty (zero-length) config from whatever source
In #3730 a user reported that OVF env takes precedence over extraConfig. Combined with the fact that `talos.config` is mandatory in the OVA spec (thus always present, and an empty string if you don't provide it), this causes two problems:
- when you don't supply the mandatory OVF env, it will cause an empty Talos config to be retrieved, which is unparsable;
- when you deploy a VM, you cannot override the built in Talos config, as OVF env takes precedence over extraConfig.
Fixes #3730
> Prefer extraConfig over OVF env, skip empty config

- internal/app/apid/pkg/backend/apid.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
- pkg/grpc/middleware/authz/context.go
- pkg/grpc/middleware/authz/metadata.go
- pkg/grpc/proxy/backend/local.go
- pkg/machinery/client/context.go
- pkg/machinery/config/types/v1alpha1/generate/generate_test.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/join.go
> feat: enable RBAC by default

- internal/app/machined/pkg/controllers/network/link_config.go
- internal/app/machined/pkg/controllers/network/link_config_test.go
This matches previous networkd implementation to make sure we can run
DHCP on the interfaces which are not explicitly brought up.
> feat: bring unconfigured links with link carrier up by default

- website/content/docs/v0.10/index.md
- website/content/docs/v0.11/index.md
Updated to be the correct time.
> docs: update community meeting time

- Makefile
Support NFS 4.1 by bumping pkgs version (it's been merged there).
To support NFS 4.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3766)
> feat: support NFS 4.1

- internal/app/machined/pkg/controllers/secrets/kubernetes.go
This includes communication from controller-manager and scheduler to the
API server and manifest injection by Talos controllers.
This eliminates dependency on control plane endpoint to be up, and might
speed up bootstrap on platform where load balancer might need some time
to start proxying to the first API server instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3780)
> fix: use localhost API server endpoint for internal communication

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0-alpha.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3781)
> release(v0.11.0-alpha.1): prepare release

- website/content/docs/v0.11/Guides/storage.md
Fill out storage guide a bit more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3750)
> docs: provide more storage details

- Dockerfile
- website/content/docs/v0.11/Guides/customizing-the-kernel.md
Fix ONBUILD  path in Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3786)
> fix: build with custom kernel/rootfs

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Fix of fixes #3765
* add PriorityClassName
* fix authentication/authorization for controlplane
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3804)
> feat: improve security of Kubernetes control plane components

- go.mod
- go.sum
- internal/app/machined/internal/server/v1alpha1/v1alpha1_resource.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- pkg/resources/config/machine_config.go
- pkg/resources/secrets/etcd.go
- pkg/resources/secrets/kubernetes.go
- pkg/resources/secrets/root.go
Refs #3421.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3802)
> feat: use COSI RD's sensitivity for RBAC

- cmd/installer/pkg/install/manifest.go
We need to be able to run an install with `docker run`. This checks if
we are running from docker and skips overlay mount checks if we are, as
docker creates a handful of overlay mounts by default that we can't
workaround (not easily at least).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3806)
> feat: skip overlay mount checks with docker

- Makefile
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
HP ILO drive, OVF fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3805)
> backports: 0.10.4

- CHANGELOG.md
- website/content/docs/v0.10/Reference/cli.md
This is the official v0.10.4 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3809)
> release(v0.10.4): prepare release

- website/src/data/cloud-images.json
Just new AMI IDs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3813)
> docs: add AMI IDs for Talos 0.10.4

- go.mod
- go.sum
See https://github.com/talos-systems/go-kmsg/pull/2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3824)
> fix: replace tabs with spaces in console output

- CHANGELOG.md
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0-alpha.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3822)
> release(v0.11.0-alpha.2): prepare release

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Do not use legacy method to run contolplane
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3826)
> feat: remove go-runner in staticpods

- internal/app/machined/pkg/controllers/k8s/templates.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.11/Reference/configuration.md
#3828 
* Coredns 1.8.0 -> 1.8.4
* Add RBAC endpointslices list/watch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/3830)
> chore: update coredns to 1.8.4

- docs/proposals/20190704-AutomatedUpgrades.md
- website/content/docs/v0.10/Learn More/architecture.md
- website/content/docs/v0.11/Learn More/architecture.md
- website/content/docs/v0.8/Learn More/architecture.md
- website/content/docs/v0.9/Learn More/architecture.md
Fix documentation typos.
Documentation should not have typos.
> fix: documentation typos

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0-beta.0 release.
> release(v0.11.0-beta.0): prepare release

- cmd/talosctl/cmd/talos/version.go
- internal/integration/cli/config.go
This commit also introduces a hidden `--json` flag for `talosctl version` command
that is not supported and should be re-worked at #907.
Refs #3852.
> chore: fix tests for disabled RBAC

- internal/app/machined/pkg/controllers/network/link_spec_test.go
- internal/app/machined/pkg/controllers/secrets/api.go
- pkg/grpc/gen/remote.go
- pkg/resources/network/link.go
> backports for Talos 0.11-beta.1

- CHANGELOG.md
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0-beta.1 release.
> release(v0.11.0-beta.1): prepare release

- pkg/cluster/bootstrap.go
With the recent changes, bootstrap API might wait for the time to be in
sync (as the apid is launched before time is sync). We set timeout to
500ms for the bootstrap API call, so there's a chance that a call might
time out, and we should ignore it.
> fix: ignore deadline exceeded errors on bootstrap

- internal/app/machined/pkg/controllers/network/address_merge.go
- internal/app/machined/pkg/controllers/network/link_merge.go
- internal/app/machined/pkg/controllers/network/route_merge.go
Fixes #3861
What this change effectively does is that it changes immediate reconcile
request to an error return, so that controller will be restarted with a
backoff.
More details:
* root cause of the update/teardown conflict is that the finalizer is
still pending on the tearing down resource
* finalizer might not be removed immediately, e.g. if the controller
which put the finalizer is itself in the crash loop
* if the merge controller queues reconcile immediately, it restarts
itself, but the finalizer is still there, so it once again goes into
reconcile loop and that goes forever until the finalizer is removed, so
instead if the controller fails, it will be restarted with exponential
backoff lowering the load on the system
Change is validated with the unit-tests reproducing the conflict. …
> fix: restart the merge controllers on conflict

- pkg/cluster/kubernetes/talos_managed.go
This removes `retrying error` messages while waiting for the API server
pod state to reflect changes from the updated static pod definition.
Log more lines to notify about the progress.
Skip `kube-proxy` if not found (as we allow it to be disabled).
```
$ talosctl upgrade-k8s -n 172.20.0.2 --from 1.21.0 --to 1.21.2
discovered master nodes ["172.20.0.2" "172.20.0.3" "172.20.0.4"]
updating "kube-apiserver" to version "1.21.2"
> "172.20.0.2": starting update
> "172.20.0.2": machine configuration patched
> "172.20.0.2": waiting for API server state pod update
< "172.20.0.2": successfully updated
> "172.20.0.3": starting update
> "172.20.0.3": machine configuration patched
> "172.20.0.3": waiting for API server state pod update
< "172.20.0.3": successfully updated
> "172.20.0.4": starting …
```
> fix: make output of `upgrade-k8s` command less scary

- website/content/docs/v0.11/Learn More/networking-resources.md
Internal details, resources, examples inspecting the configuration.
> docs: describe the new network configuration subsystem

- internal/app/machined/pkg/controllers/network/address_merge.go
- internal/app/machined/pkg/controllers/network/link_merge.go
- internal/app/machined/pkg/controllers/network/route_merge.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go
- pkg/cluster/bootstrap.go
- pkg/cluster/kubernetes/talos_managed.go
> backports for 0.11-beta.2

- CHANGELOG.md
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0-beta.2 release.
> release(v0.11.0-beta.2): prepare release

- internal/pkg/etcd/etcd.go
I believe `clientv3.SetEndpoints()` calls doesn't make etcd client
connect to the endpoints mentioned immediately, it might stil reuse old
connection (?).
At the same time `MaintenanceClient` which implements `MoveLeader` calls
doesn't support explicit endpoint setting (as other similar calls do),
so we have to manually force the connection to the leader node we need.
> fix: make forfeit leadership connect to the right node

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
This extends network device machine configuration validation to make
sure that bond slaves don't have any addressing methods set, as this
might run into a conflict with the bond setup.
Also makes sure no interface is part of two bonds.
> fix: validate bond slaves addressing

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0-beta.3 release.
> release(v0.11.0-beta.3): prepare release

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.0 release.
> release(v0.11.0): prepare release

- website/gridsome.config.js
- website/src/data/cloud-images.json
- website/static/_redirects
> docs: promote 0.11 docs to be the latest

- website/content/docs/v0.11/Introduction/what-is-new.md
This is just copy-paste from our changelog.
> docs: update what's new for Talos 0.11

- Makefile
See:
* https://github.com/talos-systems/tools/pull/142
* https://github.com/talos-systems/pkgs/pull/301
* https://github.com/talos-systems/extras/pull/22
> backport: feat: update Go to 1.16.6

- internal/app/machined/pkg/controllers/network/address_config.go
- internal/app/machined/pkg/controllers/network/address_config_test.go
- internal/app/machined/pkg/controllers/network/route_spec_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/resources/network/route_spec.go
> backports for 0.11.1

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.1 release.
> release(v0.11.1): prepare release

- internal/app/machined/pkg/controllers/network/link_status.go
When Talos runs in a container, `ethtool` availability depends on host
kernel support, and we don't strictly need `ethtool` to make networking
work, so make it optional instead of hard failure.
Example: https://gist.github.com/rgl/392d6e16d176f28430230b06ec80496c
> fix: make ethtool optional in link status controller

- pkg/cluster/kubernetes/talos_managed.go
Looks like I've missed some :facepalm:
> fix: pass all logs through the options.Log method

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.2 release.
> release(v0.11.2): prepare release

- website/content/docs/v0.10/Learn More/architecture.md
- website/content/docs/v0.11/Learn More/architecture.md
- website/content/docs/v0.12/Learn More/architecture.md
- website/content/docs/v0.8/Learn More/architecture.md
- website/content/docs/v0.9/Learn More/architecture.md
> fix: kuberentes => kubernetes typo

- Makefile
- pkg/machinery/constants/constants.go
> feat: update containerd to 1.5.3, runc to 1.0.1

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.3 release.
> release(v0.11.3): prepare release

- website/src/data/cloud-images.json
> docs: add 0.11.3 AMIs

- go.mod
- go.sum
- internal/pkg/encryption/encryption.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- website/content/docs/v0.12/Reference/configuration.md
Fixes: https://github.com/talos-systems/talos/issues/3606
> feat: expose more encryption options to the machine config

- CHANGELOG.md
- website/content/docs/v0.10/Introduction/what-is-new.md
- website/content/docs/v0.12/Introduction/what-is-new.md
"Optimizations" wasn't spelled correctly.
> chore: fix typos

- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.12/Reference/configuration.md
Update partition encryption mount options
> docs: add disk encryptions examples

- Makefile
See https://github.com/talos-systems/pkgs/pull/310
> feat: update GRUB to 2.06

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.4 release.
> release(v0.11.4): prepare release

- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- website/content/docs/v0.12/Reference/configuration.md
No need to do hacks with multiple interface entries just to get multiple
addressing methods
Fixes #2804
> feat: allow both DHCP and static addressing for the interface

- Makefile
See https://github.com/talos-systems/pkgs/pull/316
> feat: update grub to 2.06, bump max CPUs to 512

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
More friendly message why maintenance mode is starting
small part of #4018
> fix: maintenance mode reason message

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- internal/app/machined/pkg/controllers/k8s/templates.go
Token can use only for bootstrap nodes
split PR #3807
> feat: bootstrap token limit

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.11/Reference/cli.md
This is the official v0.11.5 release.
> release(v0.11.5): prepare release

- website/src/data/cloud-images.json
AMIs as uploaded via the CI release pipeline.
> docs: add AMIs for v0.11.5

- .drone.jsonnet
- hack/test/e2e-capi.sh
- hack/test/e2e-docker.sh
- hack/test/e2e-firecracker.sh
- hack/test/e2e-iso.sh
- hack/test/e2e-qemu.sh
- hack/test/e2e.sh
> chore: use k8s 1.21.3 in CAPI tests for now

- internal/app/machined/pkg/system/services/etcd.go
- pkg/machinery/constants/constants.go
> fix: move etcd PKI under /system/secrets

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.0-alpha.0 release.
> release(v0.12.0-alpha.0): prepare release

- CHANGELOG.md
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.0-alpha.1 release.
> release(v0.12.0-alpha.1): prepare release

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.0-beta.0 release.
> release(v0.12.0-beta.0): prepare release

- website/content/docs/v0.12/Cloud Platforms/aws.md
- website/content/docs/v0.12/Introduction/support-matrix.md
- website/content/docs/v0.12/Introduction/what-is-new.md
Also provide new way to fetch AMI IDs for 0.12.
> docs: add release notes for 0.12, support matrix

- CHANGELOG.md
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.0-beta.1 release.
> release(v0.12.0-beta.1): prepare release

- Dockerfile
- Makefile
> chore: fix arm64 reproducibility issues

- internal/pkg/mount/system.go
We have multiple calls for `mountState` even when `STATE` is already
mounted, so we should handle it properly.
Example error:
```
[  152.736427] [talos] apply configuration failed: error running phase 2 in applyConfiguration sequence: task 1/1: failed, error creating mount status resource: resource MountStatuses.runtime.talos.dev(runtime/STATE@1) already exists
```
(this bug is not present in 0.12)
> fix: ignore error on duplicate for `MountStatus`

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.0 release.
> release(v0.12.0): prepare release

- CHANGELOG.md
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.1 release.
> release(v0.12.1): prepare release

- pkg/cluster/kubernetes/talos_managed.go
> chore: use named constants

- website/static/_redirects
> docs: promote 0.12 docs to be the latest

- .drone.jsonnet
- cmd/installer/cmd/image.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud_test.go
- website/content/docs/v0.13/Cloud Platforms/upcloud.md
* cloud-init for upcloud.com
* ipv4/v6 support
* images format upcloud-$arch.raw.xz
> feat: add upcloud.com cloud support

- Makefile
forgot to add platforms to the makefile
* scaleway
* upcloud
> fix: build platform images

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.0-alpha.0 release.
> release(v0.13.0-alpha.0): prepare release

- pkg/cluster/sonobuoy/sonobuoy.go
Looks like we bumped sonobuoy library, and it silently changed a lot of
things in the way it works with the results.
> fix: update the way results are retrieved for certified conformance

- .drone.jsonnet
- Makefile
- cmd/installer/cmd/image.go
- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr_test.go
- website/content/docs/v0.13/Cloud Platforms/vultr.md
* cloud-init for vultr.com
* ipv4/v6 support
* set static IPs for private interface
> feat: add vultr.com cloud support

- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
* Refactoring Openstack platform.
* Catches a few edge bad cases.
The goal of this PR is make little refactoring. I'd like to add **config drive** support in next PRs https://docs.openstack.org/nova/latest/admin/config-drive.html
> openstack platform refactoring

- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/release.toml
- internal/app/machined/pkg/runtime/state.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
- pkg/machinery/config/types/v1alpha1/generate/generate.go
- pkg/machinery/config/types/v1alpha1/generate/init.go
- pkg/machinery/config/types/v1alpha1/generate/options.go
- pkg/machinery/config/types/v1alpha1/generate/worker.go
- website/content/docs/v0.13/Introduction/support-matrix.md
This should save a lot of time on BIOS/POST time with bare metal
hardware.
> feat: reboot via kexec

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/kubespan/manager.go
- internal/app/machined/pkg/controllers/kubespan/manager_test.go
- internal/app/machined/pkg/controllers/kubespan/nftables.go
- internal/app/machined/pkg/controllers/kubespan/nftables_test.go
- internal/app/machined/pkg/controllers/kubespan/routing_rules.go
- internal/app/machined/pkg/controllers/kubespan/routing_rules_test.go
- internal/app/machined/pkg/controllers/network/link_merge_test.go
- internal/app/machined/pkg/controllers/network/operator_spec.go
- pkg/resources/network/operator.go
- pkg/resources/network/operator_string.go
This concludes basic KubeSpan implementation.
Most of the code is from #3577 with some fixes and refactoring.
Co-authored-by: Seán C McCord <ulexus@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4241)
> feat: add routes, routing rules and nftables rules for KubeSpan

- internal/app/machined/pkg/controllers/time/sync.go
- internal/app/machined/pkg/controllers/time/sync_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.13/Reference/configuration.md
Fixes #4224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4245)
> feat: add an option to continue booting on NTP timeout

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4253)
> release(v0.12.2): prepare release

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.0-alpha.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4268)
> release(v0.13.0-alpha.1): prepare release

- hack/test/e2e-capi.sh
Testing with new CABPT release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4277)
> test: update CABPT provider to 0.3 release

- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/config.go
- pkg/machinery/config/bundle.go
- pkg/machinery/config/types/v1alpha1/bundle/bundle.go
- pkg/machinery/config/types/v1alpha1/bundle/options.go
- pkg/machinery/config/types/v1alpha1/machine/machine.go
- pkg/machinery/config/types/v1alpha1/machine/machine_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Closes #3910.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4293)
> chore: remove deprecated "join" term

- pkg/machinery/config/configloader/configloader_fuzz_test.go
- pkg/machinery/config/configloader/configloader_test.go
- pkg/machinery/config/configloader/testdata/controlplane.test
- pkg/machinery/config/configloader/testdata/empty1.test
- pkg/machinery/config/configloader/testdata/empty2.test
- pkg/machinery/config/configloader/testdata/worker.test
- pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
That PR contains an example of how fuzz tests can be written with Go 1.18.
It also fixes a few panics with invalid configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4160)
> test: add fuzz test for configloader

- Makefile
- pkg/machinery/constants/constants.go
See https://github.com/talos-systems/pkgs/pull/336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4295)
> chore: update Linux to 5.10.69

- CHANGELOG.md
- go.mod
- hack/protoc-lint/go.mod
- hack/protoc-lint/go.sum
- website/content/docs/v0.12/Reference/cli.md
This is the official v0.12.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4297)
> release(v0.12.3): prepare release

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.0-alpha.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4298)
> release(v0.13.0-alpha.2): prepare release

- internal/app/machined/pkg/controllers/network/address_status.go
- internal/app/machined/pkg/controllers/network/node_address.go
- internal/app/machined/pkg/controllers/network/node_address_test.go
- internal/app/machined/pkg/controllers/network/platform_config.go
- internal/app/machined/pkg/controllers/network/platform_config_test.go
This means that ExternalIPs (as presented by the platform) will be
published as `AddressStatus` resource, and transitively as
`NodeAddresses` (which includes cert generation) and as KubeSpan
endpoints (for KubeSpan connectivity in the cloud).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4303)
> feat: publish node's ExternalIPs as node addresses

- CHANGELOG.md
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.0-alpha.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4306)
> release(v0.13.0-alpha.3): prepare release

- Makefile
- go.mod
- go.sum
- hack/release.toml
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- website/content/docs/v0.13/Introduction/support-matrix.md
Update component versions, Go module versions.
Add platform tiers to the support matrix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4314)
> chore: prepare for 0.13-beta release

- .conform.yaml
- CHANGELOG.md
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.0-beta.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4316)
> release(v0.13.0-beta.0): prepare release

- hack/docgen/main.go
- hack/docgen/main_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.13/Reference/configuration.md
Use the real value in an example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4311)
> docs: fix documentation for cluster discovery

- internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/kubelet.go
- #4424
- #4441 
- #4452 
- #4465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4479)
> backports: for 0.13.2

- CHANGELOG.md
- hack/release.toml
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4480)
> release(v0.13.2): prepare release

- website/content/docs/v0.14/Cloud Platforms/gcp.md
- website/content/docs/v0.14/Cloud Platforms/gcp/config.yaml
- website/content/docs/v0.14/Cloud Platforms/gcp/talos-ha.jinja
Use GCP deployment manager for one command install
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4490)
> feat: use GCP deployment manager

- website/content/docs/v0.14/Cloud Platforms/gcp/talos-ha.jinja
Fixes generated talosconfig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4503)
> fix: endpoints and nodes in generated talosconfig

- go.mod
- go.sum
- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
Closes #4492.
Closes #4497.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4509)
> chore: bump dependencies

- internal/app/machined/pkg/controllers/kubespan/peer_spec.go
Should be helpful for debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4485)
> chore: log KubeSpan IPs overlaps

- internal/integration/cli/diskusage.go
Fixes: https://github.com/talos-systems/talos/issues/4382
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4517)
> fix: use etc folder for du cli tests

- go.mod
- go.sum
- pkg/cluster/sonobuoy/sonobuoy.go
See https://github.com/vmware-tanzu/sonobuoy/issues/1520.
Closes #4516.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4519)
> chore: update sonobuoy

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
5.15 is the new LTS: https://www.kernel.org/category/releases.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4523)
> feat: update Linux to 5.15.1

- website/content/docs/v0.10/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.11/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.12/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.13/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.13/Guides/kubespan.md
- website/content/docs/v0.13/Introduction/what-is-new.md
- website/content/docs/v0.14/Bare Metal Platforms/digital-rebar.md
- website/content/docs/v0.14/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.14/Cloud Platforms/hetzner.md
- website/content/docs/v0.14/Guides/configuring-the-cluster-endpoint.md
- website/content/docs/v0.14/Guides/kubespan.md
- website/content/docs/v0.14/Guides/storage.md
- website/content/docs/v0.14/Learn More/discovery.md
- website/content/docs/v0.14/Learn More/faqs.md
- website/content/docs/v0.8/Bare Metal Platforms/equinix-metal.md
- website/content/docs/v0.9/Bare Metal Platforms/equinix-metal.md
Fizes #4488 and some other typos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4514)
> fix: common typos

- cmd/talosctl/cmd/talos/support.go
- internal/app/machined/pkg/system/services/trustd.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/provision/providers/qemu/preflight.go
- pkg/provision/providers/vm/node.go
Avoid slice mutation with append.
Simplify code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4530)
> chore: fix simple issues found by golangci-lint

- website/content/docs/v0.14/Learn More/architecture.md
Update information about partitions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4535)
> docs: update partition info

- CHANGELOG.md
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.0-alpha.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4544)
> release(v0.14.0-alpha.1): prepare release

- pkg/machinery/resources/network/ula.go
Allocate one more value for the SideroLink feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4559)
> feat: add ULA prefix for SideroLink

- CHANGELOG.md
- go.mod
- hack/release.toml
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4573)
> release(v0.13.3): prepare release

- Makefile
- pkg/machinery/constants/constants.go
PRs:
* https://github.com/talos-systems/pkgs/pull/356
* https://github.com/talos-systems/pkgs/pull/357
* https://github.com/talos-systems/pkgs/pull/359
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4577)
> feat: update pkgs for u-boot, containerd, etc.

- cmd/talosctl/cmd/completion.go
- internal/integration/cli/completion.go
- website/content/docs/v0.14/Reference/cli.md
Generate talosctl completion for Fish
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4580)
> feat: talosctl fish completion support

- Dockerfile
- internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
Refs #4576.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4583)
> chore: set version in unit-tests

- hack/test/e2e-aws.sh
- hack/test/e2e-gcp.sh
This should help us to go forward with breaking changes in the templates
repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4586)
> test: pin cluster API templates version to tag v1alpha4

- internal/app/machined/internal/install/install.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/main.go
- internal/app/machined/pkg/controllers/runtime/events_sink.go
- internal/app/machined/pkg/controllers/runtime/events_sink_test.go
- internal/app/machined/pkg/controllers/v1alpha1/service.go
- internal/app/machined/pkg/runtime/controller.go
- internal/app/machined/pkg/runtime/drainer.go
- internal/app/machined/pkg/runtime/events.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- pkg/machinery/constants/constants.go
Report Talos events to any gRPC server.
Destination address is specified by using kernel parameters.
Fixes: https://github.com/talos-systems/talos/issues/4458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4585)
> feat: implement events sink controller

- Makefile
- pkg/machinery/constants/constants.go
PRs:
* https://github.com/talos-systems/pkgs/pull/360
* https://github.com/talos-systems/pkgs/pull/361
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4593)
> feat: update pkgs - Linux 5.15.4, LibreSSL 3.2.7

- go.mod
- internal/app/machined/pkg/controllers/network/operator_spec.go
- internal/app/machined/pkg/controllers/network/operator_spec_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/runner/containerd/containerd.go
- internal/app/machined/pkg/system/runner/containerd/opts.go
- internal/app/machined/pkg/system/runner/runner.go
- internal/app/machined/pkg/system/services/kubelet.go
- #4572 
- #4552 
- #4581 
- #4596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4609)
> backports: for 0.13.4

- CHANGELOG.md
- go.mod
- hack/release.toml
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.4 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4610)
> release(v0.13.4): prepare release

- website/content/docs/v0.14/Guides/logging.md
New Talos 0.14 feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4515)
> docs: add documentation about logging

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
See https://github.com/talos-systems/pkgs/pull/362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4619)
> feat: update Linux to 5.15.5

- CHANGELOG.md
- go.mod
- hack/release.toml
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.0-alpha.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4620)
> release(v0.14.0-alpha.2): prepare release

- website/content/docs/v0.14/Cloud Platforms/gcp.md
- website/content/docs/v0.14/Cloud Platforms/gcp/config.yaml
Fixes small issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4624)
> docs: fix GCP docs

- website/content/docs/v0.14/Guides/logging.md
Add notes on pod logs and kernel log delivery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4622)
> docs: expand logging documentation

- internal/app/machined/pkg/controllers/network/link_config.go
- internal/app/machined/pkg/controllers/network/link_config_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/docs/v0.14/Reference/configuration.md
Support setting MTU for VLAN
Fixes #3600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4625)
> feat: support MTU for VLAN's

- Makefile
- hack/release.toml
- pkg/images/list.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/vm/network.go
https://github.com/flannel-io/flannel/releases/tag/v0.15.1
Also updates CNI plugins to 1.0.1.
See:
* https://github.com/talos-systems/pkgs/pull/363
* https://github.com/talos-systems/extras/pull/31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4630)
> feat: update Flannel to 0.15.1

- hack/release.toml
- internal/app/machined/pkg/controllers/network/operator_config.go
- internal/app/machined/pkg/controllers/network/operator_config_test.go
- internal/app/machined/pkg/system/services/kubelet.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
- website/content/docs/v0.14/Reference/configuration.md
Support VIP for VLANS
Fixes #3601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4633)
> feat: VIP for VLANs

- Makefile
- pkg/machinery/constants/constants.go
See https://github.com/talos-systems/pkgs/pull/364
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4639)
> feat: update Linux to 5.15.6

- cmd/talosctl/cmd/talos/get.go
- website/content/docs/v0.14/Introduction/getting-started.md
- website/content/docs/v0.14/Reference/cli.md
Improves documentation clarity for a few common sticking points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4644)
> docs: improve clarity for users

- Makefile
In preparation for beta release, use final released versions.
There should be no actual package updates, just bumped versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4659)
> chore: bump tools/pkgs/extra to final released versions

- website/content/docs/v0.14/Guides/vip.md
VLAN VIP example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4661)
> docs: vlan VIP

- .drone.jsonnet
- Makefile
- website/content/docs/v0.14/Introduction/getting-started.md
Fixes #3311
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4660)
> chore: remove boot-{arch}.tar.gz artifact

- .conform.yaml
- CHANGELOG.md
- go.mod
- hack/release.toml
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.0-beta.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4663)
> release(v0.14.0-beta.0): prepare release

- Makefile
- hack/release.toml
See:
* https://github.com/talos-systems/tools/pull/164
* https://github.com/talos-systems/pkgs/pull/369
* https://github.com/talos-systems/extras/pull/35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4673)
> chore: update Go to 1.17.5

- CHANGELOG.md
- go.mod
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.0-beta.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4681)
> release(v0.14.0-beta.1): prepare release

- internal/integration/api/generate-config.go
- internal/pkg/tui/installer/state.go
- pkg/machinery/config/configloader/testdata/controlplane.test
- pkg/machinery/config/configloader/testdata/worker.test
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- website/content/docs/v0.14/Guides/deploying-cilium.md
- website/content/docs/v0.14/Reference/configuration.md
- Add Cilium CNI install guide
- Use Canal CNI for default examples
Fixes #4477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4698)
> docs: add cilium guide

- CHANGELOG.md
- go.mod
- hack/release.toml
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4713)
> release(v0.14.0): prepare release

- website/content/docs/v0.14/Introduction/support-matrix.md
- website/content/docs/v0.14/Introduction/what-is-new.md
- website/gridsome.config.js
- website/static/_redirects
Makes 0.14 latest, update what's new based on release notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4715)
> docs: update documentation for 0.14.0 release

- internal/integration/base/cli.go
- internal/integration/base/run.go
See #4702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4718)
> test: attempt number on two on proper retries in CLI time tests

- internal/app/machined/pkg/system/services/etcd.go
This PR solves a small UX issue where it's tought to know where to
actually send the talosctl bootstrap command when the VM or server gets
a DHCP address and we don't have access to the router to see what IP it
got.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4730)
> feat: output IPs when etcd needs to be bootstrapped

- cmd/talosctl/cmd/talos/list.go
- cmd/talosctl/cmd/talos/read.go
- cmd/talosctl/cmd/talos/root.go
Add shell completions for `list` and `read`
https://user-images.githubusercontent.com/18496730/147137557-d7f719b0-2fe9-46cb-96b2-6f8ee77917ff.mp4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4728)
> feat: shell completion for `list`, `read`

- website/content/docs/v0.14/Guides/storage.md
- website/content/docs/v0.15/Guides/storage.md
Update Mayastor docs with latest requirements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4731)
> docs: update Mayastor deployment process

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
Cleanup release.toml in preparation for 0.15-alpha.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4735)
> feat: update Linux to 5.15.11

- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.15/Guides/resetting-a-machine.md
- website/content/docs/v0.15/Reference/kernel.md
Fixes: https://github.com/talos-systems/talos/issues/4399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4734)
> feat: introduce `talos.experimental.wipe` kernel param to wipe system disk

- .drone.jsonnet
Looks like I missed adding new steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4751)
> chore: fix release pipeline

- hack/test/e2e-capi.sh
This PR updates to our latest point release for CACPPT to
ensure faster testing. It also pulls in a newer AWS provider.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4760)
> test: update CACPPT/CAPA components to latest

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
See:
* https://github.com/talos-systems/tools/pull/166
* https://github.com/talos-systems/pkgs/pull/379
* https://github.com/talos-systems/extras/pull/36
* https://github.com/talos-systems/pkgs/pull/378
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4779)
> feat: update Go to 1.17.6, containerd to 1.5.9

- website/content/docs/v0.14/Virtualized Platforms/vmware.md
- website/content/docs/v0.14/Virtualized Platforms/vmware/cp.patch
- website/content/docs/v0.14/Virtualized Platforms/vmware/vmware.sh
- website/content/docs/v0.15/Virtualized Platforms/vmware.md
- website/content/docs/v0.15/Virtualized Platforms/vmware/cp.patch
- website/content/docs/v0.15/Virtualized Platforms/vmware/vmware.sh
This PR updates the vmware docs to introduce a script to help with the
automation, as well as introduce the setup of talos-vmtoolsd and
reworking the format a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4777)
> docs: update vmware docs

- website/content/docs/v0.6/index.md
- website/content/docs/v0.7/index.md
- website/content/docs/v0.8/index.md
- website/content/docs/v0.9/index.md
Update office hours in older documentation versions to match current.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4780)
> docs: update office hours

- pkg/provision/providers/docker/docker.go
Filter the default list down to IPv4/IPv6 depending on the network
configuraiton. The problem is that the full list contains IPv6 resolvers
and these won't work on IPv4-only network (which is default for
`talosctl cluster create`).
This is not a problem for QEMU, as QEMU filters down the list for
built-in DHCP server already splitting it for DHCP4/DHCP6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4784)
> fix: filter down nameservers for docker-based cluster create

- website/content/docs/v0.10/index.md
- website/content/docs/v0.11/index.md
- website/content/docs/v0.12/index.md
- website/content/docs/v0.13/index.md
- website/content/docs/v0.14/index.md
- website/content/docs/v0.15/index.md
- website/content/docs/v0.6/index.md
- website/content/docs/v0.7/index.md
- website/content/docs/v0.8/index.md
- website/content/docs/v0.9/index.md
See #4781
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4789)
> docs: update index.md and sync across versions

- website/content/docs/v0.14/Virtualized Platforms/vmware.md
- website/content/docs/v0.15/Virtualized Platforms/vmware.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4792)
> fix: vmware documentation typo

- website/src/components/LayoutFooter.vue
- website/src/pages/Index.vue
From PRs #4798 #4799
Co-authored-by: Steve Francis <steve.francis@siderolabs.com>
Signed-off-by: Steve Francis <steve.francis@siderolabs.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4809)
> docs: update home page and footer

- Dockerfile
- go.mod
- go.sum
- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Dependabot + go-mod-outdated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4810)
> chore: bump depedencies

- pkg/cluster/check/kubernetes.go
Allow cluster nodes to have multiple internal IP addresses when checking
for all Kubernetes nodes.
Fixes #4807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4808)
> fix: handle multiple-IP cluster nodes

- .drone.jsonnet
- Dockerfile
- Makefile
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/jetson_nano/jetson_nano.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.15/Single Board Computers/bananapi_m64.md
- website/content/docs/v0.15/Single Board Computers/jetson_nano.md
- website/content/docs/v0.15/Single Board Computers/libretech_all_h3_cc_h5.md
- website/content/docs/v0.15/Single Board Computers/pine64.md
- website/content/docs/v0.15/Single Board Computers/rock64.md
- website/content/docs/v0.15/Single Board Computers/rockpi_4.md
- website/content/docs/v0.15/Single Board Computers/rpi_4.md
Support Jetson Nano SoC
Depends on https://github.com/talos-systems/pkgs/pull/380
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4819)
> feat: jetson nano SoC

- hack/release.toml
- website/content/docs/v0.15/Introduction/support-matrix.md
Release notes update from #4819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4823)
> chore: update release notes

- website/content/docs/v0.14/Learn More/developing-talos.md
- website/content/docs/v0.15/Learn More/developing-talos.md
Target audidence:
* maintainers
* contributors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4826)
> docs: add documentation on developing Talos

- website/content/docs/v0.14/Guides/storage.md
- website/content/docs/v0.15/Guides/storage.md
Fix the patch flag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4827)
> docs: fix patch flag

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
See https://www.openwall.com/lists/oss-security/2022/01/18/7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4830)
> chore: update Linux to 5.15.16

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
See https://www.openwall.com/lists/oss-security/2022/01/18/7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4833)
> chore: update Linux to 5.10.93

- hack/release.toml
- internal/app/machined/pkg/controllers/k8s/templates.go
- internal/integration/base/cli.go
- internal/integration/base/run.go
- pkg/cluster/sonobuoy/product.go
- pkg/cluster/sonobuoy/sonobuoy.go
- pkg/machinery/constants/constants.go
- website/content/docs/v0.15/Reference/configuration.md
PRs:
* #4717 
* #4718 
* #4821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4838)
> backports: for 0.14.1

- CHANGELOG.md
- go.mod
- hack/test/e2e-aws.sh
- hack/test/e2e-gcp.sh
- website/content/docs/v0.13/Reference/cli.md
This is the official v0.13.5 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4839)
> release(v0.13.5): prepare release

- CHANGELOG.md
- go.mod
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4842)
> release(v0.14.1): prepare release

- internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
Looks like despite the documentation, AWS IMDS library is using
different error wrapping on 404s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4881)
> fix: handle 404 errors from AWS IMDS correctly

- .drone.jsonnet
- hack/test/e2e-qemu.sh
- hack/test/e2e.sh
- hack/test/gvisor/manifest.yaml
This verifies system extensions via the gVisor system extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4884)
> test: add integration test for system extensions

- .drone.jsonnet
- Makefile
- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/test/e2e-qemu.sh
- hack/test/e2e.sh
- website/content/docs/v0.15/Reference/cli.md
Add tests for using rook as CSI for e2e-qemu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4841)
> chore: add CSI tests for e2e-qemu

- website/content/docs/v0.15/Cloud Platforms/oracle.md
Add more details for oracle cloud example installation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4879)
> doc: update oracle cloud example

- website/content/docs/v0.13/Guides/upgrading-talos.md
- website/content/docs/v0.14/Guides/upgrading-talos.md
- website/content/docs/v0.15/Guides/upgrading-talos.md
This enables new updated video for Talos upgrades.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4891)
> docs: replace Talos upgrades video

- internal/app/machined/internal/install/install.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
There's a low chance of a failure to clean up the containerd state from
previous installer pull/validate attempts which might render next
attempts unsuccessful as the snapshot already exists.
Sample error:
```
error validating installer image "foo": snapshot "validate": already exists
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4894)
> fix: clean up containerd state on installer run/validate

- website/content/docs/v0.15/Virtualized Platforms/hyper-v.md
Added documentation for setting up Talos cluster on Hyper-V. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4818)
> Added documentation for creating cluster on Hyper-V

- website/content/docs/v0.14/Guides/upgrading-kubernetes.md
- website/content/docs/v0.15/Guides/upgrading-kubernetes.md
Refreshed video with new content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4905)
> docs: update Kubernetes upgrade video

- pkg/grpc/middleware/authz/injector.go
Fixes #4910
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4911)
> fix: use leaf certificate in the apid RBAC check

- hack/release.toml
- pkg/machinery/constants/constants.go
- website/content/docs/v0.15/Reference/configuration.md
See https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4919)
> feat: update etcd to 3.5.2

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
Ump kernel to 5.15.21 stable
Ref: https://github.com/talos-systems/pkgs/pull/390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4937)
> chore: update kernel to 5.15.21

- website/content/docs/v0.14/Learn More/developing-talos.md
- website/content/docs/v0.15/Learn More/developing-talos.md
Port update and replace fish-specific for loop with bash one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4957)
> docs: fix developing Talos docs

- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
- website/content/docs/v0.15/Guides/editing-machine-configuration.md
- website/content/docs/v0.15/Guides/system-extensions.md
This is very first guide, we can expand it as we get more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4963)
> docs: add guide on system extensions

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
See:
* https://github.com/talos-systems/tools/pull/168
* https://github.com/talos-systems/pkgs/pull/395
* https://github.com/talos-systems/pkgs/pull/397
* https://github.com/talos-systems/extras/pull/37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4967)
> feat: update Go to 1.17.7, Linux to 5.15.23

- CHANGELOG.md
- go.mod
- website/content/docs/v0.15/Reference/cli.md
This is the official v0.15.0-alpha.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4968)
> release(v0.15.0-alpha.2): prepare release

- CHANGELOG.md
- go.mod
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4971)
> release(v0.14.2): prepare release

- website/content/docs/v0.15/Introduction/getting-started.md
Small fixes for getting started guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4989)
> docs: update getting-started.md

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
See https://github.com/talos-systems/pkgs/pull/400
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4991)
> feat: update containerd to 1.6.0

- hack/release.toml
- pkg/machinery/constants/constants.go
- website/content/docs/v0.15/Reference/configuration.md
See https://github.com/coredns/coredns/blob/master/notes/coredns-1.9.0.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4992)
> feat: update CoreDNS to 1.9.0

- website/content/docs/v0.15/Learn More/concepts.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5014)
> docs: design concepts page

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
Bump tools, pkgs and extras
Ref:
- https://github.com/talos-systems/tools/pull/171
- https://github.com/talos-systems/extras/pull/39
- https://github.com/talos-systems/pkgs/pull/403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5027)
> chore: bump tools, pkgs, extras

- website/content/docs/v0.15/Guides/troubleshooting-control-plane.md
Updated wording, added some cross references, and generally updated the
controlplane troubleshooting document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5032)
> docs: updates to troubleshooting doc

- Dockerfile
- Makefile
- hack/cleanup.sh
See #4985
Also a bit more cleanup of the rootfs contents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5033)
> feat: update xfsprogs to 5.14.2, replace LibreSSL with OpenSSL

- go.mod
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
- pkg/download/download.go
This feature allow to us use low source port <1024 to make a http calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4993)
> feat: add low source port capabilities

- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
We've forgot to apply network setting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5054)
> fix: scaleway network config

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
This brings in the following changes:
* https://github.com/talos-systems/pkgs/pull/404
* https://github.com/talos-systems/pkgs/pull/405
* https://github.com/talos-systems/pkgs/pull/406
* https://github.com/talos-systems/pkgs/pull/407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5058)
> chore: update pkgs and extras

- website/content/docs/v0.14/Guides/deploying-cilium.md
- website/content/docs/v0.15/Guides/deploying-cilium.md
Update cilium docs to reflect using K8s IPAM mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5062)
> docs: update cilium docs

- internal/app/machined/pkg/controllers/config/k8s_control_plane.go
- internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
- pkg/machinery/config/provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_apiserverconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_controllermanagerconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_schedulerconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
- pkg/machinery/resources/config/k8s_control_plane.go
- website/content/docs/v0.15/Reference/configuration.md
Fixes #5055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5059)
> feat: support specifying env vars for control plane pods

- hack/release.toml
Fix typo in release notes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5067)
> docs: fix typo in release notes

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
Also update Linux to 5.15.26.
See https://github.com/talos-systems/pkgs/pull/410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5069)
> feat: update containerd to 1.6.1

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
See https://github.com/talos-systems/pkgs/pull/411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5074)
> feat: update Linux to 5.15.26

- CHANGELOG.md
- go.mod
- hack/release.toml
- website/content/docs/v0.14/Reference/cli.md
This is the official v0.14.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5075)
> release(v0.14.3): prepare release

- website/content/docs/v0.14/Guides/deploying-cilium.md
- website/content/docs/v1.0/Guides/deploying-cilium.md
Update cilium inline install
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5079)
> docs: update cilium inline install

- Makefile
- README.md
- hack/release.toml
Fixes #5080
This updates all package dependencies to 1.0 versions.
Add a GPL note to README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5081)
> feat: update pkgs to 1.0 versions, Go 1.17.8

- internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
When IPv6 is disabled entirely, we should not try to set IPv6-related kernel parameter defaults,
since the `/proc/sys/net/ipv6` directory will not exist.
This performs a check before adding the default kernel parameters.
Fixes #5087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5088)
> fix: check for IPv6 before applying IPv6 kernel defaults

- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
fix equinix platform name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5098)
> chore: fix equinixMetal platform name

- website/content/docs/v1.0/Guides/logging.md
This PR adds a simple note about forwarding to loki from fluentbit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5102)
> docs: add loki note

- .conform.yaml
- cmd/installer/pkg/raw.go
- internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
- internal/pkg/partition/constants.go
- #5088 
- #5097 
- #5098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5123)
> backports: for v1.0.0-beta.1

- CHANGELOG.md
- go.mod
- website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.0-beta.1 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5126)
> release(v1.0.0-beta.1): prepare release

- internal/app/machined/pkg/system/services/etcd.go
This is more of a bandaid, rather than a real fix. As this should be
bacported to `release-1.0`, I tried to avoid doing big changes.
The race condition: controller correctly watches network state and
issues etcd certs as needed, but the service `etcd` writes down PKI
files from the resource just once early on startup. In this case there's
a chance that wrong PKI gets written to disk leaving etcd with
incomplete certs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5135)
> fix: refresh etcd certs on startup/join

- api/security/security.proto
- pkg/machinery/api/security/security.pb.go
- website/content/docs/v1.0/Reference/api.md
Small improvements to comments.
The comment looked like a copy paste from another service and did not match the actual behavior. Also added a little more details to the fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5137)
> docs: improve comments in security proto

- pkg/cluster/check/kubernetes.go
With graceful kubelet shutdown (#5108), after graceful node restart pods
on the restarted node might stay in the status `Terminated` which breaks
the check on pod readiness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5142)
> fix: ignore terminated pods in pod health checks

- CHANGELOG.md
- go.mod
- website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.0-beta.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5167)
> release(v1.0.0-beta.2): prepare release

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
This is a backport for Talos 1.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5171)
> feat: update Linux to 5.15.30

- website/content/v1.0/guides/system-extensions.md
Fix extensions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5189)
> docs: fix extensions

- cmd/talosctl/cmd/mgmt/cluster/create.go
- website/content/v1.0/reference/cli.md
There was hardcoded org/username.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5188)
> chore: update the talosctl CNI download url

- hack/release.toml
- pkg/machinery/constants/constants.go
- website/content/v1.0/reference/configuration.md
See https://github.com/coredns/coredns/releases/tag/v1.9.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5174)
> feat: update CoreDNS to 1.9.1

- Makefile
- go.mod
- go.sum
- hack/release.toml
- pkg/machinery/constants/constants.go
See:
* https://github.com/siderolabs/pkgs/pull/426
* https://github.com/siderolabs/pkgs/pull/430
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5193)
> feat: update containerd to 1.6.2, Linux to 5.15.31

- website/layouts/partials/hooks/body-end.html
This PR ensures only results from latest are returned in the algolia
search results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5196)
> docs: filter algolia results by latest

- internal/app/apid/pkg/backend/apid.go
- pkg/grpc/factory/factory.go
- pkg/machinery/client/client.go
Fixes: #4950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5199)
> fix: increase intiial window and conn window sizes

- website/content/v1.0/learn-more/extension-services.md
Fix extension service `path` dependency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5204)
> docs: fix extension service `path` dependency

- CHANGELOG.md
- go.mod
- website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.0-beta.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5206)
> release(v1.0.0-beta.3): prepare release

- website/layouts/partials/hooks/body-end.html
This PR updates the algolia search script such that results are filtered
based on your currently selected version (or latest if you're on the
main splash page).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5210)
> docs: target search results

- website/content/v0.14/guides/configuring-ceph-with-rook.md
- website/content/v1.0/guides/configuring-ceph-with-rook.md
Adds a guide for installing and removing a Rook Ceph
cluster with Talos Linux.
Closes #3665.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5228)
> docs: add rook ceph configuration guide

- website/content/v0.14/virtualized-platforms/proxmox.md
- website/content/v1.0/virtualized-platforms/proxmox.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5178)
> Fix incorrect path for talosconfig

- .gitignore
- Makefile
- hack/release.toml
- website/content/v1.0/guides/nvidia-gpu.md
Add NVIDIA docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5230)
> docs: add NVIDIA docs

- website/content/v1.0/guides/upgrading-talos.md
- website/content/v1.0/introduction/support-matrix.md
- website/content/v1.0/introduction/what-is-new.md
Mostly reformatting and updating release notes for easier consumption.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5232)
> docs: add release notes for 1.0

- go.mod
- go.sum
- hack/release.toml
- internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
- internal/app/machined/pkg/controllers/network/operator/vip.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
- internal/app/machined/pkg/system/services/kubelet.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- pkg/machinery/resources/k8s/k8s_test.go
- pkg/machinery/resources/k8s/kubelet_lifecycle.go
- pkg/provision/providers/docker/docker.go
PRs:
- #5212 
- #5213 
- #5214 
- #5231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5233)
> backports: for 1.0.0

- website/content/v1.0/introduction/what-is-new.md
Just a few small changes for readability
in the Whats New section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5240)
> docs: update whats-new-v1.0

- website/config.toml
- website/content/v1.0/guides/nvidia-gpu.md
- website/layouts/partials/hooks/body-end.html
- website/layouts/partials/hooks/head-end.html
- website/static/css/clipboard.css
- website/static/js/clipboard.js
Enable code blocks copying
Ref: https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/
Supersedes #5235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5238)
> docs: code block copying

- CHANGELOG.md
- go.mod
- hack/release.toml
- website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5239)
> release(v1.0.0): prepare release

- website/content/v1.0/single-board-computers/jetson_nano.md
Update jetson nano
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5243)
> docs: update jetson nano

- website/config.toml
- website/content/v0.14/_index.md
- website/content/v1.0/_index.md
- website/static/_redirects
Just moving pointers to 1.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5245)
> docs: mark 1.0 docs as latest

- cmd/talosctl/cmd/mgmt/cluster/create.go
- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Potentially fixes: #4985
See siderolabs/go-blockdevice#58 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5255)
> fix: align partitions on 1M boundary

- pkg/cluster/kubernetes/talos_managed.go
This showed up recently frequently in integration-provision tests
(might be related to Kubernetes upgrade), but anyways errors should be
retried.
Refactored the function to extract the retryable part.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5275)
> fix: retry manifest updates in upgrade-k8s

- website/config.toml
- website/content/v1.0/bare-metal-platforms/digital-rebar.md
- website/content/v1.0/guides/storage.md
- website/content/v1.1/bare-metal-platforms/digital-rebar.md
- website/content/v1.1/guides/storage.md
This PR is an omnibus edition of Steve's PRs. It includes three small
things to the docs:
- A change to config.toml to avoid redirects a bit better
- Updates to digital rebar doc that fixes a few links and typos.
- Updates for typos and wording of storage.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5272)
> docs: update config.yaml, storage.md, digital-rebar.md

- Dockerfile
The main goal to avoid cache invalidation on `tag` changes: by pushing
the tag down the build after the generate step, avoid invalidating build
cache on each tag change (`-dirty`, rebasing, etc.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5281)
> refactor: change the stages for embed files generation

- .drone.jsonnet
- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/release.toml
- internal/app/machined/pkg/system/services/etcd.go
- internal/pkg/containers/cri/containerd/hosts.go
- internal/pkg/containers/cri/containerd/hosts_test.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/provision/providers/docker/node.go
- pkg/provision/request.go
- website/content/docs/v1.0/Reference/cli.md
- #5250 
- #5263 
- #5264 
- #5275 
- #5279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5290)
> backports: for release v1.0.1

- Makefile
- hack/release.toml
- internal/app/machined/pkg/controllers/network/operator/dhcp6.go
- pkg/cluster/kubernetes/detect.go
- #5301 
- #5306 
- Go 1.17.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5340)
> backports: for v1.0.2

- CHANGELOG.md
- go.mod
- website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.2 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5341)
> release(v1.0.2): prepare release

- website/content/v1.0/kubernetes-guides/configuration/ceph-with-rook.md
- website/content/v1.1/kubernetes-guides/configuration/ceph-with-rook.md
Improve the Rook Ceph documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5369)
> docs: improve rook-ceph description
