siderolabs/talos

internal/app/machined/pkg/controllers/network/route_spec.go

When looking up existing routes in the kernel routing table, make sure
routes are filtered by the address family (IPv4, IPv6). This is usually
redundant, as either destination or gateway enforces the family, but for
the default routes without the destination, we need to add this check.

fix: match correctly routes on the address family

---

Dockerfile
Makefile
cmd/installer/cmd/iso.go
cmd/installer/pkg/epoch.go
cmd/installer/pkg/iso.go
cmd/installer/pkg/touch.go

This relies on changes in GRUB and other utilities to respect
`SOURCE_DATE_EPOCH`.
Variable `SOURCE_DATE_EPOCH` is set to the timestamp of the last git
commit which makes it deterministic, but still changes for each
release/commit.

feat: make ISO builds reproducible

---

.conform.yaml

GPG signatures are now required.

chore: require GPG signatures

---

hack/release.toml
pkg/machinery/config/decoder/decoder.go
pkg/machinery/config/decoder/decoder_test.go

This should address issues when the config is a valid yaml but contains
extra fields which may appear there if the indents got messed up somehow
for example.

feat: validate if extra fields present in the decoder

---

hack/release.toml
internal/app/machined/pkg/system/runner/containerd/containerd.go

This enable seccomp profile for all contianers launched by Talos: apid,
trustd, etcd and kubelet.
Also by default disallow gaining more priveleges in the container
(basically disables setuid). As contianers are running as root this is
no-op, but soon we'll have running as non-root users and this becomes
important.

fix: enable seccomp default profile by default

---

hack/release.toml
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/machined.go
internal/app/machined/pkg/system/services/trustd.go
internal/app/machined/pkg/system/services/utils.go
internal/pkg/mount/pseudo.go
pkg/machinery/constants/constants.go

For the `trustd`, this change is simple as it doesn't access any files
on the host filesystem.
For the `apid`, there are more things involved:
* `apid.sock` used for internal API calls should be createable by `apid`
* `runtime.sock` used for apid to COSI communication should be
accessible for `apid`
* `machined.sock` used for proxying calls to machined should be as well
made available to the `apid`.
Plus fixes default permissions for `tmpfs` mountpoints.

chore: run apid and trustd services as non-root user 

---

cmd/talosctl/cmd/talos/apply-config.go
pkg/machinery/constants/constants.go

Fixes: https://github.com/talos-systems/talos/issues/3909

 chore: drop deprecated `--no-reboot` param and KernelCurrentRoot const

---

hack/release.toml
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/utils.go
pkg/machinery/constants/constants.go

etcd has two mounts from the host, both of them are chowned to be
accessible by the etcd user:
* data directory
* secrets directory

chore: run etcd as non-root user

---

pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/generate/generate.go
pkg/machinery/config/types/v1alpha1/generate/generate_test.go
pkg/machinery/config/types/v1alpha1/generate/init.go
pkg/machinery/config/types/v1alpha1/generate/options.go
pkg/machinery/config/types/v1alpha1/generate/worker.go
pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/constants/constants.go
website/content/docs/v0.12/Reference/configuration.md

Adds a non-secret unique cluster identifier and a shared secret cluster
membership key for use by membership validation and discovery
mechanisms.
Fixes #4070

feat: add ClusterID and ClusterSecret

---

Makefile
pkg/machinery/constants/constants.go

* util-linux: 2.37
* LibreSSL: 3.2.5
* linux-firmware: 20210716
* eudev: 3.2.10
* u-boot: 2021.07
* raspberrypi-firmware: 1.20210805

feat: update Linux to 5.10.58 and many pkgs updates

---

.drone.jsonnet
Makefile

Race-detector enabled image is pushed with a tag next to normal image,
regular integration test is ran against the image.

chore: run e2e-qemu test against Talos with race-detector enabled

---

Makefile
go.mod
go.sum
pkg/machinery/go.mod
pkg/machinery/go.sum

No real functional changes, just updating to the final versions before
Talos 0.12 release.

chore: update versions to final release tags

---

website/content/docs/v0.11/Cloud Platforms/azure.md
website/content/docs/v0.12/Cloud Platforms/azure.md

This PR makes sure that azure VMs are zero indexed for consistency with
the way that NICs and IPs are generated earlier in the docs. I'm not
quite sure why we went with `seq( 0 1 2 )` instead of `seq( 0 2 )`, but
I kept the sequences the same for consistency.

docs: ensure azure VMs are 0 indexed

---

Dockerfile

It's flaky and we have another dirty check, so this one can be safely removed.

chore: do not check that go mod tidy gives empty output

---

Dockerfile

This fixes the diff between local and CI builds, apparently different
`umask` for the file checked out on the host:
```
--- initramfs-amd64.xz
+++ initramfs-amd64.ci.xz
│   --- initramfs-amd64
├── +++ initramfs-amd64.ci
│ ├── rootfs.sqsh
│ │ ├── unsquashfs -d  -lls {}
│ │ │ @@ -9,15 +9,15 @@
│ │ │  -rwxr-xr-x root/root          11441016 2021-08-17 16:57 /bin/runc
│ │ │  drwxr-xr-x root/root                 3 2021-08-17 16:57 /boot
│ │ │  drwxr-xr-x root/root                 3 2021-08-17 16:57 /dev
│ │ │  drwxr-xr-x root/root               186 2021-08-17 16:57 /etc
│ │ │  lrwxrwxrwx root/root                 8 2021-08-17 16:57 /etc/ca-certificates -> /etc/ssl
│ │ │  drwxr-xr-x root/root                 3 2021-08-17 16:57 /etc/cni
│ │ │  drwxr-xr-x root/root                38 2021-08-17 …
```

fix: make sure file mode is same (reproducibility issue)

---

internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go

This handles the case if the machine config doesn't contain
`.machine.network` (I got hit by that today).

fix: don't panic if the machine config doesn't have network (EM)

---

cmd/talosctl/cmd/talos/upgrade-k8s.go
hack/release.toml
pkg/cluster/kubernetes/daemonset.go
pkg/cluster/kubernetes/talos_managed.go
pkg/cluster/kubernetes/upgrade.go
website/content/docs/v0.12/Guides/upgrading-kubernetes.md
website/content/docs/v0.12/Reference/cli.md

Fixes: https://github.com/talos-systems/talos/issues/4026
Also add `dry-run` mode in `upgrade-k8s` command.

feat: check if cluster has deprecated resources versions

---

internal/app/machined/pkg/system/runner/containerd/containerd.go
internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/app/machined/pkg/system/runner/process/process.go
internal/app/machined/pkg/system/runner/process/process_test.go
internal/app/machined/pkg/system/runner/runner.go
internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/cri.go
internal/app/machined/pkg/system/services/udevd.go
internal/pkg/containers/containerd/containerd_test.go
internal/pkg/containers/cri/cri_test.go
internal/pkg/cri/cri_test.go

When running with cgroupsv2 and the deeply nested nature of our CI, we
need to take extra steps to make sure tests are working fine.
Some tests were disabled under cgroupsv2 as I can't make them work.

test: adapt tests to the cgroupsv2

---

internal/app/machined/pkg/system/runner/process/process.go

This was left from my attempts to fix the tests.
When Talos runs as OS, it should never try to nest cgroups, as machined
itself runs as `/system/init` and it shouldn't nest inside that cgroup.

fix: don't support cgroups nesting in process runner

---

internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

That was accidentally changed after migration to kernel params
controller.

fix: do not set KSPP kernel params in container mode

---

internal/pkg/mount/cgroups.go

Fix mount option nsdelegate.
It makes delegation safe (more restrictions in the cgroup namespace).
refs #4108 
result will be:
```bash
cgroup /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
```

fix: cgroup delegate

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/etcd.go

If etcd data directory is not empty, it means that `etcd` is already
running (or etcd has run), so removing data directory might lead to data
loss. Under normal circumstances `etcd` is not started before either
node joins existing etcd cluster or it gets bootstrapped.
Most importantly, with this change it's not possible to nuke etcd member
by issuing `talosctl bootstrap` on already running Talos node.
Plus nag user about doing bootstrap if the node is waiting to join.

fix: don't allow bootstrap if etcd data directory is not empty

---

internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
website/content/docs/v0.12/Introduction/support-matrix.md

Fix the casing of the `VMware` name.
Its name is `VMware` instead of `VMWare`.

fix: properly case the VMware name

---

Dockerfile
internal/app/machined/pkg/controllers/network/hardware_addr.go
internal/app/machined/pkg/controllers/network/hardware_addr_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
pkg/resources/network/hardrware_addr.go
pkg/resources/network/network_test.go

This will be used to derive e.g. KubeSpan address.
Fixes #4132
Example:
```
$ talosctl -n 172.20.0.2 get hardwareaddresses -o yaml
node: 172.20.0.2
metadata:
namespace: network
type: HardwareAddresses.net.talos.dev
id: first
version: 1
owner: network.HardwareAddrController
phase: running
created: 2021-08-24T20:30:43Z
updated: 2021-08-24T20:30:43Z
spec:
name: eth0
hardwareAddr: 6a:2b:bd:b2:fc:e0
```

feat: provide first NIC hardware addr as a resource

---

internal/app/machined/pkg/controllers/config/k8s_address_filter.go
internal/app/machined/pkg/controllers/config/k8s_address_filter_test.go
internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
internal/app/machined/pkg/controllers/network/node_address.go
internal/app/machined/pkg/controllers/network/node_address_test.go
internal/app/machined/pkg/controllers/secrets/api.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
pkg/resources/k8s/k8s.go
pkg/resources/network/network_test.go
pkg/resources/network/node_address.go
pkg/resources/network/node_address_filter.go

This implements abstract `NodeAddressFilter` which can be attached to
build additional `NodeAddress` resources filtering out some entries from
the complete list.
Kubernetes creates two filters to get all node IPs without Kubernetes
CIDRs and vice versa, only Kubernetes CIDRs.
API certificate generation now considers all addresses minus K8s CIDRs.

feat: add node address filters, filter out k8s addresses for Talos API

---

internal/app/machined/pkg/system/services/etcd.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
website/content/docs/v0.13/Reference/configuration.md

This adds the ability to specify the subnet that `etcd`'s listen address
should be in. This allows users to ensure that `etcd` is on a private
subnet.

feat: add subnet filter for etcd address

---

hack/release.toml
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go

The type was changed, but the example wasn't updated accordingly.

fix: correctly define example for `extraMounts`

---

cmd/talosctl/cmd/mgmt/cluster/create.go
internal/app/machined/pkg/controllers/secrets/altnames.go
internal/app/machined/pkg/controllers/secrets/api.go
internal/app/machined/pkg/controllers/secrets/api_test.go
internal/app/machined/pkg/controllers/secrets/kubernetes.go
internal/app/machined/pkg/controllers/secrets/kubernetes_test.go
internal/app/machined/pkg/controllers/secrets/utils.go
internal/app/machined/pkg/controllers/secrets/utils_test.go
pkg/kubernetes/kubernetes.go
pkg/machinery/config/contract.go
pkg/machinery/config/contract_test.go
pkg/machinery/config/types/v1alpha1/generate/generate.go

This is a PR on a path towards removing `ApplyDynamicConfig`.
This fixes Kubernetes API server certificate generation to use dynamic
data to generate cert with proper SANs for IPs of the node.
As part of that refactored a bit apid certificate generation (without
any changes).
Added two unit-tests for apid and Kubernetes certificate generation.

feat: use dynamic NodeAddresses/HostnameStatus in Kubernetes certs

---

Makefile

This pulls in latest master versions of tools/pkgs/extras:
* new reproducible toolchain with GCC 11.2
* fix for the `strip` to be multi-arch
* new reproducible tools
* updated pkgs with fixes for GCC 11.2
* updated extras

chore: update tools/pkgs/extras to the new version

---

.conform.yaml
Makefile

This check enforces that commit should not only be signed by GPG
signature, but also signature identity should be one of the
`talos-systems` organization members.
Talos welcomes all external contributions, this check just means that
the commit will be signed with one of the org members before merge.

chore: enable GPG identity check for Talos

---

internal/app/machined/pkg/controllers/cluster/cluster_test.go
internal/app/machined/pkg/controllers/cluster/config.go
internal/app/machined/pkg/controllers/cluster/config_test.go
internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
internal/app/machined/pkg/controllers/cluster/node_identity_test.go
internal/app/machined/pkg/controllers/network/etcfile.go
internal/app/machined/pkg/controllers/network/etcfile_test.go
internal/app/machined/pkg/controllers/network/hostname_config.go
internal/app/machined/pkg/controllers/network/hostname_config_test.go
internal/app/machined/pkg/controllers/network/node_address.go
internal/app/machined/pkg/controllers/network/node_address_test.go
internal/app/machined/pkg/controllers/network/status_test.go
internal/app/machined/pkg/controllers/secrets/api.go
internal/app/machined/pkg/controllers/secrets/api_test.go
internal/app/machined/pkg/controllers/secrets/kubernetes.go
internal/app/machined/pkg/controllers/secrets/kubernetes_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
internal/app/maintenance/main.go
pkg/machinery/config/types/v1alpha1/machine/machine.go
pkg/machinery/constants/constants.go
pkg/resources/cluster/affiliate.go
pkg/resources/cluster/cluster_test.go
pkg/resources/cluster/config.go
pkg/resources/network/node_address.go

Fixes #4139
This builds the local (for the node) `Affiliate` structure which
describes node for the cluster discovery. Dependending on the
configuration, KubeSpan information might be included as well.
`NodeAddresses` were updated to hold CIDRs instead of simple IPs.
The `Affiliate` will be pushed to the registries, while `Affiliate`s for
other nodes will be fetched back from the registries.

feat: provide building of local `Affiliate` structure (for the node)

---

internal/app/machined/pkg/controllers/cluster/affiliate_merge.go
internal/app/machined/pkg/controllers/cluster/affiliate_merge_test.go
internal/app/machined/pkg/controllers/cluster/config.go
internal/app/machined/pkg/controllers/cluster/config_test.go
internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go
internal/app/machined/pkg/controllers/cluster/kubernetes_push.go
internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/member.go
internal/app/machined/pkg/controllers/cluster/member_test.go
internal/app/machined/pkg/controllers/secrets/kubernetes.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
internal/pkg/discovery/registry/kubernetes.go
internal/pkg/discovery/registry/kubernetes_test.go
internal/pkg/discovery/registry/registry.go
pkg/machinery/constants/constants.go
pkg/resources/cluster/affiliate.go
pkg/resources/cluster/affiliate_test.go
pkg/resources/cluster/cluster.go
pkg/resources/cluster/cluster_test.go
pkg/resources/cluster/config.go
pkg/resources/cluster/member.go

This implements pushing to and pulling from Kubernetes cluster discovery
registry which is simply using extra Talos annotations on the Node
resources.
Note: cluster discovery is still disabled by default.
This means that each Talos node is going to push data from its own local
`Affiliate` structure to the `Node` resource, and also watches the other
`Node`s to scrape data to build `Affiliate`s from each other cluster
member.
Further down the pipeline, `Affiliate` is converted to a cluster
`Member` which is an easy way to see the cluster membership.
In its current form, `talosctl get members` is mostly equivalent to
`kubectl get nodes`, but as we add more registries, it will become more
powerful.

feat: implement Kubernetes cluster discovery registry

---

pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/docs/v0.13/Reference/configuration.md

Clarifies that either `bind` or `rbind` are required in the Kubelet's
`extraMounts`.

docs: document required options for extraMounts

---

pkg/machinery/config/types/v1alpha1/v1alpha1_types.go

The type was changed, but the example wasn't updated accordingly.
(cherry picked from commit bd5b9c96e2563249a5633433703493b292b83ee9)
PR: #4184

backport: fix: correctly define example for `extraMounts`

---

Makefile

In the PR #4186 tools were bumped to the wrong version.

chore: bump tools to the latest version

---

.drone.jsonnet
Makefile
cmd/installer/cmd/image.go
internal/app/machined/pkg/runtime/v1alpha1/platform/errors/errors.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
website/content/docs/v0.13/Cloud Platforms/hetzner.md

Hetzner cloud does not support DHCP-v6/SLAAC so we can get it from meta server.
refs #3599
* Add cloud-init for hcloud (Hetzner cloud)
* Set ipv6 to the interface
Docs:
* https://docs.hetzner.cloud/#server-metadata
* https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceHetzner.py

feat: add hetzner.com cloud support

---

internal/app/machined/pkg/controllers/kubespan/kubespan_test.go
internal/app/machined/pkg/controllers/kubespan/peer_spec.go
internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
pkg/resources/kubespan/kubespan_test.go
pkg/resources/kubespan/peer_spec.go

Controller watches cluster Affiliates and generates KubeSpanPeerSpecs
from those which are not local node Affiliates and have KubeSpan
configuration attached.
Example:
```
$ talosctl -n 172.20.0.2 get kubespanpeerspecs
NODE         NAMESPACE   TYPE               ID                                             VERSION   LABEL                    ENDPOINTS
172.20.0.2   kubespan    KubeSpanPeerSpec   27E8I+ekrqT21cq2iW6+fDe+H7WBw6q9J7vqLCeswiM=   1         talos-default-worker-1   ["172.20.0.3:51820"]
```
```
$ talosctl -n 172.20.0.3 get kubespanpeerspecs -o yaml
node: 172.20.0.3
metadata:
namespace: kubespan
type: KubeSpanPeerSpecs.kubespan.talos.dev
id: mB6WlFOR66Jx5rtPMIpxJ3s4XHyer9NCzqWPP7idGRo=
version: 1
owner: kubespan.PeerSpecController
phase: running
created: 2021-09-07T19:26:35Z …
```

feat: implement KubeSpan peer generation controller

---

.drone.jsonnet
cmd/installer/cmd/image.go
go.mod
go.sum
internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway_test.go
website/content/docs/v0.13/Cloud Platforms/scaleway.md

Support scaleway cloud meta server
* Add cloud-init for scaleway
* Set ipv6 to the interface
Docs:
* https://github.com/scaleway/scaleway-sdk-go
* https://github.com/scaleway/scaleway-sdk-go/blob/master/api/instance/v1/instance_metadata_sdk.go
* https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceScaleway.py

feat: add scaleway.com cloud support

---

internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go
internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
internal/app/machined/pkg/controllers/kubespan/peer_spec.go
internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go
pkg/resources/kubespan/peer_spec.go
pkg/resources/network/link.go
pkg/resources/network/link_spec.go
pkg/resources/network/link_status.go
pkg/resources/network/link_test.go

* calculate covering IPPrefixes for the KubeSpan peer `AllowedIPs`,
check for overlap
* don't use KubeSpan IP as potential node endpoint (inception!)
* allow Wireguard config to be applied which doesn't change peer
endpoint
* support for pre-shared Wireguard peer keys
Co-authored-by: Seán C McCord <ulexus@gmail.com>

fix: multiple fixes for KubeSpan and Wireguard implementation

---

internal/pkg/etcd/etcd.go

It's confusing in base 10, as every other place prints member ID in hex.

fix: print etcd member ID in hex

---

internal/app/machined/pkg/system/services/kubelet.go

Looks like this was an error made long ago, fixed similarly for etcd
in b52b20666.
Signed-off-by: Lennard Klein <lennard.klein@eu.equinix.com>

fix: write KubernetesCACert chmodded 0400 instead of 0500

---

cmd/talosctl/cmd/talos/edit.go

The previous check only applied to `talosctl edit <type>`, but failed to
check `talosctl edit <type> <id>`.
Editing didn't work anyways, but this prevents unhelpful error messages.

fix: completely prevent editing resources other than mc

---

internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go

When `etcd` is stopped, control plane can't function anymore as API
server connects to the local etcd instance.

fix: tear down control plane static pods when etcd is stopped

---

cmd/talosctl/cmd/talos/edit.go
cmd/talosctl/cmd/talos/patch.go

It was messing up the config due to wrong context being used in patchFn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4244)

fix: patch multi nodes support

---

internal/app/machined/pkg/controllers/kubespan/peer_spec.go
internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go

This fixes the bug with host networking pods not being able to reach out
to the Kubernetes services.
This also moves any node-to-node networking over to KubeSpan link as
well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4246)

fix: add node address to the list of allowed IPs (kubespan)

---

internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go
internal/app/machined/pkg/controllers/cluster/kubernetes_push.go
internal/app/machined/pkg/controllers/k8s/endpoint.go
pkg/conditions/files.go
pkg/conditions/kubeconfig.go

The problem is that the kubelet kubeconfig gets created early, but the
actual client key and cert files are not written, so controllers spam
with scary errors that the config is not valid. This PR removes those
scary messages as we wait for the kubeconfig to be usable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4247)

chore: add a special condition to check for kubeconfig readiness

---

internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
internal/app/machined/pkg/controllers/cluster/member.go
internal/app/machined/pkg/controllers/cluster/member_test.go
internal/pkg/discovery/registry/kubernetes.go
internal/pkg/discovery/registry/kubernetes_test.go
pkg/resources/cluster/affiliate.go
pkg/resources/cluster/member.go

Fixes #4232
The result:
```
talosctl -n 172.20.0.2 get members
NODE         NAMESPACE   TYPE     ID                       VERSION   HOSTNAME                 MACHINE TYPE   OS                                           ADDRESSES
172.20.0.2   cluster     Member   talos-default-master-1   2         talos-default-master-1   controlplane   Talos (v0.13.0-alpha.0-13-gfdd80a12-dirty)   ["172.20.0.2","fdd1:f54:2697:3902:44f8:92ff:fe2e:1aea"]
172.20.0.2   cluster     Member   talos-default-worker-1   1         talos-default-worker-1   worker         Talos (v0.13.0-alpha.0-13-gfdd80a12-dirty)   ["172.20.0.3","fdd1:f54:2697:3902:d4ba:55ff:fe8a:f551"]
172.20.0.2   cluster     Member   talos-default-worker-2   1         talos-default-worker-2   worker         Talos (v0.13.0-alpha.0-13-gfdd80a12-dirty) …
```

feat: add operating system version field to discovery

---

pkg/machinery/config/types/v1alpha1/generate/generate.go

This field is not marshalable, as it's technically an interface.
This will be used to save/load SecretsBundle as a whole in the CABPT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4269)

fix: don't marshal clock with SecretsBundle

---

pkg/machinery/config/types/v1alpha1/generate/generate.go

This field is not marshalable, as it's technically an interface.
This will be used to save/load SecretsBundle as a whole in the CABPT.
(cherry picked from commit 1cb9f282b541505f2d61ae0a57655cba9ae62843)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4271)

backport: fix: don't marshal clock with SecretsBundle

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/kubelet.go

Kubelet creates symlinks from /var/log/containers/<pod>.log to the log file /var/log/pod/<pod-folder>/0.log
Log senders (like fluentd) usualy watch the folder /var/log/containers/*.log
Kubelet needs to share **containers** folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4273)

fix: containerd log symlink

---

cmd/installer/cmd/image.go
go.mod
go.sum
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

Update `go-blockdevice` library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4280)

fix: use readonly mode when probing devices with `All` lookup

---

internal/app/machined/pkg/controllers/network/operator/dhcp6.go

Check that dhcpv6.Options.FQDN() is not nil before trying to use it.
This fixes DHCPv6 on GCP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4284)

fix: check for existence of dhcp6 FQDN first

---

go.mod
go.sum

This should fix lookup of CD-ROM devices.
Update `go-blockdevice` library to the version with the fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4282)

fix: find devices without partition table

---

internal/app/machined/pkg/controllers/secrets/api.go
pkg/grpc/gen/remote.go
pkg/grpc/middleware/auth/basic/basic.go
pkg/machinery/config/types/v1alpha1/generate/worker.go

This distributes API CA (just the certificate, not the key) to the
worker nodes on config generation, and if the CA cert is present on the
worker node, it verifies TLS connection to the trustd with the CA
certificate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4294)

fix: check trustd API CA on worker nodes

---

internal/app/machined/pkg/controllers/network/operator/dhcp6.go
internal/app/machined/pkg/controllers/secrets/api.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/grpc/gen/remote.go
pkg/grpc/middleware/auth/basic/basic.go
pkg/machinery/config/types/v1alpha1/generate/worker.go

* https://github.com/talos-systems/talos/pull/4273
* https://github.com/talos-systems/talos/pull/4284
* https://github.com/talos-systems/talos/pull/4294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4296)

backports: for 0.12.3 release

---

.drone.jsonnet
Makefile
cmd/installer/cmd/image.go
internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
website/content/docs/v0.13/Cloud Platforms/nocloud.md

https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html#datasource-nocloud
This PR helps to use some automatisation for Proxmox and other custom kvm-clouds
* cdrom version
* net version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4208)

feat: add nocloud platform support

---

go.mod
go.sum
internal/app/machined/pkg/controllers/cluster/config.go
internal/app/machined/pkg/controllers/cluster/config_test.go
internal/app/machined/pkg/controllers/cluster/discovery_service.go
internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/proto/proto.go
pkg/resources/cluster/config.go

This provides integration layer with discovery service to provide
cluster discovery (and transitively KubeSpan peer discovery).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4283)

feat: implement integration with Discovery Service

---

internal/app/machined/pkg/controllers/cluster/discovery_service_test.go

Looks like `zaptest` package when used from the goroutine (like in gRPC
server) results in a potential data race on test tear down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4299)

test: workaround race in the tests with zaptest package

---

internal/app/machined/pkg/controllers/config/k8s_control_plane.go
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
internal/app/machined/pkg/controllers/k8s/manifest_test.go
internal/app/machined/pkg/controllers/k8s/templates.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/argsbuilder/argsbuilder_args.go
pkg/argsbuilder/argsbuilder_interface.go
pkg/argsbuilder/argsbuilder_test.go
pkg/resources/config/k8s_control_plane.go

Use `argsbuilder` same way as it's used in services.
Rewrite `kubeProxy` generation code to override default args.
As a consequence of this change now flags do not have determined order
as they all come from a single merged map.
Fixes: https://github.com/talos-systems/talos/issues/4238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4292)

feat: override static pods default args by extra Args

---

internal/app/machined/pkg/controllers/secrets/api.go

This fixes a bug when after an error generating certificates controller
gets into a state of not being able to read its expected inputs
(NetworkStatus specifically).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4302)

fix: reset inputs back to initial state in secrets.APIController

---

cmd/talosctl/cmd/mgmt/config.go
go.mod
go.sum
internal/app/machined/pkg/controllers/kubespan/config.go
internal/app/machined/pkg/controllers/kubespan/config_test.go
internal/app/machined/pkg/controllers/kubespan/manager.go
internal/app/machined/pkg/controllers/kubespan/manager_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/resources/kubespan/config.go
website/content/docs/v0.13/Reference/cli.md
website/content/docs/v0.13/Reference/configuration.md

Fixes #4248
This resolves the balance between security and connectivity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4301)

feat: add an option to skip downed peers in KubeSpan

---

internal/app/machined/pkg/controllers/cluster/discovery_service.go
internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
internal/app/machined/pkg/controllers/kubespan/endpoint.go
internal/app/machined/pkg/controllers/kubespan/endpoint_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
pkg/resources/kubespan/endpoint.go
pkg/resources/kubespan/kubespan_test.go

Fixes #4250
Each KubeSpan peer sees each other KubeSpan peer endpoint as it got
connected. If the peer is behind NAT, the discovered endpoint is
different from the endpoints node knows about itself (as it punched a
hole in NAT). This discovered endpoint is pushed to the discovery
service so that every other peer now can use that punched hole to talk
to the peer.
If the endpoint observed is actually in the list of the endpoints
reported by the peer itself, discovery service will take care of
deduplicating them and suppressing updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4304)

feat: harvest discovered endpoints and push them via discovery svc

---

Makefile
pkg/machinery/constants/constants.go

This also updates runc to 1.0.2, libseccomp to 2.5.2.
See also https://github.com/containerd/containerd/releases/tag/v1.5.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4308)

feat: update containerd to 1.5.6

---

internal/app/machined/pkg/controllers/network/platform_config.go
internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go

Also ignore expected errors for other platforms to keep controller from
failing over and over again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4310)

fix: ignore 404 for AWS external IPs

---

Makefile
pkg/machinery/constants/constants.go

This backports a change from 0.13.
See https://github.com/containerd/containerd/releases/tag/v1.5.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4315)

backport: feat: update containerd to 1.5.6

---

.drone.jsonnet

We use hacked version with a workaround for capability issues with
`--privileged` in Docker.
See moby/moby#42906
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4329)

chore: update docker image in the pipeline

---

internal/app/machined/pkg/adapters/perf/cpu.go
internal/app/machined/pkg/adapters/perf/mem.go
internal/app/machined/pkg/adapters/perf/perf.go
internal/app/machined/pkg/controllers/perf/perf.go
pkg/resources/.importvet.yaml
pkg/resources/perf/cpu.go
pkg/resources/perf/mem.go

This PR introduces the concept of the resource adapter: something which
wraps core resource (which defines presentation) and adds additional
fatures to it which we don't want to have in `pkg/machinery` in the
future, but at the same time there's value in keeping it next to the
resource itself.
If the concept looks good, I will continue doing it same way for other
resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4469)

refactor: get rid of prometheus/procfs dependency in pkg/resources

---

cmd/talosctl/cmd/talos/support.go

`gopls` automatic importer always includes yaml.v2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4505)

fix: do not use yaml.v2 in the support cmd

---

internal/app/machined/pkg/system/mocks_test.go
internal/app/machined/pkg/system/runner/containerd/containerd.go
internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/app/machined/pkg/system/runner/goroutine/goroutine.go
internal/app/machined/pkg/system/runner/goroutine/goroutine_test.go
internal/app/machined/pkg/system/runner/process/process.go
internal/app/machined/pkg/system/runner/process/process_test.go
internal/app/machined/pkg/system/runner/restart/restart.go
internal/app/machined/pkg/system/runner/restart/restart_test.go
internal/app/machined/pkg/system/runner/runner.go
internal/app/machined/pkg/system/service_runner.go
internal/pkg/containers/containerd/containerd_test.go
internal/pkg/containers/cri/cri_test.go
internal/pkg/cri/cri_test.go

That context is not actually used.
Discovered by new golangci-lint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4506)

chore: remove unused parameters

---

internal/pkg/ntp/ntp.go

I don't think this is going to fix time issues, so just a small cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4468)

fix: clear time adjustment error when setting time to specific value

---

pkg/follow/follow_test.go

Fixes: https://github.com/talos-systems/talos/issues/4518
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4520)

fix: wait for follow reader to start before writing to the file

---

cmd/talosctl/cmd/mgmt/cluster/create.go

`strconv.ParseInt` always returns error for bitSize -1.
Found by the latest golangci-lint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4522)

fix: parse partition size correctly

---

internal/pkg/ntp/consts.go
internal/pkg/ntp/ntp.go
internal/pkg/ntp/ntp_test.go

Fixes #4425
* add more logging for responses and sync process
* adjust time sync constants
* change the way poll interval is chosen (increasing on good sync,
decreasing on variation)
* filter out spikes
Based on flow in https://github.com/systemd/systemd/blob/main/src/timesync/timesyncd-manager.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4521)

fix: improve NTP sync process

---

.drone.jsonnet

Canal latest is broken right now:
https://github.com/projectcalico/cni-plugin/issues/1214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4527)

test: disable e2e-misc test with Canal CNI

---

go.mod
go.sum
pkg/cluster/sonobuoy/sonobuoy.go

`replace` should be removed when v0.55.1+ is released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4528)

fix: use temporary sonobuoy version

---

website/content/docs/v0.14/Guides/resetting-a-machine.md
website/content/docs/v0.14/Learn More/architecture.md

Fixes #4512
- Add Talos partitions info
- Document `--system-labels-to-wipe` flag for `talosctl reset`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4529)

docs: add Talos partions info

---

go.mod
go.sum
hack/release.toml
internal/app/machined/pkg/system/services/kubelet.go
internal/integration/cli/config.go
internal/integration/cli/services.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
pkg/machinery/go.mod
pkg/machinery/go.sum
website/content/docs/v0.14/Reference/configuration.md

Fixes #4407 fixes #4489
This PR started by enabling simple restart of the `kubelet` service via
services API, but it turned out there's a problem:
When kubelet restarts, CNI is already up, so there's an interface on the
host with CNI node IP, the code which picks kubelet node IP finds it and
tries to add it to the list of kubelet node IPs which completely breaks
kubelet.
Solution was easy: allow node IPs to be filtered out - e.g. we never
want kubelet node IP to be from the pod CIDR.
But this filtering feature is also useful in other cases, so I added
that as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-system …

feat: allow kubelet to be restarted and provide negative nodeIP subnets

---

Makefile
internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt

The recent PI OS came with a default turbo-mode clock increase for newer PI4s. (https://www.raspberrypi.com/news/bullseye-bonus-1-8ghz-raspberry-pi-4/)
Check your model with:
`talosctl -n <node> read /sys/firmware/devicetree/base/model`
if it says:
`Raspberry Pi 4 Model B Rev 1.4`
This change will bring your boost clockspeed to `1800000`
To check your increase of this feature execute:
`talosctl -n <node> read /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq`
Please merge first PR : https://github.com/talos-systems/pkgs/pull/353
Signed-off-by: Nico Berlee <nico.berlee@on2it.net>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4537)

perf: raspberry PIs clockspeed as fast as firmware allows

---

internal/app/machined/pkg/adapters/cluster/cluster.go
internal/app/machined/pkg/adapters/cluster/identity.go
internal/app/machined/pkg/adapters/cluster/identity_test.go
internal/app/machined/pkg/adapters/k8s/k8s.go
internal/app/machined/pkg/adapters/k8s/manifest.go
internal/app/machined/pkg/adapters/k8s/manifest_test.go
internal/app/machined/pkg/adapters/k8s/static_pod.go
internal/app/machined/pkg/adapters/k8s/static_pod_status.go
internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
internal/app/machined/pkg/controllers/cluster/node_identity.go
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
internal/app/machined/pkg/controllers/k8s/extra_manifest.go
internal/app/machined/pkg/controllers/k8s/extra_manifest_test.go
internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
internal/app/machined/pkg/controllers/k8s/manifest.go
internal/app/machined/pkg/controllers/k8s/manifest_apply.go
internal/app/machined/pkg/controllers/k8s/manifest_test.go
internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go
pkg/resources/.importvet.yaml
pkg/resources/cluster/identity.go
pkg/resources/k8s/manifest.go
pkg/resources/k8s/static_pod.go
pkg/resources/k8s/static_pod_status.go

This continues the process of removing extra dependencies before moving
`pkg/resources` into machinery.
See also: #4420 #4469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4524)

refactor: remove pkg/resources dependencies on k8s and base62

---

.drone.jsonnet
hack/test/e2e-qemu.sh

This fixes the issue with kubelet picking up wrong IP on restart, as
Talos doesn't know pod IPs (Cilium is using its own pod CIDR, it doesn't
look up Kubernetes settings).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4546)

test: set proper pod CIDR for Cilium tests

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go

We don't expect to kexec on these actions, so no need to run kexec which
might fail blocking those two actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4549)

fix: don't run kexec prepare on shutdown and reset

---

internal/app/machined/pkg/system/services/kubelet.go

As now Talos picks up node IPs by default, we need to make sure kubelet
never picks up the VIP as the node IP.
This issue doesn't show up with HA control plane nodes, as Talos
releases VIP when kubelet restarts, but with single-node control plane
nodes VIP stays on the node (as there's nowhere to  move it to), so we
need to filter the VIP out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4550)

fix: ignore virtual IP as kubelet node IPs

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

This seems to happen on some versions of Raspberry PI, and we want Talos
to degrade gracefully to regular reboot vs. using `kexec`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4552)

fix: ignore EBUSY from `kexec_file_load`

---

pkg/kubernetes/kubernetes.go

Fixes #4557
When running `reset` for a node which was already deleted from
Kubernetes, we should ignore failure to cordon and proceed with other
actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4558)

fix: ignore not existing nodes on cordoning

---

Dockerfile
hack/containerd.toml
hack/cri-containerd.toml
internal/app/machined/pkg/system/services/containerd.go

Solve warning message at boot time: failed to load plugin io.containerd.internal.v1.opt
This is part of PR #3975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4547)

fix: containerd failed to load plugin

---

internal/app/machined/pkg/system/services/etcd.go

Fixes #4563 
This fixes an issue when `etcd` get stuck in `Pre` state so that even
`bootstrap` request doesn't kill it. This looks like a cluster which
fails to bootstrap itself and get stuck on reboot.
Even though `Watch()` aborts on cancel, channel recieve will block
forever as no events are delivered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4564)

fix: unblock events watch on context cancel

---

go.mod
go.sum
hack/release.toml
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
internal/integration/cli/config.go
internal/integration/cli/services.go
pkg/kubernetes/kubernetes.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
pkg/machinery/go.mod
pkg/machinery/go.sum
website/content/docs/v0.13/Reference/configuration.md

- #4549 
- #4531 
- #4550 
- #4558 
- #4564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4570)

backports for 0.13.3

---

cmd/talosctl/cmd/mgmt/cluster/create.go
go.mod
go.sum
internal/app/machined/internal/install/install.go
internal/app/machined/pkg/controllers/siderolink/manager.go
internal/app/machined/pkg/controllers/siderolink/manager_test.go
internal/app/machined/pkg/controllers/siderolink/siderolink.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
pkg/machinery/constants/constants.go
pkg/provision/providers/qemu/node.go
pkg/provision/request.go
website/content/docs/v0.14/Reference/cli.md

Related to #4448
The only remaining part is filtering out SideroLink addresses when Talos
looks for a node address.
See also https://github.com/talos-systems/siderolink/pull/2
The way to test it out:
```
$ talosctl cluster create ... --extra-boot-kernel-args
siderolink.api=172.20.0.1:4000
```
(where 172.20.0.1 is the bridge IP)
Run `siderolink-agent` (test implementation):
```
$ sudo _out/siderolink-agent-linux-amd64
```
Now on the host, there should be a `siderolink` Wireguard userspace
tunnel:
```
$ sudo wg
interface: siderolink
public key: 2aq/V91QyrHAoH24RK0bldukgo2rWk+wqE5Eg6TArCM=
private key: (hidden)
listening port: 51821
peer: Tyr6C/F3FFLWtnzqq7Dsm54B40bOPq6++PTiD/zqn2Y=
endpoint: 172.20.0.1:47857
allowed ips: fdae:41e4:649b:9303:b6db:d99c:215e:dfc4/128
latest handshake: 2 …
```

feat: provide SideroLink client implementation

---

internal/app/machined/pkg/system/runner/containerd/containerd.go
internal/app/machined/pkg/system/runner/containerd/opts.go
internal/app/machined/pkg/system/runner/runner.go
internal/app/machined/pkg/system/services/kubelet.go

Fixes #4571
Allow two new sysctls in addition to default seccomp profile to fix
cephfs mounts in the kubelet container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4572)

fix: allow add_key and request_key in kubelet seccomp profile

---

go.mod
go.sum
internal/pkg/mount/system.go

Related to: https://github.com/talos-systems/go-blockdevice/issues/51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4566)

fix: properly handle empty blockdevice in the installer

---

go.mod
internal/app/machined/pkg/controllers/network/operator_spec.go
internal/app/machined/pkg/controllers/network/operator_spec_test.go

Fixes #4567
This is not a complete fix, but rather a workaround: if the DHCP4 operator
panics, Talos shouldn't crash on `machined` unhandled panic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4581)

fix: catch panics in network operator runs

---

website/content/docs/v0.14/Cloud Platforms/gcp.md
website/content/docs/v0.14/Cloud Platforms/gcp/config.yaml
website/content/docs/v0.14/Cloud Platforms/gcp/gcp-ccm.yaml
website/content/docs/v0.14/Cloud Platforms/gcp/talos-ha.jinja

Update docs to reflect deploying GCP Cloud Control Manager (CCM)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4513)

feat: add GCP ccm

---

internal/app/machined/pkg/system/services/kubelet.go

In Talos 0.13 we introduced a way to pick kubelet's node IP via machine
configuration, and later enforced that Talos picks up node IPs
automatically on boot (which got backported to 0.13.x).
The problem is that if the node has multiple IPv4/IPv6 addresses, Talos
builds broken configuration by default (with multiple `--node-ip` of the
same family) which won't let the kubelet start.
To fix the multiple addresses issue, one has to apply machine
configuration changes to pick just a single subnet.
To make matters worse, Talos 0.12.x won't accept any `nodeIP` machine
config setting (as it's not supported yet in 0.12), so upgrading to 0.13
leaves the node in a non-functional state.
The fix is to pick just a single IP of each family on Talos side and
print a warning to make sure user knows that …

fix: leave only a single IPv4/IPv6 address as kubelet's node IP

---

internal/app/machined/main.go
internal/app/machined/pkg/runtime/drainer.go
internal/app/machined/pkg/runtime/drainer_test.go

Because of the bug Drainer never worked properly, as `shutdown` channel
wasn't initialied.
Also add unit-tests and add some small clean-ups which don't affect
functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4598)

fix: initialize Drainer properly

---

internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go

`kexec` doesn't bring much benefit to Raspberry PI 4, as boot sequence
is anyways pretty fast.
It looks like `kexec` is broken with many UEFI/firmware versions, and
even if it works properly, it doesn't properly re-initialize HDMI
output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4608)

fix: disable kexec on RPi4

---

go.mod
go.sum
internal/app/machined/pkg/controllers/runtime/kmsg_log_test.go

No functional changes, just better tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4615)

refactor: use random port listener in kernel log delivery tests

---

go.mod
go.sum
internal/app/machined/pkg/controllers/network/node_address.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
internal/app/trustd/main.go
internal/pkg/etcd/certs.go
pkg/machinery/go.mod
pkg/machinery/go.sum
pkg/machinery/resources/network/ula.go

As SideroLink addresses are ephemeral and point-to-point, filter them
out for node addresses, Kubelet, etcd, etc.
Fixes #4448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4617)

feat: filter out SideroLink addresses by default

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/cri.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/machinery/constants/constants.go

This changes helps kubelet/control-plane to collect resource metrics.
And kubelet can start eviction process at right moment.
* move kubelet process to special cgroup /podruntime/kubelet
* all cri containerd-shim-* proccesses will use cgroup /podruntime/runtime
* cgroup /system will store only Talos processes + etcd
I've set system reservation:
* cpu - 50m
* memory - 128mb usually Talos uses ~100Mb
* disk - 256Mi this is enough to store/recreate custom files from machineconfig
* pids - 100
Source documentation https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-allocatable.md
result:
```shell
1	0::/init		/sbin/init
1072	0::/system/runtime		/bin/containerd --address /system/run/containerd/containerd.sock --state /system/run/containerd --root …
```

feat: move kubelet/cri proccesses from system cgroup

---

.drone.jsonnet
Dockerfile
Makefile
hack/release.toml

Fixes #4640 
The `installer` image is used for inital install and upgrades, so it
contains only Talos artifacts for the same arch as the image
The `imager` image is used to produce Talos images, so it contains artifacts
for all arhitectures, so that it's possible e.g. to build Raspberry PI
Talos image on amd64 machine
Unpacked size comparison for amd64 (before this change, size of
`installer` was same as `imager` size):
```
REPOSITORY                               TAG                                      IMAGE ID       CREATED         SIZE
ghcr.io/smira/installer                  v0.14.0-alpha.2-8-g73293bc2-dirty        264995cf56df   4 minutes ago   176MB
ghcr.io/smira/imager                     v0.14.0-alpha.2-8-g73293bc2-dirty        3ba8e0176565   6 minutes ago   616MB
```
As the …

feat: split installer and imager images

---

hack/test/e2e-capi.sh
hack/test/e2e-gcp.sh

This PR will use the latest templates for v1alpha4 and the supporting
CAPI provider versions. We'll bump again when we land v1beta1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4631)

test: uplift capi versions and templates

---

internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
internal/app/machined/pkg/controllers/runtime/kernel_param_defaults_test.go
internal/app/machined/pkg/controllers/runtime/kernel_param_spec.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
internal/integration/cli/support.go
pkg/machinery/resources/runtime/kernel_params_spec.go

Fixes: https://github.com/talos-systems/talos/issues/4385
Now sysctls defined in the config can override kernel args defined by
defaults controller.
In that case controller shows the warning that tells which param was
overridden, new value and tells that it is not recommended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4636)

feat: allow overriding KSPP kernel parameters

---

Makefile
hack/release.sh
hack/release.toml

This also pulls in RPi hw support.
Fixes #4491
See:
* https://github.com/talos-systems/tools/pull/161
* https://github.com/talos-systems/pkgs/pull/365
* https://github.com/talos-systems/pkgs/pull/366
* https://github.com/talos-systems/extras/pull/32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4643)

chore: update Go to 1.17.4

---

hack/cri-containerd.toml
internal/pkg/containers/image/image.go
pkg/cli/formatters.go

See https://github.com/containerd/cri/pull/1543
Fixes #4274
Fix is applied on two levels:
* for Talos-initiated pulls, update API call
* for Kubernetes-initiated pulls, update CRI plugin config
Comparison of `/var` usage before/after, as reported by
`talosctl mounts` (in GiB):
|              | before | after |
|--------------|:------:|------:|
| controlplane |  1.98  |  1.74 |
| worker       |  1.17  |  1.01 |
(this is on freshly bootstrapped but otherwise empty cluster)
It's hard to measure effect on pulls to system containerd, like
`installer` image, as it's ephemeral, but it should also reduce space
usage in `tmpfs`.
Also fixes output of `talosctl mounts`.
---
This change is [<img …

fix: drop unpacked layers from containerd image store

---

internal/pkg/mount/pseudo.go

Tmpfs uses shared mamory. The owner of it is system cgroup.
It can be broke the system, put the big file on it.
* set mount options to /tmp, /run folder as many OS have.
* limit /tmp size to 64Mb.
PS. May be Talos should set limit to /system folder too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4645)

fix: tmpfs default permissions

---

cmd/talosctl/cmd/root.go
cmd/talosctl/cmd/talos/config.go
cmd/talosctl/cmd/talos/get.go
cmd/talosctl/cmd/talos/output/output.go
cmd/talosctl/cmd/talos/support.go
website/content/docs/v0.14/Reference/cli.md

Makes `talosctl` autocomplete the most used dynamic positional parameters like resource definitions, IDs of resource definitions, and also values for arguments like `--nodes` and `--context`.
As a CLI user I want uninterruptible flow of typing, not wanting to CTL-C in the middle of the command because I forgot how the resource definition was called, not knowing the node ip anymore or forgot the config context name. This commit fixes this all by simply tab-bing thru all the options.
This is my first substantional amount of go lines. Please be critical. I want to do this the right way, this is how I learn... I won't be able to learn if you are lenient.
Potential problems:
- CompleteNodes is `get.po`, maybe it should be moved to `completion.go` but it will come with a lot of includes and …

feat: autocomplete nodes, context and resource definitions

---

internal/app/machined/pkg/system/services/etcd.go
pkg/machinery/constants/constants.go

Fixes #4626
On bare metal, booting machines might take a long time to go through the
whole BIOS boot sequence, or pulling images might take considerably
longer than expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4658)

fix: increase boot and etcd join timeouts

---

pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go

Fixes #4463
Talos supports hostnames as Wireguard endpoints in the runtime, as it
will try resolving to a IP:port before sending to Wireguard.
But config validation shouldn't try to resolve the hostname.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4657)

fix: relax validation for wireguard endpoints

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/runtime/sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go

Fixes #4587
The gist is removing `ApplyConfiguration` sequence and refactoring whole
flow.
We can break down any `ApplyConfiguration` mode into following steps:
* validate incoming config
* apply dynamic config patches (we should get rid of these eventually)
* write down the config to `/state`
If we run in `--immediate` mode, we should also apply configuration
in-memory immediately.
If we run in default mode (apply with reboot), we should actually reboot
the machine (equivalent of `talosctl reboot`), no matter if the
sequencer is stuck in the boot sequence right now.
This fixes mostly apply with reboot mode with following changes:
* machine config is no longer applied in memory (it should be only
applied after a reboot)
* sequence reboot runs with take over, so it overrides sequencer …

fix: make `apply-config` work reliably in any Talos state

---

website/content/docs/v0.14/Reference/kernel.md

This is a non-obvious way to set up initial networking when DHCP doesn't
work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4668)

docs: document `ip=` kernel argument

---

internal/app/machined/pkg/controllers/cluster/cluster.go
internal/app/machined/pkg/controllers/cluster/discovery_service.go
internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
internal/app/machined/pkg/controllers/cluster/kubernetes_pull.go

Cleanup affiliates when registries are disabled
Fixes #4290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4671)

fix: cleanup affiliates

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_time.go
internal/integration/cli/time.go

This fixes simple bug:
```
$ talosctl -n 172.20.0.2 time
error fetching time: 1 error occurred:
* 172.20.0.2: rpc error: code = Unknown desc = no time servers configured
```
After the change:
```
$ talosctl -n 172.20.0.2 time
NODE         NTP-SERVER     NODE-TIME                                 NTP-SERVER-TIME
172.20.0.2   pool.ntp.org   2021-12-10 14:25:38.871656717 +0000 UTC   2021-12-10 14:25:38.92119139 +0000 UTC
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4674)

fix: use default time servers in time API if none are configured

---

go.mod
go.sum
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/go.mod
pkg/machinery/go.sum

We used it only once, but the library compiles many regexps as global
variables which we don't need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4689)

chore: remove govalidator library

---

go.mod
go.sum
pkg/machinery/go.mod
pkg/machinery/go.sum

See
* https://github.com/talos-systems/go-blockdevice/pull/53
* https://github.com/talos-systems/go-blockdevice/pull/54
* https://github.com/talos-systems/talos/issues/4686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4691)

refactor: use updated go-blockdevice library with allocation fixes

---

pkg/machinery/config/decoder/decoder.go
pkg/machinery/config/decoder/decoder_test.go
pkg/machinery/config/decoder/testdata/controlplane.yaml
pkg/machinery/config/decoder/testdata/worker.yaml
pkg/machinery/config/decoder/unknown_keys.go

Fixes #4687 
This avoids doing multiple rounds of marshal/unmarshal to check for
unknown keys.
New version simply walks the type tree of the `*v1alpha1.Config` and
maps that to the values in YAML.
Benchmark result comparing old and new implementations:
```
~/go/bin/benchstat old.txt new.txt                  7.9s  Ср 15 дек 2021 21:32:00
name                      old time/op    new time/op    delta
DecoderV1Alpha1Config-16    7.83ms ± 7%    0.98ms ±22%  -87.50%  (p=0.008 n=5+5)
name                      old alloc/op   new alloc/op   delta
DecoderV1Alpha1Config-16    6.39MB ± 0%    0.24MB ± 0%  -96.24%  (p=0.008 n=5+5)
name                      old allocs/op  new allocs/op  delta
DecoderV1Alpha1Config-16     25.7k ± 0%      2.4k ± 0%  -90.55%  (p=0.008 n=5+5)
```
Signed-off-by: Andrey …

refactor: rewrite the check for unknown keys in the machine configuration

---

cmd/talosctl/cmd/talos/get.go
cmd/talosctl/cmd/talos/output/table.go
go.mod
go.sum
internal/app/resources/server.go
pkg/machinery/go.mod
pkg/machinery/go.sum
pkg/machinery/resources/runtime/kernel_params_status.go
pkg/machinery/resources/runtime/mount_status.go
website/content/docs/v0.14/Reference/cli.md

Fixes #4396 
See https://github.com/cosi-project/runtime/pull/60
Sample:
```
ID                                                ALIASES
addressspecs.net.talos.dev                        addressspec as
addressstatuses.net.talos.dev                     address addresses addressstatus as
affiliates.cluster.talos.dev                      affiliate
apicertificates.secrets.talos.dev                 apicertificate ac acs
certsans.secrets.talos.dev                        certsan csan csans
cpustats.perf.talos.dev                           cpustat cpus
discoveryconfigs.cluster.talos.dev                discoveryconfig dc dcs
endpoints.kubernetes.talos.dev                    endpoint
etcdrootsecrets.secrets.talos.dev                 etcdrootsecret ers
etcdsecrets.secrets.talos.dev …
```

feat: show human-readable aliases in `talosctl get rd`

---

internal/integration/base/run.go
internal/integration/cli/time.go
internal/pkg/miniprocfs/testdata/1920080/exe
internal/pkg/miniprocfs/testdata/3731034/exe

As `talosctl time` relies on default time server set in the config, and
our nodes start with `pool.ntp.org`, sometimes request to the timeserver
fails failing the tests.
Retry such errors in the tests to avoid spurious failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4702)

test: retry `talosctl time` call in the tests

---

go.mod
go.sum
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
pkg/machinery/go.mod
pkg/machinery/go.sum

Due to using same config value for comparison and rewriting patched
configs, immediate apply mode was always no-op.
Fix that by properly deep copying the config.
Bug was only introduced in `master` with refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4706)

fix: config apply immediate

---

pkg/cluster/sonobuoy/product.go
pkg/cluster/sonobuoy/sonobuoy.go

Sonobouy once again changed the API in a way that breaks our tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4717)

fix: pass path to conformance retrieve results

---

website/content/docs/v0.13/Introduction/getting-started.md
website/content/docs/v0.13/Introduction/quickstart.md
website/content/docs/v0.14/Introduction/getting-started.md
website/content/docs/v0.14/Introduction/quickstart.md
website/content/docs/v0.15/Introduction/getting-started.md
website/content/docs/v0.15/Introduction/quickstart.md

Resolves #4704 
This PR updates the `quickstart` and `getting-started` pages for `v0.13` and `v0.14` to show download options for `arm64` 
The `talosctl` is available as a `arm64` binary but this is not yet publicated in the `getting-started` or `quickstart` documentation pages. To use the native version this PR adds this option in the docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4705)

Add arm64 option to talosctl download docs

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go

This means that Talos no longer tries to change the machine
configuration on the fly.
Certificate SANs are already handled automatically by COSI controllers,
so the only remaining part is the platform's hostname which was written
back to machine configuration.
In the follow-up PRs we'll provide better interface for platforms to
provide network-related data.
Fixes #4597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4733)

feat: remove `ApplyDynamicConfig`

---

website/content/docs/v0.12/Guides/troubleshooting-control-plane.md
website/content/docs/v0.13/Guides/troubleshooting-control-plane.md
website/content/docs/v0.14/Guides/troubleshooting-control-plane.md
website/content/docs/v0.15/Guides/troubleshooting-control-plane.md

It references legacy `BootstrapStatus` which was removed with the
dropped support for bootkube-based control plane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4738)

docs: fix troubleshooting guide

---

.drone.jsonnet
Makefile

Instead, build all images for a release and in the integration pipeline
which is triggered `nightly` and can be promoted to with
`/promote integration-images`.
This saves time and resources on regular builds.
Fixes #4410 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4737)

test: don't build all images in the default CI pipeline

---

cmd/talosctl/cmd/talos/read.go
internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/controllers/runtime/kernel_module_spec.go

Add `cat` alias for `talosctl read`, I always end up writing
`talosctl cat`.
Improve error messages for APIs available only on control plane nodes:
was:
```
$ talosctl -n 172.20.0.5 kubeconfig
rpc error: code = Unknown desc = error getting Kubernetes CA: failed to parse PEM block
error initializing gzip: EOF
$ talosctl -n 172.20.0.5 etcd members
error getting members: 1 error occurred:
* 172.20.0.5: rpc error: code = Unknown desc = error building etcd client TLS config: open /system/secrets/etcd/admin.crt: no such file or directory
```
now:
```
$ talosctl -n 172.20.0.6 kubeconfig
rpc error: code = Unimplemented desc = kubeconfig is only available on control plane nodes
error initializing gzip: EOF
$ talosctl -n 172.20.0.6 etcd remove-member foo
1 error occurred:
* 172.20.0.6: rpc error: …
```

fix: multiple usability fixes

---

Makefile
internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt
internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go

Fixes kexec on RPI4
Since BL31 is now enabled `talosctl shutdown` puts the Pi in a low power state instead of rebooting
Ref: https://github.com/talos-systems/pkgs/pull/375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4742)

fix: kexec on RPI4

---

go.mod
go.sum
internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go

These are I guess artifacts from the time Talos tried to auto-detect the
platform it is running on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4743)

chore: remove unused methods in AWS platform

---

internal/app/machined/pkg/controllers/runtime/kernel_module_spec.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/integration/api/discovery.go

Sometimes pushing/pulling to Kubernetes registry is delayed due to
backoff on failed attempts to talk to the API server when the cluster is
still bootstrapping. Workaround that by adding retries.
Also disable kernel module controller in container mode, as it will keep
always failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4746)

test: retry in discovery tests

---

cmd/talosctl/cmd/talos/edit.go
cmd/talosctl/pkg/mgmt/helpers/wireguard.go
internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
internal/app/machined/pkg/runtime/v1alpha1/platform/packet/packet.go
internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
internal/integration/api/apply-config.go
pkg/cluster/kubernetes/detect.go
pkg/cluster/kubernetes/kubelet.go
pkg/cluster/kubernetes/patch.go
pkg/machinery/config/configloader/configloader.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_configurator_bundle.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_readonly_provider.go
pkg/machinery/resources/config/machine_config.go
pkg/machinery/resources/config/machine_config_test.go
pkg/provision/providers/docker/node.go
pkg/provision/providers/qemu/node.go

Talos shouldn't try to re-encode the machine config it was provided
with.
So add a `ReadonlyWrapper` around `*v1alpha1.Config` which makes sure
that raw config object is not available anymore (it's a private field),
but config accessors are available for read-only access.
Another thing that `ReadonlyWrapper` does is that it preserves the
original `[]byte` encoding of the config keeping it exactly same way as
it was loaded from file or read over the network.
Improved `talosctl edit mc` to preserve the config as it was submitted,
and preserve the edits on error from Talos (previously edits were lost).
`ReadonlyWrapper` is not used on config generation path though - config
there is represented by `*v1alpha.Config` and can be freely modified.
Why almost? Some parts of Talos (platform code) …

feat: make machine configuration read-only in Talos (almost)

---

go.mod
go.sum
internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go

This provides a better way to access IMDS APIs (new IMDS API version,
etc.)
Using `aws-go-sdk` vs. new `aws-go-sdk-v2` as `go-getter` depends on
`v1` version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4747)

refactor: use AWS SDK to access AWS metadata service

---

pkg/machinery/config/types/v1alpha1/bundle/bundle.go

Resolves  #4362
Signed-off-by: Eric Wohltman <eric.wohltman@gmail.com>
When running `talosctl cluster create --input-dir` using files created from `talosctl gen config`, an error occurs because `cluster create` expects an `init.yaml` file which `gen config` does not create.
```
$ talosctl version --client
Client:
Tag:         v0.14.0
SHA:         675dee0e
Built:
Go version:  go1.17.5
OS/Arch:     linux/amd64
$ talosctl gen config talos-default https://10.5.0.2:6443 --output-dir /tmp/talos --additional-sans 127.0.0.1 --registry-mirror '*'=http://10.5.0.1:6000 --config-patch '[{"op":"add", "path": "/cluster/network/cni", "value": {"name": "none"}}]'
generating PKI and tokens
created /tmp/talos/controlplane.yaml
created /tmp/talos/worker.yaml
created /tmp/talos/talosconfig
$ talosctl cluster …
```

fix: ignore missing init.yaml for cluster create

---

Dockerfile
internal/app/machined/pkg/adapters/cluster/identity.go
internal/app/machined/pkg/adapters/cluster/identity_test.go
internal/app/machined/pkg/controllers/cluster/node_identity.go
internal/app/machined/pkg/controllers/cluster/node_identity_test.go
internal/app/machined/pkg/controllers/k8s/kubelet_service.go
internal/app/machined/pkg/system/services/kubelet.go

Fixes #4759
This uses existing features: Talos always generates 32 bytes random node
identity, we use first 16 bytes of that to generate `machine-id` in
compliant format and mount that into the `kubelet` container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4775)

fix: derive machine-id from node identity

---

hack/cleanup.sh

This removes all files but leaves `udevadm` which is actually used by
Talos.
Size reduction for `initramfs-amd64`: 54380024 -> 54228188
Files removed:
```
NODE         MODE         UID   GID   SIZE(B)   LASTMOD           NAME
172.20.0.2   drwxr-xr-x   0     0     107       Jan 10 23:46:33   .
172.20.0.2   Lrwxrwxrwx   0     0     26        Jan 10 23:46:33   iptables-xml -> /sbin/xtables-legacy-multi
172.20.0.2   -rwxr-xr-x   0     0     30496     Jan 10 23:46:33   ocspcheck
172.20.0.2   -rwxr-xr-x   0     0     442008    Jan 10 23:46:33   openssl
172.20.0.2   -rwxr-xr-x   0     0     14240     Jan 10 23:46:33   scmp_sys_resolver
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

chore: clean up /usr/bin from unneeded files

---

.drone.jsonnet
Makefile
cmd/installer/cmd/image.go
hack/release.toml
internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go
internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
website/content/docs/v0.15/Cloud Platforms/oracle.md
website/content/docs/v0.15/Introduction/support-matrix.md

Add Oracle Cloud platform.
* cloud-init for oraclecloud (IMDSv2)
* amd64/arm64 arch support
* set DHCPv6 on if IPv6 subnet allocated like in Azure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4712)

feat: add oraclecloud.com platform support

---

website/content/docs/v0.14/Virtualized Platforms/vmware.md
website/content/docs/v0.15/Virtualized Platforms/vmware.md

This PR moves to give curl commands for the vmware assets instead of
relying on the local paths that I was using. This matches what we're
doing for gcp docs as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4794)

docs: rework vmware assets

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

As wrong `error` value was used, publishing an event was causing a panic
in Talos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4796)

fix: avoid panic in config loading/validation

---

hack/release.toml
internal/app/machined/pkg/controllers/k8s/templates.go
pkg/machinery/constants/constants.go
website/content/docs/v0.15/Reference/configuration.md

Drop the rewrite rule which seems to be causing issues for
`ingress-nginx` when Kubernetes IPv4-only cluster runs in the
IPv6-enabled environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4821)

feat: update CoreDNS to 1.8.7

---

internal/app/init/main.go
internal/pkg/mount/mount.go
internal/pkg/mount/options.go
pkg/machinery/constants/constants.go
pkg/machinery/extensions/config.go
pkg/machinery/extensions/extensions.go

The list of layers should come from the `/extensions.yaml` configuration
file.
Closes: https://github.com/talos-systems/talos/issues/4814
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4828)

feat: install readonly overlay mounts during talos chroot sequence

---

internal/app/machined/pkg/controllers/runtime/kernel_param_spec.go

Fixes: https://github.com/talos-systems/talos/issues/4834
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4837)

fix: use correct error in `kernel_param_spec` Modify call handling

---

internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
internal/app/machined/pkg/controllers/k8s/kubelet_spec.go

Enforces more reasonable minimum TLS versions for Kubernetes components
(1.3 for everything except apiserver; 1.2 for API server for
interoperability).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4844)

fix: enforce reasonable TLS min tls-min-version

---

pkg/provision/providers/qemu/preflight.go

The CNI is executed on the host. Even if we want to run an arm64 qemu,
we still need to execute the amd64 CNI on the host.
Fixes https://github.com/talos-systems/talos/issues/4859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4860)

fix: qemu: always use runtime.GOARCH for CNI bundle

---

hack/cloud-image-uploader.sh
hack/fix-artifacts.sh
hack/release.sh
hack/start-registry-proxies.sh
hack/test/e2e-aws.sh
hack/test/e2e-azure.sh
hack/test/e2e-capi.sh
hack/test/e2e-docker.sh
hack/test/e2e-gcp.sh
hack/test/e2e-iso.sh
hack/test/e2e-qemu.sh
hack/test/libvirt/libvirt.sh
hack/test/provision-tests.sh
hack/test/qemu/qemu.sh

This will fix running these scripts on distros without /bin/bash, but
where bash is in $PATH, such as NixOS.
Currently, `make fmt` otherwise fails to run:
```
make[3]: Leaving directory '/home/flokli/dev/numtide/manifoldfinance/talos'
sh: ./hack/fix-artifacts.sh: /bin/bash: bad interpreter: No such file or directory
make[2]: *** [Makefile:163: local-fmt-protobuf] Error 126
make[2]: Leaving directory '/home/flokli/dev/numtide/manifoldfinance/talos'
make[1]: *** [Makefile:274: fmt-protobuf] Error 2
make[1]: Leaving directory '/home/flokli/dev/numtide/manifoldfinance/talos'
make: *** [Makefile:277: fmt] Error 2
```
Signed-off-by: Florian Klink <flokli@flokli.de>
---
This change is [<img …

fix: use #!/usr/bin/env bash as shebang instead of #!/bin/bash

---

pkg/cluster/kubernetes/talos_managed.go

Otherwise it breaks Theila, which never closes Talos clients during
operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4887)

fix: close client provider instead of Talos client in the upgrade module

---

Dockerfile
internal/app/init/main.go
internal/pkg/mount/switchroot/switchroot.go
pkg/machinery/constants/constants.go

See #4816
Depending on the hardware and firmware type, firmware might be either
needed during initial boot (`initramfs`) or in the Talos running phase
(`rootfs`). As we don't want to have two copies of same firmware, share
the firmware by bind-mounting it from the `initramfs` down to `rootfs`
on switchroot.
This also cleans up `Dockerfile` to keep firmware only in `initramfs`.
Eventually we might get rid of some of the firmware and move it to the
system extensions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4883)

feat: share `/lib/firmware` across initramfs and rootfs

---

internal/app/machined/pkg/controllers/runtime/extension_status.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
pkg/machinery/resources/runtime/extension_status.go
pkg/machinery/resources/runtime/runtime_test.go

```bash
$ talosctl -n 172.20.0.2 get extensions
NODE         NAMESPACE   TYPE              ID                                       VERSION   NAME     VERSION
172.20.0.2   runtime     ExtensionStatus   000.ghcr.io-smira-gvisor-c927b54-dirty   1         gvisor   20220117.0-v1.0.0
```
```bash
$ talosctl -n 172.20.0.2 get extensions -o yaml
node: 172.20.0.2
metadata:
namespace: runtime
type: ExtensionStatuses.runtime.talos.dev
id: 000.ghcr.io-smira-gvisor-c927b54-dirty
version: 1
owner: runtime.ExtensionStatusController
phase: running
created: 2022-01-26T20:56:51Z
updated: 2022-01-26T20:56:51Z
spec:
image: 000.ghcr.io-smira-gvisor-c927b54-dirty.sqsh
metadata:
name: gvisor
version: 20220117.0-v1.0.0
author: Andrew Rynhard
description: |
This system extension provides gVisor using containerd's …
```

feat: provide a way to list installed system extensions

---

cmd/talosctl/cmd/mgmt/cluster/create.go
pkg/provision/options.go
pkg/provision/providers/qemu/arch.go
pkg/provision/providers/qemu/node.go
pkg/provision/providers/qemu/preflight.go
website/content/docs/v0.15/Reference/cli.md

This allows specifying an additional search paths to look for UEFI firmware.
This is useful when invoking qemu in UEFI mode (either by running arm64, or by running an amd64 image with uefi enabled), but without the firmware installed in the `/usr/share/{OVMF,ovmf}` directories, or when using some custom firmware.
In the case of NixOS, this path doesn't even exist at all, so there's no way to install firmware into that location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4865)

Add --extra-uefi-search-paths option

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4890)

chore: update kernel to stable 5.15.17

---

website/content/docs/v0.14/Guides/logging.md
website/content/docs/v0.15/Guides/logging.md

As explained in https://github.com/talos-systems/talos/issues/4880#issuecomment-1022656510,
right now the recommended way to push logs to log collectors is by
running a configuring Filebeat in the local cluster, with a DaemonSet
using the host network, and pointing Talos to push logs to an UDP port
on 127.0.0.1.
I updated both v0.14 and v0.15 docs, as it should be more clear for both
versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4893)

docs: clarify Filebeat example

---

pkg/cluster/kubernetes/talos_managed.go

Update k8s upgrade message
Before:
```bash
❯ talosctl upgrade-k8s --to 1.23.3
automatically detected the lowest Kubernetes version 1.23.2
checking for resource APIs to be deprecated in version 1.23.3
discovered master nodes ["192.168.15.20"]
discovered worker nodes []
updating "kube-apiserver" to version "1.23.3"
> "192.168.15.20": starting update
> update kube-apiserver: 1.23.2 -> 1.23.3
> "192.168.15.20": machine configuration patched
> "192.168.15.20": waiting for API server state pod update
< "192.168.15.20": successfully updated
updating "kube-controller-manager" to version "1.23.3"
> "192.168.15.20": starting update
> update kube-controller-manager: 1.23.2 -> 1.23.3
> "192.168.15.20": machine configuration patched
> "192.168.15.20": …
```

chore: update k8s upgrade message

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.18 stable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4903)

chore: bump kernel to 5.15.18

---

cmd/talosctl/cmd/mgmt/cluster/create.go
cmd/talosctl/cmd/mgmt/config.go
cmd/talosctl/cmd/talos/patch.go
hack/release.toml
pkg/machinery/config/configpatcher/configpatcher_test.go
pkg/machinery/config/configpatcher/load.go
pkg/machinery/config/configpatcher/load_test.go
pkg/machinery/config/configpatcher/testdata/patch.json
pkg/machinery/config/configpatcher/testdata/patch.yaml
website/content/docs/v0.15/Guides/editing-machine-configuration.md
website/content/docs/v0.15/Reference/cli.md

Include filename content if value begins with @ (see curl for example).
Add multiple config-path option on cmdline to apply them in order.
ex:
```
talosctl-linux-amd64 gen config talos1 https://127.0.0.1:6443 --config-patch-control-plan @cidrs.json --config-patch-worker @sysctls-workders.json --config-path @cluster-name.json
```
Load JSON patch from YAML.
This applies to all commands handling config patches.
Closes: https://github.com/talos-systems/talos/issues/4764
Signed-off-by: Sébastien Bernard <sbernard@nerim.net>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4892)

feat: add multiple config patches, patches from files, YAML support

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.19 stable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4909)

chore: bump kernel to 5.15.19

---

pkg/provision/providers/docker/docker.go

This PR removes the bit where we disabled persistence for the docker
provider. Doing so allows us to do things like upgrade k8s against a
docker-based cluster for testing purposes. Tested locally and a cluster
created just fine and an `upgrade-k8s` completed successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4912)

feat: enable persistence for docker provider

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go

Shutdown sequence was refactored to support draining and force mode, but
other invocations of the shutdown sequence haven't been updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4921)

fix: pass proper sequence to shutdown sequence on ACPI shutdown

---

internal/app/machined/pkg/system/services/etcd.go

While we use properly-generated certs, it is (according to STIG 242379)
possible to allow a client to downgrade to self-signed acceptance without explicitly
disabling `auto-tls`.
This patch sets `auto-tls` to `false`, preventing the downgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4925)

fix: disable auto-tls for etcd

---

internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
internal/app/machined/pkg/controllers/runtime/kernel_param_defaults_test.go

Enables `accept_ra = 2` when IPv6 forwarding is enabled.
When IPv6 forwarding is enabled, the default `accept_ra = 1` no longer
functions.
This is intentional by the kernel developers, because routers generally should not
accept router advertisements (they supply their own).
However, in the case of a machine running Kubernetes, while IP
forwarding is enabled, the machine is still treated more as an end node
than a router.
It is common for a Kubernetes node to be configured via SLAAC and
therefore to expect to receive router advertisements, while at the same
time, IP forwarding must be enabled to handle container communication.
Fixes #3841
--- …

feat: enable accept_ra when IPv6 forwarding

---

go.mod
go.sum
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
pkg/machinery/go.mod
pkg/machinery/go.sum

Use same `talosnet` method as in the actual filtering code.
See also https://github.com/talos-systems/net/pull/9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4942)

fix: validate kubelet node IP subnets correctly

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

See #4947
The goal is to disable kexec temporarily to move on with the system
extensions, and to find the root cause and fix kexec before the next
release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4948)

feat: disable reboots via kexec

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.22 stable
Ref: https://github.com/talos-systems/pkgs/pull/391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4951)

chore: bump kernel to 5.15.22

---

go.mod
go.sum
pkg/machinery/config/types/v1alpha1/generate/generate.go

Add JSON tags so that the fields can be un-marshelled by tools like
Pulumi when creating a pulumi provider for Talos SecretsBundle,
ref: https://github.com/frezbo/pulumi-provider-talos/blob/main/provider/cmd/pulumi-resource-talos/schema.json
Ref: https://github.com/talos-systems/crypto/pull/24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4954)

chore: add json-tags for SecretsBundle

---

.drone.jsonnet
cmd/installer/pkg/install/extensions.go
internal/pkg/extensions/compress.go
internal/pkg/extensions/extensions_test.go
internal/pkg/extensions/pull.go

Fixes #4816
This changes the way system extensions are packaged into the squashfs
images: `/lib/firmware` is now moved out of the future squashfs images
and becomes part of `initramfs` to make firmware available in the early
boot.
Talos will bind-mount `/lib/firwmare` into rootfs as well, so it will be
available in the rootfs as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4904)

feat: extract firmware part of system extensions into initramfs

---

hack/test/e2e-capi.sh
internal/integration/api/discovery.go

We should always test latest versions of our providers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4956)

test: unlock CABPT/CACPPT provider versions

---

internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go

This PR changes most common tweaks.
* inotify uses for reload config files if it changed
* tcp_keepalive_* helps to refrech tcp state connections
Part of #4654
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4955)

feat: sysctl system optimization

---

Makefile

https://linux-hardware.org/?id=pci:8086-15f3-1043-87d2
Also bump tools to the version with zstd compression to match pkgs
build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4961)

chore: update the kernel with IGC driver enabled

---

Makefile

Ref: https://github.com/talos-systems/pkgs/pull/394
Kernel size also reduced by 1Meg
Before:
```bash
❯ du -sh _out/vmlinuz-amd64
16M     _out/vmlinuz-amd64
❯ file _out/vmlinuz-amd64
_out/vmlinuz-amd64: Linux kernel x86 boot executable bzImage, version 5.15.22-talos (@buildkitsandbox) #1 SMP Wed Feb 9 19:19:47 UTC 2022, RO-rootFS, swap_dev 0xF, Normal VGA
❯ du -sh _out/vmlinuz-arm64
57M     _out/vmlinuz-arm64
```
After:
```bash
❯ du -sh _out/vmlinuz-amd64
15M     _out/vmlinuz-amd64
❯ file _out/vmlinuz-amd64
_out/vmlinuz-amd64: Linux kernel x86 boot executable bzImage, version 5.15.22-talos (@buildkitsandbox) #1 SMP Thu Feb 10 18:20:11 UTC 2022, RO-rootFS, swap_dev 0xE, Normal VGA
❯ du -sh _out/vmlinuz-arm64
56M     _out/vmlinuz-arm64
```
---
This …

chore: disable TIPC and B.A.T.M.A.N

---

cmd/talosctl/cmd/mgmt/cluster/create.go
cmd/talosctl/cmd/mgmt/config.go
hack/release.toml
website/content/docs/v0.15/Reference/cli.md

Pin talos default k8s version to `talosctl gen config`
Signed-off-by: Charlie Haley <charlie.haley@hotmail.com>
The worlds smallest PR 😄
Uses the `DefaultKubernetesVersion` defined in the `constants` package as the default value for the `--kubernetes-version` flag for the `config` comand.
Fixes #4917
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4966)

chore: pin kubernetes version to `talosctl gen config`

---

internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/testdata/expected.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr.go

netaddr.Netmask changes the source ip to net clean subnet:
10.1.2.3/24 -> 10.1.2.0/24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4995)

fix: vultr define interface ip

---

internal/app/machined/pkg/controllers/network/link_merge_test.go
pkg/machinery/resources/network/link_spec.go

This solves a case when lower layer (platform) defines `bond0` as
logical interface properly, and upper layer (configuration) defines only
some part of the config (e.g. VIP).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/4999)

fix: prefer logical on merging link specs

---

cmd/installer/pkg/install/install.go

I believe it serves no purpose in GRUB config: GRUB pre-loads
`initramfs` into memory anyways, so kernel doesn't need to know, nor has
any way to load it from anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5011)

chore: don't append `initrd=` to the kernel command line

---

hack/release.toml
internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go
internal/app/machined/pkg/controllers/runtime/kernel_param_defaults_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go

Enable the kubelet's builtin kernel configuration checks.
Fixes #5002
Fixes #4990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5004)

feat: enable protectKernelDefaults in kubelet_spec

---

website/content/docs/v0.14/Guides/deploying-cilium.md
website/content/docs/v0.15/Guides/deploying-cilium.md

Expanded a little on the Talos specific Cilium deployment details.
There are some gotchas when deploying Cilium onto Talos that takes time to figure out if not documented.
https://github.com/talos-systems/talos/issues/4109 GCP ILB support / support scope local routes to be configured
https://github.com/talos-systems/talos/issues/4212 add Node.PodCIDRs to the k8s nodeadress filter
https://github.com/talos-systems/talos/issues/4654 Kernel default values (sysctl)
https://github.com/talos-systems/talos/issues/4756 Cilium Documentation Generates Clusters Without a CNI
https://github.com/talos-systems/talos/issues/4836 Kubespan and Cilium compatiblity: etcd is failing
https://github.com/talos-systems/talos/issues/4863 Cilium on talos "aoe: packet could not be sent on *. consider increasing …

Expanded Cilium deployment documentation

---

hack/release.toml
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
pkg/machinery/constants/constants.go

Instead of bundling the apiserver audit logs with the rest of the
apiserver logs, we should store them separately to file, assuring
reasonable defaults for retention and rotation.
Fixes #5000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5005)

feat: store audit logs to disk

---

hack/release.toml
pkg/machinery/config/contract.go
pkg/machinery/config/contract_test.go
pkg/machinery/config/types/v1alpha1/generate/init.go

This flips the switch in the machine config to skip PSP deployment.
See #5003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5030)

feat: disable PSP by default for Talos >= 0.15

---

website/content/docs/v0.14/Reference/kernel.md
website/content/docs/v0.15/Reference/kernel.md

Fix kernel `ip=` errata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5037)

chore: fix kernel reference errata

---

.drone.jsonnet

As `_out` is a shared volume across Drone steps, we should prefetch CLI
dependencies early, as fetching them concurrently from multiple steps
might lead to suprising results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5039)

test: pre-fetch CLI tools

---

hack/release.toml
internal/app/machined/pkg/controllers/k8s/kubelet_config.go
internal/app/machined/pkg/controllers/k8s/kubelet_config_test.go
internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
pkg/machinery/kubelet/kubelet.go
pkg/machinery/resources/k8s/kubelet_config.go
website/content/docs/v0.15/Reference/configuration.md

Fixes #4629
Note: some fields are enforced by Talos and are not overridable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5045)

feat: add a way to override kubelet configuration via machine config

---

internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/expected.yaml

Set default route to meta-server, which exists only on eth0 interface.
This changes affect dual network setup. 
In dual network solution you have to set 169.254.42.42/32 route by your self.
After that you will lost ipv6 auto configuration.
So we can set up route 169.254.42.42/32 automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5046)

fix: set route to metaserver

---

go.mod
go.sum
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/udevd.go
pkg/machinery/constants/constants.go

Set to init/sysstem processes hard memory reservation.
* init possess starts from 6Mb and grow to ~90Mb
* system processes usually use ~128Mb (with etcd)
* kubelet - 64Mb 
* cri + containerd-shim - 128Mb
When node has memory issue, init process is trying to allocate memory and get not enough memory issue.
Because this is affect the kubelet/containerd. They cannot start pod-eviction process (start very slowly). 
It also helps to gather metrics from Talos api (talosctl dashboard) or reboot the node. 
Almost ready, but I will wait this PR https://github.com/containerd/cgroups/pull/211 (merged)
--- …

Cgroup system reservation

---

Dockerfile

They haven't been actually used, it reduces initramfs size by ~600KB,
and iscsi will be re-packages as a system extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5068)

chore: remove iSCSI packages from the rootfs image

---

cmd/talosctl/cmd/talos/diskusage.go
cmd/talosctl/cmd/talos/list.go
internal/integration/cli/diskusage.go
internal/integration/cli/list.go
website/content/docs/v0.15/Reference/cli.md

Fixes: https://github.com/talos-systems/talos/issues/3018
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5060)

fix: align list and diskusage command flags with their Linux analogs

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

(backport for Talos 0.14)
See
* https://github.com/containerd/containerd/security/advisories/GHSA-crp2-qrr5-8pq7
* https://github.com/talos-systems/pkgs/pull/409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5070)

feat: update containerd to 1.5.10

---

hack/release.toml
internal/app/machined/pkg/controllers/network/cmdline.go
internal/app/machined/pkg/controllers/network/cmdline_test.go
internal/app/machined/pkg/controllers/network/link_config.go
internal/app/machined/pkg/controllers/network/network.go
pkg/machinery/constants/constants.go
website/content/docs/v1.0/Reference/kernel.md

Support bond interfaces from kernel cmdline using `bond=` format
Fixes: #4765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5078)

feat: bond interfaces from kernel cmdline

---

cmd/installer/pkg/raw.go
internal/pkg/partition/constants.go

With system extensions, size of the `initramfs` might increase
significantly. With 1000 MiB `/boot`, as we store `A` and `B` boot
directories, we have 500 MiB for each Talos boot (size of the kernel and
initramfs).
Fixes #5096
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5097)

feat: bump boot partition size to 1000 MiB

---

.drone.jsonnet

This is needed to make sure that those steps don't run in parallel on
release builds, as they write same output files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5128)

chore: add dependency images-essential -> images

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.28
ref: https://github.com/talos-systems/pkgs/pull/417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5127)

chore: bump kernel to 5.15.28

---

cmd/talosctl/cmd/talos/copy.go
cmd/talosctl/cmd/talos/diskusage.go
cmd/talosctl/cmd/talos/logs.go
cmd/talosctl/cmd/talos/restart.go
cmd/talosctl/cmd/talos/root.go
cmd/talosctl/cmd/talos/service.go

talosctl copy: path completion of src node path, dst client path was done by default
talosctl usage: directory completion of node path
talosctl logs: service completion
talosctl restart: running container/pod completion
talosctl service: service and action completion
Because I like pressing TAB
- [ unable ] you linted your code (`make lint`) -- BROKEN for me:  /toolchain/bin/bash: golangci-lint: command not found
- [ unable ] you ran unit-tests (`make unit-tests`) -- error: failed to solve: granting entitlement security.insecure is not allowed by build daemon configuration
--- …

feat: add talosctl completions to copy, usage, logs, restart and service

---

hack/release.toml
internal/app/machined/pkg/controllers/config/k8s_control_plane.go
internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
internal/app/machined/pkg/runtime/state.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_dbus.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
internal/app/machined/pkg/system/services/kubelet.go
internal/pkg/logind/broker.go
internal/pkg/logind/dbus.go
internal/pkg/logind/kubelet_mock_test.go
internal/pkg/logind/logind.go
internal/pkg/logind/logind_test.go
internal/pkg/logind/service.go
pkg/machinery/constants/constants.go

Add a mock D-Bus daemon and a mock logind implementation over D-Bus.
Kubelet gets a handle to the D-Bus socket, connects over it to our
logind mock and negotiates shutdown activities.
Fixes #3095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5108)

feat: implement D-Bus systemd-compatible shutdown for kubelet

---

internal/app/machined/pkg/controllers/k8s/kubelet_spec.go

We should skip the checks on container platforms, as Talos has no way to
enforce conditions on the host kernel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5139)

fix: invert the condition to skip kubelet kernel checks

---

internal/app/machined/pkg/controllers/network/operator_config.go
internal/app/machined/pkg/controllers/network/operator_config_test.go
internal/app/machined/pkg/controllers/network/operator_vip_config.go
internal/app/machined/pkg/controllers/network/operator_vip_config_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go

The problem is that Virtual IP operator configuration might require
accessing platform metadata server (e.g. on Equinix Metal), while
regular operator sets up critical operators like DHCP.
The issue observed on Equinix Metal without the split:
* on initial boot, DHCP is set up on `eth2`
* platform network configuration is fetched and `bond0` configuration is
created
* node IP is assigned both to `eth2` and `bond0`, while `eth2` is a
slave to `bond0`
* networking is broken
* operator config controller is stuck trying to fetch EM VIP
configuration, as the network is broken, it fails to do so, but retries
for 3 minutes (in `download.Download`)
* network is broken for 3 minutes until `OperatorConfig` controller is
unblocked and cleans up DHCP operator for `eth2` as it should
The issue here is …

fix: split regular network operation configuration and virtual IP

---

pkg/kubernetes/errors.go

This fixes `talosctl upgrade-k8s`:
```
Get "https://172.21.0.1:6443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app+%3D+kube-apiserver": read tcp 172.21.0.1:51416->172.21.0.1:6443: read: connection reset by peer
```
The error happens when the `kube-apiserver` is restarted during the
control plane upgrade, and it should be ignored as a transient error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5146)

fix: ignore connection reset errors on k8s upgrade

---

internal/app/machined/pkg/controllers/k8s/nodeip_config.go
internal/app/machined/pkg/controllers/k8s/nodeip_config_test.go

I'm not sure how I haven't noticed that before, but that is easily
reproducible with virtual IP moving between the nodes: Talos incorrectly
assumes that pod IPs might be valid kubelet node IPs, and this might
lead to unexpected results if the kubelet node IP is picked to be equal
to pod CIDR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5145)

fix: ignore pod CIDRs for kubelet node IPs

---

internal/pkg/extensions/validate.go

They should cause no harm as every extension as an image on its own, so
hardlinks are only available between the files in one image only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5162)

feat: allow hardlinks in the system extension images

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/main.go
internal/app/machined/pkg/runtime/runtime.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/integration/api/etcd-recover.go
pkg/cluster/bootstrap.go
pkg/machinery/constants/constants.go

Some failures can be fixed by updating the machine configuration.
Now `userDisks` and `userFiles` do not make Talos to enter into reboot
loop but pause for 35 minutes.
Additionally, `apid` and `machined` are now started right after
containerd is up and running.
That makes it possible for the operator to connect to the node using
talosctl and fix the config.
Fixes: https://github.com/talos-systems/talos/issues/4669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5129)

feat: pause the boot process on some failures instead of rebooting

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

This fixes a case when udev rules are first created in the machine
config and then removed from the config.
As the file is on the overlayfs, it persists over reboots, so we need to
write it every time we boot Talos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5163)

fix: clean up custom udev rules if the config is cleared

---

internal/app/machined/pkg/system/services/udevd.go

Default `--type` is `devices`, so trigger explicitly on both `devices`
and `subsystems` and use `add` action to mock initial events better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5165)

fix: trigger properly `udevd` on types and actions

---

.drone.jsonnet
Makefile
hack/test/day-two/config.yaml
hack/test/day-two/loki-values.yaml
hack/test/day-two/metallb-values.yaml
hack/test/e2e.sh

Uses Sidero Labs d2ctl to install a small sample of
common cluster services to ensure the Talos cluster
is capable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/talos-systems/talos/5160)

chore: add day-two tests for e2e-qemu

---

.conform.yaml
.drone.jsonnet
Dockerfile
Makefile
hack/release.sh
hack/release.toml
hack/test/e2e-iso.sh
hack/test/libvirt/libvirt.sh
internal/integration/provision/upgrade.go
pkg/images/list.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
pkg/machinery/constants/constants.go
website/content/v1.0/guides/adding-a-proprietary-kernel-module.md
website/content/v1.0/guides/air-gapped.md
website/content/v1.0/guides/customizing-the-kernel.md
website/content/v1.0/guides/customizing-the-root-filesystem.md
website/content/v1.0/guides/editing-machine-configuration.md
website/content/v1.0/guides/logging.md
website/content/v1.0/guides/system-extensions.md
website/content/v1.0/guides/upgrading-kubernetes.md
website/content/v1.0/guides/upgrading-talos.md
website/content/v1.0/reference/cli.md
website/content/v1.0/reference/configuration.md
website/content/v1.0/single-board-computers/jetson_nano.md

Go module import paths still use talos-systems, packages use new
siderolabs name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5183)

chore: rename github organization to siderolabs

---

website/config.toml
website/static/_redirects

This gives us doc searches, as well as redirects for latest and
docs/latest to the actual v0.14 version (until we cut 1.0).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5173)

docs: update search settings and redirects

---

website/config.toml

Adds a link to the enterprise site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5185)

docs: add enterprise link to docs header

---

hack/test/clusterctl.yaml
hack/test/e2e-capi.sh

`clusterctl init` can't follow redirects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5184)

test: use clusterctl.yaml overrides after org rename

---

website/static/_redirects

We should support old links with `/docs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5190)

docs: fix redirects for /docs URLs

---

.gitignore
website/config.toml

The config.toml for algolia doesn't do what it says on the tin. The
algolia search bar shows up without this option and enabling it somehow
adds a second search bar.
Also added the `resources/` subdir to our gitignore. This dir is
generated when doing local hugo dev.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5191)

docs: remove second search bar

---

website/layouts/partials/hooks/body-end.html

This PR adds to our templates to inject a "latest" version metadata if
the doc is indeed our latest version. This will be coupled with an algolia
facet filter to only return "latest" version results in a separate PR
after I kick a recrawl of the site once this is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5194)

docs: tag latest docs for search

---

.gitignore
website/layouts/partials/hooks/body-end.html

This PR makes sure all content gets tagged appropriately so we can be
smarter about showing relevant results.
Also added the `public` directory to the gitignore. This is created when
doing local hugo development and shouldn't be committed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5208)

docs: add algolia versions to all content

---

pkg/provision/providers/docker/docker.go

Same as OS X, we need to force endpoint to the localhost/exposed port of
the apid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5212)

fix: use 'localhost' endpoint in docker provisioner on Windows

---

internal/app/machined/pkg/controllers/network/operator/vip.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/machinery/resources/k8s/k8s_test.go
pkg/machinery/resources/k8s/kubelet_lifecycle.go

This introduces a shutdown lock basically which makes sure that whatever
needs to be terminated before kubelet shutdown sequence is initiated has
a chance to do so.
With the VIP, as the kubelet graceful shutdown terminates the API server
static pod, the VIP might be still on the node while the API server is
down. With this fix, VIP gets moved away from the node before the
kubelet graceful shutdown sequence starts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5213)

fix: give up virtual IPs before the kubelet workloads are shut down

---

internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go

Volume name is derived from the mount path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5214)

fix: correctly escape '.' in volume names

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.32 stable
Ref: https://github.com/siderolabs/pkgs/pull/433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5227)

chore: bump kernel to 5.15.32

---

website/content/v1.0/cloud-platforms/aws.md
website/content/v1.0/introduction/getting-started.md
website/content/v1.0/introduction/quickstart.md
website/content/v1.0/local-platforms/qemu.md
website/content/v1.0/local-platforms/virtualbox.md
website/content/v1.0/single-board-computers/bananapi_m64.md
website/content/v1.0/single-board-computers/jetson_nano.md
website/content/v1.0/single-board-computers/libretech_all_h3_cc_h5.md
website/content/v1.0/single-board-computers/pine64.md
website/content/v1.0/single-board-computers/rock64.md
website/content/v1.0/single-board-computers/rockpi_4.md
website/content/v1.0/single-board-computers/rpi_4.md
website/content/v1.0/virtualized-platforms/proxmox.md

GitHub download links
The path order of the `/download/` element is different for non-`latest` links, this was overlooked when replacing `latest` with `{{< release >}}` in c5da386092185fe4ed4173b08f95eac4e435ff99.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5229)

docs: fix non-latest download links

---

go.mod
go.sum
hack/release.toml
pkg/machinery/go.mod
pkg/machinery/go.sum

Update `go-blockdevice` library:
- https://github.com/siderolabs/go-blockdevice/pull/56
Also add a note on the org rename to the release notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5231)

fix: correctly find partitions with config data (`metal-iso`)

---

website/config.toml

This PR adds the Google Analytics token back. This _should_ ensure the
script is injected if the environment is "production". Once published,
if this doesn't work I'll troubleshoot further.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5246)

docs: re-add GA token

---

internal/app/machined/pkg/system/services/etcd.go

See:
- https://github.com/etcd-io/etcd/issues/13766
- https://github.com/kubernetes/kubeadm/issues/2676
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5250)

fix: enable etcd consistency check on startup

---

Makefile

Otherwise `make generate` updates embeddable data file with `-dirty`
stuffix which we don't want.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5256)

chore: drop dirty from abbreviated tag

---

website/content/v1.0/guides/upgrading-talos.md
website/content/v1.1/guides/upgrading-talos.md

This PR moves to using % instead of < for the release shortcode. As far
as I understand it, doing so tells hugo it's not raw html and thus the
headers get rendered to the sidebar properly. We may want to switch the
other uses as well, but I'm not sure it would make any difference one
way or another.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5258)

docs: update releases shortcode in upgrade guide

---

internal/app/machined/pkg/controllers/network/operator/dhcp6.go
internal/app/machined/pkg/controllers/network/operator_config.go
internal/app/machined/pkg/controllers/network/operator_spec.go
internal/app/machined/pkg/controllers/network/timeserver_spec.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/resources/network/operator_spec.go
website/content/v1.1/reference/configuration.md

I found a few cloud providers which wants to have DHCP-DUID identify to allocate the IPv6 address.
Some times DHCP-DUID uses as  stable_secret in SLAAC mode.
Also I've add the NTP server received from DHCPv6 server.
close #5018
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5086)

dhcp-v6 unique identifier/ntp from dhcp-v6

---

cmd/talosctl/cmd/mgmt/cluster/create.go
cmd/talosctl/cmd/talos/kubeconfig.go
internal/pkg/kubeconfig/kubeconfig.go
internal/pkg/kubeconfig/kubeconfig_test.go

When interating with the kubeconfig it can be
expected that a user may have the KUBECONFIG
environment variable set, so we need to use
it when appropriate.
Closes #5091
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5265)

feat: use kubeconfig env var

---

cmd/installer/pkg/install/target.go
internal/app/machined/pkg/runtime/sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go

In the case of a node being reset, using kexec greatly
speeds up the process. However, in the event the boot
partition is wiped, a full reboot is required.
Closes #4670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5273)

feat: use kexec when resetting a node

---

cmd/talosctl/cmd/mgmt/cluster/create.go
hack/release.toml
pkg/provision/providers/docker/node.go
pkg/provision/request.go
website/content/v1.1/reference/cli.md

Docker by default disable IPv6 completely in the containers which breaks
SideroLink on Docker-based clusters, as SideroLink is using IPv6
addresses for the Wiregurard tunnel.
This change might break `talosctl cluster create` on host systems which
have IPv6 disabled completely, so provide a flag to revert this
behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5279)

fix: enable IPv6 in Docker-based Talos clusters

---

website/content/v0.10/local-platforms/qemu.md
website/content/v0.11/local-platforms/qemu.md
website/content/v0.12/local-platforms/qemu.md
website/content/v0.13/local-platforms/qemu.md
website/content/v0.14/local-platforms/qemu.md
website/content/v0.7/local-platforms/qemu.md
website/content/v0.8/local-platforms/qemu.md
website/content/v0.9/local-platforms/qemu.md
website/content/v1.0/local-platforms/qemu.md
website/content/v1.1/local-platforms/qemu.md

Fix a typo in the QEMU VM install docs.
Signed-off-by: Andrei Dobre <andreidobre.web@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5288)

docs: fix a typo in QEMU VM setup guide

---

website/content/v1.0/virtualized-platforms/hyper-v.md
website/content/v1.1/virtualized-platforms/hyper-v.md

Signed-off-by: William Ashton <William@AshtonFam.org>
This PR fixes a formatting issue on the Hyper-V docs page, where a code fence included more than intended.
Before:
After:
This change makes the Hyper-V docs page a little easier to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5300)

docs: fix code fence formatting

---

internal/app/machined/pkg/controllers/network/operator/dhcp6.go

Log (lines for Talos v1):
```
[talos] operator panicked {"component": "controller-runtime", "controller": "network.OperatorSpecController", "stack": "github.com/talos-systems/talos/internal/app/machined/pkg/controllers/network.(*operatorRunState).runWithPanicHandler.func1\x5cn\x5ct/src/internal/app/machined/pkg/controllers/network/operator_spec.go:137\x5cnruntime.gopanic\x5cn\x5ct/toolchain/go/src/runtime/panic.go:1038\x5cnruntime.panicmem\x5cn\x5ct/toolchain/go/src/runtime/panic.go:221\x5cnruntime.sigpanic\x5cn\x5ct/toolchain/go/src/runtime/signal_unix.go:735\x5cngithub.com/talos-systems/talos/internal/app/machined/pkg/controllers/network/operator.(*DHCP6).parseReply\x5cn\x5ct/src/internal/app/machined/pkg/controllers/network/operator/dhcp6.go:145\x5cngithub.com/talos-systems/talos/intern …
```

fix: avoid panic in DHCPv6 operator on nil dereference

---

website/config.toml

This PR enables the little arrow that shows there's stuff underneath a
header on the sidebar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5309)

docs: enable nested arrow

---

website/layouts/sitemap.xml

`talos.dev` redirects to `www.talos.dev` so this fix to
the sitemap removes the redirect when scraping.
Closes #5313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5314)

docs: update sitemap to point to direct url

---

Dockerfile
Makefile
hack/release.toml

See https://github.com/golang/go/wiki/MinimumRequirements#microarchitecture-support
This relies on new Go 1.18 feature to use more efficient x86-64
instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5332)

feat: build Talos with support for x86-64-v2 microarchitecture

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go
pkg/machinery/gendata/data/pkgs

Bump kernel to 5.15.34
Ref: https://github.com/siderolabs/pkgs/pull/448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5346)

chore: bump kernel to 5.15.34

---

cmd/talosctl/cmd/talos/containers.go
cmd/talosctl/cmd/talos/logs.go
cmd/talosctl/cmd/talos/restart.go
cmd/talosctl/cmd/talos/root.go
cmd/talosctl/cmd/talos/stats.go
go.mod
go.sum
internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
pkg/cluster/support.go
pkg/images/list.go

Containerd CRI plugin was merged into the main repo, but we were using
old import path, so our constants coming from the module were outdated.
This fixes the image version for the pause container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5347)

fix: correct cri package import path

---

website/content/v1.0/advanced/extension-services.md
website/content/v1.1/advanced/extension-services.md

Fixes a typo in the Extension Services document alias
which serves as the redirect from the old location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5355)

docs: fix extension services alias

---

pkg/makefs/xfs.go

This "fixes" the message like:
```
xfs filesystem being mounted at /var supports timestamps until 2038 (0x7fffffff)
```
We should support Talos beyond 2038, even if we switch to a different
filesystem type by 2038 :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5356)

fix: enable long timestamps for xfs

---

website/content/v1.0/learn-more/faqs.md
website/content/v1.1/learn-more/faqs.md

Add an entry to our FAQs on why separate configurations
are needed for Talos and Kubernetes.
Closes #5295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5370)

docs: add talos/kubernetes config faq

---

website/content/v1.0/introduction/getting-started.md
website/content/v1.0/talos-guides/network/vip.md
website/content/v1.1/introduction/getting-started.md
website/content/v1.1/talos-guides/network/vip.md

Many users have been using the VIP functionality to configure
endpoints in Talos config. Documentation to clarify the possible
issues with that option and that it should be avoided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5365)

docs: improve vip caveats documentation

---

website/content/v1.0/talos-guides/configuration/editing-machine-configuration.md
website/content/v1.1/talos-guides/configuration/editing-machine-configuration.md

Add a note on how machine configuration can be retrieved
from the node, after e.g. interactive setup.
Closes #5296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5378)

Docs get machine config

---

cmd/talosctl/cmd/talos/bootstrap.go
cmd/talosctl/cmd/talos/etcd.go
internal/app/machined/pkg/system/services/etcd.go

With update of the client library to 3.5.3, etcd library started using
the logger, so using `nil` isn't fine anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5375)

fix: provide logger to the etcd snapshot restore

---

pkg/machinery/resources/network/address_spec.go
pkg/machinery/resources/network/address_status.go
pkg/machinery/resources/network/hardrware_addr.go
pkg/machinery/resources/network/hostname_spec.go
pkg/machinery/resources/network/hostname_status.go
pkg/machinery/resources/network/link_spec.go
pkg/machinery/resources/network/node_address.go
pkg/machinery/resources/network/node_address_filter.go
pkg/machinery/resources/network/operator_spec.go
pkg/machinery/resources/network/resolver_spec.go
pkg/machinery/resources/network/resolver_status.go
pkg/machinery/resources/network/route_spec.go
pkg/machinery/resources/network/route_status.go
pkg/machinery/resources/network/status.go
pkg/machinery/resources/network/timeserver_spec.go
pkg/machinery/resources/network/timeserver_status.go

Refactor all types except LinkStatus and LinkRefresh to use typed.Resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5379)

chore: refactor network resources to use typed resource

---

cmd/installer/pkg/install/manifest.go

Not sure how and when it got broken, but we're looking for mounts for
the blockdevice (like `/dev/vda`), while the actual mount info contains
the partition device (like `/dev/vda6`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5384)

fix: detect lingering mounts in the installer correctly

---

website/assets/scss/_styles_project.scss
website/layouts/partials/doc_latest_version.html
website/layouts/partials/version-banner.html

Make the latest-version banner sticky and
more noticable, and ensure the link to the
latest version links to the current document
if possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5389)

docs: improve latest-version banner

---

netlify.toml
website/layouts/partials/hooks/head-end.html

Adds a canonical link tag to doc pages
to help SEO find the current version of
documentation.
Closes #5336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5391)

docs: add canonical link ref

---

website/layouts/index.netlify_redirect

Fixes Netlify redirect commands by adding an extra
path segment aliging the directory properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5394)

docs: fix netlify redirects

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/extension.go
internal/app/machined/pkg/system/system.go
internal/app/machined/pkg/system/system_test.go

This bug showed up with extension services: say we have a service
`ext-foo` which depends on service `cri`.
Service `ext-foo` will be started correctly only once `cri` is up.
But we should also stop `ext-foo` before `cri` is stopped, as otherwise
the dependency chain is broken. This PR fixes exactly that: once `cri`
is stopped, anything which depends on it should be stopped. We should
stop as well anything which depends on `ext-foo` (transitive
dependency).
In practical terms we use dependency on `cri` in extension service to
correctly stop/start extension services with `/var` filesystem
mount/unmount.
--- …

fix: correctly handle stopping services with reverse dependencies

---

pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/v1.0/advanced/air-gapped.md
website/content/v1.1/advanced/air-gapped.md
website/content/v1.1/reference/configuration.md

Since Talos moved to new registry redirect CRI plugin format, start
redirects are no longer supported in the CRI plugin (see
https://github.com/containerd/containerd/blob/main/docs/hosts.md).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5396)

docs: fix the docs reference to star registry redirects

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.35 LTS
Ref: https://github.com/siderolabs/pkgs/pull/455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5399)

chore: bump kernel to 5.15.35

---

internal/app/machined/pkg/system/services/extension.go

Allow mounting files from host into extension services as per the [OCI
spec](https://github.com/opencontainers/runtime-spec/blob/main/config.md#mounts)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5403)

chore: allow mounting files from the host

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/controllers/k8s/endpoint.go
internal/app/machined/pkg/controllers/k8s/manifest_apply.go
internal/app/machined/pkg/controllers/secrets/kubernetes.go
internal/app/machined/pkg/controllers/secrets/kubernetes_test.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/etcd/etcd.go
pkg/kubernetes/klog.go
pkg/kubernetes/kubernetes.go
pkg/machinery/resources/secrets/kubernetes.go

Talos historically relied on `kubernetes` `Endpoints` resource (which
specifies `kube-apiserver` endpoints) to find other controlplane members
of the cluster to connect to the `etcd` nodes for the cluster (when node
local etcd instance is not up, for example). This method works great,
but it relies on Kubernetes endpoint being up. If the Kubernetes API is
down for whatever reason, or if the loadbalancer malfunctions, endpoints
are not available and join/leave operations don't work.
This PR replaces the endpoints lookup to use the `Endpoints` COSI
resource which is filled in using two methods:
* from the discovery data (if discovery is enabled, default to enabled)
* from the Kubernetes `Endpoints` resource
If the discovery is disabled (or not available), this change does almost
nothing: …

feat: use discovery information for etcd join (and other etcd calls)

---

pkg/provision/providers/qemu/launch.go

As QEMU clusters are used for testing, use unsafe cache options to
reduce amount of fsyncs going to the host blockdevice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5407)

chore: tune QEMU disk provisioner options

---

pkg/cluster/kubernetes/talos_managed.go

This fixes an issue when `talosctl upgrade-k8s` fails with unhelpful
message if the version is specified as `v1.23.5` vs. `1.23.5`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5412)

fix: strip 'v' prefix from versions on Kubernetes upgrade

---

netlify.toml
website/config.toml
website/layouts/partials/hooks/head-end.html

Fixes the Google Analytics tracking ID and
restores the production sitemap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5415)

docs: fix analytics and sitemap

---

internal/app/machined/pkg/controllers/runtime/kernel_param_defaults.go

Increase values:
- fs.aio-max-nr to 1048576 (for Ceph\Veritas\other storages)
- fs.inotify.max_user_instances to 8192 (since the usual 512 is too small today's needs)
There is no need to adjust fs.inotify.max_user_watches since it's set dynamically during startup by kernel.
Closes #5175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5408)

feat: increase aio-max-nr and inotify.max_user_instances

---

pkg/machinery/config/encoder/markdown.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/v1.0/reference/configuration.md
website/content/v1.1/reference/configuration.md

Update the configuration reference documentation
to show field information in a tabular format.
Example of the tabular layout:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5440)

docs: reformat config reference

---

internal/app/machined/pkg/controllers/files/cri_config_parts.go

When registry CRI config gets updated, contents of the file are written
to the `EtcFileSpec` resource, which gets rendered to disk and resource
`EtcFileStatus` is updated when the config is ready.
CRI config parts are merged from contents of `*.part` files which come
from system extensions and dynamic registry config which is written via
`EtcFileSpec` resource. As the controller was incorrectly triggered on
`EtcFileSpec` resource while reading files from disk, it might have read
stale contents of CRI config part (which hasn't been fully rendered to
disk), it might miss the latest content of the CRI config.
With the fix, controller is triggered on `EtcFileStatus` update, so when
the file is rendered to disk.
The symptom of the bug is the empty CRI registry config like:
```shell
$ talosctl …
```

fix: trigger CRI config merge on correct resource update

---

go.mod
go.sum
pkg/machinery/extensions/config.go
pkg/machinery/go.mod
pkg/machinery/go.sum
pkg/machinery/resources/runtime/extension_status.go
pkg/machinery/resources/runtime/kernel_module_spec.go
pkg/machinery/resources/runtime/kernel_params_spec.go
pkg/machinery/resources/runtime/kernel_params_status.go
pkg/machinery/resources/runtime/mount_status.go

No functional changes.
Also bump bumped cosi-runtime with the fix for the UnmarshalProto.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5447)

refactor: rewrite runtime resources to use typed.Resource

---

internal/app/machined/pkg/system/services/kubelet.go
pkg/machinery/constants/constants.go

`/var/run` was mounted from `/run`, and D-Bus socket to `/var/run/dbus/`
path, so when the container is stopped, container mounts are removed,
but on the host side mount propagates back, so D-Bus socket gets
propagated back to the host `/run`, and on the next kubelet restart
process continues adding even more mount levels exponentially.
Eventually on kubelet restart kernel resources are exhausted and the
node freezes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5451)

fix: don't mount D-Bus socket via mount under recursive bind mount

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.36 LTS
Ref:
- https://github.com/siderolabs/pkgs/pull/459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5452)

chore: bump kernel to 5.15.36

---

pkg/machinery/config/types/v1alpha1/v1alpha1_unstructured.go
pkg/machinery/config/types/v1alpha1/v1alpha1_unstructured_test.go

This code was written from JSON point of view, but
when YAML is unmarshaled,  we get more primitive Go types
as values, so why not include all of them?
This was showing as an error when applying a machine config e.g. for
kubelet extraArgs like:
```
shutdownGracePeriod: 0
```
Changing this to string fixes the problem, but it's not the best UX.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5453)

fix: include Go primitive types into unstructured deepcopy

---

internal/app/machined/pkg/controllers/network/cmdline.go
internal/app/machined/pkg/controllers/network/cmdline_test.go
internal/app/machined/pkg/controllers/network/link_config.go
internal/app/machined/pkg/controllers/network/link_config_test.go
internal/app/machined/pkg/controllers/network/link_spec.go
internal/app/machined/pkg/controllers/network/link_spec_test.go
internal/app/machined/pkg/controllers/network/network.go
internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/expected.yaml
pkg/machinery/ordered/ordered.go
pkg/machinery/ordered/ordered_test.go
pkg/machinery/ordered/triple.go
pkg/machinery/resources/network/link_spec.go
pkg/machinery/resources/network/link_spec_test.go

Before this change, we didn't preserve bonded interfaces ordering, which caused problems in some scenarios. Fix this by remembering their position in the original config.
Fixes #5207.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5455)

feat: add bond slaves ordering

---

internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
website/content/v1.1/learn-more/knowledge-base.md

The problem is that these values needs to be set to zero if the kubelet
feature gate is disabled, so we can't assume that we can override zero
value with the proper config, so we have to do an extra check on the
supplied configuration.
Also creates KB article on disabling this feature gate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5456)

fix: allow graceful node shutdown to be overridden

---

pkg/machinery/config/types/v1alpha1/v1alpha1_readonly_provider.go

Current code contains a data race, since access to r.bytes in Bytes() is unguarded and can be called from several goroutines. There is no need for it anyway, since WrapReadonly always gets a full slice. Refactor code to reflect that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5457)

fix: return an error if there is no byte slice in ReadonlyProvider

---

website/content/v1.0/learn-more/knowledge-base.md

As Talos v1.0.4 now supports kubelet with graceful shutdown disabled,
update the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5464)

docs: copy knowledge base to v1.0 docs

---

pkg/machinery/config/types/v1alpha1/generate/example_test.go
pkg/machinery/config/types/v1alpha1/generate/generate.go

There were many discussions on creating native Talos providers for TF,
Pulumi, etc., but there's no documented idiomatic way to use our
machinery package to generate the config. This PR tries to fill this
gap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5461)

docs: provide example on using config generation package

---

website/content/v1.1/talos-guides/install/virtualized-platforms/vmware.md

Fixed broken links and command in VMware documentation.
The examples didn't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5470)

Update VMware documentation to correct links

---

pkg/machinery/resources/files/etcfile_spec.go
pkg/machinery/resources/files/etcfile_status.go
pkg/machinery/resources/k8s/config_status.go
pkg/machinery/resources/k8s/endpoint.go
pkg/machinery/resources/k8s/kubelet_config.go
pkg/machinery/resources/k8s/kubelet_lifecycle.go
pkg/machinery/resources/k8s/kubelet_spec.go
pkg/machinery/resources/k8s/manifest.go
pkg/machinery/resources/k8s/manifest_status.go
pkg/machinery/resources/k8s/nodeip.go
pkg/machinery/resources/k8s/nodeip_config.go
pkg/machinery/resources/k8s/nodename.go
pkg/machinery/resources/k8s/secrets_status.go
pkg/machinery/resources/kubespan/config.go
pkg/machinery/resources/kubespan/endpoint.go
pkg/machinery/resources/kubespan/identity.go
pkg/machinery/resources/kubespan/peer_spec.go
pkg/machinery/resources/kubespan/peer_status.go

Refactor remaining resources into typed.Resource. Exceptions are:
- MachineConfig
- MachineType
- LinkRefresh
- LinkStatus
all of which contain additional methods, and cannot be simply reworked into new resource framework.
StaticPod and StaticPodStatus are also absent from this PR, because they result in e2e errors which are going to be resolved in the next PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5472)

chore: refactor remaining resources into typed.Resource

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.37 LTS
Bump containerd to v1.6.4
Ref:
- https://github.com/siderolabs/pkgs/pull/467
- https://github.com/siderolabs/pkgs/pull/464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5492)

chore: bump kernel and containerd

---

ADOPTERS.md

Adds an ADOPTERS markdown to the repo to allow users to show
they have adopted using Talos Linux in their organization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5496)

docs: add adopters file

---

cmd/talosctl/cmd/mgmt/cluster/create.go

The user will get an error message and talosctl aborts if `talosctl cluster create` is called with gen options and the --input-dir flag. Previously the gen options would simply be ignored without warning.
Fixes #2275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5487)

fix: talosctl exits with error if gen option and --input-dir flags are combined

---

internal/app/machined/pkg/controllers/network/hardware_addr.go
internal/app/machined/pkg/controllers/network/link_config.go
internal/app/machined/pkg/controllers/network/link_spec.go
internal/app/machined/pkg/controllers/network/node_address.go
internal/app/machined/pkg/controllers/network/operator_config.go
pkg/machinery/resources/network/link_refresh.go
pkg/machinery/resources/network/link_status.go

From #5472 Andrey comments, this commit changes LinkRefresh and LinkStatus into typed.Resource by moving Bump and Physical methods to *Spec types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5489)

chore: refactor LinkRefresh and LinkStatus into typed.Resource

---

ADOPTERS.md

Upon your invitation via Slack we would like to add Nedap Security Atlas as a Talos adopter
To show our ❤️ for Talos/k8s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5503)

feat: add Nedap Security Atlas as adopter

---

internal/app/machined/pkg/controllers/network/link_status.go
internal/app/machined/pkg/controllers/network/link_status_test.go
pkg/machinery/nethelpers/device.go
pkg/machinery/resources/network/link_status.go
website/content/v1.1/learn-more/networking-resources.md

The new fields will be used by the network device selector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5498)

feat: add more hardware information to the link status resources

---

pkg/machinery/resources/k8s/manifest.go

Remove pointer from method, because otherwise MarshalYAML doesn't work when called from type asserted empty interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5502)

chore: fix incorrect ManifestSpec.MarshalYAML signature

---

internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go

Fixes #5510
JSON is a subset of YAML, but struct tags are declared for `json:""`, so
we need to use proper function call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5530)

fix: use json.Unmarshal instead of yaml.Unmarshal

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to 5.15.38 LTS
Ref: https://github.com/siderolabs/pkgs/pull/469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5532)

chore: bump kernel to 5.15.38

---

pkg/provision/providers/qemu/arch.go

talosctl could not find the ovmf flash image to provision a local qemu
on Fedora. We added the source path where the dnf package manager will
place the image.
Fixes #5517
Fixes #5466 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5518)

fix: add source path for ovmf flash image

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

We found a race condition in the StartAllServices task, where the task
would start, before kubelet was loaded as a system service. It's
possible that the task completes without the kubelet service becoming "up". As a fix
we load the kubelet service again in StartAllServices.
Fixes #5527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5535)

fix: load kubelet system service in StartAllServices task

---

ADOPTERS.md
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
website/content/v1.1/advanced/developing-talos.md

If the a service hangs in the boot sequence will not finish. To inform
users we poll the collection of services in the StartAllServices task
regularly and log if their status has changed.
Fixes #5449
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5529)

feat: print the status of services during boot

---

pkg/machinery/config/types/v1alpha1/generate/init.go

Fixes: https://github.com/siderolabs/talos/issues/5507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5537)

fix: properly set `allowSchedulingOnMasters` in the interactive install

---

internal/integration/api/version.go
internal/integration/base/base.go
internal/integration/integration_test.go
pkg/machinery/constants/constants.go

This is to ensure that in fact Talos is built with Go version we expect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5541)

test: add a test for version of Go Talos was built with

---

pkg/machinery/config/types/v1alpha1/generate/generate.go

This fixes an issue with `talosctl gen config` not appending API server
cert SANs if the endpoint doesn't contain a port.
In fact this shouldn't be ever needed, as Talos automatically injects
SANs form the endpoint URL on the fly, but good to fix for consistency.
Fixes #5536
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5543)

fix: append hostname to cluster SANs when port is not specified

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to [5.15.39](https://github.com/siderolabs/pkgs/pull/477)
Bump runc to [v1.1.2](https://github.com/siderolabs/pkgs/pull/474)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5561)

chore: bump kernel and runc

---

internal/app/machined/pkg/controllers/secrets/api_cert_sans.go
internal/app/machined/pkg/controllers/secrets/api_cert_sans_test.go
internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans.go
internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans_test.go
pkg/machinery/resources/secrets/cert_sans.go

This affects both API server and Talos API cert SANs.
Before the fix, SANs accumulated changes over time, so even if the
hostname changes, old hostname is still kept in SANs. Even though it
shouldn't be a problem in general, it is confusing as after reboot list
will be reset back to expected value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5544)

fix: reset certificate SANs on update

---

internal/app/machined/pkg/controllers/network/operator/dhcp6.go

We are trying to get an IP-address lifetime, but we do not have it yet.
```
kern:    info: [2022-05-12T06:40:28.25916042Z]: init[663]: segfault at 20 ip 000000000201d2b1 sp 000000c00148b930 error 4 in init[400000+20ae000]
kern:    info: [2022-05-12T06:40:28.26453742Z]: Code: db 75 04 31 d2 eb 03 48 8b 10 48 8b 42 18 48 8b 5a 20 48 8b 4a 28 0f 1f 00 e8 3b a6 f7 ff 48 85 db 75 04 31 c0 eb 03 48 8b 00 <48> 8b 40 20 48 89 44 24 78 44 0f 11 bc 24 a8 00 00 00 c6 44 24 77
user: warning: [2022-05-12T06:40:28.27713142Z]: [talos] operator panicked {"component": "controller-runtime", "controller": "network.OperatorSpecController", "stack": "github.com/talos-systems/talos/internal/app/machined/pkg/controllers/network.(*operatorRunState).runWithPanicHandler.func1\x5cn\x5ct/src/internal/app/machined/pkg …
```

fix: dhcpv6 leasetime segfault loop

---

pkg/machinery/resources/cluster/affiliate.go

Rewrite types in deep-copy generation line to ascending order. Coming from #5563.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5582)

chore: fix type order in deep-copy generation line

---

website/content/v1.0/talos-guides/install/single-board-computers/jetson_nano.md
website/content/v1.1/talos-guides/install/single-board-computers/jetson_nano.md

Update Jetson Nano docs to use R32.7.2 release and u-boot 2022.04
Ref: https://github.com/siderolabs/pkgs/pull/479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5584)

docs: update jetson nano docs

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to [5.15.40](https://github.com/siderolabs/pkgs/pull/480)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5585)

chore: bump kernel to 5.15.40

---

internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/expected.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/network.json
internal/app/machined/pkg/runtime/v1alpha1/platform/utils/utils.go

Support ipv6_dhcp-* types of network.
Apply static IPs in all supported network types.
Depend on https://github.com/siderolabs/net/pull/11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5564)

feat: openstack dhcp-v6 types

---

internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
internal/app/machined/pkg/controllers/network/node_address.go

Fixes #5588
This fixes `apid` certificate generation for SideroLink IPs, so that
Talos API can be accessed over SideroLink connection.
We also drop SideroLink addresses from cluster discovery, as these
addresses don't work across nodes, so that they are not used for
KubeSpan, endpoints, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5589)

fix: allow SideroLink IPs in NodeAddresses

---

pkg/provision/providers/docker/docker.go

```
$ cat /proc/sys/kernel/osrelease
4.19.128-microsoft-standard
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5593)

fix: match for WSL platform in case-insensitive way

---

pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
website/content/v1.1/reference/configuration.md

The examples contain raw structures which will be base64-encoded on
marshaling to YAML which might be confusing if someone tries to decode
values.
At the same time we want to make sure that example certs/keys are not
useable to prevent clusters being created with fixed secrets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5595)

docs: fix "double-base64-encode" in cert/key examples

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to [5.15.41](https://github.com/siderolabs/pkgs/pull/484)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5597)

chore: bump kernel to 5.15.41

---

go.mod
go.sum
internal/app/machined/pkg/controllers/network/link_status.go
pkg/machinery/resources/network/link_status.go

This expands `LinkStatus` information when available.
Example, for QEMU:
```
$ talosctl -n 172.20.0.6 get links eth0 -o yaml
busPath: "0000:00:02.0"
driver: virtio_net
driverVersion: "1.0.0\00-talos"
```
```
$ talosctl -n 172.20.0.6 get links bond0 -o yaml
driver: bonding
driverVersion: 5.15.40-talos
firmwareVersion: "2"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5600)

feat: add ethtool ioctl as additional source of information

---

website/content/v1.0/talos-guides/install/local-platforms/virtualbox.md
website/content/v1.1/talos-guides/install/local-platforms/virtualbox.md

Fix reference to talosconfig in VirtualBox docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5610)

chore: fix reference to talosconfig

---

internal/app/machined/pkg/controllers/network/etcfile.go
internal/app/machined/pkg/controllers/network/etcfile_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/v1.1/reference/configuration.md

This PR adds the ability to disable the automatic setting of a search domain.
This can (for example) be useful to prevent issues with Alpine-based containers. (https://stackoverflow.com/a/65593511)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5605)

feat: Add support for disabling search domains

---

cmd/talosctl/cmd/mgmt/cluster/create.go

Add extra context to error message when unable to properly
open the talos config file when creating a cluster.
Closes #5625 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5626)

fix: improve error message when creating cluster

---

cmd/talosctl/cmd/mgmt/cluster/create.go

Use "%w" to properly unwrap the error operand
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5629)

fix: cluster creation error message formatting

---

cmd/talosctl/pkg/mgmt/helpers/wireguard.go

`GenerateKey` generates random 32 bytes vs. the key suitable for
Wireguard endpoint key.
This is the only place in code with this bug, and it is only used in
test code (`talosctl cluster create` with fixed Wireguard
configuration).
SideroLink and Kubespan are not affected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5630)

test: use use correct method to generate Wireguard private key

---

Makefile
cmd/installer/cmd/grub.iso.cfg
cmd/installer/cmd/iso.go
website/content/v1.1/learn-more/knowledge-base.md

Instead of hardcoded `grub.cfg`, use common code to generate list of
kernel arguments and allow using `--extra-kernel-arg` as well.
Before the change:
```
linux /boot/vmlinuz init_on_alloc=1 slab_nomerge pti=on panic=0 consoleblank=0 printk.devkmsg=on earlyprintk=ttyS0 console=tty0 console=ttyS0 talos.platform=metal
```
New (default line):
```
linux /boot/vmlinuz talos.platform=metal earlyprintk=ttyS0 console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 random.trust_cpu=on printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512
```
--- …

feat: enable passing custom kernel args to the ISO creator

---

website/content/v1.0/advanced/developing-talos.md

The tag was already corrected in v1.1 of the doc but we also need to
correct it for v1.0. When we check out git tag v1.0.5 and build the
installer it will create the image with `siderolabs` in the image tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5635)

doc: correct the install-image tag in the `Developing Talos` section

---

go.mod
go.sum
internal/app/machined/pkg/controllers/siderolink/export_test.go
internal/app/machined/pkg/controllers/siderolink/manager.go
internal/app/machined/pkg/controllers/siderolink/manager_test.go

To enable authorization to services via siderolink on startup we extend
the kernel parameter siderolink.api to accept an optional join token as
a parameter as in grpc://<host>:<port>?jointoken=1234
Fixes #5592 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5623)

feat: support join token as part of siderolink kernel parameter

---

pkg/machinery/nethelpers/routeflags.go
pkg/machinery/nethelpers/routeflags_test.go

This fixes unmarshaling of resource spec for routes with empty flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5648)

fix: correctly parse empty route flags from YAML

---

cmd/talosctl/cmd/talos/version.go
internal/app/maintenance/server/server.go
website/content/v1.1/reference/cli.md

This is useful to find Talos version as it got booted (e.g. to generate
proper machine configuration).
There's a security concern that version API might return sensitive
information via public API. At the same time Talos version can be
guessed by looking at the output of other APIs, e.g. resource type list
(`talosctl get rd`), which changes with every minor version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5645)

feat: enable version API in maintenance mode

---

pkg/machinery/nethelpers/hwaddr.go

Stdlib `net.ParseMAC` does lots of validations, but some hardware addrs
we can see (on logical interfaces) are not valid, so parse MACs in a
simple way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5651)

fix: unmarshal HardwareAddr without stdlib help

---

pkg/machinery/nethelpers/routeprotocol.go
pkg/machinery/nethelpers/routeprotocol_enumer.go

This fixes marshaling of route information.
Taken from `/etc/iproute2/rt_protos`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5656)

fix: introduce more route protocols as constants

---

website/content/_index.html

This PR fixes a typo that a kubecon attendee noticed :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5601)

docs: fix typo in main page

---

internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/azure/testdata/expected.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/azure/testdata/loadbalancer.json

Add public IP from Azure Standard SKU LB to the list of external IP (for
proper certificate generation).
part of #4150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5638)

feat: include azure public IPs from standard LB SKU into extips

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go

Bump kernel to [5.15.44](https://github.com/siderolabs/pkgs/pull/495)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5672)

chore: bump kernel to 5.15.44

---

internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4/rockpi4.go
internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4c/rockpi4c.go
internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/rpi_4.go

Disable kexec on SBC's known to have issues when doing kexec
Fixes: https://github.com/siderolabs/talos/issues/5649
Raspberry Pi seems to have issues enabling secondary CPU's on subsequent
reboots. RockPi's doesn't seem to work at all with kexec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5670)

chore: disable kexec on rpi4 and rockpi

---

internal/app/machined/pkg/controllers/k8s/manifest.go
internal/app/machined/pkg/controllers/k8s/templates.go

Flannel v0.18.0 requares ipv6-cidr in the config file if node.spec.PodCIDRs
has IPv6 subnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5662)

fix: flannel ipv6 compatibility

---

internal/app/machined/pkg/controllers/k8s/kubelet_service.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go

This is a cosmetic fix: when `KubeletServiceController` tries to write
files to `/etc/kubernetes` before `/var` mounted, it would fail.
Controller will be restarted, but each restart involves a backoff on
each restart which gets longer with each restart.
On the first boot, or when EPHEMERAL is encrypted, mounting might take
considerable time (seconds), so during that time controller might enter
such long backoff timeout that it will delay whole boot sequence - it
won't finish before `kubelet` is started.
By waiting for `EPHEMERAL` to be mounted before starting the controller
we eliminate long backoff cycles.
Also fix a bug when `StartAllServices` task might start a kubelet early
(before `KubeletServiceController` is actually going to start it).
Signed-off-by: Andrey Smirnov …

fix: wait for `/var` to be mounted in kubelet service controller

---

website/content/v1.0/learn-more/talos-network-connectivity.md
website/content/v1.1/learn-more/talos-network-connectivity.md

Workers need port 50000 to be open for control plane nodes, not port
50001.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5687)

docs: fix required ports

---

hack/release.toml
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go

This is inline with CIS guidelines. Otherwise the kube-apiserver will pass along the request with the group
set to `system:unauthenticated`. This will expose anything that is allowed by the `system:public-info-viewer`
and `system:discovery` cluster roles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5713)

feat(apiserver): disallow anonymous requests by default

---

cmd/installer/pkg/install/manifest_test.go
internal/pkg/mount/mount.go
internal/pkg/mount/mount_test.go
internal/pkg/mount/options.go
internal/pkg/mount/system.go
pkg/makefs/xfs.go

Run `xfs_repair` on XFS filesystems that needs repairing indicated by
the `unix.EUCLEAN` error when mounting
Fixes #5319
Fixes #5437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5716)

chore: run `xfs_repair` on xfs filesystem returing `EUCLEAN`

---

.drone.jsonnet
cmd/talosctl/cmd/mgmt/cluster/create.go
cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
hack/test/e2e-qemu.sh
internal/app/machined/pkg/controllers/secrets/kubernetes.go
internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans_test.go
internal/app/machined/pkg/controllers/secrets/kubernetes_test.go
internal/app/machined/pkg/controllers/secrets/root.go
pkg/machinery/config/types/v1alpha1/generate/generate.go
pkg/machinery/config/types/v1alpha1/generate/init.go
pkg/machinery/config/types/v1alpha1/generate/options.go
pkg/machinery/resources/secrets/kubernetes_root.go
pkg/provision/providers/vm/loadbalancer.go
pkg/provision/request.go
website/content/v1.1/reference/cli.md

It wasn't used when building an endpoint to the local API server, so
Talos couldn't talk to the local API server when port was changed from
the default one.
Fixes #5706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5715)

fix: respect local API server port

---

Makefile
hack/imager.sh
website/content/v1.1/talos-guides/configuration/system-extensions.md

This allows to build a custom Talos image which comes with some system
extension bundled in. Sometimes we might need to have an extension in
the initial image, e.g. `vmtoolsd` for VMWare Talos image.
Syntax:
```
make image-aws \
IMAGER_SYSTEM_EXTENSIONS="ghcr.io/siderolabs/amd-ucode:..."
```
System extensions are not supported for now for ISO images, as they
don't go through the common installer flow (https://github.com/siderolabs/talos/issues/5725).
Also it might be nice to add a simple way to generate just
`initramfs.xz` with system extensions bundled in (e.g. for PXE booting).
(https://github.com/siderolabs/talos/issues/5726)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

feat: build Talos images with system extensions included

---

internal/app/machined/pkg/controllers/siderolink/export_test.go
internal/app/machined/pkg/controllers/siderolink/manager.go
internal/app/machined/pkg/controllers/siderolink/manager_test.go

Keep using old defaults: if the scheme is not specified, assume
"insecure" gRPC.
If `https://` scheme is specified, use gRPC with default TLS config
(which assumes default trusted CAs, no client cert).
Also fixes a bug when gRPC endpoint was passed in raw form, this won't
work with actual scheme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5724)

fix: support SideroLink "secure" gRPC connection

---

hack/test/e2e.sh

With Pod Security, we need to allow priveleged for rook-ceph.
This fix was lost when reverting day-two.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5730)

test: fix csi tests

---

Dockerfile
internal/app/machined/main.go
internal/app/poweroff/main.go

Previously Talos would not shutdown gracefully if hyper-v issued the
'perform_shutdown' call. Said call would execute '/sbin/poweroff' which
did not exist in Talos. We hardlink machined to '/sbin/poweroff' and
make it send a shutdown API call to PID 1 machined.
I verified that my solution works by creating a Talos node on Azure and stopping it through the Azure Portal.
Fixes #5641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5747)

fix: enable orderly poweroff in hyper-v on Azure

---

website/content/v1.0/learn-more/knowledge-base.md
website/content/v1.1/learn-more/knowledge-base.md
website/content/v1.2/learn-more/knowledge-base.md

Add snippets for logging kube-apiserver audit logs from Talos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5753)

docs: snippets for logging api server audit logs

---

internal/integration/cli/health.go

We skip the client-side health endpoint test that relies on the discovery service if the discovery service is not enabled for the cluster. Related to siderolabs#5554.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5775)

test: fix health endpoint cli test when discovery is disabled

---

internal/app/machined/pkg/controllers/siderolink/manager.go
internal/app/machined/pkg/controllers/siderolink/manager_test.go

If no port is supplied for the SideroLink API endpoint and the https
schema is used, then assume port 443 is wanted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5792)

fix: siderlink api assume port 443 with https schema

---

pkg/provision/providers/qemu/arch.go
pkg/provision/providers/qemu/preflight.go

Find additional qemu binaries.
Default binary location on rhel is `/usr/libexec/qemu-kvm`.
By default, this location is not in the PATH, therefore we look both for the explicit path, and for just the `qemu-kvm` binary
Fix https://github.com/siderolabs/talos/issues/5761
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5795)

fix: look for qemu-kvm binary

---

internal/app/machined/pkg/controllers/config/k8s_control_plane.go
internal/app/machined/pkg/controllers/config/k8s_control_plane_test.go
internal/app/machined/pkg/controllers/k8s/manifest_test.go

`DNSServiceIP` was assumed to be IPv4 when only one CIDR is specified
which was leading to a malformed CoreDNS manifest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5798)

fix: generate correct bootstrap manifests when only IPv6 CIDR is used

---

go.mod
go.sum
pkg/machinery/go.mod
pkg/machinery/go.sum

Previously crypto library handled only RSA-SHA512, as generated by
Talos, but this is a problem when migrating `kubeadm` cluster to Talos.
See https://github.com/siderolabs/crypto/pull/25
Fixes #5783 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5799)

fix: update crypto library with support for RSA-SHA*

---

website/content/v1.0/advanced/air-gapped.md
website/content/v1.0/advanced/developing-talos.md
website/content/v1.0/talos-guides/install/local-platforms/qemu.md
website/content/v1.1/advanced/air-gapped.md
website/content/v1.1/advanced/developing-talos.md
website/content/v1.1/talos-guides/install/local-platforms/qemu.md
website/content/v1.2/advanced/air-gapped.md
website/content/v1.2/advanced/developing-talos.md
website/content/v1.2/talos-guides/install/local-platforms/qemu.md

chane `sudo` parameter from `-E` to `--preserve-enf=HOME` to enforce the config is created in users home and not in */root/.talos* when creating cluster with `talosctl cluster create --provisionber=qemu`
On fedora and opensuse, `sudo -E talosctl cluster create --provisioner=qemu` doesn't keep the home variable, so talos uses */root/.talos*. See #5467 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5801)

Change command for cluster create to keep $HOME with sudo

---

internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go
pkg/kubernetes/kubelet/kubelet.go

When we query kubelet API to populate the StaticPodStatuses, instead of checking for ownerReferences to be empty, we check the annotation "kubernetes.io/config.source" value so we avoid including standalone pods (that are regular pods but not part of a replicaset).
We also optimize their fetching by avoiding to unmarshal the fields we do not need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5819)

fix: filter static pods correctly and optimize fetching

---

go.mod
go.sum
go.work.sum
pkg/machinery/go.mod
pkg/machinery/go.sum

There are no changes between 0.3.2 and 0.3.3, but 0.3.2 tag was force
pushed causing stale checksum in Go checksum database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5822)

chore: update blockdevice library to v0.3.3

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go
pkg/machinery/gendata/data/pkgs

Bump kernel to [5.15.50](https://github.com/siderolabs/pkgs/pull/524)
Also pulls in https://github.com/siderolabs/pkgs/pull/526
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5820)

chore: bump kernel to 5.15.50

---

website/content/v1.1/kubernetes-guides/configuration/pod-security.md
website/content/v1.2/kubernetes-guides/configuration/pod-security.md

Fix the resource name for admissionconfig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5826)

docs: fix pod security talos resource name

---

Dockerfile

This adds a symlink to improve compatibility.
Fixes #5523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5829)

fix: provide CA certificates in `/etc/ssl/certs/ca-certificates.crt`

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go
pkg/machinery/gendata/data/pkgs

Bump kernel to [5.15.51](https://github.com/siderolabs/pkgs/pull/527)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5835)

chore: bump kernel to 5.15.51

---

internal/app/machined/pkg/controllers/hardware/system.go
internal/app/machined/pkg/controllers/hardware/system_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go

Disable systeminfo controller in container mode
Fixes: #5849
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5850)

chore: disable systeminfo controller in container

---

hack/release.toml
internal/app/machined/pkg/controllers/network/cmdline.go
internal/app/machined/pkg/controllers/network/cmdline_test.go
internal/app/machined/pkg/controllers/network/link_config.go
pkg/machinery/constants/constants.go
pkg/machinery/resources/network/link.go
website/content/v1.2/reference/kernel.md

this commits adds dracut style vlan support to allow
installing talos in networks where ports is not tagged
with a default vlan.
Signed-off-by: Eirik Askheim <eirik@x13.no>
dracut style vlan= cmdline support solving https://github.com/siderolabs/talos/issues/5755
Fixes #5755 
allow installation of Talos in environments without default vlan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5851)

feat: add vlan support to cmdline

---

cmd/installer/pkg/install/install.go

The example configuration generated by talosctl contains
```yaml
extraKernelArgs:
- talos.platform=metal
```
in the install section, which, if uncommented, causes the installer to append the
`talos.platform` option twice. Thus, if the platform is set/changed here, it will
not be respected. This change allows the existing value to be overridden.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5867)

fix: avoid double append of `talos.platform` kernel argument

---

internal/app/machined/pkg/system/services/etcd.go

Remove code which is no longer needed.
Taken from #5806
Co-authored-by: Serge Logvinov <serge.logvinov@sinextra.dev>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5875)

fix: use correct etcd cert path

---

internal/app/machined/pkg/system/services/etcd.go
internal/pkg/etcd/etcd.go

There were two issues with using discovery service for join and promote:
* on join, that resulted in joining too fast which triggers race bugs in
etcd cert generation (to be fixed as separate PR)
* on promote, Talos has to connect to non-learner member of the cluster
which is somehow "automatic" with Kuberentes discovery, as it only
lists `kube-apiserver` running which is up only when etcd on the same
node is healthy. etcd client doesn't allow to avoid learner members,
as even getting a member list from a learner doesn't work (to be fixed
as a separate PR)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5876 …

fix: stabilize etcd join and promote sequences

---

website/content/v1.0/talos-guides/configuration/disk-encryption.md
website/content/v1.1/talos-guides/configuration/disk-encryption.md
website/content/v1.2/talos-guides/configuration/disk-encryption.md

Disk encryption documentation is currently missing the `provider` key. This PR adds it.
Following the configuration in the current docs results in a reboot loop.

docs: fix disk encryption params

---

internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go
pkg/download/download.go

The download of the talos configuration may fail because the substituted
information like the hostname may not be initialized yet. Therefore we
retry the download and resubstitute the variables each time.
Fixes #3272

feat: resubstitute talos.config url variables on retry

---

website/config.toml

This PR removes pre-v0.10 docs from the drop down. They will remain in
the content so folks can still read them if needed.

docs: remove old docs from site

---

website/content/v1.2/talos-guides/install/virtualized-platforms/kvm.md
website/content/v1.2/talos-guides/install/virtualized-platforms/vagrant-libvirt.md

Documentation of running Talos on a Vagrant environment with libvirt provider.

docs: add documentation for vagrant & libvirt

---

website/content/v1.2/advanced/migrating-from-kubeadm.md

Document how to migrate from kubeadm-based clusters to Talos.
Part of siderolabs/talos#5832

docs: add kubeadm migration guide

---

internal/app/machined/pkg/controllers/k8s/kubelet_service.go
internal/integration/api/update-endpoint.go

Overwrite cluster's server URL in the kubeconfig file used by kubelet when the cluster control plane endpoint is changed in machineconfig, so that kubelet doesn't lose connectivity to kube-apiserver.
Closes siderolabs/talos#4470.

fix: update kubelet kubeconfig when cluster control plane endpoint changes

---

internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
internal/app/machined/pkg/controllers/k8s/render_config_static_pods.go
internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
pkg/machinery/constants/constants.go

~~WIP: works for new clusters, haven't tested upgrades (likely this breaks because of existing file permissions...?)~~
EDIT: tested and it just works, even with --preserve files are recreated with correct permission
~~Question: Should I include the seccomp yaml for the control-plane?~~
Follow KEP-2568 (https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2568-kubeadm-non-root-control-plane). Seperation UIDs, Adding GIDs, allowPriviledgeEscalation: false,drop unneeded capabilities and add seccomp CP manifest changes.
~~Seccomp is excluded as i think it has a dependency on https://github.com/siderolabs/talos/issues/5293 ? Also I have no idea how to test that.~~
Mainly better compatibility (this KEP is scheduled to be implented for kubeadm 1.25) + …

feat: follow KEP-2568 non-root enhancements

---

internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go

This fixes a problem when platform network configuration might have
already been applied from the cached on disk representation, and in that
base e.g. `bond0` MAC is same as `eth0`, so Talos might mistakenly pick
up `bond0` as a slave to itself instead of `eth0`.

fix: skip bond itself when matching interface (Equinix Metal)

---

internal/app/machined/pkg/controllers/kubespan/manager.go
internal/app/machined/pkg/controllers/kubespan/manager_test.go
internal/app/machined/pkg/controllers/kubespan/nftables.go
internal/app/machined/pkg/controllers/kubespan/nftables_test.go
internal/app/machined/pkg/controllers/kubespan/routing_rules.go
internal/app/machined/pkg/controllers/kubespan/routing_rules_test.go
pkg/machinery/constants/constants.go
website/content/v1.2/learn-more/kubespan.md

Fixes #4836
Firewall mark is `uint32` attached to the packet in the Linux kernel
(it's not transmitted on the wire). This is a shared value for all
networking software, so multiple components might attempt to set and
match on the firewall mark.
Cilium and Calico CNIs are using firewall marks internally, but they
touch only some bits of the firewall mark.
The way KubeSpan was implemented before this PR, it was doing direct
match on the firewall mark, and setting the whole `uint32`, so it comes
into conflict with any other networking component using firewall marks.
The other problem was that firewall mark 0x51820 (0x51821) was too
"wide" touching random bits of the 32-bit value for no good reason.
So this change contains two fixes:
* make firewall mark exactly a single bit (we use bits …

fix: use masks and different firewall mark for KubeSpan

---

cmd/talosctl/cmd/talos/reboot.go
website/content/v1.1/reference/cli.md
website/content/v1.2/reference/cli.md

chore: fix typo in `powercycle`

---

internal/app/machined/pkg/controllers/k8s/kubelet_service.go
internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
internal/integration/api/update-endpoint.go
internal/integration/api/update-hostname.go
internal/integration/base/k8s.go
pkg/machinery/resources/k8s/kubelet_spec.go

Clear the kubelet certificates and kubeconfig when hostname changes so that on next start, kubelet goes through the bootstrap process and new certificates are generated and the node is joined to the cluster with the new name.
Fixes siderolabs/talos#5834.

fix: regenerate kubelet certs when hostname changes

---

pkg/machinery/extensions/extensions.go

Update extension spec to support glibc standard path.
Ref: https://github.com/siderolabs/extensions/pull/49

chore: support glibc apps extension spec

---

go.mod
go.sum
hack/release.toml
internal/app/machined/pkg/controllers/network/hostname_config.go
internal/app/machined/pkg/controllers/network/hostname_config_test.go
pkg/machinery/config/contract.go
pkg/machinery/config/contract_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/generate/init.go
pkg/machinery/config/types/v1alpha1/v1alpha1_features.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
website/content/v1.2/reference/configuration.md

Use machine-id as the source for the default hostname (e.g. `talos-2gd-76y`) instead of DHCP-assigned IP (e.g. `talos-172-20-0-2`). This way, DHCP IP changes won't impact the hostname. Defaults to true for Talos version >=1.2.
Closes siderolabs/talos#5896.

feat: set stable default hostname based on machine-id

---

internal/pkg/mount/mount.go

Set the correct permissions for the overlay mounted folders. This issue
was identified from #5948

fix: folder permissions of overlay mounted folders

---

pkg/machinery/config/types/v1alpha1/generate/worker.go

This fixes a small bug with stable hostnames when they were only enabled
for control plane nodes.

fix: enable stable hostnames for worker configs as well

---

internal/integration/base/api.go

We shouldn't start cluster healthcheck until boot sequence is done.

fix: wait for boot done when rebooting a node in the integration tests

---

pkg/cluster/kubernetes/talos_managed.go

fix: retry Conflict errors when upgrading k8s manifests

---

internal/app/apid/main.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/machined.go
pkg/grpc/factory/factory.go

This fixes apid and machined shutdown sequences to do graceful stop of
gRPC server with timeout.
Also sequences are restructured to stop apid/machined as late as
possible allowing access to the node while the long sequence is running
(e.g. upgrade or reset).

refactor: make apid stop gracefully and be stopped late

---

website/content/v1.0/reference/kernel.md
website/content/v1.1/reference/kernel.md
website/content/v1.2/reference/kernel.md

Minor doc update. Doc specifies colon separated eth devices for bond devices. Dracut specifies comma.
>        bond=<bondname>[:<bondslaves>:[:<options>[:<mtu>]]]
>            Setup bonding device <bondname> on top of <bondslaves>.
>            <bondslaves> is a comma-separated list of physical (ethernet)
>            interfaces. <options> is a comma-separated list on bonding
>            options (modinfo bonding for details) in format compatible
>            with initscripts. If <options> includes multi-valued
>            arp_ip_target option, then its values should be separated by
>            semicolon. if the mtu is specified, it will be set on the
>            bond master. Bond without parameters assumes
>            bond=bond0:eth0,eth1:mode=balance-rr
Tested OK.

Minor doc update: bond devices are comma separated

---

pkg/machinery/client/config/path.go
pkg/machinery/constants/constants.go

Similar to the way kubectl reads kubeconfig, we attempt to load talosconfig file from multiple locations. If the file exists under `/var/run/secrets/talos.dev/config`, we load with higher priority before falling back to `~/.talos/config`. This will allow talosctl to be able to access Talos API from inside a pod when talosconfig is mounted into `/var/run/secrets/talos.dev/config`, similar to the way Kubernetes service account tokens work.
Part of siderolabs/talos#5980.

feat: read talosconfig from secrets directory

---

internal/app/machined/pkg/controllers/config/k8s_control_plane.go
internal/app/machined/pkg/controllers/etcd/pki.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/etcd/endpoints.go
internal/pkg/etcd/etcd.go
pkg/machinery/constants/constants.go

This uses all available (potential) etcd endpoints, which includes the
member being promoted as well. We avoid failures by iterating over the
list of endpoints on each attempt to make sure each and every endpoint
is tried.
Part of #5889

fix: iterate over etcd members endpoints for member promotion

---

cmd/installer/pkg/install/manifest_test.go
hack/gotagsrewrite/main_test.go
internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/app/machined/pkg/system/runner/goroutine/goroutine_test.go
internal/app/machined/pkg/system/runner/process/process_test.go
internal/pkg/containers/containerd/containerd_test.go
internal/pkg/containers/cri/cri_test.go
internal/pkg/cri/cri_test.go
internal/pkg/mount/mount_test.go
pkg/archiver/archiver_test.go
pkg/chunker/file/file_test.go
pkg/conditions/files_test.go
pkg/follow/follow_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
// before
func (suite *FooSuite) SetupSuite() {
var err error
suite.tmpDir, err = ioutil.TempDir("", "talos")
suite.Require().NoError(err)
}
func (suite *FooSuite) TeardownSuite() {
suite.Require().NoError(os.RemoveAll(suite.tmpDir))
}
// after
func (suite *FooSuite) SetupSuite() {
suite.tmpDir = suite.T().TempDir()
}
```
This saves us at least 2 lines (error check, and cleanup) on every instance.
> See `make help` for a …

test: use `T.TempDir` to create temporary test directory

---

hack/release.toml
internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
internal/app/machined/pkg/controllers/kubespan/config.go
internal/app/machined/pkg/controllers/kubespan/config_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
pkg/machinery/resources/kubespan/config.go
website/content/v1.2/learn-more/kubespan.md
website/content/v1.2/reference/configuration.md

This is incompatible with Calico and Cilium in default configuration, as
it's not easy to figure out exact PodCIDRs of the node.
We change the default but provide the option to revert the old behavior.

fix: don't advertise Kubernetes pod networks over KubeSpan by default

---

internal/pkg/extensions/validate.go

Support allowing explicit files in extensions.

fix: allow files in extension spec

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/system/services/machined.go

This provides a "quick" shutdown when the API server is going down.
This solves to have a "clean" shutdown of the `talosctl events` stream
when the server is rebooting.

fix: shutdown some streaming API calls when machined API is shutting down

---

cmd/talosctl/cmd/mgmt/debug/air-gapped.go
cmd/talosctl/cmd/mgmt/debug/debug.go
cmd/talosctl/cmd/mgmt/debug/httproot/debug.yaml
cmd/talosctl/cmd/mgmt/root.go
internal/app/machined/main.go
internal/app/machined/pkg/controllers/k8s/extra_manifest.go
internal/pkg/containers/image/resolver.go
internal/pkg/containers/image/resolver_test.go
pkg/download/download.go
pkg/download/tftp.go
pkg/httpdefaults/httpdefaults.go
pkg/httpdefaults/tls.go
pkg/machinery/constants/constants.go
website/content/v1.2/advanced/developing-talos.md

Fixes #5652
This reworks and unifies HTTP client/transport management in Talos:
* cleanhttp is used everywhere consistently
* DefaultClient is using pooled client, other clients use regular
transport
* like before, Proxy vars are inspected on each request (but now
consistently)
* manifest download functions now recreate the client on each run to
pick up latest changes
* system CA list is picked up from a fixed locations, and supports
reloading on changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5733)

fix: reload trusted CA list when client is recreated

---

internal/app/machined/pkg/controllers/network/operator_config.go
internal/app/machined/pkg/controllers/network/operator_config_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
website/content/v1.2/reference/configuration.md

Add `DHCPOptions` for VLAN device.
Fixes: #6011

feat: support dhcp options for vlan

---

internal/app/apid/pkg/backend/apid.go
internal/app/apid/pkg/director/director.go
internal/app/apid/pkg/director/director_test.go
pkg/machinery/client/context.go

This adds a new metadata field `node` which performs always proxying to
a single node without touching any protobuf structs on the way.
So with `node`, we can call APIs which do not conform to the Talos API
proxying standards, but from the UX point of view things will work same
way, but multiplexing will be handled on the client side.

feat: add support for proxying one-to-one to `apid`

---

cmd/talosctl/cmd/mgmt/cluster/create.go
cmd/talosctl/cmd/mgmt/inject/inject.go
cmd/talosctl/cmd/mgmt/inject/serviceaccount.go
cmd/talosctl/cmd/mgmt/root.go
cmd/talosctl/cmd/root.go
hack/release.toml
internal/app/machined/pkg/controllers/k8s/manifest.go
internal/app/machined/pkg/controllers/k8s/manifest_apply.go
internal/app/machined/pkg/controllers/k8s/templates.go
internal/app/machined/pkg/controllers/kubeaccess/endpoint.go
internal/app/machined/pkg/controllers/kubeaccess/serviceaccount.go
internal/app/machined/pkg/controllers/kubeaccess/serviceaccount/crd_controller.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/integration/api/serviceaccount.go
internal/integration/base/k8s.go
internal/integration/cli/inject.go
internal/integration/cli/testdata/inject/talosconfig-expected.yaml
internal/integration/cli/testdata/inject/talosconfig-input.yaml
internal/integration/integration_test.go
internal/integration/provision/upgrade.go
internal/pkg/etcd/lock.go
internal/pkg/tui/installer/installer.go
pkg/kubernetes/inject/serviceaccount.go
pkg/machinery/client/config/config.go
pkg/machinery/client/config/path.go
pkg/machinery/client/options.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/constants/constants.go
website/content/v1.2/advanced/talos-api-access-from-k8s.md
website/content/v1.2/reference/cli.md

We add a new CRD, `serviceaccounts.talos.dev` (with `tsa` as short name), and its controller which allows users to get a `Secret` containing a short-lived Talosconfig in their namespaces with the roles they need. Additionally, we introduce the `talosctl inject serviceaccount` command to accept a YAML file with Kubernetes manifests and inject them with Talos service accounts so that they can be directly applied to Kubernetes afterwards. If Talos API access feature is enabled on Talos side, the injected workloads will be able to talk to Talos API.
Closes siderolabs/talos#4422.

feat: introduce Talos API access from Kubernetes

---

cmd/talosctl/cmd/talos/apply-config.go
hack/release.toml
internal/integration/cli/apply-config.go
website/content/v1.2/reference/cli.md

Fixes: https://github.com/siderolabs/talos/issues/6045
`talosctl apply-config` now supports `--config-patch` flag that takes
machine config patches as the input.

feat: support patching the machine config in the `apply-config` cmd

---

hack/release.toml
internal/app/machined/pkg/system/services/kubelet.go
pkg/machinery/constants/constants.go
website/content/v1.2/kubernetes-guides/configuration/seccomp-profiles.md

Since `/var/lib/kubelet` was mounted with `rbind` and `rshared`, the
seccomp profile mount from the host at `/var/lib/seccomp/profiles` when
mounted at `/var/lib/kubelet/seccomp/profiles` would create a mount back
to the host creating an extra mount everytime kubelet starts/restarts.
Fix the issue by using the same path for the seccomp profiles on both
host and kubelet.

fix: recursive seccomp mounts

---

internal/app/machined/pkg/controllers/k8s/nodeip.go
internal/app/machined/pkg/controllers/k8s/nodeip_test.go
internal/app/machined/pkg/controllers/network/node_address.go
internal/app/machined/pkg/controllers/network/node_address_test.go
pkg/machinery/nethelpers/std_netaddr.go
pkg/machinery/resources/network/node_address.go
pkg/machinery/resources/network/ula.go

Same change will be done for the etcd in a separate PR.
The idea is to introduce a subset of `current` addresses: `routed`
addresses don't include external IPs (like AWS), as they are not on the
node, and excludes SideroLink IPs (as these are not routeable).
Reimplement `kubelet` nodeIP selection based on the new resources
removing the reliance on `net.IPAddrs`.

fix: introduce 'routed' NodeAddresses and use them in kubelet

---

internal/app/machined/pkg/controllers/etcd/config.go
internal/app/machined/pkg/controllers/etcd/config_test.go
internal/app/machined/pkg/controllers/etcd/spec.go
internal/app/machined/pkg/controllers/etcd/spec_test.go
internal/app/machined/pkg/system/services/etcd.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
pkg/machinery/resources/etcd/config.go
pkg/machinery/resources/etcd/deep_copy.generated.go
pkg/machinery/resources/etcd/spec.go
website/content/v1.2/reference/configuration.md

This introduces new configuration settings to configure
advertisted/listen subnets. For backwards compatibility when using no
settings or old 'subnet' argument, etcd still listens on all addresses.
If new `advertisedSubnets` is being used, this automatically limits etcd
listen addresses to the same value. `listenSubnets` can be configured
also explicitly e.g. to listen on additional addresses for some other
scenarios (e.g. accessing etcd from outside of the cluster).
See #5668
One more thing left (for a separate PR) is to update etcd advertised
URLs on the fly.

feat: allow configuring etcd listen addresses

---

cmd/talosctl/cmd/talos/diskusage.go
cmd/talosctl/cmd/talos/dmesg.go
cmd/talosctl/cmd/talos/events.go
cmd/talosctl/cmd/talos/list.go
cmd/talosctl/cmd/talos/logs.go
cmd/talosctl/cmd/talos/memory.go
cmd/talosctl/cmd/talos/processes.go
cmd/talosctl/cmd/talos/read.go
cmd/talosctl/cmd/talos/support.go
cmd/talosctl/pkg/talos/helpers/checks.go
cmd/talosctl/pkg/talos/helpers/error.go
cmd/talosctl/pkg/talos/helpers/stream.go
go.mod
internal/integration/cli/config.go
internal/integration/cli/diskusage.go
internal/integration/cli/logs.go
pkg/machinery/client/events.go

Fixes: https://github.com/siderolabs/talos/issues/6016
Multinode requests were printing out the errors for each node to stderr,
but they didn't set the global error.
Refactor the code a bit to use a single function for handling that logic
to avoid rewriting it in many other places.

fix: make `talosctl` command return nonzero error codes if it had errors

---

cmd/talosctl/cmd/talos/events.go
pkg/machinery/client/events.go
website/content/v1.2/reference/cli.md

Add the missing actor id on the event and a way to filter by it to the events cli command.
Related to siderolabs/talos#5499.

feat: add event actor id to client api and events cmd

---

pkg/machinery/extensions/extensions.go

Allow modules to be loaded via [extensions](https://github.com/siderolabs/extensions/pull/52).

feat: allow modules to be loaded via extension

---

pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go

Validate that the etcd CA is not empty in machine configuration.

chore: validate that etcd ca is not empty

---

cmd/talosctl/cmd/root.go
cmd/talosctl/cmd/talos/root.go
pkg/machinery/client/basic_auth.go
pkg/machinery/client/client.go
pkg/machinery/client/config/config.go
pkg/machinery/client/connection.go
pkg/machinery/client/connection_test.go
pkg/machinery/client/export_test.go
pkg/machinery/client/grpc_connection_wrapper.go
pkg/machinery/client/insecure_credentials.go
pkg/machinery/client/options.go
pkg/machinery/client/secure_credentials.go
pkg/machinery/config/types/v1alpha1/generate/generate_test.go
website/content/v1.2/reference/cli.md

Talos client can connect to Talos API via a proxy with basic auth.
Additionally it is now optional to specify a TLS CA,key or crt. Optionally
Developers can build talosctl with WITH_DEBUG=1 to allow insecure
connections when http:// endpoints are specified.
Fixes #5980

feat: enable talos client to connect to Talos through an auth proxy

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_priority_lock.go

Removed it from one place but forgot to clean up the other usages.

fix: clean up `cancelCtxMu` leftovers in PriorityLock

---

internal/app/machined/pkg/runtime/v1alpha1/bootloader/meta.go

Looks like it returns nil if it doesn't exist and the code doesn't
handle it properly.

fix: handle grub config being empty in the `Revert` function

---

hack/release.toml

Correct link to the Talos API access from Kubernetes.
The previous link went to a non-existent page.

fix: correct link to api access from k8s

---

internal/app/machined/pkg/controllers/etcd/advertised_peer.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go

This allows to update the member information (for the current node) with
new advertised peer URLs as the config changes.
E.g. if the node IP changes, this will update the peer URLs for the
member accordingly.
At the same time any member update requires quorum, so changing IPs can
only be done on node-by-node basis.
If there are no changes to advertised peer URLs, controller does
nothing.
Talos node might still need a reboot to update the listen addresses, as
these are not handled automatically for now.
Fixes #6080

feat: update etcd advertised peer addresses on the fly

---

hack/release.toml
internal/app/machined/pkg/controllers/network/hostname_config.go
internal/app/machined/pkg/controllers/network/hostname_config_test.go

When converting to base36 a 256-bit number there's a bias in the
first character of the base36 encoding, as 256-bit number never fits
perfectly base 36 number.
To give an example, when converting 4-digit binary number to decimal,
the first digit of the decimal number will be [0..3], while the
second digit won't be biased:
```
0000 -> 00
0001 -> 01
...
0111 -> 15
1000 -> 16
...
1111 -> 31
```
Same issue happens when going from e.g. base16 to base36.
Stable hostnames were biased towards having a digit as the first
character.
The fix is to skip the first character of the base36 representation, and
also we don't need to convert all 256 bits to base36, if we use only 6
characters, we can save some CPU resources by taking only 8 bytes
instead of full 32 bytes.
Signed-off-by: Andrey Smirnov …

fix: stable default hostname bias

---

Makefile
hack/release.toml
pkg/machinery/constants/constants.go
pkg/machinery/gendata/data/pkgs

Bump kernel to 5.15.62. Ref: https://github.com/siderolabs/pkgs/pull/559
This PR uses pkgs from https://github.com/siderolabs/pkgs/pull/562

chore: bump kernel to 5.15.62

---

.drone.jsonnet
cmd/talosctl/cmd/mgmt/cluster/create.go
hack/test/e2e-qemu.sh
internal/app/maintenance/main.go
internal/integration/api/discovery.go
pkg/provision/providers/qemu/node.go
pkg/provision/providers/vm/dhcpd.go
pkg/provision/request.go
website/content/v1.2/reference/cli.md

Fixes #6119
With new stable default hostname feature, any default hostname is
disabled until the machine config is available.
Talos enters maintenance mode when the default config source is empty,
so it doesn't have any machine config available at the moment
maintenance service is started.
Hostname might be set via different sources, e.g. kernel args or via
DHCP before the machine config is available, but if all these sources
are not available, hostname won't be set at all.
This stops waiting for the hostname, and skips setting any DNS names in
the maintenance mode certificate SANs if the hostname is not available.
Also adds a regression test via new `--disable-dhcp-hostname` flag to
`talosctl cluster create`.

fix: don't wait for the hostname in maintenance mode

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

fix: properly read kexec disabled sysctl

---

internal/app/machined/pkg/controllers/secrets/etcd.go
internal/app/machined/pkg/controllers/secrets/etcd_test.go
internal/pkg/etcd/certs.go

Fixes #6110
I somehow missed the fact that etcd certs were not made fully reactive
to node address changes (I wrongly assume it was already the fact).
This PR refactors etcd certificate generation process to be
resource-based and introduces unit-tests for the controller.

fix: update etcd certificates when node addresses changes

---

cmd/talosctl/cmd/talos/edit.go
cmd/talosctl/cmd/talos/get.go
cmd/talosctl/cmd/talos/patch.go
cmd/talosctl/cmd/talos/reboot.go
cmd/talosctl/cmd/talos/reset.go
cmd/talosctl/cmd/talos/shutdown.go
cmd/talosctl/cmd/talos/upgrade-k8s.go
cmd/talosctl/cmd/talos/upgrade.go
cmd/talosctl/pkg/talos/helpers/checks.go
pkg/cluster/support.go

Talos commands which are sensitive to resource API changes:
* `get`
* `edit`, `patch`
* `upgrade-k8s`
Commands with upcoming changes for actorID:
* `reboot`
* `reset`
* `shutdown`
* `upgrade`
Fixes #6101

feat: check client <> server version in some Talos commands

---

internal/pkg/containers/cri/containerd/hosts.go
internal/pkg/containers/cri/containerd/hosts_test.go

We should preserve the order of keys in generated `hosts.toml`, but
go-toml library has no real way to do that on marshaling, so fix the
previous workaround, as it was generating invalid TOML.

fix: correctly render hosts.toml with multiple endpoints

---

internal/app/maintenance/main.go

I hit this bug when one the API calls got hanging, and submitting the
machine config with `apply-config` never takes the node out of
maintenance mode, as `.GracefulStop()` may hang forever waiting for all
the calls to finish.
This way we always abort at some timeout and stop the server forcefully.

fix: always abort the maintenance service

---

internal/integration/cli/reboot.go

Fix the assertions on the reboot cli test to correctly assert the event messages in lowercase.

test: fix cli reboot test

---

pkg/machinery/client/connection.go

Previously we had `GetConn` public function, need something similar.

fix: expose Talos client gRPC connection via the function `Conn`

---

pkg/machinery/client/connection.go

`client.Conn()` now returns `*grpc.ClientConn` instead of
`gprc.ClientConnInterface`.

fix: change the type of returned gRPC connection object from the client

---

pkg/machinery/client/client.go

Client crashes if you try using it in the unixSocket mode.

fix: properly handle `configContext` being `nil` in Talos client

---

website/content/v1.1/introduction/support-matrix.md
website/content/v1.2/_index.md
website/content/v1.2/advanced/developing-talos.md
website/content/v1.2/advanced/static-pods.md
website/content/v1.2/advanced/troubleshooting-control-plane.md
website/content/v1.2/introduction/quickstart.md
website/content/v1.2/introduction/support-matrix.md
website/content/v1.2/introduction/what-is-new.md
website/content/v1.2/kubernetes-guides/configuration/cluster-endpoint.md
website/content/v1.2/kubernetes-guides/configuration/discovery.md
website/content/v1.2/kubernetes-guides/network/kubespan.md
website/content/v1.2/kubernetes-guides/upgrading-kubernetes.md
website/content/v1.2/learn-more/controllers-resources.md
website/content/v1.2/learn-more/networking-resources.md
website/content/v1.2/reference/kernel.md
website/content/v1.2/talos-guides/install/cloud-platforms/nocloud.md
website/content/v1.2/talos-guides/install/local-platforms/qemu.md
website/content/v1.2/talos-guides/upgrading-talos.md

Update what's new, upgrading docs.
Fix up instances of `master` leftover in the docs.
Fix the formatting of kernel params reference.
Fixes #6150

docs: update docs for upcoming 1.2.0 release

---

website/content/v1.2/introduction/what-is-new.md

I forgot to mention that in the docs update.

docs: highlight new `talosctl gen secrets`

---

website/config.toml
website/content/v1.1/_index.md
website/content/v1.2/_index.md

Update latest release to 1.2.0.

docs: make 1.2.0 docs default ones

---

cmd/talosctl/pkg/talos/helpers/checks.go

It should have been the opposite: it's a problem if the server version
is _older_ than the client verion.
E.g. using talosctl 1.2.0 against Talos 1.1.2 is a problem, not vice
versa.

fix: flip the client-server version check

---

internal/app/machined/pkg/controllers/etcd/config.go
internal/app/machined/pkg/controllers/etcd/config_test.go
internal/app/machined/pkg/controllers/etcd/spec.go
internal/app/machined/pkg/controllers/etcd/spec_test.go

Fixes #6210
Refactored the code a bit to support excludes and default configuration.
Etcd should never advertise VIPs, as VIPs are managed by etcd elections.

fix: automatically discard VIPs for etcd advertised addresses

---

pkg/grpc/middleware/auth/basic/token.go

There's a common logger for API calls already working, so no need to log in the token authenticator.

chore: avoid double API request logging in trustd

---

pkg/machinery/proto/proto.go
pkg/machinery/resources/k8s/k8s_test.go

Encoder function `protoenc.Marshal` expects a pointer.
Fixes #6233

fix: pass a pointer to specs.Mount into protoenc.Marshal

---

cmd/talosctl/cmd/talos/get.go
internal/app/machined/pkg/system/services/machined.go
internal/app/machined/pkg/system/services/machined_test.go
internal/integration/cli/config.go

As APIs were not listed explicitly, access with `os:reader` was denied by default, while it should have been checked down in the access filter.

fix: list COSI APIs for the apid authenticator

---

internal/app/machined/pkg/controllers/secrets/etcd.go
internal/app/machined/pkg/controllers/secrets/etcd_test.go

That was a mistake to use only 'routed' addresses, as they e.g. do not include SideroLink.

fix: include all node addresses into etcd cert SANs

---

internal/app/apid/main.go
internal/app/machined/pkg/system/services/apid.go
pkg/machinery/config/contract.go
pkg/machinery/config/contract_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/generate/generate.go
pkg/machinery/config/types/v1alpha1/generate/init.go
pkg/machinery/config/types/v1alpha1/generate/worker.go
pkg/machinery/config/types/v1alpha1/v1alpha1_features.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
website/content/v1.3/reference/configuration.md

This is enabled via a machine config feature/version contract, as `talosconfig` certificate generated previously didn't have proper key usage set, so we need to keep backwards compatibility on upgrades.
New v1.3+ clusters will include this check.
This check prevents even potential mis-use of server certificates as a client certificate.

feat: check apid client certificate extended key usage

---

internal/app/machined/pkg/controllers/secrets/kubernetes.go
pkg/kubeconfig/generate.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/constants/constants.go

Fixes #6156
Now access from Talos itself goes with `talos:admin` username in the Kubernetes API server audit log, while access with admin kubeconfig goes with `admin` username as before.

fix: use different username for Talos Kubernetes API access

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go

This makes it easier to distinguish between retriable and fatal failures.

chore: mark machine configuration validation failure as InvalidArgument

---

website/content/v1.2/learn-more/knowledge-base.md
website/content/v1.3/learn-more/knowledge-base.md

Add docs on setting cpu scaling governor across all CPUs.
Thanks to @nberlee for the [suggestion](https://github.com/siderolabs/talos/issues/4508#issuecomment-1245633679)

docs: cpu scaling governor knowledgebase

---

pkg/machinery/proto/proto_test.go

So we can compare and use binary data in Talos 1.3+

chore: add output of VLANSpec encoding to tests

---

go.mod
go.sum
pkg/machinery/go.mod
pkg/machinery/go.sum
pkg/machinery/proto/proto.go
pkg/machinery/proto/proto_test.go

This commit bumps protoenc to v0.2.0 and also adds tests to ensure that encoding fixes are working correctly.

fix: fix protoenc encoding for enums and type with custom encoders

---

internal/app/machined/pkg/system/services/etcd.go

This fixes an issue introduced in #5879: options should be set same way for both `init` and `controlplane` cases.

fix: set etcd options consistently

---

website/content/v1.2/learn-more/knowledge-base.md
website/content/v1.3/learn-more/knowledge-base.md

add new section to see how to disable admission control in control plane
Signed-off-by: Pau Campana <pau.campanya.soler@gmail.com>
Add a section for how admission control can be disabled in the control plane
It is not clear how it could be disabled.

docs: update docs for pod security

---

hack/release.toml
internal/app/machined/pkg/system/services/etcd.go

This will be only enabled for Talos v1.3.x.

feat: enable etcd consistency hashcheck

---

website/content/v1.2/talos-guides/configuration/patching.md
website/content/v1.3/talos-guides/configuration/patching.md

Fix missing 'mc' in talosctl patch example command.

docs: fix typo in patching example

---

cmd/talosctl/cmd/talos/kubeconfig.go

Set kubeconfig permission to `-rw-------`
To avoid the message 
```sh
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: kubeconfig
```
Default permission of user kube-config (~/.kube/config) is the same 0600

fix: kubeconfig permission

---

internal/app/machined/pkg/controllers/network/platform_config.go
internal/app/machined/pkg/controllers/network/platform_config_test.go
internal/app/machined/pkg/runtime/platform.go
internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
internal/app/machined/pkg/runtime/v1alpha1/platform/container/container.go
internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/expected.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go
internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_other.go
internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go

See https://github.com/siderolabs/talos/pull/6333
Using permanent address fixes issues with mis-matching the links after
they got bonded.

fix: lookup Equinix Metal bond slaves using 'permanent addr' 

---

cmd/talosctl/cmd/talos/get.go
cmd/talosctl/cmd/talos/output/json.go
cmd/talosctl/cmd/talos/output/jsonpath.go
cmd/talosctl/cmd/talos/output/jsonpath_test.go
cmd/talosctl/cmd/talos/output/output.go
cmd/talosctl/cmd/talos/output/table.go
cmd/talosctl/cmd/talos/output/yaml.go
internal/integration/cli/jsonpath.go
website/content/v1.3/reference/cli.md

We add a filter to the `talosctl get` command that allows users to specify a jsonpath filter. Now they can reduce the information that is printed to only the parts they are interested in.
Fixes #6109

feat: jsonpath filter for talosctl get outputs

---

website/content/v1.0/reference/kernel.md
website/content/v1.1/reference/kernel.md
website/content/v1.2/reference/kernel.md
website/content/v1.3/reference/kernel.md

Fix Talos required kernel parameters. `talos.config` is optional.

docs: fix talos required kernel params

---

hack/cloud-image-uploader/aws.go
hack/cloud-image-uploader/go.mod
hack/cloud-image-uploader/go.sum

Publish AMI's with IMDS v2 enabled.
Ref: https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-machine-images-support-instance-metadata-service-version-2-default/

chore: publish ami's with imds v2 enabled

---

go.mod
go.sum

See https://github.com/siderolabs/go-smbios/pull/14
This was backported on top of go-smbios v0.2.0 without any other changes.

fix: update go-smbios to v0.2.1

---

cmd/talosctl/cmd/talos/edit.go
cmd/talosctl/cmd/talos/get.go
cmd/talosctl/cmd/talos/patch.go
cmd/talosctl/pkg/talos/helpers/resources.go
go.mod
go.sum
pkg/machinery/go.mod
pkg/machinery/go.sum

The following commands:
* `talosctl get`
* `talosctl edit mc`, `talosctl patch mc`
Now these commands don't fully unmarshal resources from protobuf representation, but rather use YAML representation.
This allows `talosctl` version to be out of sync with Talos version.
Still other commands do full unmarshaling (e.g. `talosctl upgrade-k8s`), so `talosctl` should match Talos to avoid issues.

fix: skip protobuf full unmarshaling for some talosctl commands

---

README.md

When we shifted our meeting 30 minutes earlier, we forgot to update the link.

docs: update office hours time link

---

internal/app/machined/pkg/controllers/k8s/nodename.go
internal/app/machined/pkg/controllers/k8s/nodename_test.go

Kubernetes always lowercases whatever nodename is given to the kubelet, so we should do the same, otherwise Talos looks for a `Node` with uppercase letter which is never going to be registered.

fix: lowercase nodename

---

api/resource/definitions/secrets/secrets.proto
hack/release.toml
internal/app/machined/pkg/controllers/k8s/templates.go
internal/app/machined/pkg/controllers/secrets/root.go
pkg/machinery/api/resource/definitions/secrets/secrets.pb.go
pkg/machinery/api/resource/definitions/secrets/secrets_vtproto.pb.go
pkg/machinery/config/contract.go
pkg/machinery/config/contract_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/generate/generate.go
pkg/machinery/config/types/v1alpha1/generate/init.go
pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/resources/secrets/kubernetes_root.go
website/content/v1.3/reference/api.md
website/content/v1.3/reference/configuration.md

We add support for encryption with secretbox. While AESCBC is still supported secretbox will take precedence if both are configured. Secretbox is not the default encryption for new clusters.
Fixes: #6362

feat: support encryption with secretbox

---

internal/app/machined/pkg/controllers/k8s/static_pod_server.go

Previously we were serving the static pod files on localhost which assumes DNS. We change that to 127.0.0.1.

fix: serve static pod files on 127.0.0.1 instead of localhost

---

cmd/talosctl/cmd/talos/etcd.go

Fix `talosctl etcd snapshot` on windows.  Before PR change, executing `./talosctl.exe etcd snapshot ./etcd.db` on windows would give me:
> error renaming to final location: rename ./etcd.db.part ./etcd.db: The process cannot access the file because it is being used by another process.
Standard windows file locking issue, dest not being closed before trying to re-open it for the `os.Rename()`.
I didn't quite get my environment all the way set up, make conformance and make unit-tests isn't running locally, but I did build talosctl with my change and verify it fixed my issue and generated an etcd snapshot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Fix for etcd snapshot on windows

---

internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/metadata.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/expected.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/network.json

feat: cloud-init configuration improvements on the OpenStack platform

---

internal/app/machined/pkg/controllers/k8s/manifest_test.go
internal/app/machined/pkg/controllers/k8s/templates.go

See https://github.com/flannel-io/flannel/blob/master/Documentation/configuration.md#ipv6-only
Fixes #6427

fix: generate correct Flannel config for IPv6-only clusters

---

go.mod
go.sum
internal/app/machined/pkg/controllers/k8s/kubelet_static_pod.go
internal/app/machined/pkg/controllers/k8s/static_pod_server.go
internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/testdata/expected.yaml
pkg/cluster/check/default.go
pkg/cluster/check/kubernetes.go
pkg/kubernetes/kubelet/kubelet.go
pkg/machinery/go.mod
pkg/machinery/go.sum

It got broken with the changes to the kubelet now sourcing static pods from a HTTP internal server.
As we don't want it to be broken, and to make health checks better, add a new check to make sure kubelet reports control plane static pods as running. This coupled with API server check should make it more thorough.
Also add logging when static pod definitions are updated (they were previously there for file-based implementation). These logs are very helpful for troubleshooting.

fix: restore the StaticPodStatus resource

---

cmd/talosctl/cmd/talos/dashboard/components/tables.go
cmd/talosctl/cmd/talos/dashboard/components/tables_test.go

Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
Check if `nodeData.Processes` is nil before trying to access `nodeData.Processes.Processes`
This can lead to panic.
did not work locally, not sure why (not an issue with my branch, saw the same issue with master branch: `ERROR: failed to solve: granting entitlement security.insecure is not allowed by build daemon configuration`)
Fixes #5873

fix: check if processes is nil to avoid panic

---

internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
pkg/machinery/resources/network/node_address.go

Node can have two IPv6 of the same addresses:
* IPv6/64
* IPv6/128
In this case, the node will advertise two of the same IP:PORT endpoints. Which adds more time to create/recover a p2p (kubespan) connection.

fix: filter up duplicate IPs out of NodeAddresses

---

cmd/talosctl/cmd/talos/reboot.go
cmd/talosctl/cmd/talos/reset.go
cmd/talosctl/cmd/talos/shutdown.go
cmd/talosctl/cmd/talos/track.go
cmd/talosctl/cmd/talos/upgrade.go
cmd/talosctl/pkg/talos/action/node.go
cmd/talosctl/pkg/talos/action/tracker.go
hack/structprotogen/main.go
hack/structprotogen/proto/proto.go
hack/structprotogen/types/types.go
website/content/v1.3/reference/cli.md

Add a timeout of 15 minutes to the trackable CLI actions reboot, reset, shutdown and upgrade and refactor the action tracking.
Make waiting for these operations the default behavior (set `--wait` to `true` by default).

feat: add timeout to cli action tracking, track by default & refactor

---

.drone.jsonnet
hack/release.toml
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/integration/api/cgroups.go
internal/pkg/mount/cgroups.go
pkg/machinery/config/types/v1alpha1/generate/options.go
pkg/machinery/constants/constants.go
website/content/v1.3/reference/kernel.md

Use boot kernel arg `talos.unified_cgroup_hierarchy=0` to force Talos to use cgroups v1. Talos still defaults to cgroupsv2.

feat: implement support for cgroupsv1

---

pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/v1.3/reference/configuration.md

Update the docs to specify that only XFS partitions are detected when added in a `MachineDisk`. It is possible that other partition types are accepted, but it appears that ext4 is not.
I also fixed a minor typo in the same sentence.
#6483 
This should be documented or fixed. I've taken the easier route and changed the documentation, but feel free to close this if you'd rather handle it another way.
- Conformance complained about number of commits and not recognising my signature.
- `make fmt` changed a lot of unrelated files (removing newlines at the end of files) so I ignored those.
- Unit tests don't like my set up, but given it's only documentation and the rest passed, hopefully this is ok.

docs: specify that only XFS partitions are detected

---

Dockerfile
hack/cri-containerd.toml
hack/release.toml
internal/app/machined/pkg/controllers/files/cri_config_parts.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/pkg/toml/merge.go
internal/pkg/toml/merge_test.go
internal/pkg/toml/testdata/1.toml
internal/pkg/toml/testdata/2.toml
internal/pkg/toml/testdata/3.toml
internal/pkg/toml/testdata/expected.toml
internal/pkg/toml/toml.go
pkg/machinery/constants/constants.go
website/content/v1.3/talos-guides/configuration/containerd.md

This is tricky, as containerd doesn't merge itself plugin configuration across multiple files. TOML can't load configuration correctly from concatenated files.
Fixes #6390

feat: implement CRI configuration customization

---

go.mod
go.sum
hack/release.sh
internal/app/machined/pkg/controllers/cluster/discovery_service.go
internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
internal/app/machined/pkg/controllers/cluster/local_affiliate.go
internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go

This resolves a case when a node is behind NAT, but KubeSpan port is forwarded back to the node. Discovery Service returns public IP of the client as it sees from the incoming request. That address is now published to the KubeSpan endpoints.
Fixes #6508

feat: publish discovered public IP as one of the KubeSpan endpoint

---

pkg/cluster/sonobuoy/sonobuoy.go

Global timeout in kubeconfig was causing log streaming to abort.

test: fix log streaming for conformance tests

---

internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/metadata.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/testdata/expected.yaml

HCloud starts share the region/availability-zone values.
https://github.com/hetznercloud/csi-driver/pull/293#issuecomment-1320045174

feat: hcloud location properties

---

.drone.jsonnet

Looks like s3cmd image is broken now.

chore: use build-container image for s3cmd

---

cmd/talosctl/cmd/talos/kubeconfig.go
cmd/talosctl/cmd/talos/upgrade.go

This PR fixes the `talosctl upgrade` command where the `--force` flag is incorrectly parsed and remains always false.
The upgrade force option is not available for users of `talosctl`, although the server implementation supports it.
This seems to have been an oversight during some refactoring in the v1.2 release.

Fix talosctl upgrade force flag parsing

---

internal/app/machined/pkg/controllers/network/address_config.go
internal/app/machined/pkg/controllers/network/address_config_test.go
internal/app/machined/pkg/controllers/network/cmdline.go
internal/app/machined/pkg/controllers/network/cmdline_test.go
internal/app/machined/pkg/controllers/network/operator_config.go
internal/app/machined/pkg/controllers/network/operator_config_test.go
internal/app/machined/pkg/controllers/network/route_config.go
internal/app/machined/pkg/controllers/network/route_config_test.go
website/content/v1.3/reference/kernel.md

This allows multiple `ip=` parameters, and fixes setting DHCP for any link on the cmdline.
Fixes #6475

fix: parse and apply DHCP settings properly from cmdline

---

cmd/installer/pkg/install/errata.go
cmd/installer/pkg/install/install.go
internal/integration/provision/upgrade.go

Enabling BTF in the kernel brakes kexec from pre-BTF kernel (e.g. when upgrading from 1.2.x to 1.3.x).
As there's no way to detect Talos version in the installer at the moment, use another way to detect whether BTF is enabled in the Talos version which is running right now.
Fixes #6443

fix: disable kexec on upgrades from pre-BTF kernel

---

cmd/installer/pkg/install/install.go
cmd/installer/pkg/install/preflight.go
internal/pkg/install/install.go
pkg/machinery/compatibility/compatibility.go
pkg/machinery/compatibility/kubernetes_version.go
pkg/machinery/compatibility/kubernetes_version_test.go
pkg/machinery/compatibility/talos13/talos13.go
pkg/machinery/compatibility/talos_version.go
pkg/machinery/compatibility/talos_version_test.go
pkg/machinery/go.mod
pkg/machinery/go.sum

Host Talos mounts machined socket for API access into the installer contianer (for upgrades).
Installer runs any check it might need to verify compatibility.
At the moment following checks are implemented:
* Talos version (whether upgrade from version X to Y is supported)
* Kubernetes version (whether Kubernetes version X is supported with Talos Y).
Fixes #6149

feat: implement pre-flight checks in the installer

---

cmd/talosctl/cmd/talos/get.go
cmd/talosctl/cmd/talos/output/table.go
go.mod
go.sum
internal/app/apid/pkg/director/local_address.go
internal/app/apid/pkg/provider/provider.go
internal/app/machined/pkg/controllers/network/operator/vip.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
internal/app/resources/server.go
internal/app/trustd/internal/provider/provider.go
pkg/machinery/go.mod
pkg/machinery/go.sum

This brings many fixes, including a new Watch with support for Bootstapped and Errored event types.
`talosctl` from before this change is still compatible, as there's gRPC API level backwards compatibility versioning.
New client doesn't yet depend on new event types, so it will work against Talos 1.2.x.

feat: update COSI to v0.2.0

---

cmd/talosctl/cmd/mgmt/gen/config.go
internal/integration/cli/gen.go
pkg/machinery/config/types/v1alpha1/bundle/v1alpha1_configurator_bundle.go
website/content/v1.3/reference/cli.md

Add support to specify the types of outputs to be generated by talosctl gen config.
Add support for writing a single type of output to stdout instead of a file.
Related to siderolabs/talos#6562.

feat: add stdout and single config type support to talosctl gen config

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

Fixes #6553
Talos itself defaults to XFS, so IMA measurements weren't done for Talos own filesystems. But many other solutions create by default ext4 filesystems, or it might be something mounted by other means.

fix: ignore many more filesystems in IMA

---

cmd/talosctl/cmd/mgmt/gen/config.go
cmd/talosctl/cmd/mgmt/machineconfig/gen.go
cmd/talosctl/cmd/mgmt/machineconfig/machineconfig.go
cmd/talosctl/cmd/mgmt/machineconfig/patch.go
cmd/talosctl/cmd/mgmt/root.go
go.mod
hack/release.toml
internal/integration/cli/gen.go
internal/integration/cli/machineconfig.go
website/content/v1.3/reference/cli.md

Add talosctl machineconfig patch command which accepts a machine config as input and a list of patches, applying the patches and writing the result to a file or to stdout.
Link `talosctl machineconfig gen` to `talosctl gen config`, so they work the same way.
Closes siderolabs/talos#6562.

feat: add talosctl machineconfig patch command

---

internal/app/machined/pkg/controllers/kubeaccess/endpoint.go

Fixes #6566
This avoid putting all node addresses which might not be routeable across Kubernetes.

fix: use only kube-apiserver endpoints for Talos API access endpoints

---

hack/release.toml
internal/pkg/containers/cri/containerd/hosts.go
internal/pkg/containers/cri/containerd/hosts_test.go
internal/pkg/containers/image/resolver.go
internal/pkg/containers/image/resolver_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
website/content/v1.3/reference/configuration.md

There was inconsistency in the way `/v2` was appended to registry endpoint path between containerd (CRI) and Talos:
* Talos only appended `/v2` to empty paths
* containerd appended `/v2` if it's not the suffix already
Fix Talos to act same as containerd, and introduce a setting `overridePath` which stops both Talos and `containerd` from appending `/v2` (should be required with e.g. Harbor registry mirror).

fix: introduce 'overridePath' setting and fix Talos resolver

---

internal/app/machined/pkg/controllers/k8s/kubelet_service.go

The traceback:
```
user: warning: [2022-12-02T17:31:09.496341098Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.KubeletServiceController", "error": "controller \x5c"k8s.KubeletServiceController\x5c" panicked: runtime error: invalid memory address or nil pointer dereference\x5cn\x5cngoroutine 308 [running]:\x5cnruntime/debug.Stack()\x5cn\x5ct/toolchain/go/src/runtime/debug/stack.go:24 +0x65\x5cngithub.com/cosi-project/runtime/pkg/controller/runtime.(*adapter).runOnce.func2()\x5cn\x5ct/.cache/mod/github.com/cosi-project/runtime@v0.1.1/pkg/controller/runtime/adapter.go:403 +0x5d\x5cnpanic({0x2b7b600, 0x536c7c0})\x5cn\x5ct/toolchain/go/src/runtime/panic.go:884 +0x212\x5cngithub.com/talos-systems/talos/internal/app/machined/pkg/controllers/k8s.updateKubeconf …
```

fix: workaround panic in the kubelet service controller

---

internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url.go

It's only used to detect if resource is `nil` or of incorrect type. Both errors are developer errors, so we should not collect them.

chore: remove `watchErr` from `metal.getResource`

---

internal/app/machined/pkg/controllers/cluster/local_affiliate.go

This fixes a potential panic which I found in the unit-tests logs.
The error 'not found' is ignored, so need an addiitonal check.

fix: ignore k8s additional addresses if nil

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
pkg/cluster/check/default.go
pkg/cluster/check/nodes.go
pkg/minimal/limits.go

This PR adds two additional checks which are performed during boot sequence and in `talosctl health`. They ensure that nodes have enough memory and disk.
- Boot check will print a warning if memory / disk size is not sufficient.
- Health check will fail if memory / disk size is not sufficient.
Closes #6467

feat: add health check for minimal memory / disk size

---

pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go

This field has a default value, but validation was prohibiting empty value.
Fixes #6619

fix: allow empty dnsDomain in machine config

---

pkg/cluster/kubernetes/talos_managed.go
pkg/cluster/kubernetes/upgrade_checks.go
pkg/cluster/kubernetes/upgrade_checks_test.go

Add more checks for the Talos Kubernetes upgrade.
The removed api-server resources checks are kept as is, needs to be moved to the new checks as part of #6599.
Fixes: #6444

feat: add more checks for K8s upgrade

---

pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go

Make sure that machine config rejects unknown roles in Talos API access config if the feature is enabled.

feat: validate Talos API access roles in machine config

---

pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_redact_test.go

Include the previously missing service account key field in the redaction.

fix: redact service account key in config in RedactSecrets method

---

website/config.toml
website/content/v1.2/_index.md
website/content/v1.3/_index.md

docs: mark Talos 1.3 docs as default

---

website/static/install

This install script detects the platform and architecture, and downloads the correct talosctl, and checks the gpg checksums. It also installs and chmods the binary.

feat: add install script to improve talosctl installation 

---

internal/app/machined/pkg/runtime/v1alpha1/board/rpi_4/config.txt
internal/app/machined/pkg/runtime/v1alpha1/board/rpi_generic/config.txt

Possible save power consumption on the raspberry by disabling WLAN using dtoverlay.
It could save 45 mA according to https://forums.raspberrypi.com/viewtopic.php?t=257144#p1568474
Or nothing and only held it in reset according to: https://forums.raspberrypi.com/viewtopic.php?t=343854#p2060246
We should build a greener future and power is not cheap anymore.

fix: Disable Wireless Lan using dtoverlay

---

cmd/talosctl/cmd/mgmt/gen/crt.go

This command is referenced from PKI recovery documentation.

fix: use proper key usage for apid client certificate

---

internal/app/machined/pkg/controllers/secrets/kubernetes.go
pkg/kubeconfig/generate.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go

Making organization a interface for preparing to avoid giving system:masters access to the talosctl kubeconfig generated certificate.
Fork of #6658

chore: make organization selection an interface

---

website/content/v1.0/talos-guides/install/virtualized-platforms/vmware.md
website/content/v1.1/talos-guides/install/virtualized-platforms/vmware.md
website/content/v1.2/talos-guides/install/virtualized-platforms/vmware.md
website/content/v1.3/talos-guides/install/virtualized-platforms/vmware.md
website/content/v1.4/talos-guides/install/virtualized-platforms/vmware.md

https://www.talos.dev/v1.3/talos-guides/install/virtualized-platforms/vmware/ mentions 
>Download the vmware.sh script to your local machine. You can do this by issuing curl -fsSLO "https://raw.githubusercontent.com/siderolabs/talos/master/website/content/v1.3/talos-guides/install/virtualized-platforms/vmware/vmware.sh".
But the command example refers to it as `vsphere.sh`. This changes it to `vmware.sh`
also fixed the upcoming docs for 1.4. not sure if you have a backport function for historical releases.
Signed-off-by: Rowan Smith <86935689+rowansmithhc@users.noreply.github.com>
Correct the docs 
This was a simple one line change

vsphere.sh > vmware.sh

---

website/content/v1.2/_index.md
website/content/v1.2/introduction/support-matrix.md
website/content/v1.3/_index.md

Update support matrix, as Talos 1.3.0 got released.

docs: update last release for Talos 1.2.x

---

cmd/installer/cmd/root.go
cmd/talosctl/cmd/mgmt/cluster/create.go
cmd/talosctl/cmd/mgmt/gen/config.go
cmd/talosctl/cmd/talos/config.go
cmd/talosctl/cmd/talos/edit.go
cmd/talosctl/cmd/talos/patch.go
cmd/talosctl/cmd/talos/support.go
cmd/talosctl/pkg/talos/action/tracker.go
cmd/talosctl/pkg/talos/helpers/mode.go
internal/integration/cli/apply-config.go
internal/integration/cli/config.go
internal/integration/cli/gen.go
internal/integration/cli/machineconfig.go
internal/integration/cli/patch.go
internal/integration/cli/reboot.go
internal/integration/cli/support.go
internal/integration/cli/validate.go
internal/pkg/ntp/ntp.go
pkg/machinery/client/siderov1.go
pkg/machinery/config/types/v1alpha1/bundle/bundle.go
pkg/machinery/config/types/v1alpha1/bundle/v1alpha1_configurator_bundle.go
pkg/provision/providers/docker/destroy.go
pkg/provision/providers/qemu/preflight.go

Fixes #6676
There was a mix of stdout/stderr, move more consistently to stderr.

fix: send diagnostic output to stderr consistently

---

internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/metadata.go
internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go
internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/testdata/expected.yaml

Zone definition misspell.
Native services use uppercase zone.

fix: oralce cloud zone

---

internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/metadata.go
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/testdata/expected.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/testdata/interfaces.json

Introduce ipv6 to the google cloud.
It also can work with dhcpv6 is on.
But the route receives through RA packages which not working.

feat: ipv6 on gcp

---

pkg/machinery/compatibility/kubernetes_version.go
pkg/machinery/compatibility/kubernetes_version_test.go
pkg/machinery/compatibility/talos14/talos14.go
pkg/machinery/compatibility/talos_version.go
pkg/machinery/compatibility/talos_version_test.go

I missed that before cutting 1.4.0-alpha.0 release, which means unfortunately that Talos 1.4.0-alpha.0 can't upgrade Talos 1.4.0-alpha.0.

fix: implement upgrade version checks for Talos 1.4

---

cmd/talosctl/cmd/talos/config.go
cmd/talosctl/pkg/talos/helpers/confirm.go
website/content/v1.4/reference/cli.md

Adds a new sub-command to `talosctl config`. It takes in the context to be deleted as argument and supports glob matching.
A local flag `--noconfirm|-y` can be passed to bypass the confirmation prompt.
It also supports dry run by passing the `--dry-run` flag similar to `apply-config` and `edit` commands.
Example:
```
$ talosctl config remove 'ctx-*'
Remove context ctx-a(*)? (y/N): n
Remove context ctx-b? (y/N): y
Remove context ctx-c? (y/N): y
```
`talosctl` has a command to add contexts (`talosctl config add myctx`) but it was missing one to remove contexts.
References #3989

New sub-command `talosctl config remove` to remove contexts

---

website/content/v1.3/introduction/what-is-new.md

Fixes a simple typo in the Whats New auditPolicy example.

docs: fix auditpolicy example typo

---

internal/app/machined/pkg/controllers/k8s/static_endpoint.go
internal/app/machined/pkg/controllers/k8s/static_endpoint_test.go
internal/app/machined/pkg/controllers/secrets/api.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
pkg/machinery/resources/k8s/endpoint.go

These endpoints are used for workers to find the addresses of the controlplane nodes to connect to `trustd` to issue certificates of `apid`.
These endpoints today come from two sources:
* discovery service data
* Kubernetes API server endpoints
This PR adds to the list static entry based on the Kubernetes control plane endpoint in the machine config.
E.g. if the loadbalancer is used for the controlplane endpoint, and that loadbalancer also proxies requests for port 50001 (trustd), this static endpoint will provide workers with connectivity to trustd even if the discovery service is disabled, and Kubernetes API is not up.
If this endpoint doesn't provide any trustd API, Talos will still try other endpoints.
Talos does server certificate validation when calling trustd, so including …

feat: include Kubernetes controlplane endpoint as one of the endpoints

---

internal/app/machined/pkg/controllers/k8s/node_labels_apply.go
internal/app/machined/pkg/controllers/secrets/kubelet.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
pkg/kubernetes/kubernetes.go

This switches the last usage of Kubernetes controlplane endpoint to use `localhost` (itself) for controlplane nodes.
Worker nodes still use cluster-wide controlplane endpoint.
This allows controlplane nodes to boot fully even if the controlplane endpoint (e.g. loadbalancer) doesn't function.
The process of joining etcd still requires either a discovery service or a proper functioning controlplane endpoint.
With this fix, Talos controlplane nodes can boot successfully without a loadbalancer being up, while worker nodes obviously won't join.
This improves Talos behaviour in single-node clusters when controlplane endpoint is not available, the node will still boot just fine and function properly.

feat: use 'localhost' endpoint for controlplane nodes

---

internal/app/machined/pkg/controllers/kubespan/manager.go
internal/app/machined/pkg/controllers/kubespan/manager_test.go
internal/app/machined/pkg/controllers/kubespan/nftables.go
internal/app/machined/pkg/controllers/kubespan/nftables_test.go
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
pkg/machinery/constants/constants.go

Second step to solve the wireguard mtu issue.
The standard ICMP-method to discover optimal MTU size is not working with wireguard. All icmp packages cannot reach the sender because the OS cannot understand who it was. As a result we have an ICMP black hole.
We can switch on the net.ipv4.tcp_mtu_probing but it will affect all containers. I do not think this is a good idea. We will decrease the MSS of tcp packages which go through the tunnel.
```shell
...
chain kubespan_outgoing { # handle 2
type route hook output priority 0; policy accept;
meta mark & 0x00000060 == 0x00000020 accept # handle 15
oifname "lo" accept # handle 16
ip daddr @kubespan_targets_ipv4 tcp flags & (0x2 | 0x4) == 0x2 tcp option maxseg size > 1260 tcp option maxseg size set 1260 # handle 19
ip daddr …
```

fix: kubespan mss clamping

---

internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/syslinux.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/syslinux_test.go

This is (still) being used in Talos to handle upgrade rollbacks.
There were multiple problems with this code, and one of them leads to panic if the tag is written multiple times without deletion:
```
github.com/siderolabs/talos/internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux.ADV.SetTagBytes({0xc00175bc00?, 0x1f11dbe?, 0xed4f4d?}, 0x0?, {0xc000afb7f0?, 0x400?, 0x0?})
/src/internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/syslinux.go:125 +0x270
github.com/siderolabs/talos/internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux.ADV.SetTag(...)
/src/internal/app/machined/pkg/runtime/v1alpha1/bootloader/adv/syslinux/syslinux.go:95
github.com/siderolabs/talos/cmd/installer/pkg/install.(*Installer).Install(0xc0004374a0, 0x5) …
```

fix: handle overwriting tags in syslinux ADV

---

Dockerfile
cmd/installer/pkg/install/extensions.go
go.mod
go.sum
hack/extra-modules.conf
internal/pkg/extensions/extensions.go
internal/pkg/extensions/kernel_modules.go
pkg/machinery/constants/constants.go

Run `depmod` during install/upgrades when extensions provide kernel modules and `modules.dep` needs to be re-generated. This also allows modules of same name from kernel to co-exist. Modules in `extras` folder takes precedence over `in-built` ones.

feat: generate kernel module dependency tree

---

website/content/v1.3/introduction/getting-started.md
website/content/v1.3/introduction/quickstart.md
website/content/v1.3/talos-guides/install/local-platforms/qemu.md
website/content/v1.3/talos-guides/install/local-platforms/virtualbox.md
website/content/v1.3/talos-guides/install/virtualized-platforms/proxmox.md
website/content/v1.4/introduction/getting-started.md
website/content/v1.4/introduction/quickstart.md
website/content/v1.4/talos-guides/install/local-platforms/qemu.md
website/content/v1.4/talos-guides/install/local-platforms/virtualbox.md
website/content/v1.4/talos-guides/install/virtualized-platforms/proxmox.md
website/static/install

Replaced multiple curl examples to get the correct talosctl with a curl that executes the install script.

docs: update to use talosctl install script

---

internal/app/machined/pkg/system/services/etcd.go

The supposed format with multiple adverised URLs is:
`name=u1,name=u2`
Previously Talos generated:
`name=u1,u2`
(which was wrong)

fix: build correctly etcd initial cluster URL

---

internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/testdata/expected.yaml

This excludes it out of the `NodeAddress`.
Needs extra testing to confirm that it actually still works as anchor IP.
Fixes #6760

fix: mark DigitalOcean anchor IP as scope link

---

hack/docgen/go.mod
hack/docgen/go.sum
hack/docgen/schema.go
pkg/machinery/config/types/v1alpha1/schemas/v1alpha1_config.schema.json
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/v1.4/reference/configuration.md
website/content/v1.4/schemas/v1alpha1_config.schema.json

Set the additional description fields for vscode/monaco/jetbrains editors.
Strip the markdown formatting from the plain description.
Additionally, fix the description of the field `aescbcEncryptionSecret`.
Related to siderolabs/talos#6705.

feat: set markdown and html descriptions in config json schema

---

.drone.jsonnet

Fix drone config to exclude renovate pushes.

fix: drone config for renovate PR's

---

pkg/machinery/config/configpatcher/testdata/apply/expected.yaml
pkg/machinery/config/types/v1alpha1/testdata/strategic/001/expected.yaml
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go

Fixes #6747
The setting `mtu: 0` always meant "don't touch MTU", but the presence of such line is very confusing.

fix: omit zero MTU in the machine config

---

internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/decode.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/encode.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/export_test.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub_test.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/quote.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/quote_test.go

One of the fields in the GRUB config - boot arguments - contains user-controlled input. Talos supports variable expansion in `talos.config` parameter, and uses `${var}` syntax.
In GRUB config, `}` is a special character, and introduction of `}` breaks config parsing both for GRUB and Talos.
Correctly escape and unescape special characters.

fix: correctly quote and unquote strings in GRUB config

---

pkg/download/download.go

Fixes #6795
This fixes a problem with Talos being stuck if the download attempts time out - the returned context.Canceled error was triggering a different flow which treats sequence take over as a special case, while there is no other sequence to run.
Correct error should be timeout.

fix: return proper error if download attempts time out

---

internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url.go

This fixes multiple issues:
* `log.Fatalf` in the machined code leads to kernel panic
* return URL if some expansion fails
* correctly handle destroyed event (wait for the next one)
Fixes #6807

fix: correctly expand parameters in the URL

---

pkg/provision/providers/docker/reflect.go

This might happen with docker provisioner if the network is not found.
Fixes #6793

fix: panic in talosctl cluster show

---

Dockerfile
internal/app/machined/main.go
internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/app/machined/pkg/system/runner/process/process.go
internal/app/machined/pkg/system/runner/runner.go
internal/app/wrapperd/main.go

Use a wrapper for starting processes which can setup proper cgroups, OOMscore, and also drop capabilities for the process, then it calls `execve`.
The containerd tests is also fixed to support cgroups when running tests in buildkit. It used to pass previosuly as we did not error if cgroup setup failed.

feat: use wrapper for starting processes

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/runner/runner.go
internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/cri.go
internal/app/machined/pkg/system/services/udevd.go
internal/app/wrapperd/main.go
internal/pkg/capability/capability.go
pkg/machinery/constants/constants.go

Use process wrapper introduced in #6814 to drop capabilities. This change also means the capabilities are dropped per process level and not for PID 1 (machined), which allows us to drop capabilities per process.

feat: use process wrapper for dropping capabilities

---

internal/app/machined/pkg/controllers/k8s/kubelet_config_test.go
pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go

One case was missing: when network section is present, but value is omitted.
Fixes #6825

fix: default dns domain to 'cluster.local' in local case

---

.drone.jsonnet

With recent changes to Calico website, old URL returns 404.

test: update Canal CNI manifest URL

---

.drone.jsonnet

With recent changes to Calico website, old URL returns 404.
(cherry picked from commit 3d7566ec743f573a43a4a49ecb80f6ba59cbb27b)

backport: test: update Canal CNI manifest URL

---

Dockerfile
internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
internal/app/machined/pkg/runtime/v1alpha1/platform/exoscale/exoscale.go
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/internal/address/address.go
internal/app/machined/pkg/runtime/v1alpha1/platform/internal/netutils/netutils.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go
internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
pkg/machinery/constants/constants.go

Wait for the network before trying to access the metadata service.
Retry the calls when appropriate (most platforms use `download.Download` function which does proper retries).
Co-authored-by: Noel Georgi <git@frezbo.dev>

fix: wait for network and retry in platform get config funcs

---

pkg/cluster/kubernetes/talos_managed.go
pkg/cluster/kubernetes/upgrade_checks.go
pkg/cluster/kubernetes/upgrade_checks_test.go

Not all Kubernetes deprecated resources are same - if the old API version is deprecated, but new one is available, API server handles trnasition for us. If some resource is removed completely, we need to check for it. This reduces number of items to check, and simplifies the check.
Move the check under the umbrella of the 'upgrade pre-checks', and make it actually fatal.

fix: kubernetes removed resource version check

---

cmd/talosctl/cmd/talos/reboot.go

The reboot mode was not passed correctly in wait mode.

fix: talosctl reboot command passing mode in wait mode

---

internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/quote.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/quote_test.go

Not sure how I missed it in the first PR, but that's the only character which was not quoted properly.

fix: quote the ampersand character in GRUB config

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_dbus.go

If dbus is not started and a shutdown was called talos panics, fix by checking if the mock is nil.

fix: dbus shutdown when it's not initialized

---

internal/pkg/extensions/kernel_modules.go
internal/pkg/mount/mount.go

This fixes the issue when the overlay mount target directory was used as lowerdir for the mount, creating extra folders in the extension.
Fix the issue by adding support for normal overlay mounts to use a source directory when specified.
Also fixes a small issue where messages was logged when error is nil.

fix: kernel module dependency tree generation

---

pkg/provision/providers/docker/node.go
pkg/provision/providers/docker/reflect.go

Recent Docker versions seem to have changed the API in the way container IP addresses are reported.
Also fix running Talos 1.3 image under talosctl 1.4.

fix: docker talosctl cluster create provisioner

---

internal/app/machined/pkg/controllers/network/cmdline.go
internal/app/machined/pkg/controllers/network/cmdline_test.go
website/content/v1.4/reference/kernel.md

Can set netmask as number.
close #6861 

feat: cmdline integer netmask

---

cmd/talosctl/cmd/mgmt/gen/config.go
internal/integration/cli/gen.go
website/content/v1.4/reference/cli.md

Only overwrite existing files if explicitly demanded.
Closes #6847

fix: add `--force` flag to `talosctl gen config`

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/main.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/runner/goroutine/goroutine.go
internal/app/trustd/main.go

Load & start machined earlier and in initialize sequence, so that it is possible to use its API over its unix socket in maintenance mode.
Additionally, do not return features from Version API  if a config is not yet available.
Related to siderolabs/talos#4791.

feat: start machined earlier & in maintenance mode

---

cmd/talosctl/cmd/talos/config.go
cmd/talosctl/cmd/talos/diskusage.go

Use context from command line flags. Also some minor fixes.
Closes #6846

fix: use passed `--context` in `talosctl config` cmd

---

pkg/machinery/compatibility/kubernetes_version.go
pkg/machinery/compatibility/kubernetes_version_test.go
pkg/machinery/compatibility/talos12/talos12.go
pkg/machinery/compatibility/talos14/talos14.go
pkg/machinery/compatibility/talos_version.go

This provides Kubernetes version compatibility for Talos 1.2.x, so that we have a unified source of data for Talos >= 1.2.x.
Also bump supported Kubernetes version for Talos 1.4.x to be 1.25-1.27, as Talos 1.4 is expected to ship with Kubernetes 1.27.

chore: provide version compatibility data for Talos 1.2.x

---

internal/pkg/extensions/kernel_modules.go

The `modules.dep` kernel module dependency tree extension root path was previously created with a permission of `0o700` which means the talos root go a permission of `0o700` when the kernel module tree was re-built when extensions providing kernel modules was enabled. This means that any binaries lost the executable permission when ran as non-root creating an `EACCES` error. Fix by making sure the temporary directory created for building kernel modules tree has `0o755` permission explicitly.

fix: extension base folder permission

---

internal/app/machined/pkg/controllers/k8s/templates.go

Exposes the pod IP as the `POD_IP` environment variable via the downward API in the kube-proxy pod for use in e.g. metrics-bind-addr.

feat: add pod ip to kube-proxy spec

---

hack/release.toml
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/testdata/expected-match-by-mac.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/testdata/expected-match-by-name.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/testdata/metadata-match-by-mac.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/testdata/metadata-match-by-name.yaml
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_test.go
pkg/machinery/constants/constants.go

This PR is an implementation of #6708  
metadata is loaded from VMware guestinfo and used for configuration of network.
The vmware metadata which is setup by CAPV is defined here:
[VMware metadata](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/util/constants.go)
The PR implementation is inspired by the [talos nocloud](https://github.com/siderolabs/talos/tree/main/internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud) implementation of metadata and mapping to PlatformNetworkConfig.
See #6708 
Question for Sidero Talos maintainers:
1) Consider backwards compatibility. Should metadata from guestinfo always be loaded if present?
2) Not all my commits have a message that comforms to the given standard. Can we squash the commits when merging the PR?
Please …

VMware: Use network information from guestinfo.metadata

---

cmd/talosctl/cmd/talos/upgrade-k8s.go

Make the --to flag optional since there is default value for that flag.
talosctl upgrade-k8s says the --to flag has a default, still when calling without the --to flag the users gets told to that the required flag.
A different solution may would be to remove the default value.
```
talosctl upgrade-k8s -n server
required flag(s) "to" not set
Usage:
talosctl upgrade-k8s [flags]
Flags:
--dry-run           skip the actual upgrade and show the upgrade plan instead
--endpoint string   the cluster control plane endpoint
--from string       the Kubernetes control plane version to upgrade from
-h, --help              help for upgrade-k8s
--to string         the Kubernetes control plane version to upgrade to (default "1.26.1")
--upgrade-kubelet   upgrade kubelet service (default true)
Global Flags: …
```

fix: upgrade-k8s to flag should not be required since there is a default

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
pkg/machinery/constants/constants.go

This makes Talos 1.2 accept but ignore Talos 1.3 specific `/etc/cri/conf.d/20-customization.part` file, so that new config can be injected into running Talos 1.2 before upgrading to Talos 1.3.
Talos 1.3 will ignore the customization under `/var`, so it can be safely removed after the upgrade.
Fixes #6882

fix: easier upgrade to Talos 1.3 with custom CRI config

---

internal/app/machined/pkg/controllers/k8s/templates.go

Launch CoreDNS even if the node is not initialized. Network is ready already, but CCM didn't finish their job.
CCM needs the dns resolver to reach the talos-api, but CoreDNS stack in toleration condition.
I didn't catch this lock before, because I used my own coredns deploy....
I remove the `CriticalAddonsOnly` key. It was from kubeadm bootstrap process. 
We do not use it.

feat: coredns node uninitialized toleration

---

Dockerfile
internal/app/machined/pkg/controllers/k8s/templates.go
pkg/flannel/flannel.go
pkg/flannel/gen.go
pkg/flannel/template.go
pkg/images/list.go
pkg/machinery/constants/constants.go

Fixes #6730
`go generate`-based step downloads the upstream manifest, transforms it to match our requirements, and it is compiled in as the Flannel manifest.

feat: generate Flannel CNI manifest from upstream

---

.drone.jsonnet

This PR updates CI to remove the immutability policy and tags the azure "containers" (aka buckets) with a ci=true tag. This will allow us to handle the deletion of buckets with the cloud-cleaner app. Also adds the override flag to batch upload, as that was actually failing silently on subsequent runs of the CI.

chore: update CI to tag azure buckets

---

internal/app/machined/pkg/controllers/network/platform_config.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go
internal/pkg/meta/constants.go
internal/pkg/meta/meta.go
pkg/machinery/resources/runtime/meta_key.go

A special META key might contain optional platform network config for the `METAL` platform.
It is completely optional, but if present, it works same way as in the clouds: it is applied with low priority (can be overriden with machine config), but provides some initial defaults for the machine.

feat: provide platform network config for 'metal' in META

---

internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go

Fix a data race caused by the metadata field of PlatformNetworkConfig being edited after it was sent to the channel. It caused test failures.
Fix it by setting a copy of the metadata instead.

fix: fix data race on network config read

---

cmd/talosctl/cmd/mgmt/gen/ca.go
cmd/talosctl/cmd/mgmt/gen/config.go
cmd/talosctl/cmd/mgmt/gen/crt.go
cmd/talosctl/cmd/mgmt/gen/csr.go
cmd/talosctl/cmd/mgmt/gen/gen.go
cmd/talosctl/cmd/mgmt/gen/key.go
cmd/talosctl/cmd/mgmt/gen/keypair.go
cmd/talosctl/cmd/mgmt/gen/secrets.go
internal/integration/cli/gen.go
website/content/v1.4/reference/cli.md

Error out if file(s) already exists and warn user to use
`--force` to overwrite.
Fixes: #6963

fix: add `--force` flag for `talosctl gen`

---

internal/app/machined/pkg/controllers/network/link_spec.go
internal/app/machined/pkg/controllers/network/link_status.go

If link has no `Info` field we can't do anything meaningful, so we'll just log and skip.
Also fix race in test.
For #6956

fix: nil pointer exception in syncLink

---

.drone.jsonnet

Azure skips the file permissions when upload/downloaded from the object store. Make sure all binaries under `_out` have executable permissions.

chore: fix loaded artifacts file permission

---

.drone.jsonnet
Makefile

Load all external artifacts early in the build process so that the binaries are available for e2e tests.

chore: load all external artifacts earlier

---

pkg/machinery/config/types/v1alpha1/schemas/v1alpha1_config.schema.json
pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/v1.4/reference/configuration.md
website/content/v1.4/schemas/v1alpha1_config.schema.json

This PR adds a disclaimer to the 1.3 and 1.4 versions of the documentation regarding non-installable images. The reader is pointed towards ISO and PXE images as the only two kinds that acknowledge the `install` config
As explained in #6865, I was pretty confused why the Talos metal image did not want to install. Since the original discussion did not lead to a clear answer, I want to make sure that the above-mentioned image types are indeed the only ones that follow the `install` config.

Add InstallConfig ignored notice to doc

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/controllers/etcd/advertised_peer.go
internal/app/machined/pkg/controllers/etcd/member.go
internal/app/machined/pkg/controllers/network/operator/vip.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/etcd/etcd.go
internal/pkg/etcd/lock.go

The problem showed up on 'reset' of the Talos node which had multiple endpoints for other control plane nodes, many of which weren't actually available.
When 'grpc.WithBlock()' is used, etcd will try to dial the first endpoint and return an error if the dial fails.
Use noblock mode by default with multiple endpoints, and blocking mode with a single endpoint.
Pass the context to etcd to properly abort dial operations if the context get canceled.

fix: use 'no block' etcd dial with multiple endpoints

---

internal/pkg/meta/internal/adv/talos/talos.go

Discovered in #6971. Go compiler cannot deduce proper type on 32bit architectures for those constants,
in `fmt.Print(f)` functions. Since we only compare them with uint32 variables, it makes sense to add proper
types to them.

fix: add uint32 type to Magic1 and Magic2

---

.golangci.yml
Makefile
cmd/installer/pkg/install/extensions.go
cmd/talosctl/cmd/talos/get.go
cmd/talosctl/cmd/talos/support.go
internal/app/init/main.go
internal/app/machined/pkg/controllers/k8s/kubelet_service.go
internal/app/machined/pkg/controllers/k8s/node_label_spec_test.go
internal/app/machined/pkg/controllers/kubeaccess/serviceaccount/crd_controller.go
internal/app/machined/pkg/controllers/network/address_merge_test.go
internal/app/machined/pkg/controllers/network/link_merge_test.go
internal/app/machined/pkg/controllers/network/operator_merge_test.go
internal/app/machined/pkg/controllers/network/route_merge_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/internal/netutils/netutils.go
internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/integration/api/dmesg.go
internal/integration/api/logs.go
internal/integration/base/api.go
internal/pkg/extensions/kernel_modules.go
internal/pkg/extensions/validate.go
pkg/machinery/client/config/config.go
pkg/machinery/config/decoder/unknown_keys.go

Bump golangci-lint and fixup new warnings. Ignore check that checks for used function parameters, it's kind of noisy and makes it confusing to read interface implementations.

chore: bump golangci-lint

---

cmd/talosctl/cmd/talos/dashboard.go
internal/app/dashboard/main.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go
internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
internal/pkg/dashboard/dashboard.go
internal/pkg/dashboard/formdata.go
internal/pkg/dashboard/networkconfig.go
internal/pkg/dashboard/resourcedata/resourcedata.go
pkg/machinery/constants/constants.go
pkg/provision/providers/qemu/node.go

Implement the network config screen with input forms to configure the initial node networking by writing a config to the META partition.
Closes siderolabs/talos#6961.
Preview:

feat: add network config screen to dashboard

---

hack/test/e2e-qemu.sh

This bug breaks `e2e-extensions`.

test: fix misprint in e2e scripts

---

pkg/machinery/config/contract.go
pkg/machinery/config/contract_test.go

No changes vs. v1.3, so mostly no-op change just to keep things consistent.

chore: add machine config version contract for v1.4

---

hack/release.toml
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/cri.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/extension.go
internal/app/machined/pkg/system/services/kubelet.go
internal/app/machined/pkg/system/services/trustd.go
internal/pkg/environment/environment.go
internal/pkg/environment/environment_test.go
internal/pkg/install/install.go
pkg/machinery/constants/constants.go
website/content/v1.4/reference/kernel.md

Unify getting environment variables, support passing environment variables via kernel args.
Fixes #6984
See #6999
For META this will be used to pass environment variables to the installer for ISO images (or PXE booting).

feat: environment variables via the kernel arguments

---

cmd/installer/cmd/iso.go
cmd/installer/cmd/root.go
cmd/installer/pkg/install/install.go
cmd/installer/pkg/install/meta_value.go
cmd/installer/pkg/install/meta_value_test.go

E.g. with the command:
```
make image-metal IMAGER_ARGS="--meta 0xc=abc --meta 0xd=abc"
```
This doesn't support ISO/PXE boot yet, it's going to come into the next PR.
Fixes #6999

feat: allow writing initial META values into the image

---

api/resource/definitions/network/network.proto
go.mod
go.sum
internal/app/machined/pkg/controllers/network/operator/dhcp4.go
internal/app/machined/pkg/controllers/network/operator_spec.go
pkg/machinery/api/resource/definitions/network/network.pb.go
pkg/machinery/resources/network/condition.go
pkg/machinery/resources/network/hostname_spec.go
pkg/machinery/resources/network/hostname_status.go
pkg/machinery/resources/network/operator_spec.go
pkg/provision/providers/vm/dhcpd.go
website/content/v1.4/reference/api.md

This adds support for automatically registering node hostnames in DNS by
sending the current hostname to DHCP via option 12. If the current hostname is
updated, issue a new DISCOVER to propagate the update to DHCP (updating the
hostname on lease renewals is not universally supported by DHCP servers). This
addition maintains the previous functionality where the node can also request
its hostname from the DHCP server. The received hostname will be processed and
prioritized as usual by the `network.HostnameSpecController`.
This change set also contains fixes to make DHCP renewals compliant with RFC
2131, specifically avoiding sending the server identifier and requested IP
address when issuing renewals using a previous offer. This also uncovered an
issue in the upstream `insomniacslk/dhcp` …

feat: dhcpv4: send current hostname, fix spec compliance of renewals

---

internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/system/services/udevd.go

Restart udevd on adding custom rules where in the case the subsystems needs to be re-triggered.
Fixes: #7001

fix: udevd rules trigger

---

website/content/v1.4/_index.md
website/content/v1.4/talos-guides/configuration/nvidia-gpu-proprietary.md
website/content/v1.4/talos-guides/configuration/nvidia-gpu.md

Update NVIDIA install docs and add an example of setting `nvidia` as the default runtimeclass.
NVIDIA doesn't have published images of vectoradd for CUDA 12, replacing example with running `nvidia-smi` command.

docs: update nvidia instructions

---

internal/pkg/dashboard/components/networkinfo.go

Rename to be consistent between the `networkstatus` resource and the dashboard.

refactor: rename outbound to connectivity on dashboard

---

hack/test/e2e-capi.sh

Bringing up to the latest version in 1.x series.

test: bump CAPI components versions

---

cmd/talosctl/cmd/common/common.go
cmd/talosctl/cmd/root.go
cmd/talosctl/cmd/talos/reboot.go
cmd/talosctl/cmd/talos/reset.go
cmd/talosctl/cmd/talos/shutdown.go
cmd/talosctl/cmd/talos/upgrade.go
cmd/talosctl/pkg/talos/action/node.go
cmd/talosctl/pkg/talos/action/tracker.go

In the tracking of the `reset --reboot`, `reboot` and `upgrade` lifecycle commands, verify that the node was actually rebooted in the post check by comparing the pre- and post-check boot IDs.
In the `reset --reboot` post-check, try both maintenance and normal mode, since the reset might be issued to only remove `EPHEMERAL` partition, which will not put the node into the maintenance mode.
Fixes https://github.com/siderolabs/talos/issues/7009.
Additionally, if an action tracking fails, return the error instead of swallowing it. This way the command erminates with a non-zero exit code. Suppress the re-printing this error after the command was run.
Fixes https://github.com/siderolabs/talos/issues/6966.

fix: improve action tracking post checks

---

internal/app/machined/pkg/controllers/runtime/machine_status.go

The problem was that 'Succeeded' pod was treated as 'not ready', so that `MachineStatus` never reached readiness state.

fix: correctly parse static pod phase

---

pkg/machinery/client/siderov1.go

Do not attempt to open a browser if `BROWSER` env var is set to be `echo`. The browser library does not always to respect that variable.

fix: respect BROWSER=echo in client auth interceptor

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go

Previously 'START' was sent for both start and finish.

fix: send 'STOP' event on phase end

---

website/content/v1.4/kubernetes-guides/configuration/storage.md

Update documentation to match latest v1.4 API docs https://www.talos.dev/v1.4/reference/configuration/#machineconfig
Current documentation is incorrect which I validated locally.

docs: update storage.md to reference v1.4 API

---

cmd/talosctl/pkg/talos/helpers/checks.go

Message metadata might be missing, the easiest usecase is contacting worker directly using it both as an endpoint and a node.
Fixes https://github.com/siderolabs/talos/issues/7108

fix: parse errors correctly

---

internal/pkg/dashboard/components/kubernetesinfo.go
internal/pkg/dashboard/components/talosinfo.go

Hide kube-apiserver, kube-controller-manager and kube-scheduler statuses on the dashboard for the worker nodes, instead of showing them as n/a.
Also display the cluster name as n/a for workers (instead of an empty string), as that information is not available to them.
Closes siderolabs/talos#7103.

fix: do not show control plane status for workers on dashboard

---

pkg/archiver/tar.go
pkg/archiver/tar_test.go

There is some refactoring to simplify things, but mostly handle files which report size 0 in `stat`, but actually contain data when read.
We try to read up to the small buffer, if we read whole file, we use that as contents, otherwise we still skip the file, as we need to write tar header with size _before_ we read the whole file.

fix: allow `talosctl cp` to handle special files in `/proc`

---

internal/app/machined/internal/server/v1alpha1/v1alpha1_cluster.go
internal/app/machined/pkg/controllers/k8s/templates.go
internal/integration/provision/upgrade.go
pkg/cluster/check/kubernetes.go
pkg/kubernetes/kubernetes.go
pkg/machinery/constants/constants.go

Since talos now defaults to k8s 1.27, remove the handling of `master` label for controlplane nodes.

chore: remove k8s master label

---

internal/app/machined/pkg/controllers/runtime/cri_image_gc.go
internal/app/machined/pkg/controllers/runtime/cri_image_gc_test.go
internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go

Fixes #7121
Talos pulls some images on its own (without CRI/kubelet) to the `system` namespace of the CRI containerd. These images are not visible to the CRI/kubelet, so we need to clean them up manually.

feat: clean up (garbage collect) system images which are not referenced

---

Dockerfile

Fixes https://github.com/siderolabs/pkgs/issues/717
Fixes #7155
Adds back in the required TARGETARCH for installer so extensions can be built off installer again.
nvidia extension build breaking. 

fix: Update Dockerfile to include TARGETARCH in installer.

---

internal/app/machined/pkg/controllers/network/link_status_test.go
website/content/v1.2/talos-guides/configuration/patching.md
website/content/v1.3/talos-guides/configuration/patching.md
website/content/v1.4/talos-guides/configuration/patching.md
website/content/v1.4/talos-guides/network/device-selector.md
website/content/v1.5/talos-guides/configuration/patching.md
website/content/v1.5/talos-guides/network/device-selector.md

Fixing typo in the documentation and tests
Fixes #7157
I did not run the`make conformance`, looks like there is no docker image available for arm64/v8
```
Unable to find image 'ghcr.io/siderolabs/conform:latest' locally
latest: Pulling from siderolabs/conform
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

fix: typos inteface -> interface (docs and tests) 

---

website/content/v1.5/learn-more/kubespan.md
website/content/v1.5/talos-guides/discovery.md
website/content/v1.5/talos-guides/network/kubespan.md

Update KubeSpan Docs
Closes #5234
Adds documentation around KubeSpan ports and supported topologies.

docs: Added information about KubeSpan ports and topology.

---

internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
internal/app/machined/pkg/controllers/k8s/static_pod_server.go
internal/app/machined/pkg/controllers/runtime/cri_image_gc.go

API server takes care of setting priority for "regular" pods from priorityClassName, but nothing does that for static pods, so we have to specify the priotity explicitly for static pods.
This fixes the graceful node shutdown (kubelet) to stop non-critical pods before the api-server and friends (critical pods).
Also some logging fixes.

fix: set the static pod priority as values

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/pkg/mount/all.go
internal/pkg/mount/mount.go
internal/pkg/mount/unmount.go

Fixes #7137
The `umount` syscall might hang "forever" if the underlying network filesystem endpoint is down.
To be on the safe side, add a timeout around unmount operations, and try to umount with force as a last resort.
Sample log:
```
14795.458779] [talos] task unmountPodMounts (2/2): unmounting /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/dbe8d7f58e21d06cbef1ae0849317661eba4e82776722e7db5c65194ad73e916/globalmount/0001-0009-rook-ceph-0000000000000001-1051beb3-8d7a-4291-bf45-5711c13523d1
[14795.459797] [talos] task unmountPodMounts (2/2): unmounting /var/lib/kubelet/pods/f3f4d789-7f48-4dd9-9ef5-649b002c8f9c/volumes/kubernetes.io~csi/pvc-a4e72749-a8a1-43d9-9152-5bc1f757c924/mount
[14795.460555] EXT4-fs (rbd0): unmounting filesystem.
[14813.461319] [talos] task …
```

fix: set timeout for unmount calls

---

Dockerfile
hack/nfsmount.conf
internal/app/machined/pkg/system/services/kubelet.go

Talos doesn't have `rpc.statsd` running, so mounting without locking is the only option. Some places in Kubernetes don't allow to set mount options for NFS, so setting defaults is the only way.
Fixes #6582

fix: enforce nolock option for all NFS mounts by default

---

pkg/machinery/constants/constants.go

There is another `KubeProxyImage` which we're actually using.

chore: clean up unused constant

---

hack/test/e2e.sh
internal/app/wrapperd/main.go

This reverts commit a2565f67416e9b9bc22f2d5506df9ea7771c0c8c.
The fix done in `a2565f67`, was actually a no-op caused by the misunderstanding the fix done in Go and backported to [Go 1.20.4](https://github.com/golang/go/commit/ecf7e00db8b8f5fff622f232bd8c515814c2ecc6). The fix gave a false confidence that it was working when it was tested against Talos `main` branch since the PR #7190 bumped `x/sys` package from [v0.7.0 -> v0.8.0](https://github.com/golang/go/commit/ecf7e00db8b8f5fff622f232bd8c515814c2ecc6), the actual change in `x/sys` can be found here at https://cs.opensource.google/go/x/sys/+/ff18efa0a3fa22d4fede381b822bbcfe53b7ee7c which meant that when updating Go to 1.20.4 the `x/sys` package should been updated too. The `x/sys` package changed how the syscall to set the rlimit was …

fix: revert: set rlimit explicitly in wrapperd

---

internal/app/machined/pkg/controllers/cluster/cluster_test.go
internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
internal/app/machined/pkg/controllers/cri/seccomp_profile_test.go
internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
internal/app/machined/pkg/controllers/network/hostname_config_test.go
internal/app/machined/pkg/controllers/network/link_spec_test.go
internal/app/machined/pkg/controllers/network/operator_spec_test.go
internal/app/machined/pkg/controllers/network/resolver_config_test.go
internal/app/machined/pkg/controllers/network/route_spec_test.go
internal/app/machined/pkg/controllers/network/timeserver_config_test.go
internal/app/machined/pkg/controllers/time/sync_test.go

chore: use ctest.UpdateWithConflicts instead of plain UpdateWithConflicts

---

Makefile
go.mod
go.sum

- github.com/benbjohnson/clock to v1.3.5
- cilium-cli to v0.14.3

chore: bump deps

---

cmd/installer/cmd/image.go
cmd/installer/cmd/root.go
cmd/installer/pkg/install/install.go
cmd/installer/pkg/ova/ova.go
cmd/installer/pkg/raw.go

This PR adds a flag to imager that allows for tweaking the size of the created disk. Additionally, it sets the default value of that created disk to 10GB, as most images are cloud images that fail when uploaded b/c it only picks up a 1GB disk currently. Also adds some conditionals to the makefile to make sure we set the default small value for metal images and SBCs.

chore: update default image sizes to 10GB for all "cloud" images

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go

Fixes #7246
The problem was that `udevd` watches via `inotify` any attempts to open blockdevices with 'write' access.
Talos was opening with write access, but actually accessing as read-only, so the fix is to open as read-only.

fix: race with `udevd` and `mountUserDisks`

---

cmd/installer/pkg/install/preflight.go

This was discovered during 1.5.0-alpha.0 release, backporting it to release-1.4.

fix: correct upgrade Talos version check

---

cmd/installer/pkg/raw.go

This PR changes the default disk size for cloud images to be 8GiB instead. This was prompted b/c the disk price in azure between tiers is doubled and the cutoff for the tier is 8GiB.

chore: use 8GiB instead of 10GiB for cloud images

---

pkg/cluster/kubernetes/talos_managed.go
pkg/kubernetes/kubernetes.go

Fixes #7253
Also fix the case that `kube-proxy` version was updated in the machine config in `--dry-run` mode.

fix: fall back to external IP when discovering nodes in upgrade-k8s

---

.drone.jsonnet
Dockerfile
Makefile

This cleans up `Dockerfile` and `Makefile` targets to be in similar parity with `kres` auto-generated targets.
Now `make talosctl` would only build the one for the specific local machine making development easier. Also added a `iso` docker target that builds iso for local development without having to push and pull the imager. (`make local-iso DEST=_out`)

chore: faster dev cycle

---

cmd/talosctl/cmd/talos/upgrade-k8s.go

fix: fail quickly if upgrade-k8s is used with multiple nodes

---

website/content/v1.4/kubernetes-guides/upgrading-kubernetes.md
website/content/v1.5/kubernetes-guides/upgrading-kubernetes.md

Add a link to the support matrix page in the upgrading Kubernetes guide.
I was working on my Talos update procedure, and it wasn't immediately obvious to me how I should upgrade K8S. I [opened a discussion to ask](https://github.com/siderolabs/talos/discussions/7242#discussioncomment-5942386). I think this small change will make it easier for others.

feat: link support matrix in k8s update doc

---

website/content/v1.5/talos-guides/upgrading-talos.md

Recommend using talosctl x.y.z to update a cluster running x.y.z to a later version.
I assume this is the right policy, but I had some doubts, so maybe it's nice to clarify (maybe on non-patches updates it's significant?).

Document talosctl version for updates

---

pkg/machinery/constants/constants.go
website/content/v1.5/reference/configuration.md

Replace docker.io with registry.k8s.io for the coredns image.
registry.k8s.io is the official kubernetes registry. Dockerhub has a pull limit for unauthenticated image pulls and this can cause outages if you spend your entire quota.
For these reasons I think registry.k8s.io is a better default for most Talos users.

chore: registry.k8s.io for coredns image

---

.drone.jsonnet
Dockerfile
cmd/installer/cmd/image.go

Use `pigz` and `--sparse` to handle more efficiently compression of the assets.
Also move tasks out of `setup-ci` step, as it runs always, including for the promoted pipelines.

chore: optimize image generation time

---

internal/pkg/dashboard/configurl.go
internal/pkg/dashboard/dashboard.go

If the dashboard is run without the "Config URL" screen, do not initialize it, and do not probe the kernel args for the code parameter.
Refactor the dashboard to do not construct the unused screens at all.
Closes siderolabs/talos#7300.

fix: do not probe kernel args in dashboard if not needed

---

pkg/machinery/config/config/document.go
pkg/machinery/config/configloader/internal/decoder/decoder.go
pkg/machinery/config/configloader/internal/decoder/decoder_test.go
pkg/machinery/config/configpatcher/apply_test.go
pkg/machinery/config/configpatcher/json6902.go
pkg/machinery/config/configpatcher/strategic.go
pkg/machinery/config/configpatcher/testdata/multidoc/config.yaml
pkg/machinery/config/configpatcher/testdata/multidoc/expected.yaml
pkg/machinery/config/configpatcher/testdata/multidoc/jsonpatch.yaml
pkg/machinery/config/configpatcher/testdata/multidoc/strategic1.yaml
pkg/machinery/config/configpatcher/testdata/multidoc/strategic2.yaml
pkg/machinery/config/container/container.go
pkg/machinery/config/container/container_test.go
pkg/machinery/config/provider.go
pkg/machinery/config/types/meta/meta.go
pkg/machinery/config/types/siderolink/siderolink.go
pkg/machinery/config/types/siderolink/siderolink_test.go
pkg/machinery/config/types/siderolink/testdata/document.yaml
pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
website/content/v1.5/talos-guides/configuration/patching.md

Other changes:
* renamed `version:` to `apiVersion:` in the multi-doc format, as this better matches Kubernetes objects
* introduced (not used at the moment) a concept of `NamedDocuments` (many documents for the same type)
* added container validation on not having duplicate documents
* JSON6902 now denies multi-doc config
Fixes #7312

feat: add support for multi-doc strategic merge patching

---

cmd/installer/cmd/image.go

Use `pigz` (parallel) instead of `gzip`.
Use `xz` compression `-0` instead of `-6`.
This has pros and cons:
* image size goes up (77M -> 79M) (+2.5%)
* image generation goes down 19s -> 10s (-50%).

chore: optimize image compression

---

cmd/installer/pkg/iso.go
cmd/talosctl/cmd/mgmt/cluster/create.go
hack/ukify/main.go
hack/ukify/measure/measure_test.go
pkg/provision/options.go
pkg/provision/providers/qemu/arch.go
pkg/provision/providers/qemu/destroy.go
pkg/provision/providers/qemu/launch.go
pkg/provision/providers/qemu/node.go
pkg/provision/providers/qemu/pflash.go
pkg/provision/providers/qemu/preflight.go
pkg/provision/providers/qemu/tpm2.go
pkg/provision/providers/vm/dhcpd.go
pkg/provision/providers/vm/loadbalancer.go
pkg/provision/providers/vm/node.go
pkg/provision/providers/vm/process.go
pkg/provision/result.go
website/content/v1.5/reference/cli.md

Add qemu support for secureboot testing via `talosctl cluster create`.
Can be tested via:
```bash
sudo -E _out/talosctl-linux-amd64 cluster create --provisioner=qemu $REGISTRY_MIRROR_FLAGS --controlplanes=1 --workers=1 --iso-path=_out/talos-uki-amd64.iso --with-secureboot=true --with-tpm2=true --skip-injecting-config --with-apply-config
```
This currently only supports just booting Talos in SecureBoot mode. Installation and Upgrade comes as extra PRs.
Fixes: #7324

feat: qemu secureboot

---

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_test.go

This changes the mounting/unmounting of `BOOT` partiton code into `kexecPrepare` phase. Also skips if `BOOT` partition cannot be found.

chore: unify kexec phase

---

.drone.jsonnet
cmd/talosctl/cmd/mgmt/cluster/create.go
hack/test/e2e-qemu.sh
pkg/cluster/bootstrap.go
pkg/provision/providers/qemu/create.go
pkg/provision/providers/vm/network.go
pkg/provision/request.go
website/content/v1.5/reference/cli.md

Add flags for configuring the qemu bridge interface with chaos options:
- network-chaos-enabled
- network-jitter
- network-latency
- network-packet-loss
- network-packet-reorder
- network-packet-corrupt
- network-bandwidth
These flags are used in /pkg/provision/providers/vm/network.go at the end of the CreateNetwork function to first see if the network-chaos-enabled flag is set, and then check if bandwidth is set.  This will allow developers to simulate clusters having a degraded WAN connection in the development environment and testing pipelines.
If bandwidth is not set, it will then enable the other options.
- Note that if bandwidth is set, the other options such as jitter, latency, packet loss, reordering and corruption will not be used.  This is for two reasons:
- Restriction the …

feat: add network chaos to qemu development environment

---

internal/pkg/partition/format.go
internal/pkg/partition/format_test.go

Use the `go-blockdevice` library to zero partitions.
Also added a test that writes `ones` to the partition and verifies its zeroes after zeroing it.

chore: use go-blockdevice for zeroing partitions

---

go.sum
internal/app/machined/pkg/controllers/cluster/discovery_service.go
pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
pkg/machinery/go.mod
pkg/machinery/go.sum

Fixes #7333
Also fixed the discovery service controller to reconnect the client on config changes (previously it wasn't reactive on e.g. URL changes).

fix: allow http:// for discovery service URL

---

cmd/installer/cmd/install.go

There is no need that the value of err is assigned to itself. 
So removes this self assignment.

chore: clean up unnecessary self assignment

---

cmd/installer/pkg/install/meta_value.go
cmd/installer/pkg/install/preflight.go
cmd/talosctl/cmd/mgmt/cluster/create.go

Struct MetaValue has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation. Modifies the receiver usage.
Variable config collides with imported package name. Renames the variable config.
Removes a redundant alias.
Empty slice declaration uses a literal. Replaces with nil slice declaration.

chore: modify some usages that are not recommended

---

pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
website/content/v1.5/reference/configuration.md

Include a description and a commented-out example for the `cluster.allowSchedulingOnControlPlanes` field on `talosctl gen config ...` output.
Closes siderolabs/talos#7313.

docs: include `allowSchedulingOnControlPlanes` on `talosctl gen config` output

---

Dockerfile
website/content/v1.5/advanced/customizing-the-kernel.md
website/content/v1.5/talos-guides/configuration/nvidia-gpu-proprietary.md

This fixes usage of custom kernel images to copy over the modules info list and the default set of modules shipped with Talos.

fix: usage of custom kernels

---

hack/test/e2e.sh

Due to a bug (?) cilium tests don't clean up all the deployments & pods, leaving one pod in 'Pending' state.
Kubernetes e2e tests check for !Runing pods in `kube-system` namespace.
Fix by moving cilium tests to a separate namespace.

test: fix cilium integration tests

---

hack/test/e2e-qemu.sh
hack/test/e2e.sh
internal/integration/cli/jsonpath.go

`WITH_CONFIG_PATCH_WORKER` check result was overriding any value set in `CONFIG_PATCH_FLAG` variable. Move it to the different variable.

chore: fix cilium e2e tests

---

cmd/installer/pkg/install/install.go
cmd/installer/pkg/install/manifest.go
cmd/installer/pkg/install/manifest_test.go
cmd/installer/pkg/install/target.go
internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
internal/app/machined/pkg/controllers/k8s/node_apply.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/assets/assets.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/boot_label.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/decode.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/encode.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub_test.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/probe.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/revert.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/revert.go
internal/pkg/mount/options.go

Move labels out of the bootloader interface, while moving copying assets into the bootloader interface. GRUB is using one set of assets, `sd-boot` will be using another one.
Fix the problem with `bootloader.Probe()` finding boot partition on the host when it runs in a priv container, fixing issues with image creation in the CI.

refactor: bootloader interface, labels

---

.drone.jsonnet
Dockerfile
cmd/installer/pkg/install/install.go
cmd/installer/pkg/install/manifest.go
cmd/installer/pkg/install/manifest_test.go
go.mod
go.sum
hack/test/e2e-qemu.sh
hack/test/e2e.sh
internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/efivars.go
internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
internal/pkg/install/install.go
internal/pkg/mount/pseudo.go
pkg/machinery/constants/constants.go
pkg/provision/providers/qemu/arch.go
pkg/provision/providers/qemu/launch.go
pkg/provision/providers/qemu/pflash.go

This includes sd-boot handling, EFI variables, etc.
There are some TODOs which need to be addressed to make things smooth.
Install to disk, upgrades work.

feat: implement secure boot from disk

---

website/content/v1.0/talos-guides/install/virtualized-platforms/hyper-v.md
website/content/v1.1/talos-guides/install/virtualized-platforms/hyper-v.md
website/content/v1.2/talos-guides/install/virtualized-platforms/hyper-v.md
website/content/v1.3/talos-guides/install/virtualized-platforms/hyper-v.md
website/content/v1.4/talos-guides/install/virtualized-platforms/hyper-v.md
website/content/v1.5/talos-guides/install/virtualized-platforms/hyper-v.md

- Small update to documentation, basically looks like the maintainer of another [referenced project](https://github.com/nebula-it/New-TalosVM) changed their folder structure, thus resulting in a broken link in your documentation.
- Just trying to provide a better documentation experience to the lowly Windows users out there 😄
- Very small change, love the project and your docs to just happy to keep them clean.
Re-submitted with conventional commit.

docs: fix broken link to powershell module

---

internal/app/machined/main.go

Only compare the basename of the 0th argument.
Took me more than a day to debug why
```c
execl("/sbin/poweroff", "poweroff", (char *)NULL);
```
was not working in https://github.com/siderolabs/extensions/pull/173, only to discover that 
```c
execl("/sbin/poweroff", "/sbin/poweroff", (char *)NULL);
```
does work.

Compare only basename of `os.Args[0]`.

---

Dockerfile
internal/app/machined/main.go

Some tools like qemu-guest-agent when ran as a extension service calls `/sbin/shutdown` instead of `/sbin/poweroff`. This adds handling for the same.
Ref: https://github.com/siderolabs/extensions/pull/173

chore: add `/sbin/shutdown`

---

Dockerfile
hack/lvm.conf

Fixes #3129
Talos does not have a good location to keep LVM metadata backups.

fix: disable LVM backups/archive

---

cmd/installer/cmd/iso.go
cmd/installer/cmd/root.go
cmd/installer/pkg/install/meta_value.go
cmd/installer/pkg/install/meta_value_test.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_state.go
internal/pkg/meta/meta.go
pkg/machinery/constants/constants.go
pkg/machinery/meta/meta.go
pkg/machinery/meta/meta_test.go

Previously, if META values were supplied to the Talos ISO via environment variable, they will be written down and available after the install. With this fix, values are also readable and available before the installation runs (in maintenance mode).
Most of the PR is refactoring `meta.Value(s)` to be a shared library which is used by the installer/imager and (now) Talos.
Also fixes an issue with not returning properly `NotExist` error when META is not yet available as a partition on disk.

fix: provide stashed META values before installation

---

go.mod
go.sum
hack/release.toml
internal/app/machined/pkg/system/services/export_test.go
internal/app/machined/pkg/system/services/extension.go
internal/app/machined/pkg/system/services/extension_test.go
pkg/machinery/extensions/services/services.go
website/content/v1.5/advanced/extension-services.md

Supports setting `environmentFile` for Talos System Extension Services.
Fixes: #7316

feat: support environment file for extensions

---

internal/app/machined/pkg/controllers/k8s/templates.go

Pod security standard requires that ALL is in caps
See https://github.com/kyverno/policies/issues/413 for some discussion

fix: capabilities including `ALL` should be uppercase

---

cmd/talosctl/cmd/talos/edit.go
cmd/talosctl/cmd/talos/patch.go
cmd/talosctl/pkg/talos/yamlstrip/testdata/malformed.in.yaml
cmd/talosctl/pkg/talos/yamlstrip/testdata/malformed.out.yaml
cmd/talosctl/pkg/talos/yamlstrip/testdata/multidoc.in.yaml
cmd/talosctl/pkg/talos/yamlstrip/testdata/multidoc.out.yaml
cmd/talosctl/pkg/talos/yamlstrip/yamlstrip.go
cmd/talosctl/pkg/talos/yamlstrip/yamlstrip_test.go

Fixes #7425
The previously used method doesn't handle YAML multi-doc, incorrectly stripping only the first document and throwing away everything else.

fix: properly handle YAML comment stripping for multi-doc

---

internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go

Fixes #7416
These platforms don't have video console access.

fix: disable dashboard on Azure, GCP and Scaleway

---

pkg/machinery/constants/constants.go

Add extra vendor info in `os-release`.
Fixes: #7446

chore: add vendor info

---

internal/pkg/secureboot/measure/internal/pcr/bank_data.go
internal/pkg/secureboot/measure/internal/pcr/policy.go
internal/pkg/secureboot/measure/internal/pcr/policy_test.go

No real change, just using library to do the work (should be more readable).

refactor: use tpm2 library to calculate policy hash
