siderolabs/talos

CHANGELOG.md, go.mod, website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5386)
=> release(v1.0.3): prepare release

netlify.toml
Fixes the URL from Netlify given to Hugo
to build absolute URLs with the proper base.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5392)
=> docs: fix netlify deploy url

website/content/v1.1/learn-more/discovery.md
Fix typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5390)
=> docs: Fix typos in Discovery.md

internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go, internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go, internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go, internal/app/machined/pkg/controllers/k8s/manifest_apply.go, internal/app/machined/pkg/controllers/network/operator/vip.go, internal/app/machined/pkg/controllers/secrets/etcd.go, internal/app/machined/pkg/controllers/secrets/kubernetes.go, internal/app/machined/pkg/controllers/secrets/kubernetes_test.go, internal/app/machined/pkg/controllers/time/sync.go, internal/app/machined/pkg/controllers/time/sync_test.go, internal/app/machined/pkg/controllers/v1alpha1/service.go, pkg/machinery/resources/time/condition.go, pkg/machinery/resources/time/status.go, pkg/machinery/resources/v1alpha1/service.go
No functional changes, just pure refactoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5442)
=> refactor: convert time & v1alpha1 resources to use typed.Resource

go.mod, go.sum, internal/app/machined/pkg/controllers/k8s/endpoint.go, internal/app/machined/pkg/controllers/k8s/kubelet_static_pod_controller.go, internal/app/machined/pkg/controllers/k8s/manifest_apply.go, internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go, internal/app/machined/pkg/controllers/secrets/etcd.go, internal/app/machined/pkg/controllers/secrets/kubernetes.go, internal/app/machined/pkg/controllers/secrets/kubernetes_test.go, internal/app/machined/pkg/system/services/etcd.go, pkg/machinery/go.mod, pkg/machinery/go.sum, pkg/machinery/resources/secrets/api.go, pkg/machinery/resources/secrets/cert_sans.go, pkg/machinery/resources/secrets/etcd.go, pkg/machinery/resources/secrets/etcd_root.go, pkg/machinery/resources/secrets/kubelet.go, pkg/machinery/resources/secrets/kubernetes.go, pkg/machinery/resources/secrets/kubernetes_root.go, pkg/machinery/resources/secrets/os_root.go
No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5443)
=> refactor: convert secrets resources to use typed.Resource

internal/app/machined/pkg/controllers/perf/perf_test.go, pkg/machinery/resources/perf/cpu.go, pkg/machinery/resources/perf/mem.go
No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5448)
=> refactor: rewrite perf resource to use typed.Resource

cmd/installer/pkg/install/manifest.go, internal/app/machined/pkg/controllers/files/cri_config_parts.go, internal/app/machined/pkg/controllers/k8s/kubelet_spec.go, internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, internal/app/machined/pkg/system/service_runner.go, internal/app/machined/pkg/system/services/extension.go, internal/app/machined/pkg/system/services/kubelet.go, internal/app/machined/pkg/system/system.go, internal/app/machined/pkg/system/system_test.go, pkg/cluster/kubernetes/talos_managed.go, pkg/machinery/config/types/v1alpha1/v1alpha1_unstructured.go, pkg/machinery/config/types/v1alpha1/v1alpha1_unstructured_test.go, pkg/machinery/constants/constants.go, website/content/docs/v1.0/Learn More/knowledge-base.md
- #5384 
- #5387 
- #5395 
- #5412 
- ~#5444~
- #5445
- #5451 
- #5453 
- #5456
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5459)
=> backports: for v1.0.4

CHANGELOG.md, go.mod, website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.4 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5462)
=> release(v1.0.4): prepare release

pkg/machinery/resources/k8s/static_pod.go, pkg/machinery/resources/k8s/static_pod_status.go, pkg/machinery/resources/network/node_address.go
This two required some additional attention and were split into separate branch from #5472.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5497)
=> chore: refactor StaticPod and StaticPodStatus into typed.Resource

website/content/v1.1/learn-more/networking-resources.md
Remove outdated information and some small additions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5504)
=> docs: update networking resource documentation

internal/pkg/logind/broker.go
Fixes #5511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5531)
=> fix: remove D-Bus sockets before listen attempts

ADOPTERS.md
Add us to list of adopters
Because we adopt and occasionally even send patches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5524)
=> Add Equinix Managed Services NL to adopters

website/content/v1.0/_index.md
This updates download links and references to the latest release
available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5540)
=> docs: update latest Talos in 1.0 docs to 1.0.4

internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
I had a bug:
```
[   18.220624] [talos] failed to fetch external IPs, ignored: failed to download config from "http://169.254.169.254/latest/meta-data/public-ipv4": 1 error(s) occurred:
[   18.228957]  failed to fetch external addresses from metadata service
[   18.232621] [talos] restarting platform network config {"component": "controller-runtime", "controller": "network.PlatformConfigController", "interval": "7.343444983s", "error": "ParseIP(\"\"): unable to parse IP"}
```
If the ip_address string is empty the ParseIP will fail.
I've noticed that custom route creator in wrong position in switch/case block.
And more debug messages. …
=> fix: openstack unable to parseIP

website/content/v1.0/talos-guides/install/cloud-platforms/vultr.md, website/content/v1.1/talos-guides/install/cloud-platforms/vultr.md
Adds an installation guide for the Vultr cloud platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5549)
=> docs: add vultr guide

Makefile, hack/release.toml
Update tools, pkgs and extras
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5539)
=> chore: update deps to go 1.17.10

internal/app/machined/pkg/controllers/kubespan/manager.go, internal/app/machined/pkg/controllers/network/link_spec.go, internal/app/machined/pkg/controllers/network/link_status.go
This is required when running Talos in a container when host OS kernel
doesn't have support for Wireguard.
The failure is deferred so that controller actually fails when it needs
the wireguard client, but if wireguard is not used, controller continues
running.
This should fix errors when running Talos on Docker/WSL:
```
[talos] 2022/05/11 08:52:28 controller failed {"component": "controller-runtime", "controller": "network.LinkStatusController", "error": "error creating wireguard client: setsockopt: protocol not available"}
[talos] 2022/05/11 08:50:48 controller failed {"component": "controller-runtime", "controller": "kubespan.ManagerController", "error": "error creating wireguard client: setsockopt: protocol not available"}
[talos] 2022/05/11 08:50:32 controller failed {"component": …
```
=> fix: ignore failures to dial wireguard client

website/content/v1.0/learn-more/architecture.md, website/content/v1.0/learn-more/concepts.md, website/content/v1.1/learn-more/architecture.md, website/content/v1.1/learn-more/concepts.md
A few typos here and there. Excised some excess.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5551)
=> docs: fix typos, edited for clarity

pkg/provision/providers/docker/docker.go
Docker on WSL seems to have same issue as Docker/OS X and
Docker/Windows: container IPs are not routable from the host, so we need
to apply same "magic" by using exposed ports.
WSL `talosctl` binary is built for Linux, so we need to do additional
checks for the platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5560)
=> fix: detect WSL for `talosctl cluster create` on Docker

hack/release.toml, internal/app/machined/pkg/controllers/kubespan/manager.go, internal/app/machined/pkg/controllers/network/link_spec.go, internal/app/machined/pkg/controllers/network/link_status.go, internal/app/machined/pkg/controllers/network/operator/dhcp6.go, internal/app/machined/pkg/controllers/secrets/api_cert_sans.go, internal/app/machined/pkg/controllers/secrets/api_cert_sans_test.go, internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans.go, internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans_test.go, internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, internal/app/machined/pkg/system/services/extension.go, internal/integration/api/version.go, internal/integration/base/base.go, internal/integration/integration_test.go, internal/pkg/logind/broker.go, pkg/machinery/config/types/v1alpha1/generate/example_test.go, pkg/machinery/config/types/v1alpha1/generate/generate.go, pkg/machinery/config/types/v1alpha1/generate/init.go, pkg/machinery/constants/constants.go, pkg/machinery/resources/secrets/cert_sans.go, pkg/provision/providers/docker/docker.go, pkg/provision/providers/qemu/arch.go, website/content/docs/v1.0/Reference/configuration.md
- #5461 
- #5403 
- #5518 
- #5530 
- #5531 
- #5528 
- #5509 
- #5535 
- #5537 
- #5541 
- #5542 
- #5543 
- #5544 
- #5547 
- #5560
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5567)
=> backports: for v1.0.5

CHANGELOG.md, go.mod, website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.5 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5572)
=> release(v1.0.5): prepare release

ADOPTERS.md
Add a markdown newline marker (double-space) to Equinix Metal entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5571)
=> docs: tidy up adopters

pkg/cluster/check/kubernetes.go
This fixes an error when integration test become stuck with the message
like:
```
waiting for coredns to report ready: some pods are not ready: [coredns-868c687b7-g2z64]
```
After some random sequence of node restarts one of the pods might become
"stuck" in `Completed` state (as it is shown in `kubectl get pods`)
blocking the check, as the pod will never become ready.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5574)
=> fix: ignore completed pods in cluster health check

website/content/v1.0/talos-guides/configuration/logging.md, website/content/v1.1/talos-guides/configuration/logging.md
Adding information on setting up forwarding talos logs to vector, along with a suggested config for on-forwarding to a Grafana Loki instance
Give users a suggested path forward on another excellent logging solution to ease their setup & usage with talos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5591)
=> docs: add example of forwarding talos logs to vector

go.mod, go.sum, internal/app/machined/pkg/controllers/siderolink/manager.go, internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go, internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go, internal/pkg/encryption/keys/nodeid.go
go-smbios library updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5598)
=> chore: go-smbios updates

website/content/v1.1/introduction/support-matrix.md
Update 1.1.x support matrix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5604)
=> docs: fix 1.1.x support matrix

pkg/cluster/check/default.go, pkg/cluster/check/etcd.go
Add new health check which waits for all etcd members. Closes #5552.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5587)
=> feat: add 'etcd membership is consistent across nodes' health check

website/content/v1.1/advanced/extension-services.md
Explain extension service `container.security` options
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5622)
=> docs: extension service security options

website/content/v1.0/talos-guides/install/virtualized-platforms/vmware.md
Fix VMWare install script url
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5631)
=> docs: fix install script url

go.mod, go.sum, pkg/machinery/go.mod, pkg/machinery/go.sum
In preparation for beta release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5657)
=> chore: update Sidero Labs go modules to released versions

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.1/reference/configuration.md
See https://github.com/coredns/coredns/releases/tag/v1.9.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5658)
=> feat: update CoreDNS to 1.9.3

go.mod, go.sum, pkg/machinery/config/decoder/decoder_test.go, pkg/machinery/go.mod, pkg/machinery/go.sum
The updated version has several important bugfixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5659)
=> chore: update go yaml to the latest version

internal/app/machined/pkg/controllers/k8s/extra_manifest.go, internal/app/machined/pkg/controllers/network/etcfile.go, internal/app/machined/pkg/controllers/network/etcfile_test.go
Cosmetic fix, 
align records by ipv4-string size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5663)
=> fix: table align hosts file

internal/app/machined/pkg/controllers/network/operator/vip.go
Fix a bug: when etcd session is closed during election campaign, we
should quit the campaign instead of continuing which is the case when
the election was won (bug found by @frezbo).
Also in the same controller, even before election is won, we should
observe changes to kubelet lifecycle and etcd lifecycle events to make
sure we quit the campaign on appropriate events. This fixes a delay on
kubelet shutdown of control plane when VIP is enabled, but the node
doesn't own the VIP on upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5679)
=> fix: improve vip operator shutdown sequence

Makefile, cmd/installer/cmd/grub.iso.cfg, cmd/installer/cmd/iso.go, go.mod, go.sum, hack/release.toml, internal/app/machined/pkg/controllers/k8s/kubelet_service.go, internal/app/machined/pkg/controllers/network/operator/vip.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go, pkg/cluster/check/kubernetes.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types.go, pkg/machinery/constants/constants.go, pkg/provision/providers/docker/docker.go, website/content/docs/v1.0/Learn More/knowledge-base.md, website/content/docs/v1.0/Reference/configuration.md
- #5574 
- #5593
- #5595
- #5633 
- #5679 
- #5680 
- #5703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5704)
=> backports: for v1.0.6

pkg/cluster/check/default.go, pkg/cluster/check/etcd.go
Add new health check which checks if the etcd members match control plane nodes. Closes siderolabs#5553.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5682)
=> feat: add 'etcd members should be control plane nodes' health check

CHANGELOG.md, go.mod, hack/release.toml, website/content/docs/v1.0/Reference/cli.md
This is the official v1.0.6 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5708)
=> release(v1.0.6): prepare release

cmd/talosctl/cmd/mgmt/cluster/show.go, cmd/talosctl/cmd/mgmt/loadbalancer_launch.go, cmd/talosctl/cmd/talos/config.go, cmd/talosctl/cmd/talos/dashboard/components/graphs.go, cmd/talosctl/cmd/talos/dashboard/components/nodetabs.go, cmd/talosctl/cmd/talos/dashboard/data/node.go, cmd/talosctl/cmd/talos/root.go, cmd/talosctl/pkg/talos/helpers/mode.go, internal/app/apid/pkg/director/director.go, internal/app/machined/internal/server/v1alpha1/v1alpha1_monitoring.go, internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go, internal/app/machined/pkg/adapters/k8s/manifest.go, internal/app/machined/pkg/adapters/network/wireguard_spec.go, internal/app/machined/pkg/adapters/perf/cpu.go, internal/app/machined/pkg/controllers/cluster/discovery_service.go, internal/app/machined/pkg/controllers/config/k8s_control_plane.go, internal/app/machined/pkg/controllers/files/cri_registry_config.go, internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go, internal/app/machined/pkg/controllers/k8s/kubelet_config.go, internal/app/machined/pkg/controllers/k8s/kubelet_spec.go, internal/app/machined/pkg/controllers/k8s/manifest_apply.go, pkg/cluster/check/etcd.go, pkg/machinery/generic/maps/maps.go, pkg/machinery/generic/maps/maps_test.go, pkg/machinery/generic/slices/slices.go, pkg/machinery/generic/slices/slices_test.go
Things like ToSet, Keys etc...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5702)
=> chore: add generic methods and use them 1/n

website/content/v1.0/_index.md, website/content/v1.1/_index.md
Fix latest release version in docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5721)
=> docs: fix latest release version in docs

website/content/v1.0/kubernetes-guides/network/kubespan.md, website/content/v1.1/kubernetes-guides/network/kubespan.md
Add more contextual description of the discovery service
to the KubeSpan docs, and a link to the repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5727)
=> docs: add link to discovery service in kubespan

website/content/v1.1/_index.md, website/content/v1.1/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md, website/content/v1.1/kubernetes-guides/configuration/storage.md, website/content/v1.2/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md, website/content/v1.2/kubernetes-guides/configuration/storage.md, website/layouts/shortcodes/iscsi_tools_system_extension_release.html
Add docs on using OpenEBS Jiva that works well with local storage and
`iscsi-tools` extension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5745)
=> docs: openebs jiva example with iscsi-tools extension

internal/app/machined/pkg/controllers/ctest/ctest.go, internal/app/machined/pkg/controllers/secrets/api_cert_sans_test.go, internal/app/machined/pkg/controllers/secrets/api_test.go, internal/app/machined/pkg/controllers/secrets/kubelet_test.go, internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans_test.go, internal/app/machined/pkg/controllers/secrets/kubernetes_test.go, internal/app/machined/pkg/controllers/siderolink/manager_test.go
This change adds ctest package which adds DefaultSuite and helper functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5744)
=> feat: add ctest package and base for test suite

website/content/_index.html
This PR ensures we look cool on twitter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5778)
=> docs: add twitter meta info

website/config.toml, website/content/v1.0/_index.md, website/content/v1.0/introduction/support-matrix.md, website/content/v1.1/_index.md, website/content/v1.1/introduction/support-matrix.md, website/content/v1.1/introduction/what-is-new.md, website/content/v1.1/kubernetes-guides/configuration/pod-security.md, website/content/v1.1/talos-guides/upgrading-talos.md, website/content/v1.2/introduction/support-matrix.md, website/content/v1.2/kubernetes-guides/configuration/pod-security.md
Update documentation, support matrix, current release, what's new, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5787)
=> docs: update docs for release 1.1

website/content/v1.0/talos-guides/install/cloud-platforms/upcloud.md, website/content/v1.1/talos-guides/install/cloud-platforms/upcloud.md, website/content/v1.2/talos-guides/install/cloud-platforms/upcloud.md
Installation guide for UpCloud
I use UpCloud, saw there was no guide, had to figure it out on my own and wrote a guide so others don't have to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5785)
=> Add UpCloud install guide

website/content/v0.14/guides/logging.md, website/content/v1.0/talos-guides/configuration/logging.md, website/content/v1.1/talos-guides/configuration/logging.md, website/content/v1.2/talos-guides/configuration/logging.md
See https://github.com/siderolabs/talos/issues/4880#issuecomment-1170965112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5845)
=> docs: note that kernel cmdline params are only applied on upgrade

internal/app/machined/pkg/controllers/kubespan/peer_spec.go, internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go
Instead of dropping whole peer try to find non-overlapping set of IPs to
route to.
Fixes #5828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/siderolabs/talos/5866)
=> fix: perform accurate conflict resolution on overlap (kubespan)

website/content/v0.10/bare-metal-platforms/equinix-metal.md, website/content/v0.11/bare-metal-platforms/equinix-metal.md, website/content/v0.12/bare-metal-platforms/equinix-metal.md, website/content/v0.13/bare-metal-platforms/equinix-metal.md, website/content/v0.14/bare-metal-platforms/equinix-metal.md, website/content/v0.8/bare-metal-platforms/equinix-metal.md, website/content/v0.9/bare-metal-platforms/equinix-metal.md, website/content/v1.0/talos-guides/install/bare-metal-platforms/equinix-metal.md, website/content/v1.1/talos-guides/install/bare-metal-platforms/equinix-metal.md, website/content/v1.2/talos-guides/install/bare-metal-platforms/equinix-metal.md
=> website: Fix typos

website/content/v1.1/_index.md
=> docs: update last release for 1.1

.drone.jsonnet, Dockerfile, go.mod, go.sum
add FreeBSD support to talosctl 
I want to be able to run talosctl from my base server for the bhyve VM's of Talos I have running
=> Initial cut for talosctl for FreeBSD (amd64/arm64)

website/content/v1.0/talos-guides/upgrading-talos.md, website/content/v1.1/talos-guides/upgrading-talos.md, website/content/v1.2/talos-guides/upgrading-talos.md
Improve working on Talos upgrade vs Kubernetes upgrades.
=> docs: improve talos kubernetes upgrade note

website/content/v0.14/introduction/quickstart.md, website/content/v1.0/introduction/quickstart.md, website/content/v1.1/introduction/quickstart.md, website/content/v1.2/introduction/quickstart.md
This PR removes katacoda links since katacoda is dead now :(
=> docs: remove katacoda links

README.md
Fixed spelling and grammar errors in the readme file
=> Fixed spelling and grammar errors in README.md

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
The `PacketSource` interface is racy, as it provides a channel to read
packets from, while packets are read in a (invisible) goroutine, so
closing the capture handle creates a data race with reading.
Unwrap that goroutine into an explicit loop to avoid the race.
=> fix: data race in packet capture (part 2)

website/content/v1.0/talos-guides/upgrading-talos.md, website/content/v1.1/talos-guides/upgrading-talos.md, website/content/v1.2/talos-guides/upgrading-talos.md
Fix broken links in the 'Upgrading Talos' docs.
=> docs: Add missing <> to relref.

pkg/machinery/client/client.go
When message is sent via the proxy, `metadata.error` carries only string
representation which can't be unmarshalled back into an `error` which we
can match against. A similar fix was already done for "unary" responses,
but we missed the streaming case.
This fixes a spurious failure in integration tests when calling
`talosctl pcap --duration 1s`.
=> fix: correctly unwrap errors when streaming

internal/integration/api/reset.go
And improve retry logic in the test.
=> fix: skip `ResetDuringBoot` test if the `Cluster` config is unknown

internal/app/machined/pkg/controllers/network/node_address.go, internal/app/machined/pkg/controllers/network/node_address_test.go
This fixes a case when some IP which became default at some point was
removed completely from the node. In that case Talos should set default
address to another address, as having default IP not on the node doesn't
make much sense.
=> fix: update default address if removed from the host

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Fixes: https://github.com/siderolabs/talos/issues/5342
Now the sequencer is smart enough to skip `LeaveEtcd` and
`CordonAndDrain` node if the node is not fully joined to the cluster
yet.
=> fix: make reset work even if the node is not bootstrapped/not joined

website/content/v1.0/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.1/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.2/talos-guides/install/cloud-platforms/gcp.md
Fixes #6034
Fixes #6035
Closes #6027
=> docs: fix issues in GCP docs

internal/app/maintenance/server/server.go
The issue was introduced in PR #6042
=> fix: properly filter resources in maintenance server

website/content/v1.2/introduction/system-requirements.md, website/content/v1.2/learn-more/control-plane.md, website/content/v1.2/talos-guides/install/cloud-platforms/aws.md
This PR removes obsolete references
=>  docs: remove obsolete references to init nodes

.drone.jsonnet, hack/release.toml, internal/integration/api/discovery.go, pkg/machinery/config/contract.go, pkg/machinery/config/contract_test.go, pkg/machinery/config/types/v1alpha1/generate/init.go, pkg/machinery/config/types/v1alpha1/generate/worker.go, website/content/v1.2/kubernetes-guides/configuration/discovery.md
=> feat: disable Kubernetes discovery backend by default

go.mod, go.sum, go.work.sum, pkg/machinery/go.mod, pkg/machinery/go.sum, pkg/machinery/proto/proto.go, pkg/machinery/resources/k8s/admissioncontrol_config.go, pkg/machinery/resources/network/link_status.go
Forgot about it. Also bump protoenc and fix encoders/decoders.
=> fix: add missing LinkStatusType registration

website/content/v1.0/talos-guides/install/cloud-platforms/digitalocean.md, website/content/v1.1/talos-guides/install/cloud-platforms/digitalocean.md, website/content/v1.2/talos-guides/install/cloud-platforms/digitalocean.md
=> Fix verbiage in Digital Ocean tutorial

website/content/v1.2/talos-guides/install/cloud-platforms/aws.md
=> Clarification of AWS set up process

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_priority_lock.go
Looks like `cancelCtx` access from the different goroutines wasn't
protected.
=> fix: surround `cancelCtx` with the mutex

cmd/talosctl/cmd/talos/edit.go
Fixes re-opening editor forever when using `talosctl edit mc`.
Also fixes the temp dir getting filled up with temporary files created
for editing machine config.
Fixes: #6098
=> fix: talosctl edit mc loop

cmd/talosctl/cmd/talos/config.go
As the 'ca', 'crt' and 'key' parameters are now optional for the talos
client, requiring them for the 'talosctl config add' command no longer
makes sense.
=> fix: make 'ca', 'crt' and 'key' flags optional for 'talosctl config add'

website/content/v1.2/_index.md, website/content/v1.2/talos-guides/configuration/nvidia-fabricmanager.md, website/content/v1.2/talos-guides/configuration/nvidia-gpu-proprietary.md, website/layouts/shortcodes/nvidia_container_toolkit_release.html, website/layouts/shortcodes/nvidia_driver_release.html
Add docs on using NVIDIA OSS drivers
Part of #6127
=> docs: NVIDIA oss drivers

hack/release.toml
Release notes for NVIDIA GPU beta support.
=> docs: nvidia gpu beta support

internal/app/apid/main.go, internal/app/machined/main.go, internal/app/trustd/main.go, pkg/machinery/constants/constants.go, pkg/startup/maxprocs.go
=> chore: limit GOMAXPROCS for Talos services

website/content/v1.2/_index.md
Update Talos version in docs to v1.2.0-beta.1
=> docs: update to v1.2.0-beta.1

cmd/talosctl/cmd/talos/get.go, cmd/talosctl/pkg/talos/helpers/resources.go
For maintenance mode (`talosctl get --insecure`), there's no 'nodes'
set, so we run the loop for a single "current" node client is connected
to.
=> fix: get command in the case 'nodes' are not set in the context

internal/app/apid/pkg/backend/apid.go
This fixes a case when a node is rebooted, and connection via another
endpoint apid "caches" a connection error even when the node is up.
E.g. this command:
```
talosctl -e IP1 -n IP2 version
```
If node `IP2` is rebooted, `apid` at `IP1` might enter long backoff loop
and return an error still when `IP2` is actually up.
=> fix: limit apid backoff max delay

go.mod, go.sum, go.work.sum, pkg/machinery/go.mod, pkg/machinery/go.sum
=> backport: fix: update COSI to the version with gRPC Wait fix

go.mod, go.sum, go.work.sum, internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go, internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go, internal/app/machined/pkg/controllers/k8s/static_pod_config_test.go, internal/app/machined/pkg/controllers/kubespan/manager_test.go, internal/app/machined/pkg/controllers/kubespan/peer_spec_test.go, internal/app/machined/pkg/controllers/runtime/kernel_module_config_test.go, internal/app/machined/pkg/controllers/runtime/kernel_param_config_test.go, internal/app/machined/pkg/controllers/secrets/etcd_test.go, internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal_test.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go, internal/integration/api/resources.go, pkg/machinery/go.mod, pkg/machinery/go.sum, pkg/machinery/resources/config/machine_config.go, pkg/machinery/resources/config/machine_config_test.go, pkg/machinery/resources/config/machine_type.go
See https://github.com/cosi-project/runtime/pull/140
Also update for changes in https://github.com/cosi-project/runtime/pull/134
Fixes #6169
=> fix: update COSI to the version with gRPC Wait fix

pkg/machinery/client/client.go, pkg/machinery/client/connection.go
=> backports: v1.2.0

hack/test/e2e-aws.sh
Remove hacks used for CAPI tests
=> chore: remove capi hacks

hack/release.toml, pkg/images/list.go
See https://github.com/flannel-io/flannel/releases/tag/v0.19.2
=> feat: update Flannel to v0.19.2

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.3/reference/configuration.md
See https://github.com/coredns/coredns/blob/master/notes/coredns-1.9.4.md
=> feat: update CoreDNS to 1.9.4

website/content/v1.2/_index.md, website/content/v1.3/_index.md
=> docs: fix double vv in Kubernetes version

internal/app/machined/pkg/system/runner/containerd/containerd.go
The bug was triggered by `containerd` crash (restart), in this case runner receives an error as if the process exited. Runner tries to restart the container, but as the container is still running, attempt to delete the task would fail.
With this change Talos always tries to kill the running container and waits for the container to terminate.
The error message when the bug was triggered looks like:
```
service[kubelet](Waiting): Error running Containerd(kubelet), going to restart forever: failed to clean up task "kubelet": task must be stopped before deletion: running: failed precondition
```
=> fix: kill the task processes when cleaning up stale task

cmd/talosctl/cmd/talos/get.go, internal/app/machined/pkg/controllers/secrets/etcd.go, internal/app/machined/pkg/controllers/secrets/etcd_test.go, internal/app/machined/pkg/system/services/machined.go, internal/app/machined/pkg/system/services/machined_test.go, internal/integration/cli/config.go, pkg/machinery/proto/proto.go, pkg/machinery/resources/k8s/k8s_test.go
PRs:
- #6234 
- #6235 
- #6238
=> backports: for v1.2.2

.drone.jsonnet, internal/pkg/cri/pods.go
Don't skip pods which are not ready, try still to stop containers inside not ready pod sandboxes.
Re-enable the test with Canal CNI (upstream Calico got fixed).
=> fix: stop containers more thoroughly

internal/app/machined/pkg/system/services/extension.go, internal/app/machined/pkg/system/services/extension_test.go, pkg/machinery/extensions/services/services.go, website/content/v1.3/advanced/extension-services.md
This allows setting environment variables for the extension service.
=> feat: environment vars for extension service

internal/app/machined/pkg/controllers/secrets/api_test.go
Fixing the test to match the implementation.
=> test: fix api controller test

go.mod, go.sum, internal/app/machined/pkg/controllers/cluster/discovery_service.go, internal/app/machined/pkg/controllers/cluster/discovery_service_test.go
See https://github.com/siderolabs/discovery-client/pull/4
=> fix: update discovery client with the redirect fix

website/content/v1.2/_index.md, website/content/v1.3/_index.md
With misisng variable it rendered as empty creating confusion for our users.
=> docs: fix missing variable in OpenEBS docs

.drone.jsonnet
=> test: fix up default branch name

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.3/reference/configuration.md
See https://github.com/coredns/coredns/blob/master/notes/coredns-1.10.0.md
=> feat: update CoreDNS to v1.10.0

internal/app/machined/pkg/controllers/k8s/manifest_apply.go
Fixes #6302
This allows Talos to proceed if some manifest is invalid (or malformed), while aborts the loop on connection errors (when `kube-apiserver` is not ready).
This fixes a problem when a single resource might stop all manifests from being applied and preventing a cluster bootstrap.
=> fix: continue applying bootstrap manifests on some errors

Dockerfile, Makefile
See https://go.dev/security/vuln/
=> chore: add vulncheck tool as a linter

website/content/v1.3/talos-guides/configuration/disk-encryption.md
=> docs: add information about applicable use cases of disk encryption.

website/content/v1.3/talos-guides/upgrading-talos.md
=> docs: add constraints to upgrade docs.

go.mod, go.sum
See https://github.com/siderolabs/go-smbios/pull/14
=> fix: update go-smbios to v0.3.1

ADOPTERS.md
Adding Tremor Video to the list of adopters.
Supporting the project.
Signed-off-by: BJ Badyk bbadyk@tremorvideo.com
=> Adding Tremor Video

ADOPTERS.md
Adds Lofty to the ADOPTERS.md
Per Steve Francis in the announcement channel on the Sidero Slack
=> add lofty to talos adopters

hack/release.toml, pkg/images/list.go
See https://github.com/flannel-io/flannel/releases/tag/v0.20.0
=> feat: update Flannel to v0.20.0

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
We have a high timeout for node labeling retry, while the generated temporary Kubernetes PKI has a lifetime of 10 minutes, which means after 10 minutes any call would fail with `Unauthorized`.
Fix that by pulling in the PKI generation into the retry loop, this way cert is always refresh, and it also reacts to machine config changes (e.g. if the endpoint got changed).
Also it helps with the retries if the DNS updates or any other changes like that.
thanks to @steverfrancis for finding this issue
=> fix: regenerate cert on node labeling retry

Makefile, internal/integration/provision/upgrade.go, pkg/machinery/gendata/data/pkgs
This pulls in:
* https://github.com/siderolabs/pkgs/pull/612
* https://github.com/siderolabs/pkgs/pull/606
=> chore: update kernel with BTF support

website/content/v1.3/introduction/system-requirements.md
=> docs: update system requirements to mention dedicated disk usage.

website/content/v1.2/talos-guides/install/bare-metal-platforms/equinix-metal.md, website/content/v1.3/talos-guides/install/bare-metal-platforms/equinix-metal.md
=> docs: edit to reflect Talos is a supported OS on Equinix Metal.

website/content/v1.3/talos-guides/configuration/patching.md
This shows how to patch Pod Security config.
=> docs: admission control patch note

internal/app/machined/pkg/system/services/machined.go
This fixes a cosmetic issue of `machined` being the only service which doesn't have the healthcheck, and showing up as 'health unknown'.
=> chore: introduce a healthcheck for `machined` service

cmd/talosctl/pkg/talos/action/node.go, cmd/talosctl/pkg/talos/action/tracker.go
Fixes the bugs introduced on 804762c597f3aebdc3521cefc93bbbf0ff4a57eb and simplifies error handling.
=> fix: lifecycle action tracking

internal/integration/cli/reboot.go
Fix the reboot test assertion after the changed formatting.
=> test: fix assertion on reboot test

internal/app/machined/pkg/controllers/cluster/local_affiliate.go, internal/app/machined/pkg/controllers/cluster/local_affiliate_test.go
Fixes #5937
This removes external IPs from a set of addresses published by the node (we source addresses from 'routed' now which excludes external). This is definitely "right" thing to do, as those addresses are not on the node itself and can't be routed to the node.
On other hand it also removes them from `talosctl get members`, but we don't have to split this up right now.
For the KubeSpan endpoints, we still use 'all' addresses, as external IPs are perfect as KubeSpan endpoints (Wireguard endpoints).
=> fix: don't publish external IPs as affiliate addresses

website/content/v1.2/introduction/getting-started.md, website/content/v1.2/talos-guides/install/bare-metal-platforms/matchbox.md, website/content/v1.3/introduction/getting-started.md, website/content/v1.3/talos-guides/install/bare-metal-platforms/matchbox.md
I got stuck on how to detect what the disks are, and there was a github discussion about it, so added to startup guide.
=> Fixed typos, added info about how to detect disks, simplified.

internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url.go
This is a fix after upgrade to COSI v0.2.0.
=> fix: correctly handle new watch event types

internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
This provides more detailed event for better error analysis.
=> fix: report errors to Equinix Metal event API

internal/app/machined/pkg/runtime/v1alpha1/platform/metal/url.go
Currently `.Error()` call is panicking if `watchErr` is nil. Besides - we want to wrap errors the way we can unwrap them.
=> fix: fix nil pointer panic and incorrect error output

website/content/v1.3/learn-more/architecture.md
=> docs: Clarify what the deal is with /var

pkg/cluster/sonobuoy/product.go
=> chore: update conformance product.yaml

ADOPTERS.md
Signed-off-by: Samuel Kees <83597284+samuelkees@users.noreply.github.com>
=> add schulz systemtechnik to the list

cmd/talosctl/cmd/talos/get.go
This got broken with a sequence of changes related to not unmarshalling resources when using `get`.
Rewrite the completion to be more straightforward and use easier methods.
Make shell completion work even when `nodes` are not set.
Fixes #6646
=> fix: improve talosctl completion

website/content/v1.3/_index.md
Update nvidia-container-runtime version to v1.11.0
=> docs: update nvidia-container-runtime version

website/content/v1.3/introduction/support-matrix.md
=> docs: fix the 1.3 release date

ADOPTERS.md
Adds Vandebron to the ADOPTERS.md
Because its true.
=> add Vandebron to adopters list

internal/app/machined/pkg/system/service_runner.go, internal/app/machined/pkg/system/service_runner_test.go, internal/app/machined/pkg/system/system.go
Fixes #6707
There was a race condition between different parts of the service code: `Stop` waits for the event which is published before the service is removed from the `running[id]` map, so if one does `Stop` followed by `Start` (this is what `services restart` API does), by the time it goes to `Start` it might be still in the `running[id]` map, so `Start` does nothing.
Overall this code should be rewritten and simplified, but for now move out sending these "terminal" events out so that by the time the event is published, the service is stopped and removed from the `running[id]` map.
=> fix: restarting services (inlcuding extension services)

pkg/provision/providers/vm/disk.go
This improves the performance of the I/O operations if the underlying filesystem supports it.
=> chore: preallocate disk images for QEMU VMs

internal/pkg/cri/pods.go
As the client returns wrapped errors, unwrap them using our own method which does `errors.As` instead of gRPC one which doesn't do unwrapping.
=> fix: unwrap gRPC errors on stop/remove pods check

website/content/v1.3/talos-guides/install/cloud-platforms/digitalocean.md, website/content/v1.4/talos-guides/install/cloud-platforms/digitalocean.md
=> docs: simplify and clarify digital ocean docs.

internal/app/machined/pkg/system/services/udevd.go
The previous `udevd` healthcheck was incomplete and if `udevd` took more time to startup the initial `udevadm trigger` would have silently failed failing to setup proper devices. `udevadm trigger` returns an exit code of zero even if `udevd` is not running. This PR fixes by first checking if the `udevd` control socket exists, which is a faster check, then making sure `udevd` is up by running `udevadm control` command. This ensures that `udevd` is properly initialized before running any `udevadm trigger` commands even if `udevd` is restarted/killed.
=> fix: udevd healthcheck

website/content/v1.2/talos-guides/configuration/nvidia-gpu-proprietary.md, website/content/v1.3/talos-guides/configuration/nvidia-gpu-proprietary.md, website/content/v1.4/_index.md, website/content/v1.4/talos-guides/configuration/nvidia-fabricmanager.md, website/content/v1.4/talos-guides/configuration/nvidia-gpu-proprietary.md, website/content/v1.4/talos-guides/configuration/nvidia-gpu.md
Update NVIDIA component versions.
=> docs: update nvidia component versions

website/content/v1.2/talos-guides/install/virtualized-platforms/vagrant-libvirt.md, website/content/v1.3/talos-guides/install/virtualized-platforms/vagrant-libvirt.md, website/content/v1.4/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
=> docs: fix the endpoints in the libvirt guide

go.mod, go.sum
See https://github.com/siderolabs/go-smbios/pull/15
=> fix: update go-smbios library with Hyper-V data fix

internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/boot_label.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/constants.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/decode.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub_test.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/testdata/grub_parse_test.cfg
This PR ensures that we can handle third grub option - "wipe". We will use it in 1.4.
For #6842
=> chore: handle grub option - "wipe"

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Also, print error if we failed to close the device.
=> fix: remove "defer" leak in ResetUserDisks

internal/pkg/etcd/etcd.go, internal/pkg/etcd/local.go
When removing a member from `etcd`, the server does a pre-check to make sure the member is connected to a quorum of other members, and the remove request might fail. Add a retry to wait for the etcd to be fully connected before giving up, as some parts of the reset flow alrady ran.
Also fix an issue which appears in the integration test, when `reset` is called early in the boot sequence when local etcd hasn't started fully yet.
=> fix: improve etcd leave on reset process

.drone.jsonnet, Makefile, cmd/talosctl/cmd/mgmt/cluster/create.go, hack/test/e2e-qemu.sh, hack/test/e2e.sh, pkg/cluster/check/default.go, website/content/v1.4/reference/cli.md
Add cilium e2e tests. The existing cilium check was very old, update to latest cilium version and also add a test for KPR strict mode.
=> feat: add cilium e2e tests

.drone.jsonnet
This PR moves blob storage to azure.
=> ci: move blob storage to azure for builds

website/content/v1.4/talos-guides/howto/_index.md, website/content/v1.4/talos-guides/howto/scaling-up.md, website/content/v1.4/talos-guides/howto/workers-on-controlplane.md
=> docs: add how tos for workloads on control planes, and scaling up

website/content/v1.4/kubernetes-guides/network/deploying-cilium.md
Update cilium install instructions.
=> docs: update cilium install instructions

Makefile, go.mod, go.sum, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
This brings in new kernel & containerd, and the kernel has support for framebuffer console enabled.
=> feat: update pkgs with framebuffer console

cmd/installer/pkg/install/target.go, cmd/installer/pkg/install/target_test.go, hack/release.toml, internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go, internal/app/machined/pkg/runtime/controller.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/encode.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/testdata/grub_write_test.cfg, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, website/content/v1.4/reference/kernel.md
=> feat: add grub option to drop to maintenance mode

website/content/v0.13/cloud-platforms/nocloud.md, website/content/v0.14/cloud-platforms/nocloud.md, website/content/v1.0/talos-guides/install/cloud-platforms/nocloud.md, website/content/v1.1/talos-guides/install/cloud-platforms/nocloud.md, website/content/v1.2/talos-guides/install/cloud-platforms/nocloud.md, website/content/v1.3/talos-guides/install/cloud-platforms/nocloud.md, website/content/v1.4/talos-guides/install/cloud-platforms/nocloud.md
Update the link to the nocloud docs in the uh nocloud docs
=> docs(nocloud): update link

website/content/v0.14/cloud-platforms/gcp.md, website/content/v1.0/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.0/talos-guides/install/cloud-platforms/hetzner.md, website/content/v1.1/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.1/talos-guides/install/cloud-platforms/hetzner.md, website/content/v1.2/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.2/talos-guides/install/cloud-platforms/hetzner.md, website/content/v1.3/_index.md, website/content/v1.3/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.3/talos-guides/install/cloud-platforms/hetzner.md, website/content/v1.4/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.4/talos-guides/install/cloud-platforms/hetzner.md
=> docs: fix Talos version to use template

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.21.3
=> feat: update Flannel to v0.21.3

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.21.4
=> feat: update Flannel to 0.21.4

internal/app/maintenance/main.go
The problem was that `GracefulStop()` will hang forever if there is a running API call. So if there is a running streaming call, the maintenance service might hang until it is finished.
The problem shows up with 'Upgrade' API in the maintenance mode if there is a concurrent streaming API call, e.g.:
1. Watch API is running against maintenance mode.
2. Upgrade API is issued, it tries to run the MaintenanceUpgrade sequence, which tries to take over the Initialize sequence. The Initialize sequence is canceled, maintenance API service context is canceled, but the service doesn't terminate, as it's stuck in `GracefulStop`. The sequence take over times out, as even the sequence is canceled, it hasn't terminated yet.
Sample log:
```
[talos] upgrade request received: …
```
=> fix: always shutdown maintenance API service

internal/app/machined/pkg/controllers/network/route_config.go, internal/app/machined/pkg/controllers/network/route_config_test.go
=> fix: add a link-scope route if the cmdline gateway is not reachable

internal/app/machined/pkg/controllers/network/operator/dhcp4.go
Fixes #7041
Rework the DHCP flow so that we don't use `INFORM` requests anymore. The idea is to try requesting a hostname from the DHCP server first, and if the hostname is not sent, or it gets overridden in Talos, restart the DHCP sequence sending the hostname to the DHCP server.
This still avoids sending and requesting a hostname in one request.
=> fix: rework DHCP flow

internal/app/machined/pkg/controllers/network/operator/dhcp4.go
Fixes #7041
Rework the DHCP flow so that we don't use `INFORM` requests anymore. The idea is to try requesting a hostname from the DHCP server first, and if the hostname is not send, or it gets overridden in Talos, restart the DHCP sequence sending the hostname to the DHCP server.
This still avoids sending and requesting a hostname in one request.
(cherry picked from commit eb01edbc8a0ef5810693afe450861d5b63877b72)
=> backport: fix: rework DHCP flow

.drone.jsonnet, Dockerfile, Makefile, go.work, hack/docgen/go.mod, hack/docgen/go.sum, hack/module-sig-verify/go.mod, hack/module-sig-verify/go.sum, hack/module-sig-verify/main.go, hack/test/e2e.sh, hack/test/extensions/extension-patch-filter.jq, pkg/machinery/gendata/data/pkgs
Add kernel module signature verification for out of tree kernel modules.
=> chore: add kernel module signtaure verification

hack/module-sig-verify/main.go
Make module-sig-verify code more idiomatic.
=> chore: module-sig-verify cleanup

Makefile, hack/release.toml, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
=> feat: update Linux to 6.1.24

website/config.toml, website/content/v1.3/_index.md, website/content/v1.4/_index.md
Make 1.4.0 default documentation.
=> docs: activate 1.4.0 docs by default

website/config.toml
Otherwise docs think it's an archived version.
=> docs: fix the latest url

internal/pkg/dashboard/configurl.go
Show the config URL template that will be populated when the code is entered. Closes siderolabs/talos#7092.
Clear the form when the tab is exited & do not display "Saved successfully" message when the code is saved, as we navigate to the summary tab afterward anyway. Closes siderolabs/talos#7093.
=> feat: show template URL in dashboard config URL tab

website/content/v1.3/talos-guides/install/cloud-platforms/nocloud.md, website/content/v1.4/talos-guides/install/cloud-platforms/nocloud.md
Mention the requirement of the nocloud image.
It might be non obvious to newer users (that would be me), it might also save some hairs.
=> docs: update documentation for Talos 1.3

internal/pkg/dashboard/components/talosinfo.go
Rename members to machines to be clearer.
Display the correct member count.
Closes siderolabs/talos#7127.
=> fix: display correct number of machines on dashboard

website/content/v1.4/advanced/building-images.md, website/content/v1.4/advanced/troubleshooting-control-plane.md, website/content/v1.4/advanced/verifying-images.md, website/content/v1.4/learn-more/process-capabilities.md
Also fix troubleshotting docs (outdated stuff).
Fixes #7125
Fixes #7087
=> docs: document building, verifying image and process caps

website/content/v1.4/talos-guides/howto/scaling-down.md, website/content/v1.5/talos-guides/howto/scaling-down.md
Added how to scale down How To.
=> docs: Added how to on scaling down.

internal/app/machined/pkg/controllers/k8s/control_plane.go, internal/app/machined/pkg/controllers/k8s/control_plane_test.go
This bug is pretty cosmetic, but it shows up as a wrong check when performing worker upgrade - Talos pretends it checks e.g. kube-apiserver version which doesn't make sense for workers.
There were two bugs in the code:
* check for machine type was done against `TypeWorker`, while `MachineType` resource is initially created as `TypeUnknown`
* the cleanup code was not implemented
As I touched the code, I updated controller and tests to use modern conventions.
=> fix: properly skip/cleanup controlplane configs for workers

internal/app/wrapperd/main.go
=> backports: for v1.4.3

hack/test/e2e-qemu.sh, hack/test/e2e.sh
The test was added at the wrong place.
=> fix: rlimit nofile test

internal/app/machined/pkg/controllers/k8s/kubelet_service.go
Kubelet doesn't refresh self-issued serving certificates, so force it by removing the cert on each restart.
Fix the code which was forcing rejoin when the nodename changes, it was broken, as it was checking serving certificate instead of client certificate. It worked by accident when not using controlplane-issued serving certificates.
Fixes #7235
=> fix: refresh kubelet self-issued serving certificates

internal/app/machined/pkg/controllers/network/operator/dhcp4.go
RENEW packets are sent unicast, so Talos needs the address of the DHCP server to send RENEW packets to.
Fixes https://github.com/siderolabs/talos/issues/7211
Fixes https://github.com/siderolabs/talos/issues/7263
=> fix: skip DHCP RENEW if server IP in the lease is all zeroes

.drone.jsonnet, Dockerfile, Makefile, cmd/installer/cmd/iso.go, cmd/installer/pkg/iso.go, hack/ukify/main.go, pkg/makefs/makefs.go, pkg/makefs/vfat.go
This adds code to generate a SecureBoot enabled ISO.
Fixes: #7261
=> feat: add secureboot iso generation

website/content/v1.5/learn-more/faqs.md
Some documentation about certificates handling in Talos stack
Less questions in Slack community, better visibility on how talos is working under the hood
=> docs(faq): add some words about certifcates

cmd/installer/pkg/install/manifest.go, cmd/installer/pkg/install/target.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, internal/pkg/partition/constants.go, internal/pkg/partition/format.go, internal/pkg/partition/partition.go
Cleanup partition code to be explicit about `Format` and `Partition` options.
=> chore: cleanup partition code

.drone.jsonnet
The step was added to integration pipeline, but I forgot to add it to cron pipeline.
=> chore: fix cron pipeline

internal/app/machined/pkg/controllers/ctest/ctest.go, internal/app/machined/pkg/controllers/runtime/drop_upgrade_fallback.go, internal/app/machined/pkg/controllers/runtime/drop_upgrade_fallback_test.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
=> refactor: task 'updateBootLoader' as controller

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
Because `SetConfig` can be called concurrently with `Config` there is risk of data race, if something goes wrong. Since `config.Provider` is an interface type, it means its size is two machine words. And so in very unpleasant situations it can lead to arbitrary RCE, because interface variable can be in partially updated state.
=> chore: wrap config.Provider in atomic wrapper

go.mod, go.sum, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_state.go, pkg/machinery/go.mod, pkg/machinery/go.sum, pkg/machinery/resources/cluster/cluster_test.go, pkg/machinery/resources/config/config_test.go, pkg/machinery/resources/cri/cri_test.go, pkg/machinery/resources/etcd/etcd_test.go, pkg/machinery/resources/files/files_test.go, pkg/machinery/resources/hardware/hardware_test.go, pkg/machinery/resources/k8s/k8s_test.go, pkg/machinery/resources/kubeaccess/kubeaccess_test.go, pkg/machinery/resources/kubespan/kubespan_test.go, pkg/machinery/resources/network/network_test.go, pkg/machinery/resources/perf/perf_test.go, pkg/machinery/resources/runtime/runtime_test.go, pkg/machinery/resources/secrets/secrets_test.go, pkg/machinery/resources/time/time_test.go, pkg/machinery/resources/v1alpha1/v1alpha1_test.go
Replace `resource.Resource` with `meta.ResourceWithRD` where possible.
=> chore: bump github.com/cosi-project/runtime

.drone.jsonnet, Makefile, hack/cloud-image-uploader.sh, hack/cloud-image-uploader/azure-disk-template.json, hack/cloud-image-uploader/azure.go, hack/cloud-image-uploader/go.mod, hack/cloud-image-uploader/go.sum, hack/cloud-image-uploader/main.go, hack/cloud-image-uploader/options.go, website/content/v1.5/talos-guides/install/cloud-platforms/azure.md
Also uncomment Azure uploader.
=> chore: add a pipeline to test cloud-images step without a release

cmd/installer/pkg/install/install.go, cmd/installer/pkg/install/manifest.go, internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader/bootloader.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/boot_label.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/constants.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/decode.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/encode.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub_test.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/probe.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/revert.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, internal/app/machined/revert.go
This changes the bootloader code to be generic enough to support multiple bootloader implementations.
=> chore: generic boootloader implementation

website/content/v1.2/talos-guides/install/virtualized-platforms/vagrant-libvirt.md, website/content/v1.3/talos-guides/install/virtualized-platforms/vagrant-libvirt.md, website/content/v1.4/talos-guides/install/virtualized-platforms/vagrant-libvirt.md, website/content/v1.5/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
=> docs: fix yamlpath of controlplane.yaml in vagrant document

.drone.jsonnet, hack/test/e2e-qemu.sh, hack/test/e2e.sh, pkg/provision/providers/qemu/preflight.go
This formats and cleanups the test scripts.
=> chore: format and cleanup test scripts

pkg/provision/providers/qemu/arch.go
The static paths for the OVMF firmware are limited, and won't match, for example, any of the files installed by `edk2-ovmf` on a Fedora 38 system. This change separates the search paths and filenames, making sure all combinations are covered when looking for a suitable firmware. Similarly also cleans up the OVMF vars lookup.
=> fix: refine OVMF search paths

hack/ukify/gen-certs/main.go
Fix ukify cert generation by setting the proper Subj/CN.
Fixes: #7383
=> fix: ukify cert generation

website/content/v1.5/introduction/getting-started.md, website/content/v1.5/introduction/prodnotes.md
=> docs: split simple and more complex getting started guides

Dockerfile
Use shell here-doc to unify multiple commands into a single layer to have less layers created.
Use `--link` to pull in pkgs.
=> chore: optimize dockerfile instructions

internal/pkg/mount/pseudo.go
=> fix: mount hugepages with nosuid + nodev

go.mod, go.sum, internal/app/init/main.go, internal/pkg/rng/pool.go, internal/pkg/rng/rng.go, internal/pkg/rng/tpm.go
Use the TPM2 feature to provide high-quality random bytes.
=> feat: seed the kernel random pool from the TPM

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go, internal/pkg/encryption/encryption.go, internal/pkg/encryption/helpers/helpers.go, internal/pkg/encryption/keys/keys.go, internal/pkg/encryption/keys/kms.go, internal/pkg/encryption/keys/nodeid.go, internal/pkg/encryption/keys/options.go, internal/pkg/mount/options.go, internal/pkg/mount/system.go
Pass getter to the key handler instead of already fetched node uuid.
=> fix: rewrite encryption system information flow

internal/integration/provision/upgrade.go, internal/pkg/cri/pods.go
It seems that CRI has a bit of eventual consistency, and it might fail to remove a stopped pod failing that it's still running.
Rewrite the upgrade API call in the upgrade test to actually wait for the upgrade to be successful, and fail immediately if it's not successfull. This should improve the test stability and it should make it easier to find issues immediately.
=> fix: retry CRI pod removal, fix upgrade flow in the tests

cmd/talosctl/cmd/mgmt/cluster/create.go, pkg/machinery/config/generate/init.go, pkg/machinery/config/generate/options.go, pkg/machinery/config/generate/worker.go
=> chore: change missing renames of KubePrism

pkg/machinery/config/generate/options.go, website/content/v1.5/kubernetes-guides/network/deploying-cilium.md
=> docs: update cilium documentation about KubePrism usage

internal/app/machined/pkg/runtime/logging/circular.go
We can safely do it on `io.Writer` level, since `log.Logger.Output` (called by `Print|Printf`) pretty much promises that every call to `Write` ends with `\n`.
Closes #7439
=> chore: explicitly add timestamps to machined logs

internal/app/apid/main.go, internal/app/machined/pkg/system/services/machined.go, pkg/machinery/client/connection.go, pkg/machinery/constants/constants.go
=> fix: enable compression and bump gRPC max msg size

hack/test/e2e.sh, hack/test/extensions/extension-patch-filter.jq, pkg/provision/providers/qemu/launch.go
Support creating a qemu guest agent socket so we can test `qemu-guest-agent` extension in CI.
Ref: https://github.com/siderolabs/extensions/pull/173#issuecomment-1611911106
=> chore: support creating qemu guest socket

website/content/v1.3/reference/kernel.md, website/content/v1.4/reference/kernel.md, website/content/v1.5/reference/kernel.md
Small typo in reference/kernel/
=> docs: Typo DCHP -> DHCP

website/content/v1.4/talos-guides/install/virtualized-platforms/proxmox.md, website/content/v1.5/talos-guides/install/virtualized-platforms/proxmox.md
Added notes to the proxmox install guide to inform readers of a few gotchas to be aware of
=> Docs: Improve Proxmox installation guide

.drone.jsonnet, Makefile, hack/modules-amd64.txt, hack/modules-arm64.txt, pkg/machinery/gendata/data/pkgs
Disable cloud-images step due to the issue with AWS & Azure atm.
Pull in https://github.com/siderolabs/pkgs/pull/761
=> chore: disable cloud-images, pull in new kernel and gre module

Makefile, hack/modules-amd64.txt, hack/modules-arm64.txt, pkg/machinery/gendata/data/pkgs
This PR adds the alx drivers from pkgs to talos
=> chore: add alx drivers

website/content/v1.5/introduction/prodnotes.md
Prevents questions like https://github.com/siderolabs/talos/discussions/7456
=> docs: note that Talos API requires TCP only load balancer, not HTTP/S

internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/expected-v2.yaml, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v3.yaml
* support for bonding
* added interface selection by MAC address
* added routes management
=> feat: network configuration improvements on the NoCloud platform

.drone.jsonnet, Makefile
=> chore: drone jsonnet cleanup

.drone.jsonnet, hack/cloud-image-uploader.sh, hack/cloud-image-uploader/aws.go, hack/cloud-image-uploader/main.go, hack/cloud-image-uploader/options.go, hack/test/e2e-aws-prepare.sh, hack/test/e2e-aws.sh, hack/test/tfvars/aws.jq
=> feat: e2e-aws using tf code

Makefile, hack/release.toml, hack/test/e2e.sh, pkg/machinery/constants/constants.go, website/content/v1.5/reference/cli.md, website/content/v1.5/reference/configuration.md
See https://github.com/kubernetes/kubernetes/releases/tag/v1.28.0
=> feat: update Kubernetes to 1.28.0

website/content/v1.4/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md, website/content/v1.5/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
OpenEBS Jiva Installation Talos Issues
When Installing Jiva on my 2 node cluster i had some issues with openebs jiva, because i had to set the corresponding labels to the namespace and also setting the replicas. I just wanted to clarify this in the docs so the installation process is more seamless.
I did nothing of these things because i just updated the docs. I'm also not sure if I should update this for all versions of the documentation so help is appeciated. 
=> docs: Jiva Pod Security Policy

website/content/v1.4/talos-guides/configuration/nvidia-gpu-proprietary.md, website/content/v1.5/talos-guides/configuration/nvidia-gpu-proprietary.md
* Tried to improve the docs for v1.4 by explaining the different workflows for >= v1.4.8 and previous versions.
* Added a section about building the nvidia extensions directly to the docs for v1.5 instead of linking back to the docs for v1.4
* 
=> Improve the docs for enabling NVIDIA support in v1.4.8 and later

website/content/v1.5/kubernetes-guides/configuration/kubeprism.md
Fix a small typo ion the KubePrism howto.
=> docs: fix kubeprism typo

go.mod, go.sum
Fixes #7637
See https://github.com/beevik/ntp/commit/196f2d4b717e342900805eb07023df134bc1a010
=> fix: ntp query error with bare IPv6 address

internal/app/machined/pkg/system/services/etcd.go, internal/app/machined/pkg/system/services/kubelet.go
First of all, it seems to be "right way", as it makes sure the image is looked up by the digest.
Second, it fixes the case when image is specified with both tag and digest (which is not supposed to be the correct ref, but it is used frequently).
Talos since 1.5.0 stores images with the following aliases:
```
gcr.io/etcd-development/etcd:v3.5.9
gcr.io/etcd-development/etcd@sha256:8c956d9b0d39745fa574bb4dbacd362ffdc1109479432f54094859d4cf984b17
ghcr.io/siderolabs/kubelet:v1.28.0
ghcr.io/siderolabs/kubelet@sha256:50710f2cd3328c23f57dfc7fb00940d8cfd402315e33fc7cb8184fc660650a5c
sha256:50710f2cd3328c23f57dfc7fb00940d8cfd402315e33fc7cb8184fc660650a5c
sha256:8c956d9b0d39745fa574bb4dbacd362ffdc1109479432f54094859d4cf984b17
```
This change pulls the digest format (the last in this list) and uses …
=> fix: use image digest when starting a container

.drone.jsonnet, hack/test/e2e-aws-prepare.sh, hack/test/e2e.sh, hack/test/tfvars/aws.jq, hack/test/tfvars/nvidia.yaml, internal/integration/api/api.go, internal/integration/api/common.go, internal/integration/api/extensions_nvidia.go, internal/integration/api/extensions_qemu.go, internal/integration/api/trustedboot.go, internal/integration/api/update-hostname.go, internal/integration/base/api.go, internal/integration/base/base.go, internal/integration/base/k8s.go, internal/integration/integration_test.go, internal/pkg/extensions/kernel_modules.go, pkg/imager/extensions/extensions.go
=> feat: add e2e-aws for nvidia extensions

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.6/reference/configuration.md
See https://github.com/coredns/coredns/releases/tag/v1.11.1
=> feat: update CoreDNS to 1.11.1

internal/integration/api/extensions_qemu.go
Validate the amdgpu and intel-ice firmware extensions.
=> chore: validate new system extensions

website/config.toml
Replace Sidero Metal with Sidero Omni.
=> docs: update header links

Makefile, hack/release.toml, internal/integration/api/extensions_nvidia.go, internal/integration/api/extensions_qemu.go, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
Add tests for utils-linux extensions.
Ref: https://github.com/siderolabs/extensions/pull/216
=> chore: add tests for util-linux extensions

Dockerfile, Makefile
=> chore: add PKG_KERNEL arg to customize used kernel

Makefile
Better cosign flow, check for existing signature.
=> chore: improve image signing process

go.mod, go.sum, internal/app/apid/pkg/backend/apid.go, internal/app/machined/pkg/controllers/runtime/events_sink.go, internal/app/machined/pkg/controllers/siderolink/manager.go, internal/app/machined/pkg/system/services/apid.go, internal/app/machined/pkg/system/services/trustd.go, internal/app/trustd/main.go, internal/pkg/cri/client.go, internal/pkg/encryption/keys/kms.go, internal/pkg/etcd/etcd.go, pkg/grpc/factory/factory.go, pkg/grpc/middleware/auth/basic/basic.go, pkg/grpc/proxy/backend/local.go, pkg/machinery/client/connection.go, pkg/machinery/go.mod, pkg/machinery/go.sum
Fixes #7576
See https://github.com/grpc/grpc-go/pull/6309
=> chore: update gRPC library and enable shared write buffers

internal/app/machined/pkg/controllers/runtime/maintenance_service.go, internal/app/machined/pkg/controllers/runtime/maintenance_service_test.go
Fixes #7738
If the SideroLink address changes, maintenance service should listen on new address. Previously it worked "sometimes", as there was a race on maintenance config either be removed/recreated or just updated. In case of an update the listen address was not updated properly, but recreate case worked correctly.
=> fix: handle correctly change of listen address for maintenance service

pkg/imager/iso/uefi.go
Fixes #7712
Instead of hardcoding a size, calculate the UKI and sd-boot size. UKI has dynamic size, as it depends on number of system extensions installed.
=> fix: calculate UKI ISO size dynamically

internal/pkg/extensions/compress.go, internal/pkg/extensions/kernel_modules.go, pkg/imager/extensions/contents.go, pkg/imager/extensions/extensions.go, pkg/imager/extensions/rebuild.go
Closes #7729
This follows the steps described in
https://www.kernel.org/doc/html/v6.1/x86/microcode.html#early-load-microcode
=> fix: build CPU ucode correctly for early loader

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.22.3
=> feat: update Flannel to 0.22.3

hack/cloud-image-uploader/README.md
=> fix: Contributor typo

Makefile, hack/release.toml, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
=> chore: bump kernel to 6.1.54

website/content/v1.5/kubernetes-guides/configuration/kubeprism.md, website/content/v1.6/kubernetes-guides/configuration/kubeprism.md
=> docs: add KubePrism video

cmd/talosctl/cmd/mgmt/cluster/create.go, hack/release.toml, hack/test/e2e-qemu.sh, pkg/machinery/config/contract.go, pkg/machinery/config/contract_test.go, pkg/machinery/config/generate/init.go, pkg/machinery/config/generate/options.go, pkg/machinery/config/generate/worker.go, pkg/machinery/constants/constants.go, website/content/v1.6/kubernetes-guides/configuration/kubeprism.md, website/content/v1.6/reference/cli.md
=> feat: enable KubePrism by default

website/content/v1.4/advanced/metal-network-configuration.md, website/content/v1.5/advanced/metal-network-configuration.md, website/content/v1.6/advanced/metal-network-configuration.md
Describe the format and operations to get it working.
=> docs: add metal network configuration guide

pkg/imager/profile/input.go
This allows to force pull over insecure from non-local endpoints.
=> chore: allow insecure access to installer base image (imager)

website/content/v1.5/introduction/getting-started.md, website/content/v1.6/introduction/getting-started.md
Fixed some typos i encountered when setting up
=> Docs: Fix typos in example talosctl commands

internal/integration/api/extensions_qemu.go
Add tests for iscsi to make sure it works.
=> chore: add tests for iscsi

website/content/v1.5/_index.md, website/content/v1.5/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md, website/content/v1.5/talos-guides/install/single-board-computers/bananapi_m64.md, website/content/v1.5/talos-guides/install/single-board-computers/jetson_nano.md, website/content/v1.5/talos-guides/install/single-board-computers/libretech_all_h3_cc_h5.md, website/content/v1.5/talos-guides/install/single-board-computers/nanopi_r4s.md, website/content/v1.5/talos-guides/install/single-board-computers/pine64.md, website/content/v1.5/talos-guides/install/single-board-computers/rock64.md, website/content/v1.5/talos-guides/install/single-board-computers/rockpi_4.md, website/content/v1.5/talos-guides/install/single-board-computers/rockpi_4c.md, website/content/v1.5/talos-guides/install/single-board-computers/rpi_generic.md, website/content/v1.6/_index.md, website/content/v1.6/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md, website/content/v1.6/talos-guides/install/single-board-computers/bananapi_m64.md, website/content/v1.6/talos-guides/install/single-board-computers/jetson_nano.md, website/content/v1.6/talos-guides/install/single-board-computers/libretech_all_h3_cc_h5.md, website/content/v1.6/talos-guides/install/single-board-computers/nanopi_r4s.md, website/content/v1.6/talos-guides/install/single-board-computers/pine64.md, website/content/v1.6/talos-guides/install/single-board-computers/rock64.md, website/content/v1.6/talos-guides/install/single-board-computers/rockpi_4.md, website/content/v1.6/talos-guides/install/single-board-computers/rockpi_4c.md, website/content/v1.6/talos-guides/install/single-board-computers/rpi_generic.md
When user follow instructions in document v1.5 and v1.6, curl will make a request with invalid image URL.
Fixes #7809
=> docs: fix incorrect image suffix

cmd/installer/cmd/imager/root.go, pkg/imager/profile/default.go
Can possible to change boot image size.
Change the default image size for some cloud platform.
close #7851
=> feat: customize image size

pkg/imager/profile/input.go
This supports full Image interface.
=> chore: support OCI layout as a source for profile input

pkg/machinery/config/generate/generate.go
The function initialized with `Input` with some fields populated and then at the end of the code the fields are updated again with the same value, not sure why it's needed.
Just want to make the code looks better.
=> chore: remove uneeded code

cmd/installer/pkg/install/install.go, internal/pkg/meta/meta.go
Use fixed partition name instead of trying to auto-discover by label.
Auto-discovery by label might hit completely wrong blockdevice.
=> fix: when writing to META in the installer/imager, use fixed name

cmd/talosctl/cmd/mgmt/gen/secureboot.go
Output the PCR public key in `.der` format in addition to the `.pem` format.
Closes siderolabs/talos#7742.
=> feat: add `.der` output `talosctl gen secureboot pcr`

internal/pkg/secureboot/measure/measure.go, internal/pkg/secureboot/measure/measure_test.go
Drop `sha1` algorithm from expected PCR json calculation.
=> chore: drop sha1 from genereated pcr json

website/content/v1.5/learn-more/faqs.md, website/content/v1.6/learn-more/faqs.md
=> docs: add timezone information

internal/app/machined/pkg/controllers/etcd/spec.go, internal/app/machined/pkg/controllers/etcd/spec_test.go
Fixes #7947
This way etcd advertised address can be picked from the `external IPs` of the machine.
=> fix: pick etcd adverised addresses from 'current' addresses

website/content/v1.6/talos-guides/install/cloud-platforms/hetzner.md
=> docs(hetzner-cloud): extend docs for arm64

pkg/machinery/compatibility/kubernetes_version.go, pkg/machinery/compatibility/kubernetes_version_test.go, pkg/machinery/compatibility/talos17/talos17.go, pkg/machinery/compatibility/talos_version.go, pkg/machinery/compatibility/talos_version_test.go
Ensure that Talos 1.6 machinery can handle compatibility for Talos 1.7.
=> feat: provide compatibility for future Talos 1.7

.drone.jsonnet, hack/test/e2e.sh
Enable kubespan and default block firewall with cilium tests.
=> chore: enable kubespan+firewall for cilium tests

website/content/v1.6/introduction/what-is-new/index.md, website/content/v1.6/talos-guides/install/boot-assets.md
I merged docs PR before receiving those updates.
=> docs: update 1.6 docs with Noel's feedback

website/content/v1.5/talos-guides/install/bare-metal-platforms/secureboot.md, website/content/v1.6/talos-guides/install/bare-metal-platforms/secureboot.md
Restructure the docs a bit to start with the easiest option (via Image Factory).
=> docs: announce that SecureBoot is available

pkg/machinery/config/types/v1alpha1/v1alpha1_stability_test.go, website/content/v1.6/_index.md
=> docs: update latest version to v1.6.1

pkg/imager/filemap/filemap.go
This filemap is used to generate installer image layer with artifcats.
Previous dumb implementation buffered in memory which leads to extensive memory usage.
See https://github.com/siderolabs/image-factory/issues/77
=> fix: replace the filemap implementation to not buffer in memory

Makefile, hack/modules-amd64.txt, hack/modules-arm64.txt, pkg/machinery/gendata/data/pkgs
See https://github.com/siderolabs/pkgs/pull/862
=> chore: pull in NBD modules

internal/pkg/discovery/registry/kubernetes.go, internal/pkg/discovery/registry/kubernetes_test.go, pkg/machinery/constants/constants.go
=> fix: support KubePrism settings in Kubernetes Discovery

internal/app/machined/pkg/system/services/etcd.go
This is currently no-op, just noticed that while looking into another bug. This should make the intention more clean.
=> refactor: use etcd configuration from the EtcdSpec resource

website/content/v1.6/kubernetes-guides/configuration/local-storage.md, website/content/v1.7/kubernetes-guides/configuration/local-storage.md
Use kustomize (as the official supported way for Local Path Provisioner).
=> docs: document local path provisioner install

Makefile, hack/modules-amd64.txt, hack/modules-arm64.txt, hack/release.toml, internal/app/machined/pkg/controllers/runtime/kernel_module_spec.go, internal/integration/api/extensions_qemu.go, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
See https://github.com/siderolabs/pkgs/pull/873
=> feat: update Linux to 6.6.13

website/content/v1.2/talos-guides/install/virtualized-platforms/vmware/vmware.sh, website/content/v1.3/talos-guides/install/virtualized-platforms/vmware/vmware.sh, website/content/v1.4/talos-guides/install/virtualized-platforms/vmware/vmware.sh, website/content/v1.5/talos-guides/install/virtualized-platforms/vmware/vmware.sh, website/content/v1.6/talos-guides/install/virtualized-platforms/vmware/vmware.sh
This PR sets proper defaults based on the series of talos. Defaults to last release in each series.
=> docs: provide sane defaults for each release series in vmware script

internal/pkg/tui/installer/installer.go
In the previous implementation, even though `installer.err` was set, it was never checked :facepalm:.
The run loop was stolen from the dashboard code.
Fixes #8205
=> fix: run the interactive installer loop to report errors

cmd/installer/pkg/install/install.go
We had these retries in other places, but not here.
This seems to happen more frequently with Linux 6.6 update, the tl;dr is same: `udevd` tries to rescan the partition table at the wrong moment, preventing Talos installer to open the partition which was just created.
It's a race, so workaround it by retrying the call.
=> fix: retry blockdevice open in the installer

pkg/provision/providers/qemu/launch.go
This PR fixes a channel blocking bug in your code.
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.
The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.
=> chore: fix channel blocking on qemu launch

.drone.jsonnet
We don't need hacked one anymore.
=> chore: bump docker dind image

internal/integration/api/extensions_qemu.go
Created test for Wasm extension
=> Adding Wasm extension test 

internal/app/machined/pkg/controllers/runtime/extension_service.go, internal/app/machined/pkg/system/services/extension.go, internal/app/machined/pkg/system/services/extension_test.go
=> fix: use a separate cgroup for each extension service

website/content/v1.5/talos-guides/network/vip.md, website/content/v1.6/talos-guides/network/vip.md, website/content/v1.7/talos-guides/network/vip.md
Corrected the YAML intendation
incorrect YAML intendation in the Documentation
(First PR did I miss anything important?)
=> Corrected YAML intendation in the Documentation

ADOPTERS.md
Hi, we utilize Talos Linux as base disto for our free PaaS platform [Cozystack](https://cozystack.io) for running managed services, virtual machines and Kubernetes clusters.
We'd like to share this information :)
=> Add Ænix to the Adopters list

go.mod, go.sum, internal/app/machined/pkg/controllers/network/dns_resolve_cache.go, internal/pkg/dns/dns.go, internal/pkg/dns/dns_test.go
Enable some TCP optimizations, set minimal TTL, set socket reuse.
=> chore: adjust dns sockets settings

internal/app/machined/pkg/controllers/network/dns_resolve_cache.go, internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go, internal/pkg/dns/dns.go, internal/pkg/dns/dns_test.go
Replace `SO_REUSEPORT` with `SO_REUSEPORT`.
=> chore: enable v6 support on the same port

internal/pkg/mount/mount.go
Run `xfs_repair` for invalid argument error.
Part of: #8292
=> fix: run xfs_repair on invalid argument error

.drone.jsonnet, hack/test/extensions/extension-patch-filter.jq
Update extensions test to use strategic patches and use `ExtensionServiceConfig` document.
Depends on: https://github.com/siderolabs/extensions/pull/320
=> chore: update extensions test

website/content/v1.3/talos-guides/install/single-board-computers/rpi_generic.md, website/content/v1.4/talos-guides/install/single-board-computers/rpi_generic.md, website/content/v1.5/talos-guides/install/single-board-computers/rpi_generic.md, website/content/v1.6/talos-guides/install/single-board-computers/rpi_generic.md, website/content/v1.7/talos-guides/install/single-board-computers/rpi_generic.md
Replaces default architecture in install instructions
fixes #8129
=> docs: rpi talosctl install

internal/integration/api/extensions_qemu.go
Let's add a very basic test for the Kata Containers extension, mimicing what's already in place for gVisor.
This depends on the work being done in:
https://github.com/siderolabs/extensions/pull/279
If we're going to add the Kata Containers extension, we better make sure it works. :-)
- But GPG Identity is failing
NOTE: This has not been tested yet with the PR from the extensions side.
=> chore: Add tests for the Kata Containers extension

ADOPTERS.md
Oceanbox entry in adopters list
=> Add  oceanbox.io to adopters

pkg/imager/iso/uefi.go, pkg/imager/out.go
Add the uki signing cert into iso.
Fixes: #8131
=> chore: uki der certs in iso

ADOPTERS.md
docs: add Redpill Linpro to adopters list
=> docs: add Redpill Linpro to adopters list

ADOPTERS.md
Adding DreeBot to ADOPTERS
We're using Talos for our infrastructure 
=> docs: add DreeBot to ADOPTERS.md

hack/release.toml, pkg/machinery/config/schemas/config.schema.json, pkg/machinery/config/types/v1alpha1/v1alpha1_types.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go, pkg/machinery/constants/constants.go, website/content/v1.7/reference/configuration/v1alpha1/config.md, website/content/v1.7/schemas/config.schema.json
Fixes #8396
Pros:
* IPv6
* good CDN, small RTT
Cons:
* not community-run
=> feat: set default NTP server to time.cloudflare.com

Dockerfile, cmd/installer/pkg/install/manifest.go, pkg/machinery/overlay/overlay.go
Handling of Overlay PartitionOpts was missed in the previous code.
=> fix: handling of overlay partition options

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.24.4
=> feat: update Flannel to v0.24.4

website/content/v0.10/guides/managing-pki.md, website/content/v0.11/guides/managing-pki.md, website/content/v0.12/guides/managing-pki.md, website/content/v0.13/guides/managing-pki.md, website/content/v0.14/guides/managing-pki.md, website/content/v0.6/guides/managing-pki.md, website/content/v0.7/guides/managing-pki.md, website/content/v0.8/guides/managing-pki.md, website/content/v0.9/guides/managing-pki.md, website/content/v1.0/talos-guides/configuration/managing-pki.md, website/content/v1.1/talos-guides/configuration/managing-pki.md, website/content/v1.2/talos-guides/configuration/managing-pki.md, website/content/v1.3/talos-guides/configuration/managing-pki.md, website/content/v1.4/talos-guides/configuration/managing-pki.md, website/content/v1.5/talos-guides/configuration/managing-pki.md, website/content/v1.6/talos-guides/configuration/managing-pki.md, website/content/v1.7/talos-guides/howto/cert-management.md
=> chore: remove repetitive words

.drone.jsonnet, Makefile, hack/cloud-image-uploader.sh, hack/cloud-image-uploader/azure.go, hack/cloud-image-uploader/main.go, hack/cloud-image-uploader/options.go, hack/test/e2e-aws-prepare.sh, hack/test/e2e-azure-prepare.sh, hack/test/e2e-azure.sh, hack/test/tfvars/azure.jq
=> chore: azure e2e

cmd/installer/cmd/imager/root.go
provides flag for imager to pull images insecurely from private registries
Forked from #8496
=> feat: provide insecure flag to imager

cmd/talosctl/cmd/mgmt/gen/config.go
=> fix: don't set default endpoints on gen config

hack/release.toml, internal/app/machined/pkg/controllers/runtime/kmsg_log.go, internal/app/machined/pkg/runtime/logging/sender_jsonlines.go, internal/app/machined/pkg/runtime/logging/sender_jsonlines_test.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go, pkg/machinery/config/config/machine.go, pkg/machinery/config/schemas/config.schema.json, pkg/machinery/config/types/v1alpha1/v1alpha1_logging.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go, pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go, website/content/v1.7/reference/configuration/v1alpha1/config.md, website/content/v1.7/schemas/config.schema.json, website/content/v1.7/talos-guides/configuration/logging.md
=> feat: add support for static extra fields for JSON logs

internal/app/machined/pkg/controllers/siderolink/userspace.go
Reading documentation is important, because `timer.Stop()` explicitly says that it will return false if it already expired *OR* it has been already stopped. Previous version of code would block forever and because of that code tunnel relay never started.
Take that into account with new version.
=> fix: make safeReset truly safe to call multiple times

pkg/imager/out.go
Previous approach relied on a field which is _only_ present if file-based PKI is passed in, and fails for e.g. Azure KMS.
See https://github.com/siderolabs/image-factory/issues/104
=> fix: generate secureboot ISO .der certificate correctly

internal/integration/api/extensions_qemu.go
See https://github.com/siderolabs/extensions/pull/355
=> test: add a test for 'spin' container runtime

cmd/talosctl/cmd/talos/root.go, pkg/imager/profile/internal/signer/azure/azure.go
Both of those contained incorrect comments.
fix function name 
=> docs: fix getAuthenticationMethod and completePathFromNode docs

website/content/v1.7/talos-guides/install/cloud-platforms/akamai.md
=> docs: update Akamai platform docs

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.25.1
=> feat: update Flannel to v0.25.1

internal/app/apid/pkg/backend/apid.go
Fixes #8552
This fixes up the previous fix where `for` condition was inverted, and also updates the idle timeout, so that the transition to idle happens before the timeout expires.
=> fix: close apid inter-backend connections gracefully for real

pkg/imager/filemap/filemap.go, pkg/imager/out.go
Fixes #8603
P.S. There's one more issue with architecture mix that needs to be resolved as well.
=> fix: mark overlay installer executable

hack/test/extensions/extension-patch-filter.jq, website/config.toml, website/content/v1.6/_index.md, website/content/v1.7/_index.md, website/content/v1.7/introduction/what-is-new/index.md
=> docs: make 1.7 docs the default

cmd/talosctl/cmd/mgmt/cluster/create.go
Some of the flags passed to `talosctl cluster create` were failing the input validation due to being incorrectly marked as mutually exclusive with the `--input-dir` flag.
Clean up the check to allow passing all flags along with the `--input-dir` flag if those flags impact the provisioning process in any way (i.e., not solely used in generating machine config).
Additionally, replace the mutual exclusion checks with Cobra's built-in function for that.
The flags which were incorrectly assumed to be mutually exclusive were:
```
networkIPv4Flag
networkIPv6Flag
networkMTUFlag
nameserversFlag
clusterDiskSizeFlag
clusterDisksFlag
useVIPFlag
bootloaderEnabledFlag
firewallFlag
```
The flag which was missing from the mutual exclusion list: 
```
diskEncryptionKeyTypesFlag
```
=> fix: allow more flags in `talosctl cluster create --input-dir`

Makefile, internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/metadata.go, internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go, internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack_test.go, internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go, website/content/v0.10/cloud-platforms/openstack.md, website/content/v0.11/cloud-platforms/openstack.md, website/content/v0.12/cloud-platforms/openstack.md, website/content/v0.13/cloud-platforms/openstack.md, website/content/v0.14/cloud-platforms/openstack.md, website/content/v0.8/cloud-platforms/openstack.md, website/content/v0.9/cloud-platforms/openstack.md, website/content/v1.0/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.1/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.2/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.3/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.4/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.5/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.6/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.7/talos-guides/install/cloud-platforms/openstack.md, website/content/v1.8/talos-guides/install/cloud-platforms/openstack.md
Change references for OpenStack to the correct capitalization.
_**Need to setup a working Linux VM for running tests.  macOS did not work the best.  Hence draft status.**_
Been working more with Talos on OpenStack as of recently and having the name wrong is a bit annoying.
=> style: use correct capitalization for openstack

internal/integration/api/common.go, internal/integration/base/api.go, internal/integration/base/k8s.go
Run a health check before the test, as the test depends on CoreDNS being healthy, and previous tests might disturb the cluster.
Also refactor by using watch instead of retries, make pods terminate fast.
=> test: improve DNS resolver test stability

internal/pkg/etcd/lock.go
By the time unlock is called, context might be already canceled.
=> fix: use a fresh context for etcd unlock

website/content/v1.7/introduction/troubleshooting.md, website/content/v1.8/introduction/troubleshooting.md
Should simplify the search of this error over the Internet.
=> docs: add logs example for the certificate errors troubleshooting

cmd/talosctl/pkg/talos/action/tracker.go
If the `reboot/reset/shutdown/upgrade` action tracker cannot read the boot ID from the node under `/proc/sys/kernel/random/boot_id` due to insufficient permissions (e.g., when `talosctl reboot` is used over Omni), fall back to skipping boot ID check instead of hard-failing.
Closes siderolabs/talos#7197.
=> fix: do not fail cli action tracker when boot id cannot be read

website/content/v1.7/talos-guides/network/ingress-firewall.md, website/content/v1.8/talos-guides/network/ingress-firewall.md
=> docs: add resource information, some grammar fixes

README.md, website/content/v1.0/_index.md, website/content/v1.1/_index.md, website/content/v1.2/_index.md, website/content/v1.3/_index.md, website/content/v1.4/_index.md, website/content/v1.5/_index.md, website/content/v1.6/_index.md, website/content/v1.7/_index.md, website/content/v1.8/_index.md
This updates the office hours in all "published" docs versions and in the readme.
=> chore: update office hours in talos repo

hack/test/e2e-gcp.sh
This PR moves the GCP tests to a new project there. I'm working on consolidating projects, names, and doing some reservations out there.
=> chore: update project in GCP testing

website/content/v1.8/introduction/quickstart.md, website/content/v1.8/talos-guides/install/local-platforms/docker.md
=> docs: fixing typos, docker socket info

website/content/v1.7/kubernetes-guides/network/multus.md, website/content/v1.8/kubernetes-guides/network/multus.md
Added documentation on Multus based on my own experience. 
The documentation on how to use Multus with Talos is missing.
=> Added documentation on using Multus with Talos

.github/workflows/ci.yaml, .github/workflows/integration-aws-cron.yaml, .github/workflows/integration-aws-nvidia-nonfree-cron.yaml, .github/workflows/integration-aws-nvidia-oss-cron.yaml, .github/workflows/integration-azure-cron.yaml, .github/workflows/integration-cilium-cron.yaml, .github/workflows/integration-cloud-images-cron.yaml, .github/workflows/integration-equinix-metal-cron.yaml, .github/workflows/integration-extensions-cron.yaml, .github/workflows/integration-image-factory-cron.yaml, .github/workflows/integration-images-cron.yaml, .github/workflows/integration-misc-cron.yaml, .github/workflows/integration-provision-0-cron.yaml, .github/workflows/integration-provision-1-cron.yaml, .github/workflows/integration-provision-2-cron.yaml, .github/workflows/integration-qemu-cron.yaml, .github/workflows/integration-qemu-csi-cron.yaml, .github/workflows/integration-qemu-encrypted-vip-cron.yaml, .github/workflows/integration-qemu-race-cron.yaml, .github/workflows/integration-reproducibility-test-cron.yaml, .github/workflows/integration-trusted-boot-cron.yaml, .kres.yaml
=> chore(ci): fix github action crons

.github/workflows/ci.yaml, .github/workflows/integration-aws-cron.yaml, .github/workflows/integration-aws-nvidia-nonfree-cron.yaml, .github/workflows/integration-aws-nvidia-oss-cron.yaml, .github/workflows/integration-azure-cron.yaml, .github/workflows/integration-cilium-cron.yaml, .github/workflows/integration-cloud-images-cron.yaml, .github/workflows/integration-equinix-metal-cron.yaml, .github/workflows/integration-extensions-cron.yaml, .github/workflows/integration-image-factory-cron.yaml, .github/workflows/integration-images-cron.yaml, .github/workflows/integration-misc-cron.yaml, .github/workflows/integration-provision-0-cron.yaml, .github/workflows/integration-provision-1-cron.yaml, .github/workflows/integration-provision-2-cron.yaml, .github/workflows/integration-qemu-cron.yaml, .github/workflows/integration-qemu-csi-cron.yaml, .github/workflows/integration-qemu-encrypted-vip-cron.yaml, .github/workflows/integration-qemu-race-cron.yaml, .github/workflows/integration-reproducibility-test-cron.yaml, .github/workflows/integration-trusted-boot-cron.yaml
Fix cron jobs by pulling in new kres changes.
=> fix(ci): fix crons fby rekres

internal/pkg/mount/pseudo.go
Fixes https://github.com/siderolabs/pkgs/issues/963
=> fix: mount `tracefs` filesystem

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.8/reference/configuration/v1alpha1/config.md
See https://github.com/etcd-io/etcd/releases/tag/v3.5.14
=> feat: update etcd to 3.5.14

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.25.3
=> feat: update Flannel to v0.25.3

pkg/provision/providers/vm/process.go
This never worked properly, as `Wait()` doesn't work for child processes, and `talosctl cluster destroy` is not a child of processes created by `talosctl cluster create`.
=> fix: clean up VM runners on cluster destroy

go.mod, go.sum, internal/app/machined/pkg/controllers/block/discovery.go, internal/integration/api/volumes.go, internal/integration/base/api.go, internal/integration/base/k8s.go, internal/integration/k8s/tink.go
Use shared locks, discover more partitions, some other small changes.
Re-enable the flaky test.
=> fix: volume discovery improvements

.github/workflows/ci.yaml, .github/workflows/integration-conformance-cron.yaml, .github/workflows/slack-notify.yaml, .kres.yaml, hack/test/e2e-cloud-tf.sh
This was missed when moving to GHA.
=> chore(ci): add conformance pipelines

internal/integration/api/extensions_qemu.go
The iscsi test broke when the new disks api was introduced making the test pass always, now filter other only `iscsi` disk types using the new disks API.
=> chore: use new disks api for iscsi tests

.github/workflows/ci.yaml, .github/workflows/integration-aws-nvidia-oss-cron.yaml, .kres.yaml, hack/test/e2e-aws-prepare.sh, hack/test/tfvars/nvidia.yaml, website/content/v1.8/talos-guides/configuration/nvidia-gpu-proprietary.md, website/content/v1.8/talos-guides/configuration/nvidia-gpu.md
Run e2e-aws-nvidia-oss with zfs extension enabled.
=> chore(ci): run e2e-aws-nvidia with zfs extension enabled

website/content/_index.html, website/content/v1.8/introduction/getting-started.md
=> docs: clarify direct access needed to nodes in insecure mode

website/content/v1.7/kubernetes-guides/network/deploying-cilium.md, website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
Small fixes to the crossplane deployment documentation.
Because the latest cilium CLI slightly changed. And there was a `\n` missing in the documentation.
=> Update deploying cilium docs for v1.7 and v1.8

pkg/machinery/config/container/container.go
Remove the need for additional allocation in case we use `EncodeString` and overall looks nicer.
=> chore: redo EncodeString and EncodeBytes using buffer interface

website/content/v1.7/talos-guides/install/cloud-platforms/gcp.md, website/content/v1.8/talos-guides/install/cloud-platforms/gcp.md
Compute command missing backslashes for new lines
=> doc: add missing backslashes

hack/release.toml, pkg/machinery/config/contract.go, pkg/machinery/config/contract_test.go, pkg/machinery/config/generate/init.go, pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/base-controlplane.yaml, pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/overrides-controlplane.yaml, pkg/machinery/constants/constants.go
=> feat: add label 'exclude-from-external-load-balancers' for cp nodes

pkg/minimal/limits.go
Reduce memory requirement for controlplane nodes by 200M. (2*1024-200).
=> chore: reduce memory requirement for contrplane nodes

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Fixes #9017
Don't assume the config is there before trying to access it.
=> fix: panic on shutdown

hack/cloud-image-uploader/aws.go
Ensure that non-TLS connections are denied to S3 buckets via policy. Required for compliance.
=> chore: ensure tls required on s3 buckets

internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
=> feat: provide POD_IP env var to scheduler and controller-manager

website/content/v1.7/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md, website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
jiva operator was moved to the openebs-archive
Applied some yaml linting too.
=> docs: update openebs-jiva helm repo

website/content/v1.8/kubernetes-guides/network/multus.md
Extends documentation around multus CNI plugin
I spent my Sunday evening deep diving on why these files were missing ;-)
=> docs: extend multus configuration for Cilium

.github/workflows/ci.yaml, .github/workflows/integration-misc-1-cron.yaml, .github/workflows/integration-misc-4-cron.yaml, .kres.yaml, hack/test/e2e-qemu.sh, internal/integration/base/k8s.go, internal/integration/k8s/apparmor.go, internal/integration/k8s/testdata/apparmor.yaml
Add a test that verifies pods can be scheduled with `RuntimeDefault` apparmor profile.
=> chore: add test for apparmor

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.8/reference/configuration/v1alpha1/config.md
See https://github.com/coredns/coredns/releases/tag/v1.11.3
=> feat: update CoreDNS to 1.11.3

website/content/v1.8/talos-guides/install/cloud-platforms/aws.md
There is a better way to do for-loop in shell
=> docs: better for-loop in shell

hack/release.toml
See https://github.com/siderolabs/kubelet/pull/84
=> chore: document slim kubelet image

.github/workflows/ci.yaml, .github/workflows/integration-aws-nvidia-nonfree-cron.yaml, .github/workflows/integration-aws-nvidia-oss-cron.yaml, .kres.yaml, hack/test/e2e-aws-prepare.sh
Update nvidia integration tests to reflect new support matrix.
Part of: #9086.
=> chore(ci): update nvidia integration tests

hack/test/e2e.sh
Cilium helm values have changed from string to boolean.
Found in https://github.com/siderolabs/talos/actions/runs/10328653708/job/28595449398
=> chore(ci): fix cilium ci tests

website/content/v0.10/guides/configuring-network-connectivity.md, website/content/v0.11/guides/configuring-network-connectivity.md, website/content/v0.12/guides/configuring-network-connectivity.md, website/content/v0.13/guides/configuring-network-connectivity.md, website/content/v0.14/guides/configuring-network-connectivity.md, website/content/v0.8/guides/configuring-network-connectivity.md, website/content/v0.9/guides/configuring-network-connectivity.md, website/content/v1.0/learn-more/talos-network-connectivity.md, website/content/v1.1/learn-more/talos-network-connectivity.md, website/content/v1.2/learn-more/talos-network-connectivity.md, website/content/v1.3/learn-more/talos-network-connectivity.md, website/content/v1.4/learn-more/talos-network-connectivity.md, website/content/v1.5/learn-more/talos-network-connectivity.md, website/content/v1.6/learn-more/talos-network-connectivity.md, website/content/v1.7/learn-more/talos-network-connectivity.md, website/content/v1.8/learn-more/talos-network-connectivity.md
=> docs: fix typo in doc

website/content/v1.7/talos-guides/install/virtualized-platforms/vmware.md, website/content/v1.8/talos-guides/install/virtualized-platforms/vmware.md
=> docs: fix the VMWare docs

Makefile, pkg/imager/iso/grub.go, pkg/imager/iso/iso.go, pkg/imager/iso/iso_test.go, pkg/imager/iso/uefi.go, pkg/machinery/imager/quirks/quirks.go
Fixes https://github.com/siderolabs/talos/issues/8769
=> feat: ISO VolumeID named with ReleaseID

hack/gotagsrewrite/main.go, internal/app/machined/internal/server/v1alpha1/v1alpha1_monitoring.go, internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go, internal/app/machined/pkg/adapters/perf/cpu.go, internal/app/machined/pkg/controllers/network/operator/dhcp4.go, internal/app/machined/pkg/controllers/network/operator/dhcp6.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_events.go, internal/pkg/containers/cri/cri.go, internal/pkg/dashboard/components/components.go, internal/pkg/dashboard/components/graphs.go
=> chore: replace `if` blocks with `min`/`max` functions

pkg/provision/providers/qemu/arch.go, pkg/provision/providers/qemu/launch.go, pkg/provision/providers/qemu/node.go
Improve cluster create UX on aarch64.
=> chore: improve `cluster create` UX on aarch64

pkg/cluster/check/default.go
Re-structure k8s components health checks so that K8s health can be independently checked without auxiliary components being up.
=> chore: restructure k8s component health checks

internal/pkg/dashboard/resourcedata/resourcedata.go
A single resource not being there (i.e., the type does not exist on an older version of Talos) or not allowed to be read for whatever reason should not interrupt the refresh cycle of the other resources' status.
=> fix: always handle `PermissionDenied` in dashboard resource watches

website/content/v1.7/talos-guides/network/kubespan.md, website/content/v1.8/talos-guides/network/kubespan.md
Noticed a typo in the documentation
It should be corrected
=> docs: Update kubespan.md - fix typo

go.mod, go.sum
See https://github.com/siderolabs/go-smbios/issues/16
=> fix: bump go-smbios for broken SMIOS tables

hack/modules-amd64.txt, hack/modules-arm64.txt
=> fix: add missing host/nvme-rdma

website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
Fix incorrect helm install command for cilium
User have a better experience installing cilium
=> docs: kubeProxyReplacement from "disabled" to "false"

cmd/talosctl/cmd/mgmt/cluster/create.go
The initramfs unarchive won't work as it's extension is `xz` while the actual compression is `zst`.
=> fix: never unarchive initramfs when loading boot assets in talosctl

cmd/talosctl/cmd/mgmt/cluster/internal/firewallpatch/firewallpatch.go, pkg/machinery/config/configloader/internal/decoder/decoder.go, pkg/machinery/config/configloader/internal/decoder/decoder_test.go, pkg/machinery/config/configloader/internal/decoder/testdata/double/v1alpha1.yaml, pkg/machinery/config/configpatcher/load.go, pkg/machinery/config/configpatcher/load_test.go, pkg/machinery/config/configpatcher/strategic.go, pkg/machinery/config/container/container.go
=> chore: disallow duplicate documents on decoder level

hack/release.toml, internal/app/machined/pkg/controllers/config/acquire.go, internal/app/machined/pkg/controllers/config/acquire_test.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go, pkg/machinery/constants/constants.go, website/content/v1.8/reference/kernel.md
=> feat: acquire machine config inline from kernel cmdline

hack/release.toml, website/content/v1.8/introduction/what-is-new/index.md, website/content/v1.8/kubernetes-guides/configuration/device-plugins.md
=> docs: document `/dev/net/tun` compatibility

CONTRIBUTING.md, README.md, SECURITY.md
Document security vulnerabilty reporting process.
Minor fixes in other docs, and add OpenSSF badge.
=> docs: add SECURITY.md

internal/integration/api/common.go, internal/integration/api/extensions_qemu.go, internal/integration/api/volumes.go, internal/integration/base/k8s.go
Refactor tests to avoid code duplication.
=> chore: refactor tests

website/config.toml, website/themes/docsy/layouts/partials/page-meta-links.html
=> docs: enabled 'edit on GitHub' link

internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-cloud-init.yaml, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-nocloud.yaml
=> feat: add support for CI Network config in nocloud

website/content/v1.8/talos-guides/configuration/nvidia-gpu.md, website/content/v1.9/talos-guides/configuration/nvidia-gpu.md
=> docs: fix nvidia CRI config example

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.25.7
=> feat: update Flannel to v0.25.7

internal/app/machined/pkg/controllers/block/discovery.go, internal/app/machined/pkg/controllers/block/disks.go
Fixes https://github.com/siderolabs/go-blockdevice/issues/113
=> fix: skip ram disks

website/content/v1.8/talos-guides/configuration/nvidia-gpu-proprietary.md, website/content/v1.8/talos-guides/configuration/nvidia-gpu.md, website/content/v1.9/talos-guides/configuration/nvidia-gpu-proprietary.md, website/content/v1.9/talos-guides/configuration/nvidia-gpu.md
Added details about the difference in hardware support between Proprietary and OSS drivers for Nvidia. 
I tripped myself up by choosing the OSS driver (we love OSS after all :) ), without realizing that my Pascal-era Tesla P4s aren't supported by the OSS driver.
=> doc: Update Nvidia docs with Proprietary/OSS hardware reqs

pkg/machinery/resources/hardware/pcidevice.go
=> fix: update incorrect alias for PCIDevice resource

website/content/v1.8/introduction/prodnotes.md, website/content/v1.9/introduction/prodnotes.md
Fix typo in https://www.talos.dev/v1.8/introduction/prodnotes.
Typo.
=> Fix typo in prodnotes.md

website/content/v1.8/talos-guides/configuration/performance-tuning.md, website/content/v1.9/talos-guides/configuration/performance-tuning.md
Thanks to various people who submitted this information over time, and special thanks to @maxpain for IOMMU fix.
Fixes #9539
=> docs: add documentation on performance tuning

ADOPTERS.md
Ok I guess I managed to fail all CI with this tiny doc change.
Do I have to spend the time to figure this out or can we just push it through? 😅
=> Add Mynewsdesk to ADOPTERS.md

internal/integration/api/containers.go, pkg/images/list.go
Fix the test, and update the reference.
=> fix: update the CRI sandbox image reference

pkg/imager/iso/uefi.go
The Secureboot ISO previously generated has just an EFI parition.
Now generate iso with both the EFI partition and also having ISO filesystem having the content so *File System transposition* also works.
Fixes: #9565
=> fix: generation of SecureBoot iso

internal/app/machined/pkg/system/runner/process/process.go
Replace `[]func()` with `[]io.Closer` in `process.processRunner.build`.
=> chore: small refactoring

website/content/v1.8/talos-guides/install/bare-metal-platforms/network-config.md
Fixing typo 0xa->0x0a
Documentation update with validated values
To improve documentation
=> Fixing documentation typo

website/content/v1.9/talos-guides/install/bare-metal-platforms/network-config.md
Also fix typo `0xa`->`0x0a` in 1.9 docs.
=> docs: update network-config.md (cont)

.github/workflows/ci.yaml, .kres.yaml, Dockerfile, Makefile
Add Windows ARM64 build for talosctl
Windows on ARM is starting to get popular so its about time 
=> feat: Add Windows ARM64 build for talosctl

Dockerfile
Fix talosctl windows arm64 build, #9626 missed a step.
=> fix: talosctl windows arm64

internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
=> fix: update permissions for logging directories in /var

internal/integration/integration_test.go, internal/integration/provision/provision.go, pkg/cluster/crashdump.go, pkg/provision/access/adapter.go, pkg/provision/providers/docker/crashdump.go, pkg/provision/providers/docker/create.go, pkg/provision/providers/docker/destroy.go, pkg/provision/providers/docker/reflect.go, pkg/provision/providers/docker/result.go, pkg/provision/providers/vm/crashdump.go
Generate support zip on crashdump.
=> chore: generate support zip for crashdump

hack/release.toml
=> docs: add apparmor enablement release notes

.github/workflows/ci.yaml, .github/workflows/integration-misc-4-cron.yaml, .kres.yaml, hack/release.toml, hack/test/patches/usernamespace.yaml, internal/integration/k8s/testdata/usernamespace.yaml, internal/integration/k8s/usernamespace.go, website/content/v1.9/kubernetes-guides/configuration/usernamespace.md
Add docs and test for usernamespaces support in Kubernetes.
Fixes: #8554
=> docs: add docs on usernamespace support in k8s

pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go, pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Add a similar check for bridged interfaces to ensure that they do not have addresses configured. The implementation combines the checks for bonded and bridged interfaces to avoid code duplication. Error messages have been slightly rephrased to match the changed scope.
Additionally fixes the test case implementation for addresses on bonded interfaces to include eth2 which was configured but not actually used in the test.
Bridged interfaces should not have IP addresses, the addresses should be configured on the parent bridge instead.
=> feat: check bridged interfaces should not have addresses

internal/app/machined/pkg/system/runner/process/process.go
Don't try cgroups/OOM scoe if not specified in the runner spec.
=> test: fix unpriviliged process runner test

pkg/machinery/cel/cel.go, pkg/machinery/config/types/block/volume_config_test.go
=> fix: allow CEL expressions config merge

cmd/talosctl/cmd/talos/image.go, cmd/talosctl/cmd/talos/processes.go, internal/integration/cli/image.go, pkg/imager/cache/cache.go, website/content/v1.9/reference/cli.md
=> feat: image cache gen

pkg/imager/cache/cache.go
The initial code missed saving the image config and the platform specific manifest.
=> fix: missing config and platform manifest

pkg/imager/cache/cache.go
=> fix: no longer leak `Close` reader.

website/content/v1.6/introduction/getting-started.md, website/content/v1.7/introduction/getting-started.md, website/content/v1.8/introduction/getting-started.md, website/content/v1.9/introduction/getting-started.md
Some commands were missing a parameter for talosconfig.
Help others not get stuck :)
=> Update getting-started.md - add missing talosconfig parameter

internal/pkg/selinux/selinux.go
Do not do string lookups in repetitive calls. We do not support changing SELinux status during runtime, so once we read this we can assume status does not change.
Also avoid unneeded FS writes when appropriate label is already set on file.
=> refactor: optimize flags and SetLabel

internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
On devtmpfs or sysfs SELinux attribute is not listed unless it has been set, yet it is available and represents the SELinux label of file.
=> fix: show SELinux labels on pseudo-fs

internal/pkg/containers/image/image.go, pkg/machinery/resources/time/condition.go
=> fix: small logrus fixes

website/content/v1.8/advanced/install-kubevirt.md, website/content/v1.9/advanced/install-kubevirt.md
rebase of PR #9522
@MichaelTrip
=> docs: add kubevirt install

.github/ISSUE_TEMPLATE/config.yml, internal/app/machined/pkg/controllers/cri/image_cache_config.go, internal/app/machined/pkg/controllers/cri/image_cache_config_test.go, internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go, pkg/machinery/config/config/machine.go, pkg/machinery/config/schemas/config.schema.json, pkg/machinery/config/types/v1alpha1/v1alpha1_features.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go, website/content/v1.9/reference/configuration/v1alpha1/config.md, website/content/v1.9/schemas/config.schema.json
Make it nested, so that we can expand easily to support e.g. distributed cache.
=> chore: update image cache config

Dockerfile, hack/cri-plugin.part, hack/release.toml, internal/app/machined/pkg/controllers/files/cri_base_runtime_spec.go, internal/app/machined/pkg/controllers/files/cri_base_runtime_spec_test.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go, internal/integration/api/common.go, internal/integration/base/api.go, internal/integration/base/k8s.go, pkg/machinery/config/config/machine.go, pkg/machinery/config/schemas/config.schema.json, pkg/machinery/config/types/v1alpha1/v1alpha1_examples.go, pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go, pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go, pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go, pkg/machinery/constants/constants.go, website/content/v1.9/advanced/oci-base-spec.md, website/content/v1.9/reference/configuration/v1alpha1/config.md, website/content/v1.9/schemas/config.schema.json
=> feat: support overriding base OCI spec for CRI

website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md, website/content/v1.8/talos-guides/install/local-platforms/virtualbox.md, website/content/v1.9/talos-guides/install/local-platforms/virtualbox.md
=> docs: fix typo in virtualbox docs

website/content/v1.8/advanced/install-kubevirt.md, website/content/v1.9/advanced/install-kubevirt.md
=> Docs: fix KubeVirt links

website/content/v1.8/kubernetes-guides/network/deploying-cilium.md, website/content/v1.9/kubernetes-guides/network/deploying-cilium.md
Update the Cilium CNI Deployment Docu and Method 5: Using a Job to satisfy #9835.
Update the Cilium CNI Deployment Docu and Method 5: Using a Job to satisfy #9835
Update the Cilium CNI Deployment Docu and Method 5: Using a Job to satisfy #9835
Fixes #9835
=> Update the Cilium CNI Deployment Docu and Method 5: Using a Job

internal/app/machined/pkg/controllers/network/resolver_merge.go
Remove unnecessary allocations, streamline logic.
=> chore: refactor mergeDNSServers func

.github/workflows/ci.yaml, .github/workflows/integration-cilium-cron.yaml, .github/workflows/integration-conformance-cron.yaml, .github/workflows/integration-extensions-cron.yaml, .kres.yaml, hack/test/e2e-qemu.sh
=> test: use two workers in qemu tests by default

.github/workflows/ci.yaml, .kres.yaml, Makefile, hack/test/e2e-qemu.sh, hack/test/e2e.sh, hack/test/patches/image-cache.yaml, internal/integration/cli/image.go, internal/integration/cli/list.go, pkg/imager/cache/cache.go
Provide separate `integration/image-cache` tag.
Closes #9860
=> chore: add integration tests for image-cache

hack/release.toml
Couple of syntax and grammar corrections.
=> docs: fix a few mistakes in release notes

Makefile, hack/release.toml, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
=> feat: update Linux to 6.12.3

internal/app/machined/pkg/controllers/cri/registries_config.go, internal/app/machined/pkg/controllers/cri/registries_config_test.go, pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
One billion dollar mistake strikes again. Increase code coverage.
Closes #9912
=> fix: avoid nil-pointer-panic in `RegistriesConfigController`

internal/app/machined/pkg/controllers/k8s/control_plane.go, internal/app/machined/pkg/controllers/k8s/control_plane_test.go
We were appending to existing slice, fix by using a variable.
=> fix: authorization config gen

cmd/talosctl/cmd/mgmt/cluster/create.go, pkg/provision/providers/qemu/launch.go, pkg/provision/providers/qemu/node.go, pkg/provision/request.go, website/content/v1.9/reference/cli.md
Emulates a boot from a USB stick.
=> test: add an option to boot from a USB stick

internal/integration/api/apply-config.go, internal/integration/api/common.go, internal/integration/api/etcd.go, internal/integration/api/extensions_qemu.go, internal/integration/api/reboot.go, internal/integration/api/update-hostname.go, internal/integration/api/volumes.go, internal/integration/base/api.go, internal/integration/base/k8s.go
=> test: cleanup failed Kubernetes pods

website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md, website/content/v1.9/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
Closes #9880
We get a PR a week to change the path one way or another, it turns out it's different for different OpenEBS version in their docs.
=> docs: mention different paths for OpenEBS

internal/app/machined/pkg/controllers/block/volume_manager.go, internal/pkg/meta/internal/adv/syslinux/syslinux.go, internal/pkg/meta/internal/adv/talos/talos.go, internal/pkg/meta/meta.go
Doesn't fix anything, but the hope is that it would help with #9852 and #9786.
=> chore: add more debugging logs for META and volumes

.github/renovate.json, .kres.yaml
=> chore: rekres for renovate changes

internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go, internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-serverscom.yaml
=> fix: match MAC addresses case-insensitive (nocloud)

.github/renovate.json, .kres.yaml
=> fix: renovate typo

website/content/v1.8/kubernetes-guides/network/deploying-cilium.md, website/content/v1.9/kubernetes-guides/network/deploying-cilium.md
Adding note about this issue: https://github.com/siderolabs/talos/pull/9200#issuecomment-2463361375
It would save me some time. Hope it will help others.
=> Update deploying-cilium.md - note about coredns and cilium

pkg/imager/cache/cache.go, pkg/imager/profile/input.go
Support gcr.io auth for cache and image gen.
=> chore: support gcr.io auth for cache and image gen

internal/app/machined/internal/server/v1alpha1/v1alpha1_time.go, internal/pkg/ntp/ntp.go
Fix query function used by CLI to match the time syncer behavior.
=> fix: make talosctl time work with PTP time sync

cmd/talosctl/cmd/talos/bootstrap.go, website/content/v1.10/introduction/getting-started.md, website/content/v1.10/reference/cli.md, website/content/v1.10/talos-guides/install/virtualized-platforms/proxmox.md, website/content/v1.9/introduction/getting-started.md, website/content/v1.9/talos-guides/install/virtualized-platforms/proxmox.md
=> docs: fix several typos

website/content/v1.10/kubernetes-guides/network/deploying-cilium.md, website/content/v1.10/talos-guides/install/boot-assets.md, website/content/v1.9/kubernetes-guides/network/deploying-cilium.md, website/content/v1.9/talos-guides/install/boot-assets.md
=> docs: fix two typos

hack/test/e2e-qemu.sh
=> test: fix apparmor tests

pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go, pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
=> fix: update field name for bus path disk selector

internal/app/syslogd/internal/parser/parse_test.go, internal/integration/api/extensions_qemu.go
Part of: https://github.com/siderolabs/extensions/issues/572
=> chore(ci): better zfs checks

website/content/v1.10/kubernetes-guides/configuration/ceph-with-rook.md, website/content/v1.9/kubernetes-guides/configuration/ceph-with-rook.md
Fixed command to wait for ceph-rook HEALTH_OK
=> ceph-with-rook.md: Fixed command to wait for ceph-rook HEALTH_OK

hack/release.toml, pkg/machinery/config/generate/init.go, pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types.go, pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go, pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
This reverts commit 32c67c27c393c989f9d70ccb8506c4735f70d494.
=> chore: revert: drop deprecated allowSchedulingOnMasters

internal/pkg/dashboard/apidata/node.go
=> fix: yet another dashboard panic

pkg/imager/profile/profile.go, pkg/machinery/extensions/extensions_test.go, pkg/machinery/extensions/validate.go, pkg/machinery/imager/quirks/quirks.go
=> fix: a couple of imager panics/crashes

.github/workflows/ci.yaml, .github/workflows/integration-qemu-csi-openebs-cron.yaml, .github/workflows/slack-notify.yaml, .kres.yaml, hack/test/patches/openebs-cp.yaml, hack/test/patches/openebs.yaml, internal/integration/api/extensions_qemu.go, internal/integration/api/volumes.go, internal/integration/api/wipe.go, internal/integration/base/api.go, internal/integration/k8s/constants.go, internal/integration/k8s/openebs.go, internal/integration/k8s/testdata/openebs-diskpool.yaml, internal/integration/k8s/testdata/openebs-values.yaml
Add a test in CI for OpenEBS MayaStor.
=> chore(ci): add test for OpenEBS MayaStor

.github/workflows/ci.yaml, .github/workflows/integration-qemu-csi-longhorn-cron.yaml, .github/workflows/integration-qemu-csi-openebs-cron.yaml, .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml, .kres.yaml, internal/integration/base/k8s.go
Save the CSI tests fio results as GitHub artifacts.
=> chore(ci): save csi tests fio results

Makefile, hack/release.toml, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
=> chore: update Go to 1.23.5

cmd/talosctl/cmd/talos/etcd.go, website/content/v1.10/introduction/troubleshooting.md, website/content/v1.9/introduction/troubleshooting.md
CLI is actually "members" not "member"
Minor documentation update
Confusing when first running through docs
=> docs: update troubleshooting.md

.github/workflows/ci.yaml, .github/workflows/integration-qemu-csi-longhorn-cron.yaml, .github/workflows/integration-qemu-csi-openebs-cron.yaml, .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml, .kres.yaml, hack/test/e2e-qemu.sh, hack/test/patches/longhorn-cp.yaml, hack/test/patches/longhorn.yaml, hack/test/patches/openebs.yaml, internal/integration/base/k8s.go, internal/integration/k8s/constants.go, internal/integration/k8s/longhorn.go, internal/integration/k8s/testdata/longhorn-v2-disk-patch.yaml, internal/integration/k8s/testdata/longhorn-v2-engine-values.yaml, internal/integration/k8s/testdata/longhorn-v2-storageclass.yaml
Add tests with longhorn v2 engine.
Fixes: #9669
=> chore(ci): add tests with longhorn v2 engine

website/content/v1.10/introduction/getting-started.md, website/content/v1.10/introduction/prodnotes.md, website/content/v1.10/kubernetes-guides/configuration/local-storage.md, website/content/v1.10/talos-guides/install/local-platforms/qemu.md, website/content/v1.10/talos-guides/install/local-platforms/virtualbox.md, website/content/v1.10/talos-guides/install/virtualized-platforms/hyper-v.md, website/content/v1.10/talos-guides/install/virtualized-platforms/proxmox.md, website/content/v1.7/introduction/getting-started.md, website/content/v1.7/introduction/prodnotes.md, website/content/v1.7/talos-guides/install/local-platforms/qemu.md, website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md, website/content/v1.7/talos-guides/install/virtualized-platforms/hyper-v.md, website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md, website/content/v1.8/introduction/getting-started.md, website/content/v1.8/introduction/prodnotes.md, website/content/v1.8/kubernetes-guides/configuration/local-storage.md, website/content/v1.8/talos-guides/install/local-platforms/qemu.md, website/content/v1.8/talos-guides/install/local-platforms/virtualbox.md, website/content/v1.8/talos-guides/install/virtualized-platforms/hyper-v.md, website/content/v1.8/talos-guides/install/virtualized-platforms/proxmox.md, website/content/v1.9/introduction/getting-started.md, website/content/v1.9/introduction/prodnotes.md, website/content/v1.9/kubernetes-guides/configuration/local-storage.md, website/content/v1.9/talos-guides/install/local-platforms/qemu.md, website/content/v1.9/talos-guides/install/local-platforms/virtualbox.md, website/content/v1.9/talos-guides/install/virtualized-platforms/hyper-v.md, website/content/v1.9/talos-guides/install/virtualized-platforms/proxmox.md
First of all, **thank you** so much for providing this amazing project!
I played a little bit with Talos in the last few days, and I noticed that some specific parts of the docs could maybe be improved a little bit (mostly just typos). So here are my suggestions 🙂 let me know what you think
Fix docs:
- Fixed "worker02" in docs down to 1.7
- Update manual installation parts in docs.
- Fixed prodnotes YAML indentation in docs down to 1.7
- Ad some hints to the Local Path Provisioner section
See section above.
=> docs: fix typos and add more explanations in docs

internal/integration/base/k8s.go, internal/integration/k8s/longhorn.go
Wait for longhorn node resource before checking resource status.
=> fix(ci): wait for longhorn node resource

internal/integration/base/k8s.go
The code was previously calling `GetUnstructuredResource` which wraps
the k8s error, construct the mapping and call the api directly.
=> fix(ci): k8s integration suite wait for resource.

internal/pkg/uki/internal/pe/native.go, internal/pkg/uki/internal/pe/pe_test.go
Required for multi-profile UKIs.
=> fix: handling of PE sections with duplicate names

internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go, internal/app/machined/pkg/runtime/v1alpha1/platform/aws/testdata/expected.yaml
=> fix: use local NTP for AWS platform

.github/workflows/ci.yaml, .github/workflows/integration-misc-0-cron.yaml, .github/workflows/integration-misc-2-cron.yaml, .kres.yaml
Fix integration-misc-{0,2} crons by generating the required files.
=> fix(ci): fix intergration-misc crons

hack/docgen/schema.go, pkg/machinery/config/schemas/config.schema.json, website/content/v1.10/schemas/config.schema.json
Descriptions were being added to the fields but not to the top level objects
=> feat: add description to schema object defs

internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
Prefer sd-boot for all UEFI systems.
=> feat: prefer sd-boot for UEFI

.github/workflows/integration-image-cache-cron.yaml, .github/workflows/slack-notify.yaml, .kres.yaml
=> test: enable image-cache in the cron

.github/workflows/ci.yaml, .github/workflows/integration-qemu-csi-longhorn-cron.yaml, .github/workflows/integration-qemu-race-cron.yaml, .kres.yaml, Makefile, hack/release.toml, internal/integration/k8s/longhorn.go
=> fix(ci): fix integration tests

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.10/reference/configuration/v1alpha1/config.md
See https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md
=> feat: update etcd to 3.5.19

pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.26.5
=> feat: update Flannel to 0.26.5

.github/workflows/ci.yaml, .github/workflows/integration-image-cache-cron.yaml, .kres.yaml
=> fix(ci): image-cache cron

website/content/v1.10/advanced/metal-network-configuration.md, website/content/v1.4/advanced/metal-network-configuration.md, website/content/v1.5/advanced/metal-network-configuration.md, website/content/v1.6/advanced/metal-network-configuration.md, website/content/v1.7/advanced/metal-network-configuration.md, website/content/v1.8/advanced/metal-network-configuration.md, website/content/v1.9/advanced/metal-network-configuration.md
=> fix: change from "init6" to "inet6" in docs

pkg/machinery/platforms/platforms.go
Very small PR to fix the link to UpCloud Talos guide docs page in Image Factory.
I saw the link was wrong, decided to make a PR to fix it.
- fails to GPG as I'm not part of the org
=> fix: typo in machinery CloudPlatforms

website/content/v1.10/talos-guides/install/single-board-computers/unofficial.md, website/content/v1.9/talos-guides/install/single-board-computers/unofficial.md
=> docs: add documentation on unofficial SBC forks

internal/integration/cli/list.go
=> fix(ci): fix image cache test

.github/workflows/ci.yaml, .github/workflows/integration-conformance-cron.yaml, .kres.yaml
Make sure names are not conflicting so that integration-qemu can be uploaded
=> chore: fix conformance artifact name

Makefile, internal/integration/api/extensions_qemu.go
Fixes #10575
See https://github.com/siderolabs/extensions/pull/651
=> fix: kata extension

website/content/v1.10/kubernetes-guides/network/multus.md, website/content/v1.9/kubernetes-guides/network/multus.md
Also race problems in 'install-multus-binary' container.
Forked from #10582
=> docs: add information about Cilium exclusive CNI

website/content/v1.10/talos-guides/install/cloud-platforms/aws.md, website/content/v1.9/talos-guides/install/cloud-platforms/aws.md
Correct typo.
Improve documentation.
=> chore: fix typo in aws docs

cmd/installer/pkg/install/errata.go, cmd/installer/pkg/install/install.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
Fix by setting the default booted entry as like sd-boot.
Fixes: #10577
=> fix: upgrades with kexec

website/content/v1.10/advanced/building-images.md, website/content/v1.10/advanced/developing-talos.md
=> docs: update development docs.

.github/workflows/ci.yaml, .github/workflows/integration-conformance-enforcing-cron.yaml, .github/workflows/integration-misc-1-enforcing-cron.yaml, .github/workflows/integration-misc-3-enforcing-cron.yaml, .github/workflows/integration-misc-4-enforcing-cron.yaml, .github/workflows/integration-qemu-enforcing-cron.yaml, .github/workflows/integration-trusted-boot-enforcing-cron.yaml, .kres.yaml, hack/test/e2e-qemu.sh
Build UKI certs in cron.
Also pass `enforcing=1` to the initial step (if applicable).
=> test: fix enforcing steps in cron

Dockerfile, cmd/installer/pkg/install/install.go, hack/cleanup.sh, internal/app/machined/pkg/controllers/block/internal/volumes/format.go, internal/pkg/partition/format.go, pkg/machinery/imager/quirks/quirks.go, pkg/machinery/imager/quirks/quirks_test.go, pkg/makefs/makefs.go, pkg/makefs/xfs.go
Use xfs mkfs config versions based on Talos versions.
Fixes: #9955
=> feat: support xfs mkfs config version

.github/workflows/ci.yaml, .github/workflows/integration-misc-2-cron.yaml, .kres.yaml, api/resource/definitions/runtime/runtime.proto, internal/app/machined/pkg/controllers/runtime/security_state.go, internal/integration/api/trustedboot.go, internal/integration/api/uki.go, internal/integration/base/base.go, internal/integration/integration_test.go, pkg/machinery/api/resource/definitions/runtime/runtime.pb.go, pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go, pkg/machinery/resources/runtime/security_status.go, website/content/v1.10/reference/api.md
Expose if system is booted with a UKI in `securitystate` resource.
Fixes: #10620
=> feat: expose if system is booted with UKI

.github/workflows/ci.yaml, .github/workflows/integration-gcp-cron.yaml, .kres.yaml, cmd/talosctl/cmd/talos/list.go, hack/cloud-image-uploader/gcp.go, internal/app/machined/pkg/controllers/runtime/security_state.go, internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/efivars.go, internal/integration/api/common.go, internal/integration/api/uki.go, internal/integration/base/base.go, internal/integration/integration_test.go
fix: uki boot detection
Fix UKI boot detection
Also fix bug introduced by #10640 which imported the unix package making talosctl non-unix builds broken
=> fix: uki boot detection

.github/workflows/ci.yaml, .github/workflows/integration-gcp-cron.yaml, .kres.yaml, hack/cloud-image-uploader/aws.go
Prefer UEFI boot for AWS AMI's.
=> feat: prefer uefi boot for aws ami's

api/resource/definitions/runtime/runtime.proto, hack/test/tfvars/aws.jq, internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go, internal/app/machined/pkg/runtime/v1alpha1/platform/aws/metadata.go, internal/app/machined/pkg/runtime/v1alpha1/platform/aws/testdata/expected.yaml, internal/app/machined/pkg/runtime/v1alpha1/platform/aws/testdata/metadata.json, internal/integration/api/platform.go, pkg/machinery/api/resource/definitions/runtime/runtime.pb.go, pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go, pkg/machinery/resources/runtime/deep_copy.generated.go, pkg/machinery/resources/runtime/platform_metadata.go, website/content/v1.10/reference/api.md
We can add on other platforms as well as we go.
See https://github.com/siderolabs/omni/issues/1059
=> feat: add support for instance tags on AWS

internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go, internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/metadata.go, internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/testdata/expected.yaml, internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/testdata/metadata.json, internal/integration/api/platform.go
=> feat: add support for GCP instance tags

internal/app/machined/pkg/controllers/block/lvm.go
=> fix: skip lvm activation if meta is not found

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.26.6
=> feat: update Flannel to v0.26.6

website/content/v1.0/introduction/theila.md, website/content/v1.1/introduction/theila.md, website/content/v1.10/talos-guides/configuration/patching.md, website/content/v1.2/talos-guides/configuration/patching.md, website/content/v1.3/kubernetes-guides/configuration/storage.md, website/content/v1.3/talos-guides/configuration/patching.md, website/content/v1.4/kubernetes-guides/configuration/storage.md, website/content/v1.4/talos-guides/configuration/patching.md, website/content/v1.5/talos-guides/configuration/patching.md, website/content/v1.6/talos-guides/configuration/patching.md, website/content/v1.7/talos-guides/configuration/patching.md, website/content/v1.8/talos-guides/configuration/patching.md, website/content/v1.9/talos-guides/configuration/patching.md, website/layouts/_default/_markup/render-heading.html
* add anchors to headings
* fix text collision on tabpane elements:
previously:
=> Docs improvements

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.26.7
=> feat: update Flannel to v0.26.7

pkg/machinery/platforms/sbcs.go
=> feat: add new SBCs

internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
fix GRUB install EFI mount point.
=> fix: grub EFI mount point

internal/app/machined/pkg/system/runner/containerd/containerd.go, internal/app/machined/pkg/system/runner/process/process.go
=> fix: extension services logging to console

internal/pkg/dns/runnner.go
I observed a random failure (via Sidero Metal integration tests) when Talos fails to reboot due to the runner never shutting down.
A probable root cause is a bug in the `dns` library (which runs the DNS server), but we need to ensure this code always terminates, even at the price of leaking a running DNS server.
=> fix: force DNS runner shutdown on timeout

hack/test/provision-tests.sh, internal/integration/provision/provision.go, internal/integration/provision/upgrade.go
Use disk image to test dual boot bios provision test.
=> fix(ci): bios provision test

pkg/cluster/kubernetes/kubelet.go, pkg/cluster/kubernetes/talos_managed.go
Preserve the `-fat`, `-slim` kubelet image suffixes while upgrading `kubelet` images.
Fixes #10488
=> fix: preserve kubelet image suffix

internal/integration/api/platform.go
It seems that the integration test introduced in
https://github.com/siderolabs/talos/pull/10792 is causing some unintented side-effects in kube-apiserver -> kubelet communication (most probably around the TLS certificate??).
Instead of assigning dummy external IP, create a dummy link.
=> test: replace platform metadata test

website/content/v1.10/_index.md, website/content/v1.9/_index.md, website/hugo.toml
In preparation for Talos 1.10.0 release.
=> docs: activate Talos 1.10 docs

internal/integration/api/extensions_qemu.go
Add extensions test for Youki container runtime.
=> chore(ci): add extensions test for Youki runtime

website/content/v1.10/talos-guides/configuration/image-cache.md, website/content/v1.9/talos-guides/configuration/image-cache.md
Additional command for registry troubleshooting.
#10841
=> docs: add registryd debug command

.github/workflows/ci.yaml, .github/workflows/integration-provision-0-cron.yaml, .kres.yaml, cmd/talosctl/cmd/mgmt/cluster/create/create.go, hack/test/e2e-qemu.sh, hack/test/provision-tests.sh, internal/integration/provision/upgrade.go, pkg/provision/providers/qemu/node.go
Fix the provision-0 cron tests.
Support zstd disk images for `talosctl cluster create`.
=> fix(ci): provision tests

pkg/provision/providers/vm/network.go, pkg/provision/providers/vm/network_darwin.go, pkg/provision/providers/vm/network_test.go
part of #10537
this will be used for the dhcpd server assignment later
next step will be making the loadbalancer work
=> chore: calculate vmnet interface name preemptively

.github/workflows/ci.yaml, .github/workflows/integration-provision-0-cron.yaml, .kres.yaml
=> fix(ci): provision cron jobs

.github/workflows/ci.yaml, .github/workflows/integration-misc-1-cron.yaml, .kres.yaml, hack/test/e2e-qemu.sh, internal/app/apid/main.go, internal/app/trustd/main.go, pkg/machinery/client/connection.go
=> fix: ignore http proxy on grpc socket dial

pkg/imager/iso/grub.go, pkg/imager/iso/hybrid.go, pkg/imager/iso/uefi.go
Fix generating ISO greater than 4 Gig.
Fixes: #10887
=> fix: generating iso greater than 4 gig

internal/app/machined/pkg/controllers/network/platform_config.go
The issue was that the controller might have got into a loop trying to load the cached network config crashing the runtime.
Also, due to the bug, it might have never persisted the platform config to STATE (depends on platform implementation).
=> fix: multiple logic issues in platform network config controller

go.mod, go.sum
=> fix: k8s 1.32->1.33 upgrade check

internal/app/machined/pkg/controllers/network/cmdline_test.go, internal/app/machined/pkg/system/runner/process/process.go, internal/app/machined/pkg/system/runner/process/process_test.go, internal/pkg/dns/dns_test.go
=> test: fix some flaky tests

website/content/v1.10/kubernetes-guides/network/deploying-cilium.md, website/content/v1.11/kubernetes-guides/network/deploying-cilium.md
Fix a typo in the docs
The command ends there, so there shouldn't be a `\` at the end of its last line
Didn't do any of the checklist points, since it's a minor change and the docs are hopefully generated in a pipeline.
=> Fix typo in docs

cmd/talosctl/cmd/mgmt/cluster/create/command.go, cmd/talosctl/cmd/mgmt/cluster/create/command_test.go, website/content/v1.11/reference/cli.md
Please see the individual commits for more details.
=> Tidy up cluster create flags

internal/pkg/selinux/selinux.go
Fix SELinux detection.
Fixes: #10965
=> fix: selinux detection

website/content/v1.10/talos-guides/configuration/disk-encryption.md, website/content/v1.11/talos-guides/configuration/disk-encryption.md
Fix formatting for consistency reasons
=> Fix formatting in docs

pkg/cluster/check/nodes.go
For old Talos without `VolumeStatus` resource skip the check.
=> fix: make disk size check work on old Talos

Makefile, pkg/imager/iso/uefi.go
Fix `metal-iso` reproducibility.
Fixes: #11074
=> fix: metal-iso reproducibility

cmd/talosctl/cmd/mgmt/cluster/create/command.go
* error if an usupported flag is passed
* hide unsupported flags from --help
part of #10537
=> chore: add a check for unsupported darwin flags

Makefile
Fix iso reproducibility file permissions.
=> fix(ci): iso reproducibility file permissions

website/content/v1.10/introduction/troubleshooting.md, website/content/v1.11/introduction/troubleshooting.md
=> Fix CIDR name

website/content/v1.11/talos-guides/install/local-platforms/qemu.md
add documentation about the usage of the qemu provider on macos
part of #10537
=> docs: macos qemu provider

hack/release.toml, pkg/flannel/template.go, pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.27.0
=> feat: update Flannel to 0.27.0

Makefile, hack/release.toml, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs, pkg/machinery/gendata/data/tools
=> chore: update Go to 1.24.4

Makefile, go.mod, go.sum, hack/release.toml, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
Update via https://github.com/siderolabs/pkgs/pull/1269
=> feat: update Linux to 6.12.35, containerd to 2.1.3

website/content/v1.10/talos-guides/install/single-board-computers/rpi_generic.md, website/content/v1.11/talos-guides/install/single-board-computers/rpi_generic.md
Added documentation of the `vc4`  system extension and the configuration of `config.txt` related to GPU CMA issues of the Raspberry Pi target.
Lack of current documentation about the GPU CMA configuration and potential issues with it.
=> docs: add vc4 memory documentation

hack/cloud-image-uploader/aws.go
It turns out some S3 regions can't upload a Talos image in 15 minutes, so rework the code once again to make it more resilient to failures:
* if one region/arch fails, ignore it and go forward
* bump S3 upload timeout to 30 minutes
* previously, a failure to upload failed the errgroup which in turn cancels all other uploads, and the whole upload fails.
=> chore: improve cloud image uploader resilience

website/content/v1.11/advanced/selinux.md
Make sure there is the proper way documented to make sure SELinux is disabled correctly.
Fixes #11192 
=> docs: document disabling SELinux

.github/workflows/ci.yaml, .github/workflows/integration-image-factory-cron.yaml, .kres.yaml
Hopefully this makes CI less flaky.
=> chore: bump Talos version in the Image Factory CI pipeline

internal/app/machined/pkg/controllers/block/user_volume_config.go, internal/integration/api/volumes.go, pkg/machinery/config/config/volume.go, pkg/machinery/config/schemas/config.schema.json, pkg/machinery/config/types/block/block_doc.go, pkg/machinery/config/types/block/deep_copy.generated.go, pkg/machinery/config/types/block/testdata/uservolumeconfig_prjquota.yaml, pkg/machinery/config/types/block/user_volume_config.go, pkg/machinery/config/types/block/user_volume_config_test.go, website/content/v1.11/reference/configuration/block/uservolumeconfig.md, website/content/v1.11/schemas/config.schema.json
Just exposting existing value via the config.
Fixes #11090
=> feat: support project quota support for user volumes

.github/workflows/ci.yaml, .kres.yaml
Run more stuff more in parallel, allow restarting smaller pipelines.
=> test: split tests and lint from the default pipeline

.github/workflows/ci.yaml, .github/workflows/integration-aws-cron.yaml, .github/workflows/integration-aws-nvidia-nonfree-cron.yaml, .github/workflows/integration-aws-nvidia-oss-cron.yaml, .github/workflows/integration-gcp-cron.yaml, .kres.yaml, Makefile
Move AWS/GCP images to respective pipelines.
=> chore: build less images by default

.github/renovate.json, .github/workflows/ci.yaml, .github/workflows/integration-aws-nvidia-nonfree-lts-cron.yaml, .github/workflows/integration-aws-nvidia-nonfree-production-cron.yaml, .github/workflows/integration-aws-nvidia-oss-lts-cron.yaml, .github/workflows/integration-aws-nvidia-oss-production-cron.yaml, .github/workflows/slack-notify.yaml, .kres.yaml, hack/test/e2e-aws-prepare.sh, internal/integration/api/constants.go, internal/integration/api/extensions_nvidia.go, internal/integration/api/testdata/nvidia-device-plugin.yaml, website/content/v1.11/talos-guides/configuration/nvidia-gpu.md
Add more NVIDIA tests covering all supported OSS and Proprietary LTS and Production driver versions.
Fixes: #11398
=> chore(ci): add more nvidia test matrix

hack/release.toml, pkg/machinery/constants/constants.go, website/content/v1.11/reference/configuration/v1alpha1/config.md
See https://github.com/etcd-io/etcd/releases/tag/v3.5.22
=> feat: update etcd to v3.5.22

Makefile, internal/integration/api/constants.go
Fix datasource versioning for container images.
=> chore(renovate): fix datasource versioning

hack/cloud-image-uploader/aws.go
This is to make them more easily identifiable for clean up if required.
Ensure AWS EBS snapshots created during CI are tagged to make then easily identifiable.
Without a Name tag we cannot identify redundant snapshots easily.
=> chore: tag aws snapshots created via ci with the image name

Makefile, hack/modules-amd64.txt, pkg/machinery/gendata/data/pkgs
See https://github.com/siderolabs/pkgs/pull/1288
=> feat: add F71808E watchdog driver

.github/workflows/slack-notify.yaml
run rekres to use correct slack channel for slack-notify
Signed-off-by: Oguz Kilcan <oguz.kilcan@siderolabs.com>
=> chore: run rekres

internal/pkg/dashboard/components/footer.go, internal/pkg/dashboard/dashboard.go
Inspired by htop, helps for looking at process tables and logs.
=> feat: add a pause function to dashboard

internal/app/machined/pkg/controllers/network/operator/dhcp4.go
Some DHCP servers are configured to require non-zero value for the field.
DHCPv6 seems to have no equivalent field so I left it untouched.
fixes https://github.com/siderolabs/talos/issues/11401
related to https://github.com/siderolabs/talos/discussions/11394#discussioncomment-13832608
=> fix: set secs field in DHCPv4 packets

pkg/provision/providers/qemu/node_darwin.go
update darwin specific findAPIBindAddrs func
=> fix: darwin build

Makefile
The vulndb got (finally) fixed.
=> chore: re-enable vulncheck

internal/app/machined/pkg/controllers/cluster/node_identity.go, internal/app/machined/pkg/controllers/kubespan/identity.go, internal/app/machined/pkg/controllers/secrets/encryption_salt.go, internal/app/machined/pkg/controllers/utils.go, internal/pkg/xfs/fsopen/fsopen_linux.go, internal/pkg/xfs/fsopen/options_linux.go, internal/pkg/xfs/fsopen_test.go, internal/pkg/xfs/opentree/opentree_linux.go, internal/pkg/xfs/opentree_test.go, internal/pkg/xfs/root.go, internal/pkg/xfs/root_test.go, internal/pkg/xfs/root_unix.go
Prepares for mount refactoring (part of https://github.com/siderolabs/talos/issues/11608)
=> chore: use new filesystem api on STATE partition

website/content/v1.10/talos-guides/install/single-board-computers/unofficial.md, website/content/v1.11/talos-guides/install/single-board-computers/unofficial.md, website/content/v1.12/talos-guides/install/single-board-computers/unofficial.md
fixed the miscommunication in the sbc unofficial port docs.
there was a miscommunication in the unofficial port docs.
=> docs: add sbc unofficial ports docs

website/content/v1.12/talos-guides/install/local-platforms/docker.md, website/content/v1.12/talos-guides/install/local-platforms/qemu.md
update the user facing docs the utilize the user facing commands
closes [#11687](https://github.com/siderolabs/talos/issues/11687)
=> docs: update qemu and docker docs

website/content/v1.10/talos-guides/network/kubespan.md, website/content/v1.11/talos-guides/network/kubespan.md, website/content/v1.12/talos-guides/network/kubespan.md
=> docs: add docs on cilium's compatibility with kubespan

Makefile, hack/release.toml, pkg/machinery/constants/constants.go, pkg/machinery/gendata/data/pkgs
See https://github.com/opencontainers/runc/releases/tag/v1.3.1
=> feat: update runc to 1.3.1

website/content/v1.10/talos-guides/network/vip.md, website/content/v1.11/talos-guides/network/vip.md, website/content/v1.12/talos-guides/network/vip.md
document what happens when the controlplane node holding the vip shuts down
sorts #11581
=> docs: document talos vip failover behaviour

Dockerfile, internal/app/machined/pkg/controllers/files/cri_config_parts.go, internal/app/machined/pkg/controllers/files/cri_registry_config.go, internal/app/machined/pkg/controllers/files/etcfile.go, internal/app/machined/pkg/controllers/files/etcfile_test.go, internal/app/machined/pkg/controllers/files/iqn.go, internal/app/machined/pkg/controllers/files/nqn.go, internal/app/machined/pkg/controllers/network/etcfile.go, internal/app/machined/pkg/controllers/network/etcfile_test.go, internal/app/machined/pkg/controllers/network/watch/rtnetlink.go, internal/app/machined/pkg/runtime/kernel.go, internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go, internal/integration/api/selinux.go, internal/integration/k8s/tink.go, internal/pkg/containers/cri/containerd/containerd.go, internal/pkg/mount/v3/mount.go, internal/pkg/selinux/selinux.go, internal/pkg/xfs/fsopen_test.go, internal/pkg/xfs/opentree_test.go, internal/pkg/xfs/osroot.go, internal/pkg/xfs/osroot_test.go, internal/pkg/xfs/root.go, internal/pkg/xfs/root_test.go, internal/pkg/xfs/root_unix.go, pkg/machinery/constants/constants.go
=> feat: create detached tmpfs

internal/integration/api/apply-config.go, internal/integration/api/update-hostname.go
One issue is with update hostname tests which runs against Talos v1.11 machine config which contains legacy fields which need to be removed.
Another is an attempt to refactor apply-try tests.
=> test: fix several issues with tests

website/content/v1.12/talos-guides/install/bare-metal-platforms/secureboot.md
Update secureboot docs to be more verbose and use flowcharts to make it easier to understand.
=> docs: update secureboot docs

internal/pkg/efivarfs/efivarfs.go
Use new `mount/v3` package in efivarfs.
=> chore: use new mount/v3 package in efivarfs

internal/pkg/efivarfs/efivarfs.go
This reverts commit c6279e04c45504af243c0aef9f255317426b4ca0.
=> fix: revert "chore: use new mount/v3 package in efivarfs"

.github/workflows/ci.yaml, .github/workflows/integration-airgapped-cron.yaml, .github/workflows/slack-notify-ci-failure.yaml, .github/workflows/slack-notify.yaml, .kres.yaml, cmd/talosctl/cmd/mgmt/debug/air-gapped.go, hack/test/e2e-qemu.sh, hack/test/patches/proxied-registry.yaml, internal/app/machined/pkg/controllers/cluster/discovery_service.go, internal/app/machined/pkg/controllers/runtime/events_sink.go, internal/app/machined/pkg/controllers/siderolink/manager.go, internal/pkg/encryption/keys/kms.go, pkg/grpc/middleware/auth/basic/basic.go, pkg/httpdefaults/tls.go, pkg/machinery/client/dialer/proxy.go
Most of the work is to add proper test environment for more cases.
Include a test for pulling an image
=> fix: support secure HTTP proxy with gRPC dial

website/content/v1.10/talos-guides/network/kubespan.md, website/content/v1.11/kubernetes-guides/upgrading-kubernetes.md, website/content/v1.11/talos-guides/network/kubespan.md, website/content/v1.12/kubernetes-guides/upgrading-kubernetes.md, website/content/v1.12/talos-guides/network/kubespan.md
add info on kubespan's relationship with discovery service, when unavailable
=> docs: updated the kubespan docs

.github/workflows/ci.yaml, .github/workflows/integration-aws-nvidia-nonfree-lts-cron.yaml, .github/workflows/integration-aws-nvidia-nonfree-production-cron.yaml, .github/workflows/integration-aws-nvidia-oss-lts-cron.yaml, .github/workflows/integration-aws-nvidia-oss-production-cron.yaml, .github/workflows/stale.yml, .kres.yaml
Run only NVIDIA related tests for NVIDIA workflows.
=> chore(ci): run only nvidia tests for NVIDIA workflows
