siderolabs/talos

- internal/pkg/rng/tpm.go
- internal/pkg/secureboot/tpm2/pcr.go
For rng seed and pcr extend, let's ignore if the device is not TPM2.0 based. Seal/Unseal operations would still error out since it's explicitly user enabled feature.
> fix: skip over tpm2 1.2 devices

- internal/app/poweroff/main.go
Use the `machined` socket for `shutdown` and `poweroff` aliases. This ensures that worker nodes does not have to wait on apid to start.
> chore: machined socket for `shutdown`, `poweroff`

- website/content/v1.4/learn-more/process-capabilities.md
- website/content/v1.5/learn-more/process-capabilities.md
It's CAP_SYS_BOOT, not CAP_BOOT.
> docs: fix wrong capability name

- Makefile
- hack/release.toml
- hack/test/e2e.sh
- pkg/machinery/constants/constants.go
- website/content/v1.5/reference/cli.md
- website/content/v1.5/reference/configuration.md
See https://github.com/kubernetes/kubernetes/releases/tag/v1.28.0-beta.0
Go modules are not tagged yet, so skipped updating them.
> feat: update default Kubernetes version to 1.28.0-beta.0

- cmd/ukify/main.go
- pkg/machinery/kernel/kernel.go
UKI is meant to be for UEFI Secure Boot, so it's expected to enforce kernel lockdown. We might reconsider in the future to use a kernel patch instead: https://github.com/SUSE/kernel/commit/b1a0314b0827ea781c13a27abcc3c3b96fc0e946
> feat: enforce kernel lockdown for UKI

- website/content/v1.5/advanced/migrating-from-kubeadm.md
Warning about EncryptionConfig when migrating from an existing kubeadm cluster in documentation.
If you don't know about this config, you risk having a split configuration between kubeadm controlplane and talos controlplane, it **will** lead to unusable Secrets and to a dysfunctional cluster.
https://github.com/siderolabs/talos/issues/7475
> doc: warning about secretboxEncryptionSecret in kubeadm migration guide

- hack/cloud-image-uploader/aws.go
- hack/cloud-image-uploader/main.go
Fixes #7513
AWS image uploads recently consistently fail in some regions, which blocks the release process. Allow to skip some AMIs if they fail to upload.
Disable Azure until #7512 is resolved.
> chore: workaround AWS AMI failures, disable Azure uploader

- internal/app/dashboard/main.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/dashboard.go
- internal/pkg/console/console.go
- internal/pkg/dashboard/dashboard.go
- pkg/machinery/constants/constants.go
- Make dashboard SIGTERM-aware
- Handle panics on dashboard and terminate it gracefully, so it resets the terminal properly
- Switch to TTY2 when it starts and back to TTY1 when it stops.
Closes siderolabs/talos#7516.
> fix: terminate dashboard gracefully on & switch back to tty1

- internal/pkg/partition/format.go
As part of bootloader refactoring `go-blockdevice` was used for wiping partitions in #7329, but used standard wipe which could be fast/slow depending on the blockdevice support. Switch to using fast-wipe for partitions. This should not affect `wipe` option in machineconfig.
Fixes: #7531
> fix: use fast wipe for upgrade

- Makefile
- hack/modules-amd64.txt
- hack/modules-arm64.txt
- pkg/machinery/gendata/data/pkgs
This PR pulls in the latest pkgs commit to enable dm_multipath as a module.
> chore: add dm_multipath module

- go.mod
- go.sum
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/vmware_amd64.go
This module was imported just for a single Go struct (for XML unmarshalling), and it could be easily internalised.
The module causes significant allocation on startup:
```
init github.com/vmware/govmomi/vim25/types @23 ms, 1.4 ms clock, 1269864 bytes, 196 allocs
```
> refactor: drop dependency on vmware/govmomi

- cmd/talosctl/cmd/talos/pcap.go
- go.mod
- go.sum
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/pkg/tui/components/form.go
This new fork seems to be more active. The change itself doesn't fix any memory allocation, but I submitted a PR for gopacket/gopacket:
https://github.com/gopacket/gopacket/pull/24
Also fix crazy alloc in `tui/components` (this is only relevant for `talosctl`).
> refactor: replace google/gopacket with gopacket/gopacket

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/network/operator/vip/hcloud.go
- pkg/machinery/resources/network/operator_spec.go
There are no functional changes, but SDK got updated to handle int -> int64 changes. v1 version is only supported to Sep 2023.
See https://github.com/hetznercloud/hcloud-go#support
> chore: update hcloud API SDK to v2

- .drone.jsonnet
The step was disabled for the latest alpha release to workaround AWS issues which have been resolved.
> chore: re-enable cloud images step

- internal/app/machined/pkg/controllers/k8s/kubelet_service.go
- internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
- internal/app/machined/pkg/system/system.go
- pkg/machinery/resources/k8s/deep_copy.generated.go
- pkg/machinery/resources/k8s/kubelet_config.go
- pkg/machinery/resources/k8s/kubelet_spec.go
After we closed `kubelet`, remove `/var/lib/kubelet/cpu_manager_state` if there are any changes in `cpuManagerPolicy`. We do not add any other safeguards, so it's user responsibility to cordon/drain the node in advance.
Also minor fixes in other files.
Closes #7504
> chore: remove `cpu_manager_state` on `cpuManagerPolicy` change.

- pkg/machinery/extensions/extensions.go
NVIDIA OpenGL/Vulkan files are super hard-coded.
Ref: https://github.com/siderolabs/extensions/pull/191
Fixes: https://github.com/siderolabs/extensions/issues/171
> feat: update extension spec allowlist for opengl

- hack/release.toml
- website/content/v1.5/kubernetes-guides/network/deploying-cilium.md
Update cilium instructions to skip mounting `bpffs`.
Also fix the TPM example in release notes.
> docs: update cilium instructions

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Fixes #7558
I see no reason to keep old behavior (removing all partitions on the disk), as it's only compatible with Talos itself.
> fix: fast-wipe the system disk on talosctl reset

- internal/app/machined/pkg/runtime/v1alpha1/platform/aws/aws.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/aws/testdata/expected.yaml
This PR updates the ProviderID format for aws resources. There seems to be a bug when using Talos CCM (which consumes this value from Talos) because the format is `aws://x/y` (two slashes) vs. the expected `aws:///x/y` (three slashes) that is set with the AWS CCM code [here](https://github.com/kubernetes/cloud-provider-aws/blob/d0551093673e8c355db17249b8f069767c014748/pkg/providers/v1/instances.go#L47-L53).
Setting only two slashes causes important software in the workload cluster to fail, specifically cluster-autoscaler. The regex they use for pulling providerID is [here](https://github.com/kubernetes/autoscaler/blob/702e9685d6c1d002f4a448f2d88007141dfa6d56/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L195). …
> fix: update providerid prefix for aws

- internal/pkg/ntp/interfaces.go
- internal/pkg/ntp/ntp.go
- internal/pkg/ntp/ntp_test.go
- internal/pkg/timex/timex.go
Fixes #7080
The real bug was off-by-one in `log2i` implementation, other changes are cleanups as `x/sys/unix` package now contains all the constants we need.
> fix: calculate log2i properly

- cmd/talosctl/pkg/talos/helpers/checks.go
- go.mod
- hack/cloud-image-uploader/azure.go
- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
- internal/pkg/extensions/validate.go
- pkg/cluster/kubernetes/detect.go
- pkg/cluster/sonobuoy/sonobuoy.go
- pkg/machinery/compatibility/kubernetes_version.go
- pkg/machinery/compatibility/talos12/talos12.go
- pkg/machinery/compatibility/talos13/talos13.go
- pkg/machinery/compatibility/talos14/talos14.go
- pkg/machinery/compatibility/talos15/talos15.go
- pkg/machinery/compatibility/talos_version.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Currently, we use `github.com/coreos/go-semver/semver` and `github.com/hashicorp/go-version` for version parsing. As we use `github.com/blang/semver/v4` in our other projects, and it has more features, it makes sense to use it across the projects. It also doesn't allocate like crazy in `KubernetesVersion.SupportedWith`.
> chore: unify semver under `github.com/blang/semver/v4`

- internal/pkg/encryption/encryption.go
- pkg/machinery/config/config/machine.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Fixes: https://github.com/siderolabs/talos/issues/7515
Rename `Kind` to `Provider` in the `v1alpha1_provider`.
> fix: make encryption config provider default to `luks2` if not set

- .drone.jsonnet
- Dockerfile
- Makefile
These assets are required to build a UKI, so publish them as part of the release.
> chore: publish systemd-boot and systemd-stub assets

- Dockerfile
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/dashboard.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/pkg/dashboard/dashboard.go
- internal/pkg/mount/switchroot/switchroot.go
- pkg/machinery/constants/constants.go
There are two changes here:
* build `machined` binary with `tcell_minimal` tag (which disables loading some parts of the terminfo database), which also affects `apid`, `trustd` and `dashboard` processes, as they run from the same executable; in `dashboard` explicitly import `linux` terminal we're using when the `dashboard` runs on the machine
* pass `TCELL_MINIMIZE=1` environment variable to each Talos process which removes 0.5MiB of runewdith allocation for a lookup table
See #7578
> chore: optimize memory usage of `tcell` library on init

- cmd/talosctl/cmd/talos/copy.go
- cmd/talosctl/cmd/talos/etcd.go
- cmd/talosctl/cmd/talos/kubeconfig.go
- cmd/talosctl/cmd/talos/pcap.go
- cmd/talosctl/cmd/talos/read.go
- cmd/talosctl/pkg/talos/action/tracker.go
- internal/integration/api/cgroups.go
- internal/integration/api/dmesg.go
- internal/integration/api/etcd-recover.go
- internal/integration/api/logs.go
- internal/integration/base/api.go
- pkg/cluster/crashdump.go
- pkg/cluster/support.go
- pkg/machinery/client/client.go
Simplify code by passing error directly into the pipe closer.
> chore: remove <-errCh where possible in grpc methods

- .drone.jsonnet
The `images` step modifies files in `_out/` breaking the concurrent `save-artifacts` step.
> chore: fix dependencies in the release pipeline

- internal/app/machined/pkg/controllers/network/route_spec.go
- internal/app/machined/pkg/controllers/network/route_spec_test.go
Fixes #7592
The problem was a mismatch between a "primary key" (ID) of the `RouteSpec` and the way routes are looked up in the kernel - with two idential routes but different priority Talos would end up in an infinite loop fighting to remove and re-add back same route, as priority never matches.
> fix: match routes on the priority properly

- hack/docgen/main.go
- internal/pkg/tui/installer/state.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_examples.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.5/reference/configuration.md
Short version is: move from global variables/`init()` function into explicit functions.
`docgen` was updated to skip creating any top-level global variables, now `Doc` information is generated on the fly when it is accessed. Talos itself doesn't marshal the configuration often, so in general it should never be accessed for Talos (but will be accessed e.g. for `talosctl`).
Machine config examples were changed manually from variables to functions returning a value and moved to a separate file.
There are no changes to the output of `talosctl gen config`.
There is a small change to the generated documentation, which I believe is a correct one, as previously due to value reuse it was clobbered with other data.
See #7578
> refactor: docgen and config examples

- website/content/v1.5/kubernetes-guides/network/deploying-cilium.md
Partial rollback of 76fa45a.
The cilium helm chart requires an fix to handle the hostPath at /sys/fs/bpf when bpf.autoMount.enabled=false. The earlier commit disabled bpf automount, removing the init container's mount. Helm missed adding the hostPath, and neither /sys nor /sys/fs got added. This made cilium wrongly mount /sys/fs/bpf.
Fixes error message at: https://github.com/siderolabs/talos/pull/7565#issuecomment-1671063014
Continuation of PR https://github.com/siderolabs/talos/pull/7593 which i was unuable to reopen as I forced pushed in between
> docs: retain cilium autoMount pending upstream hostPath fix

- pkg/machinery/compatibility/kubernetes_version.go
- pkg/machinery/compatibility/kubernetes_version_test.go
- pkg/machinery/compatibility/talos16/talos16.go
- pkg/machinery/compatibility/talos_version.go
- pkg/machinery/compatibility/talos_version_test.go
- pkg/machinery/config/contract.go
- pkg/machinery/config/contract_test.go
This will be backported to 1.5, so that Talos 1.5 machinery will still provide compatibility for (future) Talos 1.6.
> chore: add version compatibility for Talos 1.6

- website/content/v1.4/talos-guides/configuration/nvidia-gpu-proprietary.md
- website/content/v1.5/talos-guides/configuration/nvidia-gpu-proprietary.md
- website/content/v1.5/talos-guides/configuration/nvidia-gpu.md
Update NVIDIA docs to point to use pre-built extensions.
Ref: https://github.com/siderolabs/extensions/pull/201
Fixes: #7611
> docs: update nvidia docs

- website/config.toml
- website/content/v1.4/_index.md
- website/content/v1.5/_index.md
- website/content/v1.5/introduction/support-matrix.md
- website/content/v1.5/introduction/what-is-new/index.md
This matches upcoming Talos 1.5.0 release.
> docs: make Talos 1.5 documentation the default one

- pkg/imager/ova/ova.go
With the refactoring to 1.5, the confusion between bytes and megabytes introduced this bug.
Fixes #7627
> fix: put correct capacity to the ovf

- internal/app/machined/pkg/adapters/k8s/manifest.go
- internal/app/machined/pkg/adapters/k8s/manifest_test.go
- internal/app/machined/pkg/adapters/k8s/testdata/list.yaml
Fixes #7636
This support a `List`-type manifests by unwrapping them into individual objects.
> fix: support 'List' type manifests

- cmd/installer/pkg/install/install.go
As `rpi_4` was removed in Talos 1.5, automatically migrate to `rpi_generic`.
Fixes #7632
> fix: automatically change `rpi_4` board on upgrade

- internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
- internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
The `--container-runtime-endpoint` flag was moved to the kubelet config only in Kubernetes 1.27.
Kubernetes 1.27 and 1.28 still support the flag (even though 1.28 shows the warning that the flag is deprecated).
This is direct commit to `release-1.5`, as `main` is going to use Kubernetes 1.27-1.29, so it should be using a config file.
Fixes #7648
> fix: restore compatibility with Kubernetes 1.26

- internal/app/machined/pkg/controllers/runtime/cri_image_gc.go
- internal/app/machined/pkg/controllers/runtime/cri_image_gc_test.go
- internal/app/machined/pkg/controllers/runtime/export_test.go
This is a follow-up fix for #7640
I noticed that image cleanup controller cleans up the images if specified with both tag and digest.
The problem was incorrectly building image references in the expected set of images, so they were incorrectly marked as unused.
Refactor the code to make the core part testable.
> fix: properly GC images supplied with both tag and digest

- internal/app/machined/pkg/controllers/k8s/internal/nodename/nodename.go
- internal/app/machined/pkg/controllers/k8s/internal/nodename/nodename_test.go
- internal/app/machined/pkg/controllers/k8s/nodename.go
- internal/app/machined/pkg/controllers/k8s/nodename_test.go
Fixes #7615
This extends the previous handling when Talos did `ToLower()` on the hostname to do the full filtering as expected.
> feat: filter the hostname to produce nodename

- internal/pkg/dashboard/components/tables.go
Processes and their info are not guaranteed to be present on the api-based data gathered by the dashboard. Therefore, we switch to using nil-safe access to the CPU time when rendering the process table.
Closes siderolabs/talos#7645.
> fix: prevent dashboard crashes when process info is not available

- Dockerfile
Due to a mistake, the amd64 modules were copied :facepalm:
> fix: copy proper modules to arm64 squashfs

- internal/integration/api/extensions.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/vm/network.go
This is required for https://github.com/siderolabs/sidero/pull/1070, as we need to allow DHCP traffic from Sidero controller running in a VM through the bridge to other VMs.
> chore: allow bridge traffic with DHCP broadcast traffic

- internal/app/machined/pkg/controllers/network/node_address.go
- internal/app/machined/pkg/controllers/network/node_address_test.go
Example: host has address `10.0.0.1/8`, while Kubernetes pod CIDR is `10.244.0.0/16`. These two subnets overlap, but the address `10.0.0.1` isn't contained in the `10.244.0.0/16` subnet.
This change fixes the check to make sure address is not contained vs. the address subnet overlaps with the filter.
NB: this is still a bad idea to have host network subnet to overlap with Kubernetes pod/service CIDRs.
Also refactor the unit-tests to use new (better ways) to do assertions.
Fixes #7657
> fix: properly calculate overlap of node address with subnet filters

- pkg/imager/out.go
- pkg/imager/ova/ova.go
It looks like while our code accepted any random name for the contents of `.ova`, it should be named `disk.*`.
Change the code accordingly.
Fixes #7663
> fix: ova contents to be named `disk.*`

- Dockerfile
- hack/release.toml
Drop firmware from initramfs. Extra firmware can be added as system extensions enabled through imager service.
Before:
```bash
❯ du -sh _out/initramfs-amd64.xz
58M	_out/initramfs-amd64.xz
```
After:
```bash
❯ du -sh _out/initramfs-amd64.xz
56M	_out/initramfs-amd64.xz
```
> chore: drop firmware from initramfs

- hack/test/tfvars/aws.jq
This PR updates the e2e-aws flow to use worker groups and an updated control plane variable setup.
> test: update e2e-aws to use worker groups

- internal/pkg/ntp/internal/spike/spike.go
- internal/pkg/ntp/internal/spike/spike_test.go
- internal/pkg/ntp/ntp.go
See https://github.com/siderolabs/talos/issues/7080#issuecomment-1696105986
The NTP spike detector code was refactored out of the main NTP code so that it can be unit-tested.
I dropped one check which I think is causing false-positives in the spike detector (when NTP offset is higher than the RTT of the best packet received so far).
The overall flow resembles the one in systemd-timesync, the current implementation has this check:
https://github.com/systemd/systemd/blob/6639ac474eb7a5325a72a3d7370492792dd00bc0/src/timesync/timesyncd-manager.c#L357-L360
This check was introduced in the initial release, after some refactoring:
https://github.com/systemd/systemd/commit/3dbc7620030b7eacfe19d55f1bcd8237dd3230ef#diff-4aa9995f07bb31b9884d40a7634f5f6d30245dfd26ac27b89cd5fd3bd4eef56aR429-R431
There …
> refactor: update NTP spike detector

- Makefile
- cmd/installer/cmd/imager/root.go
- pkg/imager/imager.go
- pkg/imager/out.go
- pkg/imager/post.go
- pkg/imager/profile/input.go
- pkg/imager/profile/output.go
- pkg/imager/profile/outputkind_enumer.go
- pkg/imager/profile/profile.go
- website/content/v1.6/talos-guides/install/bare-metal-platforms/secureboot.md
* report the final output path of the asset
* allow 'cmdline' output (just to get the kernel cmdline, e.g. for PXE booting)
* rename `installer` asset to be without `platform` (as it doesn't depend on the platform)
> feat: improve imager APIs

- cmd/installer/pkg/install/install.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/options/options.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
- pkg/imager/out.go
This is not a problem in general, but when running multiple image generation procedures using the same mount point is a problem.
This is a no-op if `MountPrefix` is not set (when installing/upgrading vs. creating an image).
> fix: use a mount prefix when installing a bootloader

- internal/app/machined/pkg/controllers/k8s/kubeprism.go
- pkg/machinery/constants/constants.go
The default timeouts are very aggressive, and we should use explicit timeouts so that healh checks don't run that often.
Fixes #7690
> fix: set proper timeouts for KubePrism loadbalancer

- cmd/talosctl/cmd/talos/config.go
- cmd/talosctl/cmd/talos/config_test.go
- internal/app/machined/pkg/adapters/cluster/identity_test.go
- internal/app/machined/pkg/controllers/runtime/maintenance_service_test.go
- internal/integration/cli/config.go
- pkg/machinery/config/generate/secrets/bundle.go
- pkg/machinery/constants/constants.go
Fixes #7698
Also fix `talosctl config info` for `talosconfig` without a client certificate (e.g. Omni-generated one).
> fix: set correct (1 year) talosconfig expiration

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Fixes #7696
This allows to set env variables from `talos.environment=` command line arg.
> feat: set environment variables early in the boot

- hack/release.sh
The `talosctl images` command was renamed.
> chore: fix default image list in the release notes

- go.mod
- go.sum
See https://github.com/siderolabs/go-kubernetes/pull/7
Fixes #7697
> fix: update kubernetes library for 1.28 upgrade pre-checks

- internal/app/machined/pkg/controllers/network/address_config.go
- internal/app/machined/pkg/controllers/network/cmdline.go
- internal/app/machined/pkg/controllers/network/link_config.go
- internal/app/machined/pkg/controllers/network/operator_config.go
- internal/app/machined/pkg/controllers/network/operator_vip_config.go
- internal/app/machined/pkg/controllers/network/route_config.go
- pkg/machinery/nethelpers/vlan.go
- pkg/machinery/nethelpers/vlan_test.go
Fixes #7679
This should be no-op if the link name is <= 10 chars, but with predictable interface names based on MAC addresses, they have to be shortened to make some space for VLAN ID.
> fix: shorten VLAN link names to fit into the limit of 15 characters

- cmd/talosctl/cmd/talos/config.go
- internal/integration/cli/config.go
- website/content/v1.6/reference/cli.md
Add output flag for `talosctl config info`.
This allows to programatically gather endpoints for CI tests.
Eg:
```bash
_out/talosctl-linux-amd64 config info --output json | jq '.Contexts[].Endpoints[0]'
```
> chore: add output flag for talosctl config info

- hack/test/e2e-aws.sh
Drop all hacky bash, depend on the `cluster_health` from TF code.
> chore: e2e-aws cleanup

- pkg/imager/out.go
When imager generates `installer` image, it should generate a layer without `/` in front, e.g. `/usr/install` -> `usr/install`.
It works either way, but this seems to be cleaner.
> fix: trim file path in the container image

- Makefile
- hack/test/e2e.sh
- website/content/v1.5/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.6/kubernetes-guides/network/deploying-cilium.md
Update cilium setup doc with latest info
`kubeProxyReplacement=strict` The value strict is now deprecated. From Cilium helm char values:
```
#kubeProxyReplacement: "false"
```
> Update Cilium Install Docs

- cmd/talosctl/cmd/talos/upgrade-k8s.go
- internal/integration/provision/upgrade.go
- pkg/cluster/kubernetes/kubelet.go
- pkg/cluster/kubernetes/patch.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/cluster/kubernetes/upgrade.go
- website/content/v1.6/reference/cli.md
Hello.
the command `talosctl gen config --with-docs=false --with-examples=false` can generate machineConfig without documentation inside. But during upgrade-k8s, talosctl adds them.
This feature allows us to remove any comments from the machineconfig after upgrading Kubernetes.
Thanks.
> feat: upgrade-k8s  without comments

- internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/testdata/expected.yaml
Otherwise route gets created with priority '0' and it seems to get into conflict with what Cilium tries to add.
> fix: set default route priority for hcloud platform

- website/content/v1.5/introduction/prodnotes.md
- website/content/v1.6/introduction/prodnotes.md
etcd and kubelet may benefit from controlling the subnets used for establishing their addresses.
Closes #7718
> docs: add notes about stable addressing

- internal/pkg/extensions/compress.go
- internal/pkg/extensions/discarder.go
- internal/pkg/extensions/kernel_modules.go
- pkg/imager/extensions/extensions.go
- pkg/machinery/constants/constants.go
Drop loop device/mounts completely, use userspace utilities to extract and lay over module trees in the tmpfs.
Discover kernel version automatically instead of hardcoding it to be current one (required for Image Service).
> refactor: reimplement the depmod extension rebuilder

- website/content/v1.6/learn-more/talos-network-connectivity.md
Not only worker nodes tend to be accessed from control plane nodes. Other control plane nodes can also be accessed from another control plane node.
> docs: add control plane nodes as users of apid also for control plane nodes

- internal/pkg/extensions/kernel_modules.go
- pkg/imager/extensions/extensions.go
When running on the machine, the extensionTreePath is not writeable, so create and clean up a temporary directory to host `modules.dep` extension.
> fix: generate of modules.dep when on the machine

- Makefile
- hack/modules-amd64.txt
- hack/modules-arm64.txt
- pkg/machinery/gendata/data/pkgs
Enable common h/w sensor modules.
Ref: https://github.com/siderolabs/pkgs/pull/815
> feat: enable common h/w sensors

- go.mod
- go.sum
- pkg/cluster/kubernetes/kubernetes_test.go
- pkg/machinery/constants/constants.go
Also add a unit-test to prevent issues like that (I upgraded to 1.29 but forgot to update go-kubernetes).
> fix: update kubernetes library to support 1.29 upgrades

- internal/app/machined/pkg/controllers/k8s/nodeip.go
- internal/app/machined/pkg/controllers/runtime/kmsg_log_test.go
This was a fix some time ago, but it was incorrect (missing `continue`), which was failing the unit-tests.
Also fix a data race in another unit-test (which is unit-test only, not affecting production).
> fix: the node IP for kubelet shouldn't change if nothing matches

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
When STATE is reset, we need to make sure we wipe the META keys containing encryption config as well.
Fixes #7819
> fix: clear the encryption config in META when STATE is reset

- internal/pkg/secureboot/tpm2/pcr.go
The conversion from TPM 2 hash algorithm to Go crypto algorithm will fail for uncommon algorithms like SM3256. This can be avoided by checking the constants directly, rather than converting them. It should also be fine to allow some non SHA-256 PCRs.
Fixes: #7810
> fix: use tpm2 hash algorithm constants and allow non-SHA-256 PCRs

- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
* support for local-hostname parameter
* support for hostnames passed via user-data (for Proxmox VE)
Official documentation shows examples how to use `local-hostname` with `NoCloud`:
* https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html
* https://www.talos.dev/v1.5/talos-guides/install/cloud-platforms/nocloud/#example-qemu
Proxmox VE writes `hostname` to `user-data` instead of `meta-data`.
Until `user-data` in not used for machine config it can still be used to parse the hostname from user's `cloud-config`
> feat: hostname configuration improvements on the NoCloud platform

- internal/integration/cli/gen.go
- internal/integration/cli/pki.go
There were weird hacks put into the tests, while each test already runs in a temporary directory as 'working directory', so no hacks are needed.
Moreover, using fixed `/tmp/...` paths leads to test failures, as CI runs docker & QEMU tests in parallel conflicting with each other.
> test: fix 'talosctl gen' tests

- internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/testdata/expected.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/testdata/metadatanetwork.json
- website/content/v1.4/talos-guides/install/cloud-platforms/oracle.md
- website/content/v1.5/talos-guides/install/cloud-platforms/oracle.md
- website/content/v1.6/talos-guides/install/cloud-platforms/oracle.md
Update oracle platform:
* Set static gateway IPv6 if it possible. Some cni do not work properly with ipv6, so we will fix it. (We already did the same in gcp/azure)
* Disable Talos dashboard. Oracle cloud does not have screen interface.
close #7528
> fix: oracle integration fixes

- internal/app/machined/pkg/runtime/v1alpha1/platform/internal/netutils/netutils.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/expected-v1.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v1.yaml
Use MAC address over network interface name.
This helps to use SR-IOV and paravirtualization network devices together.
Also I've added `WaitInterfaces` func. 
The kernel has not yet initialized the network devices, when the platform is attempting to identify the device by its MAC address.
> feat: nocloud platform prefer mac address

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/grpc/grpc-go/pull/6737
Note: this isn't a problem in `main`, as we're using 1.58 there, and it never had this bug.
> fix: update gRPC library to 1.57.2

- go.mod
- go.sum
PR https://github.com/vmware-tanzu/sonobuoy/pull/1933 got merged and 0.57.0 released, so update accordingly.
> chore: update sonobuouy library, drop the fork

- internal/app/machined/pkg/controllers/k8s/control_plane.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod_test.go
- internal/app/machined/pkg/controllers/k8s/control_plane_test.go
- internal/app/machined/pkg/controllers/k8s/templates.go
- pkg/flannel/gen.go
fixes #7874
This commit integrates the GOMEMLIMIT environment variable into the shipped k8s manifests when resources.limits.memory are defined. It is set to 95% of the memory limit to optimize the performance of the Go garbage collector, mitigating the risk of OOMKills in containerized environments.
see issue #7874 :
Addressing inefficiencies of Go's garbage collector in constrained memory environments, this PR introduces the GOMEMLIMIT environment variable to k8s manifests with defined resources.limits.memory. This optimizes garbage collection frequency, reducing OOMKill risk. The GOMEMLIMIT is set to 95% of the memory limit, ensuring efficient garbage collection while accommodating undetected memory usages.
> See `make help` for a description of the …
> feat: Add GOMEMLIMIT to k8s templates

- cmd/talosctl/cmd/mgmt/gen/secrets.go
- internal/integration/cli/gen.go
- website/content/v1.6/introduction/getting-started.md
- website/content/v1.6/introduction/prodnotes.md
- website/content/v1.6/reference/cli.md
This allows to "recover" secrets if the machine config was generated first without explicitly saving secrets bundle.
Fixes #7895
> feat: generate secrets bundle from the machine config

- internal/pkg/mount/mount.go
- internal/pkg/mount/options.go
- internal/pkg/mount/pseudo.go
Suppress `efivars` `ENODEV` errors: skip mount and proceed with boot sequence.
> fix: make Talos work on Rockpi 4c boards again

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Bring in the fix in https://github.com/siderolabs/go-api-signature/pull/31
> chore: bump go-api-signature dependency to v0.3.1

- cmd/talosctl/cmd/talos/reboot.go
- cmd/talosctl/cmd/talos/reset.go
- cmd/talosctl/cmd/talos/shutdown.go
- cmd/talosctl/cmd/talos/upgrade.go
- cmd/talosctl/pkg/talos/action/tracker.go
- internal/integration/cli/reboot.go
Before we started a reboot/shutdown/reset/upgrade action with the action tracker (`--wait`), we were setting a flag to prevent cobra from printing the returned error from the command.
This was to prevent the error from being printed twice, as the reporter of the action tracker already prints any errors occurred during the action execution.
But if the error happens too early - i.e. before we even started the status printer goroutine, then that error wouldn't be printed at all, as we have suppressed the errors.
This PR moves the suppression flag to be set after the status printer is started - so we still do not double-print the errors, but neither do we suppress any early-stage error from being printed.
Closes siderolabs/talos#7900.
> fix: fix error output of cli action tracker

- cmd/installer/pkg/install/install.go
- internal/app/machined/pkg/runtime/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/jetson_nano/jetson_nano.go
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
- internal/app/machined/pkg/runtime/v1alpha1/board/nanopi_r4s/nanopi_r4s.go
- internal/app/machined/pkg/runtime/v1alpha1/board/pine64/pine64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rock64/rock64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4/rockpi4.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4c/rockpi4c.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_generic/rpi_generic.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/options/options.go
- pkg/imager/filemap/filemap.go
- pkg/imager/out.go
- pkg/imager/profile/input.go
- pkg/imager/profile/profile.go
- pkg/machinery/constants/constants.go
See https://github.com/siderolabs/image-factory/issues/43
Two fixes:
* pass path to the dtb, uboot and rpi-firmware explicitly
* include dtb, uboot and rpi-firmware into arm64 installer image when generated via imager (regular arm64 installer was fine)
(The generation of SBC images was not broken for Talos itself, but only when used via Image Factory).
> fix: generate images for SBCs using imager

- internal/app/machined/pkg/controllers/network/network.go
- internal/app/machined/pkg/controllers/network/operator_config.go
- internal/app/machined/pkg/controllers/network/operator_config_test.go
- internal/app/machined/pkg/controllers/network/route_config.go
- internal/app/machined/pkg/controllers/network/route_config_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/hcloud/hcloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/oracle/oracle.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vmware/metadata.go
- pkg/machinery/resources/network/network.go
This leads to lots of unneccesary improts, as the chain from network controllers is pretty long.
> refactor: drop the dependency link platform -> network ctrl

- website/content/v1.5/learn-more/image-factory.md
- website/content/v1.5/talos-guides/install/boot-assets.md
- website/content/v1.6/learn-more/image-factory.md
- website/content/v1.6/talos-guides/install/boot-assets.md
Document Image Factory in general, and also provide specific examples for boot assets.
Secure Boot section is not covered, as we don't have Secure Boot support (yet) in the Image Factory.
Fixes #7920
> docs: add documentation for Image Factory

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/controllers/config/acquire.go
- internal/integration/api/apply-config.go
As Talos doesn't consume `.machine.install` if already installed, there is no point in validating it once already installed.
This fixes a problem users often run into: after a reboot/upgrade the system disk blockdevice name changes, due to the kernel upgrade, or just unpredictable behavior of device discovery. Talos fails to boot as it can't validate the machine config, while it's already installed, so actual blockdevice name doesn't matter.
> fix: don't validate machine.install if installed

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/pkg/pcap/pcap.go
First of all, this interface is way more performant than `pcap` interface. It is Linux-specific, but we don't care in Talos Linux :)
Second, this drop dependency of `machined` on `gopacket/layers` package, which has huge issues with memory allocations and startup time.
This cuts around 20MiB of process RSS for all Talos processes. (`talosctl` still requires this `gopacket/layers` library for decoding packets).
Fixes #7880
> refactor: update packet capture to use 'afpacket' interface

- internal/app/machined/pkg/runtime/v1alpha1/board/nanopi_r4s/nanopi_r4s.go
> fix: image build for nanopi_4s

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Move `setupLogging` inside the controller, so that logger is set up correctly before Talos starts printing first messages.
This fixes an inconsistency that first messages are printed using "default" logger, while after that the proper logger is set up, and format of the messages matches kernel log.
Also move `waitForUSBDelay` into the sequencer after `udevd` was started (this is when blockdevices including USB ones are discovered).
> fix: proper logging in machined on startup

- pkg/download/download.go
- pkg/download/download_test.go
> feat: show first 32 bytes of response body on download error

- internal/app/apid/pkg/backend/apid.go
- pkg/grpc/proxy/backend/local.go
Previously a fix was deployed in the Talos API client, but when the request passes through `apid`, we need to make sure that proxy doesn't reject large responses.
> fix: set max msg recv size when proxying

- pkg/imager/profile/profile.go
With SecureBoot, kernel args are part of the UKI (and signed), so we need to allow kernel args when building an installer, as this is the only way to allow updating kernel args in SecureBoot mode.
> fix: allow extra kernel args for secureboot installer

- website/content/v1.5/_index.md
- website/content/v1.6/_index.md
In the getting ["Getting Started" section](https://www.talos.dev/v1.5/introduction/getting-started/#acquire-the-talos-linux-image-and-boot-machines) the iso images are both for the previous release. Right now the links are:
```
X86: https://github.com/siderolabs/talos/releases/download/v1.5.4/metal-amd64.iso
ARM64: https://github.com/siderolabs/talos/releases/download/v1.5.4/metal-arm64.iso
```
But they should point to the latest `v1.5.5`.
I believe `lastRelease` in `_index.md` also needs to be bumped. 
> docs: update lastRelease to v1.5.5 in _index.md

- internal/app/machined/pkg/system/services/extension.go
- internal/integration/api/extensions_qemu.go
- pkg/machinery/extensions/services/services.go
- website/content/v1.6/advanced/extension-services.md
Fixes #7873
Some services which perform mounts inside the container which require mounts to propagate back to the host (e.g. `stargz-snapshotter`) require this configuration setting.
> fix: allow rootfs propagation configuration for extension services

- website/content/v1.5/introduction/what-is-new/index.md
Fixes a broken link in the documentation.
https://www.talos.dev/v1.5/introduction/what-is-new/#tpm-based-disk-encryption
Verified with `make docs-preview`
> docs: fix link in what is new page

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/system/services/extension.go
Start container early in the boot process so system extension services start in maintenance mode.
Fixes: #7083
> chore: start containerd early in boot

- api/machine/machine.proto
- pkg/machinery/api/machine/machine_grpc.pb.go
- website/content/v1.6/reference/api.md
Fixes formatting for https://www.talos.dev/v1.6/reference/api/#machineservice
Formatting with change:
> docs: fix table formatting for machineservice api

- cmd/talosctl/cmd/talos/pcap.go
- website/content/v1.6/reference/cli.md
Fixes whitespaces in talosctl pcap examples. With change:
Before change (current docs): https://www.talos.dev/v1.5/reference/cli/#synopsis-15
> docs: fix talosctl pcap example indentation

- api/machine/machine.proto
- pkg/machinery/api/machine/machine.pb.go
- website/content/v1.6/reference/api.md
Fixes formatting for https://www.talos.dev/v1.6/reference/api/#bootstraprequest
Before:
With this change:
> docs: fix table formatting for bootstraprequest

- internal/app/machined/pkg/controllers/runtime/events_sink_config.go
- internal/app/machined/pkg/controllers/siderolink/config.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
Ignore kernel command line for `SideroLink` and `EventsSink` config when running in container mode. Otherwise when running Talos as a docker container in Talos it picks up the host kernel cmdline and try to configure SideroLink/EventsSink.
> fix: ignore kernel command line in container mode

- cmd/talosctl/cmd/talos/dashboard.go
- website/content/v1.6/reference/cli.md
Fixes the shortcuts for the dashboard command by encoding < and >
Current docs: https://www.talos.dev/v1.6/reference/cli/#talosctl-dashboard
With commit:
> docs: fix talosctl dashboard cli docs

- cmd/talosctl/cmd/talos/inspect.go
- website/content/v1.6/reference/cli.md
Adds missing whitespace to ensure correct rendering on web
Current docs https://www.talos.dev/v1.6/reference/cli/#talosctl-inspect-dependencies
With change:
> docs: fix talosctl inspect dependencies example indentation

- cmd/talosctl/cmd/talos/pcap.go
- website/content/v1.6/reference/cli.md
Fixes a formatting issue on the website. The `--output` argument is shown with a single dash and without code formatting. 
Current docs: https://www.talos.dev/v1.6/reference/cli/#talosctl-pcap
With change:
> docs: fix talosctl pcap argument

- internal/app/machined/pkg/controllers/k8s/node_taint_spec.go
- internal/app/machined/pkg/controllers/k8s/node_taint_spec_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
- internal/integration/api/node-labels.go
- internal/integration/api/node-taints.go
- pkg/machinery/config/config/machine.go
- pkg/machinery/config/container/container_test.go
- pkg/machinery/config/types/v1alpha1/schemas/v1alpha1_config.schema.json
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
- pkg/machinery/constants/constants.go
- pkg/machinery/labels/validate.go
- pkg/machinery/labels/validate_test.go
- website/content/v1.6/reference/configuration.md
- website/content/v1.6/schemas/v1alpha1_config.schema.json
This PR adds support for custom node taints. Refer to `nodeTaints` in the `configuration` for more information.
Closes #7581
> chore: add custom node taints

- cmd/installer/pkg/install/install.go
- go.mod
- go.sum
- hack/release.toml
- pkg/imager/imager.go
- pkg/machinery/config/types/v1alpha1/schemas/v1alpha1_config.schema.json
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.6/reference/configuration.md
- website/content/v1.6/schemas/v1alpha1_config.schema.json
- website/content/v1.6/talos-guides/install/boot-assets.md
Support dropping kernel args that start with `-`.
Fixes: #7613
> feat: support sanitized kernel args

- pkg/machinery/config/merge/merge.go
- pkg/machinery/config/merge/merge_test.go
Checking for `zeroValue` is not enough when accessing `map[string]any`.
Closes #8005
> fix: do not panic in `merge.Merge` if map value is nil.

- internal/app/machined/main.go
- internal/app/machined/pkg/controllers/network/platform_config.go
- internal/app/machined/pkg/runtime/emergency/emergency.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Fixes #7854
Talos runs an emergency handler if the sequence experiences an unrecoverable failure. The emergency handler was unconditionally executing "reboot" action if no other action was received (which only gets received if the sequence completes successfully), so the Shutdown request might result in a Reboot behavior on error during shutdown phase.
This is not a pretty fix, but it's hard to deliver the intent from one part of the code to another right now, so instead use a global variable which stores default emergency intention, and gets overridden early in the Shutdown sequence.
> fix: store and execute desired action on emergency action

- hack/release.toml
It was using `note` instead of `notes`, so some entries got dropped.
I blame CodePilot for that ;)
> chore: fix the release.toml

- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/vm/disk.go
The core blockdevice library already supported resolving symlinks, we just need to get the raw block device name from it, and use it afterwards.
In QEMU provisioner, leave the first (system) disk as virtio (for performance), and mount user disks as 'ata', which allows `udevd` to pick up the disk IDs (not available for `virtio`), and use the symlink path in the tests.
> fix: support user disks via symlinks

- pkg/machinery/config/encoder/markdown.go
- pkg/machinery/config/encoder/markdown.tmpl
- website/content/v1.6/reference/configuration/v1alpha1/config.md
Markdown/HTML can't have headings after level 6, so make sure the maximum heading level is capped at 6.
We have just a single place with such deep nesting.
> docs: cap max heading level

- cmd/installer/pkg/install/install.go
- internal/app/machined/pkg/runtime/board.go
- internal/app/machined/pkg/runtime/v1alpha1/board/bananapi_m64/bananapi_m64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/jetson_nano/jetson_nano.go
- internal/app/machined/pkg/runtime/v1alpha1/board/libretech_all_h3_cc_h5/libretech_all_h3_cc_h5.go
- internal/app/machined/pkg/runtime/v1alpha1/board/nanopi_r4s/nanopi_r4s.go
- internal/app/machined/pkg/runtime/v1alpha1/board/pine64/pine64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rock64/rock64.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4/rockpi4.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rockpi4c/rockpi4c.go
- internal/app/machined/pkg/runtime/v1alpha1/board/rpi_generic/rpi_generic.go
When creating an image under non-default mount prefix, it should be explictly used when copying SBC files.
See https://github.com/siderolabs/image-factory/issues/65
> fix: use correct prefix when installing SBC files

- internal/app/machined/pkg/controllers/k8s/address_filter.go
- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
- internal/app/machined/pkg/controllers/k8s/control_plane_test.go
- internal/app/machined/pkg/controllers/k8s/endpoint.go
- internal/app/machined/pkg/controllers/k8s/extra_manifest.go
- internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go
- internal/app/machined/pkg/controllers/k8s/kubelet_config_test.go
- internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
- internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
- internal/app/machined/pkg/controllers/k8s/kubelet_static_pod.go
- internal/app/machined/pkg/controllers/k8s/manifest.go
- internal/app/machined/pkg/controllers/k8s/manifest_apply.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- internal/app/machined/pkg/controllers/k8s/node_apply.go
- internal/app/machined/pkg/controllers/k8s/node_apply_test.go
- internal/app/machined/pkg/controllers/k8s/nodeip.go
- internal/app/machined/pkg/controllers/k8s/render_config_static_pods.go
- internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
- internal/app/machined/pkg/controllers/k8s/static_pod_config.go
- internal/app/machined/pkg/controllers/k8s/static_pod_config_test.go
- internal/app/machined/pkg/controllers/k8s/static_pod_server.go
- internal/app/machined/pkg/controllers/k8s/static_pod_server_test.go
This is going to be multipart effort to finally use safe.* wrappers in the production code. Quick regexp search shows that there are around 150 direct type assertions on resources (excluding the ones in this commit).
Also - migrate from `interface{}` to `any` and use `slices.Sort` instead of `sort.*` where possible.
> chore: modernize machined/pkg/controllers/k8s

- go.mod
- go.sum
- pkg/imager/profile/internal/signer/azure/azure.go
- pkg/imager/profile/internal/signer/azure/azure_test.go
- pkg/imager/profile/internal/signer/azure/secureboot.go
The previous code was a mistake, the public part of the certificate is more easily available.
> fix: update the way secureboot signer fetches certificate (azure)

- website/content/v1.5/talos-guides/install/bare-metal-platforms/secureboot.md
- website/content/v1.6/talos-guides/install/bare-metal-platforms/secureboot.md
Add note to try spamming Esc to bring up the sd-boot menu option if keys don't automatically enroll in UEFI firmware.
> docs: secureboot sd-boot menu clarification

- pkg/imager/iso/loader.conf
- pkg/imager/iso/uefi.go
- pkg/imager/utils/copy.go
Without truncate the file was not overwritten properly if the file with the same name already exists and has smaller size.
Fixes #8097
Also add a 10 second timeout on UEFI ISO boot, so that boot menu can be seen without pressing `Esc` many times.
> fix: properly overwrite files on install

- cmd/installer/pkg/install/install.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/decode.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/encode.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub_test.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/testdata/grub_write_no_reset_test.cfg
- pkg/imager/iso/grub.cfg
- pkg/imager/iso/grub.go
- pkg/imager/out.go
- pkg/imager/quirks/quirks.go
- pkg/imager/quirks/quirks_test.go
Add some quirks to make images generated with newer Talos compatible with images generated by older Talos.
Specifically, reset options were adding in Talos 1.4, so we shouldn't add them for older versions.
See https://github.com/siderolabs/image-factory/issues/20
> fix: imager should support different Talos versions

- pkg/imager/out.go
Only Talos 1.5+ provides proper optimized image,
Talos 1.4 provided a single-layer image (which worked in this case), while Talos 1.2-1.3 have multi-layered images which can't be replaced easily.
> fix: pick correctly base installer image layers

- .drone.jsonnet
- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/test/e2e-image-factory.sh
- hack/test/e2e.sh
This allows to pass direct URLs to Image Factory assets for disk image/ISO/vmlinuz/initramfs, so that we can test Image Factory with Talos.
Also add an integration test for Image Factory.
Fixes #8110
> chore: support http downloads for assets in talosctl cluster create

- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/testdata/expected.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/digitalocean.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/digitalocean/testdata/expected.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/testdata/expected.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/expected.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/expected.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/upcloud/upcloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/vultr/vultr.go
We will use the default IPv6 gateway priority as 2048. The RA default is 1024, which leads to verbose messages such as 'error adding route: netlink receive: file exists.'
Azure uses DHCPv6 and RA for configuring IPv6 on the node. The platform sets the default gateway as a fallback in case 'accept_ra' is not set to 2.
PS. @smira can we backport it to 1.6.x?  Thanks.
> fix: default priority for ipv6

- internal/app/storaged/server.go
`talosctl disks` always show empty UUID and WWID which is annoying if you want to select an install disk by a stable hardware attribute.
https://github.com/siderolabs/omni-feedback/issues/54#issuecomment-1712956202
Missing UUID and WWID attributes during conversion from go-blockdevice Disk to protobuf Disk
> fix: disk UUID & WWID always empty in `talosctl disks`

- pkg/machinery/config/types/network/rule_config.go
Use `replace` patch merging strategy for `portSelector.ports` and `ingress`es in `NetworkRuleConfig` document, so that they do not have duplicate entries and/or fail on port range validation.
Closes siderolabs/talos#8136.
> fix: merge ports and ingress configs correctly in NetworkRuleConfig

- internal/app/machined/pkg/controllers/k8s/control_plane.go
- internal/app/machined/pkg/controllers/k8s/kubeprism_config.go
- internal/app/machined/pkg/controllers/k8s/kubeprism_config_test.go
- internal/app/machined/pkg/controllers/secrets/kubelet.go
- internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans.go
- internal/app/machined/pkg/controllers/secrets/kubernetes_cert_sans_test.go
- internal/app/machined/pkg/controllers/secrets/root.go
Before this change KubePrism used hardcoded "localhost" as destination which Go could resolve to IPv6 destination and then fail to connect to. This change forces KubePrism to connect using IPv4 and uses hardcoded "127.0.0.1" destination so it will always use IPv4.
For #8112
> fix: force KubePrism to connect using IPv4

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
This pulls in gRPC keepalive fix.
See https://github.com/siderolabs/discovery-client/pull/8
(not required for v1.6.x, as it runs older grpc-go library)
> fix: update discovery service client to v0.1.6

- cmd/talosctl/cmd/mgmt/gen/secureboot.go
- website/content/v1.6/talos-guides/install/bare-metal-platforms/secureboot.md
PEM was converted to DER incorrectly when the output was a X509 certificate and not a public key.
Skip unnecessary parsing of it to an RSA public key before writing it in DER format as output.
Simplify the code as we do not generate `*-signing-public-key.pem` anymore.
> fix: fix .der output in `talosctl gen secureboot`

- pkg/machinery/config/merge/merge.go
- pkg/machinery/config/types/v1alpha1/testdata/strategic/005/expected.yaml
- pkg/machinery/config/types/v1alpha1/testdata/strategic/005/left.yaml
- pkg/machinery/config/types/v1alpha1/testdata/strategic/005/right.yaml
- pkg/machinery/config/types/v1alpha1/testdata/strategic/006/expected.yaml
- pkg/machinery/config/types/v1alpha1/testdata/strategic/006/left.yaml
- pkg/machinery/config/types/v1alpha1/testdata/strategic/006/right.yaml
The audit policy is marked as `merge: replace`, but there's no check for zero value. So the problem is that any patch which has `cluster:` section zeroes out previously set `cluster.apiServer.auditPolicy`.
Add regression tests.
> fix: strategic patch merging for audit policy

- website/content/v1.6/talos-guides/howto/cert-management.md
> docs: add how-to for cert management

- Dockerfile
- Makefile
use registry and username inside Dockerfile to allow build with custom registry
impossible to `make imager` with specific kernel built and pkgs version
> chore: allow custom registry to build installer/imager

- cmd/talosctl/cmd/talos/config.go
- website/content/v1.7/reference/cli.md
> fix: use correct TTL for talosconfig in `talosctl config new`

- website/content/v1.0/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.1/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.2/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.3/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.4/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.5/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.6/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.7/talos-guides/install/virtualized-platforms/vmware.md
Fixes #8190 - a documentation bug.
Better documentation.
> Fix #8190 - vmware.md - add missing talos-config option to the vmtools-secret step

- cmd/installer/pkg/install/meta_value.go
- pkg/imager/imager.go
- pkg/imager/quirks/quirks.go
- pkg/imager/quirks/quirks_test.go
- pkg/machinery/meta/meta.go
- pkg/machinery/meta/meta_test.go
- website/content/v1.7/advanced/metal-network-configuration.md
Fixes #8186
This is planned to be backported to Talos 1.6.3.
This allows to pass large META values (YAML for platform network configuration) which might otherwise exceed the limit for kernel command line params.
> fix: allow META encoded values to be compressed

- Dockerfile
- pkg/machinery/config/schemas/config.schema.json
- website/content/v1.7/schemas/config.schema.json
After the JSON schema is generated in a build container, copy it over to the host, so it becomes a part of the codebase.
This is required as the location of the schema changed recently from being under `pkg/machinery/config/types/` to be under `pkg/machinery/config/schemas/`.
> docs: copy generated JSON schema to host

- website/content/v1.4/advanced/metal-network-configuration.md
- website/content/v1.5/advanced/metal-network-configuration.md
- website/content/v1.6/advanced/metal-network-configuration.md
- website/content/v1.7/advanced/metal-network-configuration.md
There are some broken links on the metal-network-config.md page, it seems to be the same error copied between multiple versions.
Fixed the set of the same links in 1.4, 1.5, 1.6, and 1.7, except a link in 1.4 where it links to boot assets and boot assets, if we were to place a copy in that version, it is missing a bunch of supporting links. Opted to skip that update, as that documentation is unsupported.
Because fixed links are nice, and not having to hunt down the correct link saves people time.
> docs: fix broken links in metal-network-configuration.md

- internal/app/machined/pkg/controllers/runtime/cri_image_gc.go
- internal/app/machined/pkg/controllers/runtime/cri_image_gc_test.go
Fixes #8069
The image age from the CRI is the moment the image was pulled, so if it was pulled long time ago, the previous version would nuke the image as soon as it is unreferenced. The new version would allow the image to stay for the full grace period in case the rollback is requested.
> fix: take into account the moment seen when cleaning up CRI images

- internal/app/machined/pkg/controllers/config/acquire_test.go
- internal/app/machined/pkg/controllers/secrets/root_test.go
With switching to RSA service account, machine config generation time is considerably higher now, so the test might not make it in time.
> chore: bump timeout in acquire tests

- Dockerfile
Don't ask me why this weird syntax for flags.
Don't ask me why it fails with exit code zero (success) on invalid flags.
> chore: fix markdown-lint call

- internal/app/machined/main.go
While we decide what to do with #8263 and #8256 this quickfix at least allows us to see what went wrong.
> fix: add log line about controller runtime failing

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/integration/cli/config.go
- pkg/machinery/config/generate/secrets/bundle.go
This PR adds a TTL argument to the `GenerateTalosAPIClientCertificate` function.
Fixes #8250.
The value of the `--crt-ttl` argument of the `talosctl config new` command did not get passed to the `GenerateTalosAPIClientCertificate` function which generates a new client certificate, causing the default of one year to always be used.
> fix: pass TTL when generating client certificate

- website/content/v1.6/talos-guides/install/cloud-platforms/nocloud.md
- website/content/v1.7/talos-guides/install/cloud-platforms/nocloud.md
This PR updates the documentation that suggested reading and editing the VM configuration by hand, and replaces that with CLI commands to do the same.
I also updated the UUID to be a real UUID, and then I tested these commands on my home Proxmox server to ensure they make the changes they're expected to.
Proxmox _does_ support manually editing the configuration files, but a safer option is to use the CLI or API for the sake of option validation.
The `qm` command needs to be run from a root shell, but you need to be `root` to edit (or even read!) the configuration via something like SFTP, anyway, so I think this ultimately is a safer option than suggesting manual editing of the config file.
> Update nocloud.md Proxmox information

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
Fixes #4525
The previous implementation had several issues:
* etcd concurrency session never closed
* Unlock() with potentially closed context
* unlocking when upgrade sequence finishes, but this overlaps with the machine reboot, so a chance that it never got unlocked
> fix: unlock the upgrade mutex properly

- pkg/machinery/config/configloader/configloader_fuzz_test.go
- pkg/machinery/config/configloader/configloader_test.go
- pkg/machinery/config/configloader/internal/decoder/decoder_test.go
- pkg/machinery/config/configloader/testdata/fuzz/FuzzConfigLoader/dfd1adfe630cffc2
- pkg/machinery/config/configloader/testdata/multidoc2.test
- pkg/machinery/config/configloader/testdata/multidoc3.test
- pkg/machinery/config/internal/registry/registry.go
- pkg/machinery/config/internal/registry/registry_test.go
Fixes #8270
The base bug was that the registry will return `nil` `ConfigDocument` if the version is not registered for a kind, which would result into weird config decoding errors.
Add more unit-tests, while at it, also add more fuzzing samples.
> fix: decoding config document with wrong apiVersion

- cmd/talosctl/cmd/talos/upgrade-k8s.go
- hack/release.toml
- internal/integration/provision/provision.go
- pkg/cluster/kubernetes/kubelet.go
- pkg/cluster/kubernetes/talos_managed.go
- pkg/cluster/kubernetes/upgrade.go
- website/content/v1.7/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.7/reference/cli.md
Fixes: #8275 
* Adding management of private registries for k8s upgrades
* set image before condition
* format
Due to the usage of authentication for image pullin adding this in the pre-pull feature was to big that is why we enable the feature only on --pre-pull=false.
It could be another feature. 
The cli patch MachineConfig using public registries. This break automatic upgrade because of public registries overwriting.
Co-author : @g3offrey
> feat: custom image settings for k8s upgrade

- pkg/cluster/check/default.go
- pkg/cluster/check/events.go
The previous implementation used old events API, which had several issues:
* buffer overruns, and weird checks
* big timeout even if the all nodes are booted up
Replace that with direct reading of `MachineStatus` resource which is available since Talos 1.2.0.
> fix: use MachineStatus resource to check for boot done

- hack/release.toml
- website/content/v1.7/advanced/extension-services.md
- website/content/v1.7/talos-guides/upgrading-talos.md
Deprecate `environmentFile` for extension services in favor of `ExtensionServiceConfig`.
> chore: deprecate `environmentFile` for extensions

- internal/app/machined/pkg/controllers/network/dns_upstream.go
Prevent `DNSUpstreamController` from panicking by checking if the `machine` section in the config is `nil`. This is the case when a machine has partial configuration, e.g., when the machine has only a `SideroLinkConfig` in its config.
> fix: correctly handle partial configs in `DNSUpstreamController`

- go.mod
- go.sum
- pkg/imager/profile/input.go
- pkg/imager/profile/internal/signer/aws/aws.go
- pkg/imager/profile/internal/signer/aws/aws_test.go
- pkg/imager/profile/internal/signer/aws/pcr.go
- pkg/imager/profile/internal/signer/aws/secureboot.go
As of today, `imager` secureboot-iso generation only supports file and azure approach. The goal of the PR is extending the feature to also support AWS KMS as Signer by implementing the `Crypton.Signer` interface.
Support AWS KMS as signer method for generating UKI.
Given that you have a certificate issued by AWS KMS and the KMS id itself, the following fields needs to be passed to `-` profile under `input.secureboot.securebootSigner` yaml field:
- certPath: certificate issued by AWS KMS service which you want to embed into the ISO image.
- awsKmsID: AWS key that will sign the UKI
- awsRegion: region where such KMS is present.
> Implementing secureboot imager leveraging AWS KMS as signer

- go.mod
- go.sum
- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/syslogd.go
- internal/app/syslogd/internal/parser/parse.go
- internal/app/syslogd/internal/parser/parse_test.go
- internal/app/syslogd/syslogd.go
- internal/app/syslogd/syslogd_test.go
- pkg/machinery/constants/constants.go
Add a basic syslog listening on `/dev/log`.
Fixes: https://github.com/siderolabs/talos/issues/8087
> feat: add basic syslog implementation

- cmd/talosctl/cmd/mgmt/cluster/create.go
Allow passing a static, custom config to every machine created by `talosctl cluster create`. This is useful for testing, e.g., passing partial machine config via cloud user data.
> feat: add custom config support to `talosctl cluster create`

- Makefile
- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/grpc/grpc-go/pull/6954
Before:
```
-rw-r--r-- 1 smira smira 68241300 Feb 20 20:08 _out/initramfs-amd64.xz
```
After:
```
-rw-r--r-- 1 smira smira 66376648 Feb 20 20:08 _out/initramfs-amd64.xz
```
> chore: disable x/net/trace in gRPC to enable dead code elimination

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/provision/providers/vm/disk.go
- pkg/provision/request.go
- website/content/v1.7/reference/cli.md
Added an option to disable `fallocate` calls on QEMU images
Preallocation is still done by default for correct max usage estimates, but in development environment it could be beneficial not to use up that space, so I added a flag to disable preallocation and provision the image thinly.
> chore: allow non preallocated disks for QEMU cluster

- internal/app/machined/pkg/runtime/v1alpha1/platform/opennebula/opennebula.go
fix for feature https://github.com/siderolabs/talos/pull/8249 
Fix for the platform OpenNebula to only set gateway if is set in context.
to resolve error when you attach a second nic to the vm without gateway
> fix: platform opennebula - only set gateway if is set in context

- internal/app/apid/main.go
- internal/app/apid/pkg/provider/provider.go
- internal/app/trustd/internal/provider/provider.go
- internal/app/trustd/main.go
Fixes #8345
Both `apid` and `trustd` services use a gRPC connection back to `machined` to watch changes to the certificates (new certificates being issued).
This refactors the code to follow regular conventions, so that a failure to watch will crash the process, and they have a way to restart and re-establish the watch.
Use the context and errgroup consistently.
> fix: handle errors to watch apid/trustd certs

- website/content/v1.0/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.1/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.2/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.3/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.4/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.5/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.6/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
We missed the `cluster` key in the config patch. Fixed to avoid user confusion.
> docs: update config patch in cilium docs

- pkg/imager/profile/input.go
- website/content/v1.7/talos-guides/install/boot-assets.md
Use standard Docker/Podman auth methods plus `GITHUB_TOKEN`.
See #8363
> fix: provide auth when pulling images in the imager

- go.mod
- go.sum
- pkg/provision/providers/qemu/launch.go
When provisioning VMs, each launch process sets up CNI network, and from time to time CNI setup fails with something like:
```
error provisioning CNI network: plugin type="firewall" failed (add): running [/sbin/iptables -t filter -N CNI-ADMIN --wait]: exit status 4: iptables v1.8.10 (nf_tables)
```
This a race condition in the CNI plugins, and it looks like there is no fix for it (see e.g. https://github.com/hashicorp/nomad/issues/8838).
As a workaround, take a mutex around CNI operation to serialize them. CNI setup happens in different processes, so use a file-based mutex.
> fix: workaround a race in CNI setup (talosctl cluster create)

- cmd/installer/pkg/install/install.go
- pkg/machinery/constants/constants.go
As we're using a mirrored image from `registry.k8s.io`, use that as a source instead of GitHub. Mirrored image appears with some delay after an official CoreDNS release.
> chore: update CoreDNS renovate source

- website/content/v1.2/learn-more/knowledge-base.md
- website/content/v1.3/learn-more/knowledge-base.md
- website/content/v1.4/learn-more/knowledge-base.md
- website/content/v1.5/learn-more/knowledge-base.md
- website/content/v1.6/learn-more/knowledge-base.md
- website/content/v1.7/learn-more/knowledge-base.md
> docs: fix typo in word governor

- cmd/installer/cmd/imager/root.go
- pkg/imager/imager.go
- pkg/imager/internal/overlay/executor/executor.go
- pkg/imager/profile/deep_copy.generated.go
- pkg/imager/profile/input.go
- pkg/imager/profile/profile.go
- pkg/imager/quirks/quirks.go
- pkg/machinery/overlay/adapter/adapter.go
- pkg/machinery/overlay/overlay.go
Support overlays for imager.
The `Install` interface is not wired yet, it will be done as a different PR.
This should be a no-op for existing imager.
Part of: #8350
> feat: imager overlay

- internal/app/syslogd/internal/parser/parse.go
- internal/app/syslogd/internal/parser/parse_test.go
Fixes a condition when the timestamp contains a single digit day. This started failing when the month started :sweat_smile.
Also handle a case when `tag` and `hostname` are both missing.
> fix: syslog parser

- website/content/v1.7/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
Changed the documentation for the configuration of Mayastor.
Trying to install the Mayastor deployment led to MountVolume.NewMounter errors. At least for my case the issue resided in the path of the patch being incorrect.
> docs: update replicated-local-storage-with-openebs-jiva.md

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/machinery/config/bundle/bundle.go
As `--input-dir` flag now supports partial configs, it should not fail when there is no talosconfig in the directory.
This was the missing part in siderolabs/talos#8333.
> fix: do not fail cluster create when `--input-dir` does not contain talosconfig

- internal/pkg/install/install.go
Fix the nil dereferences when a Talos node is attempted to be upgraded while in maintenance mode and having a partial machine config.
> fix: fix nil panic on maintenance upgrade with partial config

- .drone.jsonnet
- Dockerfile
- Makefile
- cmd/installer/cmd/imager/root.go
- cmd/installer/cmd/installer/root.go
- cmd/installer/pkg/install/install.go
- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/board/board.go
- internal/pkg/install/install.go
- pkg/imager/imager.go
- pkg/imager/out.go
- pkg/imager/overlay/executor/executor.go
- pkg/imager/profile/deep_copy.generated.go
- pkg/imager/profile/profile.go
- pkg/imager/quirks/quirks.go
- pkg/imager/quirks/quirks_test.go
- pkg/machinery/constants/constants.go
- pkg/machinery/overlay/adapter/adapter.go
- pkg/machinery/overlay/overlay.go
Implement `Install` for imager overlays.
Also add support for generating installers.
Depends on: #8377
Fixes: #8350
Fixes: #8351
Fixes: #8350
> feat: implement `Install` for imager overlays

- internal/app/machined/pkg/controllers/runtime/maintenance_service.go
- internal/app/machined/pkg/controllers/runtime/maintenance_service_test.go
We now remove the machine config with the id `maintenance` when we are done with it - when the maintenance service is shut down.
Closes siderolabs/talos#8424, where in some configurations there would be machine configs with both `v1alpha1` and `maintenance` IDs present, causing the `talosctl edit machineconfig` to loop twice and causing confusion.
> fix: remove maintenance config when maintenance service is shut down

- internal/integration/api/apply-config.go
- internal/integration/base/api.go
- pkg/cluster/kubernetes/patch.go
- pkg/machinery/config/container/container.go
- pkg/machinery/config/container/container_test.go
- pkg/machinery/config/provider.go
The current code was stipping non-`v1alpha1.Config` documents. Provide a proper method in the config provider, and update places using it.
> fix: patch correctly config in `talosctl upgrade-k8s`

- internal/integration/api/volumes.go
They're flaky, disable until the root cause is known.
> test: disable volume tests

- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/expected.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/metadata.json
- website/content/v1.6/_index.md
- website/content/v1.6/talos-guides/install/bare-metal-platforms/equinix-metal.md
- website/content/v1.7/talos-guides/install/bare-metal-platforms/equinix-metal.md
Fixes #8267
Also refactor the code so that we don't fail hard on mutiple bonds, but it's not clear still how to attach addresses, as they don't have a interface name field, so for now attaching to the first bond.
Fixes #8411
> fix: populate routes to BGP neighbors (Equinix Metal)

- cmd/installer/pkg/install/install.go
- internal/app/machined/pkg/controllers/block/devices.go
- internal/app/machined/pkg/controllers/block/internal/inotify/inotify.go
- internal/app/machined/pkg/controllers/block/internal/inotify/inotify_test.go
- internal/app/machined/pkg/controllers/block/internal/kobject/kobject.go
- internal/pkg/etcd/etcd.go
I want to catch a spurious error `ENODEV`, where exactly it comes from.
> chore: annotate installer errors

- hack/release.toml
- internal/pkg/ntp/ntp.go
- pkg/machinery/config/schemas/config.schema.json
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.7/reference/configuration/v1alpha1/config.md
- website/content/v1.7/schemas/config.schema.json
Add support for using PTP clock devices as time sources instead of NTP servers. Mainly targeted for using paravirtual sources, but if a system extension is made true PTP network time can be possible as well as time sync controller can sync to a PTP device.
Fixes #8347 
> feat: allow syncing time to /dev/ptp_kvm and so on

- go.mod
- go.sum
- pkg/provision/providers/docker/reflect.go
For consistency with `talosctl cluster create`, this commit fetches the missing information through an inspect call for each node so that this information are available from a `Reflect` initialization.
`talosctl cluster show` currently reports '-' in the CPU and RAM columns because this information are not available directly from the container list API call.
➡️ Placing a call to Docker inspect in this location does not feel right from an architecture point of view. It should probably be in `listNodes` instead, but it would change the signature from `[]types.Container` to `[]types.Container`. While this type is mostly a superset of the former, it will require adaptations to the existing callers. Let me know if you want me to do this.
> See `make help` …
> feat: report Docker node resources in cluster show

- pkg/provision/providers/qemu/arch.go
add openSUSE OVMF paths
Tested both secureboot and non-secure code. Not enabled SB by default
Avoid the need to copy those files to temp files
> chore: talosctl: add openSUSE OVMF paths

- Makefile
- website/content/v1.4/introduction/quickstart.md
- website/content/v1.5/introduction/quickstart.md
- website/content/v1.6/introduction/quickstart.md
- website/content/v1.7/introduction/quickstart.md
Bump hugo and change the quickstart guide to use brew install instructions. Updated command formatting and added warning for macOS Docker Desktop users.
> docs: quickstart video and brew install

- internal/app/machined/pkg/controllers/network/address_merge_test.go
- internal/app/machined/pkg/controllers/network/link_merge_test.go
- internal/app/machined/pkg/controllers/network/operator_merge_test.go
- internal/app/machined/pkg/controllers/network/route_merge_test.go
- internal/app/machined/pkg/controllers/siderolink/userspace.go
Before this commit, if tunnel failed with error, it would never restart again until `siderolink.TunnelType` event happen. For most of the time it's a good idea, because it might mean that destination has changed.
But tunnel can also fail because allowed peer list is not yet loaded on newly started Omni instance.
Because of that, we want to try again and not be tied to the runtime event channel.
> fix: retry in the fixed amount of time if grpc relay failed

- Dockerfile
- go.mod
- go.sum
- internal/app/init/main.go
- internal/app/machined/pkg/controllers/block/internal/kobject/kobject.go
- internal/integration/api/rotate.go
- internal/integration/base/api.go
- pkg/machinery/constants/constants.go
- pkg/rotate/pki/kubernetes/kubernetes.go
Fixes #8361
Talos requires v2 (circa 2008), but VMs are often configured to limit the exposed features to the baseline (v1).
```
[    0.779218] [talos] [initramfs] booting Talos v1.7.0-alpha.1-35-gef5bbe728-dirty
[    0.779806] [talos] [initramfs] CPU: QEMU Virtual CPU version 2.5+, 4 core(s), 1 thread(s) per core
[    0.780529] [talos] [initramfs] x86_64 microarchitecture level: 1
[    0.781018] [talos] [initramfs] it might be that the VM is configured with an older CPU model, please check the VM configuration
[    0.782346] [talos] [initramfs] x86_64 microarchitecture level 2 or higher is required, halting
```
> fix: report unsupported x86_64 microarchitecture level

- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/network.json
Fixes #8531 
The issue was that the link 'bridge' was skipped, so Talos default was applied to run DHCP and use the DHCP hostname (instead of using platform's hostname).
> fix: handle more OpenStack link types

- internal/app/machined/pkg/controllers/network/operator/vip.go
I noticed that while looking at #8493, but I don't know if this problem actually happened in real life.
If acquiring a VIP fails (which can only fail for Equinix/HCloud, not L2 ARP announce), we should not set the leader flag, as it would make the controller announce the IP, while it shouldn't do that.
If this call fails, there's no matching call to de-announce on failure.
The bug would show up as two nodes having same VIP assigned on the host.
> fix: don't announce the VIP on acquire failure

- hack/release.toml
Also add a note about how-to enable dns caching for k8s pods.
> docs: change localDNS to hostDNS in release notes yaml section

- hack/release.toml
- internal/app/machined/pkg/controllers/network/nftables_chain.go
In Talos, kubelet (and kube-proxy) images use `iptables-wrapper` script to detect which version of `iptables` (legacy or NFT) to use.
The script assumes that `kubelet` runs on the host, and uses whatever version of `iptables` which is being used by the host. In Talos, `kubelet` runs in a container which has same `iptables-wrapper` script, and it defaults to `legacy` mode in our case.
We can't check the `kubelet` image, as it would affect all Talos version, so instead pre-create the chains/tables in `nftables` so that kubelet will pick up `nft` version of `iptables`, and `kube-proxy` will do the same.
Without this fix, the problem arises from the mix of `nft` used by Talos for the firewall and Kubernetes world relying on `legacy` (`xtables`).
Fixes …
> fix: pre-create nftables chain to make kubelet use nftables

- internal/app/apid/pkg/backend/apid.go
Fixes #8552
When `apid` notices update in the PKI, it flushes its client connections to other machines (used for proxying), as it might need to use new client certificate.
While flushing, just calling `Close` might abort already running connections.
So instead, try to close gracefully with a timeout when the connection is idle.
> fix: close the apid connection to other machines gracefully

- internal/app/machined/pkg/controllers/k8s/render_secrets_static_pod.go
- internal/integration/api/rotate.go
This fixes an issue with a single controlplane cluster.
Properly present all accepted CAs to the apiserver, in the test let the cluster fully recovery between two CA rotations performed.
> fix: present all accepted CAs to the kube-apiserver

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
Only the cert should be present on worker nodes, enforce this via validation.
> fix: validate that workers don't get cluster CA key

- pkg/cluster/check/kubernetes.go
Sort the pod names, so the check output doesn't re-print itself on no change to the list of pods.
> fix: make static pods check output consistent

- pkg/machinery/compatibility/kubernetes_version.go
- pkg/machinery/compatibility/kubernetes_version_test.go
- pkg/machinery/compatibility/talos18/talos18.go
- pkg/machinery/compatibility/talos_version.go
- pkg/machinery/compatibility/talos_version_test.go
Fixes #8572
This allows to use 1.7 machinery with future 1.8 (e.g. alpha) versions.
> feat: provide Kubernets/Talos version compatibility for 1.8

- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/expected.yaml
Fixes #8558
Similar fix is done for other platforms, but not OpenStack.
> fix: assign different priority to IPv6 default gateway on OpenStack

- website/content/v1.6/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
Updated the Cilium docs to include explanations about the Pod Security Admission.
For users unfamiliar with the changes introduced in K8s 1.25 and enforced by Talos that might bumb their heads against Pod Security Admission related issues after installing Cilium.
> docs: update Cilium docs

- cmd/installer/cmd/imager/root.go
- cmd/installer/cmd/installer/root.go
- cmd/installer/pkg/install/install.go
- pkg/imager/out.go
- pkg/imager/profile/input.go
1. Use overlay installer to build the `cmdline` when running in install/upgrade mode.
2. Pull down the overlay installer with the arch specific to the installer being generated, vs. the arch of the `imager`.
3. Print a message when running an overlay installer.
> fix: overlay installer operations

- go.mod
- go.sum
Brings in fixes for empty CD probing, more filesystems supported.
> chore: update go-blockdevice/v2 library to the latest version

- internal/app/machined/pkg/controllers/config/acquire_test.go
- internal/app/machined/pkg/controllers/network/address_spec_test.go
- internal/app/machined/pkg/controllers/network/link_spec_test.go
- internal/app/machined/pkg/controllers/network/link_status_test.go
- internal/app/machined/pkg/controllers/network/route_spec_test.go
- internal/integration/base/api.go
- internal/integration/base/cli.go
- internal/pkg/dns/dns.go
- internal/pkg/etcd/etcd.go
- pkg/download/download.go
- pkg/machinery/client/resolver/roundrobin.go
New package arrived in Go 1.22 which provides better rand primitives and functions. Use it instead of the old one.
> chore: replace math/rand with math/rand/v2

- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
Since we are returning interfaces in config, we have to return something typed for method chaining to work. Otherwise, it simply doesn't know what method to call because there is no type information. We also don't want to change the default config behavior, so we don't try to check for `nil` after calling `.STP()`.
Closes #8626
> fix: return proper value from Bridge.STP instead of plain nil

- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/testdata/expected.yaml
IT looks like gateway is sometimes reported as a 'route' skipping a 'gateway' field.
Fixes #8619
> fix: bump priority of OpenStack routes if IPv6 and default gateway

- internal/app/machined/pkg/controllers/k8s/templates/talos-host-dns-svc-template.yaml
Without endpoints `kube-proxy` adds an automatic reject rule for the service if it has no endpoints which breaks host network namespace DNS resolving with `forwardKubeDNSToHost: true`.
> fix: add endpoints for "virtual" `host-dns` service

- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/start-registry-proxies.sh
- pkg/provision/providers/qemu/create.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
- pkg/provision/result.go
- website/content/v1.8/reference/cli.md
Allow skipping NAT for the given destinations from a cluster network. This option makes it possible to form an etcd cluster from clusters in different networks created by running `talosctl cluster create` command multiple times using different CIDRs: they simply should have the CIDR of the other clusters passed with `--non-masquerade-cidrs`.
> feat: add `--non-masquerade-cidrs` flag to `talosctl cluster create`

- internal/app/machined/pkg/runtime/v1alpha1/platform/internal/netutils/netutils.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/opennebula/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/opennebula/opennebula.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/opennebula/opennebula_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/openstack/openstack.go
- pkg/machinery/resources/runtime/condition.go
With Talos 1.7+, more storage drivers are split as modules, so the devices might not be discovered by the time platform config is going to be loaded. Explicitly wait for udevd to settle down before trying to probe a CD.
Fixes #8625
> fix: wait for devices to be discovered before probing filesystems

- internal/integration/api/etcd-recover.go
- internal/integration/api/reset.go
- internal/integration/base/api.go
Provide a trace for each step of the reset sequence taken, so if one of those fails, integration test produces a meaningful message instead of proceeding and failing somewhere else.
More cleanup/refactor, should be functionally equivalent.
> test: improve the reset integration tests

- internal/app/machined/main.go
Delay the reboot for 10 seconds only if Talos hits an error, but otherwise just proceed with the requested action.
This removes 10 seconds on "regular" reboot without kexec.
> fix: use reboot delay only in case of error

- pkg/imager/ova/ova.go
his PR bumps the minimum hardware family to vmx-15. This corresponds to "ESXi 6.7 U2" and matches the minimum required for anyone deploying the vsphere CSI as shown in [this](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-0AB6E692-AA47-4B6A-8CEA-38B754E16567.html) doc. This allows us to bypass an extra step anytime talos is deployed into a vsphere environment.
> chore: update minimum hardware requirement for vmware ova

- website/content/v1.7/talos-guides/network/siderolink.md
- website/content/v1.8/talos-guides/network/siderolink.md
Changing documentation about siderolink so that the value to enable grpc_tunnel is `true`, so it will be `https://siderolink.api/?jointoken=token&grpc_tunnel=true`, which is what the code is actually looking for.
grpc_tunnel is described as being enabled by using the value yes in the docs, but it should be true.
> docs: fix grpc_tunnel value to true

- website/content/v1.6/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
I noticed in the docs [here](https://github.com/siderolabs/talos/blob/8df5b85ec7e8ca53fd73c9c095ee5c453d5c4e51/website/content/v1.8/kubernetes-guides/network/deploying-cilium.md?plain=1#L241) it mentions enabling the KubePrism feature.
However, [here](https://github.com/siderolabs/talos/blob/8df5b85ec7e8ca53fd73c9c095ee5c453d5c4e51/website/content/v1.8/kubernetes-guides/configuration/kubeprism.md?plain=1#L25) the docs mention it's enabled by default since 1.6.
So I was wondering if *not* removing the mention of enabling KubePrism in v1.6+ was a mistake? Note it was mentioned several times in the docs v1.5.
Disclaimer: I have no idea
```
❯ rg "kubePrism:" --glob "*deploying-cilium.md" -A1
website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
240:    kubePrism:
241- …
```
> docs: remove mention of enabling KubePrism after v1.6

- internal/app/machined/pkg/system/services/kubelet.go
This allows the kubelet to enforce AppArmor.
> feat: mount /sys/kernel/security into kubelet

- internal/integration/cli/gen.go
- pkg/machinery/config/contract.go
- pkg/machinery/config/contract_test.go
- pkg/machinery/config/generate/worker.go
- pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/base-worker.yaml
- pkg/machinery/config/types/v1alpha1/testdata/stability/v1.8/overrides-worker.yaml
This is 1.8+ only.
Fixes #8694
> fix: put cluster name to the worker machine config

- cmd/installer/cmd/installer/install.go
Otherwise we get `nil reference` exception during maintenance mode upgrade with partial machine configs.
> fix: check for `nil` machine config during installation

- website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
- Update to Proxmox docs to give guidance on installing with the QEMU guest agent
- Without the QEMU guest agent, you cannot `shutdown` the Talos VMs in Proxmox
- The `shutdown` command just hangs until Proxmox eventually terminates the VM
> Proxmox install update to add QEMU guest agent guidance

- internal/pkg/mount/mount.go
Run `xfs_repair` on `unix.EIO` error.
```text
16T18:19:30.85674118Z]: XFS (sdb5): Mounting V5 Filesystem
109.200.197.196: kern:    info: [2024-04-16T18:19:30.92421418Z]: XFS (sdb5): Ending clean mount
109.200.197.196: kern:  notice: [2024-04-16T18:19:36.42651618Z]: XFS (sdb6): Mounting V5 Filesystem
109.200.197.196: kern:    info: [2024-04-16T18:19:36.49568918Z]: XFS (sdb6): Ending clean mount
109.200.197.196: kern:  notice: [2024-04-16T18:19:36.54484918Z]: XFS (sdb6): Quotacheck needed: Please wait.
109.200.197.196: kern:  notice: [2024-04-16T18:19:36.54586418Z]: XFS (sdb6): Quotacheck: Done.
109.200.197.196: kern:   alert: [2024-05-13T15:13:11.99476118Z]: XFS (sdb6): log I/O error -5
109.200.197.196: kern:   alert: [2024-05-13T15:13:11.99477118Z]: XFS (sdb6): Filesystem has been shut …
```
> chore: handle I/O error for xfs_repair

- website/config.toml
These docs are still present in the repo, but won't be an option in the talos docs site.
> chore: remove docs prior to 1.0 from website navigation

- internal/app/machined/pkg/controllers/network/dns_resolve_cache.go
- internal/pkg/dns/dns.go
- internal/pkg/dns/dns_test.go
This PR fixes incorrect packet TTL if `forwardKubeDNSToHost` is enabled.
Credits go to Julian Wiedmann.
Closes #8698.
> fix: increase host dns packet ttl for pods

- go.mod
- go.sum
See https://github.com/siderolabs/go-tail/pull/2
It seems to pop up more with compressed logs, but overall makes sense to be fixed.
> fix: update go-tail library to fix 'short read' error

- cmd/talosctl/cmd/talos/containers.go
- cmd/talosctl/cmd/talos/logs.go
- cmd/talosctl/cmd/talos/netstat.go
- cmd/talosctl/cmd/talos/restart.go
- cmd/talosctl/cmd/talos/root.go
- cmd/talosctl/cmd/talos/stats.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_images.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- pkg/machinery/constants/constants.go
In containerd 2.0 source tree, this constant is under `internal`, so we can't import it directly.
So instead re-declare it as a Talos constant.
Doing this multi-staged, as `go-talos-support` is using it as well, and to update it to stop importing old containerd library I need first to declare the constant in Talos source tree.
> chore: stop using containerd package for cri namespace

- internal/app/machined/pkg/controllers/secrets/api.go
- internal/integration/api/apply-config.go
- pkg/grpc/gen/remote.go
- pkg/grpc/middleware/auth/basic/basic.go
- pkg/machinery/config/container/container_test.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_validation_test.go
Note: this issue never happens with default Talos worker configuration (generated by Omni, `talosctl gen config` or CABPT).
Before change https://github.com/siderolabs/talos/pull/4294 3 years ago, worker nodes connected to trustd in "insecure" mode (without validating the trustd server certificate). The change kept backwards compatibility, so it still allowed insecure mode on upgrades.
Now it's time to break this compatibility promise, and require accepted CAs to be always present. Adds validation for machine configuration, so if upgrade is attempeted, it would not validate the machine config without accepted CAs.
Now lack of accepted CAs would lead to failure to connect to trustd.
> fix: require accepted CAs on worker nodes

- website/content/v1.7/introduction/getting-started.md
- website/content/v1.7/talos-guides/install/local-platforms/qemu.md
- website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md
- website/content/v1.7/talos-guides/install/talosctl.md
- website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
Updated all install instructions and added install page for future OS specific install instructions
Updates default install instructions for talosctl to use `brew`
We want people to have an easier way to keep talosctl updated
> docs: default to brew docs for talosctl

- .github/workflows/ci.yaml
- .github/workflows/integration-aws-cron.yaml
- .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
- .github/workflows/integration-aws-nvidia-oss-cron.yaml
- .github/workflows/integration-azure-cron.yaml
- .github/workflows/integration-cilium-cron.yaml
- .github/workflows/integration-cloud-images-cron.yaml
- .github/workflows/integration-equinix-metal-cron.yaml
- .github/workflows/integration-extensions-cron.yaml
- .github/workflows/integration-image-factory-cron.yaml
- .github/workflows/integration-images-cron.yaml
- .github/workflows/integration-misc-cron.yaml
- .github/workflows/integration-provision-0-cron.yaml
- .github/workflows/integration-provision-1-cron.yaml
- .github/workflows/integration-provision-2-cron.yaml
- .github/workflows/integration-qemu-cron.yaml
- .github/workflows/integration-qemu-csi-cron.yaml
- .github/workflows/integration-qemu-encrypted-vip-cron.yaml
- .github/workflows/integration-qemu-race-cron.yaml
- .github/workflows/integration-reproducibility-test-cron.yaml
- .github/workflows/integration-trusted-boot-cron.yaml
- .kres.yaml
Fix crons by setting up buildx always, also make sure `images-essential` has `uki-certs` as dependency.
Also use platform as `linux/amd64` in CI integration tests and cron jobs, since we don't run tests with arm64 binaries.
> fix(ci): fix crons by setting up buildx always

- go.mod
- go.sum
Logs:
```
[    7.127481] [talos] adjusting time (jump) by -205704h26m36.111961385s via 162.159.200.1, state TIME_OK, status STA_NANO {"component": "controller-runtime", "controller":t}
```
Fix: https://github.com/beevik/ntp/pull/47
Fixes: #8771
> fix: time sync over NTP from future era

- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/expected-2bonds.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/testdata/metadata-2bonds.json
Talos doesn't support MLAG aggregation yet, but having the initial testcase is a good step forward.
> test: add Equnix Metal sample metadata with two bonds

- internal/app/machined/pkg/runtime/v1alpha1/platform/equinixmetal/equinix.go
Fixes the problem when bonds can be listed in random order.
> fix: produce stable order of bonds with equinix

- cmd/talosctl/cmd/mgmt/cluster/cluster.go
- cmd/talosctl/cmd/mgmt/cluster/create.go
Otherwise, it doesn't make sense.
> chore: require enabled bootloader for docker provisioner

- .github/workflows/ci.yaml
- .github/workflows/integration-aws-cron.yaml
- .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
- .github/workflows/integration-aws-nvidia-oss-cron.yaml
- .github/workflows/integration-equinix-metal-cron.yaml
- .github/workflows/integration-extensions-cron.yaml
- .github/workflows/integration-images-cron.yaml
- .github/workflows/integration-trusted-boot-cron.yaml
- .kres.yaml
Crons needing extensions need the `generate` step as a dependency for the `talos-metadata` file.
TrustedBoot needs the `secureboot-installer`.
Equinix needs arm64 since we boot an arm64 box as part of integration.
> fix(ci): cron jobs

- .github/workflows/ci.yaml
- .github/workflows/integration-extensions-cron.yaml
- .kres.yaml
- Makefile
Now that extensions run the `extensions-validator` we need to fetch proper tags.
> chore(ci): fix integration extensions

- internal/integration/api/watchdog.go
- internal/integration/base/api.go
Add a test for watchdog
Ensure integration tests cover all code
> test: add a test for watchdog timers

- pkg/machinery/imager/quirks/quirks.go
Make it report true for Talos >= 1.5.0.
> feat: add multidoc check to the Talos quirks module

- go.mod
- go.sum
- internal/pkg/containers/cri/containerd/containerd.go
- internal/pkg/containers/cri/containerd/hosts.go
- internal/pkg/containers/cri/containerd/hosts_test.go
- internal/pkg/containers/cri/containerd/testdata/cri.toml
- internal/pkg/toml/merge.go
- internal/pkg/toml/testdata/expected.toml
Drop BurntSushi one, and use /v2 of pelletier package. There is indirect use of v1 which should hopefully go away once we move away from sonobouy.
> chore: unify toml packages being used

- internal/integration/api/common.go
This should be more reliable on `integration-aws-*` and others.
> fix: replace `nslookup` with `dig` in integration tests

- go.mod
- go.sum
github.com/beevik/ntp v1.4.2 contains [^1] overflow bug. 1.4.3 fixes that, so lets use it.
Closes #8828
[^1]: https://github.com/beevik/ntp/commit/235effe749df8cdf5d59e833f041313f2c1389e9
> fix: correct time adjustment in `time.SyncController`

- .golangci.yml
- go.mod
See https://github.com/golang/go/issues/60126
The issue is that `containerd/containerd` is an indirect dependency via a circular import from `containerd/containerd/v2` via `microsoft/hccsim`, but in fact it's not used/built into Talos.
So explicitly exclude it, so that `go.work` flows work once again.
@DmitriyMV found the issue and a workaround
> chore: fix go.work resolution

- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/gcp/gcp.go
It looks like VMs might be stuck on kexec, while there's little value in kexec with VMs.
> fix: disable kexec on GCP/Azure

- Dockerfile
This is minor, as it's lint-markdown, but seems to be slightly faster on installing dependencies, but mostly same time on running the actual tools.
> chore: use bun instead of npm

- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/metadata.go
- pkg/download/download.go
- pkg/download/download_test.go
Fixes #8555
It seems that older version supports same set of fields we actually use in our platform code, so we can safely downgrade to the version supported by Azure Stack Hub.
I used
[this repo](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable) to check schemas across versions.
> fix: downgrade Azure IMDS required version

- cmd/installer/pkg/install/errata.go
- cmd/installer/pkg/install/install.go
Fixes #8854
Talos 1.8.0 instroduces EFI ZBoot compression, and kexec from 1.7.0 to compressed kernel doesn't work.
> fix: add upgrade errata for arm64/zboot kernels

- .github/workflows/lock.yaml
- .github/workflows/stale.yaml
Mark as stale and close issues (to keep ourselves focused, and ensure that the issue is still relevant today).
Lock old issues to force new issue being created, even if the problem looks similar.
> chore: add stale and lock issue workflows

- website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
- website/content/v1.8/talos-guides/install/virtualized-platforms/proxmox.md
This PR fixes an issue I encountered installing Talos on Proxmox. The docs indicate that the command to install QEMU guest agent support is: 
`talosctl gen config talos-proxmox-cluster https://$CONTROL_PLANE_IP:6443 --output-dir _out --installer-image factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.7.0`
(using my generated image instead of the example) which caused an error when I ran that command. According to the help with the command (`talosctl gen config --help`), the parameters is `--install-image`, not `--installer-image`. This PR changes `--installer-image` to `--install-image` for both the v1.7 and v1.8 pages.
> Fixed typo in parameter for installing QEMU guest agent support

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/extension.go
- internal/app/machined/pkg/system/services/kubelet.go
- internal/app/machined/pkg/system/services/trustd.go
- pkg/machinery/constants/constants.go
There was a bit of a mess here which worked fine until we bumped runc/containerd, and the problem shows up in Talos-in-Kubernetes tests.
Use consistently `runner.WithCgroupPath`, as it handles cgroup nesting for cases when Talos runs in a contianer.
Assign each service its own unique cgroup.
> fix: update the cgroups for Talos core services

- .github/workflows/ci.yaml
- .github/workflows/integration-aws-cron.yaml
- .github/workflows/integration-aws-nvidia-nonfree-cron.yaml
- .github/workflows/integration-aws-nvidia-oss-cron.yaml
- .github/workflows/integration-azure-cron.yaml
- .github/workflows/integration-cilium-cron.yaml
- .github/workflows/integration-cloud-images-cron.yaml
- .github/workflows/integration-equinix-metal-cron.yaml
- .github/workflows/integration-extensions-cron.yaml
- .github/workflows/integration-image-factory-cron.yaml
- .github/workflows/integration-images-cron.yaml
- .github/workflows/integration-misc-0-cron.yaml
- .github/workflows/integration-misc-1-cron.yaml
- .github/workflows/integration-misc-2-cron.yaml
- .github/workflows/integration-misc-3-cron.yaml
- .github/workflows/integration-misc-4-cron.yaml
- .github/workflows/integration-provision-0-cron.yaml
- .github/workflows/integration-provision-1-cron.yaml
- .github/workflows/integration-provision-2-cron.yaml
- .github/workflows/integration-qemu-cron.yaml
- .github/workflows/integration-qemu-csi-cron.yaml
- .github/workflows/integration-qemu-encrypted-vip-cron.yaml
- .github/workflows/integration-qemu-race-cron.yaml
- .github/workflows/integration-reproducibility-test-cron.yaml
- .github/workflows/integration-trusted-boot-cron.yaml
- .kres.yaml
- hack/test/e2e-docker.sh
- hack/test/e2e-image-factory.sh
- hack/test/e2e-iso.sh
- hack/test/e2e-qemu.sh
Drop `--crashdump` and save talos cluster logs as artifacts.
> chore(ci): drop crashdump, save logs as artifacts

- internal/app/machined/pkg/controllers/network/operator/vip/hcloud.go
- internal/app/machined/pkg/controllers/network/operator_vip_config.go
As described in https://github.com/siderolabs/talos/issues/3599, assigning an alias IP in Hetzner Cloud at bootstrap of the cluster does (sometimes) not work. 
The assignment of private networks happens in the hetzner cloud after starting the server and therefore often after querying the network information when assigning VIPs.
If an alias IP is to be set but no private network is yet available, an error message is now thrown, until the private network is assigned.
Previously, no error message was thrown and the network ID was set to 0, which means that the VIP is regarded as a public floating IP in the further code and not as a private alias IP.
In addition, some logs are added that make it much easier to find out what is happening.
> fix: initial assignment of alias IP in hcloud (Hetzner)

- internal/integration/base/discovery_k8s.go
- internal/integration/base/k8s.go
- pkg/cluster/kubernetes.go
- pkg/cluster/sonobuoy/sonobuoy.go
- pkg/kubernetes/kubernetes.go
(This is not user-facing, but rather internal use of the kubeconfig in the tests/inside the machine).
This was added 4 years ago as a workaround, but instead of a global timeout we should rather use contexts with timeouts/deadlines (and we do!).
Setting a global timeout breaks streaming Kubernetes pod logs.
> chore: drop k8s timeout in the default kubeconfig

- internal/pkg/dns/dns.go
This PR does those things:
* No longer shuffles dns servers for each request.
* Sets a context timeout of 4.5 seconds.
* Correctly returns a proper error from the root layer.
> chore: fix our dns server implementation

- internal/integration/api/volumes.go
When META has never been written (e.g. booted from a disk image), it won't be detected as `talosmeta`.
> test: fix the integration test for no META name

- internal/integration/api/common.go
- internal/integration/base/k8s.go
This should make investigating things like [this](https://github.com/siderolabs/talos/actions/runs/9411253542/job/25924192027) easier.
> chore: output more info when `ExecuteCommandInPod` fails

- hack/test/e2e-aws-prepare.sh
Append the target name to the cluster name so that parallel tests do not create resources with same names.
> chore(ci): fix cluster name generation

- website/content/v1.0/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.1/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.2/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.3/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.4/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.5/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.6/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.7/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
Fixes a typo/misspelling and missing interpunctuation:
"As a safety messure Talos..." → "As a safety measure, Talos...".
Because I was reading through it and it was an easy fix.
> Typo: "As a safety messure Talos... -> As a safety measure, Talos..."

- cmd/talosctl/cmd/talos/apply-config.go
- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/integration/api/apply-config.go
Before this PR diff generator only diffed the v1alpha1 config and nothing else. With this PR it also takes separate docs into the account.
```shell
~ > <editor> controlplane.yaml
~ > talosctl -n talos-default-controlplane-1  apply-config --file controlplane.yaml --dry-run
Dry run summary:
Applied configuration without a reboot (skipped in dry-run).
Config diff:
No changes.
Documents diff:
[]config.Document{
+	&runtime.KmsgLogV1Alpha1{
+		Meta:       meta.Meta{MetaAPIVersion: "v1alpha1", MetaKind: "KmsgLogConfig"},
+		MetaName:   "omni-kmsg",
+		KmsgLogURL: s"tcp://[fdae:41e4:649b:9303::1]:8092",
+	},
}
~ > talosctl -n talos-default-controlplane-1 apply-config --file controlplane.yaml
Applied configuration without a reboot
~ >
~ >
~ >
~ > <editor> controlplane.yaml
~ > talosctl -n …
```
> chore: handle documents diff in `apply-config` dry run

- hack/test/e2e-cloud-tf.sh
Previously it was generating same name for the state file causing parallel runs to delete resources created by another running test.
Fix names to be unique by reading `cluster_name`.
> chore(ci): fix parallel runs of tf pipelines

- pkg/machinery/config/contract.go
- pkg/machinery/config/contract_test.go
Support passing in version with and without `v` prefix to Talos machine config version contract parser.
> chore: support version with and without `v` prefix

- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/pkg/ntp/ntp.go
- pkg/logging/error_suppress.go
- pkg/logging/error_suppress_test.go
- pkg/logging/zap.go
- pkg/machinery/constants/constants.go
As the controllers might fail with transient errors on machine startup, but errors are always retried, persistent errors will anyway show up in the console.
The full `talosctl logs controller-runtime` are not suppressed.
> feat: suppress controller runtime first N failures on the console

- go.mod
- go.sum
- hack/docgen/go.sum
- internal/app/machined/pkg/controllers/network/link_spec.go
- internal/app/machined/pkg/controllers/network/link_spec_test.go
- internal/app/machined/pkg/controllers/network/nftables_chain.go
- internal/app/storaged/server.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
`SortBonds` function bothered me since the last time I refactored this part.
We always know that it only accepts `network.LinkSpec`s, but we accepted the slice of untyped Resources because this is what `List` method returns. Now we can do better, since `safe.List` now supports `Swap` method.
We can utilize `sort.Interface` and pass `safe.List` directly to `SortBonds`.
> chore: improve link spec controller code

- cmd/talosctl/cmd/talos/edit.go
- cmd/talosctl/cmd/talos/output/json.go
- cmd/talosctl/cmd/talos/output/table.go
- cmd/talosctl/cmd/talos/output/yaml.go
For `get mc -o json|yaml` we pretend that `spec` field is string and not an actual yaml map. That way you can see the full spec in unformatted view using `talosctl -n <node> get mc -o yaml` or formatted using `talosctl -n <node> get mc -o yaml | yq .spec`.
`edit mc` command is unaffected.
Fixes #8687
> fix: properly output multi-doc machine config in `get mc`

- website/content/v1.8/kubernetes-guides/configuration/storage.md
The Mayastor helm chart ships with an init container that won't mount /sys and runs lsmod. Add a note in the guide as this is not obvious.
There are few hits on google. Had to search the slack channel for information. Adding pull request to make this information more accessible.
> docs: add not about mayastor nvme_tcp init container check

- pkg/machinery/client/client.go
- pkg/machinery/client/inspect.go
- pkg/machinery/client/reply.go
- pkg/machinery/client/reply_test.go
Simple change:
1. `FilterMessages` became `filterMessages`.
2. `FilterMessages` is now typed generic function which calls `filterMessages` internally.
3. Adjusted callsites of `FilterMessages`.
Most of the reflection can be avoided in `filterMessages` body (aside from setting `Messages` field which can be done using proto reflection mechanisms). But for now, lets stick to the simple change.
> chore: redo FilterMessages as generic function

- internal/app/machined/pkg/system/services/trustd.go
Not sure why this mount was needed, but it was added long time ago, and I believe it's no longer needed.
> fix: remove host bind mount for `/tmp` for trustd

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/integration/base/api.go
- pkg/provision/providers/qemu/arch.go
Ensure that SecureBoot enabled images come before regular ones.
With Ubuntu 24.04 `ovmf` package, due to the ordering of the search paths `talosctl` might pick up a wrong image and disable SecureBoot.
> fix: change the UEFI firmware search path order

- cmd/talosctl/cmd/mgmt/cluster/create.go
- internal/pkg/encryption/keys/keys.go
- internal/pkg/encryption/keys/tpm2.go
- pkg/machinery/config/config/machine.go
- pkg/machinery/config/schemas/config.schema.json
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.8/reference/configuration/v1alpha1/config.md
- website/content/v1.8/schemas/config.schema.json
Fixes #8995
There is no security impact, as the actual SecureBoot state/configuration is measured into the PCR 7 and the disk encryption key unsealing is tied to this value.
This is more to provide a way to avoid accidentally encrypting to the TPM while SecureBoot is not enabled.
> feat: provide an option to enforce SecureBoot for TPM enrollment

- internal/app/machined/pkg/adapters/network/nftables_rule.go
- internal/app/machined/pkg/adapters/network/nftables_rule_test.go
- internal/app/machined/pkg/controllers/network/nftables_chain_test.go
Fixes #9009
When building a port interval set, sort the ports and merge adjacent ranges to prevent mismatch on the nftables side.
With address sets, this was already the case due to the way IPRange builder works, but ports need a manual implementation.
> fix: sort ports and merge adjacent ones in the nft rule

- website/content/v1.7/talos-guides/configuration/editing-machine-configuration.md
- website/content/v1.8/talos-guides/configuration/editing-machine-configuration.md
Fixing a typo in the v1.7 and v1.8 docs. Ran `make docs` but didn't see any extra changes to commit.
Just to fix a misspelling I noticed after copy/pasting the command.
> docs: fix talosctl spelling

- pkg/provision/providers/qemu/preflight.go
We missed passing the log formatting options while printing logs in a couple places, causing the logs to be in inconsistent format.
> fix: fix log format in cluster provisioning

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/network/link_spec.go
- internal/app/machined/pkg/controllers/network/resolver_merge.go
- internal/app/machined/pkg/controllers/network/resolver_merge_test.go
- internal/app/machined/pkg/controllers/network/timeserver_merge.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Fixes #8690
Consider the following scenario (e.g. OpenStack): platform issues a correct list of DNS servers, which includes both IPv4 and IPv6 resolvers, and configures DHCPv4 on the interface.
DHCPv4 returns a set of IPv4 resolvers (as it can't return IPv6 ones), and this list completely overrides the list from the platform, wiping out the IPv6 resolvers completely.
With this change, the merge process is more smart, as it tries to preserve IPv6 resolvers for example if the next layer provides no resolvers for IPv6.
> fix: be more smart when merging DNS resolver config

- cmd/talosctl/cmd/mgmt/cluster/create.go
- pkg/machinery/config/contract.go
- pkg/machinery/config/contract_test.go
> fix: enforce secureboot enroll option only for supported releases

- internal/integration/api/extensions_qemu.go
Add test for Gvisor extensions when kvm platform is used.
The test is marked as skipped until pod termination issue is resolved.
> chore: add test for gvisor extension with platform kvm

- Dockerfile
- Makefile
Point to the last release to avoid updates on `make generate`.
> chore: lock microsoft secureboot certs

- website/content/v1.8/talos-guides/install/bare-metal-platforms/equinix-metal.md
Following the most recent livestream (https://www.youtube.com/live/J0DAWK21stA), I'm adding in a few small fixes, specifically to the device create command in the Equinix Metal guide, specifically this PR:
* Adds `--always-pxe` which was required to successfully boot, and
* Uses `metros` instead of `facilities` as the latter is deprecated (https://deploy.equinix.com/developers/docs/metal/locations/facilities/)
> Docs: Update Equinix Guide

- website/content/v1.7/talos-guides/install/local-platforms/docker.md
- website/content/v1.8/talos-guides/install/local-platforms/docker.md
> docs: fix docker getting started typo

- hack/containerd.toml
- hack/cri-containerd.toml
- hack/cri-plugin.part
- internal/app/machined/pkg/system/services/containerd.go
- internal/app/machined/pkg/system/services/cri.go
- internal/app/machined/pkg/system/services/udevd.go
- internal/pkg/containers/cri/containerd/config.go
- internal/pkg/containers/cri/containerd/testdata/cri.toml
- website/content/v1.8/talos-guides/configuration/containerd.md
- website/content/v1.8/talos-guides/configuration/nvidia-gpu-proprietary.md
- website/content/v1.8/talos-guides/configuration/nvidia-gpu.md
Provide `XDG_RUNTIME_DIR` environment variable, this specifically fixes the `kubectl exec` action when `/tmp` is filled up.
Update containerd configuration to version 3 and fix it up.
> fix: update containerd configuration and settings

- website/content/v1.8/kubernetes-guides/network/deploying-cilium.md
`disabled` was removed in https://github.com/cilium/cilium/pull/31286
`kubeProxyReplacement` `disabled` has to be changed to `false`.
`disabled` is no longer valid upstream
> docs: replace removed Cilium/kubeProxyReplacement value

- pkg/machinery/config/types/v1alpha1/v1alpha1_etcdconfig.go
Remove the architecture-specific tag usage for the etcd image.
The main etcd image is now multi-arch. The linux/arm64 variant of v3.5.13 and v3.5.13-arm64 resolve to the same image, so this shouldn't have any actual affect on etcd in arm64 environments. Cleaning up the special case resolves some weirdness with e.g. `talosctl images default` to producing output that depends on your local arch as opposed to the arch of your target servers.
N/A
> Remove arch-specific etcd image tag

- internal/pkg/dashboard/apidata/source.go
- internal/pkg/dashboard/dashboard.go
- internal/pkg/dashboard/logdata/logdata.go
- internal/pkg/dashboard/resolver/resolver.go
When `talosctl dashboard` is used with node "aliases" (e.g., node names or machine IDs in Omni) passed via `-n` flag, the graphs in the monitor tab were not rendered correctly: The matching of the old and current data were done incorrectly.
Fix this by doing the comparison over the non-resolved node names, not over the resolved ones.
> fix: fix graph diffs in dashboard when node aliases are used

- internal/integration/base/k8s.go
The check for k8s suite added in #9085 causes issues with applying k8s resources which are global like `Namespace` or `StorageClass`.
Instead of failing just log.
> chore: fix k8s tests

- website/content/v1.7/talos-guides/install/cloud-platforms/aws.md
- website/content/v1.8/talos-guides/install/cloud-platforms/aws.md
Updated with mulit-AZ subnets for control plane group and better copy/paste ability
> docs: AWS getting started re-write

- go.mod
- go.sum
Security fix (we are not affected).
> chore: bump github.com/docker/docker to v27.1.1+incompatible

- website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
Updates the default path used in the Talos docs to point to the [default base path in the openEBS docs.](https://openebs.io/docs/user-guides/local-storage-user-guide/local-pv-hostpath/hostpath-configuration#create-storageclass)
Defaults should be used whenever possible, also addresses requested change here https://github.com/siderolabs/talos/pull/9079#pullrequestreview-2220183221
> Fix default openEBS StorageClass base path in docs to match the default in openEBS docs

- website/content/v1.7/_index.md
- website/content/v1.7/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.7/talos-guides/install/virtualized-platforms/vmware/cp.patch.yaml
- website/content/v1.7/talos-guides/install/virtualized-platforms/vmware/vmware.sh
- website/content/v1.8/_index.md
- website/content/v1.8/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.8/talos-guides/install/virtualized-platforms/vmware/cp.patch.yaml
- website/content/v1.8/talos-guides/install/virtualized-platforms/vmware/vmware.sh
fix talos version in vmware.sh for 1.7.6
using the script from the v1.7 repo/website version, it uploads an OVA of talos 1.1, which won't work
> fix talos version in vmware.sh for 1.7.6

- hack/release.toml
The github.com/coredns/coredns dropped the tag v1.11.2 for the previous version we were using, so `release-tool` can't generate the release notes.
> chore: fix release notes

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/zboot/zboot.go
When using kernel images that are using ZBOOT for arm64 we need to extract the vmlinux from the vmlinuz EFI file and pass it on the the kexec call.
Ref: https://git.kernel.org/pub/scm/utils/kernel/kexec/kexec-tools.git/tree/kexec/kexec-pe-zboot.c
Fixes: #8907
> chore: support arm64 kexec from zboot kernel images

- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/services/udevd.go
- pkg/machinery/constants/constants.go
- website/content/v1.8/reference/kernel.md
Fixes #9092
This is a workaround for broken hardware drivers (e.g. RAID controllers), which report settled event too early.
> feat: provide device extra settle timeout

- website/content/v1.8/advanced/overlays.md
This provides rough step-by-step instructions on developing an overlay and using the imager. It also provides some basic information about different file types and their purpose.
This was discussed in siderolabs/sbc-rockchip#16. Developing an overlay is hard and can be time-consuming, but it is valuable work, so let's lower the barrier to entry.
> docs: add high-level overlay development guide

- internal/pkg/dns/dns.go
- internal/pkg/dns/dns_test.go
Do not return response to the client if we got SERVFAIL or REFUSED, until we run out of upstreams.
Fixes #9143
> fix: retry with another upstream if the previous failed.

- website/content/v1.7/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva.md
Fixes an incorrect path in the current documentation that prevents OpenEBS from working.  The documentation for 1.8 has the correct path, but whoever fixed it for that didn't make the change in the current stable docs.
So that the documentation results in a system that works.
> docs: fix incorrect path for openebs in documentation

- Dockerfile
- Makefile
`protoc-gen-doc` was using `pseudomuto/protoc-gen-doc` image which was running go 1.17. Update to use `go install` from source like other tools.
> chore: update protoc-gen-doc

- .github/workflows/ci.yaml
- .github/workflows/integration-cilium-cron.yaml
- .kres.yaml
- cmd/talosctl/cmd/mgmt/cluster/create.go
- hack/test/e2e-qemu.sh
- website/content/v1.8/reference/cli.md
Restructure code as per changes from #9198.
This makes the flag name to be in sync with what it actually does.
> chore: make qemu check flag consistent with code

- internal/integration/k8s/tink.go
- website/content/v1.8/talos-guides/install/cloud-platforms/kubernetes.md
The `/opt/cni/bin` in the rootfs contains CNI binaries, which get overwritten by the volume mount.
> fix: drop /opt mount for containers/tink

- hack/modules-amd64.txt
- hack/modules-arm64.txt
Fixes #9214
This finishes the work which started in
https://github.com/siderolabs/pkgs/pull/906, but it never got finished.
> fix: add NVMe target kernel modules

- pkg/machinery/config/configpatcher/testdata/multidoc/config.yaml
- pkg/machinery/config/configpatcher/testdata/multidoc/expected.yaml
- pkg/machinery/config/configpatcher/testdata/multidoc/strategic2.yaml
- pkg/machinery/config/types/runtime/extensions/service_config.go
- pkg/machinery/config/types/runtime/extensions/service_config_test.go
- website/content/v1.8/talos-guides/configuration/patching.md
Allow overwriting config file content.
> fix: merge extension service config files by `mountPath`

- .github/renovate.json
- .github/workflows/ci.yaml
- .github/workflows/integration-cilium-cron.yaml
- .github/workflows/integration-misc-2-cron.yaml
- .github/workflows/integration-qemu-csi-longhorn-cron.yaml
- .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
- .github/workflows/slack-notify.yaml
- .kres.yaml
- Makefile
- hack/test/e2e-qemu.sh
- hack/test/e2e.sh
- hack/test/patches/cgroupsv1.yaml
- hack/test/patches/cilium-kubeproxy.yaml
- hack/test/patches/cilium-no-kubeproxy.yaml
- hack/test/patches/extensions.yaml
- hack/test/patches/longhorn.yaml
- hack/test/patches/rook-ceph.yaml
- internal/integration/base/base.go
- internal/integration/base/k8s.go
- internal/integration/integration_test.go
- internal/integration/k8s/constants.go
- internal/integration/k8s/longhorn.go
- internal/integration/k8s/rook.go
- internal/integration/k8s/testdata/rook-ceph-cluster-values.yaml
Move rook-ceph CSI tests as go tests.
This allows us to add more CSI tests in the future.
Fixes: #9135
> chore: move csi tests as go test

- internal/app/machined/pkg/controllers/network/nftables_chain_config.go
- internal/integration/api/common.go
- internal/integration/base/k8s.go
- pkg/cluster/check/default.go
- pkg/cluster/check/kubernetes.go
Explicitly enable access to host DNS from pod/service IPs.
Also fix the Kubernetes health checks to assert number of ready pods to match expectation, otherwise the check might skip a pod (e.g. `kube-proxy` one) which is not ready, allowing the test to proceed too early.
Update DNS test to print more logs on error.
> fix: host DNS access with firewall enabled

- .github/workflows/ci.yaml
- .github/workflows/integration-image-factory-cron.yaml
- .github/workflows/integration-trusted-boot-cron.yaml
- .kres.yaml
- cmd/installer/pkg/install/install.go
- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- pkg/imager/imager.go
- pkg/machinery/imager/quirks/quirks.go
- website/content/v1.8/talos-guides/configuration/logging.md
- website/content/v1.8/talos-guides/install/bare-metal-platforms/matchbox.md
- website/content/v1.8/talos-guides/install/bare-metal-platforms/secureboot.md
Drop `console=ttyS0` argument for metal images/installer.
`console=ttyS0` causes lot of issues with bare metal hardware when trying to use a physical serial port.
Ref:
* https://bugzilla.redhat.com/show_bug.cgi?id=1839923
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=763601;msg=17
* https://www.kernel.org/doc/html/latest/admin-guide/serial-console.html
* https://github.com/coreos/fedora-coreos-tracker/issues/567
Fixes: #8695
Fixes: #8657
Fixes: #8127
> chore: drop console `ttyS0` argument.

- hack/release.toml
- pkg/flannel/template.go
- pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.25.6
> feat: update Flannel to v0.25.6

- pkg/provision/providers/qemu/arch.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
Support booting with SecureBoot on aarch64 with `talosctl cluster create` with QEMU provisioner.
> chore: aarch64 qemu local secureboot support

- internal/pkg/tui/installer/state.go
Drop calico from interactive installer.
> chore: drop calico from interactive installer

- website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
Talos config files greater than 32kb will create an error when trying to create Hetzner servers. This also applies for the default configuration.
> docs(hetzner): fix invalid input in field user_data

- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- pkg/imager/imager.go
- pkg/machinery/constants/constants.go
- pkg/machinery/imager/quirks/quirks.go
- website/content/v1.8/reference/kernel.md
Pause sequencer till the boot timeout when talos is booted from ISO, but an existing talos is installed to disk and
`talos.halt_if_installed` kernel argument is set.
Fixes https://github.com/siderolabs/talos/issues/9232
> chore: pause sequencer when talos installed and iso booted

- pkg/imager/imager.go
- pkg/imager/imager_test.go
The previous code didn't work, as it was manipulating args before they were reset by the platform.
Also it was producing wrong order of console args.
Both fixed, plus a unit-test.
> fix: correctly add console args for ttyS0

- .github/workflows/ci.yaml
- .github/workflows/integration-image-factory-cron.yaml
- .kres.yaml
Add Talos 1.7, remove Talos 1.3, as Omni minimum supported version right now is 1.4.
> test: update Talos versions in Image Factory tests

- website/content/v0.10/_index.md
- website/content/v0.11/_index.md
- website/content/v0.12/_index.md
- website/content/v0.13/_index.md
- website/content/v0.14/_index.md
- website/content/v0.6/_index.md
- website/content/v0.7/_index.md
- website/content/v0.8/_index.md
- website/content/v0.9/_index.md
- website/content/v1.0/_index.md
- website/content/v1.1/_index.md
- website/content/v1.2/_index.md
- website/content/v1.3/_index.md
- website/content/v1.4/_index.md
- website/content/v1.5/_index.md
- website/content/v1.6/_index.md
- website/content/v1.7/_index.md
- website/content/v1.8/_index.md
This PR removes the matrix links since those rooms are no longer in use.
> chore: remove matrix links from docs

- internal/app/machined/pkg/system/service_runner.go
Otherwise the internal code might assume that the service is still running and healthy, never issuing a health change event.
Fixes #9271
> fix: report internally service as unhealthy if not running

- internal/app/machined/pkg/controllers/network/link_status.go
We should ignore this, it's a totally an optional feature used in containers (Talos on its own kernel has ethtool-netlink).
Fixes #9296
> fix: remove extra logging on ethtool ioctl failures

- internal/app/machined/pkg/controllers/siderolink/config_test.go
- internal/app/machined/pkg/controllers/siderolink/status.go
- internal/app/machined/pkg/controllers/siderolink/status_test.go
In the status controller, there was a wrong method to parse the endpoint which doesn't account for all supported formats.
Use already parsed version in the config resource instead.
> fix: parse SideroLink API endpoint correctly

- internal/app/machined/pkg/controllers/network/dns_resolve_cache.go
- internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
- internal/app/machined/pkg/controllers/network/dns_upstream.go
- internal/app/machined/pkg/controllers/network/resolver_merge.go
- pkg/machinery/resources/network/dns_upstream.go
`List` returns a sorted (by id) list of resources. This doesn't work when the order of dns upstreams is important. Because of that add an `Idx` field to the "DNSUpstreams.net.talos.dev" resource, so we can preserve order.
Fixes #9274
> chore: account for resource sorting in dns upstream resource

- pkg/cluster/check/default.go
- pkg/cluster/check/kubernetes.go
The fix in #9233 wasn't correct, as it was looking for number of replicas in a "random" ReplicaSet. If the deployment has multiple replica sets, it leads to unexpected results.
Instead, read the Deployment resource directly.
> fix: update CoreDNS health check

- internal/pkg/ntp/ntp.go
- internal/pkg/ntp/ntp_test.go
Due to the bug introduced when refactoring for PTP devices, invalid NTP responses (including for example NTP kiss of death), were incorrectly handled when only a single NTP server was used.
The error was logged, but the response was used to adjust the time which leads to unexpected time jumps.
Properly ignore any invalid NTP response.
Without this fix, the adjustment from the invalid response is applied.
> fix: ignore invalid NTP responses

- pkg/machinery/config/configloader/internal/decoder/selector.go
- pkg/machinery/config/configpatcher/testdata/patchdelete/controlplane_expected.yaml
- pkg/machinery/config/configpatcher/testdata/patchdelete/strategic2.yaml
When a map key is deleted, it should be deleted as a whole. Before the fix it was zeroing out map value by key.
Fixes #9325
> fix: strategic merge patch delete for map keys

- cmd/talosctl/cmd/talos/processes.go
- internal/pkg/dashboard/components/tables.go
Otherwise the output might be distorted by characters like `\n`.
> fix: filter out non-printable characters in process line

- .github/workflows/ci.yaml
- .github/workflows/integration-extensions-cron.yaml
- .github/workflows/integration-qemu-cron.yaml
- .kres.yaml
- internal/app/machined/pkg/controllers/block/lvm.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/integration/api/extensions_qemu.go
- internal/integration/api/volumes.go
- internal/integration/base/api.go
- internal/integration/base/k8s.go
Support lvm auto-activation as per
https://man7.org/linux/man-pages/man7/lvmautoactivation.7.html.
This changes from how Talos previously used to unconditionally tried to activate all volume groups to based on udev events.
Fixes: #9300
> feat: support lvm auto activation

- pkg/machinery/extensions/extensions.go
This PR allows `/sbin/ldconfig` in extensions.
Allowing `/sbin/ldconfig` in extensions is a simple change that should have basically no bad side effects. It allows the NVIDIA container toolkit to work on Talos without modification.
The NVIDIA gpu-operator includes machinery to manage the driver on nodes via driver containers. These containers, usually provided by NVIDIA, include basically a giant shell script that will fetch, build, and load the kernel modules for the node's kernel. It will also unload these modules when the container terminates, and provide the userspace components by copying them to `/run/nvidia/driver` on the node.
More recently, driver containers have gained the ability to provide [precompiled kernel modules](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator …
> Allow /sbin/ldconfig (support for glibc extension for nvidia gpu-operator)

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/k8s/kubelet_spec.go
- internal/app/machined/pkg/controllers/k8s/kubelet_spec_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/system/runner/containerd/opts.go
- internal/app/machined/pkg/system/runner/runner.go
- internal/app/machined/pkg/system/services/apid.go
- internal/app/machined/pkg/system/services/dashboard.go
- internal/app/machined/pkg/system/services/etcd.go
- internal/app/machined/pkg/system/services/trustd.go
- internal/pkg/cgroup/cpu.go
- internal/pkg/cgroup/cpu_test.go
- internal/pkg/mount/cgroups.go
- pkg/machinery/constants/constants.go
Fixes: #7081
Review all reservations and limits set, test under stress load (using both memory and CPU).
The goal: system components (Talos itself) and runtime (kubelet, CRI) should survive under extreme resource starvation (workloads consuming all CPU/memory).
Uses #9337 to visualize changes, but doesn't depend on it.
> fix: audit and fix cgroup reservations

- pkg/machinery/config/schemas/config.schema.json
- pkg/machinery/config/types/network/kubespan_endpoints.go
- pkg/machinery/config/types/network/network_doc.go
- pkg/machinery/config/types/network/testdata/kubespanendpointsconfig.yaml
- website/content/v1.8/reference/configuration/network/kubespanendpointsconfig.md
- website/content/v1.8/schemas/config.schema.json
- website/content/v1.8/talos-guides/network/kubespan.md
- website/content/v1.8/talos-guides/upgrading-talos.md
Fix the inconsistent use of KubeSpan in docs and Config suffix for the config kind.
> docs: fix kubespan name inconsistency

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Fixes #9350
Actual fix is https://github.com/siderolabs/go-blockdevice/pull/111
> fix: update blockdevice library to v2.0.2

- website/content/v1.8/learn-more/components.md
- website/content/v1.8/reference/kernel.md
Update KSPP related URLs and fix acronym typo from "KSSP" to "KSPP".
> docs: Fix Kernel Self Protection Project (KSPP) references

- Dockerfile
- Makefile
We do it for Talos itself to minimize the memory footprint and binary size for the `dashboard` when part of Talos, while for `talosctl` we want to have better support of various terminals.
Fixes #9377
> fix: build talosctl without `tcell_minimal`

- hack/containerd.toml
This is to suppress warnings on failure to load plugins, which were harmless, but confusing.
Fixes #9393
> chore: ignore more plugins for system containerd

- .github/workflows/ci.yaml
- .github/workflows/integration-extensions-cron.yaml
- .github/workflows/integration-qemu-cron.yaml
- .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
- .github/workflows/integration-qemu-encrypted-vip-cron.yaml
- .github/workflows/integration-qemu-race-cron.yaml
- .kres.yaml
- hack/test/patches/dm-raid-module.yaml
- internal/integration/api/common.go
- internal/integration/api/volumes.go
- internal/integration/api/watchdog.go
- internal/integration/base/base.go
- internal/integration/k8s/apparmor.go
Use LVM2 tests that relies on module loading by lvm.
Fixes: #9300
> chore: better lvm2 tests

- website/content/v1.8/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
- website/content/v1.9/kubernetes-guides/configuration/replicated-local-storage-with-openebs.md
This pr fixes a typo in directory definition for patching talos with openebs/mayastor documentation:
`/var/openebs/local` -> `/var/local/openebs`
openebs fails to install with the specified patch applied to talos nodes. Upon investigation the directory hierarchy was swapped in the example. openebs expects the `/var/local/openebs` mount not `/var/openebs/local`
openebs installation was failing until this change was applied. patching the nodes caused the appropriate extra mount to be applied and openebs progressed successfully
> docs: Fix typo in extraMounts directory definition for openebs/mayastor documentation

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
For new installs, simply symlink to `/run` (which is `tmpfs`).
For old installs, simulate by cleaning up the contents.
Fixes #9432
Related to #9365
> fix: make /var/run empty on reboots

- Dockerfile
- internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
Instead of relying on cmdline (which will not work in case it's TinK on Talos, for example), add a file to container rootfs to signal the platform to machined.
> fix: improve container detection

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
As udevd is required by cryptsetup which will timeout if udevd is not working, do not stop it in StopServicesEphemeral, but let StopAllServices handle udev shutdown after cryptsetup close is called
Ref: https://bbs.archlinux.org/viewtopic.php?id=162415
> fix: do not stop udevd before unmounting volumes

- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/scaleway_test.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/expected-v2.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/expected-v3.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/metadata-v1.json
- internal/app/machined/pkg/runtime/v1alpha1/platform/scaleway/testdata/metadata-v3.json
Support legacy-style region values.
Disable DHCPv4 for external interface when public IPv4 is disabled.
Is it possible to back-port it to the 1.8 version? Thanks.
> fix: scaleway metadata

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See https://github.com/grpc/grpc-go/releases/tag/v1.66.3
Specifically stream failures, I wonder if that is causing flaky support script.
> fix: update grpc-go the latest patch release

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/partition/wipe.go
Use `DiscoveredVolumes` instead of `VolumeStatus`, force reboot to avoid confusion in the volume controller.
Fixes #9448
> fix: wipe system partitions correctly via kernel args

- internal/integration/api/volumes.go
E.g. in trusted-boot pipeline, we don't have extra disks.
(this is already in release-1.8)
> test: skip lvm test if not enough user disks available

- website/content/v1.6/advanced/egress-domains.md
- website/content/v1.7/advanced/egress-domains.md
- website/content/v1.8/advanced/egress-domains.md
- website/content/v1.9/advanced/egress-domains.md
This PR adds a list of the domains I had to allow for a Talos cluster to pull all assets needed to install and bootstrap. I've added these docs back to 1.6 of Talos, as I'm not certain they would apply to anything earlier.
> docs: add egress documentation

- website/content/v1.8/kubernetes-guides/configuration/device-plugins.md
There is an error in line 106 of changed documentation, the yaml key is supposed to be resources not requests
kubectl errors due to the key not found
```
strict decoding error: unknown field "spec.template.spec.containers[0].requests"
```
> Fix typo in documentation

- cmd/talosctl/cmd/talos/apply-config.go
- website/content/v1.9/reference/cli.md
Modules pflag and cobra use csv.Reader for `StringSliceVar` method. This doesn't work well with JSON, and we do not need this at all. Drop it.
Fixes #9493
> fix: do not use pflag csv comma reader for config-patch

- hack/test/e2e.sh
This test often fails due to etcd leader changes.
> test: skip no error test in Cilium

- cmd/talosctl/cmd/mgmt/cluster/create.go
ARM64 doesn't support `ide` as a disk driver for disks, use `virtio` instead.
> chore: use virtio driver for disks in arm64

- Dockerfile
- Makefile
Add arm64 target for integration-test, make developing on arm64 machines easier.
> chore: add arm64 target for integration-test

- pkg/provision/providers/qemu/launch.go
When using `iso` and `extra-disks` we're getting errors like below for any nodes than the first node.
```text
qemu-system-aarch64: -cdrom _out/metal-arm64-secureboot.iso: drive with bus=0, unit=2 (index=2) exists
```
Fix by explicitly specifying the the media is cdrom, so qemu doesn't index.
> fix: support `extra-disks` when using iso

- internal/app/machined/pkg/controllers/k8s/control_plane_static_pod.go
Closes #9450. This PR adds most of the [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). These are just my own suggestions though, feel free to suggest different ones or fewer. In particular, not sure about /component vs /part-of so maybe better to leave them out? I also left out `/instance`, not quite sure what to set that to or how, probably something with the node name though.
It's useful to have a set of uniform labels across Pods when looking at metrics and logs or even `kubectl` output, for example.
- not really applicable
- seemed to have unrelated failures
> feat: add recommended app.kubernetes.io labels to control-plane Pods

- .github/workflows/ci.yaml
- .github/workflows/integration-qemu-cron.yaml
- .kres.yaml
- cmd/talosctl/cmd/mgmt/cluster/create.go
- cmd/talosctl/cmd/mgmt/json_logs_launch.go
- cmd/talosctl/cmd/mgmt/kms_launch.go
- hack/test/e2e-qemu.sh
- pkg/provision/options.go
- pkg/provision/providers/qemu/create.go
- pkg/provision/providers/qemu/destroy.go
- pkg/provision/providers/vm/json-logs.go
- website/content/v1.9/reference/cli.md
Add an option to `talosctl cluster create` to start a JSON log receiver, and enabled it optionally.
Enable in `integration-qemu`.
See #9510
> test: add json logs test environment

- pkg/machinery/compatibility/kubernetes_version.go
- pkg/machinery/compatibility/kubernetes_version_test.go
- pkg/machinery/compatibility/talos19/talos19.go
- pkg/machinery/compatibility/talos_version.go
- pkg/machinery/compatibility/talos_version_test.go
To be backported to Talos 1.8 machinery to provide upgrade compatibility.
> feat: add Talos 1.9 compatiblity guarantees

- Dockerfile
- Makefile
- cmd/talosctl/cmd/mgmt/cluster/create.go
- internal/pkg/mount/switchroot/switchroot.go
- pkg/provision/options.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- website/content/v1.9/advanced/developing-talos.md
Support dropping into a very minimal debug shell.
```bash
sudo -E --preserve-env=HOME _out/talosctl-linux-amd64 cluster create --provisioner=qemu $REGISTRY_MIRROR_FLAGS --controlplanes=1 --workers=0 --with-bootloader=false --with-debug-shell
```
> chore: support debug shell for advanced development

- internal/app/machined/pkg/controllers/network/cmdline.go
Fix copy pasta in parse NTP address error message.
> fix: correct error message for invalid ip=

- hack/release.toml
- pkg/flannel/template.go
- pkg/machinery/constants/constants.go
See https://github.com/flannel-io/flannel/releases/tag/v0.26.0
(Not backporting this, as it is built against CNI 1.6.0 which is only in `main`).
> feat: update Flannel to v0.26.0

- internal/pkg/miniprocfs/processes.go
Fixes using grep on `talosctl ps` complaining about being a binary output.
> fix: talosctl process null character

- internal/app/machined/pkg/system/runner/containerd/containerd.go
- internal/app/machined/pkg/system/services/extension.go
- pkg/machinery/extensions/services/services.go
- website/content/v1.8/advanced/extension-services.md
- website/content/v1.9/advanced/extension-services.md
Allow extensions to opt-in for their logs to be printed in the console, i.e., Talos kernel log buffer as well as their default logging target.
> feat: allow extensions to log to console

- internal/app/machined/pkg/controllers/network/cmdline.go
- internal/app/machined/pkg/controllers/network/cmdline_test.go
Fixes #9552 
Recognize the alternative form `vlan=vlan1:eth1` for specifying VLANs on the kernel command line. Additionally adds a check for the vlan ID range.
The created links will still use the format ethX.NNNN for the interface names, but at least this patch allows parsing both forms on the command line.
The Talos docs at https://www.talos.dev/v1.8/reference/kernel/#vlan refers to the dracut command line docs which describe two alternative formats for `vlan=`.
> feat: add parsing of vlanNNNN:ethX style VLAN cmdline args

- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
The bug was logical: first the check was done for one of the values to be non-nil, and after that one of the values was assumed to be non-nil, while it could have been nil.
While fixing that, linter figured out that raw metadata config is never needed outside of `acquireConfig`, so this got dropped as well, simplifying the code even more.
Fixes #9578
> fix: prevent panic in nocloud platform code

- internal/app/machined/pkg/controllers/block/volume_config.go
- internal/app/machined/pkg/controllers/runtime/maintenance_service.go
- internal/app/machined/pkg/runtime/mode.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/platform.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/maintenance/server.go
- pkg/machinery/cel/celenv/celenv.go
- pkg/machinery/constants/constants.go
Introduce a new operating mode called the metal agent mode.
The mode is activated by the presence of a `/usr/local/etc/is-metal-agent` file under the root FS.
In this mode, Talos will:
- Only run the Initialize sequence, won't follow it up with the install/boot sequences
- Mark STATE partitions as `missing`, so Talos will always be in "not installed" state.
- Block applying configuration via API while in maintenance mode.
This mode can be used e.g., to collect hardware information from bare-metal servers.
> feat: introduce metal agent mode

- internal/pkg/miniprocfs/processes.go
Seems like a typo, zero is a valid character in SELinux labels
> fix: do not trim 0 from process SELinux label

- internal/pkg/containers/cri/containerd/hosts.go
- internal/pkg/containers/cri/containerd/hosts_test.go
After a fix a while ago, the condition was hard to understand - but we should skip this block as long as there's no TLS config, which might mean either being nil or having default values.
I found this while debugging #9594, but it doesn't change anything.
> fix: use more correct condition to skip generating hosts files

- pkg/machinery/config/schemas/config.schema.json
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.9/reference/configuration/v1alpha1/config.md
- website/content/v1.9/schemas/config.schema.json
As discussed [here](https://github.com/siderolabs/go-blockdevice/issues/114), this adds a warning to the docs about a bug with bus path matching for NVMe drives.
Note that `website/content/v1.9/reference/configuration/v1alpha1/config.md` dropped some comments for some reason... not sure why.
Maintainers have elected to not fix the bug. This helps other users be aware of the issue, the impact of it, and how to mitigate it.
> docs: Added warning about NVMe bus path bug

- internal/app/machined/pkg/controllers/k8s/templates/core-dns-template.yaml
Ref: https://github.com/kubernetes/kubernetes/pull/128359
Also bring in small changes from upstream CoreDNS config.
> chore: disable coredns cache for cluster domain

- internal/app/init/main.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Mount them early, they will be moved to the new root in switch root process as they're under.
> fix: mount pseudo sub-mountpoints in init

- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
As of runc 1.2.0, it internally uses an `ovverlay` mount instead of cloning `/proc/self/exe` and
https://github.com/opencontainers/runc/pull/4482/files drops and the `DMZ` code. This also reduces code that Talos has to maintain.
Fixes: #9543
> chore: drop runc memfd bind added in #9069

- internal/app/machined/pkg/controllers/network/route_config.go
- pkg/machinery/resources/network/route_spec.go
- pkg/machinery/resources/network/route_spec_test.go
When we normalize the route with e.g. IPv6 all addresses (`::/0`), we were wiping the family information. Keep the information, and also fix the scope for such routes.
Fixes #9624
> fix: make route normalization keep family

- internal/app/machined/pkg/system/services/kubelet.go
When running in containers, specifically on Docker Desktop VMs, the securityfs might be missing.
Fixes #9431
> fix: mount /sys/kernel/security conditionally

- website/content/v1.7/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.8/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.9/kubernetes-guides/upgrading-kubernetes.md
The resource in the examples had been retired a while ago, update docs accordingly.
Fixes #9651
> docs: update manual k8s upgrade docs

- Makefile
- hack/test/e2e-qemu.sh
- internal/integration/k8s/apparmor.go
- internal/pkg/install/install.go
- internal/pkg/mount/v2/pseudo.go
- pkg/imager/imager.go
- pkg/provision/providers/qemu/node.go
Conditionally mount selinuxfs only if it's present.
Fix AppArmor tests, `apparmor` and other minor LSM's and set
`apparmor=1`.
> fix: selinux handling and apparmor tests

- pkg/machinery/config/types/v1alpha1/v1alpha1_validation.go
The error was printing wrong field.
See #9647
> fix: install disk matcher error

- internal/integration/api/extensions_qemu.go
- internal/integration/k8s/usernamespace.go
We should not just rely on the sysctl, also confirm that `UserNamespacesSupport=true` feature gate is set for apiserver, so that the tests gets skipped if only sysctl is set.
> fix(ci): skip test if `UserNamespacesSupport` feature gate is not set

- hack/cloud-image-uploader/aws.go
- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
NB: it should be rewritten for AWS SDK v2.
The Progress is sometimes `nil` apparently.
> chore: fix nil pointer dereference in AWS uploader

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/network/dns_resolve_cache.go
- internal/app/machined/pkg/controllers/network/etcfile.go
- internal/app/machined/pkg/controllers/network/hostdns_config.go
- internal/app/machined/pkg/xcontext/xcontext.go
- internal/pkg/dns/dns.go
- internal/pkg/dns/dns_test.go
- internal/pkg/dns/manager.go
- internal/pkg/dns/runnner.go
Split from #9596 (without IPv6 stuff). This PR does this things:
- Refactored `DNSResolveCacheController`. Most of the logic moved to `dns` package types. Simplify and streamline logic.
- Replace most of the goroutine orchestration with suture package.
- Support per-item reaction to the dns listeners/servers failing to start. This allows us to ignore IPv6 errors if it's disabled.
- Support per-item reaction to the dns listeners/servers failing to stop.
> chore: clean dns code

- website/content/v1.8/talos-guides/install/cloud-platforms/gcp.md
- website/content/v1.9/talos-guides/install/cloud-platforms/gcp.md
Seeing the following error:
```
talosctl --talosconfig talosconfig bootstrap
error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 34.111.111.111:50000: i/o timeout"
```
The reason is that `gcloud compute instances create` command only takes tags as a comma-separated list.
Otherwise, only the last one is applied
From the command help:
```
--tags=TAG,[TAG,...]
Specifies a list of tags to apply to the instance. These tags allow
network firewall rules and routes to be applied to specified VM
instances. See gcloud compute firewall-rules create(1) for more
details.
```
> docs: use single tags option for the controlplane nodes

- website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
- website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
The last command of the Hetzner platform guide was missing the `--talosconfig` flag which would make the CLI connect to a local cluster, which is incorrect in this context.
The current command doesn't work :)
> docs: add missing `--talosconfig` parameter to end of Hetzner guide

- cmd/installer/pkg/install/extensions.go
- pkg/imager/extensions/extensions.go
- pkg/machinery/extensions/extensions_test.go
- pkg/machinery/extensions/validate.go
- pkg/machinery/imager/quirks/quirks.go
Use the version coming from imager to validate extension constraints.
Part of : #9694
> fix: use imager incoming version for extension validation

- pkg/provision/providers/qemu/arch.go
This patch adds a file search name and a file path for the QEMU provisioner for Arch Linux systems.
*tl;dr* ArchLinux renamed the 4M BIOS file over a year ago and in the last week removed the fallback it was using instead.
ArchLinux [recently stopped shipping 2M BIOS images](https://gitlab.archlinux.org/archlinux/packaging/packages/edk2/-/commit/75700baee1f5073d558029efc0e03612bedfc048) which the ability to use the QEMU provisioner on the distro. The existence of the 2M images have been masking the inability to find the 4M versions.
Several [years ago](https://gitlab.archlinux.org/archlinux/packaging/packages/edk2/-/commit/a4adfc922a23333b6705d498b05288a27ef88d88) the package maintainer for Arch's evdk2 BIOS images renamed the files with a non-standard name. Since then tools using the …
> Fix QEMU Provisioner on ArchLinux

- website/content/v1.8/talos-guides/install/cloud-platforms/vultr.md
- website/content/v1.9/talos-guides/install/cloud-platforms/vultr.md
The documentation for running talos on vultr misspells "bootstrap" as "boostrap".  Just want to fix that so the next person to do it can copy-paste, and not have to fix it themself.
> Fix a typo

- internal/app/machined/main.go
- internal/app/machined/pkg/runtime/controller.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- internal/app/machined/pkg/startup/cgroups.go
- internal/app/machined/pkg/startup/ima.go
- internal/app/machined/pkg/startup/os_release.go
- internal/app/machined/pkg/startup/startup.go
- internal/app/machined/pkg/startup/tasks.go
- internal/pkg/mount/v2/pseudo.go
Fixes #8900
Closes #9687
(contains splitting of late mounts)
The benefits:
* tasks run _before_ controllers are started
* tasks can register `defer` to undo actions
This decomposes sequencer tasks a bit.
> refactor: move early initialization functions to pre-initialize phase

- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/expected-v2.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-cloud-init.yaml
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/testdata/metadata-v2-nocloud.yaml
added support to the nocloud network metadata to accept the on-link directive. The on-link directive allows a route to be directly connected to the interface and allows a gateway outside of the nic subnet.
This is supported via kernel args but we need to use metadata passed in via an ISO and nocloud.
> feat: add on-link option for no cloud routes

- hack/release.toml
- internal/pkg/containers/cri/containerd/hosts.go
- internal/pkg/containers/cri/containerd/hosts_test.go
- internal/pkg/containers/image/resolver.go
- internal/pkg/containers/image/resolver_test.go
- pkg/machinery/config/config/machine.go
- pkg/machinery/config/schemas/config.schema.json
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.9/reference/configuration/v1alpha1/config.md
- website/content/v1.9/schemas/config.schema.json
Fixes #9613
This has two changes:
* adjust Talos registry resolver to match containerd (CRI) resolver: use by default upstream as a fallback
* add a machine config option to skip upstream as a fallback, and adjust CRI configuration accordingly
See https://github.com/containerd/containerd/blob/main/docs/hosts.md#registry-configuration---examples for details on CRI's `hosts.toml`.
> fix: registry mirror fallback handling

- go.mod
- go.sum
See https://github.com/siderolabs/talos/issues/9412
PR merged https://github.com/safchain/ethtool/pull/88
> chore: remove replace for safchain/ethtool

- hack/release.toml
- internal/app/machined/pkg/controllers/network/device_config.go
- internal/app/machined/pkg/controllers/network/device_config_test.go
- pkg/machinery/config/config/machine.go
- pkg/machinery/config/schemas/config.schema.json
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.9/reference/configuration/v1alpha1/config.md
- website/content/v1.9/schemas/config.schema.json
- website/content/v1.9/talos-guides/network/device-selector.md
This should fix the problem of including bond members by MAC address when MAC address changes as the link becomes part of the bond.
> feat: add permanent hardware addr to device selectors

- hack/modules-amd64.txt
- hack/release.toml
Drop i915 and amdgpu drivers from Talos rootfs, these will be packaged as extensions containing both firmware and drivers.
Some modules like `ttm`, `i2c-algo-bit` etc have been left off since they are used by both amdgpu and i915, so makes sense to keep in plain talos.
Part of: #9728
> chore: remove i915/amdgpu drivers

- internal/integration/cli/image.go
- pkg/imager/cache/cache.go
* print some progress
* properly save manifests for image refs which are both tagged and digested
* skip pulling duplicate blobs
> fix: small fixes for image cache generation

- internal/app/machined/pkg/controllers/block/lvm.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
In agent mode, we don't need to activate LVMs so that we can safely wipe them.
> fix: don't activate LVM volumes in agent mode

- pkg/imager/cache/cache.go
- pkg/imager/filemap/filemap.go
- pkg/imager/filemap/filemap_test.go
- pkg/imager/out.go
Always add directory entries to tarball.
Handle directory v/s files in tarball `build`.
Use the source file info to set file permissions.
> fix: add directory entries and filemode to tarball

- cmd/talosctl/cmd/talos/image.go
- pkg/imager/cache/cache.go
- pkg/imager/filemap/filemap_test.go
- website/content/v1.9/reference/cli.md
* Save image in OCI format, so imager can either use as OCI input or from a registry.
* Support caching layers to a path, so subsequent runs are faster
> chore: image cache generator improvements

- internal/app/machined/pkg/system/services/kubelet.go
- internal/app/machined/pkg/system/services/registry/app/main.go
- internal/app/machined/pkg/system/services/registry/fs.go
- internal/app/machined/pkg/system/services/registry/params.go
- internal/app/machined/pkg/system/services/registry/readers.go
- internal/app/machined/pkg/system/services/registry/registry.go
- internal/app/machined/pkg/system/services/registry/store.go
- internal/app/machined/pkg/system/services/registryd.go
- pkg/imager/cache/cache.go
Implement container registry proxy.
> feat: registry proxy

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_runtime.go
- website/content/v1.8/talos-guides/configuration/editing-machine-configuration.md
- website/content/v1.9/talos-guides/configuration/editing-machine-configuration.md
Allow to change image cache config without a reboot.
> fix: make immage cache config apply immediately

- Dockerfile
- cmd/installer/cmd/imager/root.go
- cmd/installer/pkg/install/install.go
- internal/pkg/partition/constants.go
- internal/pkg/partition/format.go
- internal/pkg/partition/partition.go
- pkg/imager/cache/cache.go
- pkg/imager/out.go
Add support for generating disk images with image cache.
Fixes: #9616
> feat: support generating disk images with image cache

- internal/app/machined/pkg/runtime/logging/circular.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_controller.go
- internal/app/machined/pkg/system/runner/goroutine/goroutine.go
All `io.Writers` implementations expect that you return exactly `len(p)` bytes on successful exit. So do just that, and ensure in runtime that we do the proper thing.
> fix: return proper number from the `timeStampWriter`

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Do not return from the function unless ctx is canceled.
> fix: properly halt installation if Talos already installed

- internal/app/machined/pkg/controllers/block/discovery.go
- internal/app/machined/pkg/controllers/block/volume_config.go
- internal/app/machined/pkg/controllers/block/volume_config_test.go
Fixes #9786
Match on exact expected size otherwise as `META` name is common, Talos might find `META` where it shouldn't be.
> fix: make Talos META partition match more precise

- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
Fixes #9811
Fall back to non-permanent hardware addresses, ignore non-physical links (e.g. bonds).
> fix: nocloud network link matching on MAC addresses

- cmd/talosctl/cmd/talos/image.go
- internal/app/machined/pkg/controllers/block/internal/volumes/locate.go
- internal/app/machined/pkg/controllers/block/internal/volumes/volumes.go
- internal/app/machined/pkg/controllers/block/volume_manager.go
- website/content/v1.9/reference/cli.md
The problem was with specific disk selector `!system_disk` - in previous implementation, as `system_disk` defaulted to false even if the system disk is not known yet, this might result in picking up a disk which is going to be system disk before system disk is picked.
In new implementation, as `system_disk` is not set before it is detected, the condition containing `system_disk` (in either way) would fail to execute and volume provision will be delayed until system disk is detected.
Also:
Fixes #9809
> fix: make `system_disk` condition work properly before install

- hack/release.toml
- pkg/imager/imager.go
- pkg/imager/imager_test.go
- pkg/machinery/imager/quirks/quirks.go
- pkg/provision/providers/qemu/node.go
For 1.9, we keep it disabled until it gets more production ready in 1.10.
It still can be enabled with `selinux=1`.
> chore: move enabling SELinux by default to 1.10

- hack/release.toml
- internal/app/machined/pkg/startup/cgroups.go
- internal/app/machined/pkg/startup/tasks.go
- internal/pkg/mount/v2/cgroups.go
- website/content/v1.9/reference/kernel.md
> chore: deprecate cgroupsv1 in non-container mode

- internal/pkg/extensions/kernel_modules.go
Fix building on SELinux systems. Extracting xattrs led to return code 2 as a non-critical error. This should not influence extension build.
> fix: do not extract xattrs in unsquashfs

- internal/app/machined/pkg/system/service_runner.go
Fixes #9839
Bug was introduced in #9273
> fix: don't reset health status if service doesn't support health checks

- internal/app/machined/pkg/system/runner/process/process.go
- internal/app/machined/pkg/system/runner/process/process_test.go
- internal/app/machined/pkg/system/runner/runner.go
- internal/app/machined/pkg/system/services/dashboard.go
- pkg/machinery/constants/constants.go
This allows us to run low-priority background tasks like xfs_scrub only while idle.
Example usage in #9848
- **chore: process: minor capability cleanup**
- **feat: allow running processes with custom priority**
- **feat: allow setting ionice on processes**
- **feat: allow setting scheduling class on processes**
> feat: add more scheduling options for process runner

- cmd/talosctl/cmd/mgmt/cluster/create.go
- internal/app/machined/pkg/controllers/block/user_disk_config.go
- internal/app/machined/pkg/controllers/block/user_disk_config_test.go
- pkg/machinery/resources/block/volume_config.go
- pkg/provision/providers/vm/disk.go
Fixes #9877
As a side-effect, fix alignment of user disks for newer QEMU versions.
> fix: lock provisioning order of user disk partitions

- pkg/provision/providers/qemu/controller.go
IPMI powers on a machine when a PowerCycle command is sent, making a prior power on call unnecessary. We probably want to do the same thing in our API-based power implementation.
> fix: power on the machine on reboot request in qemu power api

- pkg/provision/providers/docker/reflect.go
For podman the network options is not 'com.docker.network.driver.mtu but only mtu.
This patches allow to use podman for local clusters
Fixes: #7881
> fix: Use mtu network option for podman

- internal/integration/base/cli.go
- internal/integration/base/run.go
- internal/integration/cli/list.go
Rework the inners of `RunCLI` to support this.
> chore: enable proper parallel usage of TestDepth

- website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
- website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
The installation documentation for Hetzner contains [deprecated server plans](https://docs.hetzner.com/cloud/servers/deprecated-plans/) cx11 and cx21, replace them with cx22.
The installation examples do not work because of this.
> docs: replace deprecated Hetzner server plans

- website/content/v1.8/kubernetes-guides/network/multus.md
- website/content/v1.9/kubernetes-guides/network/multus.md
Fix typo found on docs (seutps => setups)
> Multus (docs): fix typo

- internal/app/machined/pkg/system/services/registry/registry.go
- internal/app/machined/pkg/system/services/registry/store.go
- internal/integration/cli/image.go
- pkg/imager/cache/cache.go
Drop semicolon in generated cache to support copying image cache to vfat filesystems.
Fixes: #9935
> chore: drop semicolon for supporting vfat filesystems

- internal/app/machined/pkg/controllers/network/node_address.go
- internal/app/machined/pkg/controllers/network/node_address_test.go
There were two issues which showed up specifically under `race` tests:
1. As the address resources are added while the controller is running, and `default` address is immutable (by design), insert the future default address first, otherwise the controller might pick up another one it sees first randomly.
2. There was a bug in accumulative address handling when the sort only took into account addresses ignoring prefix lengths.
> test: fix flaky test NodeAddressSort

- internal/app/machined/pkg/system/services/registry/registry.go
- internal/app/machined/pkg/system/services/registry/registry_test.go
- pkg/imager/cache/cache.go
Fix generating and serving registies having port in them. This is needed to copy and serve imagecache from a vfat filesystem.
> fix: generating and serving registries with port

- website/content/v1.9/talos-guides/configuration/image-cache.md
Clarifying information from #9892
> docs: update image-cache doc for iso

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/mount/system.go
The issue shows up in our tests as:
```
=== RUN   TestIntegration/api.DiscoverySuite/TestRegistries
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
discovery.go:210: waiting for cluster affiliates to be discovered: 4 expected, 6 found
``` …
> fix: node identity flip

- website/content/v1.8/talos-guides/install/cloud-platforms/aws.md
- website/content/v1.9/talos-guides/install/cloud-platforms/aws.md
Cannot boostrap (and other talosctl command) to the cluster build on AWS
To boostrap the cluster then gather dashboard or other talosctl command (health...), I need to specify the --talosconfig parameter with the generated file
.
> Add --talosconfig option with generated talosconfig file when using talosctl

- cmd/talosctl/cmd/talos/image.go
- website/content/v1.9/reference/cli.md
Container has been spelled 'containter' at multiple places.
Changed `image.go` code is only for a command description, shouldn't have any impact. Other files are the website / documentation.
> Fix 'containter' typo

- website/config.toml
- website/content/v1.8/_index.md
- website/content/v1.9/_index.md
Make Talos 1.9 documentation the default one.
> docs: activate 1.9 docs as default

- website/content/v1.10/talos-guides/install/cloud-platforms/hetzner.md
- website/content/v1.8/talos-guides/install/cloud-platforms/hetzner.md
- website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
Added lost steps in the bootstrap process and additional variant for uploading images.
An additional tool appears, and a command is added to check the status after the bootstrap process.
> Add lost steps in bootstrap. Add variant to upload image.

- internal/pkg/dashboard/components/header.go
This was introduced in 1.9 cycle.
Fixes #9998
> fix: dashboard crash on CPU data

- Dockerfile
- hack/udevd/90-selinux.rules
Create a dummy SELinux file_contexts file to mitigate the warning. We do not rely on libselinux for labeling, so empty file suffices.
> fix: fix `Failed to initialize SELinux labeling handle` udev error

- pkg/makefs/xfs_test.go
Assert on exact allocation for different filesystem size.
Note: this test only reliably works in buildkit, with a specific version of `xfsprogs`.
Fixes #10021
> test: add a xfs makefs test

- internal/app/machined/pkg/controllers/kubespan/routing_rules.go
Does not fix anything, but looks more correct
> fix: get next rule number for IPv6 in the appropriate chain

- .github/workflows/ci.yaml
- .github/workflows/integration-misc-1-cron.yaml
- .kres.yaml
- Dockerfile
- Makefile
- hack/test/e2e-qemu.sh
This still allows running install on 1 GiB hardware.
Fixes #10024
> fix: reduce installer image

- internal/app/machined/pkg/controllers/network/resolver_config.go
- internal/app/machined/pkg/controllers/network/resolver_config_test.go
Search domain should be domain name of the hostname, not the FQDN.
Bug introduced in #9844
> fix: use correct default search domain

- internal/integration/api/node-annotations.go
- internal/integration/api/node-labels.go
- internal/integration/api/node-taints.go
- internal/integration/base/k8s.go
This should improve watch reliability, as it was failing on channel being closed.
Fixes #10039
> test: use node informer instead of raw watch

- .github/workflows/ci.yaml
- .github/workflows/integration-qemu-race-cron.yaml
- .kres.yaml
- cmd/talosctl/cmd/talos/support.go
- go.mod
- go.sum
- internal/app/machined/pkg/startup/cgroups.go
- pkg/cluster/crashdump.go
1. Don't set max cgroups limit if race mode is enabled (only in test mode). When e.g. apid/trustd are built with race detector on, they consume 10x the memory.
2. Fix a data race in `talosctl support` when showing UI progress.
3. Fix an issue pulling `kubeconfig` in `talosctl support` - pull from endpoints (controlplanes) without setting any nodes.
4. Fix a deadlock in support on context cancel.
Fixes #10036
> fix: talosctl support and race tests

- internal/pkg/etcd/etcd.go
Fixes #10040
Sometimes etcd after 'server stoppped' error actually removes a member, so the next attempt returns member not found, ignore it, as our goal was to remove a member.
> fix: ignore member not found error on leave cluster

- internal/pkg/tpm/tpm_linux.go
- internal/pkg/tpm/tpm_other.go
The code from `talosctl` imports transitively tpm package, so make it build on non-Linux.
> fix: build of talosctl on non-Linux platforms

- pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_provider_test.go
> fix: exclude disks with empty transport for disk selector

- internal/pkg/secureboot/measure/measure_test.go
- internal/pkg/secureboot/secureboot.go
Bring in parity with systemd 257 by supporting more UKI sections.
The output of `sd-measure` and our measure code will be different until https://github.com/systemd/systemd/pull/35765 is fixed upstream.
Fixes: #10075
> feat: bring in partity with sd-257

- internal/pkg/mount/v2/pseudo.go
Enable `configfs`.
Ref: https://www.kernel.org/doc/Documentation/filesystems/configfs/configfs.txt
Part of: https://github.com/siderolabs/extensions/issues/562
> feat: enable `configfs`

- internal/pkg/mount/v2/pseudo.go
Having selinuxfs mounted might confuse some software, as conventional Linux systems do not have selinuxfs mounted when SELinux is disabled and no policy is loaded.
Fixes #10083
> fix: mount selinuxfs only when SELinux is enabled

- hack/release.toml
- pkg/machinery/config/generate/init.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_clusterconfig.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- pkg/machinery/config/types/v1alpha1/zz_generated.deepcopy.go
Drop deprecated `.cluster.allowSchedulingOnMasters` machine config field.
> chore: drop deprecated allowSchedulingOnMasters

- website/content/v1.10/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.9/kubernetes-guides/network/deploying-cilium.md
Updates the Cilium Installation Guide to include links to the latest stable version (previous was 1.13, it is now 1.16). 
Also includes a note about including ALPN & App Protocol to handle GRPC Connection
I was installing Omni on a Talos Cluster and running into issues using GatewayAPI as the ingress. I ran into an issue accessing Omni due to GRPC being downgraded HTTP/1.1 becuase ALPN could not be negotiated. After some troubleshooting, discovered ALPN needs to be 
> docs: Update Cilium Installation Guide to include Gateway API

- hack/cri-containerd.toml
- hack/cri-plugin.part
- website/content/v1.10/talos-guides/configuration/containerd.md
This way it's easy to re-enable NRI plugins with a simple change.
See https://github.com/siderolabs/talos/discussions/10068
I tested that it works e2e with NRI plugins repository.
> fix: disable NRI plugin in a different way

- cmd/talosctl/cmd/mgmt/cluster/create.go
- internal/pkg/secureboot/uki/generate.go
- internal/pkg/secureboot/uki/uki.go
- pkg/imager/imager.go
- pkg/imager/profile/default.go
- pkg/imager/profile/input.go
- pkg/imager/profile/profile.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/request.go
- website/content/v1.10/reference/cli.md
Support generating unsigned UKI's.
Also plumb in support to `talosctl cluster create` to boot off UKI's. This doesn't work yet as installer needs more work.
Part of #9633
> feat: support generating unsigned UKIs

- Makefile
- hack/release.toml
- pkg/machinery/constants/constants.go
- pkg/machinery/gendata/data/pkgs
> feat: update Linux to 6.12.8

- pkg/machinery/config/types/block/byte_size.go
- pkg/machinery/config/types/block/volume_config_test.go
Without the fix, the merge panics for `min`/`maxSize` due to missing `Merge` method.
> fix: merge of VolumeConfig documents with sizes

- hack/test/patches/image-cache.yaml
- internal/pkg/mount/v2/repair.go
- pkg/makefs/ext4.go
- pkg/makefs/xfs.go
> fix: extfs repair and resize

- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/install/install.go
- pkg/machinery/constants/constants.go
- website/content/v1.10/reference/kernel.md
> feat: add a kernel parameter to disable built-in auditd

- hack/release.toml
- internal/app/machined/pkg/controllers/k8s/control_plane.go
- internal/app/machined/pkg/controllers/k8s/control_plane_test.go
Fixes handling of `kube-apiserver` authorization config authorizers order.
Fixes: #10110
> fix: kube-apiserver authorizers order

- internal/app/machined/pkg/controllers/k8s/endpoint.go
- internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go
- internal/app/machined/pkg/controllers/k8s/node_status.go
- internal/integration/base/k8s.go
- internal/pkg/discovery/registry/kubernetes.go
- pkg/machinery/constants/constants.go
Also use a constant everywhere in informers.
Add some debug logs.
Might fix #9991
> fix: add informer resync period for node status watcher

- cmd/talosctl/cmd/mgmt/debug/air-gapped.go
- website/content/v1.10/advanced/developing-talos.md
While working on another issue, I discovered we can update to use new config format.
I couldn't reproduce another issue, so this is the only thing that is left.
> test: update `talosctl debug air-gapped`

- pkg/machinery/config/types/siderolink/siderolink.go
- pkg/machinery/config/types/siderolink/siderolink_doc.go
- pkg/machinery/config/types/siderolink/siderolink_test.go
- pkg/machinery/config/types/siderolink/testdata/document.yaml
- website/content/v1.10/reference/configuration/siderolink/siderolinkconfig.md
The provided example wasn't valid, it should not have a path component.
> docs: update SideroLinkConfig example

- internal/app/machined/pkg/controllers/files/cri_registry_config.go
- internal/app/machined/pkg/controllers/files/etcfile.go
Fix the `/etc` bind mounts read-only by calling a remount as `ro`.
The proper fix is to use new `fsopen` and `fsmount` API's.
> fix: make etc binds read-only

- pkg/kubernetes/kubernetes.go
K8s 1.32+ won't lest us get deleted pods as it doesn't belong to our node, so just assume the pod is gone (at least it's not on our node anymore).
Fixes #10154
> fix: ignore forbidden error when waiting for pod eviction

- Dockerfile
- hack/release.toml
- internal/app/machined/pkg/controllers/cluster/node_identity.go
- internal/app/machined/pkg/controllers/files/iqn.go
- internal/app/machined/pkg/controllers/files/nqn.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
Generate deterministic IQN and NQN files based on `machine-id`.
Fixes: #10009
> feat: generate iqn and nqn files.

- pkg/machinery/platforms/platforms.go
- pkg/machinery/platforms/platforms_test.go
- pkg/machinery/platforms/sbcs.go
- pkg/machinery/platforms/sbcs_test.go
It will be used across Image Factory, Terraform Provider and Omni.
Fixes #10108
See https://github.com/siderolabs/image-factory/pull/189
> refactor: extract platform metadata into Talos machinery

- internal/app/machined/pkg/controllers/k8s/internal/nodewatch/nodewatch.go
- internal/app/machined/pkg/controllers/k8s/node_status.go
The method `WaitForCacheSync` might block for a long time, and looks like it can block forever if the nodename requested doesn't match the actual nodename.
Allow the wait to be aborted by running it in a goroutine, and notifying readiness of the watcher via the `notifyCh`.
Fixes #10163
> fix: abort node watch on hostname change

- .github/workflows/ci.yaml
- .github/workflows/integration-qemu-csi-longhorn-cron.yaml
- .github/workflows/integration-qemu-csi-openebs-cron.yaml
- .github/workflows/integration-qemu-csi-rook-ceph-cron.yaml
- .kres.yaml
Save `fio` benchmark results as separate artifacts for upto 6 months so we could compare results b/w talos releases.
> chore(ci): fio benchmark results as separate artifacts

- website/content/v1.10/introduction/getting-started.md
- website/content/v1.10/talos-guides/install/local-platforms/qemu.md
- website/content/v1.10/talos-guides/install/local-platforms/virtualbox.md
- website/content/v1.10/talos-guides/install/virtualized-platforms/proxmox.md
- website/content/v1.7/introduction/getting-started.md
- website/content/v1.7/talos-guides/install/local-platforms/qemu.md
- website/content/v1.7/talos-guides/install/local-platforms/virtualbox.md
- website/content/v1.7/talos-guides/install/virtualized-platforms/proxmox.md
- website/content/v1.8/introduction/getting-started.md
- website/content/v1.8/talos-guides/install/local-platforms/qemu.md
- website/content/v1.8/talos-guides/install/local-platforms/virtualbox.md
- website/content/v1.8/talos-guides/install/virtualized-platforms/proxmox.md
- website/content/v1.9/introduction/getting-started.md
- website/content/v1.9/talos-guides/install/local-platforms/qemu.md
- website/content/v1.9/talos-guides/install/local-platforms/virtualbox.md
- website/content/v1.9/talos-guides/install/virtualized-platforms/proxmox.md
I am discovering this amazing project ! Thank you very much for it.
During reading the documentation I found this typo. I open this PR to fix it.
Documentation typo.
```
7.750 2025/01/20 19:48:49 generating docs for type: "KernelModuleConfig"
------
Dockerfile:355
--------------------
353 |     RUN gofumpt -w ./pkg/
354 |     WORKDIR /src/pkg/machinery
355 | >>> RUN --mount=type=cache,target=/.cache go generate ./...
356 |     RUN gotagsrewrite .
357 |     RUN goimports -w -local github.com/siderolabs/talos ./
--------------------
ERROR: failed to solve: process "/toolchain/bin/bash -c go generate ./..." did not complete successfully: exit code: 1
```
> Documentation fix typo "an MacOS" to "on MacOS"

- website/content/v1.10/advanced/proprietary-kernel-modules.md
- website/content/v1.10/kubernetes-guides/configuration/ceph-with-rook.md
- website/content/v1.10/kubernetes-guides/configuration/local-storage.md
- website/content/v1.10/learn-more/architecture.md
- website/content/v1.10/talos-guides/upgrading-talos.md
- website/content/v1.8/talos-guides/upgrading-talos.md
- website/content/v1.9/talos-guides/upgrading-talos.md
This flag no longer exists in Talos 1.8 and higher.
Fixes #10172
> docs: remove the last mentions of `preserve` flag for Talos 1.8+

- internal/app/machined/pkg/controllers/files/iqn.go
- internal/app/machined/pkg/controllers/files/nqn.go
This sets the date field to `yyyy-mm` in the generated IQN/NQN.
See: https://datatracker.ietf.org/doc/html/rfc7143#section-4.2.7.4
Signed-off-by: bzub <bzub@users.noreply.github.com>
Fixes: https://github.com/siderolabs/talos/issues/10206
> fix: invalid date field in iqn/nqn

- website/content/v1.10/talos-guides/configuration/disk-encryption.md
- website/content/v1.8/talos-guides/configuration/disk-encryption.md
- website/content/v1.9/talos-guides/configuration/disk-encryption.md
Add note about required DHCP server when using kms disk encryption
> docs: update disk-encryption.md

- .github/workflows/ci.yaml
- .github/workflows/integration-misc-2-cron.yaml
- .kres.yaml
- Makefile
- hack/release.toml
- hack/test/e2e-iso.sh
- hack/test/e2e-qemu.sh
- pkg/imager/imager.go
- pkg/imager/iso/grub.go
- pkg/imager/iso/hybrid.go
- pkg/imager/iso/iso.go
- pkg/imager/iso/uefi.go
- pkg/imager/out.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
Starting with Talos 1.10, the default generated ISO's will use GRUB for BIOS boot and sd-boot for EFI boot.
Fixes: #10192
> feat: generate iso's with both UKI and grub

- internal/app/machined/pkg/controllers/network/address_merge.go
- internal/app/machined/pkg/controllers/network/address_merge_test.go
- internal/app/machined/pkg/controllers/network/generic_merge.go
- internal/app/machined/pkg/controllers/network/hostname_merge.go
- internal/app/machined/pkg/controllers/network/hostname_merge_test.go
- internal/app/machined/pkg/controllers/network/link_merge.go
- internal/app/machined/pkg/controllers/network/link_merge_test.go
- internal/app/machined/pkg/controllers/network/operator_merge.go
- internal/app/machined/pkg/controllers/network/operator_merge_test.go
- internal/app/machined/pkg/controllers/network/resolver_merge.go
- internal/app/machined/pkg/controllers/network/resolver_merge_test.go
- internal/app/machined/pkg/controllers/network/route_merge.go
- internal/app/machined/pkg/controllers/network/route_merge_test.go
- internal/app/machined/pkg/controllers/network/timeserver_merge.go
- internal/app/machined/pkg/controllers/network/timeserver_merge_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
They had lots of common (and broken) code, so use generics to implement the core logic once, and use that in all kinds of merge controllers.
This removes lots of code duplication.
Fixes flaky unit-tests, and also improves controller perfomance on conflicts.
> refactor: all network merge controllers

- website/content/v1.10/kubernetes-guides/network/multus.md
- website/content/v1.9/kubernetes-guides/network/multus.md
this PR fixes [bug](https://github.com/siderolabs/talos/issues/10219#issuecomment-2613168885) in multus doc for talos. 
machineconfig patch is required to get multus bridge mode working.
> Update multus.md 

- internal/pkg/uki/internal/pe/extract.go
- internal/pkg/uki/internal/pe/extract_test.go
The PE UKI extract was returning a reader that reads upto the section `Size` which is the size on disk which could be padded, we need a limit reader reading upto `VirtualSize`.
> fix: pe uki extract

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/bootloader.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/kexec/kexec.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
- internal/pkg/uki/internal/pe/extract.go
Support kexec from UKI for non-secureboot by extracting kernel, initramfs and cmdline from UKI
Fixes: #10189
> feat: support kexec from uki

- website/content/v1.10/kubernetes-guides/configuration/synology-csi.md
- website/content/v1.9/kubernetes-guides/configuration/synology-csi.md
This process will not work without the iscsi-tools extension installed on the talos cluster.
Documentation change to reflect reality of process of installing Synology-csi driver on a talos cluster
The document does not explicitly state that having siderolabs/iscsi-tools installed is a prerequisite, however attempting to mount a Persistent Volume claim without these tools being available on the cluster will lead to errors due to the iscsid not running on the nodes.
> Add iscsi-tools extension to Prerequisites

- website/content/v1.10/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.9/talos-guides/install/virtualized-platforms/vmware.md
Current workarounds are use e1000 interface, switch to host-gw backend, or disable checksum offload.
related to #3143
> docs: add note about vmxnet and flannel conflict

- pkg/machinery/client/client.go
- pkg/machinery/client/client_test.go
- pkg/machinery/client/export_test.go
Always close the connection, even if we forgot to do this ourselves.
> fix: ensure proper closure of client.Client.conn with finalizer

- pkg/imager/out.go
A change to use UKIs by default broke generation of SecureBoot installers for older Talos versions.
Note: it's not affecting users, as the Image Factory hasn't been updated yet to the broken version.
> fix: installer with SecureBoot should contain UKIs

- Dockerfile
Fixes #10272
Longer description in the issue.
> fix: build of Talos on non-Linux host

- pkg/provision/providers/qemu/launch.go
Fix an issue introduced in https://github.com/siderolabs/talos/issues/10097 where if rom drives are used with qemu, they get (automatically) assigned a duplicate id of `virtio0`, which is now used for the main drives.
Please let me know if a different naming convention should be used, or if the ids should be automatically indexed instead of the hardcoded values.
```sh
$ talosctl cluster create --provisioner qemu  --controlplanes 1 --iso-path _out/metal-arm64.iso
starting /usr/bin/qemu-system-aarch64 with args:
-m 4096 -smp cpus=4 -cpu max -nographic -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device virtio-net-pci,netdev=net0,mac=ea:77:d9:dd:45:9a -device virtio-rng-pci -device virtio-balloon,deflate-on-oom=on -monitor …
```
> fix: duplicate qemu drive ids

- internal/app/machined/internal/server/v1alpha1/v1alpha1_time_test.go
- internal/pkg/cri/client.go
- internal/pkg/encryption/keys/kms.go
- pkg/grpc/gen/remote.go
- pkg/machinery/client/client_test.go
- pkg/machinery/client/grpc_connection_wrapper.go
This is an alternative to #10283 which doesn't close the connections and instead allows us to easily track the lost grpc connections using pprof.
Fix various grpc leaks while we are at it.
> chore: track opened grpc connections

- internal/pkg/uki/internal/pe/extract.go
- internal/pkg/uki/internal/pe/extract_test.go
- internal/pkg/uki/internal/pe/pe_test.go
When extracting `.cmdline` from multi profile UKI's we only need the first cmdline, rest are profile specific and not the default cmdline.
> fix: extracting cmdline multi profile UKIs

- cmd/talosctl/cmd/mgmt/loadbalancer_launch.go
- go.mod
- go.sum
It contains a breaking change, so we also need to update Talos.
> chore: upgrade siderolabs/go-loadbalancer

- website/content/v1.10/talos-guides/network/wireguard-network.md
- website/content/v1.9/talos-guides/network/wireguard-network.md
> docs: fix a typo in Wireguard docs

- internal/app/machined/pkg/controllers/cri/registries_config.go
- internal/app/machined/pkg/controllers/cri/registries_config_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
If there is no machine config at all, empty registry config should be still created.
Drop TransformController here and use regular controller, as we need to act on no resource.
See https://github.com/siderolabs/omni/issues/877
> fix: handling of empty registry config

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
If Talos fails to stop the pods, it doesn't affect any future operations.
Prevously it was critical for the install/upgrade to succeed, as it tried to remove whole partition table, but now even dangling mounts won't affect upgrades.
Sometimes pods can't be stopped because of network file systems.
Fixes #10174
> fix: ignore errors to stop pods

- internal/pkg/uki/generate.go
- internal/pkg/uki/uki.go
- internal/pkg/uki/uki_test.go
- pkg/imager/imager.go
Support passing uki profiles from imager.
Part-of: #10190
> feat: support uki profiles via imager

- pkg/machinery/config/configdiff/configdiff.go
- pkg/machinery/config/configdiff/configdiff_test.go
The second `@@` was not written to the same writer
This was breaking ability to pipe the diff output to tools that understand [`unidiff`](https://en.wikipedia.org/wiki/Diff#Unified_format)
> fix: fix diff printing

- Dockerfile
Before:
```
ls -l /etc/ssl/certs/
NODE         MODE         UID   GID   SIZE(B)   LASTMOD           LABEL                         NAME
172.20.0.2   drwxr-xr-x   0     0     65        Feb 12 14:20:52   system_u:object_r:etc_t:s0   .
172.20.0.2   -rw-r--r--   0     0     0         Feb 12 14:20:52   system_u:object_r:etc_t:s0   ca-certificates
172.20.0.2   -rw-r--r--   0     0     231212    Feb 12 16:47:29   system_u:object_r:etc_t:s0   ca-certificates.crt
```
After:
```
172.20.0.5   Lrwxrwxrwx   0     0     19        Feb 12 14:20:52   system_u:object_r:etc_t:s0   ca-certificates -> ca-certificates.crt
172.20.0.5   -rw-r--r--   0     0     231212    Feb 12 17:20:12   system_u:object_r:etc_t:s0   ca-certificates.crt
```
> fix: path for ca-certificates

- hack/release.toml
- internal/app/machined/pkg/controllers/network/nftables_chain_config.go
- internal/app/machined/pkg/controllers/network/nftables_chain_config_test.go
This fixes #10347
The core issue was that Talos nftables chain had priority 0 (`filter`), while kube-proxy does DNAT for node ports at priority -110 (before Talos can see source traffic), so Talos rule doesn't match.
Move Talos priority to -140, so it runs before kube-proxy.
> fix: make ingress firewall filter traffic to nodeports

- Makefile
- hack/release.toml
- hack/test/e2e.sh
- pkg/machinery/constants/constants.go
- website/content/v1.10/reference/cli.md
- website/content/v1.10/reference/configuration/v1alpha1/config.md
See https://github.com/kubernetes/kubernetes/releases/tag/v1.32.2
The Go modules haven't been tagged yet, but it should not be important.
> feat: update Kubernetes to 1.32.2

- Makefile
Simple typo in the Makefile target name, missing a 't' in talosctl.
> Fix typo in Makefile target talosctl-freebsd-arm64

- pkg/flannel/flannel.go
- pkg/machinery/version/osrelease.go
```
fork/exec /tmp/go-build720301329/b001/exe/gen: no such file or directory
pkg/flannel/flannel.go:8: running "go": exit status 1
```
I believe the root cause might be cache miss, that might cause `generate` target to be called from `WITH_RACE=true` target, enabling `CGO_ENABLED=1`, so it is random to reproduce (depends on buildkit cache behavior).
> chore: fix spurious generate failures

- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/metadata.go
The official documentation has a "i" value that is used as the instance-id meta parameter.
https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html
```shell
-smbios type=1,serial=ds=nocloud;h=my-host-name;i=id-1234
```
I know that the cloud (Proxmox) sets a randomly generated instance-id in the metadata file. This value cannot be reliably used in the future by code, as there is no mapping to a real ID, UUID, or other identifiers.
This PR aims to override the randomly generated Proxmox value.
> feat: support noclooud instance-id from dmi

- cmd/installer/pkg/install/preflight.go
- cmd/installer/pkg/install/preflight_test.go
Ignore the digest part of container images in machineconfig when checking semantic version validity through github.com/blang/semver/v4.
Closes #10373.
We want to pin image digests, but pre-flight tries to validate tag _and_ digest for semantic versioning.
> Ignore digest part of images when checking version in pre-flight

- website/content/v1.10/talos-guides/configuration/logging.md
- website/content/v1.9/talos-guides/configuration/logging.md
Refs: #10356
Adds a note to the website docs about syslog being part of services, so any messages sent there will be output to any configured remote logging receivers.
Adds a note to the website docs about syslog being part of services, so any messages sent there will be output to any configured remote logging receivers. I added this to both 1.9 and 1.10 website branches to ensure it was in future versions.
Details in referenced issue (#10356), but the other 2 logging facilities (kernel and services) have specific callouts with respect to configuring a remote receiver, but syslog does not. This clarifies that syslog is part of services, so messages sent there will be sent to the services receiver.
> See `make help` for a description of the available …
> docs: add a note about syslog sending messages to services

- Dockerfile
- Makefile
Go back to upstream releases after https://github.com/dmarkham/enumer/issues/105 has been fixed
> chore: update enumer to a version that fixes Go 1.24 compatibility

- website/content/v1.10/talos-guides/resetting-a-machine.md
- website/content/v1.9/talos-guides/resetting-a-machine.md
Remove minor typo on [Resetting a Machine](https://www.talos.dev/v1.9/talos-guides/resetting-a-machine/).
Corrects a typo in the documentation.
To improve the documentation
> docs: remove typo on resetting a machine page

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- internal/pkg/dashboard/apidata/node.go
- internal/pkg/dashboard/apidata/source.go
- internal/pkg/dashboard/components/header.go
There were multiple issues:
* `hostname` in the header is coming from resources, and the one in API data was unused
* we should update to `n/a` if the value is not available
* if the node is unavailable, the response contains a message with placeholders with a proxy error, and that should be honored to ignore the response; if instead we use it as it is, it puts zero value, which results in funny output.
Fixes #10383
> fix: multiple fixes for dashboard/no data

- Dockerfile
Right now any build would internally trigger `generate` even if someone forgot to do `make generate`. This causes excessive over-generation many times during the build as any change to `pkg/` invalidates the cache.
Fix that by dropping this over-generation. Our CI checks for dirtiness anyways (missing `make generate`).
Idea: Noel.
> chore: stop doing generate on each build

- internal/app/machined/pkg/controllers/network/address_config.go
- internal/app/machined/pkg/controllers/network/cmdline.go
- internal/app/machined/pkg/controllers/network/cmdline_test.go
- internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
- internal/app/machined/pkg/controllers/network/hostname_config.go
- internal/app/machined/pkg/controllers/network/link_config.go
- internal/app/machined/pkg/controllers/network/link_config_test.go
- internal/app/machined/pkg/controllers/network/operator_config.go
- internal/app/machined/pkg/controllers/network/operator_config_test.go
- internal/app/machined/pkg/controllers/network/operator_vip_config.go
- internal/app/machined/pkg/controllers/network/operator_vip_config_test.go
- internal/app/machined/pkg/controllers/network/resolver_config.go
- internal/app/machined/pkg/controllers/network/route_config.go
- internal/app/machined/pkg/controllers/network/timeserver_config.go
- pkg/machinery/resources/network/link_name_resolver.go
- pkg/machinery/resources/network/link_name_resolver_test.go
- pkg/machinery/resources/network/link_status.go
Also fix/clean up tests, and add more tests specific to link aliases.
Fixes #10402
> fix: correctly map link names/aliases when using VIP operator

- cmd/talosctl/cmd/mgmt/debug/air-gapped.go
- go.mod
- go.sum
- internal/app/machined/pkg/controllers/cluster/discovery_service.go
- pkg/grpc/dialer/proxy.go
Unfortunately, gRPC client library doesn't offer control on picking up HTTP proxy for a connection, and relies on sync.Once protected value which reads proxy variables from the environment just once.
As environment variables can be set dynamically, there is a chance that dial might happen before they are set, so they are never respected after that.
So I had to copy/adapt some part of grpc internal/transport parts to enable dynamic loading of HTTP proxy, and use new dialer in discovery client.
Fixes #10136
Also, while testing this with our small "air-gapped" tool I discovered that our HTTP proxy test implementation is not complete, so this had to be fixed as well.
> fix: handle dynamic HTTP proxy settings for discovery client

- internal/app/machined/pkg/controllers/network/nftables_chain_config.go
- internal/app/machined/pkg/controllers/network/nftables_chain_config_test.go
- internal/integration/api/firewall.go
- internal/integration/api/testdata/nodeport.yaml
The previous fix #10354 was not full/complete.
The problem lies in the fact that `kube-proxy` creates a rule like:
```
chain nat-prerouting {
type nat hook prerouting priority dstnat; policy accept;
jump services
}
```
This chain has a prerouting hook, which gets executed before Talos's input hook, and rewrites (does DNAT) for NodePort services before Talos has a chance to block the packet, but rewritten packet hits the input chain with DNAT address, or might be forwarded to another host and never hit the firewall again.
See https://github.com/siderolabs/talos/discussions/10347#discussioncomment-12280552
> fix: block NodePort services with ingress firewall

- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer.go
Simple fix of a typo in the word "shutdown".
\-
I guess this is expected behavior for my signature?
```
commit         GPG Identity                 FAILED        openpgp: signature made by unknown entity
```
> chore: fix shutdown typo in shutdown sequence

- website/content/v1.10/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
- website/content/v1.9/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
Updating `talocs disks (...)` in the documentation to `talosctl get disks (...)` to reflect the new command.
Running `talosctl disks` will throw:
```
`talosctl disks` is deprecated, please use `talosctl get disks`, `talosctl get systemdisk`, `talosctl get discoveredvolumes` instead
```
> Update deprecated command in README.md

- Makefile
- internal/integration/cli/image.go
- internal/integration/cli/list.go
- pkg/provision/providers/qemu/launch.go
Fix image cache installer ref, and preserve talos.config with UKIs for `talosctl cluster create`.
> test: fix UKI preserving talos.config and image cache

- Makefile
It has to be signed to be used as the base for imager operations.
> chore: add installer-base to the list of signed images

- internal/pkg/dns/dns_test.go
This is a workaround, as using `t.Context()` causes panics as `t.Log` is used after the test finishes, this is related to unsynchronized context.AfterFunc, but I will leave the fix to @DmitriyMV .
> test: fix dns test in race mode

- hack/test/e2e-iso.sh
> test: use standard installer for e2e-iso

- .github/workflows/ci.yaml
- .github/workflows/integration-misc-2-cron.yaml
- .github/workflows/integration-qemu-cron.yaml
- .golangci.yml
- .kres.yaml
- hack/test/e2e-qemu.sh
- pkg/provision/providers/qemu/destroy.go
Otherwise the archive is corrupted due to QEMU still writing to the logs while they are being archived
ci: enable --with-json-logs for any e2e-qemu runs
> fix: qemu: archive cluster logs only after stopping VMs

- website/content/v1.10/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
- website/content/v1.9/talos-guides/install/virtualized-platforms/vagrant-libvirt.md
Adding instruction how to get the VMs network interface. If the network interface name differs from eth0, e.g. enp1s0, the virtual IP address definition would be ignored.
The network interface name came up for me differently than eth0, causing the setting to be ignored and subsequently the IP address not being assigned. That ultimately caused the initialization halted on sending a HTTP request to the virtual IP address.
To lower the obstacles for newcomers I feel it to be appropriate to provide the `talosctl` command to request the actual interface name.
> docs: add instructions for differing network interface name

- internal/integration/api/extensions_qemu.go
- internal/integration/base/k8s.go
Use k8s websocket executor over SPDY.
> test(ci): use k8s websocket executor for tests

- .github/workflows/ci.yaml
- .github/workflows/integration-misc-2-cron.yaml
- .kres.yaml
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
https://github.com/siderolabs/talos/pull/10443 broke kexec and `callback` was never being called.
> fix: kexec when using sd-boot

- cmd/talosctl/cmd/talos/kubeconfig.go
- website/content/v1.10/reference/cli.md
Add the option for "talosctl kubeconfig" to write to stdout, using "-" as the output filename where merge is false. "talosctl gen config" already supports this convention.
This is useful to capture kubeconfig within keychains/vaults without writing it to disk first, for security purposes and for simplicity within scripts/automation.
> feat: talosctl kubeconfig write to stdout option

- pkg/machinery/config/types/v1alpha1/v1alpha1_types.go
- pkg/machinery/config/types/v1alpha1/v1alpha1_types_doc.go
- website/content/v1.10/reference/configuration/v1alpha1/config.md
- website/content/v1.9/reference/configuration/v1alpha1/config.md
I'm not sure if it's intentional to show it as "cluser" jn the example but just in case this is a typo i opened this PR :)
If its meant as an example maybe it should be changed to example.local? or corrected to cluster.local
> docs: fix typo cluser -> cluster

- hack/structprotogen/main.go
Fix example of structprotogen to reference the right name.
Found the wrong binary name reference within the example during fiddling around and getting around the source code.
> fix: correct structprotogen example

- website/content/v1.10/reference/kernel.md
- website/content/v1.10/talos-guides/configuration/certificate-authorities.md
- website/content/v1.10/talos-guides/configuration/disk-encryption.md
- website/content/v1.9/reference/kernel.md
- website/content/v1.9/talos-guides/configuration/certificate-authorities.md
- website/content/v1.9/talos-guides/configuration/disk-encryption.md
Add information to docs about STATE partition encryption using a KMS with custom CA certificates
I failed in getting this information from the docs in the places I had looked, and so had opened #10542.
Hopefully this will help future users.
> docs: clarify custom CA certificate compatibility with KMS STATE partition encryption

- website/content/v1.1/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.10/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.2/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.3/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.4/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.5/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.6/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.7/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.8/kubernetes-guides/upgrading-kubernetes.md
- website/content/v1.9/kubernetes-guides/upgrading-kubernetes.md
In the manual kubernetes upgrade website doc there is a typo where kube-proxy version is the same (in the change from X to Y example), this can confuse ppl following the doc
Can confuse someone, mostly an OCD from my side
> doc: Fix version typo in kube-proxy manual upgrade

- website/content/v1.10/talos-guides/configuration/containerd.md
- website/content/v1.9/talos-guides/configuration/containerd.md
Add docs for configuring Containerd CDI spec dirs
Default CDI spec dirs are not writable in Talos, which means DRA out of the box does not work in Talos
> docs: Add docs for configuring Containerd CDI spec dirs

- cmd/talosctl/cmd/talos/image.go
- pkg/imager/cache/cache.go
- pkg/imager/filemap/filemap.go
- website/content/v1.10/reference/cli.md
Fixes #10558
The core issue is mix of path separators: the resulting image layer should contain `/` (UNIX), while native separator might be different (`\` on Windows).
> fix: image cache generation on Windows

- internal/pkg/containers/cri/containerd/config_test.go
- internal/pkg/containers/cri/containerd/containerd.go
- internal/pkg/containers/cri/containerd/testdata/cri.toml
A special case, for `docker.io`, use `registry-1.docker.io`.
Fixes #10617
> fix: containerd auth hostname in the config

- internal/app/init/main.go
- internal/app/machined/pkg/controllers/files/etcfile.go
- internal/pkg/mount/v2/bind.go
Extract common code from `etcfile` controller and use it to mount files from initramfs into the new root actually as read-only.
```
rootfs /usr/lib/firmware rootfs ro,seclabel,size=1920152k,nr_inodes=480038 0 0
rootfs /etc/extensions.yaml rootfs ro,seclabel,size=1920152k,nr_inodes=480038 0 0
```
> fix: use proper read-only bind mounts in init

- website/content/v1.10/talos-guides/install/single-board-computers/rpi_generic.md
Added relevant example documentation for using the `vc4` system extension module and configuring the `config.txt` file of the Raspberry Pi target.
Relevant issue: https://github.com/siderolabs/extensions/issues/636
Relevant pkgs PR: https://github.com/siderolabs/pkgs/pull/1196
Relevant extensions PR: https://github.com/siderolabs/extensions/pull/659
Lack of current documentation about changing the `config.txt` file while making an image for the Raspberry Pi + usage of the new `vc4` system extension that needs to have a changed `config.txt` to function properly.
> feat: add vc4 documentation

- internal/app/machined/pkg/controllers/block/mount_status.go
- internal/app/machined/pkg/controllers/block/mount_status_test.go
- internal/app/machined/pkg/system/service_runner.go
- internal/app/machined/pkg/system/volumes.go
Wait for the volume mount status to be properly destroyed on service shutdown, and fix the controller to destroy it as well.
> fix: race in the volume mount status handling

- .github/workflows/integration-aws-nvidia-oss-cron.yaml
- .kres.yaml
- Makefile
- Use `make` variables to auto-detect target platform and not hardcode it.
- Separate one of the aws tests to a little different cron time so it works (running both parallely never worked).
- Pass in `--base-installer-image` so when a developer runs `make image-installer` with some extensions `IMAGE_REGISTRY` is honored.
> chore: small developer improvements

- cmd/talosctl/cmd/talos/list.go
SELinux context (file extended attribute `security.selinux`) is a null-terminated string. We need to properly convert the C-string inside the byte slice into a Golang string to avoid also printing the null byte in the ls command output.
Discovered when piping talosctl ls output to grep:
$ talosctl ls /lib/modules/ -r -l | grep '\.ko'
grep: (standard input): binary file matches
> fix: Avoid printing terminating null byte in SELinux context

- website/content/v1.10/talos-guides/configuration/patching.md
- website/content/v1.10/talos-guides/install/bare-metal-platforms/matchbox.md
- website/content/v1.10/talos-guides/install/cloud-platforms/gcp.md
- website/content/v1.10/talos-guides/install/cloud-platforms/hetzner.md
- website/content/v1.10/talos-guides/install/cloud-platforms/openstack.md
- website/content/v1.10/talos-guides/install/cloud-platforms/oracle.md
- website/content/v1.10/talos-guides/install/cloud-platforms/upcloud.md
Make the difference between inline patches and patches from files slightly clearer.
Addresses https://github.com/siderolabs/talos/issues/10630.
> docs: improve references to config patches

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/grub.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
Add EFI mount for GRUB install only if EFI mount is present, since starting Talos v1.10 if we boot of a dual-boot image EFI is wiped in BIOS mode.
> fix: upgrades with bios

- api/resource/definitions/network/network.proto
- go.mod
- go.sum
- internal/app/machined/pkg/controllers/network/address_spec.go
- internal/app/machined/pkg/controllers/network/address_spec_test.go
- internal/app/machined/pkg/controllers/network/address_status.go
- internal/app/machined/pkg/controllers/network/address_status_test.go
- internal/app/machined/pkg/controllers/network/nftables_chain_test.go
- internal/app/machined/pkg/controllers/network/operator/dhcp4.go
- pkg/machinery/api/resource/definitions/network/network.pb.go
- pkg/machinery/api/resource/definitions/network/network_vtproto.pb.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- pkg/machinery/resources/network/address_spec.go
- pkg/machinery/resources/network/address_status.go
- website/content/v1.10/reference/api.md
See https://github.com/jsimonetti/rtnetlink/pull/256
See https://github.com/siderolabs/talos/issues/10696
Support setting address priority, this is important to ensure that the prefix route has appropriate priority.
For now, we don't have it exposed in the machine config except for the DHCP4 operator, so now both routes created explicitly by DHCP and routes created implicitly have same metric/priority:
```
172.20.0.2   network     RouteStatus   inet4//172.20.0.0/24/1024                                1         172.20.0.0/24                                enp0s2      1024
172.20.0.2   network     RouteStatus   inet4/172.20.0.1//1024                                   1                                         172.20.0.1   enp0s2      1024
```
Before this change, the first route would have a …
> feat: support address priority

- website/layouts/partials/hooks/body-end.html
The search in the documentation page no longer works due to changes made in https://github.com/siderolabs/talos/pull/10672 by yours truly
The issue lies in the change of behavior of the `split` function. After the hugo update the 0th index is a whitespace, not the docs version.
https://github.com/siderolabs/talos/blob/f0ea478cb811675a450839b8dcd351e43404efd4/website/layouts/partials/hooks/body-end.html#L6
Just changing the index to one does result in the correct `$currentVersion` value, but the search results still don't appear.  This might be due to the a broken state of the [crawler data store](https://docsearch.algolia.com/docs/manage-your-crawls/) because the meta tags used for the version assignments have been broken since #10672 was merged. I cannot confirm this theory as I don't …
> docs: fix search

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/grub/install.go
Only select `x86_64-efi` if EFI needs to be installed.
> fix: grub efi platform install

- website/content/v1.9/kubernetes-guides/configuration/storage.md
What?
This commit tries to address an issue with the current documentation and the patches it provided for configuring the worker nodes in the OpenEBS Mayastor installation
Why?
While I was trying to follow the documentation I encountered an error in my deployment "FailedMount”, stating that a PVC doesn’t exist, checking at the video and also in this other [tutorial](https://blog.dalydays.com/post/kubernetes-storage-with-openebs/) I can confirm indeed there is an error with the patch in the documentation, very subtle but is there
> chore(docs): fixed typo at OpenEBS Mayastor worker patches

- website/content/v1.10/talos-guides/install/virtualized-platforms/vmware.md
- website/content/v1.9/talos-guides/install/virtualized-platforms/vmware.md
Correct the configuration example for using flannel `extraArgs`.
Thanks to Cameron in the [community Slack](https://taloscommunity.slack.com/archives/CMARMBC4E/p1745300100041919?thread_ts=1745299857.476909&cid=CMARMBC4E).
> docs: correct flannel extra args example

- internal/integration/provision/provision.go
- internal/integration/provision/upgrade.go
- pkg/machinery/client/client.go
Add a provision test without UEFI boot.
Drop preserve upgrade test since it's the default now.
Fixes: #10777
> chore(ci): add provision test with bios

- website/content/v1.10/talos-guides/install/cloud-platforms/hetzner.md
- website/content/v1.9/talos-guides/install/cloud-platforms/hetzner.md
This commit adds a note that Hetzner Cloud now provides Talos Linux as ISO in their public cloud ISO library.
Due to the increased demand of Talos Linux, Hetzner is now providing Talos Linux as ISO in their public ISO library.
```
hcloud iso list --type public
119702   hcloud-amd64.iso   Talos Linux 1.9.5 (amd64 / Hetzner + qemu-guest-agent)   public   x86
119703   hcloud-arm64.iso   Talos Linux 1.9.5 (arm64 / Hetzner + qemu-guest-agent)   public   arm
```
Edit 2025-04-23 13:23 CEST: We've published a [changelog entry](https://docs.hetzner.cloud/changelog#2025-04-23-talos-linux-v195-iso-now-available) on the Hetzner Cloud docs page.
I guess it's an expected fail?
```
commit         GPG Identity                 FAILED        openpgp: signature made by …
```
> docs: hetzner: add note about public iso

- internal/app/machined/pkg/controllers/network/platform_config.go
- internal/integration/api/platform.go
The bug was with incorrect condition: if `activeNetworkConfig` was ever set to non-nil value, it was stuck with this value forever, despite new network config being available with `networkConfig`.
In `talosctl dashboard` case, Talos `metal` platform always reports initial data (before META is available) which doesn't have any network config, but later on sends updates (if something updates META), so this bug leads to Talos being stuck with initial empty network config.
Fixes #10787
> fix: handle correctly changing platform network config

- internal/app/machined/pkg/controllers/runtime/unique_token.go
- internal/app/machined/pkg/controllers/runtime/unique_token_test.go
- internal/app/machined/pkg/runtime/v1alpha2/v1alpha2_controller.go
- pkg/machinery/config/config/siderolink.go
- pkg/machinery/config/schemas/config.schema.json
- pkg/machinery/config/types/siderolink/siderolink.go
- pkg/machinery/config/types/siderolink/siderolink_doc.go
- website/content/v1.10/reference/configuration/siderolink/siderolinkconfig.md
- website/content/v1.10/schemas/config.schema.json
Allow unique token to be specified in machine config, this way we can workaround a problem with META being non-persistend/wiped.
Fixes #10570
> feat: allow SideroLink unique token in machine config

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Fixes #10653
If the configuration was changed from non-encrypted to encrypted, Talos was failing in a bit mysterious way.
Changing from not encrypted to encrypted is not supported, but still we should fail more gracefully.
1. Don't be stuck in `diskSizeCheck`, Talos will be stuck in `mountEphemeralPartition` which is a bit more obvious.
2. Allow resetting non-ready volumes, as we don't need them to be ready, we just need to know the location.
> fix: handling of encryption type mismatch

- Dockerfile
There were missing util-linux libraries for e2fsprogs.
While at it, clean up static libraries from installer/imager containers to make them even smaller.
Fixes #10814
> fix: disk image generation with image cache

- cmd/talosctl/cmd/mgmt/cluster/cluster.go
- cmd/talosctl/cmd/mgmt/cluster/create/create.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_linux.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_other.go
- cmd/talosctl/cmd/mgmt/cluster/destroy.go
- cmd/talosctl/cmd/mgmt/cluster/show.go
- cmd/talosctl/cmd/root.go
- pkg/provision/providers/factory.go
Part of #10289
This is the first change in the cluster create command refactor project. The changes will be split into small parts to make review and catching bugs easier.
The command has to be imported in cmd/root.go because it can't be referenced in the mgmt/cluster package as that would create a cyclic import.
This can be fixed later by separating the logic between a third package.
I split this into two commits so the diff is easier to review. Please see 8b2b46a63e32f7ebe8c11b39aab60ec77d153f5b for the logic changes.
> split the `cluster create` command into it's own package

- pkg/provision/providers/qemu/arch.go
- pkg/provision/providers/qemu/arch_darwin.go
- pkg/provision/providers/qemu/arch_linux.go
- pkg/provision/providers/qemu/create.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/qemu/preflight.go
- pkg/provision/providers/qemu/preflight_darwin.go
- pkg/provision/providers/qemu/preflight_linux.go
* split platform specific preflight checks into platform specific files
* error on darwin if target is amd64
* error on darwin if host platform is amd64
* add darwin specific var-file and pflash file locations
* remove hard kvm requirement (so linux logic can be tested on machines without kvm)
> chore: cross platform qemu preflight checks

- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
As the backoff variable was initialized in each iteration, it means short retries without any limit if `needsReconcile` is true.
Part of #10845
> fix: do correct backoff for nocloud reconcile

- cmd/talosctl/cmd/mgmt/cluster/create/command.go
- cmd/talosctl/cmd/mgmt/cluster/create/create.go
part of #10289
chore: split options between three structs
This is the first step in dividing the provider specific logic from the common operations that need to be performed for all providers.
With this change it's much easier to tell which logic is qemu or docker specific, and which is common.
This also removes the use of package wide variables that are hard to keep track of.
This pr is in three commits to make it easier to review. I recommend going commit-by-commit
> chore: split cluster create command options

- .github/workflows/ci.yaml
- .github/workflows/integration-misc-2-cron.yaml
- .kres.yaml
- cmd/talosctl/cmd/mgmt/cluster/create/command.go
- cmd/talosctl/cmd/mgmt/cluster/create/create.go
- hack/test/e2e-qemu.sh
- internal/pkg/rng/tpm.go
- internal/pkg/secureboot/tpm2/pcr.go
- pkg/provision/options.go
- pkg/provision/providers/qemu/destroy.go
- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/node.go
- pkg/provision/providers/qemu/preflight_linux.go
- pkg/provision/providers/qemu/tpm2.go
- pkg/provision/result.go
- website/content/v1.11/reference/cli.md
When extending PCR or trying to seed entropy pool from TPM if the found device is a TPM1.2 device, skip it, since Talos only supports TPM2.0
Fixes: #10847
> fix: skip PCR extension if TPM1.2 is found

- cmd/talosctl/cmd/mgmt/cluster/create/create.go
This is a recently introduced regression during the refactoring - the downloaded asset URLs were set on the copy struct instead of the original one, causing the command to pass the URL as-is to qemu, resulting in QEMU failing to find the kernel to boot.
> fix: replace downloaded asset paths correctly in cluster create cmd

- internal/app/machined/pkg/controllers/network/platform_config.go
- internal/app/machined/pkg/controllers/network/platform_config_test.go
- internal/app/machined/pkg/runtime/platform.go
- internal/app/machined/pkg/runtime/platform_test.go
Fixes #10845
See also #10865
If the platform code emits duplicate network configuration, we don't need to trigger the code which mounts STATE and saves new platform configuration.
> fix: suppress duplicate platform config updates

- internal/pkg/configuration/configuration.go
Use correct error assertion.
Fixes #10883
> fix: interactive installer config gen

- internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go
- internal/integration/api/apply-config.go
In maintenance mode, we still accept any config.
Fixes #10897
As "normal" mode requires v1alpha1 config today, it should be an easy fix to require it part of the applied config always.
> fix: deny apply config requests without v1alpha1 in "normal" mode

- website/layouts/partials/hooks/body-end.html
Because talos.dev doesn't have a version of any kind in the URL (i.e. talos.dev/v1.9/xxx), the `currentVersion` gets set to "404" when we try to grab the index after splitting. This PR should work around that, but we should find a better function to use later.
> docs: fix search on base talos.dev

- pkg/provision/providers/vm/loadbalancer.go
- pkg/provision/providers/vm/loadbalancer_darwin.go
- pkg/provision/providers/vm/loadbalancer_linux.go
part of https://github.com/siderolabs/talos/issues/10537
The loadbalancer is bound to all interfaces on macos. The bridge interface address is not used as the bridge is not yet created at this stage. Multiple loadbalancers can be assigned via different ports.
> chore: make qemu lb address bind work on darwin

- internal/app/machined/pkg/automaton/blockautomaton/volume_mount.go
- internal/app/machined/pkg/automaton/blockautomaton/volume_mount_test.go
- internal/app/machined/pkg/controllers/config/acquire_test.go
- internal/app/machined/pkg/controllers/network/platform_config_test.go
Fixes #10846
This change would have prevented the seriousness of the issue (riding into the buffer overrun) by "slowing down" the volume mount operations.
Without this change, an automaton can (depending on the execution flow) in quick succession lock to the `VolumeMountStatus` which was created matching previous `VolumeMountRequest`:
* destroy `VolumeMountRequest` - other controller don't have a chance to run yet
* automaton restarts
* create `VolumeMountRequest`
* put a finalizer to `VolumeMountStatus`, but this instance of the status corresponds to the previously destroyed `VolumeMountRequest`, not the new one created
There is no technical problem with the way automaton worked - it just runs "too quickly" skipping the volume mount/unmount operation, and simply not letting the volume to …
> fix: improve volume mounter automaton

- go.mod
- go.sum
See https://github.com/siderolabs/go-kubernetes/pull/31
Fixes #10979
> fix: upgrade go-kubernetes for DRA flag bug

- internal/app/machined/pkg/system/runner/process/process.go
- internal/app/machined/pkg/system/runner/process/process_test.go
This is a follow-up fix for the PR
https://github.com/siderolabs/talos/pull/10964: there was one more case when the copying to the log was not synchronized with process stop - a log writer could be have been closed before process termination.
While looking into this, I figured out we don't need to close anything after process termination, as `pw` can be closed after the process start (Talos doesn't write there, only the child does), removing one more hook.
Also renamed some variables for clarity.
> test: fix the process runner log collection

- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/launch_darwin.go
- pkg/provision/providers/qemu/launch_linux.go
* rename `config.vmMAC` -> `config.VMMAC` so it can be marshaled and passed to the launch process
* implement withNetworkContext which just runs the function on the host network on darwin
> chore: dump qemu pachine ipam records on darwin

- hack/cloud-image-uploader/go.mod
- hack/cloud-image-uploader/go.sum
Previous update brought new dependency which also has vulnerabilities that Dependabot thinks is important (it's not), but let's bump once again.
> chore: update cloud-image-uploader dependencies

- website/content/v1.10/talos-guides/upgrading-talos.md
- website/content/v1.11/talos-guides/upgrading-talos.md
remove leftover of the `preserve` flag in the documentation. cf issue https://github.com/siderolabs/talos/issues/10172
> docs: remove `preserve` flag mention in upgrade notes

- internal/app/machined/pkg/controllers/runtime/events_sink.go
- internal/app/machined/pkg/controllers/siderolink/manager.go
- internal/pkg/encryption/keys/kms.go
- pkg/grpc/middleware/auth/basic/basic.go
- pkg/grpc/proxy/backend/local.go
Use a dialer which picks up environment settings on the fly, which should allow consistent results when setting environment variables to control the proxy.
Fixes #10990
There was a race between the first gRPC dial and the moment environment variables are applied - as gRPC by default reads the environment variables just once, it might read incomplete state.
> fix: consistently apply dynamic grpc proxy dialer

- hack/udevd/99-default.link
- internal/integration/api/ethernet.go
Linux kernel has the following policy:
* initial bridge MAC is random
* if the bridge MAC is not set explicitly by userspace, bridge MAC is the smallest MAC address of all ports
But systemd-udevd which we use started to assign "stable" MACs to bridge interfaces (when they are created), which Linux kernel treats as userspace explicitly set, so the bridge no longer gets an automatic MAC of the ports.
This is a breaking change, so we need to revert it.
Fixes #10884
Fixes #11011
> fix: disable automatic MAC assignment to bridge interfaces

- pkg/provision/providers/vm/dhcpd.go
- pkg/provision/providers/vm/internal/ethtool/ethtool_linux.go
- pkg/provision/providers/vm/internal/ethtool/ethtool_other.go
The fix is based on the https://github.com/kubevirt/kubevirt/pull/1766, and for the background see
https://github.com/gregoryolsen/lxc-devuan/issues/1.
Note this is not an issue in Talos itself, but only for QEMU VMs created with `talosctl cluster create`.
> test: fix DHCP unicast failures in QEMU environment

- website/content/v1.10/talos-guides/install/local-platforms/virtualbox.md
- website/content/v1.11/talos-guides/install/local-platforms/virtualbox.md
This PR formats the documentation for better workflow for setting up Talos cluster with VirtualBox. It ensures that the user bootstraps the Etcd and highlights that it must be done before the cluster is ready.
The PR also adds a few helper command examples to ensure a newbie user (like me) is able to bootstrap a cluster based on this guide only.
A newbie user like me was not able to fully bootstrap a cluster. I had some errors that I thought was related to misconfiguration (control-plane node was stuck in Booting for example). Turns out I just had to initialize the Etcd for the cluster to become healthy. Hopefully this change improves the workflow to better highlight whats needs to be completed in-order to use the cluster.
> See `make help` for a …
> Update virtualbox.md - better workflow

- internal/integration/api/apid.go
- pkg/machinery/constants/constants.go
Fixes #11046
Test up to the maximum gRPC message size as we support.
> fix: bump apid memory limit

- pkg/provision/providers/qemu/launch.go
- pkg/provision/providers/qemu/launch_darwin.go
- pkg/provision/providers/qemu/launch_linux.go
- pkg/provision/providers/qemu/node.go
* split the networking config into common and platform specific structs
* add logic to get the config file server for darwin
* generate a random mac address for the darwin qemu machines
* generate the darwin specific `-netdev` qemu params
With this change the qemu machines are successfully started, but DHCPd is still todo, so they get wrong IPs assigned.
example of the generated netdev params:
`-netdev vmnet-shared,id=net0,start-address=10.5.0.1,end-address=10.5.0.3,subnet-mask=255.255.255.0 -device virtio-net-pci,netdev=net0,mac=7e:96:ad:7c:0a:71 `
part of #10537
> chore: add vmnet support (darwin/qemu)

- pkg/provision/providers/qemu/create.go
- pkg/provision/providers/vm/dhcpd.go
- pkg/provision/providers/vm/dhcpd_darwin.go
- pkg/provision/providers/vm/dhcpd_linux.go
add usage of our in-house dhcpd server instead of apple's bootpd
part of #10537 
There's stuff to be ironed out, but with this change basic cluster creation should work on darwin as well.
> chore: use custom dhcpd server on macos qemu

- Makefile
Make `$(ARTIFACTS)` a target so other steps can easily depend on it, in case of reproducibility test the folder is created first having proper permissions as `local-` targets create `$(ARTIFACTS)` with root user.
> fix(ci): reproducibility test

- website/content/v1.10/kubernetes-guides/network/deploying-cilium.md
- website/content/v1.11/kubernetes-guides/network/deploying-cilium.md
Replace the cilium-cli-ci  image repo used for CI builds with the recently added cilium-cli image repo intended for tagged releases.
The cilium/cilium-cli-ci image is used for CI and is built and pushed on PR branches so breaking changes, bugs, and potential risks are more likely.
**_Disclaimer_**: I'm not a cilium maintainer or contributor, but found https://github.com/cilium/cilium-cli/issues/2755 where the cilium-cli repo was proposed, and https://github.com/cilium/cilium-cli/pull/2980 where the image push workflow was updated.
> docs: use the cilium-cli image repo in the job installation manifest

- hack/release.toml
On MacOS `talosctl cluster create` command now supports the Qemu provisioner in addition to the Docker provisioner.
I'm still working on the [developing talos](https://www.talos.dev/v1.11/advanced/developing-talos/) docs but I guess we can close #10537 as done?
> feat: support qemu provisioner on darwin

- cmd/talosctl/cmd/talos/dashboard.go
- website/content/v1.11/reference/cli.md
Ensure the --help output is human readable.
This fixes #11130 
After running make docs, I'm seeing a changed file: `website/content/v1.11/reference/cli.md`, but I guess the HTML encoding was here in the first place for the docs? Should I also commit this? I've not checked the file in (yet).
```
diff --git a/website/content/v1.11/reference/cli.md b/website/content/v1.11/reference/cli.md
index 818872f9f..d50b3b70a 100644
--- a/website/content/v1.11/reference/cli.md
+++ b/website/content/v1.11/reference/cli.md
@@ -843,14 +843,14 @@ Provide a text-based UI to navigate node overview, logs and real-time metrics.
Keyboard shortcuts:
- - h, &lt;Left&gt; - switch one node to the left
- - l, …
```
> fix(talosctl): correct --help output for dashboard command

- go.mod
- go.sum
- pkg/machinery/go.mod
- pkg/machinery/go.sum
See:
* https://github.com/grpc/grpc-go/releases/tag/v1.71.2
* https://github.com/grpc/grpc-go/releases/tag/v1.71.3
I believe these surface in an unexpected way in `talosctl` when used with proxy environment variables.
This is a direct commit to `release-1.10`, main should be just updated to the latest version.
> fix: upgrade grpc library to the latest 1.71.x

- internal/app/machined/pkg/controllers/block/volume_config_test.go
- pkg/machinery/resources/block/volume_config.go
- pkg/machinery/resources/files/etcfile_spec.go
- pkg/machinery/yamlutils/yamlutils.go
- pkg/machinery/yamlutils/yamlutils_test.go
This fixes a long-time problem with some fields represented as `[]byte` appearing in the resource output as a list of bytes, something like:
```yaml
- 91
- 23
...
```
Instead, new output adapts to the actual contents:
```yaml
node: 172.20.0.2
metadata:
namespace: files
type: EtcFileSpecs.files.talos.dev
id: cri/conf.d/cri.toml
version: 2
owner: files.CRIConfigPartsController
phase: running
created: 2025-06-03T13:29:23Z
updated: 2025-06-03T13:29:23Z
annotations:
talos.dev/source-file:/etc/cri/conf.d/00-base.part: 44a0319b6822a63d58368126431c891c3050a6e1b41d6450e96d767e547a1535
talos.dev/source-file:/etc/cri/conf.d/01-registries.part: 511b276fe57eddede973f1765da85a816e15e57d188699ab220380052299fe18
talos.dev/source-file:/etc/cri/conf.d/20-customization.part: …
```
> fix: marshal resource byte slices as strings in YAML

- internal/app/machined/pkg/controllers/block/internal/volumes/close.go
Wrong name was used to close encrypted volumes, so that the close was no-op.
> fix: correctl close encrypted volumes

- pkg/machinery/imager/quirks/quirks.go
All other quirks had proper checks, just this one was missing sa nil check.
> fix: nil pointer deref in quirk

- pkg/machinery/config/encoder/markdown.go
- website/assets/scss/_styles_project.scss
- website/content/v1.11/reference/configuration/block/swapvolumeconfig.md
- website/content/v1.11/reference/configuration/block/uservolumeconfig.md
- website/content/v1.11/reference/configuration/block/volumeconfig.md
- website/content/v1.11/reference/configuration/network/ethernetconfig.md
- website/content/v1.11/reference/configuration/network/kubespanendpointsconfig.md
- website/content/v1.11/reference/configuration/network/networkruleconfig.md
- website/content/v1.11/reference/configuration/runtime/kmsglogconfig.md
- website/content/v1.11/reference/configuration/runtime/watchdogtimerconfig.md
- website/content/v1.11/reference/configuration/security/trustedrootsconfig.md
- website/content/v1.11/reference/configuration/siderolink/siderolinkconfig.md
- website/content/v1.11/reference/configuration/v1alpha1/config.md
For field descriptions, don't collapse the description, as the "2nd" sentence contains very important information, and users tend to miss it.
> docs: expand documentation description

- hack/modules-amd64.txt
- hack/modules-arm64.txt
This PR pulls in siderolabs/pkgs#1245 to enable ib_umad and ib_uverbs as modules.
> chore: add user-space InfiniBand modules

- website/content/v1.10/advanced/kernel-module.md
- website/content/v1.11/advanced/kernel-module.md
Let me know if the steps are incorrect or could be shortened.
> docs: add docs for creating kernel modules

- hack/release.toml
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/azure.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/azure/testdata/expected.yaml
Azure documentation is very confusing, but the tests and the issues we observed show that 1400 is a more safe default than 1500, reducing packet fragmentation and timeouts.
See e.g. https://www.reddit.com/r/networking/comments/puowuy/do_anyone_know_the_default_tcp_mss_between_two/
> fix: set default MTU on Azure to 1400

- internal/pkg/containers/image/image.go
The containerd pull process might internally generate context canceled error while our "external" `ctx` is not canceled.
Don't treat context canceled as non-retriable, as `retry` package stops retrying when the outer `ctx` is canceled, so we don't need to handle it in any specific way.
> fix: treat context canceled as expected error on image pull

- internal/app/machined/pkg/system/services/etcd.go
Fixes #11257
This applies a fix from #6759 to recover code flow, which was missed in that PR.
> fix: etcd recover with multiple advertised addresses

- Makefile
New makefile target, which triggers registry build of a `talosctl-multiarch-bundle` Dockerfile target.
This target builds single image with all possible os/arch combinations of `talosctl`.
Fixes #11281
> feat: add talosctl mulitarch bundle image

- website/content/v1.10/talos-guides/configuration/logging.md
- website/content/v1.11/talos-guides/configuration/logging.md
Added example to enable HTTP server and listen port.
> docs: add example for fluentbit config

- .github/workflows/ci.yaml
- .kres.yaml
- Dockerfile
- Makefile
- hack/sbom.sh
- pkg/machinery/gendata/data/pkgs
Also generate multiple SBOMs for variants including different
sets of packages and different architectures.
Generated SBOMs (you can use this [web app](https://apps.rancher.io/sbom-viewer) to view them):
[talos-container-arm64.spdx.json](https://github.com/user-attachments/files/21107055/talos-container-arm64.spdx.json)
[talos-container-amd64.spdx.json](https://github.com/user-attachments/files/21107057/talos-container-amd64.spdx.json)
[talos-arm64.spdx.json](https://github.com/user-attachments/files/21107058/talos-arm64.spdx.json)
[talos-amd64.spdx.json](https://github.com/user-attachments/files/21107059/talos-amd64.spdx.json)
Scan: `grype sbom:talos-container-arm64.spdx.json`: `No vulnerabilities found`
Then patch with this to replace versions with known bad ones (only change format for …
> feat: include packages into SBOM

- api/resource/definitions/runtime/runtime.proto
- internal/app/machined/pkg/controllers/runtime/loaded_kernel_module.go
- internal/app/machined/pkg/controllers/runtime/loaded_kernel_module_test.go
- internal/integration/api/extensions_qemu.go
- pkg/machinery/api/resource/definitions/runtime/runtime.pb.go
- pkg/machinery/api/resource/definitions/runtime/runtime_vtproto.pb.go
- pkg/machinery/resources/runtime/loaded_kernel_module.go
- website/content/v1.11/reference/api.md
`ReferenceCount` is a more common name, so replacing `Instances` will provide better UX and will match online resources.
Additionally drop `Name` which is duplicated from ID.
> fix: rename instances to referenceCount

- hack/modules-amd64.txt
See https://github.com/siderolabs/pkgs/pull/1278
```
$ talosctl -n 172.20.0.5 get modules virtio_rng
NODE         NAMESPACE   TYPE                 ID           VERSION   STATE
172.20.0.5   runtime     LoadedKernelModule   virtio_rng   1         Live
```
> feat: include hwrandom modules

- cmd/talosctl/cmd/mgmt/cluster/create/command.go
Support TPM operations when developing on Mac.
`brew install swtpm` is all that is needed.
> feat(talosctl): support tpm operation on mac

- internal/pkg/dns/dns_test.go
Fixes #10853
I think the issue is that we do DNS client request to the DNS caching server, and expect the request to fail on client side, as caching server doesn't respond in time (as the server is waiting for a response).
Make sure we use a short timeout on our client side, so that we time out before a server does.
> test: fix flaky TestDNS

- internal/app/machined/pkg/controllers/network/address_merge_test.go
- internal/app/machined/pkg/controllers/network/hostname_merge_test.go
- internal/app/machined/pkg/controllers/network/link_merge_test.go
- internal/app/machined/pkg/controllers/network/operator_merge_test.go
- internal/app/machined/pkg/controllers/network/resolver_merge_test.go
- internal/app/machined/pkg/controllers/network/route_merge_test.go
- internal/app/machined/pkg/controllers/network/timeserver_merge_test.go
Use ctest suite, rtestutils assertions.
Simplifying code, making tests run faster and in parallel, and also reducing test flakiness.
> test: refactor various merge controller tests

- internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/efivars.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot.go
- internal/app/machined/pkg/runtime/v1alpha1/bootloader/sdboot/sdboot_test.go
- internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go
Fixes: #11343
Fixes: #11344
Also simplify the probing code since that only runs during `Upgrade`, `Kexec` or `Reboot`.
> fix: sd-boot kexec with disk images

- internal/app/machined/pkg/controllers/block/disks.go
- pkg/provision/providers/qemu/launch.go
Use `udev` helpers to try to extract serial information, in case it is missing. 
Fixes #11348
> fix: fill serial using helpers

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/k8s/endpoint.go
- internal/app/machined/pkg/controllers/k8s/manifest.go
- internal/app/machined/pkg/controllers/k8s/manifest_test.go
- internal/app/machined/pkg/controllers/k8s/templates.go
- internal/app/machined/pkg/controllers/k8s/templates/talos-nodes-rbac-template.yaml
- internal/app/machined/pkg/controllers/kubeaccess/endpoint.go
- internal/integration/api/serviceaccount.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
Remove deprecated core/v1.Endpoints in favor of discovery/v1.EndpointSlices.
Fixes #11322
> chore(machined): remove deprecated Endpoints

- cmd/talosctl/cmd/talos/image.go
It is used in the Talos API from Kubernetes access test.
> test: add talosctl:latest to the image cache

- website/content/v1.10/talos-guides/howto/workers-on-controlplane.md
- website/content/v1.11/talos-guides/howto/workers-on-controlplane.md
This pull request adds documentation on how to remove the `exclude-from-external-load-balancers` label from control plane nodes on the page about enabling workloads on control plane nodes.
According to https://github.com/siderolabs/talos/issues/8749, the label `exclude-from-external-load-balancers` is added to the machineconfig by default since machine config 1.8+.  However, when talos users want to enable workloads on controlplane nodes they will probably also want to be able to route to it when a load balancer is used. Therefore it would be beneficial to mention that the nodeLabel that is added by default and excludes control plane nodes from external load balancers should be removed.
> docs: add remark about 'exclude-from-external-load-balancers'

- website/content/v1.11/advanced/etcd-maintenance.md
Add new documentation page describing procedure of downgrading ETCD from `v3.6.x` to `v3.5.x`
> docs: add ETCD downgrade documentation

- go.mod
- go.sum
- internal/app/machined/pkg/controllers/cluster/discovery_service.go
See https://github.com/siderolabs/discovery-client/pull/19
This fixes a case when TrustedRoots are added while the discovery client is running, so that new trusted roots are picked up on reconnect.
> fix: live reload of TLS client config for discovery client

- internal/app/machined/pkg/system/service_runner.go
- internal/app/machined/pkg/system/volumes.go
The issue seems to be around still racy service restarts which leads to a potential hang on a conflicting state.
By not re-using the mount request IDs on each restart, hopefully we can improve on it.
> fix: one more attempt to fix volume mount race on restart

- internal/app/machined/pkg/controllers/block/encryption_meta.go
- internal/app/machined/pkg/controllers/block/encryption_meta_test.go
- internal/app/machined/pkg/controllers/block/volume_config.go
- internal/integration/provision/provision.go
- internal/integration/provision/upgrade.go
When upgrading from pre-1.11 versions of Talos, there was a failure on mismatch to unmarshal "old" encryption config into new structure.
Fix that by providing a proper fallback.
Add both unit-test verifying compatiblity, as well as a full integration upgrade test with encrypted disks.
Fixes #11502
> fix: unmarshal encryption STATE from META

- internal/pkg/logind/dbus.go
- internal/pkg/logind/logind.go
- internal/pkg/logind/service.go
It's a D-Bus client we use to communicate graceful shutdown with the kubelet.
Fixes #11300
> refactor: fix deadcode elimination with godbus

- Dockerfile
- Makefile
- tools/go.mod
- tools/go.sum
Assert that `machined` build does deadcode elimination.
Fixes #11296
> chore: add deadcode elimination linter

- website/content/v1.10/advanced/kernel-module.md
- website/content/v1.11/advanced/kernel-module.md
Fixed the git clone command for the `Adding a Kernel Module` section.
The old clone command would cause the `make rekres` step to fail with logs:
```
gen started
Error: failed to parse remote URL: origin	https://github.com/siderolabs/
```
With this change we now get:
```
gen started
GITHUB_TOKEN is missing, GitHub API integration is disabled
success
```
> docs: fix clone URL to include `.git`

- cmd/talosctl/cmd/talos/root.go
- cmd/talosctl/pkg/talos/global/client.go
- go.mod
- go.sum
- pkg/machinery/client/connection.go
- pkg/machinery/client/options.go
- pkg/machinery/constants/constants.go
- pkg/machinery/go.mod
- pkg/machinery/go.sum
- website/content/v1.11/learn-more/talosctl.md
- website/content/v1.11/reference/cli.md
- website/content/v1.12/learn-more/talosctl.md
- website/content/v1.12/reference/cli.md
Use key provider with fallback option for auth type SideroV1:
- Attempt to use $HOME/.talos/keys directory to read/remove existing PGP file if it exists or write new PGP file if directory is writable.
- Otherwise fallback to using $XDG_DATA_HOME/talos/keys directory.
- Add new talosctl flag --siderov1-key-dir (also configurable via SIDEROV1_KEYS_DIR env var) to allow customizing the directory to use for PGP keys
Update documentation to remove reference for $XDG_CONFIG_HOME for storing talosctl configuration, as it's not used anymore.
> feat: use key provider with fallback option for auth type SideroV1

- .github/workflows/ci.yaml
- .kres.yaml
Today `integration/aws` triggers all NVIDIA tests, so there is no way to run just AWS without NVIDIA.
> test: don't run nvidia tests on integration/aws

- cmd/talosctl/cmd/mgmt/cluster/create/cmd.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd_dev.go
- cmd/talosctl/cmd/mgmt/cluster/create/create.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_test.go
Make --with-uuid-hostnames flag functionality available to qemu provider on `talosctl cluster create`
> fix: make --with-uuid-hostnames functionality available to qemu provider

- .github/workflows/ci.yaml
- .github/workflows/integration-image-factory-cron.yaml
- .kres.yaml
- hack/test/e2e-image-factory.sh
The shell script expected `ipxe`, but we passed `pxe`, and it silently worked.
> test: fix the Image Factory PXE boot test

- cmd/talosctl/cmd/mgmt/cluster/cluster.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd_dev.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd_docker.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd_qemu.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
- cmd/talosctl/cmd/mgmt/cluster/destroy.go
- cmd/talosctl/cmd/mgmt/cluster/show.go
- website/content/v1.12/reference/cli.md
part of [#11404](https://github.com/siderolabs/talos/issues/11404)
I've split the changes into two commits for ease of review. Will squash before merging.
Stuff yet to do:
* extract more common logic and create a separate simplified code path for the this command (like already done for the docker command in [create_docker.go](https://github.com/siderolabs/talos/blob/main/cmd/talosctl/cmd/mgmt/cluster/create/create_docker.go))
* Change applicable e2e tests to use this command instead
* documentation updates (also need to update the docker docs)
> feat: add a user-facing create qemu command 

- internal/app/machined/pkg/controllers/network/dns_resolve_cache_test.go
- internal/app/machined/pkg/controllers/network/network_test.go
I believe it's a bug in the `suture` library itself, relevant code is:
https://github.com/thejerf/suture/blob/8a2561c661dce2a30c484b08e865676059c1e63e/supervisor.go#L779-L816
If the global context is canceled, nothing consumes from the notification channel, so the goroutine trying to send there will never have a chance to complete.
Also avoid parallel issues by moving goleak check into `TestMain`.
> test: ignore one leaking goroutine

- website/content/v1.10/_index.md
- website/content/v1.11/_index.md
- website/hugo.toml
See https://github.com/siderolabs/talos/issues/11574
> docs: activate Talos v1.11 docs by default

- cmd/talosctl/cmd/talos/cgroups.go
- cmd/talosctl/cmd/talos/cgroupsprinter/presets/psi.yaml
- cmd/talosctl/cmd/talos/cgroupsprinter/presets_test.go
- website/content/v1.12/advanced/cgroups-analysis.md
- website/content/v1.12/reference/cli.md
This flag helps debug in situations when containerd is responding slowly
Fixes #11587
> feat: add a cgroup preset for PSI and --skip-cri-resolve

- website/content/v1.10/kubernetes-guides/network/multus.md
- website/content/v1.11/kubernetes-guides/network/multus.md
- website/content/v1.12/kubernetes-guides/network/multus.md
the multus cni docs still mentions the install-cni image even though its no longer as useful
sorts #11047
> docs: clarify that install-cni image is deprecated

- cmd/talosctl/cmd/mgmt/cluster/create/create.go
If the config is not provided to the nodes skip bootstrapping the Talos cluster, otherwise the bootstrap will hand until timed out.
> fix: don't bootstrap talos cluster if there's no config present

- cmd/talosctl/cmd/mgmt/cluster/create/cmd.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd_dev.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd_docker.go
- cmd/talosctl/cmd/mgmt/cluster/create/cmd_qemu.go
- cmd/talosctl/cmd/mgmt/cluster/create/create.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_dev.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_docker.go
- cmd/talosctl/cmd/mgmt/cluster/create/create_qemu.go
Split common code between `create docker` and `create qemu` commands into a helper. The dev command stays as is due to big differences between the user oriented commands.
part of #11404
> refactor create cluster commands internal logic

- website/content/v1.10/talos-guides/install/single-board-computers/unofficial.md
- website/content/v1.11/talos-guides/install/single-board-computers/unofficial.md
- website/content/v1.12/talos-guides/install/single-board-computers/unofficial.md
Change links to PI5 unofficial repos
Factory was shut off with Pi5 support due to not wanting to play cat & mouse with changes. Repository was also moved to a different way as an talos-rpi5 GH organization.
> docs: Replace Raspberry Pi 5 links with Talos builder

- internal/integration/api/apply-config.go
- internal/integration/api/volumes.go
Fixes #11780
Couple of changes:
* clear connection refused before apply config with reboot (no-op CRI patch test)
* improve log output in volume tests
* drop locking in vgcreate, as it seems to conflict with background disk scans (by Talos or udevd)
> test: improve test stability

- pkg/machinery/client/config/path.go
Use correct order to determine SideroV1KeysDirPath:
* Use env variable `SIDEROV1_KEYS_DIR`
* If not set, use cli flag`--siderov1-keys-dir`
* If empty, use default dir `$HOME/.talos/keys`
> fix: use correct order to determine SideroV1 keys directory path

- pkg/machinery/config/types/block/raw_volume_config.go
- pkg/machinery/config/types/block/user_volume_config.go
- website/content/v1.11/talos-guides/configuration/disk-management/layout.md
- website/content/v1.11/talos-guides/configuration/disk-management/raw.md
- website/content/v1.11/talos-guides/configuration/disk-management/user.md
- website/content/v1.12/reference/configuration/block/rawvolumeconfig.md
- website/content/v1.12/reference/configuration/block/uservolumeconfig.md
- website/content/v1.12/talos-guides/configuration/disk-management/layout.md
- website/content/v1.12/talos-guides/configuration/disk-management/raw.md
- website/content/v1.12/talos-guides/configuration/disk-management/user.md
Ceph doesn't like name `ceph` in the partition labels.
See https://github.com/siderolabs/talos/issues/11778
> docs: remove 'ceph-data' from volume examples/docs

- Makefile
Pass in `GITHUB_TOKEN` to imager always.
> chore: pass in github token to imager

- internal/pkg/containers/image/resolver.go
When a registry has _some_ TLS config included, the refreshing CA pool was overwritten with the result returned from the config provider.
Ensure that is is restored back to the default value (unless explicitly set by the provider if the registry CA is set).
> fix: provide refreshing CA pool (resolvers)

- internal/app/machined/pkg/controllers/runtime/maintenance_service.go
- website/content/v1.12/talos-guides/configuration/editing-machine-configuration.md
- website/content/v1.12/talos-guides/configuration/patching.md
- website/content/v1.12/talos-guides/install/virtualized-platforms/vmware.md
Deprecate by removing the most visible references in the documentation/code, but still support both internally.
> docs: deprecate JSON6902 patches and interactive installer

- .github/workflows/ci.yaml
- .github/workflows/dispatch.yaml
- .kres.yaml
- hack/cloud-image-uploader/factory.go
- hack/cloud-image-uploader/main.go
- hack/cloud-image-uploader/options.go
Rather than building images manually, retrieve them from the image factory to guarantee that the correct base schematic is applied and that all required default extensions are consistently included.
Fixes #11454
> feat: release cloud image using factory

- internal/pkg/mount/v3/point.go
When RemountReadOnly was called on detached mount, it returned EINVAL.
This is not an expected behaviour.
> fix: stop returning EINVAL on remount of detached mounts

- cmd/talosctl/cmd/talos/image.go
- cmd/talosctl/pkg/talos/artifacts/arch.go
- cmd/talosctl/pkg/talos/artifacts/fetch.go
- cmd/talosctl/pkg/talos/artifacts/images.go
- cmd/talosctl/pkg/talos/helpers/flags.go
- internal/integration/cli/image.go
- pkg/images/images.go
- pkg/images/list.go
- website/content/v1.12/reference/cli.md
Add new command that takes Talos version (semver) and generates a list
of images that are used in Image Factory for building talos.
Fixes https://github.com/siderolabs/talos/issues/11927
> feat: generate list of images required to build talos

- internal/app/machined/pkg/controllers/block/mount.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/metal/metal.go
- internal/pkg/mount/v3/manager.go
- internal/pkg/mount/v3/point.go
- Do not create target dir for detached mounts;
- Use 'ro' flag on ReadOnly mount requests;
> fix: minor improvements to mounts

- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud.go
- internal/app/machined/pkg/runtime/v1alpha1/platform/nocloud/nocloud_test.go
Even if network config is missing, provide metadata always.
This way `PlatformMetadata` resource is properly populated, even if it just contains the platform information.
See https://github.com/siderolabs/omni/discussions/1633#discussioncomment-14577048
> fix: provide nocloud metadata with missing network config

- pkg/imager/ova/ova.go
This change adds the extra config `disk.EnableUIUD` to the generated OVA files. This flag is needed to be able to use VMware's CSI implementations.
Adds the `disk.EnableUUID` extra config flag to generated OVA files.
This flag is required for VMware CSI (Cloud Storage Interface) implementations to function properly. When enabled, it ensures that disk UUIDs are exposed to the guest OS, which is necessary for persistent volume management in Kubernetes on vSphere environments.
See [VMware documentation](https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html#:~:text=Virtual%20Machine%20Hardware%20requirements)
> feat: add disk.EnableUUID to generated ova

- website/content/v1.11/kubernetes-guides/network/deploying-calico.md
- website/content/v1.12/kubernetes-guides/network/deploying-calico.md
This PR adds Calico to the networking options supported by Talos.
Calico has a pluggable dataplane and allows users to choose between eBPF and NFtables. 
It also supports most recent Kubernetes Network Policy changes, and allows users to implement policies easier in their environments.
> docs: Add Project Calico to networking options
