initramfs/src/init/main.go
initramfs/src/init/pkg/process/process.go

feat(init): provide and endpoint for getting logs of running processes

---

initramfs/src/init/pkg/process/crio.go
rootfs/src/fsh.sh

Fixes #16. The `Missing CNI default network` error can be ignored. CRI-O should wait until the user installs a network to the cluster, instead of using a default network.

fix(init): address crio errors and warns

---

.conform.yaml
src/conformance/.conform.yaml
src/conformance/src/sonobuoy.yaml

We don't have CI in place yet, but this PR adds the build for the conformance image that we can run manually for now as part of the release process.
Note that we have to remove the `systemd_logs` plugin by editing the output of the `sonobuoy-config-cm` `ConfigMap` from `sonobuoy gen`.
Closes #102.

feat(conformance): add conformance image

---

src/image/src/entrypoint.sh

With `slub_debug=P` the following occurred when spinning up an EC2 instance with an AMI built from the Dianemo docker container:
```
2018/10/14 15:07:33.111170 main.go:44: initializing mount points
[   31.798655] XFS (xvda2): Mounting V5 Filesystem
[   31.831006] XFS (xvda2): Metadata CRC error detected at xfs_agi_read_verify+0xc6/0xf0, xfs_agi block 0x2 
[   31.839450] XFS (xvda2): Unmount and run xfs_repair
[   31.844043] XFS (xvda2): First 128 bytes of corrupted metadata buffer:
[   31.849937] 00000000fe7a10f8: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   31.857665] 00000000763e02ae: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   31.864996] 00000000885bf2eb: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   31.872928] …
```

fix(kernel): remove slub_debug kernel param

---

src/initramfs/.conform.yaml

CGO is required to use user.Current on Linux

fix(osctl): build Linux binary with CGO

---

src/initramfs/cmd/init/pkg/security/cis/cis.go
src/initramfs/cmd/init/pkg/system/services/kubeadm.go

Fixes an issue where the rendered encryptionconfig.yaml could contain invalid
base64 data.

fix(init): use text/template

---

src/initramfs/cmd/init/pkg/security/cis/cis.go

This is a temporary fix until Istio sidecar injection works with this plugin enabled.

fix: disable AlwaysPullImages admission plugin

---

src/image/src/packer.json

This is a touchy subject. The Linux community seems split on enabling this. As a security centric distro, I'm hesitant to enable this by default. Without this though, our users will experience painfully slow startup times.

feat(image): build AMI with random.trust_cpu=on

---

src/initramfs/cmd/init/pkg/system/services/crt.go

I'm seeing Kubernetes pod containers being killed if a memory limit is set on the container runtime:
```
~ # osctl dmesg
...
<6>[ 1205.517883] Task in /system/docker/kubepods/burstable/pod6687d6d7-fcae-11e8-b0b0-5e61144ba466/58f8a9bf6a469f0c94d42be34ad1bdff84fad63f236baedde981139a15aa5287 killed as a result of limit of /system/docker
...
```
And with a node using this PR, we can see the docker container using more than 2 GB of memory:
```
~ # osctl ps
ID        IMAGE                                                STATUS    MEMORY(MB)   CPU
blockd    docker.io/autonomy/blockd:317fa74-dirty              running   6.22         0
docker    docker.io/library/docker:18.06.1-ce-dind             running   12639.27     0
kubelet   gcr.io/google_containers/hyperkube:v1.13.0-alpha.3   running …
```

fix(init): no memory limit for container runtime

---

Dockerfile

Without CGO, on linux/amd64, we cannot lookup the current user.

fix(osctl): compile static binary with CGO enabeld

---

Dockerfile

Fixes an issue found by @bradbeam:
```
[    4.909748] [talos] [initramfs] Formatting Partition /dev/sda - ESP
Error loading sh[    4.917300] [talos] [initramfs] recovered from: exit status 127
[    4.917300] early boot failed
[    4.917300] main.main
[    4.917300]     /src/internal/app/init/main.go:257
[    4.917300] runtime.main
[    4.917300]     /toolchain/usr/local/go/src/runtime/proc.go:201
[    4.917300] runtime.goexit
[    4.917300]     /toolchain/usr/local/go/src/runtime/asm_amd64.s:1333
ared library lib[    4.952803] [talos] [initramfs] rebooting in 10 seconds
blkid.so.1: No such file or directory (needed by /sbin/mkfs.xfs)
Error relocating /sbin/mkfs.xfs: blkid_new_probe_from_filename: symbol not found
Error relocating …
```

fix: add libblkid to the rootfs

---

Dockerfile

chore: upgrade golangci-lint to v1.14.0

---

internal/app/init/main.go
internal/app/init/pkg/system/services/kubeadm.go

Stuff I fixed last night but forgot to push. Just a couple of small changes. Want to make sure we're at least showing a message if userdata fetch fails (#386). The returned error in the check didn't actually output a message along the way. 
Also want to ignore number of cpus in kubeadm so we can do some testing on small instances to save dolla dolla bills, y'all.

fix: output userdata fails, ignore numcpu for kubeadm

---

hack/installer/packer.json

This PR move the AWS EC2 instance type from `t2.small` to `t2.micro`.
`t2.micro` is free under AWS free tier and cheaper than `t2.small`.
I've tested that the build on a `t2.micro` work and doesn't slow down the build at all.

feat: change AWS instance type to t2.micro

---

internal/app/osctl/cmd/routes.go
internal/app/osctl/internal/client/client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

Just makes it easier to see how the routing table is setup on talos nodes.

feat: add route printing to osctl

---

Makefile

Changing assignment of the following from `:=` to `=`:
- `SHA`
- `TAG`
- `BUILT`
- `PUSH`
Additionally, changing `COMMON_ARGS` as well, because the two last assignments depend on `SHA` and `TAG` and will force them to assign a variable value too early (i.e., before the dependency `gitmeta` has been installed).
This fixes the `make: gitmeta: Command not found` error that occurs before all dependencies are installed.
See http://www.gnu.org/software/make/manual/make.html#Flavors

Delay `gitmeta` execution in Makefile

---

docs/categories/index.html
docs/components/blockd/index.html
docs/components/index.html
docs/components/init/index.html
docs/components/kernel/index.html
docs/components/kubeadm/index.html
docs/components/osctl/index.html
docs/components/osd/index.html
docs/components/proxyd/index.html
docs/components/trustd/index.html
docs/configuration/index.html
docs/configuration/masters/index.html
docs/configuration/osd/index.html
docs/configuration/workers/index.html
docs/examples/aws/index.html
docs/examples/gcloud/index.html
docs/examples/index.html
docs/examples/kvm/index.html
docs/examples/xen/index.html
docs/index.html
docs/tags/index.html
docs/talos/index.html
web/themes/autonomy/layouts/_default/list.html
web/themes/autonomy/layouts/_default/single.html
web/themes/autonomy/layouts/index.html
web/themes/autonomy/layouts/partials/footer.html
web/themes/autonomy/layouts/partials/head.html

Signed-off-by: Tommy Nguyen <remyabel@gmail.com>
All documents need `<html>` tags. Also, the rest of the page needs to be wrapped in `<body>` which was in the wrong location.

docs: properly wrap layouts in html/body tags

---

internal/pkg/crypto/x509/x509.go
internal/pkg/grpc/gen/gen.go

allows talos config to use hostnames as targets and releases
the need for static IPs for master nodes.
fixes issue #403
Signed-off-by: Tim Jones <timniverse@gmail.com>

feat: add hostname to node certificate SAN

---

go.mod
internal/pkg/kernel/kernel.go
internal/pkg/kernel/kernel_test.go

First Go test added to the package, tests are based
on stretchr/testify, I feel it provides enough goodies
to use it instead of stdlib `testing` package, but
please let me know if it works. It makes sense to use
same testing framework for the whole codebase.
Kernel boot time params parsing was improved to handle
consecutive spaces and params without value.

test: add kernel pkg tests, improve parsing

---

Dockerfile
Makefile

fixes: #373
Toolchain image updated to the latest version (see PR
autonomy/toolchain-musl#5).
This drops dependency on `gcompat` which was causing issues on Linux
4.17+ and pre-built Go binaries are imported from official
`golang:XXX-alpine` image.

feat: update gcc to 8.3.0, drop gcompat

---

internal/app/osctl/cmd/dmesg.go
internal/app/osctl/cmd/logs.go
internal/app/osctl/cmd/ps.go
internal/app/osctl/cmd/reboot.go
internal/app/osctl/cmd/reset.go
internal/app/osctl/cmd/root.go
internal/app/osctl/cmd/routes.go
internal/app/osctl/cmd/stats.go
internal/app/osctl/internal/client/client.go

closes #434 
Adds a `--target` (shorthand `-t`) to the command that communicate with nodes so direct the command at that node temporarily. Does not affect on-disk config.

feat: add arg to target nodes per command

---

internal/app/init/pkg/system/services/kubeadm.go
internal/pkg/userdata/userdata.go

This introduces a new option in the trustd configuration. The field `next` was added to indicate to a master which node to send the PKI to.

fix: join masters in serial

---

Dockerfile
Makefile
dev/.gitignore
dev/Makefile
dev/config/.base.node.yaml
dev/docker-compose.yaml
dev/os-release
internal/app/init/pkg/system/services/kubeadm.go
internal/pkg/userdata/userdata.go
internal/pkg/userdata/userdata_test.go

UX:
```bash
make osctl-darwin-amd64 osctl-linux-amd64
make docker-os
cd dev/
make config
make
make os-clean
make clean
```
`docker-compose` is used to setup the container.
Logs are mounted to files inside of the dev/ dir.
Kubeadm is configured /w ExtraArgs to ignore swap and a problematic
sysctl.
The kubelet is configured /w kubeadm's `KubeletConfiguration` to ignore
swap.
The docker-os rootfs implements a workaround where:
- the `/etc -> /var/etc` symlink is removed
- `/var/etc/` is moved to `/etc/`
- a `/var/etc -> /etc` symlink is created
This workaround allows docker to create files in the `/etc` directory
without impairing the functionality of the filesystem. (If we leave /etc
as a symlink, docker will create a directory over it)

Add docker-os build-target, Kubeadm.ExtraArgs, and a dev Makefile

---

Dockerfile
Makefile

This depends on autonomy/toolchain-musl#7.
Instead of "stealing" Go compiler from `golang` official Docker image,
use Go already baked into our toolchain image.

chore(tools): use Go compiler from toolchain image

---

internal/app/osctl/cmd/gen.go
internal/app/osctl/internal/helpers/cli.go
internal/app/osctl/internal/helpers/should.go

For any error which should be reported back to the user,
`helpers.Fatalf` is being used which prints message to
stderr and aborts with error.
Errors which can only happen during development,
`helpers.Should` is used to produce enough context.

chore: improve error reporting in osctl cli

---

.conform.yaml
.gitignore
Dockerfile
Makefile

This relies on new toolchain image from autonomy/toolchain-musl#9 to
provide `protoc` and `protoc-gen-go`.
New make target `proto` exports generated `.pb.go` files to the working
directory, so that Go source can is buildable which is really nice for
the editors to provide linting, to run the tests in local mode, etc.

chore: use protobuf compiler from the toolchain image

---

hack/dev/userdata/.master-1.tpl.yaml
hack/dev/userdata/.master-2.tpl.yaml
hack/dev/userdata/.master-3.tpl.yaml
hack/dev/userdata/.worker.tpl.yaml
internal/app/init/pkg/system/services/kubeadm.go
internal/pkg/userdata/userdata.go

This allows to merge core ignore list and any user overrides
applied on top of it.
I've added yet another default ignore for docker-compose environment:
`SystemVerification` which fails for me while trying to verify config of
the Linux kernel.

chore: split ignorePreflightErrors as settings on its own

---

hack/dev/Makefile
hack/dev/docker-compose.yaml
hack/dev/userdata/.master-1.tpl.yaml
hack/dev/userdata/.master-2.tpl.yaml
hack/dev/userdata/.master-3.tpl.yaml

* Provides certificate_key (k8s 1.14)
* Fixes local address of master-1, without the fix
it gets default 192.168.x.x assigned when k8s config is updated

chore: fixes for talos in docker-compose environment

---

hack/dev/Makefile
hack/dev/README.md
hack/dev/docker-compose.yaml
hack/dev/kubectl.sh
hack/dev/osctl.sh

I think docker-compose doesn't quite work for such use-case, as all we
need is to launch some script on docker network.
osctl runs from host just fine, but I left `docker run` to support
people on OS X where docker networks are not routable by default from
the host.

chore: take osctl/kubectl out of docker-compose

---

.gitignore
Dockerfile
Makefile
hack/golang/test.sh

Since some recent Go version `go test` is able to collect coverage info
across packages, so hacks are no longer required.
With simple addition to .travis.yaml and codecov.io setup, we can enable
code coverage via:
```
after_success:
- bash <(curl -s https://codecov.io/bash)
```
When tests run, coverage.txt is copied back to the working directory.

chore: export coverage info from unit-tests

---

internal/app/init/pkg/system/runner/process/log/log.go
internal/app/init/pkg/system/runner/process/process.go
internal/app/init/pkg/system/runner/process/process_test.go
internal/app/init/pkg/system/runner/runner.go
internal/app/init/pkg/system/services/containerd.go
internal/app/init/pkg/system/services/udevd.go

This is just first step towards better control of the services. Service
eventually uses either Process or Containerd runners to launch the
program. We don't have a way to control the service (stop it, figure out
whether it's actually running) unless we can pass back Runner instance
from the Service.
The idea is to return interface `runner.Runner` from the `Service` so
that controller (`init`) can figure out current state of the running
services and stop them on shutdown.
I haven't touched containerd runner yet (and as interface is not
enforced, code compiles fine). Only process runner is updated to allow
process to be stopped (either when it's running or while waiting to be
restarted).
For the sake of unit-tests, some additional runner options were exposed:
log path, restart interval, …

chore: rework process runner, add tests and stop method

---

internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go

This fixes "name not resolved" errors for kubelet in docker-compose env,
but I'm not sure how it might affect other platforms.

chore: provide /etc/resolv.conf to kubelet & kubeadm

---

Dockerfile
go.mod

There are two changes:
1. `go list` verifies that `go.mod` & `go.sum` are complete and fails if
they're not.
2. `go mod download` runs with just `go.mod`, so if we change Go
sources, time-consuming `go mod download` is not triggered anymore.
Added missing dependency to `go.mod` to make the check pass.

chore: enforce go.mod completeness and better buildkit cache

---

.conform.yaml
.gitignore
Makefile

This allows buildkitd cache to be reused when buildkitd container is
restarted. In CI, this directory could be shared between the builds to
speed them up.
Depends on new conform (https://github.com/talos-systems/conform/pull/121)
to skip `.builkit/` directory as it contains root-owned files which are
not readable.

chore: keep buildkitd cache as local volume

---

.gitignore
Dockerfile
Makefile
hack/golang/test.sh

There are two changes which are not directly related to each other:
* `base` target in Dockerfile was split into `base` without our Go
sources and `base-src` with our Go sources; this enables stuff which
depends on `base` only to use cache when Go sources are changed, so less
stuff to rebuild when only Go sources are changed
* tests are run in docker container in privileged mode, this is required
for upcoming tests for containerd runner; containerd is started during
the test run, containers are run in containerd

chore: split 'base' target, run tests in docker container

---

Makefile

This is a shortcut when working on changes in Go code to re-run Go tests
quickly without even trying to rebuild `test` container.
This target doesn't do any checks, it is assumed that `make test` was
run to create initial image of the `test` container. As Go sources are
mapped into the container, it picks up any changes made.

chore: add dev-test make target to quickly re-run unit-tests

---

.drone.yml
Dockerfile
Makefile
internal/app/init/pkg/system/runner/containerd/containerd.go
internal/app/init/pkg/system/runner/containerd/containerd_test.go
internal/app/init/pkg/system/runner/containerd/opts.go
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/ntpd.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go
internal/app/osd/internal/reg/reg.go

This is continuing work from PR #506.
Containerd runner is reworked to support `Run()` and `Stop()` methods
of `runner.Runner` interface.
Control on restarts is moved to our code (instead of 'restart'
containerd plugin), this allows to implement correct `Stop()` method
which stops restarting containers.
Container stop is now graceful - with SIGTERM, timeout followed by
SIGKILL.

chore: containerd runner refactoring and unit-tests

---

internal/app/osd/internal/reg/containerd.go
internal/app/osd/internal/reg/reg.go

```
root@f417a2d23378:/# osctl ps                                                                                                                                                           
NAMESPACE   ID       IMAGE          PID   STATUS
system      ntpd     talos/ntpd     84    RUNNING
system      osd      talos/osd      120   RUNNING
system      proxyd   talos/proxyd   493   RUNNING
system      trustd   talos/trustd   103   RUNNING
root@f417a2d23378:/# osctl ps -k
NAMESPACE   ID                                             IMAGE                                                                     PID   STATUS
k8s.io      kube-system/kube-scheduler-master-2            sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e   666   RUNNING
k8s.io …
```

fix(osd): Fix osctl ps output

---

internal/app/init/pkg/system/runner/containerd/containerd.go
internal/app/init/pkg/system/runner/containerd/containerd_test.go
internal/app/init/pkg/system/runner/containerd/import.go
internal/app/init/pkg/system/services/containerd.go
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/osd.go
internal/app/osd/internal/reg/containerd.go
internal/app/osd/internal/reg/reg.go
internal/pkg/constants/constants.go

A few additional minor fixes
- fixed up k8s.io ps output ( shows container name along with image name ); this was due to an issue with containerd listing the same image multiple times ( one for pretty name, one for she )
- made containerdAddress a constant based on containerd.defaults.defaultaddress. this is to allow a single place for us to change this ( and my failed attempts at making it listen on a tcp socket )
The logs are read off as a file the same way as system namespaced containers, it's just some juggling around how to identify the file location. This is based on the infra pod ( pause container ) labels since it is the first pod to create the sandbox with, along with the application pod container name. Kind of a clunky experience trying to hack through these, but it gets us …

 fix(osd): Fix k8s.io namespace logs

---

internal/app/init/pkg/system/runner/containerd/containerd.go
internal/app/init/pkg/system/runner/containerd/containerd_test.go
internal/app/init/pkg/system/runner/process/process.go
internal/app/init/pkg/system/runner/process/process_test.go
internal/app/init/pkg/system/runner/restart/restart.go
internal/app/init/pkg/system/runner/restart/restart_test.go
internal/app/init/pkg/system/runner/runner.go
internal/app/init/pkg/system/services/containerd.go
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/ntpd.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go
internal/app/init/pkg/system/services/udevd.go
internal/app/init/pkg/system/system.go
internal/app/osd/internal/reg/reg.go

This changes `runner.Runner` API to support more methods to allow for
containerd runner to create container object only once, and start/stop
tasks to implement restarts.
New API: `Open()` (initialize), `Run()` (run once until exits), `Stop()`
(stop running instance), `Close()` (free resource, no longer available
for new `Run()`).
So the sequence might be: `Open`, `Run`, `Stop`, `Run`, `Stop`, `Close`.
Process and containerd runners were updated for the new API, and
'restart' part was removed, now both runners only run the task once.
Restart piece was implemented in an abstract way for any wrapped
`runner.Runner` in the `runner/restart` package. Restart supports three
restart policies: `Once`, `UntilSuccess` and `Forever`.
Service API was changed slightly to return the `runner.Runner` …

refactor: extract 'restart' piece of the runners into wrapper runner

---

.drone.yml
.gitignore
Makefile

Make use of local bin directory so we can prevent the
need for sudo to install buildctl.

chore(ci): Update buildkit to 0.4

---

internal/app/init/main.go
internal/app/init/pkg/system/conditions/conditions.go
internal/app/init/pkg/system/conditions/conditions_test.go
internal/app/init/pkg/system/events/events.go
internal/app/init/pkg/system/events/events_test.go
internal/app/init/pkg/system/mocks_test.go
internal/app/init/pkg/system/runner/containerd/containerd.go
internal/app/init/pkg/system/runner/containerd/containerd_test.go
internal/app/init/pkg/system/runner/containerd/import.go
internal/app/init/pkg/system/runner/process/process.go
internal/app/init/pkg/system/runner/process/process_test.go
internal/app/init/pkg/system/runner/restart/restart.go
internal/app/init/pkg/system/runner/restart/restart_test.go
internal/app/init/pkg/system/runner/runner.go
internal/app/init/pkg/system/service_runner.go
internal/app/init/pkg/system/service_runner_test.go
internal/app/init/pkg/system/system.go
internal/app/init/pkg/system/system_test.go
internal/app/init/shutdown.go
internal/app/osd/internal/reg/reg.go

Most crucial changes in `init/main.go`: on shutdown now Talos tries
to stop gracefully all the services. All the shutdown paths are unified,
including poweroff, reboot and panic handling on startup.
While I was at it, I also fixed bug with containers failing to start
when old snapshot is still around.
Service lifecycle is wrapped with `ServiceRunner` object now which
handles state transitions and captures events related to state changes.
Every change goes to the log as well.
There's no way to capture service state yet, but that is planned to be
implemented as RPC API for `init` which is exposed via `osd` to `osctl`.
Future steps:
1. Implement service dependencies for correct startup order and
shutdown order.
2. Implement service health, so that we can say "start trustd when
containerd is …

feat(init): implement graceful shutdown of 'init'

---

hack/dev/Makefile
hack/dev/manifests/coredns.yaml

fixes talos-systems/talos#575 

fix: Explicitly set upstream/forward servers for coredns in dev setup

---

Dockerfile
cmd/osctl/pkg/client/client.go
internal/app/init/internal/reg/reg.go
internal/app/init/main.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/proto/api.proto
internal/app/osd/internal/reg/init_client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/main.go
internal/app/osd/proto/api.proto
internal/app/trustd/main.go
internal/pkg/constants/constants.go
internal/pkg/grpc/factory/factory.go

This implements insecure over-file-socket gRPC API for init with two
first simplest APIs: reboot and shutdown (poweroff).
File socket is mounted only to `osd` service, so it is the only service
which can access init API. Osd forwards reboot/shutdown already
implemented APIs to init which actually executes these.
This enables graceful shutdown/reboot with service shutdown, sync, etc.

feat(init): implement init gRPC API, forward reboot to init

---

internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/cloud/vmware/vmware.go
internal/app/init/internal/platform/platform.go
internal/app/init/internal/security/kspp/kspp.go
internal/app/init/main.go
internal/app/init/pkg/network/dhcp.go
internal/pkg/kernel/kernel.go

Adds a simple wrapper to get a specific kernel parameter on request.
There is a section in the `kspp` package that I specifically didn't refactor as it is in a loop.
https://github.com/talos-systems/talos/blob/83363c7a17539614fd491f5bb8453c77c5ab9385/internal/app/init/internal/security/kspp/kspp.go#L18-L42
Let me know if you think the code re-use\clarity is worth the extra cycles of calling `kernel.ParseProcCmdline()` for each loop iteration and I'll refactor it too.

refactor(init): add helper for getting specific kernel parameters

---

Makefile

When running buildkit with the local cache dir on Mac, I get 
```
#5 ERROR: failed to prepare extraction snapshot "extract-764761500-tF5j sha256:4403120d52bbd3d9af979232117a324dcddacfd8a223fc041f481f20b3476dc5": copying of parent failed: failed to copy xattrs: failed to list xattrs on /var/lib/buildkit/runc-native/snapshots/snapshots/8/toolchain/bin/[: operation not supported
```

chore: Make buildkit cache OS dependent

---

internal/app/init/pkg/system/services/udevd.go

WithParentCgroupDevices uses the default cgroup setup to inherit the container's parent cgroup's allowed and denied devices
Without this, we get 'operation not permitted' when attempting to read the block devices.

fix(init): start udevd with parent cgroup devices

---

internal/pkg/constants/constants.go

fix: use the correct param in root label check

---

internal/app/init/pkg/system/health/check.go
internal/app/init/pkg/system/health/health_test.go
internal/app/init/pkg/system/health/settings.go
internal/app/init/pkg/system/health/status.go

This is a small building block for service health checks: settings,
health state, health check runner.
This is to be integrated with ServiceRunner to provide health for each
service based on per-service health check.

feat(init): core health check package

---

internal/pkg/blockdevice/probe/probe.go

Should fix some of the issues we were seeing with being unable to identify a filesystem by label. 

fix: Update filesystem check to open device as a device

---

internal/app/osd/internal/reg/reg.go

Without this we never set the namespace for the context which prevents it from functioning at all

fix(osd): Use correct context in stats endpoint

---

internal/app/init/shutdown.go

:man_facepalming:  I broke the code while refactoring it to return the channel
which notifies about poweroff events.
`defer` was executed and immediately closed the channel, breaking any
subsequent `Receive` calls:
```
error reading from ACPI channel: netlink receive: recvmsg: bad file descriptor
```

fix(init): don't close ACPI listen handle too early

---

internal/pkg/grpc/factory/factory.go

refactor: use os.Remove instead of unix.Unlink

---

Makefile
hack/golang/test.sh
internal/app/init/pkg/system/health/health_test.go

Some unit-tests depend on timing as they're testin concurrent code and
tests do things like `time.Sleep(...)` to let the code in concurrent
goroutine proceed so that side-effect can be observed.
One issue is that `go test` (and `go build`) by default launch builds
with the number of CPUs available which might be too much and overloads
system so that tests which are also concurrent are not allowed to
execute due to high load average. I observe "lock-ups" when running
`make test` locally. I'm trying to limit number of executors to 4 as an
experiment.
Disable short test run, as we don't seem to have any short tests, and
running short and full run just means running all the tests twice.

chore: workaround flaky tests

---

internal/app/init/pkg/system/health/health_test.go
internal/app/init/pkg/system/health/settings.go
internal/app/init/pkg/system/health/status.go
internal/app/init/pkg/system/mocks_test.go
internal/app/init/pkg/system/service.go
internal/app/init/pkg/system/service_runner.go
internal/app/init/pkg/system/service_runner_test.go
internal/app/init/pkg/system/services/containerd.go
internal/app/init/pkg/system/system.go

This connects work on health state with service runner: if service
supports health checks, health check runs with specified schedule
against service when service runner is active. Health state changes are
captured and health status changes are reported via service events.
Idea is that future `osctl services` (or similar which returns service
list/status) reports last known status (including last health check
failure if any), while events capture only changes (health good/bad).
Health check is implemented only for `containerd` service as an example,
but any service implementing `HealthcheckedService` interface gets
health checking for free now.

feat(init): implement health checks for services

---

Makefile

This library is required by socat.

fix: add libressl to rootfs

---

internal/app/init/pkg/system/services/containerd.go

As containerd client API wasn't closed after use, connection was leaking
every time healthcheck was run.

fix(init): fix containerd healthcheck leaking memory in init/containerd

---

cmd/osctl/cmd/root.go
cmd/osctl/cmd/service.go
cmd/osctl/pkg/client/client.go
internal/app/init/internal/reg/reg.go
internal/app/init/pkg/system/events/events.go
internal/app/init/pkg/system/events/events_test.go
internal/app/init/pkg/system/health/health_test.go
internal/app/init/pkg/system/health/status.go
internal/app/init/pkg/system/service_runner.go
internal/app/init/pkg/system/service_runner_test.go
internal/app/init/pkg/system/system.go
internal/app/init/proto/api.proto
internal/app/osd/internal/reg/init_client.go

This returns list of all the services registered, with their current
status, past events, health state, etc.
New CLI is `osctl service [<id>]`: without `<id>` it prints list of all
the services, with specific `<id>` it provides details for a service.
I decided to create "parallel" data structures in protobuf as Go
structures don't map nicely onto what protoc generates: pointers vs.
values, additional fields like mutexes, etc. Probably there's a better
approach, I'm open for it.
For CLI, I tried to keep CLI stuff in `cmd/` package, and I also created
simple wrapper to remove duplicated code which sets up client for each
command.
Examples:
```
$ osctl service
SERVICE      STATE     HEALTH   LAST CHANGE   LAST EVENT
containerd   Running   OK       21s ago       Health check successful …
```

feat(init): implement services list API and osctl service CLI

---

internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go

This includes kubelet, osd, proxyd and trustd.
I believe we can't do healthchecks for other services unless we do some
trick (publish some ports? or file sockets?).
Example:
```
containerd   Running   OK       29s ago       Health check successful
kubeadm      Running   ?        14s ago       Started task kubeadm (PID 285) for container kubeadm
kubelet      Running   OK       6s ago        Health check successful
ntpd         Running   ?        22s ago       Started task ntpd (PID 134) for container ntpd
osd          Running   OK       16s ago       Health check successful
proxyd       Running   OK       9s ago        Health check successful
trustd       Running   OK       16s ago       Health check successful
udevd        Running   ?        22s ago       Started task udevd (PID 127) for …
```

feat(init): implement healthchecks for the services

---

internal/app/init/pkg/system/runner/process/process_test.go
internal/pkg/chunker/file/file.go
internal/pkg/chunker/file/file_test.go

This started as a simple unit-test for file chunker, but the first test
hung immediately, so I started looking into the code.
One problem was that when entering inotify() code, ctx cancel wasn't
considered. Another problem is that remove fsnotify was never triggered,
but I saw that with unit-test later.
Small nit was that inotify() was initialized every time we got to EOF,
which is not efficient for "follow" mode.
So I moved inotify into the main loop, and plugged context cancel watch
into the place when chunk is delivered. Chunker code is supposed to
block in two places: when it tries to deliver next chunk (as client
might be slow to recieve buffers) or when there's no new data (on
inotify). So it makes sense to assert context canceled condition in both
cases.
Signed-off-by: Andrey …

refactor: fix filechunker not exiting on context cancel

---

internal/pkg/chunker/stream/stream.go
internal/pkg/chunker/stream/stream_test.go

Stream chunker should be cancellable at any point of execution, plus it
should be stop chunking on EOF.

refactor: fix stream chunker & provide some tests

---

cmd/osctl/cmd/service.go

Fixes
```
#31 39.85 level=warning msg="[runner/nolint] Found unknown linters in //nolint directives: error"
```

fix: Address lint warning for unknown linter

---

internal/app/init/pkg/system/conditions/all.go
internal/app/init/pkg/system/conditions/all_test.go
internal/app/init/pkg/system/conditions/conditions.go
internal/app/init/pkg/system/conditions/files.go
internal/app/init/pkg/system/conditions/files_test.go
internal/app/init/pkg/system/conditions/none.go
internal/app/init/pkg/system/mocks_test.go
internal/app/init/pkg/system/runner/containerd/containerd.go
internal/app/init/pkg/system/runner/containerd/import.go
internal/app/init/pkg/system/service.go
internal/app/init/pkg/system/service_runner.go
internal/app/init/pkg/system/services/containerd.go
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/ntpd.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go
internal/app/init/pkg/system/services/udevd.go

Conditions are now implemented as interface with two methods: `Wait` for
condition to be true (cancelable via context) and 'String' which
describes what condition is waiting for.
Generic 'WaitForAll' was implemented to wait for multiple conditions at
once.

refactor: change conditions to be interface, add descriptions

---

internal/app/init/main.go
internal/app/init/pkg/system/events/events.go
internal/app/init/pkg/system/health/status.go
internal/app/init/pkg/system/mocks_test.go
internal/app/init/pkg/system/runner/containerd/containerd.go
internal/app/init/pkg/system/service.go
internal/app/init/pkg/system/service_events.go
internal/app/init/pkg/system/service_runner.go
internal/app/init/pkg/system/service_runner_test.go
internal/app/init/pkg/system/services/containerd.go
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/ntpd.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go
internal/app/init/pkg/system/services/udevd.go
internal/app/init/pkg/system/system.go
internal/app/init/pkg/system/system_test.go

This PR introduces dependencies between the services. Now each service
has two virtual events associated with it: 'up' (running and healthy)
and 'down' (finished or failed). These events are used to establish
correct order via conditions abstraction.
Service image unpacking was moved into 'pre' stage simplifying
`init/main.go`, service images are now closer to the code which runs the
service itself.
Step 'pre' now runs after 'wait' step, and service dependencies are now
mixed into other conditions of 'wait' step on startup.

feat(init): implement service dependencies, correct start and shutdown

---

cmd/osctl/cmd/df.go
cmd/osctl/cmd/dmesg.go
cmd/osctl/cmd/kubeconfig.go
cmd/osctl/cmd/logs.go
cmd/osctl/cmd/ps.go
cmd/osctl/cmd/reboot.go
cmd/osctl/cmd/reset.go
cmd/osctl/cmd/restart.go
cmd/osctl/cmd/routes.go
cmd/osctl/cmd/shutdown.go
cmd/osctl/cmd/stats.go
cmd/osctl/cmd/top.go
cmd/osctl/cmd/upgrade.go
cmd/osctl/cmd/version.go
hack/golang/golangci-lint.yaml

Remove duplicated code which was setting up grpc client with common
method. Should have no functional changes otherwise.
Add args len check where missing.

refactor(osctl): DRY up osctl sources by using common client setup

---

internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/kubelet.go

Fix kubeadm startup errors as required mounts are missing:
`stat /var/lib/kubelet: no such file or directory\\\"\"": unknown`
As kubelet depends on kubeadm, this should be no-op for kubelet.
Also remove forgotten wait condition for containerd socket, it is no
longer required as service depends on containerd health.

fix(init): move directory creation to kubeadm pre-func

---

cmd/osctl/cmd/df.go
cmd/osctl/cmd/dmesg.go
cmd/osctl/cmd/kubeconfig.go
cmd/osctl/cmd/logs.go
cmd/osctl/cmd/ps.go
cmd/osctl/cmd/reboot.go
cmd/osctl/cmd/reset.go
cmd/osctl/cmd/restart.go
cmd/osctl/cmd/routes.go
cmd/osctl/cmd/shutdown.go
cmd/osctl/cmd/stats.go
cmd/osctl/cmd/top.go
cmd/osctl/cmd/upgrade.go
cmd/osctl/cmd/version.go
cmd/osctl/pkg/client/client.go

This moves cli code (rendering output, etc.) out of 'client' package, so
that client package is usable outside of cli.
Consistently accept context as first param to API methods, so that we
can build graceful request cancellation.

refactor(osctl): move cli code out of 'client' package

---

cmd/osctl/cmd/df.go
cmd/osctl/cmd/dmesg.go
cmd/osctl/cmd/kubeconfig.go
cmd/osctl/cmd/logs.go
cmd/osctl/cmd/ps.go
cmd/osctl/cmd/reboot.go
cmd/osctl/cmd/reset.go
cmd/osctl/cmd/restart.go
cmd/osctl/cmd/root.go
cmd/osctl/cmd/routes.go
cmd/osctl/cmd/service.go
cmd/osctl/cmd/shutdown.go
cmd/osctl/cmd/stats.go
cmd/osctl/cmd/top.go
cmd/osctl/cmd/upgrade.go
cmd/osctl/cmd/version.go

This provides a bit better handling for the handing grpc
requests (or just slow requests):
```
$ osctl-linux-amd64 --talosconfig talosconfig version
Client:
Tag:         ad410fb-dirty
SHA:         ad410fb-dirty
Built:
Go version:  go1.12.5
OS/Arch:     linux/amd64
^CSignal received, aborting, press Ctrl+C once again to abort immediately...
error getting version: rpc error: code = Canceled desc = context canceled
```
For now we catch `SIGINT` & `SIGTERM`. Second signal kills process
immediately as signal handler is removed.

feat(osctl): handle ^C by aborting context

---

internal/app/init/pkg/system/conditions/files.go
internal/app/init/pkg/system/conditions/files_test.go
internal/app/init/pkg/system/mocks_test.go
internal/app/init/pkg/system/service_runner_test.go

If some of the conditions are already satisfied, we can update the
description to reflect that, e.g.:
```
EVENTS   [Waiting]: Waiting for service "containerd" to be "up", service "networkd" to be "up", service "trustd" to be "up" (14m17s ago)
[Waiting]: Waiting for service "trustd" to be "up" (14m16s ago)
```

feat(init): update 'waiting' state descritpion when conditions change

---

cmd/osctl/cmd/logs.go
cmd/osctl/cmd/root.go

This resolves extra messages when user does ^C to stop osctl. Message is
still printed on the second ^C and process is aborted on the third.
For the `logs` command, as it is streaming, suppress context canceled
error (before context changes process was crashing before printing an error).

fix(osctl): don't print message on first ^C

---

Dockerfile

Announcement: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/golang-announce/0wo8cOhGuAI/v96KeTYtBwAJ
This should improve module download time as `go` no longer needs
to clone full repositories.

chore: enable GOPROXY for go modules

---

Makefile

Ran into this when building talos for the first time on the new macbook. It seems that maybe an actual empty string is getting passed to docker run with the syntax we've currently got in the repo. This results in an error like: 
```
$ make buildkitd
Starting talos-buildkit container
docker run --name talos-buildkit -d --privileged -p 1234:1234  moby/buildkit:v0.5.0 --addr tcp://0.0.0.0:1234
docker: invalid reference format.
See 'docker run --help'.
make: *** [buildkitd] Error 125
```
Removing the quotes seems to work just fine. Could also remove it altogether, as that seems to work as well. 

fix: don't set BUILDKIT_CACHE to empty string in Makefile

---

internal/app/init/pkg/system/runner/containerd/containerd_test.go
internal/app/osd/internal/reg/reg.go
internal/pkg/containers/container.go
internal/pkg/containers/containers_test.go
internal/pkg/containers/inspector.go
internal/pkg/containers/pod.go

Fixes: #689, #690
Refactor container inspection code into a package of its own with some
rudimentary tests. Use this package consistently in osd commands dealing
with containers.
Improvements for the next PRs:
* implement API to fetch info about container by ID (to avoid fetching
full list)
* handle and display errors on client side, not to the log of the
server
* more tests, including k8s containers (how can we do that?)

fix(osd): consistent container ids in stats, ps and reset

---

internal/app/init/pkg/system/health/health_test.go
internal/pkg/containers/containers_test.go

For #711, this should be a complete fix - waiting for container to be
started.
For #712, this should be more of a workaround - playing with timeouts to
hit the failure less likely. Idea of the test is that health check
should be aborted on timeout (1ms) while health check succeeds if not
aborted in 50ms. Before the fix it was 1ms/10ms, but still concurrently
there was a chance that goroutine exits successfully after 10ms while
1ms context deadline is not reached.

chore: address flaky tests instability

---

internal/app/init/pkg/system/services/kubelet.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/trustd.go

fix(init): use 127.0.0.1 IP in healthchecks to avoid resolver weirdness

---

Dockerfile
hack/test/integration.sh
hack/test/osctl-docker-create.sh

This is just the first bit of the CI stuff I've been working on. Thought it might be easier to chunk it up a bit so it won't be massive. This PR will break the "osctl cluster create" flow into its own script, so that we can just call it from the basic integration test, as well as the e2e test I'm working on. 
I also noticed that there was duplication in the Dockerfile for the kernel image. So I removed one of the references there.

chore(ci): modularize integration test

---

cmd/osctl/cmd/ps.go
cmd/osctl/cmd/stats.go
internal/app/osd/internal/reg/reg.go

Logging those errors in osd makes them hard to discover.

fix(osctl): display non-fatal errors from ps/stats in osctl

---

cmd/osctl/pkg/client/client.go

When talosconfig doesn't exist, `osctl` creates empty one behind the
scenes, but that leads to immediate panic if the command tries to build
osd client:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11d6786]
goroutine 1 [running]:
github.com/talos-systems/talos/cmd/osctl/pkg/client.NewDefaultClientCredentials(0x7ffd720f5100, 0xb, 0xc000559ce8, 0x757014, 0xc0000d5500)
/src/cmd/osctl/pkg/client/client.go:50 +0xa6
github.com/talos-systems/talos/cmd/osctl/cmd.setupClient(0x16ca3f0)
/src/cmd/osctl/cmd/root.go:100 +0x3d
github.com/talos-systems/talos/cmd/osctl/cmd.glob..func22(0x24ad7c0, 0xc00058c240, 0x0, 0x3)
/src/cmd/osctl/cmd/ps.go:32 +0x37
github.com/spf13/cobra.(*Command).execute(0x24ad7c0, …
```

fix(osctl): avoid panic on empty 'talosconfig'

---

cmd/osctl/cmd/ps.go
cmd/osctl/cmd/stats.go
internal/app/osd/internal/reg/reg.go

This reverts commit f200eb7a8a0b7c2d29710f695000eb7680ce8b7d. (#724)
grpc can't send back both response and an error.

fix(osctl): Revert "display non-fatal errors from ps/stats in osctl"

---

cmd/osctl/cmd/restart.go
cmd/osctl/pkg/client/client.go
internal/app/osd/proto/api.proto

I couldn't find any use for the `timeout` flag nor the value passed in
the API, but it block much more useful and present in other commands
flag 'target'.

fix(osctl): allow '-target' flag for `osctl restart`

---

internal/app/osd/internal/reg/reg.go
internal/pkg/containers/container.go
internal/pkg/containers/containers_test.go
internal/pkg/containers/inspector.go

Instead of pulling a full list of containers, implement inspector query
for a single container following the spec to build display name.
Also adds many more tests for the container inspector.

refactor(osd): implement container inspector for a single container

---

.drone.yml

I don't really have a good way to test this I don't think, but I think the e2e test didn't get run b/c of its dependency on the basic integration test. That test was only occurring during PR events, so I added cron to the list of triggers as well.

fix: run basic-integration always

---

hack/golang/test.sh

We run tests in parallel mode (`go test -p 4`), default is to run in
parallel in fact. But tests are not isolated, as some of them launch
containerd on a fixed file socket (as socket path is hardcoded in
Talos), and that might lead to any weirdness when tests try to
launch containerd concurrently on the same file socket.

chore: don't run tests in parallel across packages

---

cmd/osctl/cmd/cp.go
cmd/osctl/pkg/client/client.go
internal/app/init/internal/reg/reg.go
internal/app/init/proto/api.proto
internal/app/osd/internal/reg/init_client.go
internal/pkg/archiver/archiver.go
internal/pkg/archiver/archiver_test.go
internal/pkg/archiver/tar.go
internal/pkg/archiver/tar_test.go
internal/pkg/archiver/walker.go
internal/pkg/archiver/walker_test.go

Actual API is implemented in the `init`, as it has access to root
filesystem. `osd` proxies API back to `init` with some tricks to support
grpc streaming.
Given some absolute path, `init` produces and streams back .tar.gz
archive with filesystem contents.
`osctl cp` works in two modes. First mode streams data to stdout, so
that we can do e.g.: `osctl cp /etc - | tar tz`. Second mode extracts
archive to specified location, dropping ownership info and adjusting
permissions a bit. Timestamps are not preserved.
If full dump with owner/permisisons is required, it's better to stream
data to `tar xz`, for quick and dirty look into filesystem contents
under unprivileged user it's easier to use in-place extraction.

feat(osctl): implement 'cp' to copy files out of the Talos node

---

cmd/osctl/cmd/ls.go
cmd/osctl/pkg/client/client.go
internal/app/init/internal/reg/reg.go
internal/app/init/proto/api.proto
internal/app/osd/internal/reg/init_client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

Service `osd` doesn't have access to rootfs, as it is running in a
container, so move API to `init` which has unconstrained access to
rootfs. (This is in line with another API, `osctl cp`).
Fixes: #752

feat(init): move 'ls' API to init from osd

---

Makefile
internal/pkg/constants/constants.go

Pull in latest toolchain commit that bumps k8s version to 1.15 proper instead of beta.
https://github.com/talos-systems/toolchain-musl/commit/3e85af25bde080fe4ce1283cd832350f82aef92b

chore: update toolchain images

---

Makefile

Didn't matter for testing the toolchain, but needed the bump anyways.

fix: forgot to bump k8s version in makefile

---

hack/dev/manifests/coredns.yaml

This plugin is not available in CoreDNS v1.3.1

chore: remove ready plugin from CoreDNS

---

cmd/osctl/cmd/routes.go
go.mod
go.sum
internal/app/osd/internal/reg/reg.go
internal/app/osd/internal/reg/reg_test.go
internal/app/osd/proto/api.proto

- Add support for IPv6, route metrics, protocols, sources, families.
- Fix destination string format to be CIDR.
Fixes #753

feat(osd): extend Routes API

---

cmd/osctl/cmd/cp.go
cmd/osctl/cmd/ls.go
internal/app/init/internal/reg/reg.go
internal/app/init/proto/api.proto
internal/pkg/archiver/archiver.go
internal/pkg/archiver/tar.go
internal/pkg/archiver/tar_test.go
internal/pkg/archiver/walker.go
internal/pkg/archiver/walker_test.go

This unifies low-level filesystem walker code for `ls` and `cp`.
New features:
* `ls` now reports relative filenames
* `ls` now prints symlink destination for symlinks
* `cp` now properly always reports errors from the API
* `cp` now reports all the errors back to the client
Example for `ls`:
```
osctl-linux-amd64 --talosconfig talosconfig ls -l /var
MODE          SIZE(B)   LASTMOD       NAME
drwxr-xr-x    4096      Jun 26 2019   .
Lrwxrwxrwx    4         Jun 25 2019   etc -> /etc
drwxr-xr-x    4096      Jun 26 2019   lib
drwxr-xr-x    4096      Jun 21 2019   libexec
drwxr-xr-x    4096      Jun 26 2019   log
drwxr-xr-x    4096      Jun 21 2019   mail
drwxr-xr-x    4096      Jun 26 2019   opt
Lrwxrwxrwx    6         Jun 21 2019   run -> ../run
drwxr-xr-x    4096      Jun 21 2019   spool …
```

feat(init): unify filesystem walkers for `ls`/`cp` APIs

---

internal/pkg/grpc/gen/gen.go

Ticker in cert generation poll loop was never stopped.

bug(gen): fix leaky ticker

---

cmd/osctl/cmd/ls.go
cmd/osctl/cmd/ps.go
cmd/osctl/cmd/stats.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

Sort output so that sandboxes and containers go together, use tree-like
characters to display relationships for them. (No change for talos
namespace):
```
$ osctl ps -k
NAMESPACE   ID                                                                        IMAGE                          PID   STATUS
k8s.io      kube-system/etcd-master-1                                                 k8s.gcr.io/pause:3.1           649   RUNNING
k8s.io      └─ kube-system/etcd-master-1:etcd                                         k8s.gcr.io/etcd:3.3.10         875   RUNNING
k8s.io      kube-system/kube-apiserver-master-1                                       k8s.gcr.io/pause:3.1           685   RUNNING
k8s.io      └─ kube-system/kube-apiserver-master-1:kube-apiserver …
```

feat(osctl): improve output of `stats` and `ps` commands

---

internal/app/proxyd/internal/frontend/frontend.go
internal/app/proxyd/internal/frontend/frontend_test.go
internal/app/proxyd/main.go

- dropped `tlsConfig` since it wasn't being used anymore
- consolidated `updateFunc` to use `AddBackend` and `DeleteBackend`
- moved kube client initialization/setup into main so we could test watch independently
I think there's still some work to do around handling shutdown better, but will follow up with another pr for that. 

test(proxyd): Add basic suite of tests

---

internal/app/init/internal/security/cis/cis.go

First, use cryptographically secure random number generator.
Second, generate random 32 bytes, don't limit them to any range, as
they're going to be base64-encoded anyways.

fix(init): secret data at rest encryption key should be truly random

---

internal/app/init/internal/security/cis/cis.go

First, use cryptographically secure random number generator.
Second, generate random 32 bytes, don't limit them to any range, as
they're going to be base64-encoded anyways.
(cherry picked from commit bf500fa)

fix(init): secret data at rest encryption key should be truly random [backport]

---

cmd/osctl/main.go
internal/app/init/main.go
internal/app/ntpd/main.go
internal/app/osd/main.go
internal/app/proxyd/main.go
internal/app/trustd/main.go
internal/pkg/startup/rand.go
internal/pkg/startup/startup.go

This is important as otherwise `math/rand` outputs predictable sequence
each time.

chore: seed math.rand PRNG on startup in every service

---

Dockerfile

When inherited from `base`, any source file change is causing
golangci-lint to be re-downloaded.

chore(ci): download golangci-lint only once

---

.drone.yml
Makefile

This is somewhat tough to test, since you can't use the github release for anything but tags (it throws an error), but this PR will build the GCE image and output it to the build directory on tag events. It should, then, get added to the release assets. Once merged, I'll push a test tag to make sure the draft looks correct.

chore: publish gce images with releases

---

CHANGELOG.md

(cherry picked from commit bfe3f247916ac9872c8b30690d29ab75fb4fabe5)

chore: prepare release v0.1.0-beta.1 (#811)

---

internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/cloud/aws/aws.go
internal/app/init/internal/platform/cloud/googlecloud/googlecloud.go
internal/app/init/internal/platform/cloud/packet/packet.go
pkg/userdata/download.go
pkg/userdata/userdata.go
pkg/userdata/userdata_test.go

This also adds in support for downloading userdata that is initially encoded in
base64.

refactor: Userdata.download supports functional args

---

go.mod
go.sum

This fixes the panic stackstraces not being printed, e.g.
https://github.com/stretchr/testify/issues/771

chore: update stretchr/testify to master version

---

internal/app/osd/internal/reg/reg.go
internal/pkg/containers/container.go
internal/pkg/containers/containerd/containerd.go
internal/pkg/containers/cri/cri.go

This refactors metrics interface to remove containerd-specific stuff and
make it common for CRI & containerd.
CRI metrics are easy to grab, we also have there filesystem metrics, not
sure how useful they are.
Next step: refactor interfaces so that metrics are optional (we don't
need them for every call, so we can skip them for `osctl ps` to save
time on CRI/containerd API calls).
Example comparing CRI & containerd (CRI doesn't seem to have a way to
get sandbox metrics, which shouldn't be a big deal imho):
```
$ osctl-linux-amd64 --talosconfig talosconfig stats -k
NAMESPACE   ID                                                                        MEMORY(MB)   CPU
k8s.io      kube-system/etcd-master-1                                                 1.51         11208976
k8s.io      └─ …
```

feat(osd): implement container metrics for CRI inspector

---

.conform.yaml
.github/main.workflow

This PR also makes use of two new options:
- maximumOfOneCommit: enforces that a commit is only one commit ahead of master
- requireCommitBody: requires that a commit contains a body

chore: upgrade conform to v0.1.0-alpha.15

---

cmd/osctl/pkg/client/client.go
internal/app/init/internal/reg/reg.go
internal/app/init/proto/api.proto
internal/app/osd/internal/reg/init_client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

This PR moves the reset API to the init API definition.
It leverages the same code we use for upgrades.

fix: use existing logic to perform reset

---

internal/pkg/blockdevice/probe/probe.go

This change fixes a bug that caused installations to fail.
On each iteration, the previously discovered block devices were dropped because the `probed` variable was reassigned.
We now append the discovered block devices to a slice declared outside the for loop.

fix: append probed block devices

---

internal/app/init/pkg/network/networkd.go
internal/app/init/pkg/network/setup.go
internal/pkg/constants/constants.go

Should allow us to handle edge cases where eth0 is not the primary interface

feat(initramfs): Add kernel arg for default interface

---

Makefile
cmd/osctl/cmd/config.go
go.mod
go.sum

Decided to combine two very small changes (which I'm now grumpy at myself for doing). 
First, we'll update the toolchain image versions to allow for the use of a new containerd and runc. Also updated go.mod and go.sum to make use of newer containerd version. Closes #743 and #744.
Second, I added the bit of logic to `osctl config generate` to determine the working directory and let the user know that we created the various yaml files there. Closes #760.

chore: update toolchain version and output created config files

---

docs/proposals/YYYYMMDD-TEMPLATE.md

This field is superfluous since we can get this from git.

chore: remove last updated field from proposal template

---

.codecov.yml

chore: bump codecov project target to 33%

---

.drone.yml
Dockerfile
Makefile

This change removes the test-container step, and consolidates it to only a
test step. This prevents the build of the test container being done
twice.

chore: prevent duplicate build of test container

---

.drone.yml
Makefile
hack/golang/test.sh
internal/app/init/pkg/system/runner/containerd/containerd.go
internal/app/init/pkg/system/runner/containerd/containerd_test.go
internal/app/init/pkg/system/runner/containerd/import.go
internal/app/init/pkg/system/runner/runner.go
internal/pkg/containers/containerd/containerd.go
internal/pkg/containers/containerd/containerd_test.go
internal/pkg/containers/cri/cri.go
internal/pkg/containers/cri/cri_test.go

This makes test launch their own isolated instance of containerd with
its own root/state directories and listening socket address. Each test
brings this instance up/down on its own.
Add options to override containerd address in the code (used only in the
tests).
Enable parallel go test runs once again.
P.S. I wish I could share that 'SetupSuite' phase across the tests, but
afaik there's no way in Go to share `_test.go` code across packages. If
we put it as normal package, this might pull in test dependencies (like
`testify`) into production code, which I don't like.

chore: make unit-tests use isolated instances of containerd

---

cmd/osctl/cmd/install_linux.go
internal/app/init/internal/platform/baremetal/baremetal.go
internal/app/init/internal/platform/cloud/packet/packet.go
internal/pkg/kernel/kernel.go
internal/pkg/kernel/kernel_test.go
pkg/userdata/install.go

In addition to adding a flag, this adds a field to the user data that allows
for extra kernel arguments to be specified.

feat: add install flag for extra kernel args

---

internal/pkg/mount/mount.go

This uses the correct mount flag for read-only.
We mistakenly had the flag for opening a file as read-only.

fix(init) mount root partition as read-only

---

internal/app/init/internal/reg/reg.go

The gRPC response will fail to be decoded because our reply is nil.

fix: return non-nil response in reset

---

internal/app/init/pkg/network/setup.go

Minor improvements to help when debugging.
Without this, if bringing up the default interface fails, the logs can
be misleading.

chore: improve network setup logging

---

internal/app/osd/internal/reg/reg.go

Temporary workaround while we get more information on the
specifics for what is failing.
Ref: talos-systems/talos#795

fix(init): Fix routes endpoint

---

.drone.yml
Dockerfile
Makefile
hack/cleanup.sh
hack/golang/test.sh
internal/app/init/internal/rootfs/rootfs.go
internal/app/init/main.go
internal/app/init/pkg/system/runner/containerd/containerd_test.go
internal/app/init/pkg/system/runner/process/process_test.go
internal/app/init/pkg/system/services/kubeadm.go
internal/app/init/pkg/system/services/osd.go
internal/app/init/pkg/system/services/proxyd.go
internal/app/init/pkg/system/services/udevd.go
internal/app/init/pkg/system/services/udevd_trigger.go
internal/pkg/containers/containerd/containerd_test.go
internal/pkg/containers/cri/cri_test.go
internal/pkg/cri/cri_test.go

This brings in the newly compiled libraries and binaries from our new
pkg builds. Since we no longer create symlinks for directories that need to be
writable, we leverage overlayfs for very specific paths
(e.g. /etc/kubernetes, /etc/cni). This allows us to keep our base rootfs as
read-only, and then have approved paths in the rootfs that we allow to be
writable.

feat: use new pkgs for initramfs and rootfs

---

Dockerfile
cmd/osctl/cmd/cluster/pkg/node/node.go

In order to run Talos with ignite, we need to have init at /sbin/init.

chore: move init to /sbin

---

.drone.yml
Dockerfile

Now that we manage dependencies manually, we need to explicitly build
the kernel target so that vmlinuz and vmlinux are placed into the build
directory.

chore: add step to drone for kernel

---

.drone.yml

Produces a VHD suitable for uploading to Azure and creating a Talos
node.

chore: publish Azure image on releases

---

internal/pkg/rootfs/rootfs.go

Without this, the check for the existence of the symlinks created in the
rootfs preparation step will always fail. On a reboot init will fail
because it tries to create a symlink that already exists.

fix: prefix file stat with rootfs prefix

---

cmd/osctl/cmd/cluster.go

This PR adds the ability to set mtu for the cluster create networks.
Default is 1440, which seems to be the default for calico.

feat: allow specification of mtu for cluster create

---

internal/pkg/network/dhcp.go

We should only set the hostname to the actual host name instead of FQDN.
This hasnt been much of an issue, but GCE does return the FQDN for the
hostname field in dhcp.

fix: Truncate hostname if necessary

---

internal/app/init/internal/platform/cloud/googlecloud/googlecloud.go

This PR is needed so that the eth0 device will have the proper mtu when
coming online in google cloud

feat: set default mtu for gce platform

---

internal/pkg/rootfs/rootfs.go

This PR will fix a bug where the non-init nodes were not generating their certs locally and relying on trustd instead. This broke down for other control plane nodes because we aren't saving the CA key when we're generating with the trustd identity function (because we don't need it for workers).

fix: Only generate pki from trustd if not control plane

---

Dockerfile
Makefile
hack/golang/test.sh

This relies on two PRs to the buildkit, which aren't merged yet, so I
had to do some overrides to apply them:
* https://github.com/moby/buildkit/pull/1081
* https://github.com/moby/buildkit/pull/1085

chore: run tests in the buildkit itself

---

Makefile

Target 'binaries' was referencing non-existent `Dockerfile` target, so
any `make all` failed.

chore: repair 'make all'

---

internal/app/machined/main.go
internal/app/machined/pkg/system/services/kubeadm.go
internal/app/machined/pkg/system/services/kubelet.go
internal/pkg/rootfs/etc/etc.go

We need /etc/resolv.conf to be writable so that networkd can update it.
This change achieves this by creating a symlink at /etc/resolv.conf that
points to /var/resolv.conf.

fix: make /etc/resolv.conf writable

---

.drone.yml

The GCE and Azure steps need to run in serial since they both output the
same artifact name.

chore: fix image builds on tags

---

Makefile

The raw disk causes the release to fail.

chore: remove the raw disk after Azure build

---

Makefile

The image needs to be compressed in order to publish it to GitHub.

chore: compress Azure image

---

Dockerfile
Makefile
hack/golang/test.sh

This allows to do `make test TESTPKGS=./internal/app/machined`.
Also update Dockerfile slug as
https://github.com/moby/buildkit/pull/1081 was merged into master.

chore: allow to run tests only for specified packages

---

internal/pkg/network/dhcp.go

This PR fixes a small bug where we weren't properly checking the value of a net.ParseIP() call and setting the hostname to the first octet of an IP.

fix: check proper value of parseip in dhcp

---

Dockerfile

`go env GOCACHE` tells it's actually `/.cache` in our build environment
(probably because `$HOME` is not set?)

chore: fix GOCACHE dir location

---

pkg/userdata/services.go
pkg/userdata/services_test.go
pkg/userdata/userdata.go

Fixes #666
Also adds IPv6 to tests for trustd endpoints

fix(trustd): allow hostnames for trustd endpoints

---

cmd/osctl/cmd/df.go
cmd/osctl/pkg/client/client.go
internal/app/machined/internal/reg/reg.go
internal/app/machined/proto/api.proto
internal/app/osd/internal/reg/init_client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/proto/api.proto

This change allows for more accurate mount reporting as /proc/mounts is
a symlink to /proc/self/mounts and contains mounts that are relative to
the running process. In our case this was osd. This caused inaccurate
reporting of mounts since they were relative to osd when we really
wanted mounts relative to machined.

feat: move df API to init

---

internal/pkg/rootfs/rootfs.go

These were disabled in previous versions of Talos since BPF was
completely disabled. With this change, we now implement all recommended
sysctls.

feat: enable missing KSPP sysctls

---

cmd/osctl/cmd/install_linux.go
hack/installer/entrypoint.sh
internal/pkg/install/prepare.go

This change reduces the size of raw disk significantly by creating it as
a sparse file.

chore: create raw image as sparse file

---

Dockerfile

This change fixes a bug that caused the API server to fail due to a
missing directory at /usr/share/ca-certificates.

fix: Run cleanup script earlier in rootfs build

---

Dockerfile

Remove `-a` flag to `go build` which caused cache to be missed all the
time. Add cache mount where missing, update path to match Go build cache
exactly.

chore: fix build cache

---

internal/app/machined/pkg/system/runner/cri/cri.go
internal/app/machined/pkg/system/runner/cri/cri_test.go
internal/app/machined/pkg/system/runner/cri/runner.go
internal/pkg/containers/cri/cri.go
internal/pkg/cri/containers.go
internal/pkg/cri/cri_test.go
internal/pkg/cri/images.go

It runs containers via CRI interface in a pod sandbox. This is the very
first version:  I tried not to introduce any changes to common runner
interface.
There should be some CRI-speficic options for the runner (like polling
interval, as it doesn't have nice `Wait()` API), plus my plan so far is
to use OCI as the common layer for container options, so that we can
analyze OCI and translate to CRI (when possible, return errors when
option is not implemented).
CRI interface doesn't have a concept of 'unpacking' an image, so we
probably need to unpack via containerd API (or any other
runtime-specific API) by targeting CRI namespace.

chore: implement first version of CRI runner

---

CHANGELOG-0.2.md

This is the official v0.2.0-alpha.4 release.

chore: prepare release v0.2.0-alpha.4

---

Makefile

This removes the `--output` flag from the rootfs target. With the output
specified it was outputting the file directory structure to the build
directory.

chore: remove rootfs output param

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/cluster/pkg/node/node.go

This allows to run tiny Talos clusters (which is sometimes nice for
local testing), e.g. with just a single master and zero workers.

feat(osctl): allow configurable number of masters to `cluster create`

---

internal/pkg/network/setup.go

This PR will fix a bug we encountered in GCE, where the interface was
already up and the MTU value wasn't getting set.

fix: set mtu value regardless of interface state

---

internal/app/machined/internal/phase/phase.go
internal/app/machined/internal/phase/phase_test.go
internal/app/machined/main.go

Phases should run sequentially, while tasks concurrently in a phase.
There are two potential issues fixed:
1. `result` multierror was updated inside goroutine without any
synchronization, so this is a data race
2. panic inside task/phase runner might happen and as unhandled panic in a
goroutine aborts whole process, this might lead to a system halt as
as the 'machined' exits

fix(init): flip concurrency of tasks/services, fix small issues 

---

Dockerfile
Makefile

New buildkit release: https://github.com/moby/buildkit/releases/tag/v0.6.0
New release was published for buildkit's dockerfile:
https://github.com/moby/buildkit/releases/tag/dockerfile%2F1.1.2-experimental,
so we can stick to release version now.
These releases include fixes/implementation for `RUN --security=insecure`.

chore: update dockerfile/buildkit versions

---

internal/app/machined/main.go

Without running the install task first, /var is read-only. This causes
the overlay phase to fail as it tries to create /var/system.

fix: create overlay mounts after install

---

.drone.yml
Makefile
hack/test/basic-integration.sh
hack/test/e2e-integration.sh
hack/test/e2e-platform.sh
hack/test/e2e-runner.sh
hack/test/gce-setup.sh
hack/test/manifests/gce-cluster.yaml
hack/test/manifests/provider-components.yaml
hack/test/osctl-cluster-create.sh

This PR will break cluster create apart from the other steps in
integration tests. It will allow us to run the cluster create, then use
it for parallel e2e builds in different cloud environments.

feat: break up osctl cluster create and basic/e2e tests

---

.drone.yml

This adds a node selector to our drone jobs that runs the jobs on
dedictated CI nodes.

chore: run CI jobs on CI nodes

---

cmd/osctl/cmd/service.go
cmd/osctl/pkg/client/client.go
internal/app/machined/internal/phase/api/reg/reg.go
internal/app/machined/internal/phase/services/services.go
internal/app/machined/pkg/system/service_events.go
internal/app/machined/pkg/system/service_runner.go
internal/app/machined/pkg/system/service_runner_test.go
internal/app/machined/pkg/system/system.go
internal/app/machined/pkg/system/system_test.go
internal/app/machined/proto/api.proto
internal/app/osd/internal/reg/init_client.go

It is now possible to `start`/`stop`/`restart` any service via `osctl`
commands.
There are some changes in `ServiceRunner` to support re-use (re-entering
running state). `Services` singleton now tracks service running state to
avoid calling `Start()` on already running `ServiceRunner` instance.
Method `Start()` was renamed to `LoadAndStart()` to break up service
loading (adding to the list of service) and actual service start.

feat(init): implement complete API for service lifecycle (start/stop)

---

internal/app/machined/internal/platform/cloud/aws/aws.go
internal/app/machined/internal/platform/cloud/azure/azure.go
internal/app/machined/internal/platform/cloud/googlecloud/googlecloud.go
internal/app/machined/internal/platform/cloud/vmware/vmware.go
internal/pkg/mount/manager/owned/owned.go
internal/pkg/mount/options.go

This adds the logic for mounting the owned block device and resizing the
ephemeral partition for cloud platforms.

fix: mount the owned partitions in cloud platforms

---

internal/app/machined/pkg/system/runner/goroutine/goroutine.go

Discovered with `go test -race`:
```
WARNING: DATA RACE
Read at 0x00c0000cf2f8 by goroutine 25:
github.com/talos-systems/talos/internal/app/machined/pkg/system/runner/goroutine.(*goroutineRunner).Stop()
/home/smira/Documents/autonomy/talos/internal/app/machined/pkg/system/runner/goroutine/goroutine.go:111 +0x3e
github.com/talos-systems/talos/internal/app/machined/pkg/system/runner/goroutine_test.(*GoroutineSuite).TestStop()
/home/smira/Documents/autonomy/talos/internal/app/machined/pkg/system/runner/goroutine/goroutine_test.go:115 +0x345
runtime.call32()
/usr/local/go/src/runtime/asm_amd64.s:519 +0x3a
reflect.Value.Call()
/usr/local/go/src/reflect/value.go:308 +0xc0
github.com/stretchr/testify/suite.Run.func2()
/home/smira/Documents/go/pkg/mod/github.com/stretchr/testify@v1.3.1-0.201903111 …
```

chore: fix data race in goroutine runner

---

CHANGELOG-0.2.md

This is the official v0.2.0-alpha.5 release.

chore: prepare release v0.2.0-alpha.5

---

pkg/constants/constants.go

This PR will bump the hyperkube version so that we've got fixes for some
pretty critical CVEs: CVE-2019-11247 and CVE-2019-11249

feat: bump k8s version to v1.15.2

---

internal/pkg/mount/manager/owned/owned.go

This fix ensures that we always grow the data partition during an installation.

fix(initramfs): Allow data partition to grow

---

Makefile

The machined dependency is not needed in the rootfs target. The
dependency is handled by buildkit.

chore: remove machined from rootfs target

---

.conform.yaml
internal/app/machined/internal/phase/rootfs/check_install.go
internal/app/machined/internal/platform/baremetal/baremetal.go
internal/app/machined/internal/platform/packet/packet.go
internal/app/machined/main.go
internal/pkg/installer/bootloader/syslinux/syslinux.go
internal/pkg/installer/installer.go
internal/pkg/installer/manifest/manifest.go
internal/pkg/mount/manager/owned/owned.go

This also includes a fix for #955 which had the unintended side effect
of breaking image creation ( since it would attempt to grow the filesystem
always ).
The refactor standardizes around looking for the DATA and ESP labels to
discover any existing installations/filesystems. If none are found, an
installation will proceed -- for both image creation and bare metal.
During bootup, the DATA partition will always attempt to expand/grow.

fix(machined): Clean up installation process

---

.drone.yml
Dockerfile
Makefile

As Go race detector doesn't work under libmuscl, use stock glibc-based
golang container.

chore: add race-enabled test run

---

.drone.yml
hack/drone.jsonnet

This fixes and issue with cloning the master branch caused by git
refusing to fetch into the current branch.

chore: fix broken clone

---

docs/community/project-layout.md

This document describes our official layout standards. It serves as a
guide for contributors to help them in organizing code and placing
packages into the correct locations.

docs: add project layout standards

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/cluster/pkg/node/node.go
hack/test/basic-integration.sh
internal/app/machined/internal/phase/services/services.go

Problem was triggered by udevd trigger, root cause is not clear, but
workaround is to disable it for container mode.
Implement CPU/mem limits for `osctl cluster create`, apply defaults,
bump defaults for cicd.

fix: stalls in local Docker cluster boot

---

go.mod
pkg/grpc/middleware/auth/basic/basic.go
pkg/net/net.go
pkg/net/net_test.go

When talking to an IPv6 address for a gRPC server, enclose the IPv6
address in brackets.
Also fixes backwards implementation of IPv4/IPv6 test.
Fixes #983

fix: enclose address in brackets gRPC client

---

.drone.yml
Makefile
hack/drone.jsonnet

Instead of building platform specific images in the default pipeline, we
should build just one image as part of our basic testing to make sure
installations work as expected.

chore: add image test step

---

.drone.yml
hack/drone.jsonnet

Although the GitHub release plug requires a tag and will fail on a
promotion, this is still useful as it will allow us to mimic a release
before we tag.

chore: add ability to promote to a release

---

internal/app/machined/internal/api/reg/reg.go

This wil remove the machine config on a reset so that a new machine
configwill be downloaded and used on a reboot.

feat: remove the machine config on reset

---

internal/app/proxyd/internal/frontend/frontend.go

This prints any error that occurs when dialing the bootstrap backend.

fix(proxyd): print bootstrap backend dial errors

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/generate_test.go
pkg/userdata/generate/init.go
pkg/userdata/generate/join.go
pkg/userdata/generate/talosconfig.go

This reworks a bunch of the formatting for the userdata generation to
output a cleaner talos config when using IPv6 masters and `osctl config
generate`.
Please note that this changes the scope of concern for master indexing,
keeping `osctl` blissfully unaware of the master-reference chaining.
All it does is report the index of the master it is trying to generate.
The generator itself handles the reference chaining.
Fixes #916, fixes #917, and fixes #918

fix: formatting problems with IPv6 and osctl gen

---

Makefile
hack/test/azure-setup.sh
hack/test/basic-integration.sh
hack/test/e2e-integration.sh
hack/test/gce-setup.sh
hack/test/manifests/azure-cluster.yaml
hack/test/manifests/gce-cluster.yaml

In order to run more than one instance of E2E testing at a time, we need
to ensure that all resources are unique to the run.

chore: run unique E2E tests

---

CHANGELOG-0.2.md

This is the official v0.2.0-alpha.6 release.

chore: prepare release v0.2.0-alpha.6

---

.drone.yml
hack/drone.jsonnet

We should only use the "tag" event and remove the promotion event. It
seems like we can't have both.

chore: fix release pipeline

---

.drone.yml
hack/drone.jsonnet

This prevents the default pipeline from running on releases. It also
ensures that the push step is executed on a release.

chore: fix default pipeline

---

.drone.yml
hack/drone.jsonnet

In order to use promotion against pull requests to trigger things like
E2E, we need to update the default clone logic. The issue is that a
promotion is assumed to be ran against a build that has been merged. In
our case, we need to promote builds that are not necessarily merged.

chore: fix drone clone

---

hack/test/manifests/azure-cluster.yaml
hack/test/manifests/gce-cluster.yaml

This PR will edit the manifests for e2e so that we can take advantage of https://github.com/talos-systems/cluster-api-provider-talos/pull/47

chore: enable floating IP creation in e2e tests

---

hack/test/conformance.sh

This is the recommended fix for waiting on conformance results. Sonobuoy
is returning early even though the --wait flag is specified.

chore: use go runner in sonobuoy

---

hack/test/e2e-integration.sh

If we wait for all masters to check in before applying the PSP, we run
the risk of kube-proxy failing to start for a long period of time.

chore: apply manifests when init node is ready

---

internal/app/machined/internal/phase/network/network.go
internal/app/machined/internal/phase/rootfs/etc/etc.go
internal/app/machined/internal/phase/rootfs/network_configuration.go
internal/app/machined/internal/platform/aws/aws.go
internal/app/machined/internal/platform/azure/azure.go
internal/app/machined/internal/platform/googlecloud/googlecloud.go
pkg/userdata/userdata.go

This sets up the ability to define hostname via userdata. I dont expect
this will get used publicly much, but provides a mechanism to convey
the hostname from various sources internally.
This also fixes the hostname retrieval from metadata services in azure.

feat: Allow hostname to be specified in userdata

---

hack/test/conformance.sh

This is only slowing down the build since we use a remote DB for drone.

chore: remove sonobuoy spinner

---

Dockerfile
internal/app/proxyd/internal/reg/reg.go
internal/app/proxyd/internal/reg/reg_test.go
internal/app/proxyd/main.go
internal/app/proxyd/proto/api.proto
pkg/constants/constants.go

Part of the API refactor; this introduces a gRPC server for proxyd
to expose some of the internal state.

feat(proxyd): Add gRPC server

---

pkg/blockdevice/table/gpt/partition/partition.go

There was a bug in the offset calculation for the last field (offset at 72 instead of 128 )
that caused a truncation of the partition name field to only allow for 8 characters/16 bytes
( utf-16 = 2bytes/character ). This last field isnt part of the gpt spec, so we are dropping it.

fix(gpt) Fix partition naming to be >8 characters

---

internal/pkg/kernel/kernel.go

This should allow for better troubleshooting during early boot/startup

chore: Disable rate limited kmessage

---

hack/test/manifests/azure-cluster.yaml

This PR will save us a little dinero over the course of running e2e
builds in azure. It's only a couple cents per hour difference, but will
shave off a fair amount over the course of a month.

chore: move to smaller azure instance type

---

pkg/blockdevice/table/gpt/gpt.go
pkg/blockdevice/table/gpt/header/header.go
pkg/blockdevice/table/gpt/partition/partition.go
pkg/serde/serde.go

This fixes the names of the Serde functions to be descriptive of what
they are actually doing. The serialize and deserialize ideas were
flipped.

fix: name the serde functions appropriately

---

pkg/userdata/download.go

This should make it clearer when the download failed what is going on.

chore: Add log message for userdata backoff.

---

internal/pkg/installer/bootloader/syslinux/syslinux.go
pkg/blockdevice/filesystem/vfat/vfat.go
pkg/blockdevice/filesystem/xfs/xfs.go
pkg/cmd/cmd.go
pkg/cmd/cmd_test.go

This adds a command runner function that can be used everywhere we need
to exec a binary. It adds addtional logic around error handling that
will allow for viewing errors in the case of a failed command.

feat: add standardized command runner

---

Makefile
hack/installer/entrypoint.sh

Adds some functionality to help prevent collisions.
- Run `losetup -f <attach>` to atomically provision the next loopback
device with a file
- Creates a tempfile for default and test named raw images to prevent
overlap

chore: Make installer script more robust

---

Makefile

Should prevent flakes when we merge fixes on release branches where they unintentionally
get tagged as `latest`.
Closes #956 

chore(ci): Only push `latest` tags if branch is master.

---

internal/app/machined/internal/cni/cni.go

We shouldnt need these anymore
Fixes #1046 

fix(machined): Remove host mounts for specific CNI providers

---

internal/app/machined/internal/phase/rootfs/mount_bpffs.go
internal/app/machined/internal/phase/rootfs/mount_cgroups.go
internal/app/machined/main.go
internal/pkg/mount/manager/bpffs/bpffs.go
internal/pkg/mount/manager/bpffs/bpffs_test.go

The BPF filesystem is required to pin BPF objects.
Fixes #1044.

feat: mount /sys/fs/bpf

---

hack/test/conformance.sh

These are failing with false positives. Disable for now so that we can
run our conformance tests.

chore: disable CIS benchmarks

---

cmd/osctl/cmd/cluster/pkg/node/node.go
internal/app/machined/internal/phase/services/services.go
internal/app/machined/pkg/system/services/ntpd.go
internal/app/machined/pkg/system/services/osd.go
internal/app/machined/pkg/system/services/proxyd.go
internal/app/machined/pkg/system/services/system-containerd.go
internal/app/machined/pkg/system/services/trustd.go
internal/app/osd/internal/reg/reg.go
pkg/constants/constants.go

In order to facilitate upgrades and resets that are capable of
manipulating the system block device, we need to run an instance of
containerd that has zero dependencies on the disk. We run containerd
purely in memory for running system services.

feat: run dedicated instance of containerd for system services

---

cmd/osctl/cmd/config.go
cmd/osctl/cmd/root.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/init.go

Adds handler for specification of additional subjet alt names (SANs) for
the API Server when generating a new cluster configuration using
`osctl`.
Fixes #800

feat: allow specification of additional API SANs

---

hack/dev/qemu-boot.sh

Fixes a typo that cased the switch statement to not match Linux
environments.

chore: fix qemu-boot.sh

---

cmd/osctl/cmd/time.go
cmd/osctl/pkg/client/client.go
internal/app/machined/pkg/system/services/ntpd.go
internal/app/machined/pkg/system/services/osd.go
internal/app/osd/internal/reg/ntp_client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/main.go

Allows us to access ntp api
```
[16:43:50] $ ./build/osctl-darwin-amd64 time --check time.cloudflare.com; ./build/osctl-darwin-amd64 time
NTP Server: time.cloudflare.com
Local time: 2019-08-21 21:44:14.5179364 +0000 UTC
Remote time: 2019-08-21 21:44:14.474403077 +0000 UTC
NTP Server: pool.ntp.org
Local time: 2019-08-21 21:44:14.9037713 +0000 UTC
Remote time: 2019-08-21 21:44:14.814032015 +0000 UTC
```

feat(osd): Add ntpd client

---

Dockerfile
cmd/osctl/cmd/interfaces.go
cmd/osctl/pkg/client/client.go
internal/app/machined/pkg/system/services/networkd.go
internal/app/machined/pkg/system/services/osd.go
internal/app/networkd/main.go
internal/app/networkd/pkg/networkd/netlink.go
internal/app/networkd/pkg/networkd/networkd.go
internal/app/networkd/pkg/reg/reg.go
internal/app/networkd/pkg/reg/reg_test.go
internal/app/networkd/proto/api.proto
internal/app/osd/internal/reg/networkd_client.go
internal/app/osd/internal/reg/ntp_client.go
internal/app/osd/internal/reg/reg.go
internal/app/osd/internal/reg/reg_test.go
internal/app/osd/main.go
internal/app/osd/proto/api.proto
pkg/constants/constants.go

Allows us to list routes and interface details. This includes moving routes() from osd to networkd
```
~/go/src/github.com/talos-systems/talos/qemu
[23:42:34] $ ../build/osctl-darwin-amd64 --talosconfig talosconfig routes
INTERFACE   DESTINATION                   GATEWAY      METRIC
eth0        <nil>                         10.254.0.2   0
eth0        10.254.0.0/24                 <nil>        0
eth0        10.254.0.0/32                 <nil>        0
eth0        10.254.0.10/32                <nil>        0
eth0        10.254.0.255/32               <nil>        0
lo          127.0.0.0/32                  <nil>        0
lo          127.0.0.0/8                   <nil>        0
lo          127.0.0.1/32                  <nil>        0
lo          127.255.255.255/32            <nil>        0
lo …
```

    feat(networkd): Add grpc endpoint

---

internal/app/networkd/pkg/address/address.go
internal/app/networkd/pkg/address/dhcp.go
internal/app/networkd/pkg/address/static.go
internal/app/networkd/pkg/networkd/networkd.go

If multiple interfaces exist on a node, but the first interface was unsuccessful
in getting a dhcp response, we would seg fault when trying to retrieve the hostname
for that interface. This was due to d.Ack being nil and us having no guard around it

fix(networkd): Fix hostname retrieval

---

Dockerfile

This step is based on `golang` image, so `GOCACHE` is set in a bit of a
different way.
No big deal, but should speed up subsequent runs a bit.

chore: fix location of Go build cache mount for unit-tests-race

---

internal/app/machined/internal/phase/upgrade/leave_etcd.go
internal/app/machined/internal/sequencer/v1alpha1/types.go

We need to remove the current node from etcd when upgrading.

fix: leave etcd when upgrading control plane node

---

Dockerfile
hack/golang/test.sh

Go by default caches unit-tests results via build cache, so if source
code doesn't have any changes, test results are cached on package level.
As our unit-tests are not that pure and depend on the environment, it
would be more helpful to make sure all the unit-tests during each build.
Setting number of test runs to one disable test result cache (but build
cache is still being used).

chore: disable go test result cache

---

go.mod
go.sum
internal/app/machined/pkg/system/services/udevd.go
pkg/cmd/cmd.go

Use circular buffer instead of (unlimited) `bytes.Buffer` to limit
amount of stderr output captured. If command being run produces too much
output on stderr, this might consume too much RAM.
Use `pkg/cmd` to run command in `udevd` service. This should allow
easier udevd integration.

fix(machined): limit max stderr output, use pkg/cmd consistently

---

internal/app/machined/pkg/system/runner/containerd/containerd_test.go

Fixes #1010
Wait for containerd shim socket to be removed before running container
second time.

chore: make TestContainerdSuite/TestRunTwice more robust

---

internal/app/networkd/pkg/address/dhcp.go

Increased retry count to 6 for DHCP.  In my testing, this worked
reliably in my setup, where the default (3) did not.
Ultimately, this should probably be configurable from the userdata.
Instead, this just makes it work for me.
Fixes #1099

fix: increase retries for DHCP

---

Makefile

This cache was more important back when builds of Talos took upwards of
40 minutes. Since this is no longer the case, and I have seen
performance issues by mounting a host path into the container, I think
we should drop this.

chore: remove buildkit cache directory

---

internal/app/machined/internal/runtime/initializer/metal/metal.go
internal/pkg/installer/manifest/verify.go

This sets the default install image just before installation. It was
erroneously placed in the boot verification.

fix: set default install image

---

internal/app/machined/main.go
internal/app/machined/pkg/system/log/log.go
internal/app/machined/pkg/system/runner/process/process.go
internal/app/machined/pkg/system/runner/process/process_test.go
pkg/cmd/cmd.go
pkg/cmd/cmd_test.go
pkg/proc/reaper/hunter.go
pkg/proc/reaper/reaper.go
pkg/proc/reaper/reaper_test.go
pkg/proc/reaper/wait.go

In UNIX, any zombies without parent process get re-parented to process
with PID 1 (usually running init), and PID 1 process should take care of
them (usually simply clean them up). Cleaning up zombies is important,
as they still take kerner resources, and having enormous amount of
zombie processes signifcantly degrades system performance.
For Talos, PID 1 process is machined, and machined itself forks to run
other processes in process runner and `pkg/cmd` one-time commands. Naive
solution of running `wait()` loop doesn't work as it might race with
`Process.Wait()` and clean up zombie which wasn't re-parented which
leads to process execution false failure.
After considering other solutions, we decided to go with the simple
approach: machined runs global zombie process reaper which …

chore(machined): implement process reaper for PID 1 machined process

---

cmd/osctl/cmd/time.go

This changes the output to a table writer with all caps for headers.
Fixes #1091.

chore: align time command with output standards

---

.conform.yaml
internal/app/ntpd/pkg/ntp/ntp.go
internal/app/ntpd/pkg/ntp/ntpd_test.go
internal/app/ntpd/pkg/ntp/options.go
internal/app/ntpd/pkg/reg/reg.go
internal/app/ntpd/pkg/reg/reg_test.go

- Use the Validate method to ensure we get an appropriate time back
- Hard set the clock initially, adjust clock by offsets afterwards
- Introduce functional opts to configure ntp client
- Add additional test coverage

refactor(ntpd): Improvements to the robustness of ntp

---

internal/app/machined/internal/phase/kubernetes/tasks.go
internal/app/machined/internal/phase/rootfs/unmount_pod_mounts.go
pkg/kubernetes/kubernetes.go

Reading /proc/mounts while simultaneously unmounting mountpoints
prevents unmounting all submounts under /var. This is due to the fact
that /proc/mounts will change as we perform unmounts, and that causes a
read of the file to become inaccurate. We now read /proc/mounts into
memory to get a snapshot of all submounts under /var, and then we
proceed with unmounting them.
This also adds some additional logging that I found to be useful while
debugging this. It also adds logic to skip of DaemonSet managed pods.

fix: prevent EBUSY when unmounting system disk

---

hack/test/basic-integration.sh

This was breaking e2e testing, as we depend on it for applying CAPI and
launching VMs from there.

fix: remove basic integration teardown

---

hack/test/basic-integration.sh
hack/test/manifests/provider-components.yaml

This PR updates our e2e tests with the provider-components file that's
generated by our capi v0.1.9 update.

chore: update provider-components for capi v0.1.9

---

internal/app/machined/internal/phase/network/network.go
internal/app/networkd/main.go
internal/app/networkd/pkg/networkd/netconf.go
internal/app/networkd/pkg/nic/nic.go
internal/app/networkd/pkg/nic/options.go
internal/pkg/kernel/kernel.go
pkg/constants/constants.go
pkg/userdata/networking.go

Added a property to userdata to allow a network interface to be ignored,
such that Talos will perform no operations on it (including DHCP).
Also added kernel commandline parameter (talos.network.interface.ignore)
to specify a network interface should be ignored.
Fixes #1124

feat: allow network interface to be ignored

---

cmd/osctl/cmd/install_linux.go
internal/pkg/kernel/kernel.go

Added a decomposition option to the kernel.NewDefaultCmdline() so that
the Defaults can be added _after_ constructing a custom commandline.
This is then implemented for `osctl install`.
Fixes #1128

fix: prepend custom options for kernel commandline

---

cmd/osctl/cmd/install_linux.go
cmd/osctl/internal/userdata/userdata.go

This modifies `osctl install` to use the provided userdata as the source
for default installation values.  This allows such things as
userdata-supplied extra kernel parameters to be automatically
included in the bootloader.
Fixes #1102

fix(osctl): use real userdata as defaults for install

---

cmd/osctl/cmd/config.go
cmd/osctl/cmd/root.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/generate_test.go
pkg/userdata/generate/init.go
pkg/userdata/generate/join.go
pkg/userdata/generate/talosconfig.go
pkg/userdata/v1/cluster_config.go
pkg/userdata/v1/generate/generate.go
pkg/userdata/v1/generate/init.go
pkg/userdata/v1/generate/talosconfig.go

Broke the binding between the discrete IP addresses of the control plane
elements and the ControlPlaneEndpoint.  This allows the specification of
a canonical controlplane address which may optionally be a DNS name.
Fixes #1131

feat: Allow spec of canonical controlplane addr

---

pkg/userdata/translate/translate_v1.go
pkg/userdata/v1/networking.go

Add translation for v1 to v0 machine networking.  Also adds "Ignore"
property to v1 network interfaces.
Fixes #1134

fix: translate machine.network to networking.os

---

internal/app/ntpd/main.go

Uses NTP client constructor so that defaults are appropriately used.
Fixes #1126

fix: use ntp client constructor

---

internal/app/machined/internal/phase/network/network.go
internal/app/machined/internal/phase/rootfs/hostname.go
internal/app/machined/internal/phase/userdata/userdata.go
internal/app/machined/internal/sequencer/v1alpha1/types.go

There was an issue where the hostname was getting set too early in the boot. This caused
the hostnam retrieved from platform.Hostname() to be ignored.

fix(machined): Fix hostname value when retrieving from cloud providers

---

internal/app/machined/pkg/system/services/osd.go

Should prevent broken mounts from occurring when services are restarted.
fixes #1115 

fix(osd): Mount host directory for grpc sockets

---

hack/test/aws-setup.sh

We need to remove an exiting AMI, if it exists, in order to create a new
one with the same name.

chore: remove existing AMI

---

internal/app/machined/internal/phase/userdata/pki.go
pkg/crypto/x509/x509.go
pkg/userdata/userdata.go

This defaults certificates to a 24 hour TTL.

feat: set expiry of certificates to 24 hours

---

Makefile
internal/pkg/kernel/kernel.go

This PR will make sure that each platform gets the console settings it
needs by setting them as extra flags in the makefile. This should ensure
that we have console logs flowing properly for each cloud.

fix: move to per-platform console setup

---

Dockerfile
hack/installer/entrypoint.sh

This was required to unzip packer. We don't need it anymore.

chore: remove unneeded packages

---

hack/dev/qemu-boot.sh
internal/pkg/kernel/kernel.go
internal/pkg/kernel/kspp/kspp.go

This is the last KSPP kernel parameter we need to be compliant with KSPP
guidelines.

fix: enable slub_debug=P

---

internal/pkg/cis/cis.go
internal/pkg/installer/manifest/manifest.go

This TODO no longer applies. We have setteled on a fixed boot size. This
also removes variables no longer needed.

chore: remove invalid TODO

---

pkg/constants/constants.go

This ensures that node certificates are ephemeral by storing them in a
tmpfs.

feat: move node certificate to tmpfs

---

internal/app/machined/pkg/system/runner/runner.go
internal/app/machined/pkg/system/services/machined_api.go
internal/app/machined/pkg/system/services/osd.go
internal/app/machined/pkg/system/services/system-containerd.go

This moves the default log path to /var/log. An expection is made for
machined-api and system-containerd since they must have zero
dependencies on the ephemeral disk. In the case of machined-api, we
cannot stop the service since it is required to perform an upgrade. As
for system-containerd, it starts before any ephemeral disk is mounted so
we will fail to start the service since /var/log is a read-only file system.

fix: use /var/log for default log path

---

Dockerfile
hack/golang/golangci-lint.yaml

New linter 'funlen' was disabled as too many functions break the default
limit, but might be considered for the future.
To limit peak memory usage, `GOGC=50` was added to the golangci-lint run
to make Go's garbage collector more aggressive. With this setting peak
seems to be around 8Gb.

chore: upgrade golancgi-lint to 1.18.0

---

Makefile

This provides a target that can be useful for developers. It will format
code according to our standards.

chore: add fmt target

---

internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/containerd_test.go
internal/app/machined/pkg/system/services/kubelet.go
internal/app/machined/pkg/system/services/kubelet_test.go
internal/app/machined/pkg/system/services/ntpd.go
internal/app/machined/pkg/system/services/ntpd_test.go
internal/app/machined/pkg/system/services/osd.go
internal/app/machined/pkg/system/services/osd_test.go
internal/app/machined/pkg/system/services/proxyd.go
internal/app/machined/pkg/system/services/proxyd_test.go
internal/app/machined/pkg/system/services/system-containerd.go
internal/app/machined/pkg/system/services/system-containerd_test.go
internal/app/machined/pkg/system/services/trustd.go
internal/app/machined/pkg/system/services/trustd_test.go
internal/app/machined/pkg/system/services/udevd_trigger.go
internal/app/machined/pkg/system/services/udevd_trigger_test.go

This moves optional interface checks to unit-tests, removing type checks
via global variable assignment.

chore: move interface type assertion to unit-tests

---

go.mod
go.sum

New release comes with bugfixes (we got some of them integrated for
not tagged release), and few interesting new assertions, including
`Eventually` for polling.
See: https://github.com/stretchr/testify/milestone/2?closed=1

chore: update github.com/stretchr/testify library to 1.4.0

---

internal/app/machined/pkg/system/services/ntpd.go

As ntpd relies on outbound networking, it makes sense to wait for
networkd.

chore: make ntpd depend on networkd

---

pkg/userdata/generate/generate.go

The default of 24 hours is much too short for the admin credentials.
This makes them expire in a year.

fix: generate client admin cert with 1 year expiry

---

hack/test/conformance.sh

This upgrade the kube-conformance image used by sonobouy to
v1.16.0-rc.2.

chore: upgrade conformange image

---

internal/app/osd/internal/reg/reg.go

This is not the best solution to this, but it stops the bleeding. We can
conditionally build the log base path based on the service logs
requested.

fix: conditionally set log path

---

internal/app/machined/internal/phase/rootfs/var_directories.go
internal/app/machined/pkg/system/runner/runner.go
internal/app/machined/pkg/system/services/osd.go
internal/app/osd/internal/reg/reg.go
pkg/constants/constants.go

Writing system logs to /var/log breaks upgrades. The system disk unmount
fails with EBUSY. For now we can log to /run/system/log to avoid this.

fix: log system services to /run/system/log

---

CHANGELOG-0.2.md

This is the official v0.2.0-beta.0 release.

chore: prepare release v0.2.0-beta.0

---

.drone.yml
hack/drone.jsonnet

We no longer need to wait for the installer image to be pushed before
creating the AWS image.

chore: fix AWS image dependency

---

internal/app/machined/internal/runtime/initializer/metal/metal.go

Check that the userdata has an Install section before trying to use it
Fixes #1186

fix(machined): add nil checks to metal initializer

---

Dockerfile

This adds CONFIG_NETFILTER_XT_TARGET_CT=y to the kernel.

fix: add kerenel config required by Cilium

---

Dockerfile

This adds a label to the installer image that indicates the version. We
can build automation around this in a number of different ways, but one
of the use cases we have immediately is to use this label to determine
which version of Talos is at a given channel. For example, if we were to
implement an "edge" channel, we could periodically check for an image
with the tag "edge" and use the version label to determine if a node is
running the current version of edge. Even if we don't use the labels for our
channel implementation, its' still useful information to have.

chore: add version label to installer image

---

CHANGELOG-0.2.md

This is the official v0.2.0-rc.0 release.
(cherry picked from commit db05c65fc9697d9e119cf36f983d3b273ee0bdc3)

chore: prepare release v0.2.0-rc.0

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.0 release.

chore: prepare release v0.3.0-alpha.0

---

.drone.yml
hack/drone.jsonnet

The changes we needed in the clone plugin have been merged. We should
use the official plugin to minimize what we have to maintain.

chore: use the official Drone git plugin

---

docs/proposals/20190708-MachineConfig.md
internal/app/machined/pkg/system/services/kubeadm/kubeadm.go
internal/pkg/cis/cis.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/init.go
pkg/userdata/kubernetes_security.go
pkg/userdata/translate/translate_v1alpha1.go
pkg/userdata/v1alpha1/cluster_config.go
pkg/userdata/v1alpha1/generate/controlplane.go
pkg/userdata/v1alpha1/generate/generate.go
pkg/userdata/v1alpha1/generate/init.go

This change allows us to generate the EncryptionConfig on each
controlplane node. The benefit is that we no longer need to distibute
the EncryptionConfig via trustd.

feat: add aescbcEncryptionSecret field to machine config

---

internal/app/machined/pkg/system/services/kubeadm/kubeadm.go
internal/pkg/cis/cis.go
pkg/constants/constants.go

This changes the controlplane logic to write the audit policy to disk
from a common template instead of using trustd to distribute it.

feat: write audit policy instead of using trustd

---

internal/app/machined/pkg/system/services/kubeadm.go
internal/app/machined/pkg/system/services/kubeadm/kubeadm.go
internal/app/machined/pkg/system/services/kubeadm/kubeadm_test.go
internal/pkg/cis/cis.go
pkg/constants/constants.go
pkg/userdata/generate/controlplane.go
pkg/userdata/generate/generate.go
pkg/userdata/generate/init.go
pkg/userdata/translate/translate_v1alpha1.go
pkg/userdata/v1alpha1/cluster_config.go
pkg/userdata/v1alpha1/generate/controlplane.go
pkg/userdata/v1alpha1/generate/generate.go
pkg/userdata/v1alpha1/generate/init.go

This removes the trustd-based PKI distribution method in favor of
kubeadm's method.

feat: use kubeadm to distribute Kubernetes PKI

---

internal/app/machined/pkg/system/services/osd.go
internal/app/osd/main.go
pkg/kubernetes/kubernetes.go

This change allows for discovery of the control plane IPs. The
motivation behind this is to remove the static IP requirement. The
endpoints are discovered by machined, and passed into OSD as arguments
in order to avoid the need to mount /var/lib/kubelet/pki.

feat: discover control plane endpoints via Kubernetes

---

internal/app/machined/pkg/system/services/kubeadm/kubeadm.go
pkg/constants/constants.go

This allows us to dynamically set in the kubeadm configuration an external etcd instance.

feat: Add kubeadm flex on etcd if service is enabled

---

Dockerfile

This PR pulls in the latest kernel container, containing v5.2.18.

chore: bump kernel to 5.2.18

---

internal/app/machined/internal/phase/platform/platform.go
internal/pkg/platform/aws/aws.go
internal/pkg/platform/azure/azure.go
internal/pkg/platform/container/container.go
internal/pkg/platform/gcp/gcp.go
internal/pkg/platform/gcp/gcp_test.go
internal/pkg/platform/iso/iso.go
internal/pkg/platform/metal/metal.go
internal/pkg/platform/packet/packet.go
internal/pkg/platform/platform.go
internal/pkg/platform/vmware/vmware.go

This introduces the functionality for discovering external addresses configured on an intance.
This allows us to automatically append these external addresses to our certificate SANs so we can
access the machines from these addresses without having to know about them ahead of time.

feat: Discover platform external addresses

---

internal/app/machined/internal/phase/userdata/pki.go

Since trustd does not rotate its' certificate in v0.2, we must generate
the default node identity certificate to 10 years. This has been fixed
in v0.3, but the implementation is too risky to cherry-pick.

fix: set default node identity cert to expire in 10 years

---

CHANGELOG-0.2.md

This is the official v0.2.0 release.

chore: prepare release v0.2.0

---

.codecov.yml
internal/app/machined/pkg/system/services/etcd.go

Adds `CommonName` and additional DNS names ( hostname, localhost ) to the peer cert

chore: Add additional cert info to etcd peer cert.

---

internal/app/machined/pkg/system/services/bootkube.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/cluster_config.go
pkg/config/types/v1alpha1/generate/init.go
pkg/constants/constants.go
pkg/net/net.go
pkg/net/net_test.go

This adds more methods to the Cluster interface that allows for more
granular control of the cluster network settings.

feat: add CNI, and pod and service CIDR to configurator

---

internal/app/machined/pkg/system/services/etcd.go

This ensures that the data directory for etcd is exists before starting
etcd.

fix: create etcd data directory

---

cmd/osctl/cmd/install_linux.go

Because `platform.Name()` returns the capitalized name but the baremetal
platform kernel commandline option expects the lowercase 'metal', we
ignore the case of the platform when doing the platform match checking
in `ostctl install`.
Fixes #1249

fix: ignore case in install platform check

---

go.mod
go.sum
internal/app/machined/internal/bootkube/bootkube.go

This brings in an updated version of our fork so that pod-checkpointer
will run properly.

fix: update bootkube fork to fix pod-checkpointer

---

cmd/osctl/cmd/cluster.go
hack/test/basic-integration.sh

The goal with the docker based cluster is to provide developers with an
easy way to run Kubernetes on their local machines. Most of the time,
they won't need more than 1 master. This defaults cluster creation to 1
master.

feat: default docker based cluster to 1 master

---

cmd/osctl/cmd/root.go

This overrides the target defined in the config if a target is
specified on the command line.

fix: set target if specified on command line

---

internal/app/machined/main.go

The builtin recover func is scoped to the current go routine, and since
our boot sequence is kicked off in its' own go routine, we were failing
to recover from panics.

fix: catch panics in boot go routine

---

cmd/osctl/cmd/cluster.go

Fixes #1251 
It can be cleared the next steps for a new user.
Signed-off-by: u5surf <u5.horie@gmail.com>

chore: Improve error messages if there is a network config overlap

---

go.mod
go.sum

When creating docker based clusters, we need to use `InternalIP` for
kubelet connections. The default is
`Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP`, but
`Hostname` doesn't work in docker because we don't depend on docker for
DNS.

fix: set kubelet-preferred-address-types to prioritize InternalIP

---

Dockerfile
cmd/osctl/cmd/install_linux.go
cmd/osctl/pkg/client/client.go
hack/golang/golangci-lint.yaml
internal/app/machined/pkg/system/runner/cri/runner.go
internal/app/machined/pkg/system/service_runner.go
internal/app/networkd/pkg/reg/reg.go
internal/pkg/containers/containerd/containerd.go
pkg/constants/constants.go

Memory usage reduced around 8-10x: now it stays stable at 1GB.
I disabled some of the new linters, and one rule which is violated a
lot.
I might make sense to go back and enable `wsl` fixing all the issues
(leaving that for another PR).

chore: bump golangci-lint to 1.20

---

pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/join.go

This PR will push the cluster network node configs for all nodes. This
is needed so that non-init nodes can know the service address range to
use for determining the IP of services like coredns.

feat: output cluster network info for all node types

---

internal/app/machined/internal/phase/platform/platform.go
pkg/config/cluster/cluster.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/cluster_config.go
pkg/config/types/v1alpha1/machine_config.go

This adds a setter for the certificate SANs and sets the hostname based
on info from the platform.

fix: update platform task to set hostname and cert SANs

---

internal/app/machined/internal/phase/config/save_config.go

Since some applications read the config from disk on startup, we need to
write the config to disk just before starting them in order to relay any
data that has been added to the config during bootup.

fix: always write the config to disk

---

internal/app/machined/pkg/system/services/etcd.go
internal/pkg/mount/mount.go
pkg/blockdevice/blockdevice.go
pkg/blockdevice/probe/probe.go
pkg/config/download.go
pkg/kubernetes/kubernetes.go
pkg/retry/constant.go
pkg/retry/constant_test.go
pkg/retry/exponential.go
pkg/retry/exponential_test.go
pkg/retry/linear.go
pkg/retry/linear_test.go
pkg/retry/options.go
pkg/retry/options_test.go
pkg/retry/retry.go

This package provides a consistent way for us to retry arbitrary logic.
It provides the following backoff algorithms:
- exponential
- linear
- constant

feat: add retry package

---

hack/test/basic-integration.sh
hack/test/e2e-integration.sh
hack/test/manifests/aws-cluster.yaml
hack/test/manifests/azure-cluster.yaml
hack/test/manifests/gcp-cluster.yaml

This PR will add the bits necessary to make use of changes to our
v1alpha1 cluster api provider for CI testing. This is needed since we've
had machine config changes.

chore: re-enable end to end tests

---

hack/test/e2e-runner.sh

This PR updates the sonobuoy version. We're currently running
conformance tests with 0.15.x

chore: update sonobuoy for conformance tests

---

pkg/config/types/v1alpha1/generate/generate.go

This generates the admin Talos certificate with an expiration of 10
years.

fix: generate admin client certificate with 10 year expiration

---

internal/app/machined/pkg/system/services/kubelet.go
internal/app/machined/pkg/system/services/osd.go
pkg/constants/constants.go
pkg/kubernetes/kubernetes.go

With the change to bootkube, kubelet.conf has changed names and is now kubelet-kubeconfig.

fix: Use correct names for kubelet config

---

pkg/config/types/v1alpha1/cluster_config.go
pkg/config/types/v1alpha1/machine_config.go

This updates any discovered CertSANs to be appended to the list provided by userdata.

fix: Make updating cert sans an append operation

---

pkg/config/types/v1alpha1/cluster_config.go

This checks is the cluster network section is nil before using it,
avoiding a panic.

fix: check if cluster network config is nil

---

internal/app/machined/pkg/system/services/osd.go

This PR will fix a bug where osd fails to start when the instances are
behind a load balancer (only one LB IP specified in machine config). For
masters, osd should be able to look to localhost anyways, and workers
will still gather the endpoints via kubernetes node lookups.

fix: use localhost for osd endpoint on masters

---

docs/content/guides/metal.md
docs/content/guides/xen.md
hack/dev/qemu-boot.sh
hack/installer/entrypoint.sh

The new kernel parameter talos.config should be used instead of
tallos.userdata.

fix: use talos.config instead of talos.userdata

---

hack/installer/entrypoint.sh

This option is required by KSPP.

fix: add slub_debug=P to ISO kernel args

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
internal/app/machined/internal/phase/services/post_boot.go
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/cluster_config.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/generate_test.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go

Since we no longer have the static IP requirement, we can update all
references to the "master IPs" to use the control plane endpoint.
This adds support for creating more than one node using the qemu-boot.sh
script.

refactor: use control plane endpoint instead of master IPs

---

Dockerfile
internal/pkg/platform/metal/metal.go
internal/pkg/runtime/initializer/metal/metal.go
pkg/constants/constants.go

This brings in a few minor improvements to the metal platform. The first
is to use talos.config=metal-iso to indicate that the machine's config
can be found in an ISO image. The second is a fix to ensure that /mnt
exists.
This adds support for creating more than one node using the qemu-boot.sh
script.

refactor: improve metal platform

---

internal/app/machined/internal/phase/rootfs/system_directory.go
internal/app/machined/pkg/system/services/machined_api.go
internal/app/machined/pkg/system/services/system-containerd.go

These services should log to the default system log path.

chore: remove custom log paths

---

internal/app/machined/internal/phase/services/start_services.go

This adds NTP and Udev to the list of services designated only for
non-container modes. We should be able to rely on the host running
Docker for accurate time and Udev information.

fix: run only essential services in container mode

---

internal/app/machined/internal/phase/services/start_services.go

Without networkd, the /etc/resolv.conf in containers causes CoreDNS to
fail with "Forwarding loop detected in "." zone." With networkd running,
we overwrite /etc/resolv.conf and avoid this. I'm not sure this is what
we want in the long run, but this will fix things for now.

fix: always run networkd

---

Dockerfile

This release comes with support for caching lint results. It should
allow for speed ups when some packages don't change between the runs, so
cached information about packages might be used instead of running
linter collect phase on the package.
In my non-scientific test:
1. Fresh: 40s
2. One file change: 15s

chore: bump golangci-lint to 1.21

---

internal/pkg/runtime/platform/metal/metal.go
internal/pkg/runtime/platform/packet/packet.go

The packet and metal platforms were erroneously set to cloud mode. This
sets them to metal.

fix: set packet and metal platform mode to metal

---

cmd/osctl/cmd/cluster.go
go.mod
go.sum
internal/app/machined/internal/phase/services/post_boot.go
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/cluster_config.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go
pkg/kubernetes/kubernetes.go

This PR moves to using the full URL for endpoint instead of trying to
hardcode 6443 in various places like we were doing.

feat: allow specifcation of full url for endpoint

---

Dockerfile
api/os/api.pb.go
api/os/api.proto
cmd/osctl/cmd/config.go
cmd/osctl/cmd/containers.go
cmd/osctl/cmd/dmesg.go
cmd/osctl/cmd/kubeconfig.go
cmd/osctl/cmd/processes.go
cmd/osctl/cmd/root.go
cmd/osctl/cmd/stats.go
cmd/osctl/pkg/client/client.go
hack/test/basic-integration.sh
internal/app/osd/internal/reg/reg.go
internal/app/osd/main.go

This enables the ability to specify additional <talos> endpoints to connect to
to pull back data.

feat(osd): Enable hitting multiple OSD endpoints

---

Makefile

Fix issue inconsistency between build-container and talos

chore: Update gitmeta to latest release

---

docs/website/pages/index.vue

This adds a feature about how Talos is ephemeral. I feel this is
important to get across to our users.

docs: add ephemeral feature note

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.2 release.

chore: prepare release v0.3.0-alpha.2

---

Dockerfile
api/machine/machine.proto
api/network/network.proto
api/os/os.proto
api/security/security.proto
api/time/time.proto

This is partially driven by the upcoming api changes, but when we tell protoc to look for api.proto,
it'll find the first match in the includes(`-I`) directive.

chore: Rename proto files into more appropriate names

---

docs/website/components/Footer.vue
docs/website/pages/index.vue

Big footers seem to be in style nowadays. This adds the CNCF log to the
footer and increases the footer height. It also moves the certified
Kubernetes log into the "What is Talos?" section.

docs: make the footer bigger

---

cmd/osctl/cmd/config.go
cmd/osctl/cmd/root.go
hack/test/basic-integration.sh
pkg/config/types/v1alpha1/config.go

We were mistakenly overwriting the control plane endpoint in the
`generate` command. This fixes that and adds a simple validation of the
endpoint field in the config. We should expand the validation to ensure
that a valid IP or DNS name have been provided.

fix: ensure control plane endpoint is set

---

pkg/retry/constant_test.go

Failure:
```
--- FAIL: Test_constantRetryer_Retry (7.00s)
--- FAIL: Test_constantRetryer_Retry/test_expected_number_of_retries (2.00s)
constant_test.go:168: expected count of 2, got 3
```
The problem is that retry interval (1s) perfectly aligns with timeout
(2s), so depending on which timer fires first, function might be called
two or three times. Fix that by extending timeout a bit so it fits one
more run and not more.
P.S. This test might be still flaky under load if function doesn't have
a chance to run (starvation). Proper fix is to use fake time in the
tests.

chore: fix flaky constant retry test

---

internal/app/machined/internal/phase/platform/platform.go

There are use cases where a Talos node will not be publicly accessible.
This treats platform external IP errors as non-fatal.

fix: create external IP failures as non-fatal

---

internal/app/machined/internal/phase/platform/platform.go
internal/app/machined/pkg/system/services/bootkube.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go

This PR fixes a bug on mac with the localhost not making it into cert
sans when doing `osctl cluster create`. Now that they're present, we're
able to use kubectl again.

fix: append localhost to cert sans if docker platform

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.3 release.

chore: prepare release v0.3.0-alpha.3

---

docs/website/README.md

Dollar signs should only be used when the command has output.

chore: fix markdown lint error

---

Dockerfile
Makefile

This also pulls in Go 1.13.3
See  talos-systems/toolchain#8, talos-systems/tools#82,
https://github.com/talos-systems/pkgs/pull/69

chore: bump tools/pkgs for toolchain refactor

---

docs/website/components/CommunityDropdown.vue
docs/website/components/Header.vue
docs/website/pages/index.vue

- tweak whitespace between sections
- fix the top menu for small screens
- fix the terminal overlapping on small screens
- tweak wording on a few of the bullet points
- clean up the display of the "certified" logo on small screens
- clean up the "features" grid on medium/large screens

docs: more whitespace, wording, and responsiveness changes

---

internal/app/machined/pkg/system/services/bootkube.go

The cluster endpoint needs to be specified in the API server's
certificate SANs.

fix: add cluster endpoint to certificate SANs

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.4 release.

chore: prepare release v0.3.0-alpha.4

---

Dockerfile

This brings in pkgs that have been built using a prefix of /usr.

chore: update pkgs SHA

---

pkg/config/types/v1alpha1/config.go

This fixes a panic by checking if the cluster endpoint is nil before
using it.

fix: check if endpoint is nil

---

go.mod
internal/app/machined/pkg/system/runner/containerd/containerd.go
internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
internal/app/machined/pkg/system/services/networkd.go
internal/app/machined/pkg/system/services/ntpd.go
internal/app/machined/pkg/system/services/osd.go
internal/app/machined/pkg/system/services/trustd.go

This removes the default privileged mode that all containers were
started with and adds the required capabilities on a per-service basis.

feat: lock down container permissions

---

docs/website/components/CommunityDropdown.vue
docs/website/components/DocumentationDropdown.vue
docs/website/components/Sidebar.vue
docs/website/content/v0.3/en/guides/metal/index.md
docs/website/nuxt.config.js

This adds a note on the usage of random.trust_cpu to get around slow
boot times due to low entropy.
Closes #1240.

docs: add note on CRNG initialization

---

docs/website/content/v0.3.en.json
docs/website/content/v0.3/en/troubleshooting/index.md
docs/website/content/v0.3/en/troubleshooting/pki.md
docs/website/docgen.config.js
docs/website/docgen.js

This adds a "Troubleshooting" section to the documention along with a
guide on generating a certificate. This covers the scenario when a
user's certificate has expired.
Closes #1274.

docs: add troubleshooting guide on common PKI scenarios

---

docs/website/pages/index.vue
docs/website/tailwind.config.js

This sets the list-style-position to inside by default, and overrides
the landing page to use outside. This way we only need to maintain the
CSS for the landing page and not all the other potential places we would
want inside in the future.

docs: fix list-style-position

---

docs/website/components/DocumentationDropdown.vue
docs/website/components/Header.vue
docs/website/components/Logo.vue
docs/website/pages/docs/_.vue

- adjust ul margin to keep the bullets inside the content area
- fix a few docs page responsiveness problems on small screens
- adjust the layout of the logo relative to the docs sidebar
- clean up some vestigial CSS classes

docs: various layout and responsiveness fixes

---

cmd/osctl/cmd/cluster/pkg/node/node.go
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/etcd/etcd.go
pkg/constants/constants.go

Since bootkube should only be ran once, we need a way to determine if it
has already been ran. This makes use of etcd to store a key-value pair
indicating that the cluster has been initialized.

fix: Avoid running bootkube on reboots

---

internal/app/machined/pkg/system/services/osd.go

This adds `CAP_DAC_READ_SEARCH`, `CAP_DAC_OVERRIDE`, and `CAP_SYSLOG`
capabilities to osd.  This fixes the ability to read dmesg and kubeconfig.
Fixes #1370 

fix(osd): Add additional capabilities for osd

---

internal/app/machined/internal/phase/upgrade/upgrade.go
internal/pkg/runtime/initializer/interactive/interactive.go
internal/pkg/runtime/initializer/metal/metal.go
internal/pkg/runtime/platform/aws/aws.go
internal/pkg/runtime/platform/azure/azure.go
internal/pkg/runtime/platform/container/container.go
internal/pkg/runtime/platform/digitalocean/digitalocean.go
internal/pkg/runtime/platform/gcp/gcp.go
internal/pkg/runtime/platform/iso/iso.go
internal/pkg/runtime/platform/metal/metal.go
internal/pkg/runtime/platform/packet/packet.go
internal/pkg/runtime/platform/vmware/vmware.go

This aligns platform names with tals.platofrm kernel arg.

refactor: align platform names with kernel args

---

internal/app/machined/internal/phase/platform/platform.go
internal/app/machined/internal/phase/upgrade/upgrade.go
internal/pkg/install/install.go
internal/pkg/runtime/initializer/cloud/cloud.go
internal/pkg/runtime/initializer/container/container.go
internal/pkg/runtime/initializer/initializer.go
internal/pkg/runtime/initializer/interactive/interactive.go
internal/pkg/runtime/initializer/metal/metal.go

By passing the runtime to the initializer we can flex on install options
better.

refactor: pass runtime to initializer

---

cmd/osctl/cmd/install_linux.go
internal/app/machined/internal/phase/upgrade/upgrade.go

Trying to be smart about whether our not an install is being performed
as part of an upgrade has proven to be error prone. This moves to
perform installs with explicit args.

fix: be explicit about installs

---

internal/pkg/installer/installer.go

This adds a timestamp to /boot/installed. It can be useful for
determining the last known successful install.

feat: add timestamp to installed file

---

internal/app/machined/pkg/system/runner/cri/runner.go
internal/app/machined/pkg/system/runner/runner.go
internal/app/osd/internal/reg/reg.go

This replaces hardcoded instances of "system" with
constants.SystemContainerdNamespace.

refactor: use constants.SystemContainerdNamespace

---

internal/app/init/main.go
internal/app/machined/internal/phase/phase.go
internal/app/machined/pkg/system/services/apid.go
internal/pkg/kmsg/kmsg.go

Since dmesg is not streamed, it becomes difficult to debug issues with
machined. This fixes that by setting up the logging of machine to go to
/dev/kmsg and to a log file.

feat: out machined logs to /dev/kmsg and file

---

internal/app/machined/internal/sequencer/v1alpha1/types.go
internal/pkg/installer/manifest/verify.go
internal/pkg/mount/manager/owned/owned.go
internal/pkg/runtime/initializer/interactive/interactive.go
internal/pkg/runtime/platform/metal/metal.go

This ensures that probed block devices are closed.

fix: stop leaking file descriptors

---

internal/app/ntpd/pkg/ntp/ntp.go
internal/app/ntpd/pkg/ntp/options.go

This moves to using the retry package for retrying NTP queries. It also
adds some additional logging that is useful when NTP queries fail.

refactor: use retry package in ntpd

---

Dockerfile

There is no need for these packages to be in the base image. This moves
to installing them using ONBUILD.
Closes #1402.

chore: install customization requirements with ONBUILD

---

internal/app/machined/internal/phase/disk/verify_availability.go
internal/app/machined/internal/sequencer/v1alpha1/types.go

This adds an extra phase to the upgrade sequence that ensures we don't
hit EBUSY when attempting to delete the ephemeral partition. This is
curucial because if we fail to do so, the disk does not have a
bootloader and we effectively destroy the machine. From the Linux man
pages: If the block device is in use by the system (e.g., mounted), open()
fails with the error EBUSY.

fix: verify system disk not in use

---

internal/app/machined/internal/phase/services/stop_services.go
internal/app/machined/internal/phase/upgrade/leave_etcd.go

We need to stop etcd earlier in the upgrade sequence to prevent machined
from trying to restart it after leaving the etcd cluster. We also need
to remove the data-dir since all the data becomes invalid once we leave
the etcd cluster.

fix: stop etcd and remove data-dir

---

internal/app/machined/pkg/system/services/osd.go

Now that the APIs have been moved, we no longer need these bind mounts.

chore: remove bind mounts from OSD

---

internal/app/machined/internal/phase/upgrade/leave_etcd.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/etcd/etcd.go

We should use 127.0.0.1 only in special cases (like when bootstrapping
the cluster). There is the potential that the local etcd member is
unhealthy and/or not responsive. This adds function for creating an etcd
client configured with all control plane node IPs in order to better
handle this case.

fix: don't use 127.0.0.1 for etcd client

---

internal/app/machined/internal/api/reg/reg.go
internal/pkg/etcd/etcd.go

This verifies that all etcd members are running before performing an
upgrade. Without this we run the risk of destroying the etcd cluster.

fix: verify that all etcd members are running before upgrading

---

internal/app/machined/internal/phase/kubernetes/cordon_and_drain.go
internal/app/machined/pkg/system/services/apid.go
pkg/kubernetes/kubernetes.go

The name helper isn't very good. This renames it to Client. A new func
was also added, NewForConfig, that will allow for the creation of the helper
client from an arbitrary Kubernetes REST config.

refactor: rename Helper to Client

---

Dockerfile
Makefile
hack/test/basic-integration.sh
internal/integration/api/api.go
internal/integration/api/version.go
internal/integration/base/api.go
internal/integration/base/base.go
internal/integration/integration_test.go
internal/integration/version_test.go

This is just first steps and core foundation.
It can be used like:
```
make integration.test
osctl cluster create
build/integration.test -test.v
```
This should run the test against the Docker instance.

test: add integration test framework

---

internal/app/machined/pkg/system/services/networkd.go
internal/app/machined/pkg/system/services/ntpd.go

Without host network namespace, networkd and ntpd didnt work properly. NTP failed to
start up because it couldnt reach the ntp servers and networkd failed to configure
the interfaces and display interface information.

fix: Add host network namespace to networkd and ntpd

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.6 release.

chore: prepare release v0.3.0-alpha.6

---

.drone.yml
Makefile
hack/drone.jsonnet
hack/test/capi.sh
hack/test/e2e-integration.sh
hack/test/e2e-runner.sh
hack/test/gcp-setup.sh
hack/test/manifests/capg-components.yaml
hack/test/manifests/gcp-cluster.yaml
hack/test/manifests/provider-components.yaml

This PR will re-enable e2e testing by using the new cluster api
bootstrap provider and various infra providers.

chore: re-enable e2e testing for gcp

---

Dockerfile
internal/integration/base/api.go
internal/integration/base/base.go
internal/integration/base/cli.go
internal/integration/base/run.go
internal/integration/cli/cli.go
internal/integration/cli/version.go
internal/integration/integration_test.go

This starts with a very simple test for `osctl version` using regexps as
output of the command depends a lot on current version.
We might use more of 'gold' matches for other commands potentially.

test: add CLI integration test

---

cmd/osctl/cmd/install_linux.go
internal/app/machined/internal/phase/phase.go
internal/app/machined/internal/phase/phase_test.go
internal/app/machined/internal/phase/rootfs/check_install.go
internal/app/machined/internal/phase/upgrade/upgrade.go
internal/app/machined/internal/sequencer/v1alpha1/types.go
internal/pkg/install/install.go
internal/pkg/installer/installer.go
internal/pkg/metadata/metadata.go
internal/pkg/runtime/initializer/interactive/interactive.go
internal/pkg/runtime/runtime.go
pkg/constants/constants.go

This introduces the notion of metadata for a node. In this initial pass
there are only two fields. A timestamp to indicate when the install was
performed, and a field to indicate if the install was performed as part
of an upgrade.

feat: add metadata file to boot partition

---

internal/app/machined/internal/phase/platform/platform.go
internal/app/machined/internal/phase/rootfs/check_install.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/installer/installer.go
internal/pkg/metadata/metadata.go

This fixes a long standing issue with upgrading the init node. We
currently have no way of knowing whether the init node should join an
existing etcd cluster, or create a new one. This makes use of the node's
metadata to determine if the node has already created the etcd cluster.

fix: conditionally create a new etcd cluster

---

internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/etcd_test.go

Fixes #1419
This is required to avoid later startup failures while trying to connect
to etcd if it hasn't actually bootstrapped.
This health check does just connectivity check, no quorum/leader checks,
as they should depend on cluster state in general.

chore: add simple health check for etcd service

---

pkg/config/types/v1alpha1/generate/generate.go
pkg/crypto/x509/x509.go

This ensures that certificates are generated with the supplied options.
Fixes #1401.

fix: pass x509 options to NewCertificateFromCSR

---

.drone.yml
Makefile
hack/drone.jsonnet
hack/test/e2e-integration.sh
hack/test/e2e-runner.sh
hack/test/manifests/aws-cluster.yaml
hack/test/manifests/azure-cluster.yaml
hack/test/manifests/gcp-cluster.yaml

Also refactored `integration-test` build as a generic step to be shared
by basic-integration and e2e-integration steps.

test: add 'integration-test' to e2e runs

---

docs/website/content/v0.3/en/configuration/v1alpha1/reference.md
internal/app/networkd/pkg/address/static.go
internal/app/networkd/pkg/networkd/netconf.go
internal/app/networkd/pkg/networkd/netconf_test.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/network_config.go

This adds support for specify nameservers in the config.

feat(networkd): Add support for custom nameservers

---

.drone.yml
Makefile
hack/drone.jsonnet
hack/test/aws-setup.sh
hack/test/capi.sh
hack/test/manifests/aws-cluster.yaml
hack/test/manifests/capa-components.yaml

This PR adds in the necessary manifests and fixes to deploy aws clusters
as part of e2e testing.

chore: re-enable e2e for aws clusters

---

Dockerfile
api/api.pb.go
internal/app/apid/main.go

This brings in the recent updates to protoc-gen-proxy to allow support
for proxying streaming api requests. We artificially limit it to only the first
target specified in the list while we work through what multi target stream
support looks like.

feat: Add support for streaming apis in apid

---

Dockerfile

This fixes import order and guarantess clean diff after `make generate`.

chore: run gofumports after protoc-gen

---

go.mod
internal/app/apid/main.go
internal/app/trustd/main.go
pkg/grpc/factory/factory.go

This installs default middleware to recover from panics (convert them to
errors) in all the grpc servers by default.
Slight refactoring to allow that as grpc can only accept Unary/Stream
interceptors only once.

fix: recover from panics in grpc servers

---

docs/website/content/v0.3/en/components/networkd.md
hack/installer/entrypoint.sh
internal/app/machined/internal/phase/network/network.go
internal/app/networkd/main.go

This allows the kernel argument `ip` to take precedence over networking configuration. Documentation for
this parameter can be found here https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt

feat: Disable networkd configuration if `ip` kernel parameter is specified

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
internal/app/ntpd/main.go
internal/app/ntpd/pkg/ntp/ntpd_test.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This introduces support for defining ntp servers via `config.machine.time.servers` parameter.

feat: Add support for defining ntp servers via config

---

internal/app/apid/main.go
internal/app/machined/internal/api/api.go
internal/app/networkd/main.go
internal/app/ntpd/main.go
internal/app/osd/main.go
internal/app/trustd/main.go
pkg/grpc/factory/factory.go
pkg/grpc/middleware/log/log.go
pkg/grpc/middleware/log/log_test.go

Logging is pretty simple and bare minimum is being logged. I believe
better logging can be provided for apid when it does fan-out, but that
is beyond the scope for the first PR.
Sample logs:
```
$ osctl-linux-amd64 logs machined-api
machined 2019/11/11 21:16:43 OK [/machine.Machine/ServiceList] 0.000ms unary Success (:authority=unix:/run/system/machined/machine.sock;content-type=application/grpc;user-agent=grpc-go/1.23.0)
machined 2019/11/11 21:17:09 Unknown [/machine.Machine/Logs] 0.000ms stream open /run/system/log/machined.log: no such file or directory (:authority=unix:/run/system/machined/machine.sock;content-type=application/grpc;user-agent=grpc-go/1.23.0)
```

feat: implement grpc request loggging

---

docs/website/content/v0.3.en.json
docs/website/content/v0.3/en/configuration/v1alpha1.md
docs/website/content/v0.3/en/customization/kernel.md
docs/website/content/v0.3/en/customization/proxy.md
pkg/config/types/v1alpha1/v1alpha1_types.go

This adds docs on how to run Talos behind a proxy.

docs: add customization guide for running behing a proxy

---

.codecov.yml
docs/website/content/v0.3/en/configuration/v1alpha1.md
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This was used by kubeadm. We no longer need it.

chore: remove CertificateKey

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.7 release.

chore: prepare release v0.3.0-alpha.7

---

internal/app/machined/internal/phase/acpi/acpi.go

The netlink package deprecated the `IsNotExist` function in favor os the
new `errors.Unwrap` and `errors.Is` functions. This moves to using
`errors.Is`.

chore: address deprecation warning from netlink package

---

internal/app/machined/internal/phase/network/network.go
internal/app/machined/internal/sequencer/v1alpha1/types.go

The name of the function was not accurate to what it does. This fixes
that.

refactor: rename initial network task func

---

docs/website/nuxt.config.js

PurgeCSS seems to be removing portions of the styles in
docs/website/assets/css. This disables it until we can figure out a
better solution.

docs: disable PurgeCSS

---

internal/app/machined/internal/phase/network/reset.go
internal/app/machined/internal/sequencer/v1alpha1/types.go
internal/app/networkd/main.go
internal/app/networkd/pkg/networkd/networkd.go

This introduces the ability to reset the network interface during the bootup sequence.
This allows for user defined static networking to be the only configuration on the
network interface instead of potentially dhcp+static.

feat: Add support for resetting the network during bootup

---

internal/app/machined/pkg/system/services/bootkube.go

This makes use of the config's control plane version to set the
hyperkube image to the expected version.

fix: use the config's cluster version for control plane image

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
internal/app/machined/pkg/system/services/etcd.go
pkg/argsbuilder/argsbuilder_args.go
pkg/argsbuilder/argsbuilder_interface.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This allows for an arbitrary set of args to be passed to etcd. Due to
the fact the we do the discovery of the current cluster state, we
blacklist initial-cluster. Additionally, we black list args that would
makes sense to modify, like the path to the certs.

feat: allow extra arguments to be passed to etcd

---

cmd/osctl/cmd/service.go

Now it shows events from last one down the oldest one.
Andrew, you wanted that :)

chore: reverse order of events in `osctl service`

---

pkg/grpc/factory/factory.go
pkg/grpc/middleware/log/log.go

Logging middleware should be the first one to log the request properly
including logging before proxy goes into action.
I had sec -> msec convertion wrong, but in the end I thought I should
replace it simply with `duration.String()` which is nicer.

fix: make logging middleware first in the list, fix duration

---

cmd/osctl/cmd/root.go
cmd/osctl/pkg/client/context.go
internal/integration/api/version.go
internal/integration/base/api.go
internal/integration/base/base.go
internal/integration/base/discovery_k8s.go
internal/integration/base/discovery_nok8s.go
internal/integration/base/k8s.go
internal/integration/flags_test.go
internal/integration/integration_test.go
internal/integration/k8s/version.go

This adds support for node discovery for API-based tests, but discovery
is based on k8s state. Discovery can be overridden if we provide a list
of node IPs as a flag.
Also adds a test for K8s API server version.

test: implement node discovery for integration tests

---

internal/pkg/install/install.go

For some reason, if the `--upgrade` flag wasn't in the form of
`--upgrade=<true|false>` (with an `=`), the flag was always true. This
adds `=` to all flags.

fix: set --upgrade flag properly on installs

---

docs/website/content/v0.3/en/components/networkd.md

Add simple examples around static addressing and assigning multiple addresses
to a single interface.

docs: Add examples to networkd

---

.gitignore
hack/test/integration/README.md
hack/test/integration/dnsmasq/talos0.conf
hack/test/integration/docker-compose.yaml
hack/test/integration/haproxy/haproxy.cfg
hack/test/integration/libvirt.sh
hack/test/integration/matchbox/groups/control-plane-1.json
hack/test/integration/matchbox/groups/control-plane-2.json
hack/test/integration/matchbox/groups/control-plane-3.json
hack/test/integration/matchbox/groups/default.json
hack/test/integration/matchbox/profiles/controlplane.json
hack/test/integration/matchbox/profiles/default.json
hack/test/integration/matchbox/profiles/init.json

This adds an integration test that can be ran on a KVM enabled Linux
machine. It makes use of docker, matchbox, dnsmasq, libvirt, and HAproxy
to create an HA cluster.

test: add integration test for full boot sequence

---

internal/integration/api/version.go

It seems to work reliably in basic-integration, but fails in e2e
(receives less responses than expected). We can re-enable once we get to
the root cause of the problem.

test: disable discovery-based test as it might break e2e

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.8 release.

chore: prepare release v0.3.0-alpha.8

---

cmd/osctl/cmd/kubeconfig.go

The kubeconfig command needs only one argument.

fix: require arg length of 1 for kubeconfig command

---

Dockerfile
internal/app/machined/internal/cni/cni.go

The common pattern is for CNIs to install everything required. I don't
think we need to do this beforehand anymore. If we end up finding that
we do we can always add it back.

refactor: remove CNI bundle

---

Dockerfile

Since we are standardizing on talos.dev everywhere else, we should align
version label with this.

refactor: rename version label

---

api/api.pb.go
api/common/common.pb.go
api/machine/machine.pb.go
api/network/network.pb.go
api/os/os.pb.go
api/security/security.pb.go
api/time/time.pb.go
cmd/osctl/cmd/processes.go
internal/app/machined/pkg/system/log/log.go
internal/app/machined/pkg/system/system.go
internal/pkg/kernel/kernel.go

Not sure if there was an update in the fmt code path, but these are the
results after running `make fmt`.
These should all be whitespace related fixes.

chore: Fix formatting ( make fmt )

---

.drone.yml
hack/drone.jsonnet

This PR removes all refs to the azure e2e/integration/conformance tests
for now, since we need to wait on some upstream CAPI fixes and the test
is currently broken.

chore: disable all azure e2e temporarily

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.9 release.

chore: prepare release v0.3.0-alpha.9

---

hack/test/integration/libvirt.sh

This is useful when developing Talos.

chore: add ability to specify custom intaller to libvirt setup

---

Dockerfile
internal/pkg/mount/manager/virtual/virtual.go

This updates the kernel to make use of a version that has IMA
measurement and appraisal enabled. It is not yet enforced. Additionally,
this adds the securityfs mount at /sys/kernel/security.

feat: enable IMA measurement and appraisal

---

internal/app/machined/internal/phase/security/ima.go

Measuring overlayfs spams the measurement logs. Since these are mostly files
in pods, we don't get a lot of benefit from measuring them. This adds a rule
to ignore overlayfs.

fix: don't measure overlayfs

---

internal/app/networkd/pkg/networkd/networkd.go

This change sets bonded devices to ignored if there is no user supplied configuration. Without
configuration, a bonded interfaces doesnt provide any value. This should speed up initial boot
times by preventing address discovery on this interface.

chore(networkd): Set bonded interfaces to ignored if we dont have any user supplied configuration.

---

.drone.yml
Makefile
hack/drone.jsonnet

This adds a step to the conformance pipeline that pushes all containers
with the tag "edge." This Will allow us to start using and edge
"channel" for upgrades.
Closes #1185.

chore: push edge tag on succesful conformance

---

go.mod
go.sum
internal/app/machined/pkg/system/services/bootkube.go

This brings in a patched version of the pod-checkpointer. It fixes a bug
that prevented the static pod-checkpointer from being scheduled,
preventing recovery of the control plane on a reboot of all control
plane nodes.

fix: recover control plane on reboot

---

internal/app/apid/main.go
internal/app/trustd/main.go
pkg/grpc/tls/provider.go
pkg/grpc/tls/tls.go

In `tls.Config`, there are two hooks for getting certificate for client
and server config. So we need separate configuration methods to
configure them both.
Required in apid to provide refreshing TLS client cert to
grpc.ClientConn.

fix: provide a way for client TLS config to use Provider

---

go.mod
go.sum

This brings in changes from upstream bootkube. It fixes an issue with
the pod-checkpointer that would cause the pod-checkpointer to fail if
the kubelet's read-only port were disabled. It also adds a dedicated
certificate for the API server's `kubelet-client-*` args, which will allow the
usage of the `authentication-token-webhook` flag in the kubelet.

chore: update bootkube

---

hack/test/conformance.sh

The `--e2e-parallel` flag seems to skip all tests when running in
certified-conformance mode. This reverts that change, and also adds a
check that fails if the conformance tests do not pass. This ensures that
we are not publishing broken versions of our edge release.

chore: fix conformance

---

go.mod
go.sum
internal/app/machined/pkg/system/services/kubelet.go

This moves to using Webhook mode instead of the default AlwaysAllow for
kubelet API authorization.

feat: enable webhook authorization mode

---

Dockerfile

This brings in the latest set of packages with the following changes:
- Linux v5.3.14
- Pinned ca-certificates (2019-11-27)

chore: upgrade packages

---

pkg/config/types/v1alpha1/v1alpha1_configurator.go

This KubeletConfig should be checked for `nil`, and initialized if
needed, before attempting to access its' fields.

fix: prevent nil pointer panic

---

internal/app/machined/internal/phase/network/network.go
internal/app/machined/internal/phase/network/reset.go
internal/app/networkd/main.go
internal/app/networkd/pkg/address/static.go
internal/app/networkd/pkg/networkd/netconf.go
internal/app/networkd/pkg/networkd/netconf_test.go
internal/app/networkd/pkg/networkd/networkd.go

This adds support for parsing/honoring the `ip=` kernel argument that can
be supplied to configure an interface on the host.

feat(networkd): Add support for kernel nfsroot arguments.

---

cmd/osctl/cmd/containers.go
cmd/osctl/cmd/dmesg.go
cmd/osctl/cmd/memory.go
cmd/osctl/cmd/processes.go
cmd/osctl/cmd/stats.go
cmd/osctl/cmd/version.go

If `osctl` invocation doesn't have `-t`, response doesn't contain
`.Metadata` field, so we need to check for it explicitly.
Some commands in osctl had this check, some didn't, now all the commands
have this check.

fix: osctl panic when metadata is nil

---

pkg/constants/constants.go

This is needed in order for integration tests to pass.

fix: update kernel version constant

---

CHANGELOG-0.3.md

This is the official v0.3.0-alpha.10 release.

chore: prepare release v0.3.0-alpha.10

---

docs/website/components/Content.vue
docs/website/components/Sidebar.vue

This changes the way the sidebar anchors are constructed, and if
there is an anchor in the URL, the Content component will render
the requested page, instead of just the top-level docs page.

feat: allow deep-linking to specific docs pages

---

internal/integration/cli/version.go

When invoked without `-t`, `osctl` shouldn't print `NODE:` anymore.
Question: how tests are passing without the fix...?

test: fix integration version test as 'NODE:' was removed

---

internal/app/machined/internal/phase/services/post_boot.go
internal/pkg/etcd/etcd.go
pkg/kubernetes/kubernetes.go

This is a simple refactor that reduces the number of arguments required
by `NewTemporaryClientFromPKI`.
Closes #1420.

refactor: simplify NewTemporaryClientFromPKI

---

docs/website/content/v0.3/en/guides/cloud/vmware.md

This PR clarifies a few nits about the vmware docs. We were referring to
alpha.2 in lots of places. I moved this to a note that just says to set
TALOS_VERSION to `v0.3.0-alpha.10` or similar. Also clarifies the path
to the ova could be any /path/to/downloaded/file.
Should close #1572 when we've gotten some extra info about the hardware
versions.

docs: clarify vmware instructions

---

cmd/osctl/cmd/version.go

This PR adds the `--client` flag to `osctl version` so that we exit
before attempting to contact the server to get its version. Will close #1363

feat: support client only version for osctl

---

cmd/osctl/cmd/logs.go
cmd/osctl/cmd/root.go

Update cli so that with multiple targets work pretty much like
`tail -f one.log two.log`.

feat: osctl logs now supports multiple targets

---

cmd/osctl/cmd/containers.go
cmd/osctl/cmd/interfaces.go
cmd/osctl/cmd/memory.go
cmd/osctl/cmd/mounts.go
cmd/osctl/cmd/processes.go
cmd/osctl/cmd/root.go
cmd/osctl/cmd/routes.go
cmd/osctl/cmd/service.go
cmd/osctl/cmd/stats.go
cmd/osctl/cmd/time.go
cmd/osctl/cmd/upgrade.go
cmd/osctl/cmd/version.go
cmd/osctl/pkg/client/client.go

This change is pretty mechanical, just wrap every API so that remote
peer address is used as default for `resp.Metadata.Hostname`.
This makes `NODE:` non-empty in all the API calls.

fix: provide peer remote address for 'NODE': as default in osctl

---

Dockerfile
hack/containerd.toml
internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/app/machined/pkg/system/runner/cri/cri_test.go
internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/system-containerd.go
internal/pkg/containers/containerd/containerd_test.go
internal/pkg/containers/cri/cri_test.go
internal/pkg/cri/cri_test.go

This configures the CRI containerd to use containerd-shim-runc-v2.
Closes #1529.

feat: use containerd-shim-runc-v2

---

internal/app/networkd/pkg/networkd/networkd.go

Kernel config should always play second to a file-based config.
Fixes #1588

fix: reverse preference order of network config

---

Dockerfile
internal/app/machined/pkg/system/runner/containerd/containerd_test.go
internal/app/machined/pkg/system/runner/cri/cri_test.go
internal/app/machined/pkg/system/services/containerd.go
internal/pkg/containers/containerd/containerd_test.go
internal/pkg/containers/cri/cri_test.go
internal/pkg/cri/cri_test.go
pkg/constants/constants.go

This changes the CRI specific containerd instance's config to a
different path.

refactor: set CRI config to /etc/cri/containerd.toml

---

internal/app/machined/internal/phase/config/extra_files.go
pkg/config/machine/machine.go

This PR introduces "op" to the extra files options. This allows for a
user to specify "append" as the op, which will create a copy of the file
specified, add the extra data provided, and bind mount over the existing
file if the file is not in the /var path. Will close #1467

feat: add ability to append to existing files with extrafiles

---

hack/test/manifests/gcp-cluster.yaml

This PR updates the disks to 100GB for hopes of better disk perf.

chore: update gcp disk sizes

---

cmd/osctl/cmd/cluster.go
internal/test-framework/cmd/basic-integration.go

In the ImagePull func comments it mentions that it is up to the caller
to handle the io.ReadCloser and close it properly. This ensures that we
do.

fix: close io.ReadCloser

---

internal/app/machined/internal/phase/rootfs/mount_shared.go

In container mode we need to mount /run as SHARED. This showed up when
running a pod that needed to get information from `/var/run/netns`. but
couldn't because the mounts from the host were not being propagated into
the container.

fix: mount /run as shared in container mode

---

pkg/retry/retry.go
pkg/retry/retry_test.go

This makes errors more descriptive in the case that a timeout occurs
when using a retry func. Today the error is simply "timeout", but that
doesn't provide anything useful to the user. It now returns a unique set of
errors that are collected through the duration of the retry.
Closes #1496.

fix: return a unique set of errors on retry failure

---

pkg/retry/linear_test.go

Retry intervals `0 + 100 + 200 + 300 + 400` ms (1000ms) align perfectly
with retry timeout (1s), so test might fire 4 or 5 retries depending on
timing.

test: fix flakey test on linear retries

---

cmd/osctl/cmd/cp.go
cmd/osctl/cmd/kubeconfig.go
cmd/osctl/cmd/root.go
cmd/osctl/pkg/client/client.go

Problem seems to be on multiple levels, and there are a bit of changes
which got mixed in from another PR (just same file changed).
Core of the issue is that `helpers.Fatalf()` calls `os.Exit()` which
terminates execution and doesn't let the `defer` and other handlers to
run. This uses Cobra feature of error propagation to pop errors through
the stack back to root command.

fix: error reporting in `osctl kubeconfig`

---

cmd/osctl/pkg/client/reply.go
cmd/osctl/pkg/client/reply_test.go
internal/integration/api/version.go
internal/integration/base/api.go
internal/integration/base/discovery_k8s.go
pkg/retry/retry.go
pkg/retry/retry_test.go

It fails on AWS, need to figure out if it's transient failure or not.
While I was there, found lots of small bugs when endpoint is
unresponsive, or target nodes are unresponsive and fixed them.
In retry formatting added `\t` so that embedded errors are better
aligned in the output (same as multierror).

test: add retries to the test which verifies cluster version

---

internal/app/networkd/pkg/address/dhcp.go

Minor fix to print out the interface name along with the failure message.

chore: Add link name to dhcp addressing error

---

internal/app/machined/pkg/system/services/bootkube.go

The getter package tries to use the netrc file to gather credentials if
none are provided when using http and https getters. This disables that
because under the hood, it uses another package (go-homedir) to try and
find the netrc file. The issue is then that go-homedir tries to invoke
getent, but that is not installed on the rootfs so the command fails.

fix: don't use netrc

---

internal/app/networkd/pkg/networkd/networkd.go

This should disregard the loopback from the hostname decision since it will always be hardcoded
to the default talos hostname.

fix(networkd): Ignore loopback interface during hostname decision.

---

internal/app/machined/internal/phase/sysctls/sysctls.go

This adds some sysctls params that are recommended by containerd.

fix: add missing sysctl params required by containerd

---

internal/app/apid/pkg/provider/tls.go
internal/app/trustd/main.go
pkg/crypto/x509/x509.go
pkg/grpc/tls/local.go
pkg/grpc/tls/provider.go
pkg/grpc/tls/remote.go
pkg/net/net.go

This adds the ability to supply additional SANs for apid and trustd.
Closes #1512.

feat: allow configurable SANs for API

---

internal/app/networkd/pkg/address/dhcp.go

If we receive a domain name from the DHCP server, append it to the
received hostname.
Fixes #1628

fix: append domainname to DHCP-sourced hostname

---

cmd/osctl/cmd/containers.go
cmd/osctl/cmd/dmesg.go
cmd/osctl/cmd/interfaces.go
cmd/osctl/cmd/memory.go
cmd/osctl/cmd/mounts.go
cmd/osctl/cmd/processes.go
cmd/osctl/cmd/routes.go
cmd/osctl/cmd/service.go
cmd/osctl/cmd/stats.go
cmd/osctl/cmd/time.go
cmd/osctl/cmd/upgrade.go
cmd/osctl/pkg/client/client.go

There are several changes which cleanup and address features of osctl,
mostly for multi-node requests:
* responses are filtered, so that client commands can print partial
failures/success responses;
* `RunE` is used in place of `Run` to propagate correct return sequence
on failures;
* cleaned up setting `targets` metadata on outgoing requests, it is set
by default in `globalCtx` already

fix: response filtering for client API, RunE for osctl

---

internal/app/networkd/pkg/address/dhcp.go

These timeouts were initially increased to handle long times for links to be ready. I think
with the updated link ready check in networkd these timers are unnecessary.

chore: Remove increased timeouts for dhcp addressing.

---

go.mod
go.sum
internal/app/machined/internal/phase/kubernetes/remove_all_pods.go
internal/app/machined/pkg/system/services/kubelet.go
internal/pkg/cri/pods.go
pkg/constants/constants.go

When we upgrade a node, we kill off all pods before performing a fresh
install. The issue with this is that we run the risk of killing the CNI
pod before we finish killing all other pods, leaving the CRI unable to
teardown the pod's networking. This works around that by first killing
any pods running without host networking so that the CNI can do its'
job, and then removing the remaining pods.

fix: kill POD network mode pods first on upgrades

---

internal/app/machined/pkg/system/services/etcd.go

This allows power users to configure etcd's initial-cluster-state. It
was originally black listed, but I found I needed this to recover the
cluster. Over time we can have better automation, and maybe blacklist
this again, but in the mean time this should be configurable.

fix: allow initial-cluster-state to be set

---

internal/app/machined/internal/phase/rootfs/mount_shared.go
internal/pkg/mount/mount.go

This adds unix.MS_REC to the shared mounts. We haven't seen any reports
of bugs yet, but in some testing I found that `Bidirectional` mounts don't
work unless the mount point is rshared.

fix: mount as rshared

---

hack/test/integration/libvirt.sh

This changes the local KVM setup to use a configurable CNI URL.

chore: make the CNI configurable in local KVM test

---

pkg/config/machine/machine.go

This updates the yaml keys for the bonding configuration to align with the kernel documentation.
This mostly adds in underscores to the keys.

refactor(networkd): Update bond config parameters to align with kernel

---

docs/website/content/v0.3/en/guides/cloud/aws.md
docs/website/content/v0.3/en/guides/cloud/digitalocean.md
docs/website/content/v0.3/en/guides/cloud/vmware.md
docs/website/content/v0.3/en/guides/getting-started/index.md
docs/website/content/v0.3/en/guides/metal/matchbox.md

The usage of `osctl kubeconfig` has changed. This updates the docs to
reflect the change.

docs: update osctl kubeconfig references

---

cmd/osctl/cmd/upgrade.go

The old flag was `--url`, so the shorthand was naturally `-u`. Now that it
is `--image`, `-u` should be `-i`.

refactor: update --image shorthand flag to -i

---

cmd/osctl/cmd/config.go
cmd/osctl/cmd/root.go

This adds a `osctl config nodes` command that updates the talosconfig
with the specified nodes.

feat: add config nodes command

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
docs/website/content/v0.3/en/customization/proxy.md
internal/app/machined/internal/phase/config/extra_files.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/v1alpha1_types.go

Explicit over implicit is the reasoning here. I think it will be more
clear to users this way.

feat: add create and overwrite file operations

---

CHANGELOG-0.3.md

This is the official v0.3.0-beta.0 release.

chore: prepare release v0.3.0-beta.0

---

go.mod
go.sum
hack/test/integration/docker-compose.yaml
hack/test/integration/libvirt.sh
pkg/download/download.go
pkg/download/tftp.go

This adds supportr for downloading the machine config over TFTP. This
will allows users to avoid having to setup an HTTP server, and use
whatever they are using for PXE.

feat: add support for tftp download

---

cmd/osctl/cmd/install_linux.go
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/config/cluster/cluster.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

In our config we allow users to override the etcd and kubelet images,
but we don't actually make use of the fields. This ensures that user
specified images are honored.

fix: use specified kubelet and etcd images

---

cmd/osctl/cmd/cluster.go

This PR updates talos_default to talos-default so all docker container
names look the same, as well as avoiding the potential to break b/c
that's not a valid dns name.

fix: use dash for default talos cluster name in docker

---

cmd/osctl/cmd/root.go
internal/app/networkd/pkg/nic/nic.go
pkg/safepath/safepath.go
pkg/safepath/safepath_test.go

Using `SafePath` function from `runc` (but had to create local copy as
`runc` doesn't build on OS X).

fix: issues discovered by lgtm tool

---

pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go
pkg/config/types/v1alpha1/v1alpha1_validation.go

This adds some missing validation steps by using a single validation
entrypoint.

refactor: use all validation code

---

cmd/osctl/cmd/gen.go
cmd/osctl/cmd/kubeconfig.go
internal/integration/base/cli.go
internal/integration/base/run.go
internal/integration/cli/completion.go
internal/integration/cli/containers.go
internal/integration/cli/gen.go
internal/integration/cli/interfaces.go
internal/integration/cli/kubeconfig.go
internal/integration/cli/memory.go
internal/integration/cli/mounts.go
internal/integration/cli/processes.go
internal/integration/cli/restart.go
internal/integration/cli/routes.go
internal/integration/cli/services.go
internal/integration/cli/stats.go
internal/integration/cli/validate.go
internal/integration/cli/version.go

I added tests for all the commands which work reliably in container mode.
Some tests are naive, some are more sophisticated. While going
through the tests, I think I found a small bug in `osctl gen keypair`.
When we get reliable KVM tests, I can revisit and add missing
tests for time, reboot, shutdown and friends.

test: add integration tests for (most) CLI commands

---

go.mod
internal/app/machined/internal/phase/phase.go
internal/app/machined/internal/sequencer/v1alpha1/types.go

This fixes an issue where the default http client transport only reads the
environment variables once. This allows us to use a default/native network
configuration via dhcp to fetch userdata and then update the environment
after applying the configuration from userdata.

fix: Reset default http client to work around proxyEnv

---

go.mod
go.sum

This pulls in talos-systems/grpc-proxy#5.

chore: pull in latest version of grpc-proxy

---

internal/pkg/kmsg/message.go

This fixes issues like:
```
72.30.252.164: %!s(PANIC=String method: runtime error: index out of range [3] with length 2): info: [2019-12-19T22:18:19.230681635Z]: udevd[2239]: starting eudev-3.2.9
```

fix: extend list of kmsg facilities

---

go.mod
go.sum
internal/app/networkd/pkg/networkd/networkd.go
internal/app/networkd/pkg/nic/nic.go

This brings in an updated library along with some tweaks on our side to allow for
better decision making when it comes to the scope of routes. This also fixes an
issue where multiple configuration definitions for an interface were not properly
merged and instead were overwritten.

fix(networkd): Make better route scoping decisions

---

hack/release.sh

This adds functionality to update the CHANGELOG, and cherry-pick a
commit into a release branch.

chore: add more functions to the release script

---

pkg/grpc/middleware/log/log.go
pkg/grpc/middleware/log/log_test.go

This field might contain sensitive information, so better to hide it in
the logs.

fix: don't log `token` metadata field in grpc request log

---

.drone.yml
hack/drone.jsonnet

We shouldn't push latest on cron events.

chore: exclude cron events in push-latest step

---

Dockerfile

This fixes the container label to use the correct top level domain. It
was mistakenly reverted in a previous commit.

fix: use the correct TLD for the container version label

---

internal/app/machined/internal/phase/phase.go
internal/app/machined/main.go

Followup from #1680.
This also moves the setting from phases to machine.init to set it earlier in
the boot sequence to ensure that we get the defaults set properly from the
start and set it only once.

fix(machined): Add additional defaults for http transport

---

.drone.yml
Makefile
cmd/osctl/cmd/cluster.go
docs/osctl/osctl_cluster_create.md
hack/drone.jsonnet
hack/test/basic-integration.sh
hack/test/capi.sh
internal/integration/base/api.go
internal/integration/base/base.go
internal/integration/base/discovery_k8s.go
internal/integration/base/discovery_nok8s.go
internal/integration/base/k8s.go
internal/integration/integration_test.go
internal/pkg/provision/access/adapter.go
internal/pkg/provision/options.go
internal/pkg/provision/providers/docker/create.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go

Added flag to workaround CI/CD issue to use direct connection to docker
container (init node) instead of 127.0.0.1 passthrough (default is still
using 127.0.0.1).

chore: use osctl cluster --wait in basic-integration

---

.drone.yml
hack/drone.jsonnet

The GitHub release plugin doesn't allow directories, and has no way to
tell it to ignore a path. The workaround is to be explicit about what
files we want in a release.

chore: fix releases

---

internal/app/networkd/pkg/nic/nic.go

Minor fix to error string format that also uses %q instead of %s. The
quoted format helps when there are hidden characters.

fix: fix error format

---

cmd/installer/cmd/image.go
cmd/installer/cmd/root.go
internal/pkg/runtime/platform/vmware/vmware.go

This enusres that we default to using `guestinfo` for VMware's config
source, and that we use tty0 instead of ttyS0 for the console.

fix: set the correct kernel args for VMware

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.0 release.

chore: prepare release v0.4.0-alpha.0

---

.drone.yml
hack/drone.jsonnet

This updates the drone conditions to push the latest and edge tags only
for pushes to the master branch.

chore: use the correct condition for latest and edge pushes

---

.drone.yml
hack/drone.jsonnet

Now that we have a push target and push-% target, we can simplify the drone
conditions. This updates the conditions so that the latest channel updates
on pushes to master, the edge channel updates on successful nightly cron, and
an image with the standard tag is pushed in all events except pull requests.

chore: fix push events

---

.drone.yml
hack/drone.jsonnet

The GitHub release should depend on the push step instead of
push-latest.

chore: fix release dependency

---

.drone.yml
hack/drone.jsonnet

This PR will disable iso creation for now. We plan to reincorporate the
ability to use ISOs once we've researched #1722.
Will close #1442

chore: disable iso artifact creation

---

cmd/osctl/cmd/cluster.go
docs/osctl/osctl_cluster_create.md
internal/pkg/provision/access/adapter.go
internal/pkg/provision/options.go
internal/pkg/provision/providers/docker/create.go
internal/pkg/provision/providers/docker/node.go
internal/pkg/provision/providers/docker/reflect.go
internal/pkg/provision/providers/docker/result.go
internal/pkg/provision/request.go
internal/pkg/provision/result.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/options.go
pkg/config/types/v1alpha1/generate/talosconfig.go

This PR will allow users to issue `osctl config generate`, tweak the
configs to their liking, then use those configs to call `osctl cluster
create`.
Example workflow:
```
osctl config generate my-cluster https://10.5.0.2:6443 -o ./my-cluster
** tweaky tweak **
osctl cluster create --name my-cluster --input-dir "$PWD/my-cluster"
```

feat: support configurable docker-based clusters

---

pkg/config/types/v1alpha1/v1alpha1_validation.go

A minor nit on the error message if using a custom CNI and no URLs are
specified.

fix: make the CNI URL error better

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.1 release.

chore: prepare release v0.4.0-alpha.1

---

internal/app/machined/internal/phase/limits/limits.go
internal/app/machined/internal/phase/limits/limits_test.go
internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go

The default NOFILE is 1024 soft and 4096 hard. Without PAM, or a shell,
and no way to set limits in Kubernetes, out only option is to raise the
limit for all processes by raising the limit on PID 1. All processes
forked by PID 1 will inherit the limits for PID 1.

fix: raise default NOFILE limit

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/generate_test.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go

This PR will pass the configs around as structs instead of strings.
We'll be using this to do a further refactor of the cluster create
command and the configurator interface.

refactor: use config struct instead of string

---

hack/docgen/main.go

Using a well known comment (docgen: nodoc), we can now tell docgen to
ignore certain structs.

chore: allow docgen to ignore a struct

---

.drone.yml
Makefile
hack/drone.jsonnet

This adds a convenience tarball that includes vmlinuz, and initramfs.xz
in a single tarball.

chore: publish boot.tar.gz

---

internal/app/machined/internal/api/reg/reg.go
internal/app/machined/internal/phase/upgrade/upgrade.go
internal/pkg/install/install.go
internal/pkg/install/options.go

This PR will add in some code to pre-pull the installer image before we
run an upgrade of a given talos node. Additionally, this will add some
functional args to the install package to allow for specifying whether
or not to pull the installer image. This was needed since there was no
sense in pulling the installer again once we made it that far into the
upgrade process.
Will close #1606 

fix: check for installer image before proceeding with upgrade

---

hack/test/basic-integration.sh
hack/test/e2e-runner.sh

The basic integration cluster name was changed in a previous PR. This
aligns the E2E script with the new naming conventions, and mounts the
correct integration test binary.

chore: fix E2E script

---

internal/app/machined/internal/phase/acpi/acpi.go
internal/app/machined/internal/phase/acpi/acpi_test.go

This adds a check to ensure that only a button/power ACPI event can
cause a shutdown of a node.
Fixes #1748.

fix: shutdown on button/power ACPI event

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
internal/pkg/runtime/configurator.go
pkg/config/config.go
pkg/config/options.go
pkg/config/types/v1alpha1/v1alpha1_configurator_bundle.go

This PR will move to using a `ConfiguratorBundle` interface for our
various config data files. This will allow us to easily abstract away
various versions and easily get the data with functions.

refactor: use an interface for config data

---

internal/app/machined/internal/phase/acpi/acpi.go

It will be useful to see what kind of ACPI events we ignore.

chore: log ignored ACPI events

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
internal/app/machined/internal/phase/services/post_boot.go
internal/app/machined/internal/phase/services/start_services.go
internal/app/machined/internal/phase/services/stop_services.go
internal/app/machined/internal/phase/upgrade/leave_etcd.go
internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/osd.go
internal/pkg/etcd/etcd.go
internal/pkg/provision/check/default.go
internal/pkg/provision/check/kubernetes.go
internal/pkg/provision/check/options.go
internal/pkg/provision/providers/docker/node.go
internal/pkg/provision/providers/docker/reflect.go
internal/pkg/provision/request.go
internal/pkg/provision/result.go
pkg/config/config.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/generate_test.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_validation.go

We have been using two packages that define a config type and a machine
type, when really they are one and the same. This unifies the types down
to one set.

refactor: unify generate type and machine type

---

internal/pkg/etcd/etcd.go

This PR adds some simple logic to bail early in the upgrade process if
there only seems to be a single etcd node present in the cluster. This
allows us to keep from blowing up non-HA clusters if users issue an
upgrade command.
Will close #1770.

fix: refuse to upgrade if single master

---

internal/app/machined/pkg/system/services/bootkube.go

This fixes an issue where the bootkube assets directory was left over from a failed
installation.

fix: Ensure assets directory does not exist

---

go.mod
go.sum

This ensures bootkube waits until all pods and nodes are ready before tearing
down the bootstrap control plane.

fix: Update bootkube to include node ready check

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
internal/app/machined/pkg/system/services/bootkube.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This PR will add an `additionalManifests` field to the config data that
allows users to specify a list of URLs that they'd like to fetch
manifests from. These manifests will then be added to the bootkube asset
directory and applied during the bootkube service.

feat: allow additional manifests to be provided to bootkube

---

docs/osctl/osctl_cluster_create.md

The `docs` target needed to be ran.

docs: add missing docs

---

internal/app/networkd/pkg/address/dhcp.go
internal/app/networkd/pkg/networkd/networkd_test.go

This fixes a condition where a dhcp response does not provide a hostname. Previously
this would cause the default hostname ( talos-127-0-1-1 ) to be used. This catches
the condition and changes it to compute the hostname via talos-ip.

fix(networkd): Set hostname properly for dhcp when no hostname option is returned

---

internal/app/machined/internal/phase/network/network.go
internal/app/machined/pkg/system/services/networkd.go
internal/app/networkd/pkg/networkd/networkd.go

This  modifies the way the hostname gets set. Previously, we would run
through the entire addressing and resolver configuration and then set the
hostname. This is problematic because the resolver depends on the functionality
of Hostname() ( resolver configuration relies on the domainname of the host ).

fix(networkd): Fix incorrect resolver settings

---

internal/app/machined/pkg/system/services/networkd.go

This adds CAP_SYS_ADMIN to the networkd container so that we can set the
hostname and domainname. Without this we get permission denied.

fix: update newtorkd permissions

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
internal/app/machined/internal/phase/platform/platform.go
pkg/config/config.go
pkg/config/options.go
pkg/config/types/v1alpha1/generate/options.go

This PR overhauls osctl's config generate command to make use of the new
ConfigBundle implementation of the ConfiguratorBundle interface

refactor: use ConfiguratorBundle interface for config generate

---

internal/app/machined/internal/api/reg/reg.go
internal/app/machined/pkg/system/services/kubelet.go
internal/pkg/containers/image/image.go
internal/pkg/install/install.go

The kubelet fails to start if a machine's hostname is not set. If
networkd doesn't set it in time, the kubelet service fails to start.
Addionally, this adds retries to container pulls to ensure that any
temporary network failures don't cause fatal errors if we can't pull
images.

fix: stop race condition between kubelet and networkd

---

Dockerfile
Makefile

This brings in the official v0.1.0 releases of tools and pkgs.

chore: use v0.1.0 tools and pkgs

---

internal/app/machined/main.go
internal/pkg/event/event.go
internal/pkg/event/event_test.go

If we don't block, there is the potential for multiple shutdown,
reboot, and upgrade requests to be processed.

fix: block when handling bus event

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.2 release.

chore: prepare release v0.4.0-alpha.2

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
internal/app/machined/pkg/system/services/bootkube.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go
pkg/constants/constants.go

This PR allows for pod checkpointer and coredns images to be customized
for bootkube. We can already customize the hyperkube image and all other
images used by bootkube are CNI-related and can be customized with the
"custom" CNI setup.

feat: allow for bootkube images to be customized

---

go.mod
go.sum
internal/app/machined/pkg/system/services/bootkube.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go

This PR will add the new cluster name field to our bootkube options.
This allows for the generated kubeconfig to include the context-name for
the default context.

chore: update bootkube config to include cluster name

---

internal/app/machined/internal/phase/phase.go
internal/app/machined/main.go
internal/pkg/runtime/errors.go
internal/pkg/runtime/initializer/metal/metal.go

machined's main.go waits for boot sequence to finish, while metal
platform initializer tries to send a message to the event bus without
any listeners, so this is pure deadlock.
Resolve that by panicking from initializer, this aborts phase and
sequence, and leads to reboot on panic. Not really clean as it leaves
scary stacktraces in the dmesg, but it works. Cleanup might be done by
introducing error value for reboot, and ignoring it when printing the
errors.

fix: install sequence stuck on event bus

---

cmd/osctl/cmd/root.go
cmd/osctl/pkg/client/client.go
go.sum
internal/integration/base/api.go
internal/pkg/provision/access/adapter.go
pkg/kubernetes/kubernetes.go

The `client.Creds` struct was not used very often, and made using the
`client.NewClient` function impossible to use in combination with the
`RemoteRenewingFileCertificateProvider`. This modifies
`client.NewClient` to accept a `tls.Config` instead of `client.Creds`,
allowing for the use of `RemoteRenewingFileCertificateProvider` with
`client.NewClient`.

refactor: use tls.Config as client credentials

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
cmd/osctl/cmd/firecracker_launch_linux.go
cmd/osctl/cmd/root.go
cmd/osctl/pkg/client/config/path.go
docs/osctl/osctl.md
docs/osctl/osctl_cluster.md
docs/osctl/osctl_cluster_create.md
docs/osctl/osctl_cluster_show.md
internal/integration/integration_test.go
internal/pkg/provision/providers/docker/create.go
internal/pkg/provision/providers/docker/node.go
internal/pkg/provision/providers/docker/reflect.go
internal/pkg/provision/providers/docker/result.go
internal/pkg/provision/providers/firecracker/create.go
internal/pkg/provision/providers/firecracker/destroy.go
internal/pkg/provision/providers/firecracker/firecracker.go
internal/pkg/provision/providers/firecracker/launch.go
internal/pkg/provision/providers/firecracker/network.go
internal/pkg/provision/providers/firecracker/node.go
internal/pkg/provision/providers/firecracker/reflect.go
internal/pkg/provision/providers/firecracker/state.go
internal/pkg/provision/provision.go
internal/pkg/provision/request.go
internal/pkg/provision/result.go
pkg/config/config.go
pkg/config/options.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/options.go
pkg/constants/constants.go

This implements `osctl cluster destroy` for Firecracker, adds
new utility command `osctl cluser show`.
Firecracker mode now has control process for firecracker VMs, allowing
clean reboots and background operations.
Lots of small fixes to Firecracker mode, clean CNI shutdown, cleaning up
netns, etc.

test: firecracker provisioner fixes, implement cluster destroy 

---

internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go

This fixes an edge case where etcd can potentially become unresponsive,
and prevent a draining of a node. We drain the node, and then leave etcd
since all subsequent tasks do not depend on etcd in any way, and will
reduce the chances of an upgrade failure.

fix: leave etcd after draining node

---

docs/website/components/DocumentationDropdown.vue

This change updates the docs toggle menu to remove "pre-release" from
the v0.3 option.

docs: remove pre-release from v0.3 docs

---

docs/website/content/v0.3.en.json
docs/website/content/v0.3/en/customization/containerd.md
hack/containerd.toml

This PR will allow for any toml files added into `/var/cri/conf.d` to be
picked up and parsed as a containerd config. This should allow users a
nice way to add additional configs by passing extra files in machine
config like:
```
machine:
...
files:
- content: |
[metrics]
address = "0.0.0.0:11234"
path: /var/cri/conf.d/metrics.toml
op: create
```
Will close #1718.

feat: allow ability to customize containerd

---

Dockerfile

Came across an issue that mentioned `paths=source_relative` to address
the full go import path generation.
ref: https://github.com/golang/protobuf/issues/515#issuecomment-487988591

chore: Clean up generated path for protoc

---

internal/app/machined/internal/phase/phase.go
internal/pkg/install/install.go
internal/pkg/kmsg/kmsg.go
internal/pkg/kmsg/writer.go
internal/pkg/kmsg/writer_test.go

This fixes cases when large `log.Printf()` was simply lost as it exceeds
max line length (despite being multi-line string with each line below
1KB). Now console logging should be much more reliable.

fix: correctly split lines with /dev/kmsg output

---

internal/app/machined/internal/phase/disk/verify_availability.go
internal/app/machined/internal/phase/rootfs/unmount_system_disks.go

This adds a retry to checking if the system disk is in use. An extra
unix.Sync() was thrown in as an extra measure to maybe help unblock any
IO threads.

fix: retry system disk busy check

---

internal/app/networkd/pkg/networkd/netconf.go
internal/app/networkd/pkg/networkd/netconf_test.go

If nameserver is missing, `net.ParseIP` parses it as `nil` `net.IP` and
later on this `<nil>` address is pushed to `resolv.conf`.

fix: parse correctly kernel command line missing DNS config 

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.3 release.

chore: prepare release v0.4.0-alpha.3

---

internal/pkg/provision/providers/firecracker/destroy.go
internal/pkg/provision/providers/firecracker/network.go

Cleaning things up so that IP network can be re-used with another
network name (and inteface name).

chore: remove Firecracker bridge interface in osctl cluster destroy

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This implements old behavior from our initial config that allows for
specifying extra mounts for the kubelet container.

fix: implement kubelet extra mounts

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
pkg/config/types/v1alpha1/v1alpha1_types.go

This removes `extraDiskArgs` from the kubelet configuration field. This
never really was a thing.

docs: remove invalid field from docs

---

pkg/archiver/walker.go
pkg/archiver/walker_test.go

This fixes the list API to check if the requested path is a symlink, and
to follow the symlink if so.
Fixes #1823.

fix: follow symlinks

---

cmd/osctl/cmd/cluster.go
docs/osctl/osctl_cluster_create.md
go.mod
go.sum
internal/pkg/provision/providers/docker/docker.go
internal/pkg/provision/providers/firecracker/firecracker.go
internal/pkg/provision/providers/firecracker/launch.go
internal/pkg/provision/providers/firecracker/network.go
internal/pkg/provision/providers/firecracker/node.go
internal/pkg/provision/providers/firecracker/state.go
internal/pkg/provision/provision.go
internal/pkg/provision/request.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go
pkg/config/types/v1alpha1/generate/options.go
pkg/constants/constants.go
pkg/net/net.go

This removes use of private fork with custom `ip=` kernel argument
handling and switches fully to upstream version of it.
Firecracker Go SDK version is `master` + following PRs:
* https://github.com/firecracker-microvm/firecracker-go-sdk/pull/167
* https://github.com/firecracker-microvm/firecracker-go-sdk/pull/177
* https://github.com/firecracker-microvm/firecracker-go-sdk/pull/178
MTU handling support was implemented as well.
Changes:
* hostname to each node is passed via `talos.hostname=` kernel arg
* IP configuration is generated by SDK from CNI result
* fixed bugs with wrong netmask
* nameservers & MTU is passed via Talos config
* network CNI config is now not written to disk (no need to clean it up)

chore: rework firecracker code around upstream Go SDK + PRs

---

go.mod
go.sum

This PR will pull in the latest of our bootkube fork and fix a bug with
extraArgs.

chore: update bootkube fork

---

hack/test/e2e-docker.sh
hack/test/e2e-firecracker.sh
hack/test/e2e.sh
internal/integration/base/api.go
internal/integration/base/base.go
internal/integration/base/cli.go
internal/integration/cli/dmesg.go
internal/integration/integration_test.go

Integration test can optionally consume cluster state as generated by
the call to `osctl cluster create` and use it to discover nodes in
integration tests.
This means that now CLI tests can use that as discovery source, and
API/K8s tests by default as well.
Flat list of nodes is to be replaced by something more complex in the
next iteration, but it's good for this PR.
As a demo, add CLI test with multiple nodes (dmesg).

chore: provide provisioned cluster info to integration test

---

hack/test/e2e-capi.sh

This PR will bring in the latest v1alpha2-supporting release of the upstream capi provider

chore: update capi-upstream

---

.github/workflows/ok-to-test.yml
.github/workflows/promote-e2e.yml

This PR will allow us to start building out checks for slash commands,
with /test and /e2e both supported initially. I'll eventually want some
dashes in those commands, but they're not supported in the upstream
regex yet. I'll PR that later.

chore: enable slash commands in github PRs

---

internal/app/networkd/pkg/reg/reg.go
internal/app/networkd/pkg/reg/reg_test.go

This implements an actual health check for networkd. We use the arp table ( ip neighbors )
to determine if the machine is actively sending traffic. We should see at least one entry
with a REACHABLE state during normal operating conditions.

feat(networkd): Make healthcheck perform a check

---

internal/app/machined/pkg/system/services/etcd.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/net/net.go

If an IPv6 address is available, etcd should bind to `[::]` instead of
`0.0.0.0`.  This will cause etcd to listen on both IPv4 and IPv6
interfaces.
Additionally, this fixes the SAN list for the etcd certificate
generation to include the FQDN of the host.
Fixes #1842
Fixes #1843

fix: bind etcd to IPv6 if available

---

cmd/osctl/cmd/read.go
cmd/osctl/pkg/client/client.go
internal/app/machined/internal/api/reg/reg.go
internal/integration/api/reboot.go
internal/integration/base/api.go
internal/integration/k8s/version.go
internal/pkg/provision/access/adapter.go
internal/pkg/provision/check/default.go
internal/pkg/provision/check/service.go
internal/pkg/provision/options.go

Reboot test does node-by-node reboots followed by cluster health checks
(same as done by provisioner).
Fixed bug with `Read()` returning `Reader` instead of `ReadCloser`
(minor).
Allowed `bootkube` to be `Skipped` (for rebooted node).
Added support for doing checks via provided client instance.
Implemented generic capabilities to skip tests based on cluster
platform.

chore: implement reboot test

---

internal/app/machined/pkg/system/services/etcd.go

This was the only place which was still doing direct call to containerd
API, use common method to support retries.

chore: use common method to pull etcd image

---

internal/integration/api/reboot.go

Seems that with a single endpoint k8s is not able to recover (?).

test: skip reboot tests

---

Dockerfile
cmd/osctl/pkg/client/client.go
hack/golang/golangci-lint.yaml
internal/app/machined/pkg/system/runner/containerd/opts.go
internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/kubelet.go
internal/app/machined/pkg/system/services/osd.go
internal/app/machined/pkg/system/services/trustd.go
internal/app/machined/pkg/system/system.go
internal/app/networkd/pkg/nic/bond_options.go
internal/app/ntpd/pkg/ntp/options.go
internal/pkg/containers/containerd/containerd_test.go
pkg/chunker/stream/stream.go
pkg/grpc/tls/tls.go
pkg/kubernetes/kubernetes.go

`gomnd` disabled, as it complains about every number used in the code,
and `wsl` became much more thorough.

chore: update golangci-lint-1.23.3

---

go.mod
go.sum

With all our PRs merged, we can switch back to upstream version. No tag
yet, so we have to follow `master` for now.

chore: use upstream version of Firecracker Go SDK

---

.github/workflows/ok-to-test.yml
.github/workflows/promote-e2e.yml

This PR fixes a small bug I found yesterday to make sure we're fetching
the latest drone build number always.

chore: get correct drone status in github actions

---

.drone.yml
.github/workflows/promote-e2e.yml
hack/drone.jsonnet

This PR adds the necessary drone step to check for the `ok-to-test`
label before running any testing against a PR.

chore: support slash commands in drone

---

.drone.yml
hack/drone.jsonnet

This PR fixes a quick bug in CI where the ok-to-test step in drone was
running after a merge to master.

chore: only run ok-to-test when PR

---

.drone.yml

This is required so that we don't have to approve every PR in Drone.

chore: sign .drone.yml

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.4 release.

chore: prepare release v0.4.0-alpha.4

---

internal/app/networkd/pkg/networkd/networkd.go

When `ip=dhcp` (as well as a few other conditions), the
buildKernelOptions function returns empty.  In these cases, this empty
network config should not be added to the common list for iteration.
fixes #1869

fix: do not add empty netconf

---

internal/app/machined/pkg/system/services/networkd.go
internal/app/machined/pkg/system/services/osd.go
internal/app/networkd/pkg/reg/reg_test.go
internal/app/ntpd/pkg/reg/reg_test.go
internal/pkg/cri/client.go
pkg/grpc/dialer/dialer.go
pkg/grpc/dialer/dialer_test.go

The default gRPC dialer honors proxy environment variables, which causes
local unix socket connections to attempt to go through the proxy. This
fixes that by using a custom dialer.

fix: don't proxy gRPC unix connections

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/firecracker_launch_linux.go
cmd/osctl/cmd/loadbalancer_launch.go
go.mod
go.sum
internal/integration/api/reboot.go
internal/pkg/loadbalancer/loadbalancer.go
internal/pkg/loadbalancer/loadbalancer_test.go
internal/pkg/loadbalancer/upstream/upstream.go
internal/pkg/loadbalancer/upstream/upstream_test.go
internal/pkg/provision/check/service.go
internal/pkg/provision/providers/docker/docker.go
internal/pkg/provision/providers/firecracker/create.go
internal/pkg/provision/providers/firecracker/destroy.go
internal/pkg/provision/providers/firecracker/firecracker.go
internal/pkg/provision/providers/firecracker/loadbalancer.go
internal/pkg/provision/providers/firecracker/node.go
internal/pkg/provision/providers/firecracker/process.go
internal/pkg/provision/provision.go

This PR contains generic simple TCP loadbalancer code, and glue code for
firecracker provisioner to use this loadbalancer.
K8s control plane is passed through the load balancer, and Talos API is
passed only to the init node (for now, as some APIs, including
kubeconfig, don't work with non-init node).

chore: implement loadbalancer for firecracker provisioner

---

cmd/osctl/cmd/cluster.go
docs/osctl/osctl_cluster_create.md
go.mod
go.sum
internal/pkg/kernel/vmlinuz/vmlinuz.go
internal/pkg/provision/options.go
internal/pkg/provision/providers/firecracker/bootloader.go
internal/pkg/provision/providers/firecracker/create.go
internal/pkg/provision/providers/firecracker/launch.go
internal/pkg/provision/providers/firecracker/node.go
pkg/blockdevice/filesystem/vfat/filesystem.go
pkg/blockdevice/filesystem/vfat/superblock.go
pkg/blockdevice/lba/lba.go

Firecracker launches tries to open VM disk image before every boot,
parses partition table, finds boot partition, tries to read it as FAT32
filesystem, extracts uncompressed kernel from `bzImage` (firecracker
doesn't support `bzImage` yet), extracts initramfs and passes it to
firecracker binary.
This flow allows for extended tests, e.g. testing installer, upgrade and
downgrade tests, etc.
Bootloader emulation is disabled by default for now, can be enabled via
`--with-bootloader-emulation` flag to `osctl cluster create`.

chore: support bootloader emulation in firecracker provisioner

---

cmd/osctl/cmd/cluster.go
cmd/osctl/cmd/config.go
docs/osctl/osctl_cluster_create.md
docs/osctl/osctl_config_generate.md
docs/website/content/v0.3/en/configuration/v1alpha1.md
go.mod
internal/app/machined/internal/api/reg/reg.go
internal/app/machined/internal/phase/config/extra_files.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
internal/pkg/containers/cri/containerd/config.go
internal/pkg/containers/cri/containerd/config_test.go
internal/pkg/containers/cri/containerd/containerd.go
internal/pkg/containers/image/image.go
internal/pkg/containers/image/resolver.go
internal/pkg/containers/image/resolver_test.go
internal/pkg/install/install.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go
pkg/config/types/v1alpha1/generate/options.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

When images are pulled by Talos or via CRI plugin, configuration
for each registry is applied. Mirrors allow to redirect pull request to
either local registry or cached registry. Auth & TLS enable
authentication and TLS authentication for non-public registries.

feat: implement registry mirror & config for image pull

---

.drone.yml
Dockerfile
Makefile
hack/drone.jsonnet

Container images for `apid`, `networkd`, etc. are now built inside the
buildkit using the `img` tool. This means that all the dependencies are
now controlled in `buildkit` and many more stages can run in parallel
without problems (overwriting content in `_out/images`).
This also simplifies Drone configuration, as we can let buildkit handle
the dependencies. I also enabled more stages to run in parallel.

chore: build app container images skipping export to host 

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.5 release.

chore: prepare release v0.4.0-alpha.5

---

pkg/config/types/v1alpha1/v1alpha1_configurator.go

PodCIDRs and ServiceCIDRs are now returned as comma-delimited set of
their slices, as per the documenation for kube-api-server and
kube-controller-manager in dual-stack configurations.
Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#enable-ipv4-ipv6-dual-stack
Fixes #1883

fix: PodCIDR, ServiceCIDR should be comma sets

---

pkg/config/types/v1alpha1/v1alpha1_validation.go

This adds a check that verifies the install disk in metal mode. The
check requires a value, and that the path is valid.

fix: validate install disk

---

cmd/osctl/cmd/cluster.go
internal/pkg/provision/request.go

Not sure how it got into `ClusterRequest`, but we're not using it.

chore: remove KubernetesVersion from provision request

---

.drone.yml
Makefile
hack/drone.jsonnet
hack/test/e2e-firecracker.sh

This enables a way to run the matching installer image in firecracker
tests.

chore: push installer & talos images to the CI registry on every build

---

internal/pkg/provision/providers/firecracker/launch.go

When inner function was added, `return nil` was not aborting launch
sequence, but rather leading to VM restart. `cluster destroy` still
worked fine, as it removes state directory and launcher exits on
failure.

fix: stop firecracker launcher on signal

---

go.mod
go.sum
internal/pkg/runtime/platform/metal/metal.go

This allows users to specify well known query parameters in `talos.config`.
The only supported parameter in this change is `uuid`. This will send
the node's UUID determined from SMBIOS along with the request for the
config.

feat: support sending machine info

---

cmd/osctl/cmd/reset.go
docs/osctl/osctl_reset.md

This exposes the reboot option for thee reset API by adding a `--reboot`
flag to the CLI.

fix: add reboot flag to reset command

---

Makefile

This allows building when http(s) proxy is enforced to download content on the build machine

feat: support proxy in docker buildx

---

internal/pkg/containers/image/resolver.go

Fixes #1901
This is same fix as #1680, #1690, but applied to image resolver code.
Default HTTP client can't be used here, as custom TLS client config
might be set on the transport to authenticate to the registry.

fix: refresh proxy settings from environment in image resolver

---

pkg/net/net.go

This is backport of
https://github.com/talos-systems/talos/commit/fae5e6915d32c41b464978baf7ba335264963e58#diff-da3509c3f67d46ea31daf53392216e68.
This fixes `etcd` bootstrap with firecracker provisioner, as firecracker
provisions link-local addresses on each node and `etcd` code might pick
them up instead of real interface address.

fix: ignore link-local and other non routable addresses

---

.drone.yml
Dockerfile
Makefile
hack/drone.jsonnet
hack/test/provision-tests.sh
internal/integration/base/flags.go
internal/integration/integration_test.go
internal/integration/provision/provision.go
internal/integration/provision/upgrade.go
pkg/constants/constants.go

This class of tests is included/excluded by build tags, but as it is
pretty different from other integration tests, we build it as separate
executable. Provision tests provision cluster for the test run, perform
some actions and verify results (could be upgrade, reset, scale up/down,
etc.)
There's now framework to implement upgrade tests, first of the tests
tests upgrade from latest 0.3 (0.3.2 at the moment) to current version
of Talos (being built in CI). Tests starts by booting with 0.3
kernel/initramfs, runs 0.3 installer to install 0.3.2 cluster, wait for
bootstrap, followed by upgrade to 0.4 in rolling fashion. As Firecracker
supports bootloader, this boots 0.4 system from boot disk (as installed
by installer).

test: implement new class of tests: provision tests (upgrades)

---

internal/app/machined/internal/phase/disk/verify_availability.go
internal/app/machined/internal/phase/rootfs/unmount_system_disk_bind_mounts.go
internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go

Bind mounts created by `machine.File` section of the config (e.g. when
appending to config outside of `/var`) are not unmounted with other
flows and keep ephemeral disk busy.
New task processes such mounts and unmounts them. Also added debugging
dump of `/proc/mounts` on system disk busy error.

fix: unmount bind mounts for system (fixes upgrade stuck on disk busy)

---

internal/app/machined/pkg/system/services/bootkube.go

Http getter library is by default using it's own client. This ensure the default transport is used for fetching additional manifests.

fix: ensure proxy is used when fetching additional manifests for bootkube

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.6 release.

chore: prepare release v0.4.0-alpha.6

---

.gitignore
cmd/installer/cmd/image.go
cmd/osctl/cmd/loadbalancer_launch.go
internal/app/machined/internal/api/reg/reg.go
internal/app/machined/pkg/system/services/bootkube.go
internal/integration/provision/upgrade.go
internal/pkg/kubeconfig/admin.go
internal/pkg/kubeconfig/admin_test.go
internal/pkg/kubeconfig/kubeconfig.go
internal/pkg/provision/providers/firecracker/loadbalancer.go
internal/pkg/provision/request.go
pkg/config/cluster/cluster.go
pkg/constants/constants.go
pkg/crypto/x509/x509.go

This extracts admin kubeconfig generation out of bootkube, now based on
Talos x509 library. On each API request for `kubeconfig`, config is
generated on the fly and sent back on the wire.
This fixes two issues:
* any master node can now generate `kubeconfig` (worker nodes can do
that too, but that should probably change in the future)
* after upgrade-and-wipe the disk scenario, `osctl kubeconfig` still
works

feat: generate kubeconfig on the fly on request

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
internal/pkg/kubeconfig/admin.go
internal/pkg/kubeconfig/admin_test.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

Fixes #1906
This provides lifetime as duration relative to kubeconfig generation
time (the moment `osctl kubeconfig` was called).

feat: make admin kubeconfig cert lifetime configurable

---

cmd/osctl/cmd/gen.go
cmd/osctl/cmd/root.go

This PR fixes a bug with cert generation via `osctl gen ca`. The value
specified by the --hour flag was never being appended to the CA options
and also, since the default value for `hour` was being set on init, the
CA default was being overwritten by a subsequent command setup for the
CRT default (24h). This PR moves to using two distinct variables for
those hour values. Will fix #1911.

fix: ensure CA cert generation respects the hour flag

---

cmd/installer/cmd/install.go
cmd/osctl/cmd/validate.go
docs/website/content/v0.3/en/configuration/v1alpha1.md
internal/app/apid/main.go
internal/app/machined/internal/phase/config/config.go
internal/app/machined/internal/phase/config/save_config.go
internal/app/machined/internal/phase/rootfs/mount_system_disks.go
internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
internal/app/networkd/main.go
internal/app/ntpd/main.go
internal/app/trustd/main.go
internal/pkg/etcd/etcd.go
internal/pkg/mount/manager/owned/owned.go
internal/pkg/runtime/configurator.go
internal/pkg/runtime/initializer/cloud/cloud.go
internal/pkg/runtime/initializer/metal/metal.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go
pkg/constants/constants.go

This PR will allow users to set the `persist: true` value in their
config data to tell talos not to re-pull the config data at each reboot.
The default will still remain as a "pull every time" methodology in order
to encourage immutability by default.

feat: allow for persistence of config data

---

internal/app/machined/pkg/system/mocks_test.go
internal/app/machined/pkg/system/service.go
internal/app/machined/pkg/system/service_runner.go
internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/containerd.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/machined/pkg/system/services/kubelet.go
internal/app/machined/pkg/system/services/machined_api.go
internal/app/machined/pkg/system/services/networkd.go
internal/app/machined/pkg/system/services/ntpd.go
internal/app/machined/pkg/system/services/osd.go
internal/app/machined/pkg/system/services/routerd.go
internal/app/machined/pkg/system/services/system-containerd.go
internal/app/machined/pkg/system/services/trustd.go
internal/app/machined/pkg/system/services/udevd.go
internal/app/machined/pkg/system/services/udevd_trigger.go

This PR will allow us to take conditional actions in the postfunc of our
services by passing the state of the service into the postfunc call. We
can use this to do conditional cleanups and finalizers if success.

chore: add service state to postfunc

---

go.mod
hack/test/e2e.sh
internal/app/machined/pkg/system/services/bootkube.go
internal/integration/integration_test.go

Try more attempts, wait for the response. Treat empty response as no
error (as this is what to expect when key is not set yet).

chore: improve handling of etcd responses in bootkube pre-func

---

internal/app/machined/internal/bootkube/bootkube.go
internal/app/machined/pkg/system/services/bootkube.go
pkg/constants/constants.go

This PR will clean up bootkube assets regardless of whether bootkube
succeeds. This will allow for a failed bootkube deployment to retry on
reboot.

chore: cleanup assets dir after bootkube is done

---

internal/integration/api/reboot.go
internal/integration/api/reset.go
internal/integration/base/api.go
internal/pkg/provision/providers/firecracker/launch.go

Every node is reset, rebooted and it comes back up again except for the
init node due to known issues with init node boostrapping etcd cluster
from scratch when metadata is missing (as node was wiped).
Planned workaround is to prohibit resetting init node (should be coming
next).

test: add 'reset' integration test for Reset() API

---

internal/app/networkd/pkg/address/dhcp.go
internal/app/networkd/pkg/networkd/networkd_test.go

This fixes a case when the domain name DHCP option is set, but hostname
is missing, causing the node to be setup without a hostname.

fix: ensure hostname is never empty

---

internal/app/init/main.go
pkg/constants/constants.go

This PR allows Talos to respect the panic=0 flag if users pass that in
their kernel args. Doing this makes it easier to catch kernel panics in
debug scenarios and allows the user to manually trigger a restart with
ctrl+alt+del when they're ready.

feat: respect panic kernel flag

---

internal/app/machined/pkg/system/services/networkd.go

We need better logging on why networkd is failing the health check. This
adds logging if the debug option is set to true in the machine config.

feat: add debug logs to networkd health check

---

internal/app/networkd/pkg/networkd/misc.go
internal/app/networkd/pkg/networkd/networkd.go

This change ensures that we avoid setting up interfaces without a
carrier.

fix: skip links without a carrier

---

docs/website/content/v0.3/en/configuration/v1alpha1.md
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This PR fixes the `debug` option in the config.

fix: add debug option to v1alpha1 config

---

Dockerfile
pkg/constants/constants.go

This PR will update the base packages to the latest versions. Updated
packages are:
- ca-certificates
- cni
- iptables
- kernel
- kmod
- libseccomp
- musl
- runc
- socat
- util-linux
- xfsprogs

feat: update talos base packages

---

Dockerfile
cmd/osctl/cmd/gen.go
internal/app/apid/pkg/provider/tls.go
internal/app/machined/internal/phase/phase.go
internal/app/machined/pkg/system/runner/goroutine/goroutine.go
internal/app/machined/pkg/system/services/etcd.go
internal/app/trustd/main.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/kubernetes/kubernetes.go
pkg/startup/rand.go

This PR cleans up the formatting for various package imports as they
were causing the linter to throw errors.

chore: fix formatting of imports

---

cmd/osctl/cmd/config.go
docs/osctl/osctl_config_generate.md
go.mod
go.sum
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/kubelet.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/options.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/constants/constants.go

BREAKING CHANGE: This PR fixes a bug where we were only passing `cluster.local` to the
kubelet configuration. It will also pull in a new version of the
bootkube fork to ensure that custom domains got propogated down to the
API Server certs, as well as the CoreDNS configuration for a cluster.
Existing users should be aware that, if they were previously trying to
use this option in machine configs, that an upgrade will may break
their cluster. It will update a kubelet flag with the new domain, but
CoreDNS and API Server certs will not change since bootkube has already
run. One option may be to change these values manually inside the
Kubernetes cluster. However, it may prove easier to rebuild the cluster
if necessary.
Additionally, this PR also exposes a flag to `osctl config generate`
to …

fix: respect dns domain from machine config

---

cmd/osctl/cmd/mgmt/cluster/create.go
docs/osctl/osctl_cluster_create.md
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go
pkg/config/types/v1alpha1/generate/options.go

This enables config option 'debug: yes' which redirects service logs to
console which helps debugging cases when API is not available.

feat: add support for `--with-debug` to osctl cluster create

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.7 release.

chore: prepare release v0.4.0-alpha.7

---

internal/app/networkd/pkg/reg/reg.go

According to `rtnetlink(7)` field `state` is a bitmask of states, so
update the check to test accordingly.

fix: update rtnetlink checks for bit masks

---

internal/app/networkd/pkg/address/static.go
internal/app/networkd/pkg/networkd/netconf.go
internal/app/networkd/pkg/networkd/networkd.go
internal/app/networkd/pkg/nic/netlink.go
internal/app/networkd/pkg/nic/nic.go
internal/app/networkd/pkg/nic/nic_test.go
internal/app/networkd/pkg/nic/options.go
internal/app/networkd/pkg/nic/vars.go
internal/app/networkd/pkg/nic/vlan_options.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/v1alpha1_validation.go

- Creates VLAN devices that are configured under a certain master device
- Address and routes are added to VLAN devices
- Allows a physical device to be created without Addressing if VLANs are defined for a network interface.

feat: Add support for VLAN devices on Talos

---

docs/website/content/v0.4/en/configuration/v1alpha1.md
pkg/config/types/v1alpha1/v1alpha1_types.go

I know there is an example at the top of the page but the example mid-page was empty yaml

docs: add bare-metal install example yaml

---

Dockerfile
internal/pkg/kernel/vmlinuz/vmlinuz.go

This PR will pull in a newer kernel config that enables the
`CONFIG_USB_STORAGE` options for folks wanting to interact with USB
storage devices from talos.
Will close #1967

feat: add usb storage support

---

.drone.yml
Makefile
hack/drone.jsonnet
hack/test/e2e.sh
hack/test/provision-tests.sh
internal/app/init/main.go
internal/integration/base/base.go
internal/integration/base/cli.go
internal/integration/integration_test.go
internal/integration/provision/upgrade.go
internal/pkg/provision/access/crashdump.go
internal/pkg/provision/adapters.go

This updates upgrade tests to run two flows with 3+1 clusters:
1. 0.3 -> current (testing upgrade with partition wiping)
2. 0.4-alpha.7 -> current (testing upgrade without partition wiping,
boot-a/boot-b)
And small upgrade with preserve enabled for single-node cluster.
Provision tests are now split into two parallel tracks in Drone.

chore: update upgrade tests for new version, split into two tracks

---

go.mod
go.sum

This brings in the latest changes from our fork of bootkube. One thing
to note is a fix that stops the pod controller cache object.

feat: update bootkube

---

CHANGELOG-0.4.md

This is the official v0.4.0-alpha.8 release.

chore: prepare release v0.4.0-alpha.8

---

cmd/talosctl/cmd/mgmt/cluster/create.go
docs/talosctl/talosctl_cluster_create.md
hack/test/e2e-docker.sh
hack/test/e2e-firecracker.sh

It seems to be useful enough to be the default one and it prevents
simple mistakes while trying to access the cluster which is not ready
yet.

feat: make `--wait` default option to `talosctl cluster create`

---

cmd/installer/pkg/bootloader/syslinux/constants.go
cmd/installer/pkg/bootloader/syslinux/syslinux.go
cmd/installer/pkg/installer.go
internal/app/machined/internal/phase/rootfs/syslinux.go
internal/app/machined/main.go
internal/app/machined/pkg/system/services/etcd.go
internal/pkg/provision/providers/firecracker/bootloader.go
pkg/constants/constants.go

Since the `--once` option of `extlinux` seems to only work with BIOS, we
needed to change to remove any reliance on this option. Instead of
booting the upgraded version once, and then making it the default after
a successful boot, we now make it the default, and then revert on any
boot error.

fix: make upgrades work with UEFI

---

internal/integration/api/reboot.go
internal/integration/api/reset.go
internal/integration/cli/restart.go

This skips long-running integration tests if `-test.short` mode is
enabled.

test: mark long tests as !short

---

Dockerfile
internal/app/bootkube/assets.go
internal/app/bootkube/main.go
internal/app/machined/pkg/system/services/bootkube.go
internal/app/machined/pkg/system/services/kubelet.go

This moves `bootkube start` into container which runs pretty much like
any other Talos service.
This resolves issues with bootkube log and provides better isolation.

feat: move bootkube out as full service

---

internal/app/machined/internal/phase/rootfs/unmount_system_disks.go

Knowing which partition fails is good to know, so that we can narrow
our search for bugs.

refactor: include partition label when unmount fails

---

cmd/talosctl/cmd/mgmt/cluster/cluster.go
cmd/talosctl/cmd/mgmt/cluster/create.go
cmd/talosctl/cmd/mgmt/cluster/destroy.go
cmd/talosctl/cmd/mgmt/cluster/show.go
docs/talosctl/talosctl_cluster_create.md
internal/pkg/provision/options.go
internal/pkg/provision/providers/docker/create.go
internal/pkg/provision/providers/docker/node.go

This PR will introduce a `-p/--exposed-ports` flag to talosctl. This
flag will allow us to enable port forwards on worker nodes only. This
will allow for ingresses on docker clusters so we can hopefully use
ingress for Arges initial bootstrapping. I modeled this after how KIND allows ingresses
[here](https://kind.sigs.k8s.io/docs/user/ingress/)

feat: allow for exposing ports on docker clusters

---

cmd/installer/pkg/bootloader/syslinux/syslinux.go
internal/app/machined/main.go

We should always set the fallback tag on an upgrade, and only revert if
the tag value is not an empty string.

fix: move empty label check

---

internal/app/machined/main.go

We need to ensure that we delete the upgrade tag from the ADV even if
the tag value is an empty string.

fix: delete tag on revert with empty label

---

docs/website/content/v0.4/en/configuration/v1alpha1.md
internal/app/networkd/pkg/networkd/misc.go
internal/app/networkd/pkg/networkd/networkd.go
pkg/config/machine/machine.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

This PR will allow users to configure /etc/hosts through the network
config section, as opposed to having to use a file append operation.
Example usage might look something like:
```
...
...
machine:
...
...
network:
extraHostEntries:
- ip: 192.168.1.100
aliases:
- test
- test.wtf.bbq
...
...
```

feat: introduce ability to specify extra hosts in /etc/hosts

---

cmd/installer/pkg/installer.go
internal/app/machined/internal/api/reg/reg.go
internal/app/machined/internal/phase/security/ima.go
internal/app/machined/pkg/system/runner/containerd/import.go
internal/pkg/containers/container.go

For some places `.Close()` was clearly missing, for some of them I wanted
to be 200% sure it gets called on every code path.

fix: make sure Close() is called on every path

---

internal/integration/api/reboot.go

This PR will update the values for timeout when testing e2e. We were
hitting issues in GCP on the reboot test, as the nodes seemed to be
taking a few minutes to become responsive again. I also moved the
"cluster health" check in the node-by-node reboot test to use the
default suite context, so it'll have a timeout of 30m instead of the 5
that it had initially. This seems to solve the node-by-node bailing as
well.

chore: update timeout values for e2e tests

---

internal/app/machined/pkg/system/services/bootkube.go

Bootkube needs TLS certs to fetch TLS-protected resources (or to use
custom TLS certifcates).

fix: mount TLS certs into bootkube container

---

.github/PULL_REQUEST_TEMPLATE.md

This PR will add the ability for us to show new contributors some
protips when they open a new PR against Talos.

chore: add PR template for contributors

---

CHANGELOG-0.5.md

This is the official v0.5.0-alpha.0 release.

chore: prepare release v0.5.0-alpha.0

---

Dockerfile

**What this PR does / why we need it**:
This PR will add in the drivers for HP Smart Array RAID controllers so
that Talos users can use raid setups.

fix: add hpsa drivers

---

internal/app/machined/internal/api/reg/reg.go

This pipes the installer verification output to `/dev/null`.

refactor: don't log installer verification

---

docs/website/content/v0.4.en.json
docs/website/content/v0.4/en/guides/getting-started/docker.md
docs/website/content/v0.4/en/guides/getting-started/firecracker.md

This adds documentation on how to create clusters using the firecracker provisioner.

docs: add firecracker documentation

---

internal/pkg/provision/providers/docker/node.go
internal/pkg/provision/providers/firecracker/node.go

Due to the race, main goroutine might consume all the errors from
`errCh` and close `nodesCh`, so node goroutine might hit panic on send
to closed channel.
```
panic: send on closed channel
goroutine 40 [running]:
github.com/talos-systems/talos/internal/pkg/provision/providers/firecracker.(*provisioner).createNodes.func1(0x26ab668, 0xc00025a000, 0xc0005a83c0, 0xc00029d540, 0xc000536120, 0xc000464540, 0xc000041d80, 0x18, 0xc0006d406c, 0x4, ...)
/src/internal/pkg/provision/providers/firecracker/node.go:55 +0x1fa
created by github.com/talos-systems/talos/internal/pkg/provision/providers/firecracker.(*provisioner).createNodes
/src/internal/pkg/provision/providers/firecracker/node.go:50 +0x1ca
```

fix: resolve race condition in createNodes

---

internal/app/machined/internal/phase/services/start_containerd.go
internal/app/machined/internal/phase/services/start_services.go
internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/system/services/apid.go
internal/app/machined/pkg/system/services/cri.go
internal/app/machined/pkg/system/services/cri_test.go
internal/app/machined/pkg/system/services/networkd.go
internal/app/machined/pkg/system/services/ntpd.go
internal/app/machined/pkg/system/services/osd.go
internal/app/machined/pkg/system/services/routerd.go
internal/app/machined/pkg/system/services/system-containerd.go
internal/app/machined/pkg/system/services/system-containerd_test.go

This changes the name of the `system-containerd` service to `containerd`
and the `containerd` service to `cri`. This is so that the CRI service
is a little more generic. In the future, when we add support for other
CRIs, it will be better to refer to this service generically as "cri."

refactor: rename system-containerd and containerd services

---

Dockerfile

This change updates the pkgs tag to v0.2.0. There is no difference in
the content of the packages.

chore: update pkgs tag to v0.2.0

---

docs/website/content/v0.4/en/configuration/v1alpha1.md
internal/app/bootkube/assets.go
pkg/config/cluster/cluster.go
pkg/config/types/v1alpha1/v1alpha1_configurator.go
pkg/config/types/v1alpha1/v1alpha1_types.go

Provides capability to add extra headers in cases where files can only be fetched with token based authenction.

feat: add extra headers to fetch of extraManifests

---

internal/pkg/provision/providers/docker/docker.go
pkg/config/types/v1alpha1/generate/controlplane.go
pkg/config/types/v1alpha1/generate/generate.go
pkg/config/types/v1alpha1/generate/init.go
pkg/config/types/v1alpha1/generate/join.go
pkg/config/types/v1alpha1/generate/options.go

feat: make machine config persist by default
This PR will change the default behavior for machine configs to
`persist: true`. This seems to be expected behavior from our users so
we'll move to this method for v0.5
Will close #2023

feat: make machine config persist by default

---

internal/app/machined/pkg/system/services/kubelet.go

feat: disable kubelet ro port
This PR will remove the kubelet read only port, using the default of 0
(disabled). This will bring us closer to CIS alignment.
Will close #1731

feat: disable kubelet ro port

---

internal/app/networkd/pkg/networkd/networkd.go

fix: ensure ordering of interfaces when deciding hostname
This PR will fix some unexpected behavior where we were using Interfaces
as an unordered map, which led to varying behavior with hostname
determination. We will now go through the list of interfaces
alphabetically by name.
Will close #1927

fix: ensure ordering of interfaces when deciding hostname

---

README.md
docs/website/components/DocumentationDropdown.vue
docs/website/components/Header.vue
docs/website/pages/index.vue

This brings the v0.4 docs out of pre-release status, and updates links
to point to v0.4 docs by default.

docs: default to v0.4

---

cmd/installer/pkg/installer.go

fix: prevent formatting the ephemeral partition twice
This adds the requirement of the existence of the boot partition in the
if statement responsible for handling v0.4 style upgrades. Without this,
when upgrading from v0.3 to v0.4, we will attempt to format the
ephemeral partition twice. This will cause upgrades to fail.

fix: prevent formatting the ephemeral partition twice

---

cmd/installer/pkg/installer.go
cmd/installer/pkg/manifest/manifest.go
go.sum
internal/pkg/install/install.go
pkg/blockdevice/filesystem/xfs/xfs.go

This fixes a bug caused by a missing device argument to `mkfs.xfs`.
Without a device, `mkfs.xfs` will error out. Additionally, this ensures
that the installer container is started with the `kmsg` writer that
ensures logs are formatted correctly for `/dev/kmsg`. Without this we
lose a lot of the logs output by the container, one of them being any
error from `mkfs.xfs`

fix: pass dev path to mkfs

---

internal/app/machined/internal/phase/disk/verify_availability.go
internal/app/machined/internal/sequencer/v1alpha1/v1alpha1_sequencer.go
internal/app/machined/pkg/system/services/trustd.go

This fixes a few bugs that collectively caused `EBUSY` error when trying
to format the system disk. It ensures that we use the correct path to
the partition, and requires the path to exist. It also removes the
`/etc/kubernetes` mount from `trustd` as it was discovered that this
mount was causing the `EBUSY`.

fix: ensure disk is not busy
